### ISSUE TITLE
When in online mode, you are automatically thrown back to the last played song after changing song options

### ISSUE THREAD

**Issue by Thumbsy** [stepmania/stepmania#100]
Playing on SMO earlier today, I found that after changing your song options, you are automatically thrown back to your last played song if you navigate to another song before changing the song options.

Making any actual changes to the song options is not necessary, the 'warping' happens after you press the back button or select 'Exit' on the song options. It only happens if you started/played a song before in the same session.

**Comment by concubidated** [comment]
This is a smo server thing. Not stepmania fault.  So going to close. @Thumbsy can reproduce this on stepmaniaonline.net:8888? That will be replacing the current server.

**Comment by Thumbsy** [comment]
@concubidated I can confirm that the issue no longer exists on stepmaniaonline.net:8888, looking good!
