### ISSUE TITLE
Stepmania not reading .redir files for playing

### ISSUE THREAD

**Issue by arviejhay** [stepmania/stepmania#1000]
I downloaded stepmania 5.0.10 because i want to play. but this error shows up at the event screen after i press enter to choose the song.
The error was that the "/Noteskin/dance/de-default/Down Tap Mine.redir" points to the file "_mine.model" which doesn't exist.
after i press ignore, another error shows up "/Noteskin/dance/de-default/Down Tap Note 192nd.redir" points to the file "Down Tap Note 12th.model" which doesn't exist.
and press ignore again then its the same error and so on.
This is the crash log after i abort it.
https://www.dropbox.com/s/8sd072svi0tl8x9/Logs.rar?dl=0

**Comment by shakesoda** [comment]
It sounds like you're trying to use a noteskin which isn't compatible with SM5.

**Comment by arviejhay** [comment]
@shakesode what should i do now? do i need to downgrade my stepmania to 4? the song that i download is only for SM5. is there any options? or new update about the de-default noteskin?

**Comment by shakesoda** [comment]
Just use a new noteskin. I don't know what noteskin de-default is, but a bunch of compatible ones can be found here: http://jousway.co.uk/

**Comment by arviejhay** [comment]
@shakesoda  thank you so much! i didn't know that i can change the noteskin. sorry for this stupid issue. seems the de-default is not compatible.
