### ISSUE TITLE
Crash upon startup after install windows 10

### ISSUE THREAD

**Issue by MineCreeperLPs** [stepmania/stepmania#1001]
Static log:
StepMania5.0.10
Compiled 20151031 @ 14:38:06 (build 4b39375)
Log starting 2016-02-02 23:59:12
Loading window: win32
Windows 6.2 (Win8) build 9200 []
Memory: 2047mb total, 4095mb swap (4095mb swap avail)
Video driver: Intel(R) HD Graphics [Intel Corporation]
              9.17.10.4229, 5-27-2015 [pci\ven_8086&dev_0102]
Drive: "Hitachi HDS721010CLA630" Driver: storahci DMA: N/A
Drive: "hp      DVD A  DH16ACSH JHD6" Driver: storahci DMA: N/A
Sound device 0: Speakers (dreamGEAR ELITE Heads, 1.0, MID 65535, PID 65535 
Sound device 1: Speakers (Realtek High Definiti, 10.0, MID 1, PID 100 
DirectSound Driver: Primary Sound Driver
DirectSound Driver: Speakers (dreamGEAR ELITE Headset) {0.0.0.00000000}.{2481cf76-5cd6-46df-9e81-16a855a741c7}
DirectSound Driver: Speakers (Realtek High Definition Audio) {0.0.0.00000000}.{fc594a82-e86f-4e8f-9f4e-d58d7d7e26d2}
DirectSound sample rates: 100..200000 (continuous)
Software mixing at 44100 hz
Sound driver: DirectSound-sw
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'd3d,opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 1, 854, 480, 16, 0, 1 )
D3D Windowed 854x480 16 color 16 texture 60Hz Vsync NoSmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00010215 Instance Name: "Controller (Pro Ex mini for XBOX)" Product Name: "Controller (Pro Ex mini for XBOX)"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 3 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Controller (Pro Ex mini for XBOX)' axes: 5, hats: 1, buttons: 10 (buffered)
   2: 'Mouse' axes: 3, hats: 0, buttons: 3 (buffered)
Players joined: none
Language: en
Current renderer: Direct3D
Theme: default

**Comment by kyzentun** [comment]
Did you do anything besides run the installer when you installed stepmania?
Did you snip off the beginning of what you pasted?  Normally the crashinfo.txt has a section before the start of the static log with a stack trace.

**Comment by MineCreeperLPs** [comment]
I just put some music in the song folder and yes I did take off the stack trace repeat thing

**Comment by kyzentun** [comment]
Did it have a message that looks like this in the part you took out?
```
The folder "%s" appears to be a song folder.  All song folders must reside in a group folder.  For example, "Songs/Originals/My Song".
```

When you add songs, the songs have to be in group folders.  Then the group folder goes inside the Songs folder.

**Comment by MineCreeperLPs** [comment]
No it doesn't have that it just crashes when I try starting it up I had them put into the stepmania 5 song folder
Thread: Main thread
        RageSurface_Load_PNG.cpp:22 Reading the png file.
        RageSurface_Load_PNG.cpp:22 Reading the png file.
        RageSurface_Load_PNG.cpp:22 Reading the png file.
        RageSurface_Load_PNG.cpp:22 Reading the png file.
        RageSurface_Load_PNG.cpp:22 Reading the png file.
Thread: Decode thread
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:773 
        InputHandler_DirectInput.cpp:749 
        InputHandler_DirectInput.cpp:768 
        InputHandler_DirectInput.cpp:773 
        InputHandler_DirectInput.cpp:749 
01209579: StepMania!00d60000
01097dc9: StepMania!00d60000
0122c41a: StepMania!00d60000
0122c443: StepMania!00d60000
0122bfa7: StepMania!00d60000
0121d6fe: StepMania!00d60000
0122ce5b: StepMania!00d60000
01217faa: StepMania!00d60000
01218004: StepMania!00d60000
01217811: StepMania!00d60000
01216992: StepMania!00d60000
01216539: StepMania!00d60000
0121655e: StepMania!00d60000
012181bd: StepMania!00d60000
01097de9: StepMania!00d60000
01097dc9: StepMania!00d60000
0122c41a: StepMania!00d60000
0122c443: StepMania!00d60000
0122bfa7: StepMania!00d60000
0121d6fe: StepMania!00d60000
0122ce5b: StepMania!00d60000
01217faa: StepMania!00d60000
01218004: StepMania!00d60000
01217811: StepMania!00d60000
01216992: StepMania!00d60000
01216539: StepMania!00d60000
0121655e: StepMania!00d60000
012181bd: StepMania!00d60000
01097de9: StepMania!00d60000
01097dc9: StepMania!00d60000
0122c41a: StepMania!00d60000
0122c443: StepMania!00d60000
0122bfa7: StepMania!00d60000
0121d6fe: StepMania!00d60000
0122ce5b: StepMania!00d60000
01217faa: StepMania!00d60000
01218004: StepMania!00d60000
01217811: StepMania!00d60000
01216992: StepMania!00d60000
01216539: StepMania!00d60000
0121655e: StepMania!00d60000
012181bd: StepMania!00d60000
01097de9: StepMania!00d60000
01097dc9: StepMania!00d60000
0122c41a: StepMania!00d60000
0122c443: StepMania!00d60000
0122bfa7: StepMania!00d60000
0121d6fe: StepMania!00d60000
0122ce5b: StepMania!00d60000
01217faa: StepMania!00d60000
01218004: StepMania!00d60000
01217811: StepMania!00d60000
01216992: StepMania!00d60000
01216539: StepMania!00d60000
0121655e: StepMania!00d60000
012181bd: StepMania!00d60000
01097de9: StepMania!00d60000
01097dc9: StepMania!00d60000
0122c41a: StepMania!00d60000
0122c443: StepMania!00d60000
0122bfa7: StepMania!00d60000
0121d6fe: StepMania!00d60000
0122ce5b: StepMania!00d60000
01217faa: StepMania!00d60000
01218004: StepMania!00d60000
01217811: StepMania!00d60000
01216992: StepMania!00d60000
01216539: StepMania!00d60000
0121655e: StepMania!00d60000
012181bd: StepMania!00d60000
01097de9: StepMania!00d60000
01097dc9: StepMania!00d60000
0122c41a: StepMania!00d60000
0122c443: StepMania!00d60000
0122bfa7: StepMania!00d60000
0121d6fe: StepMania!00d60000
0122ce5b: StepMania!00d60000
01217faa: StepMania!00d60000
01218004: StepMania!00d60000
01217811: StepMania!00d60000
01216992: StepMania!00d60000
01216539: StepMania!00d60000
0121655e: StepMania!00d60000
012181bd: StepMania!00d60000
01097de9: StepMania!00d60000
01097dc9: StepMania!00d60000
0122c41a: StepMania!00d60000
0122c443: StepMania!00d60000
0122bfa7: StepMania!00d60000
0121d6fe: StepMania!00d60000
0122ce5b: StepMania!00d60000
01217faa: StepMania!00d60000
01218004: StepMania!00d60000
01217811: StepMania!00d60000
01216992: StepMania!00d60000
01216539: StepMania!00d60000
0121655e: StepMania!00d60000
012181bd: StepMania!00d60000
01097de9: StepMania!00d60000

Static log:
StepMania5.0.10
Compiled 20151031 @ 14:38:06 (build 4b39375)
Log starting 2016-02-03 02:54:42
Loading window: win32
Windows 6.2 (Win8) build 9200 []
Memory: 2047mb total, 4095mb swap (3848mb swap avail)
Video driver: Intel(R) HD Graphics [Intel Corporation]
              9.17.10.4229, 5-27-2015 [pci\ven_8086&dev_0102]
Drive: "Hitachi HDS721010CLA630" Driver: storahci DMA: N/A
Drive: "hp      DVD A  DH16ACSH JHD6" Driver: storahci DMA: N/A
Sound device 0: Speakers (dreamGEAR ELITE Heads, 1.0, MID 65535, PID 65535 
Sound device 1: Speakers (Realtek High Definiti, 10.0, MID 1, PID 100 
DirectSound Driver: Primary Sound Driver
DirectSound Driver: Speakers (dreamGEAR ELITE Headset) {0.0.0.00000000}.{2481cf76-5cd6-46df-9e81-16a855a741c7}
DirectSound Driver: Speakers (Realtek High Definition Audio) {0.0.0.00000000}.{fc594a82-e86f-4e8f-9f4e-d58d7d7e26d2}
DirectSound sample rates: 100..200000 (continuous)
Software mixing at 44100 hz
Sound driver: DirectSound-sw
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'd3d,opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 1, 854, 480, 16, 0, 1 )
D3D Windowed 854x480 16 color 16 texture 60Hz Vsync NoSmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00010215 Instance Name: "Controller (Pro Ex mini for XBOX)" Product Name: "Controller (Pro Ex mini for XBOX)"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 3 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Controller (Pro Ex mini for XBOX)' axes: 5, hats: 1, buttons: 10 (buffered)
   2: 'Mouse' axes: 3, hats: 0, buttons: 3 (buffered)
Players joined: none
Language: en
Current renderer: Direct3D
Theme: default

Partial log:
00:03.451: RageBitmapTexture: Loaded '/Themes/_fallback/Fonts/_japanese 24px [kanji 6] 8x8 (doubleres).png' (256x256); RGB5A1 matte, source 208,256;  image 208,256.
00:03.467: RageBitmapTexture: Loaded '/Themes/_fallback/Fonts/_japanese 24px [kanji 6-stroke] 8x8 (doubleres).png' (256x256); RGBA4, source 208,256;  image 208,256.
00:03.510: RageBitmapTexture: Loaded '/Themes/_fallback/Fonts/_japanese 24px [kanji 7] 8x8 (doubleres).png' (256x256); RGB5A1 matte, source 224,256;  image 224,256.
00:03.528: RageBitmapTexture: Loaded '/Themes/_fallback/Fonts/_japanese 24px [kanji 7-stroke] 8x8 (doubleres).png' (256x256); RGBA4, source 224,256;  image 224,256.
00:03.543: RageBitmapTexture: Loaded '/Themes/_fallback/Fonts/_japanese 24px [kanji 8] 8x8 (doubleres).png' (256x256); RGB5A1 matte, source 224,256;  image 224,256.
00:03.561: RageBitmapTexture: Loaded '/Themes/_fallback/Fonts/_japanese 24px [kanji 8-stroke] 8x8 (doubleres).png' (256x256); RGBA4, source 224,256;  image 224,256.
00:03.582: RageBitmapTexture: Loaded '/Themes/_fallback/Fonts/_japanese 24px [kanji 9] 8x8 (doubleres).png' (256x256); RGB5A1 matte, source 224,256;  image 224,256.
00:03.599: RageBitmapTexture: Loaded '/Themes/_fallback/Fonts/_japanese 24px [kanji 9-stroke] 8x8 (doubleres).png' (256x256); RGBA4, source 224,256;  image 224,256.
00:03.944: RageBitmapTexture: Loaded '/Themes/_fallback/Fonts/_japanese 24px [kanji-jis1] 32x32 (doubleres).png' (1024x1024); RGB5A1 matte, source 896,1024;  image 896,1024.
00:04.349: RageBitmapTexture: Loaded '/Themes/_fallback/Fonts/_japanese 24px [kanji-jis1-stroke] 32x32 (doubleres).png' (1024x1024); RGBA4, source 896,1024;  image 896,1024.

-- End of report
That's all the report I got after trying to put them into a new folder

**Comment by MineCreeperLPs** [comment]
I removed the folder with my custom songs and its the same error script

**Comment by kyzentun** [comment]
Did you install 5.0.10 on top of an old version?  Some of the font images changed, and it crashes if  the old ones are still around.

**Comment by MineCreeperLPs** [comment]
I don't belive I have an older one installed how do I check

**Comment by MineCreeperLPs** [comment]
I deleted all items and reinstalled it and it worked thanks for your help
