### ISSUE TITLE
Course Mode Bug

### ISSUE THREAD

**Issue by sillybear** [stepmania/stepmania#1020]
Every song in each course plays only the first song of the course. I believe this is caused by https://github.com/stepmania/stepmania/pull/1002

paging @blindbox

**Comment by blindbox** [comment]
Which Course? Endless, Oni, Extended?

Anyway, please give me the .sm files for the first song of the course, and any one of the other songs in the course. I need them to confirm my suspicions (I got the feeling that Stepmania drops a song from the course if it doesn't have a default 'Normal' difficulty)

**Comment by blindbox** [comment]
I've confirmed my own suspicions (it's taking in Medium difficulty as a baseline, and gives up if it can't find it). Can't give you a timeline, as the fix is not trivial.

More info is still welcomed :)

**Comment by sillybear** [comment]
Confirmed today. I just backed-up my own commit and deleted all the source code today. I made a clean new git clone and compiled a new program. The course bug is still intact. Yesterday, it was fixed by reverting it to the 2nd last commit of Course.cpp before you made changes.

**Comment by blindbox** [comment]
For now, I'm isolating Endless (which is what that commit was mainly for) to a separate function. Give me a sec, I'll have the commit ready.
