### ISSUE TITLE
"No Fakes" option doesn't remove header-defined Fakes

### ISSUE THREAD

**Issue by Kaiveran** [stepmania/stepmania#1024]
Only fake notes (F) placed in editor get removed.

Of course, since the only time you're gonna be faking whole sections is usually when they're gonna be skipped by a warp, this is almost totally inconsequential with regards to gameplay and nobody would be particularly bothered if it were never fixed, but I'm mentioning it for the sake of completeness.

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/commit/eb3121faf94903ab507befb04b4ab56fa4fc0d88
