### ISSUE TITLE
[Enhancement] Better gimmick editor (And new attack mod)

### ISSUE THREAD

**Issue by JOELwindows7** [stepmania/stepmania#1033]
The attacks that should be in the game shall also allowing the movement of the receptors, notes, and do anything as what the lua does.

There should be a new mod that moves the receptor and notes crazily

see issue #1034  for Lua stepchart
also this was a relation to issue #1015

**Comment by kyzentun** [comment]
Considering that gimmick authors have been hostile to SM5 the whole way through, so just the thought of making stuff for them irritates me.

**Comment by JOELwindows7** [comment]
Ok, I know that it would be worse impossible.

**Comment by Kingdaro** [comment]
5.1.0+ is going to have a new notefield system that'll make the old modifier/ArrowAttacks system obsolete. I think it's worth waiting for that instead and learning how to use it in the meantime.

**Comment by JOELwindows7** [comment]
@Kingdaro thx for sharing that. Yes @shakesoda had planned this right based on issue #730 I guess.

@Kyzentun , why the gimmicks irritates you? Is it because the moving away receptor makes it impossible? Did you know, e.g. School subjects getting more and more wacky and gimmick too compared in the past time. That's what my parent says, and that's true, the math is harder and harder than the same class in 1970s.

**Comment by JOELwindows7** [comment]
Wrong, issue #740, please edit above!

**Comment by JOELwindows7** [comment]
(I could not edit current comment in Mobile version, Well app is solution right?)

So, some gimmick we can accept and we can not accept. Is that right? Yes!

**Comment by Kaiveran** [comment]
Yeah, SM5.1's NewField is way more flexible and is going to be able to do more than the current system ever could.

If you check [Kyzentun's youtube](https://www.youtube.com/user/Kyzentun/videos), you'll notice that all sorts of crazy new mod/attack trickery has been accomplished, and even some older gimmick charts have been near flawlessly converted to SM5.1. So this will likely not be an issue at all going forward, in fact, I'd say it would make for many new creative possibilities.

**Comment by kyzentun** [comment]
> even some older gimmick charts have been near flawlessly converted to SM5.1.
I haven't actually converted any old gimmick charts specifically to 5.1.  "The Medley of Kirby" was converted by the xml converter that I wrote over a year ago.  It doesn't actually use any modifiers at all, so there was nothing to convert for 5.1.

"Sweet Doughnuts" and "Under Arrest" were converted by a bganimation.ini converter that I wrote in lua and lost at the same time I made the xml converter.  They also didn't use any modifiers, and thus didn't need special handling for 5.1.

**Comment by 1033Forest** [comment]
Oh look, an issue with my number on it.

Sorry for commenting on such an old issue, but where are all the old modifiers in the menu, like drunk, dizzy, confusion, flip, invert, beat, bumpy, tipsy, etc.? Will they come back in a future SM 5.1?
