### ISSUE TITLE
[Feature request] [Enhancement] Lua stepchart as the project file (Chart and gimmicks at one file)

### ISSUE THREAD

**Issue by JOELwindows7** [stepmania/stepmania#1034]
I hate clutters in a project. this happens for complex gimmick mappers
Basically, you have 3 main sets of files: stepchart, images, scripts. let's just focus 2 things
the .ssc is the stepchart you have in. you can also put attacks inside of it.
the Lua/default.lua is the gimmick script that does crazy things to the gameplays and image behaviour. you can also script to damage Stepmania game itself too. no, don't do it.

I want this to be merged into one, just .lua file

this system loads stepchart, gimmicks, images, etc. all at onces. that one, you can set a code to move a receptor based on the key command that what you can do in current .scc format.
mainly, you'll save a lot of space and time and don't have to bother with 2 different files

And when the .lua project file is finished, saving will renders these child step file for backward compatibility:
* SSC, and default,lua
* SM, and default.xml (smart quirk, using spacing and so on)(well, we're gonna do this feature right?)
* UCS for PIU
* other format according the game type the project was

[Other refference]
Until the better editor was made. There will be 3 tabs: `Chart` , `Storyboard/gimmick` , `song setup`
just like in osu!

**Comment by kyzentun** [comment]
Changing the simfile format would only bring grief from all sides.

**Comment by JOELwindows7** [comment]
Ok then. this one will be our own proprietary format, so.

**Comment by JOELwindows7** [comment]
... We do evolve more and more the SSC format into the official Project format?
just like the Adobe's behaviour (.ai, .indd, .pdf, .swf, etc.)
Do you agree? because you disagree to turn away into Lua.
While evolving cause no drastic incompatibility, instead it just adding some other tagging stuffs which make the playability still universal

**Comment by JOELwindows7** [comment]
EDIT 2: What grief would it gave for this format change? Is it format confusion?

**Comment by JOELwindows7** [comment]
@kyzentun hey dude, check out the documentation folder. have you seen @shakesoda already been concepting step chart in Lua format? still unfinished yet.

**Comment by shakesoda** [comment]
@JOELwindows7 he is well aware of that, and that it's a long-term plan. Changing formats is a major undertaking and you have to support anything you do for... pretty much forever.

Every time someone does this is a significant burden for everyone later, so it needs to be done with extreme care. We've got proposals but they will not go forward until there is a strong enough case and somebody willing to put in the time.

Further, format changes make users angry if there aren't immediate and obvious benefits. People would much rather have the shitty format they know than a better one they don't.

**Comment by JOELwindows7** [comment]
@shakesoda I should have been understand then. but how with about the newskin system? that is one of the format change too.
