### ISSUE TITLE
[Question] [Help wanted] [litterally stupid] How do we load NewSkin in 5.1...

### ISSUE THREAD

**Issue by JOELwindows7** [stepmania/stepmania#1038]
...to Test the Newskin?

regarding to an article in:
https://zenius-i-vanisher.com/v5.2/thread?threadid=7864

@kyzentun said the new system about the Newskin, and it can be loaded from the old NoteSkin option
Only, you have to enable it by adding an option to select `NewSkin` row.

I still confuse, can you give me very clear instruction where lua or ini file should be added with?

**Comment by kyzentun** [comment]
The issue tracker is not for tech support problems.

Pull the newfield_alpha2 branch from my fork and build that.  The default theme in that fork supports the newfield stuff.
