### ISSUE TITLE
Compiling under Fedora 23 fails - SOLUTION included (glew-devel was missing)

### ISSUE THREAD

**Issue by openAfre** [stepmania/stepmania#1042]
The wiki entry for installing the build dependencies for Fedora 23 should say:

dnf install libXrandr-devel libXtst-devel libpng-devel libjpeg-devel zlib-devel libogg-devel libvorbis-devel yasm alsa-lib-devel pulseaudio-libs-devel libmad-devel bzip2-devel jack-audio-connection-kit-devel libva-devel pcre-devel gtk2-devel **glew-devel** **libudev-devel**

(added glew-devel and libudev-devel which resolves to systemd-devel)

**Comment by kyzentun** [comment]
If you use Fedora 23 with a 4.x kernel, you will probably find that your dance pads do not work.  I couldn't get mine to work at all on Fedora 23, or on Debian stretch with a 4.3 kernel, but they worked when I switched to a 3.16 kernel.  I suspect the joydev kernel module or similar broke compatibility with older devices.

**Comment by openAfre** [comment]
thank you. I have good news my usb dance pads are working though. ;-)
