### ISSUE TITLE
StepMania5.0.10 crash report (build 108b297, 20151031 @ 11:58:28)

### ISSUE THREAD

**Issue by ParkYoHan** [stepmania/stepmania#1055]
StepMania5.0.10 crash report (build 108b297, 20151031 @ 11:58:28)
--------------------------------------

Architecture:   Mac OS X (i386)
Crash reason:   No playable steps for ScreenGameplaySyncMachine
Crashed thread: Main thread

Checkpoints:
Thread: GUI thread
Thread: Main thread
        SongUtil.cpp:270 Duplicate steps from Sync removed.
        SongUtil.cpp:272 Charts from Sync sorted.
        SongUtil.cpp:270 Duplicate steps from Sync removed.
        SongUtil.cpp:272 Charts from Sync sorted.
        ScreenGameplaySyncMachine.cpp:40 No playable steps for ScreenGameplaySyncMachine
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
Thread: Music thread
Thread: HAL I/O thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: Input thread

Thread: 
0068857c: CrashHandler::ForceCrash(char const*) 
0068e38a: sm_crash(char const*) 
004c7992: ScreenGameplaySyncMachine::Init() 
004c70a9: CreateScreenGameplaySyncMachine(StdString::CStdStr<char> const&) 
004dc9d4: ScreenManager::MakeNewScreen(StdString::CStdStr<char> const&) 
004de02a: ScreenManager::PrepareScreen(StdString::CStdStr<char> const&) 
004dda18: ScreenManager::LoadDelayedScreen() 
004dd5f7: ScreenManager::Update(float) 
0012dc28: GameLoop::RunGameLoop() 
005fb0ce: sm_main 
00685fdb: -[SMMain startGame:] 

Static log:
StepMania5.0.10
Compiled 20151031 @ 11:58:28 (build 108b297)
Log starting 2016-03-31 06:48:17
Loading window: macosx
Model: MacBookPro10,1 (8/8)
Clock speed 2.70 GHz
Mac OS X 10.11.4
Memory: 16.00 GB
WARNING: ReadFile(Save/ThemePrefs.ini): No such file or directory
Sound driver: AudioUnit
Lights driver: SystemMessage
Video renderers: 'opengl'
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: NVIDIA Corporation
OGL Renderer: NVIDIA GeForce GT 650M OpenGL Engine
OGL Version: 2.1 NVIDIA-10.10.5.2 310.42.25f01
OGL Max texture size: 16384
OGL Texture units: 8
GLU Version: 1.3 MacOSX
OGL Extensions:
  GL_APPLE: aux_depth_stencil, client_storage, element_array, fence, float_pixels, flush_buffer_range, 
    flush_render, object_purgeable, packed_pixels, pixel_buffer, rgb_422, row_bytes, specular_vector, 
    texture_range, transform_hint, vertex_array_object, vertex_array_range, vertex_point_size, 
    vertex_program_evaluators, ycbcr_422
  GL_ARB: color_buffer_float, depth_buffer_float, depth_clamp, depth_texture, draw_buffers, 
    draw_elements_base_vertex, draw_instanced, fragment_program, fragment_program_shadow, fragment_shader, 
    framebuffer_object, framebuffer_sRGB, half_float_pixel, half_float_vertex, imaging, instanced_arrays, 
    multisample, multitexture, occlusion_query, pixel_buffer_object, point_parameters, point_sprite, 
    provoking_vertex, seamless_cube_map, shader_objects, shader_texture_lod, shading_language_100, shadow, sync, 
    texture_border_clamp, texture_compression, texture_compression_rgtc, texture_cube_map, texture_env_add, 
    texture_env_combine, texture_env_crossbar, texture_env_dot3, texture_float, texture_mirrored_repeat, 
    texture_non_power_of_two, texture_rectangle, texture_rg, transpose_matrix, vertex_array_bgra, vertex_blend, 
    vertex_buffer_object, vertex_program, vertex_shader, window_pos
  GL_ATI: separate_stencil, texture_env_combine3, texture_float, texture_mirror_once
  GL_EXT: abgr, bgra, bindable_uniform, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, 
    blend_subtract, clip_volume_hint, debug_label, debug_marker, depth_bounds_test, draw_buffers2, 
    draw_range_elements, fog_coord, framebuffer_blit, framebuffer_multisample, 
    framebuffer_multisample_blit_scaled, framebuffer_object, framebuffer_sRGB, geometry_shader4, 
    gpu_program_parameters, gpu_shader4, multi_draw_arrays, packed_depth_stencil, packed_float, provoking_vertex, 
    rescale_normal, secondary_color, separate_specular_color, shadow_funcs, stencil_two_side, stencil_wrap, 
    texture_array, texture_compression_dxt1, texture_compression_s3tc, texture_env_add, 
    texture_filter_anisotropic, texture_integer, texture_lod_bias, texture_mirror_clamp, texture_rectangle, 
    texture_sRGB, texture_sRGB_decode, texture_shared_exponent, timer_query, transform_feedback, 
    vertex_array_bgra
  GL_IBM_rasterpos_clip
  GL_NV: blend_square, conditional_render, depth_clamp, fog_distance, fragment_program2, fragment_program_option, 
    light_max_exponent, multisample_filter_hint, point_sprite, texgen_reflection, texture_barrier, 
    vertex_program2_option, vertex_program3
  GL_SGIS: generate_mipmap, texture_edge_clamp, texture_lod
OpenGL Windowed 1422x800 32 color 32 texture 60Hz Vsync SmoothLines
WARNING: Couldn't initialize device.
WARNING: ReadFile(Save/ThemePrefs.ini): No such file or directory
Attempting to connect to: , Port: 8765
Beginning to connect
Calling EzSockets:connect()
Back from ezsockets...
WARNING: Network Sync Manager failed to connect
Attempting to connect to: 127.0.0.1, Port: 8765
Beginning to connect
Calling EzSockets:connect()
Back from ezsockets...
WARNING: Network Sync Manager failed to connect
Attempting to connect to: 127.0.0.1, Port: 8765
Beginning to connect
Calling EzSockets:connect()
Back from ezsockets...
WARNING: Network Sync Manager failed to connect
Attempting to connect to: stepmaniaonline.net, Port: 8765
Beginning to connect
Calling EzSockets:connect()
Back from ezsockets...
Server Version: 128 StepmaniaOnline.net
Mixing underruns: 1
Players joined: P1, P2
Language: en
Current renderer: OpenGL
Theme: default

Partial log:
03:29.996: RageTextureManager: deleting '/Themes/_fallback/Graphics/_blank.png'.
03:29.996: RageTextureManager: deleting '/Themes/default/Graphics/ScreenWithMenuElements header/_texture stripe (stretch).png'.
03:29.997: RageTextureManager: deleting '/Themes/_fallback/Fonts/_roboto black Bold 24px [alt] 10x10.png'.
03:29.997: RageTextureManager: deleting '/Themes/_fallback/Fonts/_roboto black Bold 24px [alt-stroke] 10x10.png'.
03:29.997: RageTextureManager: deleting '/Themes/_fallback/Fonts/_roboto black Bold 24px [main] 15x15.png'.
03:29.997: RageTextureManager: deleting '/Themes/_fallback/Fonts/_roboto black Bold 24px [main-stroke] 15x15.png'.
03:29.998: RageTextureManager: deleting '/Themes/default/Graphics/ScreenWithMenuElements header/Header.png'.
03:29.998: Performing texture garbage collection.
03:29.998: Loading screen: "ScreenGameplaySyncMachine"
03:30.006: Song::LoadFromSMFile(/Themes/default/Other/ScreenGameplaySyncMachine music.sm)

-- End of report

**Comment by kyzentun** [comment]
What game type did you have selected?

**Comment by kyzentun** [comment]
Does this crash only happen when you're connected to the online server?  If so, I think it has been fixed.
