### ISSUE TITLE
Tornado mod doesn't work correctly

### ISSUE THREAD

**Issue by YungDaVinci** [stepmania/stepmania#1056]
(5.1)
Although the arrows do still have the Tornado effect, only the first two columns of arrows are shown (left and down arrows). The last two columns, including the receptors, are completely invisible.

**Comment by kyzentun** [comment]
Looks fine to me.  http://i.imgur.com/Vu27806.jpg http://i.imgur.com/GSVx2e5.jpg
There's probably something else making the other two vanish, unrelated to tornado.
