### ISSUE TITLE
Unhandled C++ Exception

### ISSUE THREAD

**Issue by RedAgent14** [stepmania/stepmania#1061]
I'm having an issue with the 5.1.0 Alpha, with one particular theme. All of the themes work fine, expect for a DDR X2 theme I have (KenP's theme). When I get to the "select profile" screen, I get the following error:

"Crash reason: Unhandled Microsoft C++ Exception"
I've attached the crashinfo.txt file to this post.

[crashinfo.txt](https://github.com/stepmania/stepmania/files/202998/crashinfo.txt)

**Comment by kyzentun** [comment]
Fixed in this commit: https://github.com/stepmania/stepmania/commit/2b330240729eec8ea73d4ea690eb59291395b84d

Unrelated: Looks like none of the fonts used by that theme actually work.
