### ISSUE TITLE
Unable to build and run Stepmania in Win10 VS2015 Community!

### ISSUE THREAD

**Issue by shyamalschandra** [stepmania/stepmania#1063]
I am getting the following error message box.

![stepmania_error](https://cloud.githubusercontent.com/assets/9545735/14324189/7b2645a6-fbe9-11e5-868e-6e00e75fe2f5.PNG)
 
What should I do?

**Comment by jansol** [comment]
Set StepMania as the startup project. ALL_BUILD is just meta-target for building everything.

**Comment by shyamalschandra** [comment]
Thanks a lot!
