### ISSUE TITLE
[LOG] Crash on opening a simfile in edit mode after editing simfile and forgetting to reload songs

### ISSUE THREAD

**Issue by ianklatzco** [stepmania/stepmania#1064]
Made some nice blooming noises that scared the shit out of me rather later at night, hah.

Just posting the crash log. Problem appears to be that if you've edited a simfile and stepmania can't find the chart it's looking for, it crashes.

`StepMania5.0.10 crash report (build 108b297, 20151031 @ 11:58:28)
--------------------------------------

Architecture:   Mac OS X (i386)
Crash reason:   Segmentation fault - address not mapped at 0x000000bc
Crashed thread: Main thread

Checkpoints:
Thread: GUI thread
Thread: Main thread
        Screen.cpp:164 ScreenMessage(SM_UpdateTextInfo)
        Screen.cpp:164 ScreenMessage(SM_UpdateTextInfo)
        Screen.cpp:164 ScreenMessage(SM_UpdateTextInfo)
        Screen.cpp:164 ScreenMessage(SM_UpdateTextInfo)
        Screen.cpp:164 ScreenMessage(SM_BeginFadingOut)
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
Thread: Music thread
Thread: HAL I/O thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: Input thread
Thread: Streaming sound buffering

Thread: Main thread
0060278e: Steps::SetNoteData(NoteData const&) 
0060276e: Steps::SetNoteData(NoteData const&) 
0030f06c: PlayerState::Update(float) 
0043523f: ScreenEdit::Update(float) 
004dd551: ScreenManager::Update(float) 
0012dc28: GameLoop::RunGameLoop() 
005fb0ce: sm_main 
00685fdb: -[SMMain startGame:] 

Static log:
StepMania5.0.10
Compiled 20151031 @ 11:58:28 (build 108b297)
Log starting 2016-04-07 02:03:17
Loading window: macosx
Model: MacBookPro11,1 (4/4)
Clock speed 2.60 GHz
Mac OS X 10.10.5
Memory: 8.00 GB
Sound driver: AudioUnit
Lights driver: SystemMessage
Video renderers: 'opengl'
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: Intel Inc.
OGL Renderer: Intel Iris OpenGL Engine
OGL Version: 2.1 INTEL-10.6.33
OGL Max texture size: 16384
OGL Texture units: 8
GLU Version: 1.3 MacOSX
OGL Extensions:
  GL_APPLE: aux_depth_stencil, client_storage, element_array, fence, float_pixels, flush_buffer_range, 
    flush_render, object_purgeable, packed_pixels, pixel_buffer, rgb_422, row_bytes, specular_vector, 
    texture_range, transform_hint, vertex_array_object, vertex_array_range, vertex_point_size, 
    vertex_program_evaluators, ycbcr_422
  GL_ARB: color_buffer_float, depth_buffer_float, depth_clamp, depth_texture, draw_buffers, 
    draw_elements_base_vertex, draw_instanced, fragment_program, fragment_program_shadow, fragment_shader, 
    framebuffer_object, framebuffer_sRGB, half_float_pixel, half_float_vertex, instanced_arrays, multisample, 
    multitexture, occlusion_query, pixel_buffer_object, point_parameters, point_sprite, provoking_vertex, 
    seamless_cube_map, shader_objects, shader_texture_lod, shading_language_100, shadow, sync, 
    texture_border_clamp, texture_compression, texture_compression_rgtc, texture_cube_map, texture_env_add, 
    texture_env_combine, texture_env_crossbar, texture_env_dot3, texture_float, texture_mirrored_repeat, 
    texture_non_power_of_two, texture_rectangle, texture_rg, transpose_matrix, vertex_array_bgra, vertex_blend, 
    vertex_buffer_object, vertex_program, vertex_shader, window_pos
  GL_ATI: separate_stencil, texture_env_combine3, texture_float, texture_mirror_once
  GL_EXT: abgr, bgra, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, blend_subtract, 
    clip_volume_hint, debug_label, debug_marker, draw_buffers2, draw_range_elements, fog_coord, framebuffer_blit, 
    framebuffer_multisample, framebuffer_multisample_blit_scaled, framebuffer_object, framebuffer_sRGB, 
    geometry_shader4, gpu_program_parameters, gpu_shader4, multi_draw_arrays, packed_depth_stencil, packed_float, 
    provoking_vertex, rescale_normal, secondary_color, separate_specular_color, shadow_funcs, stencil_two_side, 
    stencil_wrap, texture_array, texture_compression_dxt1, texture_compression_s3tc, texture_env_add, 
    texture_filter_anisotropic, texture_integer, texture_lod_bias, texture_rectangle, texture_sRGB, 
    texture_sRGB_decode, texture_shared_exponent, timer_query, transform_feedback, vertex_array_bgra
  GL_IBM_rasterpos_clip
  GL_NV: blend_square, conditional_render, depth_clamp, fog_distance, light_max_exponent, texgen_reflection, 
    texture_barrier
  GL_SGIS: generate_mipmap, texture_edge_clamp, texture_lod
OpenGL Windowed 854x480 32 color 16 texture 60Hz Vsync SmoothLines
WARNING: Couldn't initialize device.
WARNING: Couldn't load the Beginner chart's NoteData from "/Songs/ianananananabananaman/Washington On Your Side/Washington On Your Side.sm"
WARNING: Couldn't load the Challenge chart's NoteData from "/Songs/ianananananabananaman/Washington On Your Side/Washington On Your Side.sm"
WARNING: Couldn't load the Hard chart's NoteData from "/Songs/ianananananabananaman/Washington On Your Side/Washington On Your Side.sm"
WARNING: Couldn't load the Medium chart's NoteData from "/Songs/ianananananabananaman/Washington On Your Side/Washington On Your Side.sm"
WARNING: Couldn't load the Easy chart's NoteData from "/Songs/ianananananabananaman/Washington On Your Side/Washington On Your Side.sm"
WARNING: Couldn't load the Beginner chart's NoteData from "/Songs/ianananananabananaman/Washington On Your Side/Washington On Your Side.sm"
Mixing underruns: 1
Players joined: P1
Top Screen: ScreenPractice
Language: en
Current renderer: OpenGL
Theme: default

Partial log:
06:00.910: Sound "/Themes/_fallback/Sounds/_missing.ogg" has a start time 0.000008 seconds in the past
06:01.339: 60 FPS, 60 av FPS, 5642 VPF, OpenGL
06:01.609: Approximate sound time: driver frame 912003992, m_pImpl->m_Queue frame 49215..98430 (dist 168), closest position is 98430
06:01.633: PushScreen: "ScreenMiniMenuMainMenu"
06:01.633: ScreenOptions::InitMenu()
06:02.307: WARNING: Couldn't load the Challenge chart's NoteData from "/Songs/ianananananabananaman/Washington On Your Side/Washington On Your Side.sm"
06:02.307: WARNING: Couldn't load the Hard chart's NoteData from "/Songs/ianananananabananaman/Washington On Your Side/Washington On Your Side.sm"
06:02.308: WARNING: Couldn't load the Medium chart's NoteData from "/Songs/ianananananabananaman/Washington On Your Side/Washington On Your Side.sm"
06:02.308: WARNING: Couldn't load the Easy chart's NoteData from "/Songs/ianananananabananaman/Washington On Your Side/Washington On Your Side.sm"
06:02.308: WARNING: Couldn't load the Beginner chart's NoteData from "/Songs/ianananananabananaman/Washington On Your Side/Washington On Your Side.sm"

-- End of report
`

**Comment by ianklatzco** [comment]
okay to be fair this is kinda expected behavior cause i wiped all the doubles charts from an existing simfile. surprised it segfaulted instead of throwing an error message tho.

**Comment by kyzentun** [comment]
I need better steps to reproduce this crash, because simply deleting the charts from a simfile before editing it isn't crashing for me.

**Comment by ianklatzco** [comment]
Lemme try and reproduce later today,

**Comment by ianklatzco** [comment]
Couldn't reproduce.
