### ISSUE TITLE
RTT is broken with D3D

### ISSUE THREAD

**Issue by dguzek** [stepmania/stepmania#1065]
Render to texture is broken when `d3d` is set as the primary VideoRenderer.

It's possible to work around this by setting `opengl` as the primary VideoRenderer, but most Windows users suggest that fps is roughly cut in third in Gameplay with that set.

This bug can be seen in the background of ScreenSortList of the GameModes branch of my Simply Love theme.  ScreenSortList appears like an overlay on top of SSM but is actually a distinct screen.  Before transitioning out of  SSM, I use an AFT to render the entire screen (via ActorProxy) to texture, and set the background of ScreenSortList to be that texture.

~~**To reproduce this bug:**
**1.** Use the [_GameModes_ branch](https://github.com/dguzek/Simply-Love-SM5/tree/GameModes) of my Simply Love theme and proceed to ScreenSelectMusic.
**2.** Press `MenuLeft`+`MenuRight` or hold `Select` and press `Start` to switch to ScreenSortList.
**3.** When D3D is set as the primary renderer, the background will appear all gray.~~

As of [this commit](https://github.com/dguzek/Simply-Love-SM5/commit/a0834292a6fed582f303d91c855fda290a1fcbd8) to my GameModes branch, I no use longer the RTT trick on Simply Love's ScreenSelectMusic + ScreenSortList.  I _do_ still use RTT on ScreenEvaluation for a screenshot animation.

**To reproduce this bug:**
**1.** Use the [_GameModes_ branch](https://github.com/dguzek/Simply-Love-SM5/tree/GameModes) of my Simply Love theme, play any song in _Competitive_ mode, and proceed to ScreenEvaluation.
**2.** Save a screenshot by pressing `Select`.
**3.** Note that the what should be the TopScreen rendered to a Sprite via ActorFrameTexture appears all white.

D3D rendering currently looks like this:
![broken](http://i.imgur.com/xalbgUb.jpg)

It should look like this.
![working](http://i.imgur.com/HSeW1se.jpg)

**Comment by dguzek** [comment]
As of [this commit](https://github.com/dguzek/Simply-Love-SM5/commit/a0834292a6fed582f303d91c855fda290a1fcbd8) to my GameModes branch, I no use longer the RTT trick on Simply Love's ScreenSelectMusic + ScreenSortList.

I've updated the issue text to reflect this.

**Comment by shakesoda** [comment]
Looking into this: RTT is more than broken, it's completely not implemented for D3D.

Not closing this yet, though, I'm still looking at it (and debating throwing in a BGFX renderer for 5.1 entirely - which would solve a lot of problems)

**Comment by Ov3rHell3XoduZ** [comment]
Back to theming after 2 years to notice this bug still present, even in the latest build.

**Comment by shakesoda** [comment]
unlikely to ever be fixed, see #1583.

I did look into this at the time, but there were a lot of other problems that needed to be addressed for it to be at feature parity and it's pretty much completely not worth it. use opengl.

**Comment by coderjo** [comment]
I might take a look. If I remember correctly, I had to render to texture to make screenshots work after removing D3DX.

**Comment by coderjo** [comment]
Upon a quick review, no, it wasn't how that was implemented.

**Comment by Ov3rHell3XoduZ** [comment]
Remove D3D that gives high performance than OpenGL for just one thing broken is not worth it. Lets continue using SM without RTT, it has been broken for years already anyway.

**Comment by coderjo** [comment]
@dguzek is RTT used in the new thonk visual theme in SL 4.8.4? It didn't appear to render correctly, and then I realized it might be a d3d thing, and when I changed to opengl it worked properly. (if it does, it gives me a known test case, should I get off my butt to try and fix this.)

**Comment by dguzek** [comment]
@coderjo – Ah, I didn't even think to check that.  The code was contributed by someone else, and I don't really have access to Windows to test d3d, so its existence/this problem slipped my mind.

ActorFrameTextures are indeed used in the Simply Thonk mode, as well as a handful of other non-critical places throughout the theme (screenshot animations on ScreenEvaluation).
