### ISSUE TITLE
Stepmania 5 songs folder

### ISSUE THREAD

**Issue by jamgallACE** [stepmania/stepmania#1075]
Hi! So on stepmania 5, i am trying to install some indavidual songs and one pack. I have put the songs in the songs place but then it says
The folder "Songs/Bonetrousle" appears to be a song folder. All song folders must reside in a group folder. For example, "Songs/Originals/My Song" will contain the music file (MP3, OGG...), the steps file (.sm, .dwi, .ksf...) and other related files.
I do not have anything in the songs folder, except the songs i have put in. I have tried removing some songs, and it still doesnt work. The pack works fine in the songs folder. Can anyone help?

**Comment by Jousway** [comment]
you cannot put invidual songs inside the song folder, they must be in a pack, so make it like Songs/Songs/Bonetrousle

**Comment by dguzek** [comment]
The StepMania forums are better suited for questions like this.  GitHub's issue tracker is intended for bug reports, crashes, etc.

Maybe this post will help you: <http://www.stepmania.com/forums/song-packs/show/5564#post11119>

**Comment by Jousway** [comment]
maybe he posted here because "Note (2016-04-11): We are working on updating the site to mitigate the spam. Registration is temporarily disabled."

**Comment by dguzek** [comment]
Good point!  I had forgotten about that.

Still, this (exact) question gets answered frequently on the forums, just like in the post I linked to.
