### ISSUE TITLE
(Stepmania 5.0.11-git) LUA effetcs happening faster than intended.

### ISSUE THREAD

**Issue by MrThatKid** [stepmania/stepmania#1081]
Hello, I've found an issue with scripted lua effects (not mods) in that they go much faster than they're probably supposed to.
As an example, I'll use TaroNuke's Louder Louder file.
The file and it's effects are supposed to look like [this](https://www.youtube.com/watch?v=D2dPELijDkY)
In the latest git version (April 24, 2016 on master branch), some effects seem to act like the rate is faster than it actually is. This results in some things not looking right or going faster than normal.
However, in older versions (I have StepMania5.0-git-108b297 working), this doesn't happen and the effects play out as they do in the video.
This issue persists over multiple files regardless of theme or scroll rate.
The OS used is Ubuntu 16.04, 64-bit and I'm using a rate mod of 2.5x, but it doesn't change (for better or worse) if 1.0x was used instead.

**Comment by kyzentun** [comment]
Make a minimal example so that the problem isn't obscured by tons of other distractions and can be easily examined.

**Comment by kyzentun** [comment]
Also, try this commit: https://github.com/stepmania/stepmania/commit/073ba9f10bd99b6a6e21e302469ca712d5d0769a

**Comment by MrThatKid** [comment]
That fixed it. Thank you.
