### ISSUE TITLE
Website formum registration link is broken in Chrome on mac osx 10.11.3

### ISSUE THREAD

**Issue by LinkReincarnate** [stepmania/stepmania#1082]
I am unable to register on the forums because the registration link is broken.  It takes you to a server error page.

**Comment by kyzentun** [comment]
There is a separate issue page for the forum: https://github.com/stepmania/stepmania-site/issues
(and this issue is known already)

If you have an IRC client and need help with something specific, you can join #stepmania-devs on irc.freenode.net.
