### ISSUE TITLE
StepMania 5.0.11 Crash when changing difficulty on SMO (with crash report)

### ISSUE THREAD

**Issue by HypnoticMarten77** [stepmania/stepmania#1096]
The SN3 team and I were testing our private SMO server and my SM crashed when I pressed down to change difficulties while connected to SMO.  This happens with every version of SM5 I use, as well as every SMO server I try.  Even with a clean install, it happens.

StepMania5.0.11 crash report (build 9c6858f, 20160331 @ 02:03:00)
--------------------------------------

Crash reason: Access Violation

Thread: Main thread
        ScrollBar.cpp:67 Percentages set.
        ScrollBar.cpp:67 Percentages set.
        ScrollBar.cpp:67 Percentages set.
        ScrollBar.cpp:67 Percentages set.
        ScrollBar.cpp:67 Percentages set.
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
Thread: Mixer thread
Thread: Music thread
        RageFileDriverDirectHelpers.cpp:230 C:/Users/Andres/Documents/DDRSN3/Announcers/*
        RageFileDriverDirectHelpers.cpp:230 C:/Users/Andres/Documents/DDRSN3/Themes/_fallback/Sounds/*
        GameSoundManager.cpp:358 Removing old sound at index 0
        GameSoundManager.cpp:358 Removing old sound at index 0
        GameSoundManager.cpp:358 Removing old sound at index 0
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:773 
        InputHandler_DirectInput.cpp:749 
        InputHandler_DirectInput.cpp:768 
        InputHandler_DirectInput.cpp:773 
        InputHandler_DirectInput.cpp:749 
Thread: Streaming sound buffering
0025c469: StepMania!00080000
00547bf8: StepMania!00080000
00156897: StepMania!00080000
0025bec4: StepMania!00080000
003f5937: StepMania!00080000
003f49ee: StepMania!00080000
003f05d7: StepMania!00080000
0039d56f: StepMania!00080000
003932fe: StepMania!00080000
003b6043: StepMania!00080000
003f4798: StepMania!00080000
0011201d: StepMania!00080000
0015477d: StepMania!00080000
00154ad9: StepMania!00080000
0010e3b0: StepMania!00080000
00116045: StepMania!00080000
00548626: StepMania!00080000
00548626: StepMania!00080000
00473aaa: StepMania!00080000
00473756: StepMania!00080000
0052b7b7: StepMania!00080000
7713ab5a: ntdll!RtlInitializeExceptionChain [770e0000+5ab00+5a]

Static log:
StepMania5.0.11
Compiled 20160331 @ 02:03:00 (build 9c6858f)
Log starting 2016-05-10 19:44:05
Loading window: win32
Windows 6.2 (Win8) build 9200 []
Memory: 4095mb total, 4095mb swap (4095mb swap avail)
Video driver: Intel(R) HD Graphics Family [Intel Corporation]
              10.18.14.4170, 3-16-2015 [pci\ven_8086&dev_0a16]
Drive: "WDC     WD10JPVX-22JC3T001.0" Driver: storahci DMA: N/A
Sound device 0: Speakers (Realtek High Definiti, 6.3, MID 1, PID 100 
WARNING: Direct3D mode detected. Some visual effects may not work properly.
WARNING: Do not report these problems as bugs, they are limitations of Direct3D mode.
WARNING: ReadFile(Save/ThemePrefs.ini): No such file or directory
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Lights driver: SystemMessage
Lights driver: Export
WARNING: Unlock: Cannot find song matching "Arabbiata"
Video renderers: 'd3d,opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 1, 1280, 720, 32, 0, 1 )
D3D Windowed 1280x720 32 color 32 texture 60Hz Vsync SmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 2 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Mouse' axes: 3, hats: 0, buttons: 8 (buffered)
WARNING: #1  ... in /Themes/_fallback/Scripts/02 ActorDef.lua:30
WARNING: #2  (tail call)
WARNING: #3  LoadPlayerStuff() in /Themes/DDR SN3/BGAnimations/ScreenSelectProfile overlay.lua:321
WARNING: #4  main in /Themes/DDR SN3/BGAnimations/ScreenSelectProfile overlay.lua:649
WARNING: 
WARNING: Overriding "Name": string with string
WARNING: #1  ... in /Themes/_fallback/Scripts/02 ActorDef.lua:30
WARNING: #2  (tail call)
WARNING: #3  LoadPlayerStuff() in /Themes/DDR SN3/BGAnimations/ScreenSelectProfile overlay.lua:361
WARNING: #4  main in /Themes/DDR SN3/BGAnimations/ScreenSelectProfile overlay.lua:661
WARNING: 
WARNING: Overriding "Name": string with string
WARNING: RageSoundDriver::GetHardwareFrame: too many tries
WARNING: #1  ... in /Themes/_fallback/Scripts/02 ActorDef.lua:30
WARNING: #2  (tail call)
WARNING: #3  LoadPlayerStuff() in /Themes/DDR SN3/BGAnimations/ScreenSelectProfile overlay.lua:321
WARNING: #4  main in /Themes/DDR SN3/BGAnimations/ScreenSelectProfile overlay.lua:649
WARNING: 
WARNING: Overriding "Name": string with string
WARNING: #1  ... in /Themes/_fallback/Scripts/02 ActorDef.lua:30
WARNING: #2  (tail call)
WARNING: #3  LoadPlayerStuff() in /Themes/DDR SN3/BGAnimations/ScreenSelectProfile overlay.lua:361
WARNING: #4  main in /Themes/DDR SN3/BGAnimations/ScreenSelectProfile overlay.lua:661
WARNING: 
WARNING: Overriding "Name": string with string
WARNING: ReadFile(Save/ThemePrefs.ini): No such file or directory
WARNING: RageDisplay_D3D::TryVideoMode( 1, 1280, 720, 32, 0, 1 )
Attempting to connect to: 76.20.103.238, Port: 8765
Beginning to connect
Calling EzSockets:connect()
Back from ezsockets...
Server Version: 128 DDR SuperNOVA 3
Mixing underruns: 1
Players joined: P1
Lost focus to: (NULL), Discord.exe, explorer.exe
Top Screen: ScreenNetSelectMusic
Language: en
Current renderer: Direct3D
Theme: default

Partial log:
17:50.119: Sound "/Songs/6b-EXTRA STAGE/Illegal Function Call/Illegal Function Call.mp3" has a start time 0.001000 seconds in the past
17:50.161: Mixing underruns: 2
17:50.161: Approximate sound time: driver frame 47098847, m_pImpl->m_Queue frame 0..1024 (dist 6177), closest position is 0
17:50.781: RageSound: Load "/Songs/6b-EXTRA STAGE/DAZZLING SEASON/DAZZLING SEASON.mp3" (precache: 0)
17:50.781: Starting thread: Streaming sound buffering
17:50.782: Found '/Songs/6b-EXTRA STAGE/DAZZLING SEASON/DAZZLING SEASON.sm'
17:50.784: Sound "/Songs/6b-EXTRA STAGE/DAZZLING SEASON/DAZZLING SEASON.mp3" has a start time 0.001000 seconds in the past
17:51.151: 21 FPS, 16 av FPS, 4702 VPF, D3D
17:51.198: Mixing underruns: 1
17:52.177: 21 FPS, 18 av FPS, 4641 VPF, D3D

-- End of report

**Comment by HypnoticMarten77** [comment]
Never mind.  It crashed because I didn't have the down arrow key mapped to P1.  It was mapped to P2, so when I hit a P2 key while playing as P1 StepMania freaked out.

**Comment by kyzentun** [comment]
That still sounds super broken.  Hitting the other player's keys shouldn't crash the game.  More proof that online mode needs serious work.

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/commit/a9a1b82d8c21d39c274fe5109058b7dc355b2667

Hopefully I didn't cause some other weird problem in the process.
