### ISSUE TITLE
Program Crash when Minimaid is not used.

### ISSUE THREAD

**Issue by sillybear** [stepmania/stepmania#1097]
Steps to reproduce:
- place mmmagic.dll in Program folder
- set in Save/Preference.ini: LightsDriver=Win32Minimaid
- don't plug Minimaid device
- open StepMania
- crash

Crash log is shown here: http://codepad.org/A7YzadJR

**Comment by wolfman2000** [comment]
Tell me where to get `mmmagic.dll` and I can hopefully look into this later tonight/tomorrow.

**Comment by sillybear** [comment]
grabbed from sows:
http://www.mediafire.com/download/izxu7drtu7nqrm3/mmmagic_dll.zip

**Comment by sillybear** [comment]
sources : https://bemaniso.ws/forums.php?action=viewthread&threadid=31959&postid=1290406#post1290406

**Comment by wolfman2000** [comment]
Which version? Threaded or nonthreaded?
