### ISSUE TITLE
Xcode build error: yasm/nasm not found or too old

### ISSUE THREAD

**Issue by lostonroute66** [stepmania/stepmania#1100]
used "cmake -G Xcode .. && cmake .."
yasm found during cmake
When building in Xcode I get the following error (pasted below).
yasm/nasm not found or too old. Use --disable-yasm for a crippled build.

Not sure if this matters, but my first cmake was done before I installed yasm.  Xcode threw the yasm error.  I researched, then cleared the cmake cache, installed ffmpeg, installed yasm 1.3.0, re-ran cmake, and opened the new Xcode project.  Same error on build.

Thanks for any help.

---

PhaseScriptExecution CMake\ Rules Build/StepMania.build/Debug/ffmpeg.build/Script-238D08976D4C4CA8B5243E73.sh
    cd /Users/username/Downloads/stepmania
    /bin/sh -c /Users/username/Downloads/stepmania/Build/StepMania.build/Debug/ffmpeg.build/Script-238D08976D4C4CA8B5243E73.sh

echo "Performing configure step for 'ffmpeg'"
Performing configure step for 'ffmpeg'
cd /Users/username/Downloads/stepmania/Build/ffmpeg-prefix/src/ffmpeg-build && /Users/username/Downloads/stepmania/extern/ffmpeg-git/configure --disable-programs --disable-doc --disable-avdevice --disable-swresample --disable-postproc --disable-avfilter --disable-shared --enable-static --arch=i386 "--cc=clang -m32" --enable-gpl --extra-cflags=-w
yasm/nasm not found or too old. Use --disable-yasm for a crippled build.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solving the problem.
make: **\* [/Users/username/Downloads/stepmania/Build/ffmpeg-prefix/src/ffmpeg-stamp/Debug/ffmpeg-configure] Error 1
Command /bin/sh failed with exit code 2

**Comment by wolfman2000** [comment]
This can mean a few things. Was yasm or nasm found on your PATH? Type in `which yasm` or `which nasm` in the Terminal. Afterwards, check their versions by running `yasm --version` or `nasm --version`.

Do not be afraid to use Homebrew to get the latest versions.

yasm/nasm is required for ffmpeg to be more efficient. If you do not have yasm/nasm, you are informed to set the --disable-yasm flag.

......now, admittedly, we don't offer a way of passing in --disable-yasm right away with cmake. That's a valid bug to report in.

You have two choices. Get a more recent version of yasm/nasm, or wait for --disable-yasm to be added as an option.

**Comment by lostonroute66** [comment]
Looks like I have the latest version of yasm installed.


$ which yasm

/opt/local/bin/yasm


$ yasm --version

yasm 1.3.0

Compiled on Jan 29 2016.

Copyright (c) 2001-2014 Peter Johnson and other Yasm developers.

Run yasm --license for licensing overview and summary.

**Comment by janwerkhoven** [comment]
You can avoid that error by installing both YASM and FFmpeg with Homebrew:

    brew install yasm
    brew install ffmpeg

http://brewformulas.org/Yasm  
http://brewformulas.org/Ffmpeg

Makes installing a breeze.

**Comment by concubidated** [comment]
Can confirm. Feel free to reopen if you are still stuck building on OSX
