### ISSUE TITLE
Course mods no longer work.

### ISSUE THREAD

**Issue by YungDaVinci** [stepmania/stepmania#1103]
They worked in 5.0.11. Not sure if this was intentional.
Example if you want to test it: http://www.mediafire.com/download/1ev1eccrdsl6zxv/WinDEU_Loves_You_The_Redemption.zip
(I'm not on the latest commit by the way)

**Comment by kyzentun** [comment]
1. No more releases are planned for the 5.0.x line.
2. 5.1 needs some groundwork laid before course mods can be supported properly.
3. You need to be more clear when describing the problem.  In particular, make sure it's not actually #1081.

**Comment by kyzentun** [comment]
Defective mode and the code to enable it should make the course mods work fine in 5.1.-3.
