### ISSUE TITLE
StepMania 5.0.11 crash report (build 9c6858f, 20160331 @ 02:03:00)

### ISSUE THREAD

**Issue by Mindless3D** [stepmania/stepmania#1104]
Crash reason: waveOutGetPosition failed(There is no driver installed on your system.)

Thread: Main thread
        GraphicsWindow.cpp:179 000F0740, 32, 000f0740, 02000001
        GraphicsWindow.cpp:54 000F0740, 512, 00000000, 00790196
        GraphicsWindow.cpp:179 000F0740, 512, 00000000, 00790196
        GraphicsWindow.cpp:54 000F0740, 127, 00000000, 00000060
        GraphicsWindow.cpp:179 000F0740, 127, 00000000, 00000060
Thread: Decode thread
Thread: Mixer thread
        RageSoundDriver_WaveOut.cpp:97 waveOutGetPosition failed(There is no driver installed on your system.)
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
00f23c0f: StepMania!00b30000
00bbeadd: StepMania!00b30000
00d2560c: StepMania!00b30000
74afe21e: KERNELBASE!WaitForSingleObjectEx [74a50000+ae170+ae]
74afe162: KERNELBASE!WaitForSingleObject [74a50000+ae150+12]
00d25919: StepMania!00b30000
00d2596b: StepMania!00b30000
77b35dae: ntdll!RtlUnicodeStringToInteger [77ad0000+65b90+21e]

Static log:
StepMania5.0.11
Compiled 20160331 @ 02:03:00 (build 9c6858f)
Log starting 2016-05-14 23:29:36
Loading window: win32
Windows 6.2 (Win8) build 9200 []
Memory: 2047mb total, 4095mb swap (4095mb swap avail)
Video driver: NVIDIA GeForce GTX 970 [NVIDIA]
              10.18.13.5900, 11-13-2015 [pci\ven_10de&dev_13c2]
Drive: "WDC     WD10EZEX-08M2NA001.0" Driver: storahci DMA: N/A
Drive: "        Crucial_CT256MX1MU01" Driver: storahci DMA: N/A
Drive: "ASUS    DRW-24F1ST   a  1.00" Driver: storahci DMA: N/A
Sound device 0: Kuulokkeet (SteelSeries Siberia, 0.18, MID 65535, PID 65535 
WARNING: ReadFile(Save/ThemePrefs.ini): No such file or directory
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'opengl,d3d'
Mode: ICD 32 (888) 24 depth 64 accum 
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: NVIDIA Corporation
OGL Renderer: GeForce GTX 970/PCIe/SSE2
OGL Version: 4.5.0 NVIDIA 359.00
OGL Max texture size: 16384
OGL Texture units: 4
GLU Version: 1.2.2.0 Microsoft Corporation
OGL Extensions:
  GL_AMD: multi_draw_indirect, seamless_cubemap_per_texture, vertex_shader_layer, vertex_shader_viewport_index
  GL_ARB: ES2_compatibility, ES3_1_compatibility, ES3_2_compatibility, ES3_compatibility, arrays_of_arrays, 
    base_instance, bindless_texture, blend_func_extended, buffer_storage, clear_buffer_object, clear_texture, 
    clip_control, color_buffer_float, compatibility, compressed_texture_pixel_storage, compute_shader, 
    compute_variable_group_size, conditional_render_inverted, conservative_depth, copy_buffer, copy_image, 
    cull_distance, debug_output, depth_buffer_float, depth_clamp, depth_texture, derivative_control, 
    direct_state_access, draw_buffers, draw_buffers_blend, draw_elements_base_vertex, draw_indirect, 
    draw_instanced, enhanced_layouts, explicit_attrib_location, explicit_uniform_location, 
    fragment_coord_conventions, fragment_layer_viewport, fragment_program, fragment_program_shadow, 
    fragment_shader, fragment_shader_interlock, framebuffer_no_attachments, framebuffer_object, framebuffer_sRGB, 
    geometry_shader4, get_program_binary, get_texture_sub_image, gpu_shader5, gpu_shader_fp64, gpu_shader_int64, 
    half_float_pixel, half_float_vertex, imaging, indirect_parameters, instanced_arrays, internalformat_query, 
    internalformat_query2, invalidate_subdata, map_buffer_alignment, map_buffer_range, multi_bind, 
    multi_draw_indirect, multisample, multitexture, occlusion_query, occlusion_query2, parallel_shader_compile, 
    pipeline_statistics_query, pixel_buffer_object, point_parameters, point_sprite, post_depth_coverage, 
    program_interface_query, provoking_vertex, query_buffer_object, robust_buffer_access_behavior, robustness, 
    sample_locations, sample_shading, sampler_objects, seamless_cube_map, seamless_cubemap_per_texture, 
    separate_shader_objects, shader_atomic_counter_ops, shader_atomic_counters, shader_ballot, 
    shader_bit_encoding, shader_clock, shader_draw_parameters, shader_group_vote, shader_image_load_store, 
    shader_image_size, shader_objects, shader_precision, shader_storage_buffer_object, shader_subroutine, 
    shader_texture_image_samples, shader_texture_lod, shader_viewport_layer_array, shading_language_100, 
    shading_language_420pack, shading_language_include, shading_language_packing, shadow, sparse_buffer, 
    sparse_texture, sparse_texture2, sparse_texture_clamp, stencil_texturing, sync, tessellation_shader, 
    texture_barrier, texture_border_clamp, texture_buffer_object, texture_buffer_object_rgb32, 
    texture_buffer_range, texture_compression, texture_compression_bptc, texture_compression_rgtc, 
    texture_cube_map, texture_cube_map_array, texture_env_add, texture_env_combine, texture_env_crossbar, 
    texture_env_dot3, texture_filter_minmax, texture_float, texture_gather, texture_mirror_clamp_to_edge, 
    texture_mirrored_repeat, texture_multisample, texture_non_power_of_two, texture_query_levels, 
    texture_query_lod, texture_rectangle, texture_rg, texture_rgb10_a2ui, texture_stencil8, texture_storage, 
    texture_storage_multisample, texture_swizzle, texture_view, timer_query, transform_feedback2, 
    transform_feedback3, transform_feedback_instanced, transform_feedback_overflow_query, transpose_matrix, 
    uniform_buffer_object, vertex_array_bgra, vertex_array_object, vertex_attrib_64bit, vertex_attrib_binding, 
    vertex_buffer_object, vertex_program, vertex_shader, vertex_type_10f_11f_11f_rev, vertex_type_2_10_10_10_rev, 
    viewport_array, window_pos
  GL_ATI: draw_buffers, texture_float, texture_mirror_once
  GL_EXTX_framebuffer_mixed_formats
  GL_EXT: Cg_shader, abgr, bgra, bindable_uniform, blend_color, blend_equation_separate, blend_func_separate, 
    blend_minmax, blend_subtract, compiled_vertex_array, depth_bounds_test, direct_state_access, draw_buffers2, 
    draw_instanced, draw_range_elements, fog_coord, framebuffer_blit, framebuffer_multisample, 
    framebuffer_multisample_blit_scaled, framebuffer_object, framebuffer_sRGB, geometry_shader4, 
    gpu_program_parameters, gpu_shader4, import_sync_object, multi_draw_arrays, packed_depth_stencil, 
    packed_float, packed_pixels, pixel_buffer_object, point_parameters, polygon_offset_clamp, post_depth_coverage, 
    provoking_vertex, raster_multisample, rescale_normal, secondary_color, separate_shader_objects, 
    separate_specular_color, shader_image_load_formatted, shader_image_load_store, shader_integer_mix, 
    shadow_funcs, sparse_texture2, stencil_two_side, stencil_wrap, texture3D, texture_array, 
    texture_buffer_object, texture_compression_dxt1, texture_compression_latc, texture_compression_rgtc, 
    texture_compression_s3tc, texture_cube_map, texture_edge_clamp, texture_env_add, texture_env_combine, 
    texture_env_dot3, texture_filter_anisotropic, texture_filter_minmax, texture_integer, texture_lod, 
    texture_lod_bias, texture_mirror_clamp, texture_object, texture_sRGB, texture_sRGB_decode, 
    texture_shared_exponent, texture_storage, texture_swizzle, timer_query, transform_feedback2, vertex_array, 
    vertex_array_bgra, vertex_attrib_64bit
  GL_IBM: rasterpos_clip, texture_mirrored_repeat
  GL_KHR: blend_equation_advanced, blend_equation_advanced_coherent, context_flush_control, debug, no_error, 
    robust_buffer_access_behavior, robustness
  GL_KTX_buffer_region
  GL_NVX: conditional_render, gpu_memory_info, nvenc_interop
  GL_NV: ES1_1_compatibility, ES3_1_compatibility, bindless_multi_draw_indirect, 
    bindless_multi_draw_indirect_count, bindless_texture, blend_equation_advanced, 
    blend_equation_advanced_coherent, blend_square, command_list, compute_program5, conditional_render, 
    conservative_raster, conservative_raster_dilate, copy_depth_to_color, copy_image, depth_buffer_float, 
    depth_clamp, draw_texture, explicit_multisample, fence, fill_rectangle, float_buffer, fog_distance, 
    fragment_coverage_to_color, fragment_program, fragment_program2, fragment_program_option, 
    fragment_shader_interlock, framebuffer_mixed_samples, framebuffer_multisample_coverage, geometry_shader4, 
    geometry_shader_passthrough, gpu_program4, gpu_program4_1, gpu_program5, gpu_program5_mem_extended, 
    gpu_program_fp64, gpu_shader5, half_float, internalformat_sample_query, light_max_exponent, 
    multisample_coverage, multisample_filter_hint, occlusion_query, packed_depth_stencil, parameter_buffer_object, 
    parameter_buffer_object2, path_rendering, path_rendering_shared_edge, pixel_data_range, point_sprite, 
    primitive_restart, register_combiners, register_combiners2, sample_locations, sample_mask_override_coverage, 
    shader_atomic_counters, shader_atomic_float, shader_atomic_fp16_vector, shader_atomic_int64, 
    shader_buffer_load, shader_storage_buffer_object, shader_thread_group, shader_thread_shuffle, 
    texgen_reflection, texture_barrier, texture_compression_vtc, texture_env_combine4, texture_multisample, 
    texture_rectangle, texture_shader, texture_shader2, texture_shader3, transform_feedback, transform_feedback2, 
    uniform_buffer_unified_memory, vertex_array_range, vertex_array_range2, vertex_attrib_integer_64bit, 
    vertex_buffer_unified_memory, vertex_program, vertex_program1_1, vertex_program2, vertex_program2_option, 
    vertex_program3, viewport_array2
  GL_S3_s3tc
  GL_SGIS: generate_mipmap, texture_lod
  GL_SGIX: depth_texture, shadow
  GL_SUN_slice_accum
  GL_WIN_swap_hint
  WGL_EXT_swap_control
OpenGL Windowed 854x480 32 color 32 texture 60Hz Vsync SmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Näppäimistö" Product Name: "Näppäimistö"
Lost focus to: explorer.exe
Language: fi
Current renderer: OpenGL
Theme: default

Partial log:
00:00.548:   GL_SUN_slice_accum
00:00.548:   GL_WIN_swap_hint
00:00.548:   WGL_EXT_swap_control
00:00.548: LowLevelWindow_Win32::IsSoftwareRenderer 'NVIDIA Corporation', 'GeForce GTX 970/PCIe/SSE2'
00:00.548: OpenGL Windowed 854x480 32 color 32 texture 60Hz Vsync SmoothLines
00:00.548: RageInput::RageInput()
00:00.548: InputHandler_DInput::InputHandler_DInput()
00:00.558: InputHandler_DInput: IDirectInput::EnumDevices(DIDEVTYPE_KEYBOARD)
00:00.567: DInput: Enumerating device - Type: 0x00000413 Instance Name: "Näppäimistö" Product Name: "Näppäimistö"
00:01.659: InputHandler_DInput: IDirectInput::EnumDevices(DIDEVTYPE_JOYSTICK)

-- End of report

**Comment by kyzentun** [comment]
Find Preferences.ini. (https://github.com/stepmania/stepmania/wiki/Manually-Changing-Preferences)
Try setting ```SoundDrivers=DirectSound-sw``` or ```SoundDrivers=WDMKS```.

**Comment by Mindless3D** [comment]
Thanks for the answer! The first option worked just fine and now the game works. 

Thank you.
