### ISSUE TITLE
[5.1-git] Options aren't exactly navigatable.

### ISSUE THREAD

**Issue by MrThatKid** [stepmania/stepmania#1106]
When entering options before playing a song, the actual listed menu options are tilted in such a way that makes it rather difficult to naviagte in general. This happens regardless of which players join.
An example: [http://imgur.com/ZavfjxT](http://imgur.com/ZavfjxT)
It's even worse in some menus: [http://imgur.com/N0jV53G](http://imgur.com/N0jV53G)
This happens under StepMania5.1-git-21f924d
Compiled 20160516 @ 15:38:56 (build 21f924d)
OS used: Ubuntu 16.04 64-bit. Renderer: OpenGL

**Comment by kyzentun** [comment]
lol, Midiman never got around to fixing it after insisting that I put in some way to make options appear different for different types of thing. (submenu, bool item, number item, action, ...)

**Comment by MrThatKid** [comment]
This has been fixed for a while and nobody has closed this. I guess I'll close it, then.
