### ISSUE TITLE
Dance-threepanel mode bug

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1111]
3 panel mode shows the wrong arrows; instead of upleft down upright (like DDR Solo used to) it shows left down right. So now it just looks like single mode without the up arrow. What caused this to happen? This issue has happened since whatever version of SM5 was released 1/9/2012.

3 panel bug proof: http://i.imgur.com/XE8XzZ5.png

**Comment by kyzentun** [comment]
In a few months, it should be possible to make custom stepstypes in data files, instead of changing the source code.
So I'm just going to ignore this issue until then.

**Comment by 1033Forest** [comment]
So anything can be made possible, including a 9 panel technomotion game?

**Comment by kyzentun** [comment]
My plan is to make the engine only care about button names.  The stepstype data will have a list of button names.  That list will be passed to the newskin, which returns all the stuff for rendering them.  Input will be handled by storing a different config for each stepstype.

**Comment by Flameshadowxeroshin** [comment]
I changed dance-threepanel to allow the player to either use the left or right buttons or upleft or upright buttons to hit the first and third tracks, which to the best of my understanding, DDR Solo lets you do. Unfortunately, because left and right have higher "priority" in the button list than UpLeft and UpRight, that means it draws left and right instead.

**Comment by 1033Forest** [comment]
Will a 3 panel option be added in the select style menu in a future version? Will there be a SM 5.0.12?

**Comment by Kaiveran** [comment]
> My plan is to make the engine only care about button names. The stepstype data will have a list of button names. That list will be passed to the newskin, which returns all the stuff for rendering them. Input will be handled by storing a different config for each stepstype.

Hold up, if the engine only cares about button names, than what happens to skins like Delta? Even though dance and pump have buttons called UpLeft, they get different graphics for different stepstypes; won't that be no longer possible with what you're describing? (Once I have a basic, working incarnation of babykai, I want to have different arrows for pump in a later version)

**Comment by 1033Forest** [comment]
@Flameshadowxeroshin What type of buttons/controls would you have to use to change it? Does that mean there will be 2 threepanel modes?

**Comment by 1033Forest** [comment]
Thanks for finally fixing the 3 panel mode bug, now it displays correctly. I tried it on easyv2 noteskin. This issue can be closed now.

Now, if only a 3 panel button could be added to the select style menu, the menu for that game type would be complete...
