### ISSUE TITLE
Keys to edit steps for games with more than 10 panels

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1114]
There are 2 game modes with more than 10 panels: Beat Double7 (14 panels) and Techno Double8 (16 panels). Only keys 1-0 work to add notes. Could keys be implemented to add notes for panels after the 10th panel?

**Comment by kyzentun** [comment]
Edit mode in general is a mess that needs a complete rewrite.  It'll probably be several months before someone starts giving it the rewrite it needs.

**Comment by SpoOkyMagician** [comment]
there are/was keys. I think you have to hold one of the following and go back to 1. (alt/ctrl/shift)

**Comment by 1033Forest** [comment]
Now I figured out how to make it work!
Alt+number to add keys to the right side
