### ISSUE TITLE
[5.1-git] Beat mod doesn't look quite right.

### ISSUE THREAD

**Issue by MrThatKid** [stepmania/stepmania#1115]
In OpenITG and Stepmania 5.0, Beat would cause the receptors and arrows to go back and forth (left and right) to the beat of the song.
In 5.1, Beat makes the arrows go back and forth for the most part(Doesn't seem to go predictably back and forth, which is noticable on holds), but the receptors only go to the right on the beat of the song.
Whether enabled by theme (The theme itself doesn't matter) or by a song's LUA mods, it doesn't quite line up with the past versions.
This doesn't seem intentional because in Kyzentun's video with mods while paused ([here](https://www.youtube.com/watch?v=a8zi2F5oDw4) at ~2:37) I see that beat makes the targets go back and forth like they're probably supposed to.
Version: StepMania5.1-git-21f924d
Compiled 20160516 @ 15:38:56 (build 21f924d) on Ubuntu 16.04, 64-bit.
P.S.: Sorry if this seems nitpicky or unimportant.

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/commit/b5b1e30d5b6956066fdbe681c4d26e377e6aa890

**Comment by kyzentun** [comment]
Interesting side note from 3.95's code:
```
		/* If the song is really fast, slow down the rate, but speed up the
		 * acceleration to compensate or it'll look weird. */
		const float fBPM = GAMESTATE->m_fCurBPS * 60;
		const float fDiv = max(1.0f, truncf( fBPM / 150.0f ));
		fAccelTime /= fDiv;
		fTotalTime /= fDiv;

		/* offset by VisualDelayEffect seconds */
		float fBeat = GAMESTATE->m_fSongBeatVisible + fAccelTime;
		fBeat /= fDiv;
```
I think this means that in any song over 150 bpm, the beat effect will occur off beat.  I don't think we want to bring that in, since it seems nonsensical.

**Comment by MrThatKid** [comment]
Huh, I didn't know that. Either way, the commit fixed the problem for me. Thanks a lot!

**Comment by Kingdaro** [comment]
Correction: it's when the song reaches 300 bpm that the beat effect halves itself as though the song were playing at 150, though the effect still happens quickly and creates an awkward twitching effect with a high enough bpm.

**Comment by kyzentun** [comment]
Oh, you're right, they did truncate it to avoid having fDiv come out to 1.5 for 225 bpm.
