### ISSUE TITLE
RollingNumber bug

### ISSUE THREAD

**Issue by sillybear** [stepmania/stepmania#1118]
Test code:

self:set_text_format("%0.0f"):set_approach_seconds(0)
			:set_commify(true):set_leading_glyph("0")
			:set_chars_wide(10):target_number(9999999)
			:set_leading_attribute{ Diffuse= color("#333333") }
			:set_number_attribute{ Diffuse= color("#ffffff") }

This will display as 09,999,999 which is correct. If you change the target_number to anything less than 1000000, it lacks a comma. Example 999999 would become 000999,999 . The comma is being replaced to 0 to match char_wide.

**Comment by kyzentun** [comment]
This should take care of the bugs.  https://github.com/stepmania/stepmania/commit/11deba4ef724f7535b702588afb8d8f8570a90cd

**Comment by sillybear** [comment]
Yes, it is fixed now. Thanks! ^_^
