### ISSUE TITLE
3 panel mode button

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1121]
Now that the issue with left-down-right and upleft-down-upright has been resolved (it can be chosen now), will a 3 panel button be available in the select style menu in the next version or a future version? Will there be SM 5.0.12?

**Comment by Kaiveran** [comment]
The main stepmania team will not be involved in backporting fixes to 5.0.x – they are focused solely on 5.1+ and planning for SM6.

However, a new 5_0 branch has been created so that other people can port fixes if they want. Your best bet is to get someone to fix 3panel there.
