### ISSUE TITLE
[5.1-git] Graphic Missing in player options menu.

### ISSUE THREAD

**Issue by MrThatKid** [stepmania/stepmania#1126]
The player options menu got changed a bit. Now it's not all tilted, but has a different problem.
Pictured is the menu now : [Here.](http://imgur.com/Hjrn0QF)
Not pictured: the items doing a neat 'flapping' animation before the speed at the top is displayed.
The console displays:
WARNING: Graphics/menu_icons/bool could not be found in "Themes/default/" or "Themes/_fallback/".

WARNING: Graphics/menu_icons/menu could not be found in "Themes/default/" or "Themes/_fallback/".
Tested on default theme.
Version: StepMania5.1-git-f112edf
Compiled 20160523 @ 19:52:50 (build f112edf) on Ubuntu 16.04 64-bit

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/commit/cfa998e05cda9dc8572a3059d14118e3865efda3

The flapping animation is just so @ListenerJubatus knows where to put his on commands when he has the animation he wants.
