### ISSUE TITLE
Switch libraries to Shared by default.

### ISSUE THREAD

**Issue by wolfman2000** [stepmania/stepmania#1127]
I know our history with licenses is...well, a rocky road. However, the more I'm thinking about it, the more I think our standing would improve a bit more if we transitioned to using shared libraries instead of static libraries by default.

ffmpeg (among others) already do that. I'm not fully sure why we don't yet. Maybe it's easier to worry about compiling staticly.

I just want details confirmed on if we should stay or go with the shared option.

**Comment by Prcuvu** [comment]
In my opinion, it is good to go with shared libraries on *nix, but I suggest keeping it static on Windows, as Windows DLLs are managed in a chaotic manner.

**Comment by shakesoda** [comment]
we want them static
