### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by ChunLam** [stepmania/stepmania#1128]
StepMania5.0.11 crash report (build 9c6858f, 20160331 @ 02:03:00)
--------------------------------------

Crash reason: waveOutWrite failed(Cannot perform this operation while media data is still playing.  Reset the device, or wait until the data is finished playing.)

Thread: Main thread
        RageTextureManager.cpp:145 RageTextureManager::LoadTexture(/Songs/StepMania 5/[LK4D4] Aoki Flamme - Pumpkin Scissors OP/lkred1.png).
        ScrollBar.cpp:67 Percentages set.
        RageTextureManager.cpp:145 RageTextureManager::LoadTexture(/Songs/StepMania 5/[LK4D4] Aoki Flamme - Pumpkin Scissors OP/lkred1.png).
        ScrollBar.cpp:67 Percentages set.
        RageTextureManager.cpp:145 RageTextureManager::LoadTexture(/Songs/StepMania 5/[LK4D4] Aoki Flamme - Pumpkin Scissors OP/lkred1.png).
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
Thread: Mixer thread
        RageSoundDriver_WaveOut.cpp:77 waveOutWrite failed(Cannot perform this operation while media data is still playing.  Reset the device, or wait until the data is finished playing.)
Thread: Music thread
        RageFileDriverDirectHelpers.cpp:230 C:/Users/Chun/AppData/Roaming/StepMania 5/Themes/_fallback/*
        RageFileDriverDirectHelpers.cpp:230 C:/Games/StepMania 5/Themes/_fallback/Sounds/*
        RageFileDriverDirectHelpers.cpp:230 C:/Users/Chun/AppData/Roaming/StepMania 5/Themes/_fallback/Sounds/*
        RageFileDriverDirectHelpers.cpp:230 C:/Users/Chun/AppData/Roaming/StepMania 5/Themes/default/Sounds/default/*
        RageFileDriverDirectHelpers.cpp:230 C:/Users/Chun/AppData/Roaming/StepMania 5/Themes/default/Sounds/*
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:773 
        InputHandler_DirectInput.cpp:749 
        InputHandler_DirectInput.cpp:768 
        InputHandler_DirectInput.cpp:773 
        InputHandler_DirectInput.cpp:749 
Thread: Streaming sound buffering
016a3c0f: StepMania!012b0000
0133eadd: StepMania!012b0000
014a54f2: StepMania!012b0000
76a11601: KERNELBASE!WaitForSingleObjectEx [76a00000+11536+cb]
014a5919: StepMania!012b0000
014a596b: StepMania!012b0000
77d298d5: ntdll!RtlInitializeExceptionChain [77cf0000+3989f+36]

Static log:
StepMania5.0.11
Compiled 20160331 @ 02:03:00 (build 9c6858f)
Log starting 2016-05-24 01:33:38
Loading window: win32
Windows 6.1 (Win7) build 7601 [Service Pack 1]
Memory: 4095mb total, 4095mb swap (2296mb swap avail)
Video driver: AMD Radeon HD 5800 Series [Advanced Micro Devices, Inc.]
              15.200.1062.0, 7-15-2015 [pci\ven_1002&dev_6899]
WARNING: RegOpenKeyEx(80000002,HARDWARE\DEVICEMAP\Scsi) error (The system cannot find the file specified.)
Sound device 0: Speakers (4- ODAC-revB USB DAC), 0.1, MID 65535, PID 65535 
Sound device 1: Line 3 (Virtual Audio Cable), 6.1, MID 1, PID 100 
Sound device 2: Line 2 (Virtual Audio Cable), 6.1, MID 1, PID 100 
Sound device 3: Speakers (Realtek High Definiti, 6.1, MID 1, PID 100 
Sound device 4: Realtek Digital Output(Optical), 6.1, MID 1, PID 100 
Sound device 5: Realtek Digital Output (Realtek, 6.1, MID 1, PID 100 
Sound device 6: Headset (SoliCall), 6.1, MID 1, PID 100 
Sound device 7: Line 1 (Virtual Audio Cable), 6.1, MID 1, PID 100 
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Lights driver: SystemMessage
Lights driver: Export
WARNING: Main title or music file for '/Songs/StepMania 5/(Cynic) #56/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/StepMania 5/(GLoVE) Eternal Nocturne/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
Video renderers: 'opengl,d3d'
Mode: ICD 32 (888) 8 alpha 16 depth 
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: ATI Technologies Inc.
OGL Renderer: AMD Radeon HD 5800 Series
OGL Version: 4.5.13399 Compatibility Profile Context 15.200.1062.0
OGL Max texture size: 16384
OGL Texture units: 8
GLU Version: 1.2.2.0 Microsoft Corporation
OGL Extensions:
  GL_AMDX: debug_output, vertex_shader_tessellator
  GL_AMD: conservative_depth, debug_output, depth_clamp_separate, draw_buffers_blend, multi_draw_indirect, 
    name_gen_delete, performance_monitor, pinned_memory, query_buffer_object, sample_positions, 
    seamless_cubemap_per_texture, shader_stencil_export, shader_trace, texture_cube_map_array, texture_texture4, 
    transform_feedback3_lines_triangles, vertex_shader_layer, vertex_shader_tessellator, 
    vertex_shader_viewport_index
  GL_ARB: ES2_compatibility, ES3_1_compatibility, ES3_compatibility, arrays_of_arrays, base_instance, 
    blend_func_extended, buffer_storage, clear_buffer_object, clear_texture, clip_control, color_buffer_float, 
    compatibility, compressed_texture_pixel_storage, compute_shader, conditional_render_inverted, 
    conservative_depth, copy_buffer, copy_image, cull_distance, debug_output, depth_buffer_float, depth_clamp, 
    depth_texture, derivative_control, direct_state_access, draw_buffers, draw_buffers_blend, 
    draw_elements_base_vertex, draw_indirect, draw_instanced, enhanced_layouts, explicit_attrib_location, 
    explicit_uniform_location, fragment_coord_conventions, fragment_layer_viewport, fragment_program, 
    fragment_program_shadow, fragment_shader, framebuffer_no_attachments, framebuffer_object, framebuffer_sRGB, 
    geometry_shader4, get_program_binary, get_texture_sub_image, gpu_shader5, gpu_shader_fp64, half_float_pixel, 
    half_float_vertex, imaging, instanced_arrays, internalformat_query, internalformat_query2, invalidate_subdata, 
    map_buffer_alignment, map_buffer_range, multi_bind, multi_draw_indirect, multisample, multitexture, 
    occlusion_query, occlusion_query2, pipeline_statistics_query, pixel_buffer_object, point_parameters, 
    point_sprite, program_interface_query, provoking_vertex, query_buffer_object, robust_buffer_access_behavior, 
    sample_shading, sampler_objects, seamless_cube_map, seamless_cubemap_per_texture, separate_shader_objects, 
    shader_atomic_counters, shader_bit_encoding, shader_image_load_store, shader_image_size, shader_objects, 
    shader_precision, shader_stencil_export, shader_storage_buffer_object, shader_subroutine, 
    shader_texture_image_samples, shader_texture_lod, shading_language_100, shading_language_420pack, 
    shading_language_packing, shadow, shadow_ambient, stencil_texturing, sync, tessellation_shader, 
    texture_barrier, texture_border_clamp, texture_buffer_object, texture_buffer_object_rgb32, 
    texture_buffer_range, texture_compression, texture_compression_bptc, texture_compression_rgtc, 
    texture_cube_map, texture_cube_map_array, texture_env_add, texture_env_combine, texture_env_crossbar, 
    texture_env_dot3, texture_float, texture_gather, texture_mirror_clamp_to_edge, texture_mirrored_repeat, 
    texture_multisample, texture_non_power_of_two, texture_query_levels, texture_query_lod, texture_rectangle, 
    texture_rg, texture_rgb10_a2ui, texture_snorm, texture_stencil8, texture_storage, texture_storage_multisample, 
    texture_swizzle, texture_view, timer_query, transform_feedback2, transform_feedback3, 
    transform_feedback_instanced, transform_feedback_overflow_query, transpose_matrix, uniform_buffer_object, 
    vertex_array_bgra, vertex_array_object, vertex_attrib_64bit, vertex_attrib_binding, vertex_buffer_object, 
    vertex_program, vertex_shader, vertex_type_10f_11f_11f_rev, vertex_type_2_10_10_10_rev, viewport_array, 
    window_pos
  GL_ATI: draw_buffers, envmap_bumpmap, fragment_shader, separate_stencil, texture_compression_3dc, 
    texture_env_combine3, texture_float, texture_mirror_once
  GL_EXT: abgr, bgra, bindable_uniform, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, 
    blend_subtract, compiled_vertex_array, copy_buffer, copy_texture, direct_state_access, draw_buffers2, 
    draw_instanced, draw_range_elements, fog_coord, framebuffer_blit, framebuffer_multisample, framebuffer_object, 
    framebuffer_sRGB, geometry_shader4, gpu_program_parameters, gpu_shader4, histogram, multi_draw_arrays, 
    packed_depth_stencil, packed_float, packed_pixels, pixel_buffer_object, point_parameters, 
    polygon_offset_clamp, provoking_vertex, rescale_normal, secondary_color, separate_specular_color, 
    shader_image_load_store, shader_integer_mix, shadow_funcs, stencil_wrap, subtexture, texgen_reflection, 
    texture3D, texture_array, texture_buffer_object, texture_compression_bptc, texture_compression_latc, 
    texture_compression_rgtc, texture_compression_s3tc, texture_cube_map, texture_edge_clamp, texture_env_add, 
    texture_env_combine, texture_env_dot3, texture_filter_anisotropic, texture_integer, texture_lod, 
    texture_lod_bias, texture_mirror_clamp, texture_object, texture_rectangle, texture_sRGB, texture_sRGB_decode, 
    texture_shared_exponent, texture_snorm, texture_storage, texture_swizzle, timer_query, transform_feedback, 
    vertex_array, vertex_array_bgra, vertex_attrib_64bit
  GL_IBM_texture_mirrored_repeat
  GL_KHR: context_flush_control, debug, robust_buffer_access_behavior, robustness
  GL_KTX_buffer_region
  GL_NV: blend_square, conditional_render, copy_depth_to_color, copy_image, depth_buffer_float, 
    explicit_multisample, float_buffer, half_float, primitive_restart, texgen_reflection, texture_barrier
  GL_OES_EGL_image
  GL_SGIS: generate_mipmap, texture_edge_clamp, texture_lod
  GL_SUN_multi_draw_arrays
  GL_WIN_swap_hint
  WGL_EXT_swap_control
OpenGL Windowed 768x480 32 color 32 texture 60Hz NoVsync SmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 2 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Mouse' axes: 3, hats: 0, buttons: 8 (buffered)
WARNING: Graphics/Banner Nonstop could not be found in "Themes/default/" or "Themes/_fallback/".
WARNING: RageSoundDriver::GetHardwareFrame: too many tries
WARNING: The graphic '/Songs/StepMania 5/(Otaku's Dream) WOAH-OH-OH-AH-AH-AH-AAAA-HA-AH-AH-AH/OwneDMIX.png' has frame dimensions that aren't a multiple of 2.
WARNING: The entire image is 75x50 and frame size is 75.0x50.0.
WARNING: Image quality will be much improved if you resize the graphic to 76x50, which is a frame size of 76x50.
WARNING: HID devices changes
WARNING: HID devices changes
Mixing underruns: 1
Players joined: P1
Lost focus to: (NULL), OpenProcess (Access is denied.), StepMania.exe, chrome.exe, dota2.exe
Top Screen: ScreenSelectMusic
Language: en
Current renderer: OpenGL
Theme: default

Partial log:
41:08.337: glTexImage2D (format GL_RGBA8, 128x64, format GL_RGBA, type GL_UNSIGNED_BYTE, pixfmt 0, imgpixfmt 0)
41:08.480: glTexImage2D (format GL_RGBA8, 256x128, format GL_RGBA, type GL_UNSIGNED_BYTE, pixfmt 0, imgpixfmt 0)
41:08.590: RageSound: Load "/Songs/StepMania 5/[LK4D4] Aoki Flamme - Pumpkin Scissors OP/PS O Audio.mp3" (precache: 0)
41:08.593: Starting thread: Streaming sound buffering
41:08.593: Sound "/Songs/StepMania 5/[LK4D4] Aoki Flamme - Pumpkin Scissors OP/PS O Audio.mp3" has a start time 0.001000 seconds in the past
41:09.012: 85 FPS, 85 av FPS, 6046 VPF, OpenGL
41:10.019: 86 FPS, 85 av FPS, 6124 VPF, OpenGL
41:11.024: 87 FPS, 86 av FPS, 6124 VPF, OpenGL
41:11.024: WARNING: HID devices changes
41:11.113: WARNING: HID devices changes

-- End of report

**Comment by kyzentun** [comment]
See if this is the same problem as in #1104.  Someone needs to figure out how to fix the logic for detecting that the WaveOut driver doesn't work.

**Comment by ChunLam** [comment]
The game works after rebooting. I have no clue what happened though. It might've been my default sound driver malfunctioning for a second.

**Comment by kyzentun** [comment]
Unreproducible crashes like that are nigh impossible to fix.  If you figure out how to make it happen on command, post it.
