### ISSUE TITLE
Mungyodance type lifebar? (feature request)

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1134]
I think this could be implemented in SM.
In the select life type menu: Bar (default), Battery, or Counter (Counter is MGD type lifebar).
This counter, starts at a specified number defined by the player, or could automatically choose a number depending on how hard the song is. If it drops to 0, the song is failed.
Choices for counter: Automatic (default), 1, 5, 10, 15, and all multiples of 5 up to 100.

How the counter works:
After every 50 notes hit (combo), or every hold held, 1 life is added to the counter.
If a hold is dropped or a note is missed, 1 life is subtracted.
After 100, hold notes will not count for the counter, only 50 combo will add 1 to the counter.

**Comment by kyzentun** [comment]
Implement it in lua in the theme.  This does not need to be in the engine.
