### ISSUE TITLE
(5.1) Delta newskin diagonals broken

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1142]
I just spotted, the rotations aren't correct. The correct rotations are:
UpLeft: 135
UpRight: 225
DownLeft: 45
DownRight: 315

Since upleft is 90 and upright is 45 (current file), it draws left and downleft instead.

**Comment by shakesoda** [comment]
oops

**Comment by 1033Forest** [comment]
https://github.com/stepmania/stepmania/blob/5_1_0/NewSkins/delta/notes.lua Here's where I spotted the bug. This bug is easy to fix: just change the rotation numbers to what I said above

**Comment by wolfman2000** [comment]
@1033Forest Verify a68d051 please.

**Comment by 1033Forest** [comment]
Correct

**Comment by 1033Forest** [comment]
The receptors have the same issue:
https://github.com/stepmania/stepmania/blob/5_1_0/NewSkins/delta/receptors.lua

**Comment by wolfman2000** [comment]
@1033Forest Check 75baf4d please.

**Comment by 1033Forest** [comment]
Receptors: correct

**Comment by wolfman2000** [comment]
...wait. explosion file.

**Comment by wolfman2000** [comment]
And 43b4bd9 for good measure.

**Comment by 1033Forest** [comment]
Yep, everything looks pretty much done now
