### ISSUE TITLE
"Ridiculous" (W0) timing?

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1144]
Just an idea. I'd like to see a 7th judgement implemented. 3.9 had it, why not 5? Pulsen (another game based on SM5) has it, and it is Ludicrous timing. Should be an add-on, just like 3.9 had it as an add-on. Should be a ZIP, so there would be no confusing installer that would say it's already installed even though it's not installed.

For players who don't want it, it can easily be turned off, just like Flawless/Marvelous timing. Ridiculous timing would be turned off by default. This new timing would be twice as hard to get as a Flawless. A grade of all ridiculouses or whatever it will be called would result in an AAAAA (In ITG/Simply Love theme, it would result in a 5 star rating). This could be for players who want to live up to the challenge.

Instead of ridiculous, a different word could be used. And the judgement color could be pink, or teal. The flashes for ridiculous would be pink/teal as well. In timing settings, or noteskin explosions, it would be W0, since 0 comes before 1.

**Comment by kyzentun** [comment]
Already discussed in my comment on #1030.

**Comment by shakesoda** [comment]
1) Not every input driver actually has the granularity to do such small timing windows
2) You can do it in Lua by reading the timing offsets.

As such, we won't have ridiculous timing.

**Comment by 1033Forest** [comment]
@shakesoda If I do it in Lua and change the timing offsets, I could try editing the judgements picture just to add the new timing. But then that means getting a great can break combo, and getting a good actually lowers the lifebar.

**Comment by Prcuvu** [comment]
> But then that means getting a great can break combo, and getting a good actually lowers the lifebar.

As far as I know, Lua solves the problem.

**Comment by kyzentun** [comment]
Actually, metrics and preferences in this case.  Not necessarily lua unless the metrics point to lua.
