### ISSUE TITLE
Cannot build with GCC6.1.1

### ISSUE THREAD

**Issue by Xiaomu0** [stepmania/stepmania#1145]
When building from AUR, an error occured:

[ 58%] Building CXX object src/CMakeFiles/StepMania.dir/ScreenNetSelectMusic.cpp.o
...
...
In file included from $AUR_TEMP/aur-stepmania/src/stepmania-5.0.11/src/Screen.h:7:0,
                 from $AUR_TEMP/aur-stepmania/src/stepmania-5.0.11/src/ScreenWithMenuElements.h:4,
                 from $AUR_TEMP/aur-stepmania/src/stepmania-5.0.11/src/ScreenNetSelectBase.h:6,
                 from $AUR_TEMP/aur-stepmania/src/stepmania-5.0.11/src/ScreenNetSelectMusic.h:6,
                 from $AUR_TEMP/aur-stepmania/src/stepmania-5.0.11/src/ScreenNetSelectMusic.cpp:4:
$AUR_TEMP/aur-stepmania/src/stepmania-5.0.11/src/ThemeMetric.h: In constructor ‘MusicWheel::MusicWheel()’:
$AUR_TEMP/aur-stepmania/src/stepmania-5.0.11/src/ThemeMetric.h:280:4: **internal compiler error**: in emit_move_insn, at expr.c:3546
    m_metric[*s].Load( sGroup, pfn(*s) );
    ^~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.archlinux.org/> for instructions.
make[2]: *** [src/CMakeFiles/StepMania.dir/build.make:8319: src/CMakeFiles/StepMania.dir/ScreenNetSelectMusic.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:418: src/CMakeFiles/StepMania.dir/all] Error 2
make: *** [Makefile:150: all] Error 2

**Comment by shakesoda** [comment]
compiler bug, not us
