### ISSUE TITLE
Para support broken 5.0.x and 5.1.x

### ISSUE THREAD

**Issue by chrispable** [stepmania/stepmania#1149]
Video capture from 5.0.10:
https://www.youtube.com/watch?v=P9nwDgHRZ6w at 17 seconds in

Holds are broken.

In 5.1.0 alpha 2, para support is show similar to this in edit mode, when when pressing p to play from edit mode, notes are replace with beatmania styled notes.

Example ssc:
http://www.mediafire.com/download/v2yzql4tvlah3bs/speedway-ssc.zip

**Comment by shakesoda** [comment]
nobody has para hardware and nobody plays para, so as a side effect nobody tests it.

**Comment by 1033Forest** [comment]
This issue happened to me too, but the para noteskin worked on older SM5 builds...

**Comment by kyzentun** [comment]
If it's just about the noteskin, somebody has to make a para noteskin in the new format.

**Comment by chrispable** [comment]
a little more complicated than that for 5.1.x. In the latest version, there's the note skin problem but then when you go to play, the note skin changes to beatmania. yet in edit mode is para. it's pretty strange

**Comment by 1033Forest** [comment]
@chrispable That beatmania looking noteskin is zenbuquan; it is a noteskin designed to support every button on every game type.

**Comment by kyzentun** [comment]
[para.zip](https://github.com/stepmania/stepmania/files/477542/para.zip)

I don't have any para simfiles to test with, so....
Put this in your NoteSkins folder on 5.1.-3 or latest master and try it out.  If it works, I'll commit it.
