### ISSUE TITLE
5.0.11 Editor Crash

### ISSUE THREAD

**Issue by DXUltimate** [stepmania/stepmania#1150]
http://pastebin.com/qRHSLhfp

This was created by making a Routine in the editor and attempting to add attacks into the simfile itself. It would successfully add the attack, but the moment I would go test it out, it would spit out this crash message.

Using: dbk2's Simply Love SM5 theme, not sure this matters considering it crashes on StepF2 as well, even though that's also SM5 (a more outdated version as well I think, not sure)
Version: 5.0.11
Game: pump

Pastebin will expire in 2 weeks.

EDIT: I'm going to try this in 5.1

**Comment by kyzentun** [comment]
StepF2 is SM5 beta 4ish.  Don't report crashes that occur in it to us.

Does this only happen when using attacks, or does it happen with normal routine charts too?

**Comment by DXUltimate** [comment]
Only when attacks are added, I went ahead and created a small test file on singles and it works fine until I add attacks. this is only in the editor though. I haven't played them in the actual game yet, but it seems like attacks work in the normal gameplay.

**Comment by kyzentun** [comment]
Upload the simfile you have, so I can try it out directly.

**Comment by DXUltimate** [comment]
http://puu.sh/pwjvT/44d16c27cc.rar

Here it is, to redo the crash here is some steps.

1. Switch to pump gamemode
2. Open editor,
3. Choose simfile, and then move to routine, and it should be set as "EXPERT 21"
4. Select an area, and just add something like 1x hallway or something
5. Then "Play Whole Song"

**Comment by kyzentun** [comment]
I hate the way the old notefield handles noteskins, especially when it comes to routine mode.

Here's the line it's actually asserting on.  https://github.com/stepmania/stepmania/blob/master/src/NoteField.cpp#L245

Need to figure out some way to set the routine noteskin from the metrics (which is itself a terrible way to handle picking a noteskin for routine mode).

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/commit/7daaf04cfc358726684b8f8f14552d575474b7b0
