### ISSUE TITLE
Shock arrows and potions?

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1152]
https://www.youtube.com/watch?v=jVOPaoyeGYQ Concept tested in AMX (not my video).

Note types from DDR and PIU.
Shock arrows: Unlike mines, these when hit not only decrease your lifebar, but they also make all the arrows invisible for a second, make a lightning bolt appear, breaks your combo, and gives an NG. When avoided it adds 1 (or 2 or more depending on how many shocks there were) to your combo and gives an OK. So they are graded like holds. In the options menu, there would also be an option to change mines to shocks. ("S" in .sm file)
Potions: IDK what they're supposed to do, but they don't do anything in AMX ("P" in .sm file)

**Comment by kyzentun** [comment]
Shock arrows have been possible to implement theme-side for years.  Notice how not even the most dedicated DDR themer has bothered to do it.  They're a bad idea, poorly implemented.
