### ISSUE TITLE
"Step Revolution" game type?

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1159]
So, Kyle Ward has been working on his new dance game, Step Revolution:
https://zenius-i-vanisher.com/v5.2/thread?threadid=8319&&page=1
https://youtu.be/lZfbWeuBg_g
http://www.kyleaward.com/2016/01/15/returning-to-dance-games/

I was wondering if this game type could be added to a future SM 5.1 or SM6. The Step Revolution game will actually come out late 2016. There are 3-, 5-, and 9-panel modes (9-panel interested a lot of people).

The panels:
3 panel: Left, Center, Right
5 panel: Left, Down, Center, Up, Right (like PIU, but without diagonals)
9 panel: DownLeft, Left, UpLeft, Down, Center, Up, UpRight, Right, DownRight (techno with a center panel)

**Comment by kyzentun** [comment]
Just stop.  Custom stepstypes are already covered and planned elsewhere.

**Comment by 1033Forest** [comment]
Will custom stepstypes appear soon in 5.1, or will I have to wait for SM6?
