### ISSUE TITLE
(5.1) (Experimental feature idea) Have note colors adjust to speed mod

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1162]
Is this possible in NewField? To have the note colors adjust depending on your speed mod.
Example: 2x would "halve" the noteskin, like if 4th=red and 8th=blue, in the speed mod, 8th=red and 16th=blue.
3x would remove the triplet colors (change all 12ths to red, 24ths to blue, 48ths to yellow, etc)
C-mods, would randomly color the arrow depending on what speed mod is currently in use at that point (might see a lot of greens/grays)

**Comment by kyzentun** [comment]
Quantization probably needs to change to a different method internally, so I'd rather not create any mods for it right now.

**Comment by 1033Forest** [comment]
I know you might not be interested right now, but here's a menu system I thought of it:
There could be 2 menus, one for changing the speed mod and one for the note colors.

Like, you could make it look like 3x on a 1.5 speed mod. Or make it look like 0.25x on any speed mod to make it look like a "bag" edit as a joke...

Note color customizations menu (this is where the other 7 quantizations on the x16 noteskins can be used):
Single color: Choose a color (4th-192nd or other colors) to change all the notes into one color (flat)
Column colored: Choose colors (4th-192nd or other colors) for each individual column
Speed mod: Adjust note colors based on speed mod
Random: Randomizes every note color so each note will have a different color no matter the quantization (like one 4th could look like a 16th and another one a 24th)

The default note color setting, will be speed mod, 1x.

**Comment by 1033Forest** [comment]
It turns out, noteskin authors can do this in the noteskin parameters. I saw hanubeki's noteskin and there is a way to either use column colors based on the gametype, or split/alternate colors of gray and blue.

**Comment by 1033Forest** [comment]
Closing this since authors can do this in noteskin params
