### ISSUE TITLE
Incorporate 96ths (32nd note triplets) into source code

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1166]
https://github.com/stepmania/stepmania/blob/75daad9d436722ee199b5cd645e8be810497fb85/src/NoteTypes.h#L260
There are sixteenth note triplets and sixty-fourth note triplets, where's our thirty-second note triplet?

DDReam had a 96th snap where you could easily add 96th notes, and AMX has it too. But in the SM editor, there isn't one, so I have to resort to using 192nd, then placing a note every 2 beats, and I might accidentally go off and add a 192nd or 64th when doing that. Can I add some code to incorporate 96ths into the engine?

Here's some 96th code I could add:
	NOTE_TYPE_96TH,/**< thirty-second note triplet */
	case NOTE_TYPE_96TH:	return 1.0f/24; // thirty-second note triplets
	else if( row % (ROWS_PER_MEASURE/96) == 0)	return NOTE_TYPE_96TH;
		case NOTE_TYPE_96TH: return 2;

96ths are OK, not a bad idea compared to 384ths or higher
Should I add the code now, add the code and put 2 slashes before it, or not add the code now? Because IDK how to compile a program by source to test it out...

**Comment by kyzentun** [comment]
This belongs under the editor revamping topic.
