### ISSUE TITLE
(5.1) (NewSkin bug/visual oddity) Arrows don't light up all the way to the beat in certain noteskins

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1167]
http://i.imgur.com/Kwx6ljy.png

I notice that in certain noteskins, not all the arrows light up fully to the beat (they are all different frames). Each note color has 4 frames. In previous versions of note (3.9-5.0) all the arrows would light up the same way (all arrows lit up for every note no matter what beat they are on). But in 5.1, each note is on a different frame (like the 4ths in this picture have 1 light lit up, while the 8ths are fully lit up, and the 16th isn't). What's causing it, and will it be fixed in a future 5.1? I know the new noteskin system is still a work in progress.

This doesn't just happen in note, it happens in any note-colored noteskin with 4 frames on it.

**Comment by kyzentun** [comment]
They're on different frames because the author set the vivid flag.  They all still cycle through the frames.  Not a bug.

**Comment by 1033Forest** [comment]
Thanks, I set the vivid flag to false and now it works
