### ISSUE TITLE
Crash on Startup (MAC OS X)

### ISSUE THREAD

**Issue by WorldlessMusic** [stepmania/stepmania#1168]
Stepmania crashes immediately on startup. I will attach the crash report.
StepMania5.0.11 crash report (build 9c6858f, 20160331 @ 02:01:34)
--------------------------------------

Architecture:   Mac OS X (i386)
Crash reason:   Assertion 'IsThemeSelectable(sThemeName)' failed
Crashed thread: Main thread

Checkpoints:
Thread: GUI thread
Thread: Main thread
        IniFile.cpp:21 Reading 'Save/Preferences.ini'
        IniFile.cpp:21 Reading 'Save/Preferences.ini'
        IniFile.cpp:21 Reading 'Data/Static.ini'
        IniFile.cpp:21 Reading 'Data/Static.ini'
        ThemeManager.cpp:392 Assertion 'IsThemeSelectable(sThemeName)' failed

Thread: 
0065417c: CrashHandler::ForceCrash(char const*) 
00659bea: sm_crash(char const*) 
005e79ae: ThemeManager::SwitchThemeAndLanguage(StdString::CStdStr<char> const&, StdString::CStdStr<char> const&, bool, bool) 
005c6e1b: StepMania::InitializeCurrentGame(Game const*) 
005c8117: sm_main 
00651b6b: -[SMMain startGame:] 

Static log:
StepMania5.0.11
Compiled 20160331 @ 02:01:34 (build 9c6858f)
Log starting 2016-06-20 13:25:20
Loading window: macosx
Model: MacBook5,2 (2/2)
Clock speed 2.13 GHz
Mac OS X 10.11.4
Memory: 2.00 GB

Partial log:
00:01.031: Reading 'Data/Defaults.ini' failed: No such file or directory
00:01.031: Reading 'Save/Preferences.ini' failed: No such file or directory
00:01.031: Reading 'Save/Preferences.ini' failed: No such file or directory
00:01.031: Reading 'Data/Static.ini' failed: No such file or directory
00:01.031: Loading window: macosx
00:01.064: Model: MacBook5,2 (2/2)
00:01.064: Clock speed 2.13 GHz
00:01.064: Mac OS X 10.11.4
00:01.064: Memory: 2.00 GB
00:01.095: Reading 'Data/Static.ini' failed: No such file or directory

-- End of report
Please help me, I would very much like to play it but crashing just gettin in the way >:(

**Comment by kyzentun** [comment]
Sounds like it wasn't installed correctly.  What theme is set in the preferences file?  Did you do anything after installing?

**Comment by WorldlessMusic** [comment]
I did not do anything after installing...I have no theme in Application Support, if that is what you meant By "Preferences".

**Comment by wolfman2000** [comment]
How did you install this version of StepMania? Did you have older versions of StepMania installed before?

**Comment by WorldlessMusic** [comment]
Installed it from stepmania.com, never installed it before.

(^.^)

On June 20, 2016, at 5:09 PM, Jason Felds <notifications@github.com> wrote:

How did you install this version of StepMania? Did you have older versions of StepMania installed before?

---

**Comment by kyzentun** [comment]
(wolfman actually has OS X, I don't)

**Comment by wolfman2000** [comment]
I'll try this approach. When you installed it, did the application appear in /Applications? What is inside StepMania.app?

I'm wondering if perhaps the build got corrupted somehow. That doesn't make sense since this is about 3 months old, but...I'm wondering what's going on.

**Comment by WorldlessMusic** [comment]
It appeared in downloads, but I put the .app in applications. The normal folders are inside,
Announcers
BackgroundEffects
BackgroundTransitions
BGAnimations
CDTitles
Characters
Courses
Noteskins
Packages
Randommovies
Songs
Themes

(^.^)

On June 20, 2016, at 5:17 PM, Jason Felds <notifications@github.com> wrote:

I'll try this approach. When you installed it, did the application appear in /Applications? What is inside StepMania.app?

I'm wondering if perhaps the build got corrupted somehow. That doesn't make sense since this is about 3 months old, but...I'm wondering what's going on.

---

**Comment by wolfman2000** [comment]
Unless I'm mistaken, those folders are the correct ones.

Does `~/Library/Preferences/StepMania 5/` exist? If so, try deleting that folder and starting again. Same with `~/Library/Application Support/StepMania 5/`.

**Comment by WorldlessMusic** [comment]
I did so, but it says No NoteSkins found, where do I put the NoteSkins?

(^.^)

On June 20, 2016, at 5:38 PM, Jason Felds <notifications@github.com> wrote:

Unless I'm mistaken, those folders are the correct ones.

Does `~/Library/Preferences/StepMania 5/` exist? If so, try deleting that folder and starting again. Same with `~/Library/Application Support/StepMania 5/`.

---

**Comment by wolfman2000** [comment]
...the noteskins should already be provided. What are the contents of the NoteSkins folder within StepMania.app?

**Comment by WorldlessMusic** [comment]
Beat
Common
Dance
Instructions.text
Kb7
Kickbox
Lights
Para
Pump
Techno

(^.^)

On June 20, 2016, at 6:35 PM, Jason Felds <notifications@github.com> wrote:

...the noteskins should already be provided. What are the contents of the NoteSkins folder within StepMania.app?

---

**Comment by wolfman2000** [comment]
Okay, NoteSkins should be in place. Is there any Preferences.ini or Static.ini file that is being read in from any of the directories discussed?

**Comment by WorldlessMusic** [comment]
What do you mean, read in? I have no preferences.INI or static.INI in the device, Preferences/StepMania 5 or Application support/StepMania 5

(^.^)

On June 20, 2016, at 7:11 PM, Jason Felds <notifications@github.com> wrote:

Okay, NoteSkins should be in place. Is there any Preferences.ini or Static.ini file that is being read in from any of the directories discussed?

---

**Comment by dguzek** [comment]
You downloaded *StepMania-5.0.11-mac.dmg* from <www.stepmania.com/download/> which is a disk image that contains a single folder titled "StepMania-5.0.11" like this:

![screen shot 2016-06-21 at 8 06 34 am](https://cloud.githubusercontent.com/assets/1253483/16228792/1dc38980-3787-11e6-9144-629a31a7fe76.png)

Start by deleting whatever copy of StepMania you think you have installed to the Applications folder.

Then, follow these steps:

1. drag that folder to your Desktop
2. eject the disk image
3. double-click *StepMania.app* from within the folder that is now on your desktop

That should work.

**Comment by WorldlessMusic** [comment]
Thank you! I will try upon getting home

(^.^)

On June 21, 2016, at 8:10 AM, Dan Guzek <notifications@github.com> wrote:

You downloaded *StepMania-5.0.11-mac.dmg* from <www.stepmania.com/download/> which is a disk image that contains a single folder titled "StepMania-5.0.11" like this:

![screen shot 2016-06-21 at 8 06 34 am](https://cloud.githubusercontent.com/assets/1253483/16228792/1dc38980-3787-11e6-9144-629a31a7fe76.png)

Start by deleting whatever copy of StepMania you think you have installed to the Applications folder.

Then, follow these steps:

1. drag that folder to your Desktop
2. eject the disk image
3. double-click *StepMania.app* from within the folder that is now on your desktop

That should work.

---

**Comment by WorldlessMusic** [comment]
It worked, thank you so much!

(^.^)

On June 21, 2016, at 8:10 AM, Dan Guzek <notifications@github.com> wrote:

You downloaded *StepMania-5.0.11-mac.dmg* from <www.stepmania.com/download/> which is a disk image that contains a single folder titled "StepMania-5.0.11" like this:

![screen shot 2016-06-21 at 8 06 34 am](https://cloud.githubusercontent.com/assets/1253483/16228792/1dc38980-3787-11e6-9144-629a31a7fe76.png)

Start by deleting whatever copy of StepMania you think you have installed to the Applications folder.

Then, follow these steps:

1. drag that folder to your Desktop
2. eject the disk image
3. double-click *StepMania.app* from within the folder that is now on your desktop

That should work.

---

**Comment by dguzek** [comment]
Thanks for letting us know.  I'll close this issue now.
