### ISSUE TITLE
Key to add checkpoint holds in editor

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1170]
Can a key to add checkpoint holds be added? Like shift creates a roll, I thought of a key for a checkpoint hold. Maybe Ctrl+number then go down.

**Comment by kyzentun** [comment]
Checkpoint holds don't even exist as their own hold type yet.

**Comment by 1033Forest** [comment]
Once they exist, there will be a total of 7 note types. Back in the 3.9 era, there were only 3...

Note type history:
Tap (start)
Hold (start)
Mine (3.9)
Roll (3.95)
Lift (4.0)
Fake (4.0)
Checkpoint Hold (5.1)
Timed-Release Hold (5.1?)
Minefield/Mine hold/Mine area (Unknown, might need to get opinions from some other SM workers first)
Hidden notes (Also unknown, still needs more opinions)
