### ISSUE TITLE
Why is beat-double5 crashing?

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1172]
It says in the noteskin instructions, for beat, 10 key mode is broken. Why is it broken, and what causes it to crash? Will it be fixed in a future 5.0/5.1?

**Comment by kyzentun** [comment]
I think those "instructions" just mean that noteskin doesn't work.  Not a bug in the engine.

**Comment by 1033Forest** [comment]
I tried beat double5 (10 keys) and it crashed.

**Comment by kyzentun** [comment]
Looks like the button names and other stuff in the style is done wrong somehow.  Probably never worked.

**Comment by 1033Forest** [comment]
I should probably check the source code...

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/commit/6ce300e06f0f40d7ff475a5ef246170236d82284

**Comment by 1033Forest** [comment]
https://github.com/stepmania/stepmania/blob/master/NoteSkins/instructions.txt
Since 10 key is fixed now I think we can remove "10(double) Keys Gameplay Broken"
