### ISSUE TITLE
(5.1) No SM saved because split timing was used

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1175]
It gives me that message even though it saved the SM and I was using song timing, not split timing.

**Comment by kyzentun** [comment]
Are you sure the SM file isn't from an earlier save?  Are you sure that *none* of the charts in the simfile use split timing?  Can you upload the simfile to reproduce the bug?

**Comment by 1033Forest** [comment]
https://www.mediafire.com/?iv58kqawtywyltl

This is a simfile I just made, it's not really that good because I just put left arrows and super shuffled everything.

**Comment by kyzentun** [comment]
Cannot reproduce.  You probably had a chart in split timing mode without realizing it.

**Comment by 1033Forest** [comment]
This happens all the time on 5.1, on every simfile I try to save, even though it did save the SM.
