### ISSUE TITLE
New rows to add in the options menu (operator menu)

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1176]
Editor noteskin: I found this row on the Simply Love theme and I think it needs to be added to the default theme. In here you can choose the default noteskin for the editor. This goes under appearance options

3 panel tracks: Now that 3 panel has been fixed (upleft/upright style re-added back, left/right still there), there can be the option to choose from upleft/upright and left/right (DDR Solo let you choose from using diagonals or left/right to hit the first and third tracks). Default is upleft/upright. This goes under advanced options or gameplay options.

**Comment by 1033Forest** [comment]
Editor one seems like a good idea.
3 panel, IDK yet (I only see the arrows being different in 5.1 noteskins, in 5.0 the first and third tracks are still left and right, because apparently they have higher priority than the diagonals)

**Comment by kyzentun** [comment]
Editor noteskin belongs in the editor, not the operator menu.
Choosing different tracks for 3 panel is part of having custom steps types.

**Comment by 1033Forest** [comment]
The editor menu (by pressing Esc) could have a new button: Editor noteskin. In there you can select the noteskin to use in the editor (it will not be saved forever unless you have a profile).
