### ISSUE TITLE
Assist tick roll idea

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1182]
For rolls, have it clap every 0.333 seconds the roll is active.
This can be turned on or off in the operator menu.

**Comment by kyzentun** [comment]
This is impractical and a bad idea.  The roll timing window does not actually match the intended rhythm of the roll.  An assist clap that is the wrong rhythm is bad.  Calculating the intended rhythm from the step chart is impractical because there is a huge variety of weird cases.
