### ISSUE TITLE
Karaoke mode?

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1184]
I see something in the noteskin instructions for an unimplemented karaoke mode. What is this game mode supposed to be for, and why is it there? I think it may never be implemented... should we remove it from the instructions?

I tried to add a noteskin folder for karaoke game mode but it didn't appear in the select game.

**Comment by 1033Forest** [comment]
For auto set style there is a number representing how many panels that particular mode has. I see in the language file, that karaoke is a V. What does the V stand for/mean?
And for lights cabinet mode the number is a !. Lights is not really a game mode, it's only for the arcade light configuration to add lights to certain songs.

**Comment by shakesoda** [comment]
v for voice or vocal.

it's just an old unfinished mode which I don't think anyone is interested in finishing, currently.

**Comment by 1033Forest** [comment]
Yeah. It's like not possible to make a noteskin for it.
And how are you supposed to play it? There's no buttons to hit
