### ISSUE TITLE
(5.1) Autoplay roll issue

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1190]
https://www.mediafire.com/?sf61f37deexau6m Here is the file I am having trouble with.

This file has only one roll on the right arrow. But when Autoplay hits the roll, the left receptor flashes as if it were hitting an invisible roll, but there is no roll there. Is there any bug in the engine, or is it just this simfile?

**Comment by 1033Forest** [comment]
It only happens on this simfile and nothing else.

**Comment by kyzentun** [comment]
This actually happens on 5.0 too, for any chart that has a tap on the same row that a roll starts on.

**Comment by 1033Forest** [comment]
What causes it to happen and will it be fixed in a future SM build?

**Comment by kyzentun** [comment]
https://git.io/voHgx
