### ISSUE TITLE
"Free Performance" mod game crash

### ISSUE THREAD

**Issue by DrBox** [stepmania/stepmania#1191]
Recently in StepF2 V1.12, there's a new mod called Free Performance in which it duplicated your input on both side.
However, if you start the game as both P1 and P2 at the same time (Single mode only) and any of the player enable the mod, the game will crash whenever you start the song
Hope this get fix soon, thanks

**Comment by Fighter19** [comment]
I'm not 100% sure about this, but from what I know, StepF2 uses it's own modified version of Stepmania to allow doing this. Therefor you should ask them (as probably their modification causes the crash).

**Comment by kyzentun** [comment]
Report this bug to the StepF2 team (whoever that may be), not us.
