### ISSUE TITLE
SM properties/options box

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1195]
This separate program can be used instead of manually having to edit metrics.ini if a person makes a change that is irreversable by just using SM (example: mistakenly mapping the enter key for a button other than start, or changing the keys to only dedicated buttons if the dedicated buttons haven't been mapped or the user does not know what the dedicated keys are). This can also be used if the computer or keyboard the user is using does not have an operator (scroll lock) key.

**Comment by kyzentun** [comment]
Key mappings aren't in metrics.ini.

There is already a debug menu option for resetting the key mapping.

Mapping the enter key to something else is fine.

The key mapping screen already has logic to ensure that Start, Left, and Right are all mapped before
allowing the player to save the current mapping.

**Comment by 1033Forest** [comment]
I saw an issue on Yahoo Answers 2 or 3 years ago about how some guy accidentally mapped the enter key as the left arrow and is trying to get back to normal key maps because of that. And another guy on another website accidentally mapped his enter key to up arrow.

**Comment by shakesoda** [comment]
And in the meantime it's been fixed.
