### ISSUE TITLE
Error Playing Command

### ISSUE THREAD

**Issue by AishaEM** [stepmania/stepmania#1199]
I got an Error Playing Command while loading the menu screen when you open the game, it has something to do with the theme, or my version... Help me!!!!!!!!

(https://cloud.githubusercontent.com/assets/20213197/16467136/f913f56e-3e13-11e6-9347-c61142ca76a0.png)

**Comment by kyzentun** [comment]
That theme does not support SM5 beta 4.  Update to a newer version.  I think the readme for spawncamping-wallhack says it only supports 5.1 Alpha 2.
