### ISSUE TITLE
Notefield not showing up for this particular song (I think there may be some others like that too)

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1200]
Nothing shows up on the notefield for this song (no receptors or anything). And it says the percentage I got is -1.#J%.

https://www.mediafire.com/?94in51hw1nc0gtc
What is wrong with this file?

**Comment by kyzentun** [comment]
The space on the end of the description wasn't handled right.
https://github.com/stepmania/stepmania/commit/2a2007b9c89ff9c3a21a393add4c6da6a8173dab

**Comment by 1033Forest** [comment]
What is with the weird percentages that appear on certain songs, which appear when I fail a song, or it gets autoplayed?
