### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by jamuwu** [stepmania/stepmania#1201]
```
Linking CXX executable ../../stepmania
/usr/bin/ld: ../../extern/libmmmagic/linux-32bit/libmmmagic.a(mmmagic.o): Relocations in generic ELF (EM: 3)
/usr/bin/ld: ../../extern/libmmmagic/linux-32bit/libmmmagic.a(mmmagic.o): Relocations in generic ELF (EM: 3)
../../extern/libmmmagic/linux-32bit/libmmmagic.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
src/CMakeFiles/StepMania.dir/build.make:10450: recipe for target '../stepmania' failed
make[2]: *** [../stepmania] Error 1
CMakeFiles/Makefile2:388: recipe for target 'src/CMakeFiles/StepMania.dir/all' failed
make[1]: *** [src/CMakeFiles/StepMania.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by kyzentun** [comment]
Are you building on a 32 bit system?

**Comment by jamesguessis** [comment]
I am building on a 64 bit system

**Comment by kyzentun** [comment]
What is the first line of Build/CMakeFiles/CMakeOutput.log?

Mine is: The system is: Linux - 3.16.0-4-amd64 - x86_64

The cmake file for libmmmagic needs to be modified to check for 64 bit correctly. (https://github.com/stepmania/stepmania/blob/master/extern/CMakeProject-mmmagic.cmake)

**Comment by jamesguessis** [comment]
oh
so I guess I'm actually trying to build on an arm processor 
`The system is: Linux - 4.4.11-v7+ - armv7l`

**Comment by kyzentun** [comment]
This thread of people trying to use a pi is probably relevant to you: http://www.stepmania.com/forums/stepmania-development/show/5825

**Comment by jamesguessis** [comment]
I get the same error following those instructions (replacing /home/pi with my home directory of course)

**Comment by wolfman2000** [comment]
@jamesguessis How many bits does that processor use?

Allowing for better handling of 32/64 bit systems is on the TODO list. I may not personally get to it until mid July, but others may beat me to it.

**Comment by jamesguessis** [comment]
it's a 64 bit processor I do know that

**Comment by ajs124** [comment]
There are more differences to processors than 32 and 64 bit. @jamesguessis is running this on an ARM chip, whereas the libraries are x86 and x86_64.
