### ISSUE TITLE
Option to randomly quantize arrows

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1204]
Also another feature from pulsen. In there, it will give each note a random color no matter what quantization it is.

Example: https://twitter.com/PulsenGame/status/729003649381236736 (This will also randomly quantize mines, lifts, or any other item that is quantized)

**Comment by kyzentun** [comment]
"Took me weeks to write this code!"

Excuse me while I die laughing.  If it's hardcoded into the engine, that should take *minutes*, not weeks.

**Comment by 1033Forest** [comment]
Well, I think this can easily be done in the newfield... I've seen your video where you quantize notes by Y offset. So it's possible to quantize notes not by beat, but by other things too. Which means, random note quantizations should be possible.

**Comment by kyzentun** [comment]
Possible as of now, but not in the mods menu because I'm lazy.  https://github.com/stepmania/stepmania/commit/b06ec6093b5f09f270f6c372a85a2062a8a41501
