### ISSUE TITLE
[Feature Request] Allow alternate path for user directory on Windows

### ISSUE THREAD

**Issue by Prcuvu** [stepmania/stepmania#1205]
As far as I know, it is recommended to store downloaded contents in user directory, which is located in `%AppData%` on Windows.
Some players have allocated small amount of space for their system drive, which is not enough for storing huge amount of song packs. So they place their song packs under installation path.
I suggest implementing adjustable user directory path on Windows.
Reference: #67 #864

**Comment by kyzentun** [comment]
[Feature Request] Inform users of the AdditionalSongFolders preference

**Comment by Prcuvu** [comment]
That's something likely to miss.

**Comment by kyzentun** [comment]
There is also an AdditionalFolders preference, which I think allows putting themes and noteskins in other places.

**Comment by Prcuvu** [comment]
Yes, I've experimented with them. Thank you very much.

**Comment by Prcuvu** [comment]
By the way, is it possible to specify multiple paths?

**Comment by kyzentun** [comment]
Yes, it's a comma separated list.

**Comment by Prcuvu** [comment]
I have tried this out, StepMania still writes profiles, edits and screenshots to the `%AppData%` directory. Maybe creating a symbolic link is the only solution for this.
