### ISSUE TITLE
Random speed mod?

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1206]
I've seen an old speed modifier "Randomspeed" in older SM versions.
Example:
Speed,12=mod,1x,200% randomspeed;name,Random

What this does, is gives each note a random speed mod. This is also a feature in Pulsen too. Does it still exist, and if it does, will it be added back into the game?

**Comment by kyzentun** [comment]
Possible as of now, but not in the mods menu because I'm lazy.  https://github.com/stepmania/stepmania/commit/b06ec6093b5f09f270f6c372a85a2062a8a41501
