### ISSUE TITLE
Crash when I try to start making a file

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1210]
Attempted to make a file (all I did was put the BPM on it) and it crashed. I don't have the .sm file because it crashed before it even started saving the file.

StepMania5.1-git-767999d crash report (build 767999d, 20160623 @ 05:58:43)
--------------------------------------

Crash reason: Unhandled Microsoft C++ Exception

Thread: Main thread
        RageFileDriverDirectHelpers.cpp:237 C:/Users/1033Forest/AppData/Roaming/StepMania 5/RandomMovies/*
        RageFileDriverDirectHelpers.cpp:237 C:/Users/1033Forest/AppData/Roaming/StepMania 5/RandomMovies/Joke Charts/*
        RageFileDriverDirectHelpers.cpp:237 C:/Games/StepMania 5/BackgroundEffects/*
        RageFileDriverDirectHelpers.cpp:237 C:/Users/1033Forest/AppData/Roaming/StepMania 5/BackgroundEffects/*
        RageTextureManager.cpp:146 RageTextureManager::LoadTexture(/Songs/Joke Charts/Paperclip/Paperclip.avi).
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:203 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:203 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:203 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:203 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:203 Processing the sound while buffers are available.
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:788 
        InputHandler_DirectInput.cpp:759 
        InputHandler_DirectInput.cpp:783 
        InputHandler_DirectInput.cpp:788 
        InputHandler_DirectInput.cpp:759 
Thread: Streaming sound buffering
76c3c54f: KERNELBASE!RaiseException [76c30000+c4f7+58]
76c3c54f: KERNELBASE!RaiseException [76c30000+c4f7+58]
00208502: StepMania!00140000
006c6e87: StepMania!00140000
00650a30: StepMania!00140000
0065160e: StepMania!00140000
7713f8e1: ntdll!NtWaitForSingleObject [77120000+1f8cc+15]
76c415ce: KERNELBASE!WaitForSingleObjectEx [76c30000+11536+98]
76c41601: KERNELBASE!WaitForSingleObjectEx [76c30000+11536+cb]
001ffe87: StepMania!00140000
00207ef6: StepMania!00140000
00207ef6: StepMania!00140000
004c85c4: StepMania!00140000
7714e40c: ntdll!RtlInitUnicodeString [77120000+2e2a8+164]
7714e172: ntdll!RtlAllocateHeap [77120000+2e0c6+ac]
004c85c4: StepMania!00140000
004c86a4: StepMania!00140000
002083e8: StepMania!00140000
004c8539: StepMania!00140000
7714e40c: ntdll!RtlInitUnicodeString [77120000+2e2a8+164]
00207ef6: StepMania!00140000
7713fbb1: ntdll!NtReleaseMutant [77120000+1fb9c+15]
76c410d3: KERNELBASE!ReleaseMutex [76c30000+110c3+10]
003b2721: StepMania!00140000
76a814bd: kernel32!HeapFree [76a70000+114a9+14]
7714e40c: ntdll!RtlInitUnicodeString [77120000+2e2a8+164]
7714e172: ntdll!RtlAllocateHeap [77120000+2e0c6+ac]
00504d70: StepMania!00140000
00504d88: StepMania!00140000
002018ab: StepMania!00140000
00207ef6: StepMania!00140000
00207ef6: StepMania!00140000
00201204: StepMania!00140000
00208502: StepMania!00140000
003a5bd2: StepMania!00140000
00207ef6: StepMania!00140000
003a3939: StepMania!00140000
003a486f: StepMania!00140000
003a4dc4: StepMania!00140000
006cafa9: StepMania!00140000
003a4dd9: StepMania!00140000
003a1bc8: StepMania!00140000
006c91e3: StepMania!00140000
003a1b8c: StepMania!00140000
00207ef6: StepMania!00140000
002083e8: StepMania!00140000
004f9143: StepMania!00140000
002c2614: StepMania!00140000
004f8f62: StepMania!00140000
002c2614: StepMania!00140000
002ea28c: StepMania!00140000
002083e8: StepMania!00140000
002e9809: StepMania!00140000
002e97cf: StepMania!00140000
7714e0a3: ntdll!RtlFreeHeap [77120000+2e025+7e]
7713fbb1: ntdll!NtReleaseMutant [77120000+1fb9c+15]
76c410d3: KERNELBASE!ReleaseMutex [76c30000+110c3+10]
003b2721: StepMania!00140000
003b2787: StepMania!00140000
003dbef4: StepMania!00140000
0050067d: StepMania!00140000
0024d58f: StepMania!00140000
0024d5ad: StepMania!00140000
00622292: StepMania!00140000
002d181d: StepMania!00140000
0062ea68: StepMania!00140000
002083e8: StepMania!00140000
002c01d9: StepMania!00140000
002c02d5: StepMania!00140000
002be816: StepMania!00140000
002bdb98: StepMania!00140000
002d181d: StepMania!00140000
003b2787: StepMania!00140000
003dbef4: StepMania!00140000
0050067d: StepMania!00140000
76a814bd: kernel32!HeapFree [76a70000+114a9+14]
006c870c: StepMania!00140000
002d1c11: StepMania!00140000
002d1c2d: StepMania!00140000
002083e8: StepMania!00140000
002d1fab: StepMania!00140000
7714e40c: ntdll!RtlInitUnicodeString [77120000+2e2a8+164]
00524528: StepMania!00140000
00207ef6: StepMania!00140000
7714e40c: ntdll!RtlInitUnicodeString [77120000+2e2a8+164]
0025abae: StepMania!00140000
7714e40c: ntdll!RtlInitUnicodeString [77120000+2e2a8+164]
7714e172: ntdll!RtlAllocateHeap [77120000+2e0c6+ac]
006cafa9: StepMania!00140000
7714e0a3: ntdll!RtlFreeHeap [77120000+2e025+7e]
7714e0a3: ntdll!RtlFreeHeap [77120000+2e025+7e]
76a814bd: kernel32!HeapFree [76a70000+114a9+14]
002f5488: StepMania!00140000
002f75b0: StepMania!00140000
7714e40c: ntdll!RtlInitUnicodeString [77120000+2e2a8+164]
7714e172: ntdll!RtlAllocateHeap [77120000+2e0c6+ac]
7714e40c: ntdll!RtlInitUnicodeString [77120000+2e2a8+164]
0021b82b: StepMania!00140000
0021be90: StepMania!00140000

Static log:
StepMania5.1-git-767999d
Compiled 20160623 @ 05:58:43 (build 767999d)
Log starting 2016-07-01 09:38:44
Loading window: win32
Windows 6.1 (Win7) build 7601 [Service Pack 1]
Memory: 4060mb total, 4095mb swap (3451mb swap avail)
Video driver: Intel(R) G45/G43 Express Chipset [Intel Corporation]
              8.15.10.1840, 7-3-2009 [pci\ven_8086&dev_2e22]
WARNING: RegOpenKeyEx(%p,%s) error (The system cannot find the file specified.)
Sound device 0: Speakers (High Definition Audio, 0.0, MID 1, PID 65535 
WARNING: Error loading noteskin '/NewSkins/babykai/noteskin.lua': /NewSkins/babykai/noteskin.lua:1: unexpected symbol near 'ï'
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Lights driver: SystemMessage
Lights driver: Export
WARNING: Video renderer list has been changed from 'd3d,opengl' to 'opengl'
Video renderers: 'opengl'
Mode: ICD 32 (888) 8 alpha 16 depth 64 accum 
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: Intel
OGL Renderer: Intel(R) G45/G43 Express Chipset
OGL Version: 2.1.0 - Build 8.15.10.1840
OGL Max texture size: 4096
OGL Texture units: 8
GLU Version: 1.2.2.0 Microsoft Corporation
OGL Extensions:
  GL_3DFX_texture_compression_FXT1
  GL_ARB: color_buffer_float, depth_texture, draw_buffers, fragment_program, fragment_shader, half_float_pixel, 
    multitexture, occlusion_query, pixel_buffer_object, point_parameters, point_sprite, shader_objects, 
    shading_language_100, shadow, texture_border_clamp, texture_compression, texture_cube_map, texture_env_add, 
    texture_env_combine, texture_env_crossbar, texture_env_dot3, texture_float, texture_non_power_of_two, 
    texture_rectangle, transpose_matrix, vertex_buffer_object, vertex_program, vertex_shader, window_pos
  GL_ATI_separate_stencil
  GL_EXT: abgr, bgra, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, blend_subtract, 
    clip_volume_hint, compiled_vertex_array, draw_range_elements, fog_coord, framebuffer_object, 
    multi_draw_arrays, packed_pixels, rescale_normal, secondary_color, separate_specular_color, shadow_funcs, 
    stencil_two_side, stencil_wrap, texture3D, texture_compression_s3tc, texture_env_add, texture_env_combine, 
    texture_filter_anisotropic, texture_lod_bias, texture_rectangle, texture_sRGB, texture_swizzle
  GL_IBM_texture_mirrored_repeat
  GL_NV: blend_square, conditional_render, texgen_reflection
  GL_SGIS: generate_mipmap, texture_edge_clamp, texture_lod
  GL_WIN_swap_hint
OpenGL Windowed 854x480 16 color 16 texture 60Hz Vsync NoSmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 2 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Mouse' axes: 3, hats: 0, buttons: 3 (buffered)
WARNING: Startup time: 7.2430000305176
Players joined: P1
Lost focus to: StepMania.exe
Top Screen: ScreenEdit
Language: en
Current renderer: OpenGL
Theme: consensual-master

Partial log:
00:29.822: glTexImage2D (format GL_RGBA4, 128x256, format GL_RGBA, type GL_UNSIGNED_BYTE, pixfmt 2, imgpixfmt 0)
00:29.827: glTexImage2D (format GL_RGBA4, 64x64, format GL_RGBA, type GL_UNSIGNED_BYTE, pixfmt 2, imgpixfmt 0)
00:29.829: glTexImage2D (format GL_RGBA4, 256x128, format GL_RGBA, type GL_UNSIGNED_BYTE, pixfmt 2, imgpixfmt 0)
00:29.832: glTexImage2D (format GL_RGBA4, 256x128, format GL_RGBA, type GL_UNSIGNED_BYTE, pixfmt 2, imgpixfmt 0)
00:29.850: Loading /Songs/Joke Charts/Paperclip/Paperclip.avi, type FileType_Movie
00:29.850: Movie /Songs/Joke Charts/Paperclip/Paperclip.avi has handler 'H264', type 'H264'
00:29.850: Initializing driver: FFMpeg
00:29.850: MovieTexture_Generic::MovieTexture_Generic(/Songs/Joke Charts/Paperclip/Paperclip.avi)
00:29.871: Opening codec h264
00:29.872: Bitrate: 0

-- End of report

**Comment by kyzentun** [comment]
Crash fixed, but the video won't play because it's encoded wrong.  https://github.com/stepmania/stepmania/commit/b06ec6093b5f09f270f6c372a85a2062a8a41501
