### ISSUE TITLE
[5.1-git] Force ITG (lower) placement of notefield in defective mode.

### ISSUE THREAD

**Issue by MrThatKid** [stepmania/stepmania#1211]
In older builds of 5.1, I could set where the defective mode playfield was placed in options (either normal, which is too high, or lower, which is probably ITG placement). This option no longer exists (from what I can tell).
In TaroNuke's Iris stage (on expert difficulty), there's a section that replicates Cytus. (also effectively contains the Driven Drop effect)
The first sign that the notefield is too high is that the line that marks the playfield receptors is too low.
The next sign is that the arrows slowly slide in the direction the playfield is going.
Ex: If playfield drops down, the arrows slowly slide down.
That problem happens in other mod courses that use the Driven Drop effect.
This didn't happen if the playfield was set to 'lower', which made everything look and work as intended.
Version: StepMania5.1-git-b06ec60
Compiled 20160701 @ 17:18:16 (build b06ec60) on Ubuntu 16.04, 64-bit.

**Comment by kyzentun** [comment]
I've mysteriously lost my copy of Iris, so I'm just going to throw in the values from Simply Love 3.95.

https://github.com/stepmania/stepmania/commit/b06ec6093b5f09f270f6c372a85a2062a8a41501
