### ISSUE TITLE
This isnt an issue but something i dont want.

### ISSUE THREAD

**Issue by AishaEM** [stepmania/stepmania#1212]
is there some way to hide these things while playing?
![ss 2016-07-01 at 05 05 00](https://cloud.githubusercontent.com/assets/20213197/16534478/0561215c-3fae-11e6-96b6-266f09b04940.png)

**Comment by AishaEM** [comment]
Does anyone know how to remove this?

**Comment by ZeroTheSavior** [comment]
Control with PlayerOptions in [Gameplay] in metrics.ini

You'll have a much better time using the forums or Zenius I Vanisher
