### ISSUE TITLE
.mgd file support?

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1216]
.mgd is the file format in Mungyodance games. That way, people who have Mungyodance who want to play the official Mungyodance songs can just copy them over to the SM songs folder, and play them right in SM, while keeping the double and triple digit difficulty ratings.

**Comment by kyzentun** [comment]
Renard has previously released sm format simfiles for the Mungyodance songs.
Double and triple digit difficulty ratings work just fine in stepmania.

**Comment by 1033Forest** [comment]
T his could be for people who want the full MGD experience (BG videos, which aren't available in the actual MGD packs downloadable for SM, and the 2-3 digit ratings).

**Comment by dguzek** [comment]
> This could be for people who want the full MGD experience

People who want the "full MGD experience" should probably just play Mungyodance.

**Comment by 1033Forest** [comment]
Yeah, but for people who want it in their SM, they could just copy the song files from MGD and paste them if they wanted to play in SM. (Even though .mgd is not supported yet)

**Comment by shakesoda** [comment]
I don't know why we'd support these - SM's job isn't to support other people's pack formats, especially not for something like MGD (which, as already said, had content released in a reasonable form for SM *already*).

Just make a converter or extract the extra files the hard way. It's not worth it for us to support a one-off format that nobody can even make new content for.

**Comment by 1033Forest** [comment]
Can I PR in the .mgd notesloader, or will it be rejected?

**Comment by shakesoda** [comment]
Yes, for the above reason of it being out of scope and not really worthwhile.
