### ISSUE TITLE
Mine explosions not showing up in ANY noteskin I use

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1228]
No matter what the noteskin, there's no mine explosion. Even on classic noteskins like Jousway's 3.9 for 5.1. Why is that?

**Comment by kyzentun** [comment]
I didn't bother to copy the mine explosion graphics for any I ported, and Jousway didn't bother to do mine explosion graphics for any he ported.

**Comment by 1033Forest** [comment]
Can I PR in a mine explosion graphic so fallback noteskins can use it?
