### ISSUE TITLE
[5.1] Hold Judgments don't show up.

### ISSUE THREAD

**Issue by MrThatKid** [stepmania/stepmania#1229]
In Stepmania 5.1, find a song that uses hold (or roll) notes.
During the song, when these notes finish, no OK!/NG* judgements that happen when you complete/drop a hold/roll note appear at all.
This was tested with the default theme and the smFiftyOne theme, and happens in both (even though they have graphics for hold judgments)
* (Replace "OK!/NG" with what your current theme uses for hold judgments instead)

Version: StepMania5.1-git-f1dc5f3
Compiled 20160715 @ 17:31:21 (build f1dc5f3) on Ubuntu 16.04, 64-bit.

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/commit/43cdf5f3ceeecac703799d28d5376cfcdd30a9cd
https://github.com/ListenerJubatus/smtheme-fiftyOne/pull/8
