### ISSUE TITLE
(5.1) SM Froze on me!

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1230]
I was in the middle of editing a file, and it froze on me, and when I tried to exit out in task manager it didn't exit out, it doesn't even close!

Freezing happened 23:16:12. And I started at 23:01:41. Can't post log since it exceeds the maximum character limit.

**Comment by kyzentun** [comment]
If anything in the log is useful, it would only be the end, the last 100 or so lines.  Any idea how to reproduce the freeze?

**Comment by 1033Forest** [comment]
IDK, it just randomly happened when I was trying to edit my file

Didn't catch anything after 10...
10:00.544: 33 FPS, 50 av FPS, 8178 VPF, OpenGL
10:00.710: Approximate sound time: driver frame 26479089, m_pImpl->m_Queue frame 4997376..5004288 (dist 527), closest position is 4997376
10:01.545: 31 FPS, 50 av FPS, 8215 VPF, OpenGL
10:01.721: Approximate sound time: driver frame 26523632, m_pImpl->m_Queue frame 5025024..5031936 (dist 16), closest position is 5025024
10:02.572: 29 FPS, 49 av FPS, 8303 VPF, OpenGL
10:02.878: Approximate sound time: driver frame 26574715, m_pImpl->m_Queue frame 5025024..5031936 (dist 133), closest position is 5025024
10:03.585: 30 FPS, 49 av FPS, 8241 VPF, OpenGL
10:03.966: Approximate sound time: driver frame 26622645, m_pImpl->m_Queue frame 5045760..5052672 (dist 331), closest position is 5045760
10:04.599: 28 FPS, 48 av FPS, 8204 VPF, OpenGL
10:05.620: 30 FPS, 48 av FPS, 8163 VPF, OpenGL
10:06.205: Approximate sound time: driver frame 26721437, m_pImpl->m_Queue frame 5080320..5087232 (dist 867), closest position is 5080320
10:06.645: 27 FPS, 48 av FPS, 8211 VPF, OpenGL
10:07.674: 29 FPS, 47 av FPS, 8309 VPF, OpenGL
10:07.840: Approximate sound time: driver frame 26793500, m_pImpl->m_Queue frame 5107968..5114880 (dist 484), closest position is 5107968
10:08.703: 30 FPS, 47 av FPS, 8292 VPF, OpenGL
10:08.862: Approximate sound time: driver frame 26838616, m_pImpl->m_Queue frame 5135616..5142528 (dist 424), closest position is 5135616
10:09.715: 31 FPS, 47 av FPS, 8212 VPF, OpenGL
10:09.893: Approximate sound time: driver frame 26884040, m_pImpl->m_Queue frame 5156352..5163264 (dist 56), closest position is 5156352
10:10.723: 30 FPS, 48 av FPS, 8314 VPF, OpenGL
10:11.740: 30 FPS, 46 av FPS, 8326 VPF, OpenGL
10:12.003: Approximate sound time: driver frame 26977100, m_pImpl->m_Queue frame 5184000..5190912 (dist 180), closest position is 5184000
10:12.766: 28 FPS, 46 av FPS, 8349 VPF, OpenGL
10:13.238: Approximate sound time: driver frame 27031524, m_pImpl->m_Queue frame 5197824..5204736 (dist 28), closest position is 5197824
10:13.793: 28 FPS, 46 av FPS, 8376 VPF, OpenGL
10:14.110: not stopping a sound because it's not playing
10:14.110: not stopping a sound because it's not playing
10:14.110: not stopping a sound because it's not playing
10:14.110: not stopping a sound because it's not playing
10:14.153: Loading /Songs/My stuff/Lookin' Like Magic/Daniella Monet - Lookin' Like Magic feat. Drake Bell ( Official Music Video ).avi, type FileType_Movie
10:14.153: Movie /Songs/My stuff/Lookin' Like Magic/Daniella Monet - Lookin' Like Magic feat. Drake Bell ( Official Music Video ).avi has handler 'H264', type 'H264'
10:14.153: Initializing driver: FFMpeg
10:14.153: MovieTexture_Generic::MovieTexture_Generic(/Songs/My stuff/Lookin' Like Magic/Daniella Monet - Lookin' Like Magic feat. Drake Bell ( Official Music Video ).avi)
10:14.171: Opening codec h264
10:14.172: Bitrate: 0
10:14.172: Codec pixel format: yuv420p
10:14.172: Texture pixel format: 1 0 (32bpp, 000000ff 0000ff00 00ff0000 ff000000)
10:14.174: glTexImage2D (format GL_RGBA8, 427x480, format GL_RGBA, type GL_UNSIGNED_BYTE, pixfmt 0, imgpixfmt 0)
10:14.182: Expect 0.000000, got 0.040000 -> 0.040000
10:14.182: Resolution: 854x480 (854x480, 1024x512)
10:14.201: Created movie texture "/Songs/My stuff/Lookin' Like Magic/Daniella Monet - Lookin' Like Magic feat. Drake Bell ( Official Music Video ).avi" with driver "FFMpeg"
10:14.203: Loading /Themes/consensual-master/Graphics/Common fallback background.lua, type FileType_Lua
10:14.203: Starting playback at 26.621088
10:14.214: Seek to 0.000000
10:14.251: Approximate sound time: driver frame 27076204, m_pImpl->m_Queue frame 12026880..12028928 (dist 5524), closest position is 12026880
10:14.252: Opening codec h264
10:14.382: Expect 0.000000, got 0.040000 -> 0.040000
10:14.803: 39 FPS, 46 av FPS, 2993 VPF, OpenGL
10:15.817: 49 FPS, 46 av FPS, 1399 VPF, OpenGL
10:16.819: 56 FPS, 47 av FPS, 1395 VPF, OpenGL
10:17.838: 56 FPS, 46 av FPS, 1393 VPF, OpenGL
10:18.848: 60 FPS, 47 av FPS, 1377 VPF, OpenGL
10:19.313: Approximate sound time: driver frame 27299448, m_pImpl->m_Queue frame 2921130..2924615 (dist 3051), closest position is 2921130
10:19.313: not stopping a sound because it's not playing
10:19.313: not stopping a sound because it's not playing
10:19.875: 44 FPS, 46 av FPS, 4073 VPF, OpenGL
10:20.611: Approximate sound time: driver frame 27356687, m_pImpl->m_Queue frame 5232384..5239296 (dist 497), closest position is 5232384
10:20.892: 30 FPS, 46 av FPS, 8293 VPF, OpenGL
10:21.921: 30 FPS, 46 av FPS, 8319 VPF, OpenGL
10:22.948: 28 FPS, 46 av FPS, 8351 VPF, OpenGL
10:23.062: not stopping a sound because it's not playing
10:23.062: not stopping a sound because it's not playing
10:23.062: not stopping a sound because it's not playing
10:23.062: not stopping a sound because it's not playing
10:23.078: Loading /Songs/My stuff/Lookin' Like Magic/Daniella Monet - Lookin' Like Magic feat. Drake Bell ( Official Music Video ).avi, type FileType_Movie
10:23.078: Movie /Songs/My stuff/Lookin' Like Magic/Daniella Monet - Lookin' Like Magic feat. Drake Bell ( Official Music Video ).avi has handler 'H264', type 'H264'
10:23.078: Initializing driver: FFMpeg
10:23.078: MovieTexture_Generic::MovieTexture_Generic(/Songs/My stuff/Lookin' Like Magic/Daniella Monet - Lookin' Like Magic feat. Drake Bell ( Official Music Video ).avi)
10:23.096: Opening codec h264
10:23.097: Bitrate: 0
10:23.097: Codec pixel format: yuv420p
10:23.097: Texture pixel format: 1 0 (32bpp, 000000ff 0000ff00 00ff0000 ff000000)
10:23.097: glTexImage2D (format GL_RGBA8, 427x480, format GL_RGBA, type GL_UNSIGNED_BYTE, pixfmt 0, imgpixfmt 0)
10:23.114: Expect 0.000000, got 0.040000 -> 0.040000
10:23.114: Resolution: 854x480 (854x480, 1024x512)
10:23.130: Created movie texture "/Songs/My stuff/Lookin' Like Magic/Daniella Monet - Lookin' Like Magic feat. Drake Bell ( Official Music Video ).avi" with driver "FFMpeg"
10:23.132: Loading /Themes/consensual-master/Graphics/Common fallback background.lua, type FileType_Lua
10:23.132: Starting playback at 27.725985
10:23.145: Seek to 0.000000
10:23.177: Approximate sound time: driver frame 27469907, m_pImpl->m_Queue frame 12264448..12265472 (dist 6061), closest position is 12264448
10:23.180: Opening codec h264
10:23.212: Expect 0.000000, got 0.040000 -> 0.040000
10:23.956: 50 FPS, 47 av FPS, 1805 VPF, OpenGL
10:24.956: 52 FPS, 47 av FPS, 1403 VPF, OpenGL
10:25.960: 58 FPS, 47 av FPS, 1383 VPF, OpenGL
10:26.960: 59 FPS, 47 av FPS, 1375 VPF, OpenGL
10:27.396: not stopping a sound because it's not playing
10:27.396: not stopping a sound because it's not playing
10:27.396: not stopping a sound because it's not playing
10:27.984: 43 FPS, 46 av FPS, 4260 VPF, OpenGL
10:28.997: 30 FPS, 46 av FPS, 8089 VPF, OpenGL
10:30.026: 32 FPS, 45 av FPS, 8282 VPF, OpenGL
10:30.225: Approximate sound time: driver frame 27780649, m_pImpl->m_Queue frame 5260032..5266944 (dist 471), closest position is 5260032
10:31.065: 33 FPS, 44 av FPS, 8238 VPF, OpenGL
10:31.742: Approximate sound time: driver frame 27847591, m_pImpl->m_Queue frame 5287680..5294592 (dist 89), closest position is 5287680
10:32.080: 32 FPS, 45 av FPS, 8164 VPF, OpenGL
10:33.010: Approximate sound time: driver frame 27903520, m_pImpl->m_Queue frame 5315328..5322240 (dist 480), closest position is 5315328
10:33.088: 32 FPS, 46 av FPS, 8193 VPF, OpenGL
10:34.076: Approximate sound time: driver frame 27950535, m_pImpl->m_Queue frame 5356800..5363712 (dist 569), closest position is 5356800
10:34.108: 32 FPS, 45 av FPS, 8205 VPF, OpenGL
10:35.121: 31 FPS, 45 av FPS, 8202 VPF, OpenGL
10:35.121: Approximate sound time: driver frame 27996574, m_pImpl->m_Queue frame 5398272..5405184 (dist 610), closest position is 5398272
10:36.134: 33 FPS, 45 av FPS, 8196 VPF, OpenGL
10:36.312: Approximate sound time: driver frame 28049100, m_pImpl->m_Queue frame 5439744..5446656 (dist 308), closest position is 5439744
10:37.163: 29 FPS, 44 av FPS, 8334 VPF, OpenGL
10:37.289: not stopping a sound because it's not playing
10:37.289: not stopping a sound because it's not playing
10:37.289: not stopping a sound because it's not playing
10:37.289: not stopping a sound because it's not playing
10:37.289: Starting playback at 30.764448
10:37.313: Approximate sound time: driver frame 28093240, m_pImpl->m_Queue frame 12464128..12465152 (dist 6344), closest position is 12464128
10:38.169: 93 FPS, 46 av FPS, 1448 VPF, OpenGL
10:38.604: not stopping a sound because it's not playing
10:38.604: not stopping a sound because it's not playing
10:38.604: not stopping a sound because it's not playing
10:39.190: 65 FPS, 45 av FPS, 2965 VPF, OpenGL
10:39.585: not stopping a sound because it's not playing
10:39.585: not stopping a sound because it's not playing
10:39.585: not stopping a sound because it's not playing
10:39.585: not stopping a sound because it's not playing
10:39.585: Starting playback at 30.764448
10:39.599: Approximate sound time: driver frame 28194120, m_pImpl->m_Queue frame 12534784..12535808 (dist 6840), closest position is 12534784
10:40.193: 74 FPS, 46 av FPS, 2326 VPF, OpenGL
10:41.197: 103 FPS, 47 av FPS, 1078 VPF, OpenGL
10:42.205: 110 FPS, 48 av FPS, 1078 VPF, OpenGL
10:43.206: 103 FPS, 48 av FPS, 1066 VPF, OpenGL
10:44.210: 115 FPS, 49 av FPS, 1059 VPF, OpenGL
10:45.213: 111 FPS, 49 av FPS, 1047 VPF, OpenGL
10:46.217: 110 FPS, 50 av FPS, 1079 VPF, OpenGL
10:47.217: 114 FPS, 51 av FPS, 1068 VPF, OpenGL
10:48.222: 114 FPS, 51 av FPS, 1055 VPF, OpenGL
10:49.228: 105 FPS, 52 av FPS, 1079 VPF, OpenGL
10:50.230: 112 FPS, 52 av FPS, 1080 VPF, OpenGL
10:51.020: not stopping a sound because it's not playing
10:51.020: not stopping a sound because it's not playing
10:51.020: not stopping a sound because it's not playing
10:51.260: 89 FPS, 51 av FPS, 1664 VPF, OpenGL
10:51.578: Approximate sound time: driver frame 28722369, m_pImpl->m_Queue frame 5474304..5481216 (dist 831), closest position is 5474304
10:52.271: 27 FPS, 51 av FPS, 8888 VPF, OpenGL
10:53.286: 28 FPS, 51 av FPS, 8931 VPF, OpenGL
10:53.288: not stopping a sound because it's not playing
10:53.288: not stopping a sound because it's not playing
10:53.288: not stopping a sound because it's not playing
10:53.288: not stopping a sound because it's not playing
10:53.337: Loading /Songs/My stuff/Lookin' Like Magic/Daniella Monet - Lookin' Like Magic feat. Drake Bell ( Official Music Video ).avi, type FileType_Movie
10:53.337: Movie /Songs/My stuff/Lookin' Like Magic/Daniella Monet - Lookin' Like Magic feat. Drake Bell ( Official Music Video ).avi has handler 'H264', type 'H264'
10:53.337: Initializing driver: FFMpeg
10:53.337: MovieTexture_Generic::MovieTexture_Generic(/Songs/My stuff/Lookin' Like Magic/Daniella Monet - Lookin' Like Magic feat. Drake Bell ( Official Music Video ).avi)
10:53.354: Opening codec h264
10:53.356: Bitrate: 0
10:53.356: Codec pixel format: yuv420p
10:53.356: Texture pixel format: 1 0 (32bpp, 000000ff 0000ff00 00ff0000 ff000000)
10:53.356: glTexImage2D (format GL_RGBA8, 427x480, format GL_RGBA, type GL_UNSIGNED_BYTE, pixfmt 0, imgpixfmt 0)
10:53.374: Expect 0.000000, got 0.040000 -> 0.040000
10:53.374: Resolution: 854x480 (854x480, 1024x512)
10:53.392: Created movie texture "/Songs/My stuff/Lookin' Like Magic/Daniella Monet - Lookin' Like Magic feat. Drake Bell ( Official Music Video ).avi" with driver "FFMpeg"
10:53.392: Loading /Themes/consensual-master/Graphics/Common fallback background.lua, type FileType_Lua
10:53.393: Starting playback at -1.001312
10:53.414: Approximate sound time: driver frame 28803346, m_pImpl->m_Queue frame 13050880..13051904 (dist 6894), closest position is 13050880
10:54.169: not stopping a sound because it's not playing

**Comment by shakesoda** [comment]
This isn't fixable unless it can be reproduced.

**Comment by 1033Forest** [comment]
It just randomly happened when I was trying to edit a file. I don't know or remember what key combination caused it...
