### ISSUE TITLE
Color effects not working in BGscripts?

### ISSUE THREAD

**Issue by ListenerJubatus** [stepmania/stepmania#1232]
I mean color effects as in when the code is
`60.000=song-bg.png=1.000=0=0=1====#FFFF00=,`

Basically, the color changes aren't coming up,

**Comment by kyzentun** [comment]
Stick a backslash in front of the # symbol.

**Comment by ListenerJubatus** [comment]
As we established, that didn't work.

**Comment by kyzentun** [comment]
I used edit mode to stick some bg changes in a test sim, random anime screenshots.
http://i.imgur.com/oiUleQV.png

It saved like this:
```
#BGCHANGES:0.000=vlcsnap-2016-09-03-00h27m26s389.png=1.000=1=0=1=Centered==CrossFade=#FF0000=#00FF00,
8.000=vlcsnap-2016-09-03-00h27m32s468.png=1.000=0=0=1====#FFFFFF=,
16.000=vlcsnap-2016-09-03-00h28m14s342.png=1.000=0=0=1====#808080=,
24.000=vlcsnap-2016-09-03-14h55m04s015.png=1.000=0=0=1====#00FF00=,
99999=-nosongbg-=1.000=0=0=0 // don't automatically add -songbackground-
;
```

The color changes all showed up, so I think the BackgroundEffect file you're using doesn't use the color variable.

**Comment by kyzentun** [comment]
I tried the simfile you sent me, and the color changes worked fine.  At this point, I think your cache for the simfile is wrong.

**Comment by concubidated** [comment]
@ListenerJubatus can we close this? Clearing cache work for you?

**Comment by ListenerJubatus** [comment]
Yeah.
