### ISSUE TITLE
Can I Have A Compiled Version Of The Latest Commit Of Stepmania 5.1?

### ISSUE THREAD

**Issue by powie444** [stepmania/stepmania#1237]
No, Seriously.
Might Not Look Like An Issue...
BUT I CAN'T COMPILE THINGS WITH MY LAPTOP, AND ALL MY DESKTOP COMPUTERS ARE **BROKEN**!
Please Respond! )':

**Comment by shakesoda** [comment]
Here, throw this in Program and you should be good to go.
[StepMania-5.1-c5fb4f.zip](https://github.com/stepmania/stepmania/files/382702/StepMania-5.1-c5fb4f.zip)

**Comment by powie444** [comment]
The Song Picking Screen For The Editor Doesn't Work. IT'S A BLANK SCREEN, FOR CRYING OUT LOUD!

**Comment by kyzentun** [comment]
It's under construction.  The current default theme is going to be replaced, so I didn't bother porting the new picking screen to it.
