### ISSUE TITLE
bring back old default noteskin

### ISSUE THREAD

**Issue by latot** [stepmania/stepmania#1253]
Hi all, well with the last updates i have this little problem, the availables noteskins with some videos are very difficult to see, so its posible bring back the old default noteskin plis?

Thx.

**Comment by kyzentun** [comment]
@ListenerJubatus is working on a new default noteskin for 5.1: https://github.com/ListenerJubatus/hardline-noteskin
It will replace the current default when it's ready.

**Comment by 1033Forest** [comment]
I think he is talking about gamma noteskin (5.0).

Default set of 5.1 noteskins I proposed:
Hardline (default)
Consentient (old default)
Delta
EasyV2
Edgy
ExactV2
Gamma (5.0 default)
Zenbuquan

**Comment by shakesoda** [comment]
@1033Forest no.

**Comment by calexil** [comment]
well, midi should be included for sure..

all midi flavors were great

**Comment by 1033Forest** [comment]
The old default noteskin was already brought back in 5.1.-3 (the latest release today) and now has quantizable holds

**Comment by shakesoda** [comment]
fixed in 5.1.-3

**Comment by latot** [comment]
@kyzentun Thx!

**Comment by calexil** [comment]
@kyzentun thx
