### ISSUE TITLE
back XMod to default speed type

### ISSUE THREAD

**Issue by latot** [stepmania/stepmania#1255]
Hi, well its posible change the default speed type? before the XMod was by default, now the order is:
MMod
CMod
XMod

Thx.

**Comment by kyzentun** [comment]
I honestly want to get rid of XMods entirely.  They're outdated and everybody moves to using CMod or MMod after gaining experience.

**Comment by shakesoda** [comment]
We're keeping XMods.


- Colby

**Comment by 1033Forest** [comment]
There are people who still use xmod when playing in arcades just to stretch the playfield to make reading easier. And xmods are good for beginning players, too.

**Comment by latot** [comment]
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
personally, i don't like cmod, we lost difficulty in the songs, now mmod, i test it with some songs, but the timings change to much, and in some cases delay the rhythm with the songs, so mmod probably works good with some songs but with my repertory i think don't is a good idea. (A lot of my songs are from Otaku's Dream). So the only option to can play this songs is with xmod, at least if i want preserve the rhythm.

**Comment by Flameshadowxeroshin** [comment]
what does "delay the rhythm with the songs" mean?

**Comment by Prcuvu** [comment]
I'm not in favour of removing XMods.
There are songs whose difficulties are entirely based on BPM change and freezes. CMods nullifies them, making them challenging no more.

**Comment by Kingdaro** [comment]
#1 problem with using MMods: people who forget to set the max BPM on their gimmick files that go upwards to 1000 BPM, causing the MMod algorithm to give you a super slow reading speed and squish all of the notes together.

**Comment by Jousway** [comment]
MMod is terrible, this is why I wrote my amod for my themes
http://pastebin.com/kDKy5z8B
I never made it fail proof but it works rip

**Comment by latot** [comment]
@Flameshadowxeroshin, every song have his own rhythm, and the .sm files have his own too, the idea is the .sm follow the song, saying in other way both should be synchronized, that why SM is a rhythm game. But the mmod change the rhythm of the .sm and then not always it can follow the song, basically the song rhythm is different to the .sm + mmod.
Well this is a logic argument, still left psychological arguments about music/rhythm but i think is enough(if you like i can write it).

Cya.

**Comment by shakesoda** [comment]
MMods don't change the rhythm of anything... they just calculate the XMod
that gives you the scroll rate you asked for according to the highest BPM
in the chart. M600 @ 200bpm = 3x


- Colby

**Comment by latot** [comment]
mm, that weird, when i play with mmod the rhythm change a lot in some songs, maybe is because its saying @Kingdaro:
```
#1 problem with using MMods: people who forget to set the max BPM on their gimmick files that go upwards to 1000 BPM, causing the MMod algorithm to give you a super slow reading speed and squish all of the notes together.
```
probably can be why when a i set the mmod don't follow correctly the speed

**Comment by latot** [comment]
maybe other way to solve this is with this https://github.com/stepmania/stepmania/issues/1256
saving this as a general conf or per song

**Comment by kyzentun** [comment]
I meant that it would be nice if we didn't need XMods, but they are necessary for the unusual edge cases that MMods can't cover.

Related:  I've actually been using a different algorithm for picking the read bpm that mmods use.  Instead of using the highest bpm that ever occurs, I use the highest bpm that lasts for at least 8 seconds.

**Comment by latot** [comment]
@Jousway Hi, can you explain a how does amod plis? thx

**Comment by Jousway** [comment]
@latot what you mean?

**Comment by latot** [comment]
you say you wrote the amod for your themes, how works amod?
ex, in xmod is speed multiplied for some factor, cmod standardize speed, mmod its a proportion between max bpm and your speed.

**Comment by latot** [comment]
this is already fixed :D
