### ISSUE TITLE
(5.1 Branch Source Build) Minor Missing Metrics.

### ISSUE THREAD

**Issue by SpoOkyMagician** [stepmania/stepmania#1265]
Did another build and found these minor errors in metrics/language.

Metric ScreenOptionsAdvanced::LineSI is missing.
Metric ScreenOptionsAdvanced::LineSM is missing.

**Comment by kyzentun** [comment]
Update the metrics in the theme you're using.  Those option rows were part of the ArbitrarySpeedMods system, which was obsoleted and removed.

**Comment by kyzentun** [comment]
Oh, default still has them, woops.

**Comment by SpoOkyMagician** [comment]
Yeah, default.
