### ISSUE TITLE
Editor/ScreenTextEntry Issue

### ISSUE THREAD

**Issue by SpoOkyMagician** [stepmania/stepmania#1274]
So, I am now back in the master branch. (Compiled source code.) I was trying to make a chart when I came across an annoying bug. When I was trying to edit the title, I pressed 'n' and it kicks you out of ScreenTextEntry. (I will just edit this later in a text editor.) Anyway, that is really annoying. Please fix this issue please...

Edit: I found _ also backs out as well.

**Comment by kyzentun** [comment]
Are those keys mapped to Back?

**Comment by SpoOkyMagician** [comment]
Err, it's set for player 2... (I must of been messing around with keys...) Although, _ isn't set. Also, I was using player one. I will change/reset the keys though...

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/commit/43764f4253e0f5ec58f1cf4c6790861a11e4491d
