### ISSUE TITLE
Wrong notedata loaded when playing steps with multiple edit difficulties.

### ISSUE THREAD

**Issue by ca25nada** [stepmania/stepmania#1276]
StepMania 5.1.-2 on Win7

SM loads the wrong notedata if there are multiple edit difficulties that have the same step descriptions. 

e.g.
Simfile with 2 edits, with identical description. The first step listed on the .sm file has 20 taps, the second has 10 taps.:
* Playing the first edit difficulty (displayed having 20 taps) will play normally.
* The second edit difficulty (displayed having 10 taps) will instead play the first edit difficulty with 20 steps.

Also a video:
(one simfile with 3 edit charts with different description, other with 3 edits with identical description. Difficulty meter corresponds to the number of taps they should have.) 
https://www.youtube.com/watch?v=EP2hCt3TplI

The .sm files:
http://pastebin.com/wj5zxpQ8 (Identical difficulty descriptions)
http://pastebin.com/fws1MfzL (Different  difficulty descriptions)

----

Some extra things related to this because I'm not sure whether they should be in separate issues:
* Reloading a simfile with multiple edits removes all the edits with identical descriptions even if they have different steps.
* After reloading the simfile gets rid of of the "duplicate" difficulties, play the one remaining edit difficulty, reload the simfile again. Attempting to play any files afterwards will cause an access violation.

**Comment by kyzentun** [comment]
If you're creating the multiple edit difficulties by editing the simfile manually instead of using the edit menu to copy charts, then the cache isn't being updated.

Multiple edits with the same description are not allowed.  Different descriptions are how stepmania tells them apart.

**Comment by kyzentun** [comment]
I just tested this myself with three freshly made edits, and the correct note data was loaded each time.

The problem has nothing to do with multiple edits.  The problem is that you edited the file outside of stepmania, which made the cache data for that song wrong.
