### ISSUE TITLE
String "LongStepsType::Bm_Versus5" could not be found

### ISSUE THREAD

**Issue by Arvaneth** [stepmania/stepmania#1278]
String "LongStepsType::Bm_Versus5" could not be found in "Themes/default/metrics.ini"' or "Themes/_fallback/metrics.ini". 
"LongStepsType::Bm_Versus7" is also missing.
Found it while moving between the songs in the edit song/steps menu

**Comment by 1033Forest** [comment]
Duplicate of #1277

**Comment by dguzek** [comment]
This issue has been resolved as of d26a1e3b4d3145fa29f3cce2fb9dc1d5426d83bd.
