### ISSUE TITLE
[5.1] Hitting "reset" in Speed mod value menu after changing speed mod type carries over old value onto selected speed type

### ISSUE THREAD

**Issue by ListenerJubatus** [stepmania/stepmania#1279]
## Steps to replicate:

1. Set an Mmod
2. Change the MMod to an XMod
2. Go to the speed mod value menu and hit "Reset"

## Expected behavior:
The value should be reset to the original value but converted to the equivalent for the selected speed mod type

## Instead:
It takes the value of the original MMod and literally makes it the speed value, disregarding the type of speed mod I had switched to. So if I had an MMod 250 going in, changed to XMod, but hit reset, it turns it into 250x speed rather than an Xmod equivalent of 250 BPM scrolling.

**Comment by kyzentun** [comment]
It's easy to explain why this happens:
```lua
			reset_value= get_element_by_path(conf:get_default(), field_name),
```
Haven't decided on a good way to solve it yet.

**Comment by kyzentun** [comment]
https://git.io/vPFBF
