### ISSUE TITLE
2D -> 3D (Generic Lighting Changing/Scaling/Etc.) Applies to Mods

### ISSUE THREAD

**Issue by SpoOkyMagician** [stepmania/stepmania#1280]
A similar idea to https://github.com/stepmania/stepmania/issues/1037 but the reverse idea. Just stick with me a bit here. It shouldn't be too hard to do but, this is the general idea...

Proposal: Add some Lua to make the spinning, flipping, etc mods to modify the sprites in such a way that adds more depth to the actual noteskin without actually changing it too much.

When I made my spinning noteskin, it was pretty simple to do in GIMP. In theory, it should be as well with Lua. (Assuming you are using a default-like noteskin) 

1: Basically, grab the receptor sprite twice.
2: Make one White and the other Black. (The new layer sprites)
3: (For each frame animation) Scale the sprite(s) based on how many frames you want to animate it to. (I used 16 frames for rotating.) White/Black frame will depend on where you light source comes from. I did direct front. You can change it however you want. Adjust the pixels/layers as needed based on center.

Here is the general idea (If you have not see the noteskin.) 

https://dl.dropboxusercontent.com/u/105712481/tap_note%2016x8.png
https://dl.dropboxusercontent.com/u/105712481/template_left_hold%2016x1.png

You would have to deal with masks and stuff as well though... Might be worth experimenting/trying. Although, completely optional.

Edit: Hmm... Effects are not even in SM5 anymore... This is assuming you add those back in eventually. Otherwise, close this.

**Comment by Flameshadowxeroshin** [comment]
If by effects you mean mods, SM5 does still have mods, they just aren't the same as they used to be.

**Comment by SpoOkyMagician** [comment]
Specific mods yes. I don't remember the exact names. However, they are not implemented in the new nesty options. (Yet... If they even are going to come back at all.) Like, twirl, dizzy, tornado, boomerang, etc. (Only the rotating ones though that will/could show depth.)

**Comment by SpoOkyMagician** [comment]
I am gonna close this. Not even worth it honestly.
