### ISSUE TITLE
Black screen finishing songs some times take to much time

### ISSUE THREAD

**Issue by latot** [stepmania/stepmania#1282]
Hi all, well playing in this new version i found when we finish a song appears a black screen, and some times it can take 15 segs to get out.

As a note, this did not happen i the 5.0.11 version.

Thx Cya.

**Comment by Flameshadowxeroshin** [comment]
is there any pattern to it?

**Comment by kyzentun** [comment]
It's always the very first song played after starting stepmania.

**Comment by kyzentun** [comment]
From what I can tell, most of the time is being wasted in this block of code:
https://github.com/stepmania/stepmania/blob/master/src/StatsManager.cpp#L240-L288

I don't know what purpose the Save/Upload folder originally served, or whether it serves any purpose now.  It just stores recent scores, and never gets cleared.  The DisableUploadDir preference disables the whole block.

The two biggest problems in there are Profile::MakeUniqueFileNameNoExtension and XmlFileUtil::SaveToFile.

Profile::MakeUniqueFileNameNoExtension has to get a listing of every file in the folder.  If there are 10k+ files, that can take a while.

XmlFileUtil::SaveToFile will need some digging.

**Comment by shakesoda** [comment]
Upload folder is for score trackers, like groovestats


- Colby

**Comment by latot** [comment]
maybe if we link the concept with this issue https://github.com/stepmania/stepmania/issues/1283 and both in background (other thread)???

**Comment by latot** [comment]
Hi, actually this works fine, so lets closing it.
