### ISSUE TITLE
Crashed after pressing center step (StepF2)

### ISSUE THREAD

**Issue by dionzz99** [stepmania/stepmania#1287]
idk but each restart gave me different errors from the main thread

StepMania v5.0 beta 3 crash report (build 24, 20160626 @ 18:28:51 Hora estándar de Argentina)
--------------------------------------

Crash reason: Assertion 'AddTo.size() != NumAdd' failed

Thread: Main thread
        RageTextureManager.cpp:123 RageTextureManager::LoadTexture(/Themes/Fiesta 2/Fonts/MenuTimer numbers 4x3.png).
        BitmapText.cpp:165 BitmapText::LoadFromFont(/Themes/Fiesta 2/Fonts/MenuTimer numbers.ini)
        FontManager.cpp:40 FontManager::LoadFont(/Themes/Fiesta 2/Fonts/MenuTimer numbers.ini).
        RageFileDriverDirectHelpers.cpp:227 D:/STEP_F2_V1_12 (Steppack 2.12)/Themes/Fiesta 2/BGAnimations/ScreenSelectMusic decorations/_plights/*
        SongManager.cpp:2270 Assertion 'AddTo.size() != NumAdd' failed
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
        InputHandler_DirectInput.cpp:750 
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 

00527a0a: long MainExceptionHandler(struct _EXCEPTION_POINTERS *) [00400000+127a05+5]
005100a3: void sm_crash(char const *) [00400000+110088+1b]
00605a4a: void SongManager::GetSongGroupNamesAvailables(class std::vector<class StdString::CStdStr<char>,class std::allocator<class StdString::CStdStr<char> > > &) [00400000+2054bb+58f]
0063ce20: rehash() [00400000+23cdc0+60]
67b63eb8: MSVCR90!operator new [67b00000+63e99+1f]
0060aaab: int LunaSongManager::GetSongGroupNamesAvailables(class SongManager *,struct lua_State *) [00400000+20aa91+1a]
00633e93: luaD_precall() [00400000+233d1d+176]
0063eea8: luaV_execute() [00400000+23e666+842]
77a73578: ntdll!RtlAllocateHeap [77a30000+43485+f3]
00633efe: luaD_call() [00400000+233eb6+48]
0062eb7f: f_call() [00400000+22eb6d+12]
00633677: luaD_rawrunprotected() [00400000+23363f+38]
00633667: luaD_rawrunprotected() [00400000+23363f+28]
67b63eb8: MSVCR90!operator new [67b00000+63e99+1f]
00634043: luaD_pcall() [00400000+23400e+35]
0062ebcf: lua_pcall() [00400000+22eb83+4c]
005e87b9: bool LuaHelpers::RunScriptOnStack(struct lua_State *,class StdString::CStdStr<char> &,int,int,bool) [00400000+1e8781+38]
5ce96458: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [5ce90000+643c+1c]
005beeac: bool ActorUtil::LoadTableFromStackShowErrors(struct lua_State *) [00400000+1bee65+47]
67b63c3a: MSVCR90!free [67b00000+63b4e+ec]
0062f7cd: l_alloc() [00400000+22f7bc+11]
0063750d: luaM_realloc_() [00400000+2374f1+1c]
77b0aa40: ntdll!RtlpNtMakeTemporaryKey [77a30000+d89ba+2086]
77a5b1cb: ntdll!RtlGetUserPreferredUILanguages [77a30000+2a33b+e90]
77a81e25: ntdll!RtlFreeHeap [77a30000+51daa+7b]
67b63c1b: MSVCR90!free [67b00000+63b4e+cd]
67b63c3a: MSVCR90!free [67b00000+63b4e+ec]
0062f791: luaL_loadbuffer() [00400000+22f76c+25]
67b63c3a: MSVCR90!free [67b00000+63b4e+ec]
5ce95e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [5ce90000+5dfb+48]
005bf1ae: class XNode * LoadXNodeFromLuaShowErrors(class StdString::CStdStr<char> const &) [00400000+1bf0aa+104]
5ce963b5: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [5ce90000+632a+8b]
005c0907: class Actor * ActorUtil::MakeActor(class StdString::CStdStr<char> const &,class Actor *) [00400000+1c081b+ec]
67b51f22: MSVCR90!vcwprintf_s [67b00000+4f0e5+2e3d]
67b51d0a: MSVCR90!vcwprintf_s [67b00000+4f0e5+2c25]
67b51d96: MSVCR90!vcwprintf_s [67b00000+4f0e5+2cb1]
5ce95ec4: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > [5ce90000+5ebb+9]
0060f990: bool ThemeManager::GetPathInfo(struct ThemeManager::PathInfo &,enum ElementCategory,class StdString::CStdStr<char> const &,class StdString::CStdStr<char> const &,bool) [00400000+20f79a+1f6]
77ac1381: ntdll!RtlCreateUserThread [77a30000+7294a+1ea37]
77a73541: ntdll!RtlAllocateHeap [77a30000+43485+bc]
77a73578: ntdll!RtlAllocateHeap [77a30000+43485+f3]
00633667: luaD_rawrunprotected() [00400000+23363f+28]
00634043: luaD_pcall() [00400000+23400e+35]
77a81e25: ntdll!RtlFreeHeap [77a30000+51daa+7b]
77a73541: ntdll!RtlAllocateHeap [77a30000+43485+bc]
77a73578: ntdll!RtlAllocateHeap [77a30000+43485+f3]
67b63c3a: MSVCR90!free [67b00000+63b4e+ec]
0062f7cd: l_alloc() [00400000+22f7bc+11]
0063750d: luaM_realloc_() [00400000+2374f1+1c]
77a5da1c: ntdll!ZwWaitForSingleObject [77a30000+2da10+c]
75bf1129: KERNELBASE!WaitForSingleObjectEx [75bf0000+10bd+6c]
75bf1151: KERNELBASE!WaitForSingleObjectEx [75bf0000+10bd+94]
67b63eb8: MSVCR90!operator new [67b00000+63e99+1f]
67b238b3: MSVCR90!initptd [67b00000+23753+160]
77a81e25: ntdll!RtlFreeHeap [77a30000+51daa+7b]
67b63c1b: MSVCR90!free [67b00000+63b4e+cd]
67b63c3a: MSVCR90!free [67b00000+63b4e+ec]
67b63c1b: MSVCR90!free [67b00000+63b4e+cd]
67b63c3a: MSVCR90!free [67b00000+63b4e+ec]
00419739: void std::_Tree<class std::_Tmap_traits<class Steps *,class Song *,struct std::less<class Steps *>,class std::allocator<struct std::pair<class Steps * const,class Song *> >,0> >::_Erase(struct std::_Tree_nod<class std::_Tmap_traits<class Steps *,class Song *,struct std::less<class Steps *>,class std::allocator<struct std::pair<class Steps * const,class Song *> >,0> >::_Node *) [00400000+19716+23]
00559a40: class std::_Tree<class std::_Tmap_traits<struct std::pair<int,float>,struct PolyphaseFilter *,struct std::less<struct std::pair<int,float> >,class std::allocator<struct std::pair<struct std::pair<int,float> const ,struct PolyphaseFilter *> >,0> >::iterator std::_Tree<class std::_Tmap_traits<struct std::pair<int,float>,struct PolyphaseFilter *,struct std::less<struct std::pair<int,float> >,class std::allocator<struct std::pair<struct std::pair<int,float> const ,struct PolyphaseFilter *> >,0> >::begin(void) [00400000+159a31+f]
004d597f: class std::_Tree<class std::_Tmap_traits<struct lua_State *,bool,struct std::less<struct lua_State *>,class std::allocator<struct std::pair<struct lua_State * const,bool> >,0> >::iterator std::_Tree<class std::_Tmap_traits<struct lua_State *,bool,struct std::less<struct lua_State *>,class std::allocator<struct std::pair<struct lua_State * const,bool> >,0> >::erase(class std::_Tree<class std::_Tmap_traits<struct lua_State *,bool,struct std::less<struct lua_State *>,class std::allocator<struct std::pair<struct lua_State * const,bool> >,0> >::const_iterator,class std::_Tree<class std::_Tmap_traits<struct lua_State *,bool,struct std::less<struct lua_State *>,class std::allocator<struct std::pair<struct lua_State * const,bool> >,0> >::const_iterator) [00400000+d592c+53]
77a5dbdc: ntdll!NtReleaseMutant [77a30000+2dbd0+c]
75bf103b: KERNELBASE!ReleaseMutex [75bf0000+102b+10]
00526193: void MutexImpl_Win32::Unlock(void) [00400000+126187+c]
005a745b: void RageMutex::Unlock(void) [00400000+1a7446+15]
005e7d09: void LuaManager::Release(struct lua_State * &) [00400000+1e7c52+b7]
005c1a47: void AutoActor::Load(class StdString::CStdStr<char> const &) [00400000+1c1a34+13]
005c1b80: void AutoActor::LoadB(class StdString::CStdStr<char> const &,class StdString::CStdStr<char> const &) [00400000+1c1add+a3]
5ce95242: MSVCP90!std::allocator<wchar_t>::deallocate [5ce90000+5081+1c1]
5ce959d5: MSVCP90!std::allocator<char>::allocate [5ce90000+5929+ac]
5ce96422: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [5ce90000+63c3+5f]
5ce9642f: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [5ce90000+63c3+6c]
00434ecf: void ScreenWithMenuElements::Init(void) [00400000+34a9e+431]
004202e3: void ScreenSelectMusic::Init(void) [00400000+1fac8+81b]
5ce95e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [5ce90000+5dfb+48]
5ce95ec4: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > [5ce90000+5ebb+9]
0042046c: void ScreenSelectMusic::Init(void) [00400000+1fac8+9a4]
67b63eb8: MSVCR90!operator new [67b00000+63e99+1f]
67b369ed: MSVCR90!memcpy_s [67b00000+369a3+4a]
5ce94f2a: MSVCP90!std::char_traits<char>::_Copy_s [5ce90000+4f13+17]
5ce95242: MSVCP90!std::allocator<wchar_t>::deallocate [5ce90000+5081+1c1]
5ce959d5: MSVCP90!std::allocator<char>::allocate [5ce90000+5929+ac]
5ce963b5: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [5ce90000+632a+8b]
004246d7: class Screen * CreateScreenSelectMusic(class StdString::CStdStr<char> const &) [00400000+2467f+58]
004c4e2e: class ModIcon * * std::vector<class ModIcon *,class std::allocator<class ModIcon *> >::_Umove<class ModIcon * *>(class ModIcon * *,class ModIcon * *,class ModIcon * *) [00400000+c4e19+15]
006005d5: class DownloadTask * * stdext::unchecked_copy<class DownloadTask * *,class DownloadTask * *>(class DownloadTask * *,class DownloadTask * *,class DownloadTask * *) [00400000+2005b3+22]
005ffb27: void ScreenManager::PrepareScreen(class StdString::CStdStr<char> const &) [00400000+1ffb02+25]
0046d40c: void std::vector<class OptionRow *,class std::allocator<class OptionRow *> >::clear(void) [00400000+6d3d4+38]
0042b514: void std::_Tree<class std::_Tset_traits<class StdString::CStdStr<char>,struct std::less<class StdString::CStdStr<char> >,class std::allocator<class StdString::CStdStr<char> >,0> >::clear(void) [00400000+2b503+11]
005ff0c4: void ScreenManagerUtil::GrabPreparedActors(class std::vector<class Actor *,class std::allocator<class Actor *> > &) [00400000+1fefe9+db]
005fff37: void ScreenManager::LoadDelayedScreen(void) [00400000+1ffe3e+f9]
77a5dbdc: ntdll!NtReleaseMutant [77a30000+2dbd0+c]
005de8e7: bool InputFilter::IsBeingPressed(struct DeviceInput const &,class std::vector<struct DeviceInput,class std::allocator<struct DeviceInput> > const *)const  [00400000+1de890+57]
005a745b: void RageMutex::Unlock(void) [00400000+1a7446+15]
005de8fd: bool InputFilter::IsBeingPressed(struct DeviceInput const &,class std::vector<struct DeviceInput,class std::allocator<struct DeviceInput> > const *)const  [00400000+1de890+6d]
006003ae: void ScreenManager::Update(float) [00400000+200190+21e]
005d7f61: void GameState::Update(float) [00400000+1d7f03+5e]
005a5685: void RageTextureManager::Update(float) [00400000+1a562b+5a]

Static log:
StepMania v5.0 beta 3
Compiled 20160626 @ 18:28:51 Hora estándar de Argentina (build 24)
Log starting 2016-09-13 20:21:56
Loading window: win32
Windows 6.2 (Win8) build 9200 []
Memory: 4095mb total, 4095mb swap (4095mb swap avail)
Video driver: Intel(R) HD Graphics 4600 [Intel Corporation]
              9.18.10.3071, 3-19-2013 [pci\ven_8086&dev_0416&subsys_11ed1043]
Drive: "HL-DT-STDVDRAM GU71N    AS00" Driver: iaStorA DMA: N/A
Drive: "ATA     ST1000LM024 HN-M0002" Driver: iaStorA DMA: N/A
Sound device 0: Speakers (3- USB Audio Device), 6.2, MID 1, PID 100 
Sound device 1: Speakers (Realtek High Definiti, 6.2, MID 1, PID 100 
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'd3d,opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 1, 1280, 720, 16, 0, 1 )
D3D Windowed 1280x720 16 color 16 texture 60Hz Vsync NoSmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 2 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Mouse' axes: 3, hats: 0, buttons: 8 (buffered)
Players joined: P1
Lost focus to: chrome.exe
Language: en
Current renderer: Direct3D
Theme: Fiesta 2

Partial log:
00:17.721: Song "/Songs/07-INFINITY/IN44 - The Fool/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:17.721: Song "/Songs/17-PRIME/1482 - Creed - 1st Desire/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:17.721: Song "/Songs/17-PRIME/1491 - Bad End Night/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:17.722: Song "/Songs/17-PRIME/1494 - Just Hold On/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:17.722: Song "/Songs/17-PRIME/1431 - Point Zero One/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:17.722: Song "/Songs/07-INFINITY/IN32 - Moonshard/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:17.722: Song "/Songs/07-INFINITY/IN44 - The Fool/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:17.722: Song "/Songs/07-INFINITY/IN47 - True/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:17.722: Song "/Songs/17-PRIME/1487 - Trashy Innocence/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:17.722: Song "/Songs/17-PRIME/1494 - Just Hold On/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.

-- End of report

StepMania v5.0 beta 3 crash report (build 24, 20160626 @ 18:28:51 Hora estándar de Argentina)
--------------------------------------

Crash reason: Assertion 'AddTo.size() != NumAdd' failed

Thread: Main thread
        RageFileDriverDirectHelpers.cpp:227 D:/STEP_F2_V1_12 (Steppack 2.12)/Songs/07-INFINITY/INE10 - [Short Cut] Kill Them!/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/User/AppData/Roaming/StepF2/Songs/07-INFINITY/INE10 - [Short Cut] Kill Them!/*
        RageFileDriverDirectHelpers.cpp:227 D:/STEP_F2_V1_12 (Steppack 2.12)/Songs/07-INFINITY/INE14 - [Short Cut] What Happened/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/User/AppData/Roaming/StepF2/Songs/07-INFINITY/INE14 - [Short Cut] What Happened/*
        SongManager.cpp:2270 Assertion 'AddTo.size() != NumAdd' failed
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
        InputHandler_DirectInput.cpp:750 
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 

00527a0a: long MainExceptionHandler(struct _EXCEPTION_POINTERS *) [00400000+127a05+5]
005100a3: void sm_crash(char const *) [00400000+110088+1b]
00605a4a: void SongManager::GetSongGroupNamesAvailables(class std::vector<class StdString::CStdStr<char>,class std::allocator<class StdString::CStdStr<char> > > &) [00400000+2054bb+58f]
0063ce20: rehash() [00400000+23cdc0+60]
67b63eb8: MSVCR90!operator new [67b00000+63e99+1f]
0060aaab: int LunaSongManager::GetSongGroupNamesAvailables(class SongManager *,struct lua_State *) [00400000+20aa91+1a]
00633e93: luaD_precall() [00400000+233d1d+176]
0063eea8: luaV_execute() [00400000+23e666+842]
77a73578: ntdll!RtlAllocateHeap [77a30000+43485+f3]
00633efe: luaD_call() [00400000+233eb6+48]
0062eb7f: f_call() [00400000+22eb6d+12]
00633677: luaD_rawrunprotected() [00400000+23363f+38]
00633667: luaD_rawrunprotected() [00400000+23363f+28]
67b63eb8: MSVCR90!operator new [67b00000+63e99+1f]
00634043: luaD_pcall() [00400000+23400e+35]
0062ebcf: lua_pcall() [00400000+22eb83+4c]
005e87b9: bool LuaHelpers::RunScriptOnStack(struct lua_State *,class StdString::CStdStr<char> &,int,int,bool) [00400000+1e8781+38]
5ce96458: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [5ce90000+643c+1c]
005beeac: bool ActorUtil::LoadTableFromStackShowErrors(struct lua_State *) [00400000+1bee65+47]
67b63c3a: MSVCR90!free [67b00000+63b4e+ec]
0062f7cd: l_alloc() [00400000+22f7bc+11]
0063750d: luaM_realloc_() [00400000+2374f1+1c]
77b0aa40: ntdll!RtlpNtMakeTemporaryKey [77a30000+d89ba+2086]
77a5b1cb: ntdll!RtlGetUserPreferredUILanguages [77a30000+2a33b+e90]
77a81e25: ntdll!RtlFreeHeap [77a30000+51daa+7b]
67b63c1b: MSVCR90!free [67b00000+63b4e+cd]
67b63c3a: MSVCR90!free [67b00000+63b4e+ec]
0062f791: luaL_loadbuffer() [00400000+22f76c+25]
67b63c3a: MSVCR90!free [67b00000+63b4e+ec]
5ce95e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [5ce90000+5dfb+48]
005bf1ae: class XNode * LoadXNodeFromLuaShowErrors(class StdString::CStdStr<char> const &) [00400000+1bf0aa+104]
5ce963b5: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [5ce90000+632a+8b]
005c0907: class Actor * ActorUtil::MakeActor(class StdString::CStdStr<char> const &,class Actor *) [00400000+1c081b+ec]
67b51f22: MSVCR90!vcwprintf_s [67b00000+4f0e5+2e3d]
67b51d0a: MSVCR90!vcwprintf_s [67b00000+4f0e5+2c25]
67b51d96: MSVCR90!vcwprintf_s [67b00000+4f0e5+2cb1]
5ce95ec4: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > [5ce90000+5ebb+9]
0060f990: bool ThemeManager::GetPathInfo(struct ThemeManager::PathInfo &,enum ElementCategory,class StdString::CStdStr<char> const &,class StdString::CStdStr<char> const &,bool) [00400000+20f79a+1f6]
77a73541: ntdll!RtlAllocateHeap [77a30000+43485+bc]
77a73578: ntdll!RtlAllocateHeap [77a30000+43485+f3]
00633667: luaD_rawrunprotected() [00400000+23363f+28]
00634043: luaD_pcall() [00400000+23400e+35]
77a81e25: ntdll!RtlFreeHeap [77a30000+51daa+7b]
77a5b8d4: ntdll!RtlRemoveVectoredContinueHandler [77a30000+2b86b+69]
77a73578: ntdll!RtlAllocateHeap [77a30000+43485+f3]
0063750d: luaM_realloc_() [00400000+2374f1+1c]
77a73541: ntdll!RtlAllocateHeap [77a30000+43485+bc]
77a73578: ntdll!RtlAllocateHeap [77a30000+43485+f3]
67b63eb8: MSVCR90!operator new [67b00000+63e99+1f]
67b238b3: MSVCR90!initptd [67b00000+23753+160]
77a81e25: ntdll!RtlFreeHeap [77a30000+51daa+7b]
67b63c1b: MSVCR90!free [67b00000+63b4e+cd]
67b63c3a: MSVCR90!free [67b00000+63b4e+ec]
67b63c1b: MSVCR90!free [67b00000+63b4e+cd]
67b63c3a: MSVCR90!free [67b00000+63b4e+ec]
00419739: void std::_Tree<class std::_Tmap_traits<class Steps *,class Song *,struct std::less<class Steps *>,class std::allocator<struct std::pair<class Steps * const,class Song *> >,0> >::_Erase(struct std::_Tree_nod<class std::_Tmap_traits<class Steps *,class Song *,struct std::less<class Steps *>,class std::allocator<struct std::pair<class Steps * const,class Song *> >,0> >::_Node *) [00400000+19716+23]
00559a40: class std::_Tree<class std::_Tmap_traits<struct std::pair<int,float>,struct PolyphaseFilter *,struct std::less<struct std::pair<int,float> >,class std::allocator<struct std::pair<struct std::pair<int,float> const ,struct PolyphaseFilter *> >,0> >::iterator std::_Tree<class std::_Tmap_traits<struct std::pair<int,float>,struct PolyphaseFilter *,struct std::less<struct std::pair<int,float> >,class std::allocator<struct std::pair<struct std::pair<int,float> const ,struct PolyphaseFilter *> >,0> >::begin(void) [00400000+159a31+f]
004d597f: class std::_Tree<class std::_Tmap_traits<struct lua_State *,bool,struct std::less<struct lua_State *>,class std::allocator<struct std::pair<struct lua_State * const,bool> >,0> >::iterator std::_Tree<class std::_Tmap_traits<struct lua_State *,bool,struct std::less<struct lua_State *>,class std::allocator<struct std::pair<struct lua_State * const,bool> >,0> >::erase(class std::_Tree<class std::_Tmap_traits<struct lua_State *,bool,struct std::less<struct lua_State *>,class std::allocator<struct std::pair<struct lua_State * const,bool> >,0> >::const_iterator,class std::_Tree<class std::_Tmap_traits<struct lua_State *,bool,struct std::less<struct lua_State *>,class std::allocator<struct std::pair<struct lua_State * const,bool> >,0> >::const_iterator) [00400000+d592c+53]
77a5dbdc: ntdll!NtReleaseMutant [77a30000+2dbd0+c]
75bf103b: KERNELBASE!ReleaseMutex [75bf0000+102b+10]
00526193: void MutexImpl_Win32::Unlock(void) [00400000+126187+c]
005a745b: void RageMutex::Unlock(void) [00400000+1a7446+15]
005e7d09: void LuaManager::Release(struct lua_State * &) [00400000+1e7c52+b7]
005c1a47: void AutoActor::Load(class StdString::CStdStr<char> const &) [00400000+1c1a34+13]
005c1b80: void AutoActor::LoadB(class StdString::CStdStr<char> const &,class StdString::CStdStr<char> const &) [00400000+1c1add+a3]
5ce95242: MSVCP90!std::allocator<wchar_t>::deallocate [5ce90000+5081+1c1]
5ce959d5: MSVCP90!std::allocator<char>::allocate [5ce90000+5929+ac]
5ce96422: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [5ce90000+63c3+5f]
5ce9642f: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [5ce90000+63c3+6c]
00434ecf: void ScreenWithMenuElements::Init(void) [00400000+34a9e+431]
004202e3: void ScreenSelectMusic::Init(void) [00400000+1fac8+81b]
5ce95e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [5ce90000+5dfb+48]
5ce95ec4: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > [5ce90000+5ebb+9]
0042046c: void ScreenSelectMusic::Init(void) [00400000+1fac8+9a4]
67b63eb8: MSVCR90!operator new [67b00000+63e99+1f]
67b369ed: MSVCR90!memcpy_s [67b00000+369a3+4a]
5ce94f2a: MSVCP90!std::char_traits<char>::_Copy_s [5ce90000+4f13+17]
5ce95242: MSVCP90!std::allocator<wchar_t>::deallocate [5ce90000+5081+1c1]
5ce959d5: MSVCP90!std::allocator<char>::allocate [5ce90000+5929+ac]
5ce963b5: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [5ce90000+632a+8b]
004246d7: class Screen * CreateScreenSelectMusic(class StdString::CStdStr<char> const &) [00400000+2467f+58]
004c4e2e: class ModIcon * * std::vector<class ModIcon *,class std::allocator<class ModIcon *> >::_Umove<class ModIcon * *>(class ModIcon * *,class ModIcon * *,class ModIcon * *) [00400000+c4e19+15]
006005d5: class DownloadTask * * stdext::unchecked_copy<class DownloadTask * *,class DownloadTask * *>(class DownloadTask * *,class DownloadTask * *,class DownloadTask * *) [00400000+2005b3+22]
005ffb27: void ScreenManager::PrepareScreen(class StdString::CStdStr<char> const &) [00400000+1ffb02+25]
0046d40c: void std::vector<class OptionRow *,class std::allocator<class OptionRow *> >::clear(void) [00400000+6d3d4+38]
0042b514: void std::_Tree<class std::_Tset_traits<class StdString::CStdStr<char>,struct std::less<class StdString::CStdStr<char> >,class std::allocator<class StdString::CStdStr<char> >,0> >::clear(void) [00400000+2b503+11]
005ff0c4: void ScreenManagerUtil::GrabPreparedActors(class std::vector<class Actor *,class std::allocator<class Actor *> > &) [00400000+1fefe9+db]
005fff37: void ScreenManager::LoadDelayedScreen(void) [00400000+1ffe3e+f9]
77a5dbdc: ntdll!NtReleaseMutant [77a30000+2dbd0+c]
005de8e7: bool InputFilter::IsBeingPressed(struct DeviceInput const &,class std::vector<struct DeviceInput,class std::allocator<struct DeviceInput> > const *)const  [00400000+1de890+57]
005a745b: void RageMutex::Unlock(void) [00400000+1a7446+15]
005de8fd: bool InputFilter::IsBeingPressed(struct DeviceInput const &,class std::vector<struct DeviceInput,class std::allocator<struct DeviceInput> > const *)const  [00400000+1de890+6d]
006003ae: void ScreenManager::Update(float) [00400000+200190+21e]
005d7f61: void GameState::Update(float) [00400000+1d7f03+5e]
005a5685: void RageTextureManager::Update(float) [00400000+1a562b+5a]
0050ff17: void GameLoop::RunGameLoop(void) [00400000+10fe4e+c9]
5ce96458: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [5ce90000+643c+1c]
5ce95e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [5ce90000+5dfb+48]
5ce95ec4: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > [5ce90000+5ebb+9]

Static log:
StepMania v5.0 beta 3
Compiled 20160626 @ 18:28:51 Hora estándar de Argentina (build 24)
Log starting 2016-09-13 20:24:40
Loading window: win32
Windows 6.2 (Win8) build 9200 []
Memory: 4095mb total, 4095mb swap (4095mb swap avail)
Video driver: Intel(R) HD Graphics 4600 [Intel Corporation]
              9.18.10.3071, 3-19-2013 [pci\ven_8086&dev_0416&subsys_11ed1043]
Drive: "HL-DT-STDVDRAM GU71N    AS00" Driver: iaStorA DMA: N/A
Drive: "ATA     ST1000LM024 HN-M0002" Driver: iaStorA DMA: N/A
Sound device 0: Speakers (3- USB Audio Device), 6.2, MID 1, PID 100 
Sound device 1: Speakers (Realtek High Definiti, 6.2, MID 1, PID 100 
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'd3d,opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 1, 1280, 720, 16, 0, 1 )
D3D Windowed 1280x720 16 color 16 texture 60Hz Vsync NoSmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 2 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Mouse' axes: 3, hats: 0, buttons: 8 (buffered)
Players joined: P1
Language: en
Current renderer: Direct3D
Theme: Fiesta 2

Partial log:
00:30.969: Song "/Songs/07-INFINITY/IN44 - The Fool/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:30.969: Song "/Songs/17-PRIME/1482 - Creed - 1st Desire/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:30.969: Song "/Songs/17-PRIME/1491 - Bad End Night/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:30.969: Song "/Songs/17-PRIME/1494 - Just Hold On/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:30.969: Song "/Songs/17-PRIME/1431 - Point Zero One/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:30.969: Song "/Songs/07-INFINITY/IN32 - Moonshard/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:30.971: Song "/Songs/07-INFINITY/IN44 - The Fool/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:30.971: Song "/Songs/07-INFINITY/IN47 - True/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:30.971: Song "/Songs/17-PRIME/1487 - Trashy Innocence/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
00:30.971: Song "/Songs/17-PRIME/1494 - Just Hold On/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.

-- End of report

**Comment by kyzentun** [comment]
Report this to the StepF2 team, not us.
