### ISSUE TITLE
Compiling instructions are out of date

### ISSUE THREAD

**Issue by AngledLuffa** [stepmania/stepmania#1290]
The instructions for compiling new releases still refer to the 5.1.0 branch

```
git clone --depth=1 -b 5_1_0 https://github.com/stepmania/stepmania.git
```

However, at this point I think those should just ask for the master branch

**Comment by kyzentun** [comment]
The wiki page should be good now.  I can't think of other places.

**Comment by AngledLuffa** [comment]
https://github.com/stepmania/stepmania/releases

The release notes refer to the first alpha release of 5.1

```
Check the section on Compiling in the release notes for the previous 5.1.0
alpha release. Those instructions still apply.
```

Those instructions include the directions to checkout -b 5.1.0

**Comment by kyzentun** [comment]
Updated.

**Comment by AngledLuffa** [comment]
Thank you!
