### ISSUE TITLE
New sm and ssc improvement request

### ISSUE THREAD

**Issue by sillybear** [stepmania/stepmania#1295]
I'm aware that those tags with no values are not written in ssc files. I'm also requesting that those tags that uses the default values should not be written too. Those are the following:
- VERSION (what is this for?)
- JACKET (there is no point in adding it)
- OFFSET (when value is 0)
- SELECTABLE
- TIMESIGNATURES
- TICKCOUNTS
- COMBOS
- SPEEDS
- LABELS

**Comment by kyzentun** [comment]
Why?  How does this improve things at all?

When I removed those empty fields from ssc, it barely made a second of difference in my startup time.
Before:
```00:59.005: Found 18509 songs in 51.694164 seconds.```
After:
```00:56.809: Found 18509 songs in 50.406364 seconds.```

Time spent processing those tags isn't a bottleneck anywhere.

**Comment by Flameshadowxeroshin** [comment]
VERSION is the .ssc file version, and its presence allows SSC to be changed in a way that the game can actually know about. It has been changed, but not in a while.

**Comment by sillybear** [comment]
It is not just for performance. It's also for cosmetic improvement. Less tags, more readability.
