### ISSUE TITLE
Dance pads work in Fedora 24

### ISSUE THREAD

**Issue by Espionage724** [stepmania/stepmania#1298]
At the bottom of https://github.com/stepmania/stepmania/wiki/Linux-Dependencies, it mentions dance pads on Fedora aren't supported. I'm not sure if it that note happens to affect just certain pads/devices, but my dance pad worked fine on F22, 23, and 24 (last tried a little under a month ago; all 64-bit editions). 

These are the dependencies I used on F24:

`sudo dnf install cmake gcc-c++ libmad-devel libvorbis-devel nasm yasm bzip2-devel gtk2-devel pcre-devel zlib-devel libjpeg-turbo-devel pulseaudio-libs-devel alsa-lib-devel jack-audio-connection-kit-devel libva-devel glew-devel systemd-devel`

My dance pad is a Konami PS2 board with a PSX-to-USB adapter (Shawan or something like that).

**Comment by shakesoda** [comment]
They work fine for me, too, but @kyzentun's cobalt fluxes apparently don't work on 4.x kernels.
