### ISSUE TITLE
Better Song Loading System?

### ISSUE THREAD

**Issue by SpoOkyMagician** [stepmania/stepmania#1300]
[Feature Request] - This kinda applies to all the step/song/etc loading and such improvements.

Maybe it's just me but, wouldn't it make more sense to to have _required_ filename(s) for loading song/charts/steps/etc? (You can still have extras of course but, make it check for a specific file or ignore the directory.) Something simple like...

song.extention (mp3, ogg, etc...)
steps.extention (sm, scc, dwi, etc...)
banner.extention (png, bmp, gif, etc...)
background.extention (png, bmp, gif, etc...)

(You would only have to find those specific names. If none are found, don't use them/don't load it.)

This way, there will be less error prone filenames that use weird characters. (I have a lot of those. Too lazy to fix...) One major down side to this is obvious... Existing song packs would have to be renamed and stuff... However, it would/should improve loading times. (in theory. It would be organized and skip all the garbage...)

**Comment by Flameshadowxeroshin** [comment]
it probably wouldn't save very much time and would also probably piss off almost every single user
