### ISSUE TITLE
How to randomize "LoadActor functions"?

### ISSUE THREAD

**Issue by SakuraTRC** [stepmania/stepmania#1301]
Hi everybody, i currently work on simple cut-ins animations for DDR X2 Theme by KENP, with lot of code from DDR X2 Plus by Musashi ; 
Animations - Ok
Graphics - Ok
Trigger every +XX combo - Ok
But i have some troubles for randomize the characters, actually i have only one animation during a song because math.random(x,x) is refresh only during the screengameplay creation, 
here is a global example : 

local t = Def.ActorFrame {}
local r = math.random(1,x)

t[#t+1] = LoadActor( THEME:GetPathG("","Char1") )..{
		StartTransitioningCommand=cmd(animation);
	        Condition= r == 1
	};

t[#t+1] = LoadActor( THEME:GetPathG("","Char2") )..{
		StartTransitioningCommand=cmd(animation);
		Condition= r == 2
	};

t[#t+1] = LoadActor( THEME:GetPathG("","Char3") )..{
		StartTransitioningCommand=cmd(animation);
		Condition= r == x
	};

Etc etc for every layers of animation...
After Lua researches and hundreds of exotic tests, i'm unable to "refresh" the math.random function at every triggers

Can you help me please?

Thank you to France!

**Comment by Flameshadowxeroshin** [comment]
commands are the only things in that file that do not run at creation time, so you have to find some way to make the random character selection happen due to a command.

**Comment by SakuraTRC** [comment]
Ho, ok, thank you for your advice! ;)

**Comment by NeobeatIKK** [comment]
"Char"..r

**Comment by kyzentun** [comment]
Not a bug.
