### ISSUE TITLE
[THEME] Localization of some graphic elements (i18n)

### ISSUE THREAD

**Issue by urtzai** [stepmania/stepmania#1305]
I'm trying to translate the whole game to Basque lang but there are some graphic elements that aren't in locale files. I think they should be easily translatable. For example this one: 
 
https://github.com/stepmania/stepmania/tree/master/Themes/default/BGAnimations/ScreenGameplay%20go

**Comment by kyzentun** [comment]
That is an image because stepmania's font system is not capable of those effects.

**Comment by urtzai** [comment]
Could be a solution to implement an image selection by language? Like go_en.png / go_eu / go_fr ... With an appropiate fallback to go_en.png? 

Those localizable images should stay in a centralized library... So editing a raw go_en.psd / go_en.xcf file should be enough to "translate" those images.

**Comment by kyzentun** [comment]
Yeah, I was thinking about that, and it would be possible.  The only problem is that the translations are unmaintained.  There's nobody around to make translated images for the various languages.
So it'd be yet another system that sits around unused.

**Comment by urtzai** [comment]
Ok, but I think providing compressed english png and xfc image versions is enough. If the fallback answers well the community would do the rest with the translations. It's not so hard to manipulate good organized xcf files. What do you think? Do you have psd or xfc files?

**Comment by shakesoda** [comment]
@kyzentun the system is already in place, people just need to make images.
filename hints for languages have been a thing since 3.x


- Colby

**Comment by kyzentun** [comment]
Good, then I don't even have to do anything, you can just document the system somewhere.

**Comment by urtzai** [comment]
@kyzentun Nice! And which is the correct format? filename_eu.png? Where I have to place my images? Is there any raw image (psd, xfc...) file repository of the default theme?

**Comment by shakesoda** [comment]
I recall the name format being "filename (lang eu).png" will need to check
though, nobody has used it in some time.


- Colby

**Comment by urtzai** [comment]
@shakesoda so where can I find editable graphic files? I cannot edit png files... :cry:

**Comment by shakesoda** [comment]
If the original is available it can be found here:
https://github.com/stepmania/stepmania/tree/master/_assets/Themes/default/~res


- Colby

**Comment by urtzai** [comment]
YES! That's what I need!

**Comment by urtzai** [comment]
Ok so I tryed to replace this image but it fallbacks to _fallback graphic png file... How or where I have to put this new file?

![judgments normal 1x6](https://cloud.githubusercontent.com/assets/1741252/19151128/516b76b0-8bcb-11e6-9898-1d3d342beaec.png)

Thank you

**Comment by urtzai** [comment]
@kyzentun, @shakesoda can you help me please?

**Comment by urtzai** [comment]
I made it!! You can close this thread!! Thank you!
