### ISSUE TITLE
OpenITG SSE2 for Windows crashes when entering Graphic Options

### ISSUE THREAD

**Issue by bootmii** [stepmania/stepmania#1306]
I wanna run this game windowed. I really do. But it won't let me. My copy of SM5 does it just fine, but since I can't find their repo I'm dropping it off here.

**Comment by dguzek** [comment]
Try here: https://github.com/openitg/openitg

**Comment by ListenerJubatus** [comment]
This is the issue tracker for official StepMania builds only. You may be looking for https://github.com/openitg/openitg
