### ISSUE TITLE
Hold heads not disappearing after touching receptors during sine wave

### ISSUE THREAD

**Issue by YungDaVinci** [stepmania/stepmania#1310]
Not sure if this is intended behavior, but they don't disappear, but instead continue to follow the sine wave. Kind of hard to describe. So here's a gif.
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/7882157/19216953/84ae2254-8d9f-11e6-9002-743527c776f4.gif)

**Comment by kyzentun** [comment]
They're supposed to not disappear, because hold heads have always stayed around when hit.  However, they are using the wrong time for mod evaluation.
