### ISSUE TITLE
How to change the arrows to actual arrows???

### ISSUE THREAD

**Issue by Benjiiihu** [stepmania/stepmania#1312]
I only see squares, but no arrows.. how can I change that to arrows?

**Comment by kyzentun** [comment]
What version are you using?
Did you change the game mode?

**Comment by shakesoda** [comment]
post your info.txt

**Comment by shakesoda** [comment]
also, try changing your texture resolution to 1024 in graphics options.

**Comment by kyzentun** [comment]
Closing for no response.
