### ISSUE TITLE
Making an in-game loading screen

### ISSUE THREAD

**Issue by Santikun** [stepmania/stepmania#1315]
I wanted to know if there was a way to remove the current SM5 splash screen and replace it with an in-game loading screen. Kinda like this:

![screenshot_2](https://cloud.githubusercontent.com/assets/22405218/19421572/b3b0fd24-93da-11e6-9f45-ce6da635ea45.png)

I'm trying to make this for people to use this build with linux-based cabinets. Now for what I know, this has to be made modifying the source code (C++), however I'm not sure how. How can I achieve this?

**Comment by shakesoda** [comment]
you'd have to remove the loading window and make the initial screen do everything it does instead.

on my cab I just show the loading window.

**Comment by Santikun** [comment]
And how can I do that? Sorry if this sounds pretty bothersome, I recently started with this kind of stuff.

**Comment by shakesoda** [comment]
All of this would have to happen with the display already initialized: https://github.com/stepmania/stepmania/blob/master/src/StepMania.cpp#L1076-L1197

You're on your own beyond that. If you want your loading to have no info why don't you just set the wallpaper and use a null loading window?

**Comment by Santikun** [comment]
I?ll try that, thanks a lot!
