### ISSUE TITLE
Error while initializing video card (SM 5.0.12)

### ISSUE THREAD

**Issue by That2000sKid** [stepmania/stepmania#1322]
For some reason, I just got this error after installing this. My PC has the requirements it needs to run this, but when I launch the game, it crashes with a "fatal error". Here is a log to give some more details:
---------------------------------------------------------------------------------------------------------------------    
00:00.084: StepMania5.0.12
00:00.085: Compiled 20160811 @ 00:34:46 (build 45e0787)
00:00.085: Log starting 2016-10-21 20:12:53
00:00.085:  
00:00.086: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.089: Reading 'Data/Static.ini' failed: No such file or directory
00:00.309: Loading window: win32
00:00.309: Windows 6.2 (Win8) build 9200 []
00:00.310: Memory: 2037mb total, 3189mb swap (1512mb swap avail)
00:00.311: Video driver: Intel(R) 82945G Express Chipset Family (Microsoft Corporation - WDDM 1.0) [Intel Corporation]
00:00.311:               8.15.10.2697, 10-1-2012 [pci\ven_8086&dev_2772]
/////////////////////////////////////////
00:00.312: WARNING: RegOpenKeyEx(80000002,HARDWARE\DEVICEMAP\Scsi) error (The system cannot find the file specified.)
/////////////////////////////////////////
00:00.370: Sound device 0: Headphones (High Definition Aud, 0.0, MID 1, PID 65535 
00:00.373: Sound device 1: Headset Earphone (Headset (Kona, 49.34, MID 65535, PID 65535 
00:00.385: Reading 'Data/Static.ini' failed: No such file or directory
/////////////////////////////////////////
00:00.385: WARNING: Selected theme '_fallback' not found.  Trying Theme preference default value '_fallback'.
/////////////////////////////////////////
/////////////////////////////////////////
00:00.385: WARNING: Theme preference defaults to '_fallback', which cannot be used.  Trying DefaultTheme preference 'default'.
/////////////////////////////////////////
00:00.385: ThemeManager::SwitchThemeAndLanguage: "default", "en"
00:00.555: Loading "/Scripts/32log.lua" ...
00:00.566: Loading "/Scripts/extend_table.lua" ...
00:00.574: Loading "/Scripts/unavailable_functions.lua" ...
00:00.582: Loading "/Scripts/32log.lua" ...
00:00.583: Loading "/Scripts/extend_table.lua" ...
00:00.584: Loading "/Scripts/unavailable_functions.lua" ...
00:00.585: Loading "/Themes/_fallback/Scripts/00 init.lua" ...
00:00.614: Loading "/Themes/_fallback/Scripts/01 alias.lua" ...
00:00.635: Loading "/Themes/_fallback/Scripts/01 base.lua" ...
00:00.652: Loading "/Themes/_fallback/Scripts/01 IniFile.lua" ...
00:00.676: Loading "/Themes/_fallback/Scripts/02 Actor.lua" ...
00:00.691: Loading "/Themes/_fallback/Scripts/02 ActorDef.lua" ...
00:00.707: Loading "/Themes/_fallback/Scripts/02 Branches.lua" ...
00:00.720: Loading "/Themes/_fallback/Scripts/02 Colors.lua" ...
00:00.749: Loading "/Themes/_fallback/Scripts/02 Debug.lua" ...
00:00.761: Loading "/Themes/_fallback/Scripts/02 Enum.lua" ...
00:00.777: Loading "/Themes/_fallback/Scripts/02 OptionsMenu.lua" ...
00:00.814: Loading "/Themes/_fallback/Scripts/02 Other.lua" ...
00:00.839: Loading "/Themes/_fallback/Scripts/02 Serialize.lua" ...
00:00.855: Loading "/Themes/_fallback/Scripts/02 Sprite.lua" ...
00:00.870: Loading "/Themes/_fallback/Scripts/02 StageMods.lua" ...
00:00.890: Loading "/Themes/_fallback/Scripts/02 ThemePrefs.lua" ...
00:00.906: Loading "/Themes/_fallback/Scripts/02 ThemePrefsRows.lua" ...
00:00.921: Loading "/Themes/_fallback/Scripts/02 Utilities.lua" ...
00:00.948: Loading "/Themes/_fallback/Scripts/03 CustomSpeedMods.lua" ...
00:00.964: Loading "/Themes/_fallback/Scripts/03 Gameplay.lua" ...
00:00.985: Loading "/Themes/_fallback/Scripts/03 GamePreferences.lua" ...
00:01.001: Loading "/Themes/_fallback/Scripts/03 ThemeAndGamePrefs.lua" ...
00:01.032: Loading "/Themes/_fallback/Scripts/03 ThemeLibrary.lua" ...
00:01.067: Loading "/Themes/_fallback/Scripts/03 UserPreferences2.lua" ...
00:01.118: Reading 'Themes/_fallback/ThemeInfo.ini' failed: No such file or directory
00:01.118: Loading "/Themes/_fallback/Scripts/04 CreditsHelpers.lua" ...
00:01.314: Loading "/Themes/_fallback/Scripts/04 LogDisplay.lua" ...
00:01.334: Loading "/Themes/_fallback/Scripts/04 NumPadEntry.lua" ...
00:01.355: Loading "/Themes/_fallback/Scripts/04 pause_menu_helper.lua" ...
00:01.366: Loading "/Themes/_fallback/Scripts/04 SetBGFitHelpers.lua" ...
00:01.383: Loading "/Themes/_fallback/Scripts/find_missing_lang_strings.lua" ...
00:01.394: Loading "/Themes/default/Scripts/00 ThemeInfo.lua" ...
00:01.401: Loading "/Themes/default/Scripts/02 Colors.lua" ...
00:01.408: Loading "/Themes/default/Scripts/02 Lyrics.lua" ...
00:01.419: Loading "/Themes/default/Scripts/02 TextBanner.lua" ...
00:01.429: Loading "/Themes/default/Scripts/02 ThemePrefs.lua" ...
00:01.440: ThemePrefs.InitAll( prefs )
00:01.440: ThemePrefs.Init: loading from disk
00:01.440: IniFile.ReadFile( Save/ThemePrefs.ini )
/////////////////////////////////////////
00:01.440: WARNING: ReadFile(Save/ThemePrefs.ini): No such file or directory
/////////////////////////////////////////
00:01.440: NotePosition doesn't exist, creating
00:01.440: GameplayFooter doesn't exist, creating
00:01.440: TimingDisplay doesn't exist, creating
00:01.440: GameplayShowScore doesn't exist, creating
00:01.440: ShowLotsaOptions doesn't exist, creating
00:01.440: FlashyCombo doesn't exist, creating
00:01.440: AutoSetStyle doesn't exist, creating
00:01.440: ComboOnRolls doesn't exist, creating
00:01.440: LongFail doesn't exist, creating
00:01.440: GameplayShowStepsDisplay doesn't exist, creating
00:01.440: FancyUIBG doesn't exist, creating
00:01.440: ComboUnderField doesn't exist, creating
00:01.441: Loading "/Themes/default/Scripts/03 Gameplay.lua" ...
00:01.449: Loading "/Themes/default/Scripts/04 Other.lua" ...
00:01.636: WaveOut software mixing at 44100 hz
00:01.638: Starting thread: Decode thread
00:01.638: Starting thread: Mixer thread
00:01.638: Sound driver: WaveOut
00:01.638: Starting thread: Music thread
00:01.648: Initializing lights drivers: SystemMessage,Export
00:01.648: Lights driver: SystemMessage
00:01.648: Lights driver: Export
00:01.648: ThemeManager::SwitchThemeAndLanguage: "default", "en"
00:01.671: Attempting to load 1 songs from "Songs/DDR SOLO"
00:01.692: Loaded 1 songs from "Songs/DDR SOLO"
00:01.699: Found 1 songs in 0.029000 seconds.
00:01.699: Loading courses.
00:01.701: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/ChallengingRandom5.crs") ("Cache/Courses/Courses_Default_ChallengingRandom5.crs")
00:01.735: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/Jupiter.crs")
00:01.743: Course file "/Courses/Default/Jupiter.crs" contains an invalid #METER string: "Medium"
00:01.743: Course file "/Courses/Default/Jupiter.crs" contains a fixed song entry "StepMania 5/Springtime" that does not exist. This entry will be ignored.
00:01.743: Course file "/Courses/Default/Jupiter.crs" contains a fixed song entry "StepMania 5/MechaTribe Assault" that does not exist. This entry will be ignored.
00:01.743: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_01-04.crs") ("Cache/Courses/Courses_Default_MostPlayed_01-04.crs")
00:01.794: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_05-08.crs")
00:01.807: Course file "/Courses/Default/MostPlayed_05-08.crs" is trying to load BEST4 with only 1 songs installed. This entry will be ignored.
00:01.807: Course file "/Courses/Default/MostPlayed_05-08.crs" is trying to load BEST5 with only 1 songs installed. This entry will be ignored.
00:01.807: Course file "/Courses/Default/MostPlayed_05-08.crs" is trying to load BEST6 with only 1 songs installed. This entry will be ignored.
00:01.807: Course file "/Courses/Default/MostPlayed_05-08.crs" is trying to load BEST7 with only 1 songs installed. This entry will be ignored.
00:01.807: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_09-12.crs")
00:01.817: Course file "/Courses/Default/MostPlayed_09-12.crs" is trying to load BEST8 with only 1 songs installed. This entry will be ignored.
00:01.817: Course file "/Courses/Default/MostPlayed_09-12.crs" is trying to load BEST9 with only 1 songs installed. This entry will be ignored.
00:01.817: Course file "/Courses/Default/MostPlayed_09-12.crs" is trying to load BEST10 with only 1 songs installed. This entry will be ignored.
00:01.817: Course file "/Courses/Default/MostPlayed_09-12.crs" is trying to load BEST11 with only 1 songs installed. This entry will be ignored.
00:01.820: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_13-16.crs")
00:01.830: Course file "/Courses/Default/MostPlayed_13-16.crs" is trying to load BEST12 with only 1 songs installed. This entry will be ignored.
00:01.830: Course file "/Courses/Default/MostPlayed_13-16.crs" is trying to load BEST13 with only 1 songs installed. This entry will be ignored.
00:01.830: Course file "/Courses/Default/MostPlayed_13-16.crs" is trying to load BEST14 with only 1 songs installed. This entry will be ignored.
00:01.830: Course file "/Courses/Default/MostPlayed_13-16.crs" is trying to load BEST15 with only 1 songs installed. This entry will be ignored.
00:01.849: Starting thread: Worker thread (MemoryCardWorker)
00:01.871: RageSound: Load "/Themes/_fallback/Sounds/MemoryCardManager ready.ogg" (precache: 1)
00:01.901: RageSound: Load "/Themes/_fallback/Sounds/_missing.ogg" (precache: 1)
00:01.942: RageSound: Load "/Themes/_fallback/Sounds/_missing.ogg" (precache: 1)
00:01.944: RageSound: Load "/Themes/_fallback/Sounds/MemoryCardManager disconnect.ogg" (precache: 1)
00:01.965: Starting thread: Worker thread (/@mc1int/)
00:01.967: Starting thread: Worker thread (/@mc2int/)
00:01.975: Profile::LoadAllFromDir( /Save/MachineProfile/ )
00:02.006: Loading /Save/MachineProfile/Stats.xml
00:02.007: Done.
00:02.009: UnlockManager::Load()
00:02.049: Last seen video driver: 
00:02.051: Card matches 'Intel.*'.
00:02.051: Applying defaults for Intel(R) 82945G Express Chipset Family (Microsoft Corporation - WDDM 1.0).
00:02.052: Video renderers: 'd3d,opengl'
00:02.052: RageDisplay_D3D::RageDisplay_D3D()
00:02.066: Driver: igdumd32.dll
00:02.066: Description: Intel(R) 82945G Express Chipset Family (Microsoft Corporation - WDDM 1.0)
00:02.066: Max texture size: 2048
00:02.066: Alpha in palette: no
00:02.066: 
00:02.066: This display adaptor supports the following modes:
00:02.092:   320x200 70Hz, format 22
00:02.094:   320x240 70Hz, format 22
00:02.094:   400x300 70Hz, format 22
00:02.094:   512x384 70Hz, format 22
00:02.094:   640x400 70Hz, format 22
00:02.094:   640x480 59Hz, format 22
00:02.094:   640x480 60Hz, format 22
00:02.094:   640x480 70Hz, format 22
00:02.094:   640x480 73Hz, format 22
00:02.094:   640x480 75Hz, format 22
00:02.094:   800x600 56Hz, format 22
00:02.094:   800x600 60Hz, format 22
00:02.094:   800x600 72Hz, format 22
00:02.094:   800x600 75Hz, format 22
00:02.094:   1024x768 60Hz, format 22
00:02.094:   1024x768 70Hz, format 22
00:02.094:   1024x768 75Hz, format 22
00:02.094:   1152x864 60Hz, format 22
00:02.094:   1152x864 75Hz, format 22
00:02.094:   1280x600 60Hz, format 22
00:02.094:   1280x720 60Hz, format 22
00:02.094:   1280x720 75Hz, format 22
00:02.094:   1280x768 60Hz, format 22
00:02.094:   1280x768 75Hz, format 22
00:02.094:   1280x960 60Hz, format 22
00:02.094:   1280x960 75Hz, format 22
00:02.094:   1280x1024 60Hz, format 22
00:02.094:   1280x1024 75Hz, format 22
00:02.094:   1360x768 60Hz, format 22
00:02.094:   1400x1050 60Hz, format 22
00:02.094:   1400x1050 75Hz, format 22
00:02.095:   1440x900 60Hz, format 22
00:02.095:   1600x900 60Hz, format 22
00:02.095:   1680x1050 60Hz, format 22
00:02.095:   1920x1080 60Hz, format 22
/////////////////////////////////////////
00:02.095: WARNING: RageDisplay_D3D::TryVideoMode( 1, 854, 480, 16, 0, 1 )
/////////////////////////////////////////
00:02.095: Testing format: display 22, back buffer 20, windowed 1...
00:02.095: Testing format: display 22, back buffer 22, windowed 1...
00:02.095: This will work.
00:02.161: WM_ACTIVATE (0, 0): has focus
00:02.188: Testing format: display 22, back buffer 20, windowed 1...
00:02.188: Testing format: display 22, back buffer 22, windowed 1...
00:02.188: This will work.
00:02.188: Present Parameters: 854, 480, 22, 1, 0, 1, 4850372, 1, 1, 80, 0, 0, 0
00:02.193: TryVideoMode failed: CreateDevice failed: 'D3DERR_INVALIDCALL'
/////////////////////////////////////////
00:02.193: WARNING: RageDisplay_D3D::TryVideoMode( 1, 854, 480, 16, 0, 1 )
/////////////////////////////////////////
00:02.193: Testing format: display 22, back buffer 20, windowed 1...
00:02.193: Testing format: display 22, back buffer 22, windowed 1...
00:02.193: This will work.
00:02.207: Testing format: display 22, back buffer 20, windowed 1...
00:02.207: Testing format: display 22, back buffer 22, windowed 1...
00:02.207: This will work.
00:02.207: Present Parameters: 854, 480, 22, 1, 0, 1, 4850372, 1, 1, 80, 0, 0, 0
/////////////////////////////////////////
00:02.210: WARNING: RageDisplay_D3D::TryVideoMode( 1, 854, 480, 32, 0, 1 )
/////////////////////////////////////////
00:02.210: Testing format: display 22, back buffer 20, windowed 1...
00:02.210: Testing format: display 22, back buffer 22, windowed 1...
00:02.210: This will work.
00:02.221: Testing format: display 22, back buffer 20, windowed 1...
00:02.223: Testing format: display 22, back buffer 22, windowed 1...
00:02.223: This will work.
00:02.223: Present Parameters: 854, 480, 22, 1, 0, 1, 4850372, 1, 1, 80, 0, 0, 0
/////////////////////////////////////////
00:02.224: WARNING: RageDisplay_D3D::TryVideoMode( 1, 320, 200, 32, 0, 1 )
/////////////////////////////////////////
00:02.224: Testing format: display 22, back buffer 20, windowed 1...
00:02.224: Testing format: display 22, back buffer 22, windowed 1...
00:02.224: This will work.
00:02.237: Testing format: display 22, back buffer 20, windowed 1...
00:02.239: Testing format: display 22, back buffer 22, windowed 1...
00:02.239: This will work.
00:02.239: Present Parameters: 320, 200, 22, 1, 0, 1, 4850372, 1, 1, 80, 0, 0, 0
00:02.240: RageDisplay_D3D::~RageDisplay()
00:02.253: WM_ACTIVATE (1, 0): doesn't have focus
00:02.339: RageDisplay_Legacy::RageDisplay_Legacy()
00:02.420: WM_ACTIVATE (0, 0): has focus
00:02.456: SetScreenMode ...
00:02.496: Reset: pixel format changing
00:02.497: WM_ACTIVATE (1, 0): doesn't have focus
00:02.500: WM_ACTIVATE (0, 0): has focus
/////////////////////////////////////////
00:02.579: WARNING: Invalid format: Mode: software 32 (888) 16 depth 8 stencil 64 accum 
/////////////////////////////////////////
00:02.582: Paletted textures disabled: glGetTexLevelParameteriv(GL_TEXTURE_INDEX_SIZE_EXT) failed (GL_INVALID_ENUM).
00:02.582: GL_UNSIGNED_SHORT_1_5_5_5_REV failed (GL_INVALID_ENUM), disabled
/////////////////////////////////////////
00:02.582: WARNING: Vertex shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:02.582: WARNING: Vertex shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:02.582: WARNING: Vertex shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:02.582: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:02.582: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:02.582: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:02.582: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:02.582: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:02.584: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:02.584: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
/////////////////////////////////////////
00:02.584: WARNING: Fragment shaders not supported by driver. Some effects will not be available.
/////////////////////////////////////////
00:02.584: TryVideoMode failed: The WGL_EXT_swap_control extension is not supported on your computer.
00:02.584: SetScreenMode ...
00:02.642: Paletted textures disabled: glGetTexLevelParameteriv(GL_TEXTURE_INDEX_SIZE_EXT) failed (GL_INVALID_ENUM).
00:02.642: GL_UNSIGNED_SHORT_1_5_5_5_REV failed (GL_INVALID_ENUM), disabled
00:02.642: SetScreenMode ...
00:02.684: Paletted textures disabled: glGetTexLevelParameteriv(GL_TEXTURE_INDEX_SIZE_EXT) failed (GL_INVALID_ENUM).
00:02.684: GL_UNSIGNED_SHORT_1_5_5_5_REV failed (GL_INVALID_ENUM), disabled
00:02.832: SetScreenMode ...
00:02.855: Paletted textures disabled: glGetTexLevelParameteriv(GL_TEXTURE_INDEX_SIZE_EXT) failed (GL_INVALID_ENUM).
00:02.855: GL_UNSIGNED_SHORT_1_5_5_5_REV failed (GL_INVALID_ENUM), disabled
00:02.885: WM_ACTIVATE (1, 0): doesn't have focus
00:02.924: 
00:02.924: //////////////////////////////////////////////////////
00:02.924: Exception: There was an error while initializing your video card.
00:02.924: 
00:02.924: Please do not file this error as a bug!  Use the web page below to troubleshoot this problem.
00:02.924: 
00:02.924: http://old.stepmania.com/stepmaniawiki.php?title=Video_Driver_Troubleshooting
00:02.924: 
00:02.924: Video Driver: Intel(R) 82945G Express Chipset Family (Microsoft Corporation - WDDM 1.0)
00:02.924: 
00:02.924: Initializing d3d...
00:02.924: SetVideoMode failed: CreateDevice failed: 'D3DERR_INVALIDCALL';CreateDevice failed: 'D3DERR_INVALIDCALL';CreateDevice failed: 'D3DERR_INVALIDCALL';CreateDevice failed: 'D3DERR_INVALIDCALL'
00:02.924: 
00:02.924: 
00:02.924: Initializing opengl...
00:02.924: SetVideoMode failed: The WGL_EXT_swap_control extension is not supported on your computer.;The WGL_EXT_swap_control extension is not supported on your computer.;The WGL_EXT_swap_control extension is not supported on your computer.;The WGL_EXT_swap_control extension is not supported on your computer.
00:02.924: 
00:02.924: 
00:02.924: 
00:02.924: //////////////////////////////////////////////////////
00:02.924: 
00:02.924: Shutting down mixer thread ...
00:02.936: Mixer thread shut down.
00:02.956: Shutting down decode thread ...
00:02.966: Decode thread shut down.
00:02.966: Mixing 7495.322754 ahead in 62 Mix() calls
00:03.022: Shutting down music start thread ...
00:03.022: Music start thread shut down.
00:03.108: Lost focus to: StepMania.exe, explorer.exe
00:03.108: Language: en
00:03.108: Current renderer: OpenGL
00:03.108: Theme: default

**Comment by shakesoda** [comment]
Log says you need to update your video card drivers or use a better video card. Neither D3D nor OpenGL seem to be working on your system.
