### ISSUE TITLE
Hold/roll ends are stretched too much.

### ISSUE THREAD

**Issue by MrThatKid** [stepmania/stepmania#1332]
In 5.1, certain mods cause the ends of holds/rolls to stretch, which can result in possibly unpleasant results.
 For an example, I'll use SRT X's The End course, with the mods in question being at TIME=175.431 to 204.754. (course/simfile can be gotten [here](http://www.mediafire.com/?rb018vz5patbk6i).)
The bug being demonstrated: [here](https://youtu.be/c3mVsEA349A?t=3m2s)
For comparison, a screenshot of the file under Stepmania 5.0: [http://imgur.com/a/qIAap](http://imgur.com/a/qIAap)
This was tested under StepMania5.1-git-bb764a9
Compiled 20161023 @ 04:56:44 (build bb764a9) on Ubuntu 16.04 64-bit

**Comment by ListenerJubatus** [comment]
The rendering of hold endings in general seems to be a bit weird. Especially on certain noteskins (such as Delta).

**Comment by shakesoda** [comment]
fixed by #1480
