### ISSUE TITLE
No noteskin error

### ISSUE THREAD

**Issue by WieldyQuincy** [stepmania/stepmania#1336]
I have not played sm in about 3 years and I tried to download 5.0.12 and when I tried to open the game it won't open due to "No Noteskins". I'm not sure what to do? 

I attempted to download a beta version but it gives me the same error. The instructions in the noteskins folder don't seem to point towards a fix. Any help would be great thanks!

UPDATE: 5.0.12 and below give me the Note Skin error. 5.1 doesn't even open.

**Comment by dguzek** [comment]
See: https://github.com/stepmania/stepmania/issues/1299#issuecomment-248893243

**Comment by WieldyQuincy** [comment]
Sorry, should have said that. Yes I am. I just tried 5.0.8 to 5.0.12 and they all give me that error.

**Comment by dguzek** [comment]
Right, the issue I linked to seems to be the same problem, and includes what appears to be a fix near the bottom of the discussion.

I can't comment on *what* the fix does; hopefully it works for you, too.

**Comment by WieldyQuincy** [comment]
Oh, ok! I'll check it out!

Thanks!

**Comment by WieldyQuincy** [comment]
Worked like a charm thank you so much!!
