### ISSUE TITLE
MusicWheel BPM Sort bug

### ISSUE THREAD

**Issue by sillybear** [stepmania/stepmania#1339]
There are some instances that some songs with 1 more than max bpm included in the bpm folder like for example:

130-bpm songs in group 120-129, 150-bpm songs bpm in group 140-149 and so on.

**Comment by sigatrev** [comment]
Not a bug, just a UI inconsistency. Sort truncates bpm, while BPM display rounds to the nearest integer, so 129.6 displays as 130 but sort as 120-129.
