### ISSUE TITLE
Theme crashed the game

### ISSUE THREAD

**Issue by Cublex** [stepmania/stepmania#1341]
So a theme that I'VE SEEN WORK (was used at AGDQ 2016) I decided to use. I installed it, turned it on, selected play (it was invisible lol) and then the game crashed.

Here's the GitHub page: https://github.com/ca25nada/spawncamping-wallhack

Here's the crash log.

StepMania5.0.12 crash report (build 45e0787, 20160811 @ 00:34:46)
--------------------------------------

Crash reason: Invalid preview mode: 5

Thread: Main thread
        FontManager.cpp:40 FontManager::LoadFont(/Themes/spawncamping-wallhack-master/Fonts/_bokutachinogothic2bold 24px.ini).
        RageTextureManager.cpp:145 RageTextureManager::LoadTexture(/Themes/_fallback/Graphics/_blank.png).
        BitmapText.cpp:210 BitmapText::LoadFromFont(/Themes/spawncamping-wallhack-master/Fonts/_bokutachinogothic2bold 24px.ini)
        FontManager.cpp:40 FontManager::LoadFont(/Themes/spawncamping-wallhack-master/Fonts/_bokutachinogothic2bold 24px.ini).
        ScreenSelectMusic.cpp:1875 Invalid preview mode: 5
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:773 
        InputHandler_DirectInput.cpp:749 
        InputHandler_DirectInput.cpp:768 
        InputHandler_DirectInput.cpp:773 
        InputHandler_DirectInput.cpp:749 
Thread: Streaming sound buffering
012ce76f: StepMania!00ed0000
00f65b4d: StepMania!00ed0000
012b6f7f: StepMania!00ed0000
00fc92b9: StepMania!00ed0000
012b2619: StepMania!00ed0000
010d3f5c: StepMania!00ed0000
00f6596d: StepMania!00ed0000
00fa5081: StepMania!00ed0000
00fa0246: StepMania!00ed0000
00fd518f: StepMania!00ed0000
00fd5bbe: StepMania!00ed0000
0139fde8: StepMania!00ed0000
00f6592e: StepMania!00ed0000
00fd70c3: StepMania!00ed0000
00fd70da: StepMania!00ed0000
00fd6499: StepMania!00ed0000
011f6eaf: StepMania!00ed0000
00fd88cd: StepMania!00ed0000
00f8f82f: StepMania!00ed0000
00f65365: StepMania!00ed0000
00f6d2fc: StepMania!00ed0000
013a0d0f: StepMania!00ed0000
012ce61a: StepMania!00ed0000
012ce2d6: StepMania!00ed0000
01383e09: StepMania!00ed0000
773106e4: ntdll!RtlSubscribeWnfStateChangeNotification [772b0000+602e0+404]

Static log:
StepMania5.0.12

**Comment by RGates94** [comment]
There is both a 5.1 and 5.0.12 version of this theme, I've seen a lot of people crash their game by trying to use the 5.1 version on 5.0.12.  You should ensure that you are in fact using the 5.0.12 version and not the 5.1 version it is not backwards compatible.

**Comment by OptimusCrime** [comment]
Using it in 5.1 without problems. Must be as @RGates94 say, wrong version of the theme.

**Comment by dguzek** [comment]
Thanks for responding.  I'll close this issue now.
