### ISSUE TITLE
FILEMAN:DoesFileExist(THEME:GetPathG("","@")) returns true

### ISSUE THREAD

**Issue by ARCofSpada** [stepmania/stepmania#1351]
Tested three times:
(There is no file named menu-background@2x.png or named @@@@@@@@@@)

true:
FILEMAN:DoesFileExist(THEME:GetPathG("", "_skin/menu-background@2x.png"))
true:
FILEMAN:DoesFileExist(THEME:GetPathG("","@@@@@@@@@@@@"))
false:
FILEMAN:DoesFileExist("@@@@@@@@@@@@")

**Comment by sillybear** [comment]
I'm glad someone complained about it. It happened to me too.

**Comment by shakesoda** [comment]
I'll have the @ behavior changed for SM6.
