### ISSUE TITLE
/usr/bin/ld: ../../extern/libmmmagic/linux-64bit/libmmmagic.a(mmmagic.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by JOELwindows7** [stepmania/stepmania#1352]
I tried to compile/recompile (update) the latest stepmania git with the stuffs specified:
- Make 4.1
- Cmake 3.7.0
- Ubuntu 16.10 (Yakety Yak)
- followed their dependencies as told by this git. idk if I fulfilled all those stuff but I'm sure as I installed with the command supplied (`sudo apt get install "lib one" "lib two" "lib three" "lib etc etc"`).
- This Ubuntu was reinstalled while preserving user data.
- ...

I've done something as shown bellow:
[![asciicast](https://asciinema.org/a/94208.png)](https://asciinema.org/a/94208?t=1:02)
[This video: Strange MAKE Problem](https://asciinema.org/a/94208?t=1:02)

You can see these bunch of monstrosities:
```
joelwindows7@joelwindows7-Compaq-510:~$ cd stepmania; git pull origin master; cd Build/; cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release .. && cmake ..; make -j8
From https://github.com/stepmania/stepmania
 * branch            master     -> FETCH_HEAD
Already up-to-date.
-- -- At least one sound library was found. Do not worry if any were not found at this stage.
Host processor is x86_64
Host processor is 64bit
-- Configuring done
-- Generating done
-- Build files have been written to: /home/joelwindows7/stepmania/Build
-- -- At least one sound library was found. Do not worry if any were not found at this stage.
Host processor is x86_64
Host processor is 64bit
-- Configuring done
-- Generating done
-- Build files have been written to: /home/joelwindows7/stepmania/Build
[  0%] Built target cppformat
[  0%] Built target glew
[  1%] Built target jsoncpp
[  2%] Built target ffmpeg
[  4%] Built target png
[  8%] Built target lua-5.1
[ 24%] Built target tommath
[ 26%] Built target rage
[ 26%] Built target GtkModule
[ 45%] Built target tomcrypt
Scanning dependencies of target StepMania
[ 45%] Building CXX object src/CMakeFiles/StepMania.dir/generated/verstub.cpp.o
[ 45%] Linking CXX executable ../../stepmania
/usr/bin/ld: ../../extern/libmmmagic/linux-64bit/libmmmagic.a(mmmagic.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; rekompile dengan -fPIC
/usr/bin/ld: ../../extern/libmmmagic/linux-64bit/libmmmagic.a(minimaidhid.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; rekompile dengan -fPIC
/usr/bin/ld: ../../extern/libmmmagic/linux-64bit/libmmmagic.a(update.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; rekompile dengan -fPIC
/usr/bin/ld: ../ffmpeg-prefix/src/ffmpeg-build/libavformat/libavformat.a(rmsipr.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; rekompile dengan -fPIC
/usr/bin/ld: ../ffmpeg-prefix/src/ffmpeg-build/libavcodec/libavcodec.a(mqc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; rekompile dengan -fPIC
/usr/bin/ld: ../ffmpeg-prefix/src/ffmpeg-build/libavcodec/libavcodec.a(mqcdec.o): relocation R_X86_64_32S against undefined symbol `ff_mqc_qe' can not be used when making a shared object; rekompile dengan -fPIC
/usr/bin/ld: ../ffmpeg-prefix/src/ffmpeg-build/libavcodec/libavcodec.a(mqcenc.o): relocation R_X86_64_32S against undefined symbol `ff_mqc_qe' can not be used when making a shared object; rekompile dengan -fPIC
/usr/bin/ld: ../ffmpeg-prefix/src/ffmpeg-build/libavcodec/libavcodec.a(svq13.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; rekompile dengan -fPIC
/usr/bin/ld: ../ffmpeg-prefix/src/ffmpeg-build/libavcodec/libavcodec.a(xface.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; rekompile dengan -fPIC
/usr/bin/ld: final link gagal: Bagian tidak dapat direpresentasikan di keluaran
collect2: error: ld returned 1 exit status
src/CMakeFiles/StepMania.dir/build.make:10905: recipe for target '../stepmania' failed
make[2]: *** [../stepmania] Error 1
CMakeFiles/Makefile2:423: recipe for target 'src/CMakeFiles/StepMania.dir/all' failed
make[1]: *** [src/CMakeFiles/StepMania.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

```
I have no idea what does this `relocation _thisthisthis_ against _blablabla_ can not be used when making a shared object` and then `recompile with -fPIC` means.
this was when it is __Making__ thus that could be the problem

Or I think I made a mistake that too far to aware back..

**Comment by dguzek** [comment]
Did you run `git submodule init` and `git submodule update` as the [Prerequisites](https://github.com/stepmania/stepmania/tree/master/Build#prerequisites) section instructs?

**Comment by JOELwindows7** [comment]
I've ran the submodule init and the submodule update!

**Comment by JOELwindows7** [comment]
Ugh, it still results same error even though. maybe I should to apply -fPIC in cmake, but how?

**Comment by dguzek** [comment]
To verify, you:

1. deleted your pre-existing cmake files, including CMakeCache.txt
2. ran `git submodule init` and `git submodule update`
3. generated completely new build files in the *./Build* directory using `cmake -G "Unix Makefiles" ..`
4. attempted to build

**Comment by JOELwindows7** [comment]
I did. but nothing works still. :(

**Comment by JOELwindows7** [comment]
Last error it was made to make sure:
```
/usr/bin/ld: ../../extern/libmmmagic/linux-64bit/libmmmagic.a(mmmagic.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; rekompile dengan -fPIC
/usr/bin/ld: ../../extern/libmmmagic/linux-64bit/libmmmagic.a(minimaidhid.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; rekompile dengan -fPIC
/usr/bin/ld: ../../extern/libmmmagic/linux-64bit/libmmmagic.a(update.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; rekompile dengan -fPIC
/usr/bin/ld: final link gagal: Bagian tidak dapat direpresentasikan di keluaran
collect2: error: ld returned 1 exit status
src/CMakeFiles/StepMania.dir/build.make:10904: recipe for target '../stepmania' failed
make[2]: *** [../stepmania] Error 1
CMakeFiles/Makefile2:423: recipe for target 'src/CMakeFiles/StepMania.dir/all' failed
make[1]: *** [src/CMakeFiles/StepMania.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by JOELwindows7** [comment]
As you can see, the error happens when finally making the executable file

**Comment by JOELwindows7** [comment]
can someone help me interpret what actually last of the error means? As best as I could, there's a problem within the Linux minimaid

**Comment by Wallacoloo** [comment]
Instead of running
```
stepmania/Build$ cmake ..
stepmania/Build$ make
```

You have to do:
```
stepmania/Build$ cmake .. -DWITH_MINIMAID=OFF
stepmania/Build$ make
```

I couldn't find the sources for libmmmagic anywhere, otherwise you actually could compile it with `-fPIC` as the error message suggests. Wondering why the stepmania devs allowed something that's apparently closed-source into their open-source project (?)

**Comment by Flameshadowxeroshin** [comment]
probably because there was no other way to do it and it's a relatively minor feature

**Comment by JOELwindows7** [comment]
IT WORKS!!!!!!! Under @Wallacoloo 's solution!! thx buddy!
Solution: Do not use minimaid when cmaking.
case closed!

**Comment by dzackgarza** [comment]
Also ran into this issue trying to build (06/2017) - using `-D WITH_MINIMAID=OFF` does seem to solve it, but it was a bit difficult to find this fix. Is there a good place to add this fix in the documentation to make it easier to find?

**Comment by concubidated** [comment]
I have never ran into this, but wouldn't it make more sense just to set WITH_MINIMAID to OFF for default builds?

https://github.com/stepmania/stepmania/blob/e959c3fb6f1b22f0207dc844173451da7545e818/CMake/DefineOptions.cmake#L69

**Comment by sl1pkn07** [comment]
is not better ship the source code of MINIMAID instead of binaries?

**Comment by chrispable** [comment]
When I finish the p3io driver stuff, there will be an alternative means for using the minimaid without libmmmagic. The commit is just sitting at about 95% of what is needed but I just haven't had time to finish it yet :(

**Comment by sl1pkn07** [comment]
In few days, style_of_2001, developer behind libmmmagic, he can fix the issue (I hope) (now it's on vacation time)

Greetings

**Comment by sl1pkn07** [comment]
done!

https://github.com/sl1pkn07/libmmmagic

**Comment by RodentVienna** [comment]
https://github.com/stepmania/stepmania/pull/1623 compiles successfully.
