### ISSUE TITLE
No audio in Linux [solved]

### ISSUE THREAD

**Issue by mrlinuxfish** [stepmania/stepmania#1369]
I'm trying to get stepmania to run on my linux box, but there is no audio output. I'm running version 5.0.12 on archlinux. I tried both from the AUR as well as downloading directly from the website and had no luck with either method.

**Comment by concubidated** [comment]
Can you include the stepmania log?

**Comment by mrlinuxfish** [comment]
Where can I find that?

**Comment by concubidated** [comment]
should be a log.txt created. It might be in ~/.stepmania-5.0/ 
LogtoDisk=1 might need to be set in the Perferences.ini in ~/.stepmania-5.0/Save

Another option is just start it up on the command line and copy that buffer. Basically would like to see what it is picking for you audio device, my guess is your default device is incorrect.

**Comment by mrlinuxfish** [comment]
[log.txt](https://github.com/stepmania/stepmania/files/667137/log.txt)

**Comment by concubidated** [comment]
Sorry for the delay in getting back to you. Either set your USB audio device as default in your .asoundrc, or just add `SoundDevice=plughw:2,0` to ~/.stepmania-5.0/Save/Preferences.ini which will tell Stepmania which device to use.


Your USB speakers in this case are Card 2, Device 0
`00:00.080: ALSA Driver: 2: Scarlett 2i2 USB [USB], device 0: USB Audio [USB Audio], 0/1 subdevices avail`

You can double check with `arecord -l` as well.

**Comment by mrlinuxfish** [comment]
Thanks, that fixed the problem.
