### ISSUE TITLE
Parsing a .SM file

### ISSUE THREAD

**Issue by MicroTransactionsMatterToo** [stepmania/stepmania#1371]
Hey, this isn't so much an issue, as a question, and I couldn't figure out how to contact you. 

I'm building a MIDI to SM file converter, and as such, need to be able to parse and write out SM files. I have the spec from the wiki, but was wondering which part of StepMania's source handles parsing these files, so I could look at how you guys managed it. 

Many Thanks,
Ennis Massey

**Comment by shakesoda** [comment]
these are probably the files you care about:
https://github.com/stepmania/stepmania/blob/master/src/MsdFile.cpp
https://github.com/stepmania/stepmania/blob/master/src/NotesLoaderSM.cpp
https://github.com/stepmania/stepmania/blob/master/src/NotesLoaderSSC.cpp

**Comment by MicroTransactionsMatterToo** [comment]
Many thanks :)
