### ISSUE TITLE
cppformat submodule missed

### ISSUE THREAD

**Issue by latot** [stepmania/stepmania#1372]
Hi all, is possible update cppformat(fmt) please?, actually one submodule of the actual version was removed from upstream, so now we can't update submodules..

```
git submodule update --recursive
Cloning into '/home/pipe/Documentos/git/stepmania/extern/cppformat/doc/sphinx-bootstrap-theme'...
Username for 'https://github.com': latot
Password for 'https://latot@github.com': 
remote: Repository not found.
```

I check this in the actual upstream and works fine.

Thx. Cya.

**Comment by shakesoda** [comment]
@wolfman2000 ping

**Comment by wolfman2000** [comment]
Which branch are you on? If you are on master, there should not be any submodules at all. If your project still claims to need submodules and you are on master, clear your cmake cache and regenerate. If you are on another branch, please say which one so that I can debug further.

**Comment by latot** [comment]
Hi!, i'm in master, and you can't find the submodule directly, but if you do
```
git submodule update --recursive
```
you will get the problem.

here is the submodule in the main branch:
https://github.com/stepmania/fmt/tree/0b097da31eae1642dd8132f2996e74f7fe354e46/doc

Thx. Cya.

**Comment by wolfman2000** [comment]
Apparently the submodule work was brought in and I didn't notice. Huh.

@latot Did you already run `git submodule init` prior to `git submodule update --recursive`?

**Comment by latot** [comment]
yes, and sadly didn't works, if you go to the submodule via web, you will see we can't access to it.

**Comment by wolfman2000** [comment]
@latot That last statement makes no sense. I purposefully opened an incognito window and was able to view the submodule link you referred to. I also updated my other copy of the SM repo to validate that submodules worked, and I was able to get them without a problem.

> wolfman2000:~/Repos/stepmania (master)
$ git submodule init
Submodule 'extern/cppformat' (https://github.com/stepmania/fmt.git) registered for path 'extern/cppformat'
Submodule 'extern/ffmpeg-git' (https://github.com/stepmania/ffmpeg.git) registered for path 'extern/ffmpeg-git'
Submodule 'extern/googletest' (https://github.com/stepmania/googletest.git) registered for path 'extern/googletest'
Submodule 'extern/libogg-git' (https://github.com/stepmania/ogg.git) registered for path 'extern/libogg-git'
Submodule 'extern/libvorbis-git' (https://github.com/stepmania/vorbis.git) registered for path 'extern/libvorbis-git'
Submodule 'extern/tomcrypt' (https://github.com/stepmania/libtomcrypt.git) registered for path 'extern/tomcrypt'
Submodule 'extern/tommath' (https://github.com/stepmania/libtommath.git) registered for path 'extern/tommath'
wolfman2000:~/Repos/stepmania (master)
$ git submodule update --recursive
Cloning into '/Users/wolfman2000/Repos/stepmania/extern/cppformat'...
Cloning into '/Users/wolfman2000/Repos/stepmania/extern/ffmpeg-git'...
Cloning into '/Users/wolfman2000/Repos/stepmania/extern/googletest'...
Cloning into '/Users/wolfman2000/Repos/stepmania/extern/libogg-git'...
Cloning into '/Users/wolfman2000/Repos/stepmania/extern/libvorbis-git'...
Cloning into '/Users/wolfman2000/Repos/stepmania/extern/tomcrypt'...
Cloning into '/Users/wolfman2000/Repos/stepmania/extern/tommath'...
Submodule path 'extern/cppformat': checked out '0b097da31eae1642dd8132f2996e74f7fe354e46'
Submodule path 'extern/ffmpeg-git': checked out 'eda6effcabcf9c238e4635eb058d72371336e09b'
Submodule path 'extern/googletest': checked out '0dd5ef8bd4b9e3978955e8cdab2eec7016dda4c2'
Submodule path 'extern/libogg-git': checked out '18c401c6bc8814d06f3ae53ebf5d4399f90871cc'
Submodule path 'extern/libvorbis-git': checked out 'd8ffc480787fcd8b5bb7203d6e0acf3bbfb2dd02'
Submodule path 'extern/tomcrypt': checked out 'e24b01d3925265c4999ad9a63f3d8707af201952'
Submodule path 'extern/tommath': checked out '3aba4eacc639dc85b3bc93bf565d2aea91e1ecb7'

**Comment by latot** [comment]
Hi, only to check, if you open a new windows you will open automatically the submodule, there you will see the submodule in a folder called ```sphinx-bootstrap-theme @ c26c975```, can you access to it?

and i don't understand very well some parts of the log, effectively you are updating the submodules, but i can't see there the affected submodule...

maybe if you try
```
git submodule update --force --recursive
```
?

if you didn't see any problem what happen if you go to extern/cppformat and there you update the submodules?

Thx. Cya.!

**Comment by latot** [comment]
maybe your not getting the error because the submodule don't is initialized, maybe something like:
```
git submodule update --init --recursive
```
?

**Comment by wolfman2000** [comment]
@latot Using my logged in browser, I did see the sphinx folder and tried to access it. I was given a 404 not found error. However, I'm not sure I'm seeing the relevance. I was not prevented from retrieving the submodules with git as my own output above has shown. Also, I did init the submoules first as I'm supposed to do and stated within the readme files.

**Comment by latot** [comment]
Hi, only as a note, run ```git submodule init``` don't initialize this submodule, to initialize it you need via the command i post above (via git submodule .. etc) or manually in the folder, out of this.

If you can't access to that folder means the repo was removed, because that link is the submodule, and the error 404 at least confirm this.

note 2, i did not explain very well this, in you log of update don't exist the submodule with the problem, so your not updating it, there my theory is not initialized, i can be wrong but lets try to check and confirm this.

I can in other way confirm this, when i try install sm from gentoo ebuild, there all submodules are updated recursively and i get the same error.

Thx. Cya.

**Comment by wolfman2000** [comment]
Running `git submodule update --force --recursive` states that it checked out the hashes as before.

In viewing the detached head for sphinx-bootstrap-theme, I confirm that there is no content. However, I did not get an error on that.

Are you trying to update the commit hash that cppformat is pointing to instead of using 0b097da31ea? If so, that's not what you are supposed to do.

**Comment by latot** [comment]
mm, in my case this errors appears when i try update submodules normally, without any change, sorry continue asking this, but you run before ```git submodule --init --recursive```?

**Comment by wolfman2000** [comment]
@latot In README.md, I explicitly state to run `git submodule init` and then run `git submodule update`. I had to do that on my spare repo in order to get the submodules loaded in the first place.

We need to start at the beginning. From when you entered into `~/programming/stepmania/` or wherever you keep the code, give me the exact commands you ran. Also report if you already had the submodules on hand.

**Comment by latot** [comment]
List of commands executed from zero:

```
pipe@mNA ~/Documentos/git/tmp $ git clone https://github.com/stepmania/stepmania
Cloning into 'stepmania'...
remote: Counting objects: 267400, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 267400 (delta 0), reused 0 (delta 0), pack-reused 267397
Receiving objects: 100% (267400/267400), 492.89 MiB | 1.29 MiB/s, done.
Resolving deltas: 100% (179409/179409), done.
Checking out files: 100% (4698/4698), done.
pipe@mNA ~/Documentos/git/tmp $ cd stepmania
pipe@mNA ~/Documentos/git/tmp/stepmania $ git submodule update --init --recursive
Submodule 'extern/cppformat' (https://github.com/stepmania/fmt.git) registered for path 'extern/cppformat'
Submodule 'extern/ffmpeg-git' (https://github.com/stepmania/ffmpeg.git) registered for path 'extern/ffmpeg-git'
Submodule 'extern/googletest' (https://github.com/stepmania/googletest.git) registered for path 'extern/googletest'
Submodule 'extern/libogg-git' (https://github.com/stepmania/ogg.git) registered for path 'extern/libogg-git'
Submodule 'extern/libvorbis-git' (https://github.com/stepmania/vorbis.git) registered for path 'extern/libvorbis-git'
Submodule 'extern/tomcrypt' (https://github.com/stepmania/libtomcrypt.git) registered for path 'extern/tomcrypt'
Submodule 'extern/tommath' (https://github.com/stepmania/libtommath.git) registered for path 'extern/tommath'
Cloning into '/home/pipe/Documentos/git/tmp/stepmania/extern/cppformat'...
Cloning into '/home/pipe/Documentos/git/tmp/stepmania/extern/ffmpeg-git'...
Cloning into '/home/pipe/Documentos/git/tmp/stepmania/extern/googletest'...
Cloning into '/home/pipe/Documentos/git/tmp/stepmania/extern/libogg-git'...
Cloning into '/home/pipe/Documentos/git/tmp/stepmania/extern/libvorbis-git'...
Cloning into '/home/pipe/Documentos/git/tmp/stepmania/extern/tomcrypt'...
Cloning into '/home/pipe/Documentos/git/tmp/stepmania/extern/tommath'...
Submodule path 'extern/cppformat': checked out '0b097da31eae1642dd8132f2996e74f7fe354e46'
Submodule 'breathe' (https://github.com/michaeljones/breathe.git) registered for path 'extern/cppformat/breathe'
Submodule 'doc/sphinx-bootstrap-theme' (https://github.com/cppformat/sphinx-bootstrap-theme.git) registered for path 'extern/cppformat/doc/sphinx-bootstrap-theme'
Cloning into '/home/pipe/Documentos/git/tmp/stepmania/extern/cppformat/breathe'...
Cloning into '/home/pipe/Documentos/git/tmp/stepmania/extern/cppformat/doc/sphinx-bootstrap-theme'...
Username for 'https://github.com': ^C
```

the difference between ```git submodule init``` and ```git submodule update --init --recursive``` is basically the first only init the first level of modules, while the second init all the modules, i think is better the second command because we can don't know what modules uses every package (and with every change/update) and compile without modules can cause problems (you know, build without modules).

mm, I don't think is a good idea keep that module in the tree, i don't like broken modules....

And the last, when i try install this in gentoo send errors, because when portage (package manager) try sync the git repo run automatically recursively in the modules, so i can't install now sm ... D:

Thx. Cya.

**Comment by wolfman2000** [comment]
Ah, there is a difference. This was your first time cloning the repo.

...in this case, I was able to recreate your scenario.

There is technically something I can do, however. I can update the actual commit that cppformat is pointing to. The latest commit either does not use sphinx bootstrap or has it integrated within the repo. If this were to be done, however, that means everyone would have to run `git submodule update` on the new commit. I'm personally fine with that, but I don't know about others.

**Comment by latot** [comment]
Hi thx!, i think is normal update submodules, at least i do it when i update a repo, and if i'm right, if you run the last command in your repo you should get the same error without clone from zero.

Thx. Cya.

**Comment by latot** [comment]
Hi, is possible on the way rename cppformat to fmt? and write the actual direction the the repo?

Thx. Cya.

**Comment by wolfman2000** [comment]
That request...makes no sense to me off the top of my head. The repo is already cloned with fmt.git. The fact that the path is set to `extern/cppformat` instead of `extern/fmt` should be irrelevant.

**Comment by latot** [comment]
Right, is only to clarify the name, is right the direction is in the right way.

**Comment by latot** [comment]
@wolfman2000 a little question, why the submodules they point to a fork in sm instead to the original repo?, i mean, don't will be more easy point to the repo and set the head?, or i misread something?

**Comment by wolfman2000** [comment]
Talk to @shakesoda about that one. His decision that we host forks.

**Comment by latot** [comment]
okidokis, @shakesoda can you read this comment please and give your opinion?
https://github.com/stepmania/stepmania/issues/1372#issuecomment-269148936
(my comment above)

Thx. Cya.

**Comment by latot** [comment]
mm, for now, @wolfman2000 what do think can be the best here?

**Comment by Tatsh** [comment]
What version of fmtlib is stepmania/fmt based on? It appears to be almost 1000 commits behind the latest HEAD which is similar to 3.0.1.

**Comment by latot** [comment]
checking the tags probably closer to 2.2.1

**Comment by bonimy** [comment]
Hi. I'm new to the project and just want to state I'm experiencing this same issue too. If I clone the repo without submodules I do just fine, but I'm not sure how necessary these are for successfully building the program.

Regardless, since this is a popular project, it likely draws a lot of attention, and it really can't have the inability to be cloned be the first thing people see when they decide they want to contribute to it.

Any internal progress on fixing this dependency yet?

**Comment by dguzek** [comment]
> Any internal progress on fixing this dependency yet?

Be the change you wish to see in StepMania.  The project is not being worked on very much right now, otherwise.

**Comment by bonimy** [comment]
What I do is clone stepmania from Visual Studio and uncheck the option to clone submodules. I then do
```
git submodule init
git submodule update
```

As your [readme](https://github.com/stepmania/stepmania#from-source) recommends. This works fine, but extern\cppformat\doc\sphinx-bootstrap-theme is empty. So I'm curious if it should even exist at all at this stage. I am aware that [cppformat](https://github.com/stepmania/fmt/tree/0b097da31eae1642dd8132f2996e74f7fe354e46) is a submodule too that you are forking from [another](https://github.com/fmtlib/fmt) repo, so I don't know how well this can be managed, but I'm just bringing this up. Although it's worth noting [they](https://github.com/fmtlib/fmt/tree/master/doc) don't have the sphinx submodule anymore.

**Comment by bonimy** [comment]
For the record, [here](https://github.com/ryan-roemer/sphinx-bootstrap-theme/tree/c26c975e8af6a379f63f8bf969c015fa3b4a2d0a) is the missing sphinx submodule, under new ownership.

**Comment by sleep-walker** [comment]
It would be nice to
1. fork missing sphinx submodule
2. adjust reference in forked cppformat fork
3. update reference in stepmania repo to newer cppformat commit

Right now it is not possible to build Stepmania from source without some obscure GIT magic.

**Comment by coderjo** [comment]
A couple of questions: Is this submodule actually required in order to build? What errors are you getting while building?

I ask because I had no problem building from a fresh checkout on Windows. Though I also only do a clone, init, update. non-recursive.

**Comment by sleep-walker** [comment]
I am trying to update package for openSUSE (which is for some reason still on 4.0) so my target platform is x86_64 Linux.
I haven't tried to check whether it is dead code or not. It is referenced and missing so that should be good reason to fix anyway because following the build process (where the `--recursive` is) fails.
`extern/cppformat/doc/sphinx-bootstrap-theme` doesn't sound like something vital though. And I'd use system cppformat if I could.

**Comment by sleep-walker** [comment]
I verified that I am able to build it only with:
 * extern/cppformat (doesn't seem to need theme for build)
 * extern/ffmpeg-git (could be taken from system, but I have too new version)
 * extern/tomcrypt (not taken from system)
 * extern/tommath (not taken from system)
