### ISSUE TITLE
Encourage users to have a sensible Screen Resolution and Display Aspect Ratio pairing

### ISSUE THREAD

**Issue by dguzek** [stepmania/stepmania#139]
This is not immediately pressing, but the issue has irked me for some time now.

I believe that the Default theme's interface should force users to pick a combination of display aspect ratio and screen resolution that make sense together.  I've found that those most likely to be running 640x480 via 16:9 are those most likely to not realize they are running 640x480 via 16:9 and then complain about the unexpected effects.

Combinations that make sense include:

**4:3**
- 640x480
- 800x600
- 1024x768
- 1280x1024

**16:10**
- 768x480
- 960x600
- 1152x720
- 1280x800
- 1440x900
- 1920x1200

**16:9**
- 640×360
- 960×540
- 1280x720
- 1600x900
- 1920x1080

If the user _really_ wants to use 640x480 with 16:9, s/he can still set that in preferences.ini, but I feel like it's something that should be discouraged.

**Comment by tylerstraub** [comment]
This definitely confused me as a first time user and caused all sorts of very strange scaling issues when I was initially adjusting my resolution to native format. It would be very helpful for this two things to be linked as dguzek proposed.

**Comment by dguzek** [comment]
I looked into this matter shortly after filing this issue.  From what I could gather, it came down to the *display resolution* and *aspect ratio* OptionRows being fairly hardcoded and entangled in display code.

The best workaround I could think of would be to expose a new function to Lua, one that refreshed the existing window to reflect the current DisplayHeight and DisplayAspectRatio preferences. 

In this manner,  the *_fallback* theme could create a pair of custom OptionRows, one for ScreenResolution (really, just DisplayHeight) and one for DisplayAspectRatio.  The available options for ScreenResolution would change dynamically as the DisplayAspectRatio was changed.

The Lua for this would be fairly straightforward, but I imagine the C++ would not be.

**Comment by dguzek** [comment]
This issue was resolved by @drewbarbs in pull request #1018, which was merged into both _master_ and  *5_1-new*.  

*5_1-new* now has a [proper release](https://github.com/stepmania/stepmania/releases/tag/v5.1.0-b1), so this issue can be closed now.  Thanks, @drewbarbs. 👍

**Comment by PehrMeldert** [comment]
this is sad. I used to set my screen to 1024x768 and 16:9 and then let the TV stretch the pixels to correct ratio. That's not possible anymore :'(

**Comment by Horsey-** [comment]
> this is sad. I used to set my screen to 1024x768 and 16:9 and then let the TV stretch the pixels to correct ratio. That's not possible anymore
> 
> Now I'm stuck with 740 x 400, 70 Hz :'(

If the user really wants to use 640x480 with 16:9, s/he can still set that in preferences.ini, but I feel like it's something that should be discouraged.

**Comment by PehrMeldert** [comment]
> > this is sad. I used to set my screen to 1024x768 and 16:9 and then let the TV stretch the pixels to correct ratio. That's not possible anymore
> > Now I'm stuck with 740 x 400, 70 Hz :'(
> 
> "If the user really wants to use 640x480 with 16:9, s/he can still set that in preferences.ini, but I feel like it's something that should be discouraged."

ye, I guess. A bit cumbersome though... didn't get it to work last time either. but I'll try again...
