### ISSUE TITLE
Stepmania linux download not working

### ISSUE THREAD

**Issue by ArcFutahito** [stepmania/stepmania#1392]
Stepmania binaries for linux not working on Kubuntu 16.10 x64. Console produces following message:
`/home/user/Programs/StepMania-5.0.12-Linux/stepmania-5.0/stepmania: error while loading shared libraries: libjpeg.so.62: cannot open shared object file: No such file or directory
`

**Comment by drewbarbs** [comment]
have you tried `sudo apt-get install libjpeg62`?

**Comment by ArcFutahito** [comment]
whoops. I was checking for libjpeg in general and apt listed it as already installed. Yes, it's working now, thank you

**Comment by RollingStar** [comment]
Should this be added to the linux-dependencies wiki page? It fixed my issue on Ubuntu 16.04.

https://github.com/stepmania/stepmania/wiki/Linux-Dependencies
