### ISSUE TITLE
Keysounds and offset causes desync

### ISSUE THREAD

**Issue by ARCofSpada** [stepmania/stepmania#1402]
1. Set global offset to -.200
2. Play any keysounded song such as BMS
3. If you get the correct timing, the note will still be sounded way late. It's also broken in autoplay.

**Comment by shakesoda** [comment]
you can only really fix this by actually having low latency.

**Comment by ARCofSpada** [comment]
I think the problem is that offset changes the notes themselves.
Maybe it can be fixed by using a visual offset only and leaving the global offset at 0.0. I'll have to test later.

**Comment by concubidated** [comment]
@ARCofSpada did you play with the visual offset and global offset at 0.0? Pretty sure this is expected behavior.
