### ISSUE TITLE
Bookkeeping: Coins inserted should be persistent

### ISSUE THREAD

**Issue by concubidated** [stepmania/stepmania#1403]
If game is exited/crashes while credits are inserted but not used, upon reboot those should still be available.

(I might plan to do attempt this before the sqlite profile updates #1354  since I would like to use this feature right away).

**Comment by shakesoda** [comment]
I don't think this is a good idea, actually.

It'd be great to not lose coins, but this introduces a lot more points the game would be writing to disk (if it were to be any good), which we specifically only do during profile saves. More disk writes means more potential for power loss to cause DB/profile corruption.

**Comment by karai17** [comment]
What about just dumping a flat file with an integer value in it every time you add a coin or use a coin? That way it doesn't touch your profile or sensitive data and at worst, it behaves as it currently does (power outage corrupting the flat file loses all inserted tokens)

**Comment by concubidated** [comment]
That's exactly what I was thinking. It would make the worst failure case be
loss if credits.

On Feb 15, 2017 7:56 PM, "Landon Manning" <notifications@github.com> wrote:

What about just dumping a flat file with an integer value in it every time
you add a coin or use a coin? That way it doesn't touch your profile or
sensitive data and at worst, it behaves as it currently does (power outage
corrupting the flat file loses all inserted tokens)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/stepmania/stepmania/issues/1403#issuecomment-280194200>,
or mute the thread
