### ISSUE TITLE
RFC: StepMania 6.0 DP/Scoring Algorithm

### ISSUE THREAD

**Issue by karai17** [stepmania/stepmania#1406]
SM5 (MIGS) scoring sucks. The main problem with it is that it punishes a player for not doing good enough. Not only can you get a 0% score for trying, but you can also *lose* score for messing up. Working with @shakesoda, I propose a scoring algorithm that keeps the good traits of MIGS while eliminating the bad.

### SM6 Scoring Rules

* Score starts at 0 and can never go down. You always keep what you earn.
* Score is calculated internally as Dance Points (DP) and then displayed as a maximum score of 100,000,000 or 100%.
* All scoring is per-note, not per-row. Judgements, however, are per row (in foot game modes). This means that a Jump is counted as a single action with two Notes. If you miss one, you miss both.

## Mathematical Examples

https://docs.google.com/spreadsheets/d/1d6RxvaiXPSw0J-ZGJPHFHX7IH3JxoaemrQboKKgO9a0/edit#gid=0

## Dance Points

```
         | MIGS | SM6 |
---------+------+-----+
Flawless |  3   |  9  |
Perfect  |  2   |  6  |
Great    |  1   |  3  |
Good     |  0   |  2  |
Bad      | -4   |  1  |
Miss     | -8   |  0  |
OK       |  6   |  9  |
NG       |  0   |  0  |
Mine-OK  |  0   |  9  |
Mine-NG  | -8   |  0  |
---------+------+-----+
```

As you can see from the examples in the spreadsheet, scores are generally quite similar for average/good players, but for newbie players, it is far less punishing. Every point you earn, you keep. Full combos of W1, W2, and W3 judgements are the same as MIGS. However, you now earn points for W4 and W5 (instead of earning nothing or losing points). If you play a song and walk off the dance pad, you get 0% since you didn't do anything. However if you try at all, you get some positive score because you earned it.

It is worth noting that this new algorithm will not affect your life judgement. You can still fail a song by getting only W5s or missing several notes in a row. However you will not be deducted points for doing so.

This is currently independent of grading (we are still working on that).

Finally, it is worth noting that SM5 currently has exactly 87.932 scoring systems, none of which are good (or StepMania-specific). This proposal suggests that we should implement one single system; our own.

**Comment by shakesoda** [comment]
👍

**Comment by shakesoda** [comment]
since there's been no feedback I went ahead and implemented the calculator for 6 with these as defaults. closing.
