### ISSUE TITLE
Stepmania Crashes as soon as it opens. OSX 10.11.6

### ISSUE THREAD

**Issue by psychic2ombie** [stepmania/stepmania#1407]
This is my first time running Stepmania and when I launch it, it immediately closes and gives me this log file

StepMania5.0.12 crash report (build 45e0787, 20160811 @ 00:05:39)
--------------------------------------

Architecture:   Mac OS X (i386)
Crash reason:   Segmentation fault - address not mapped at 0x00000000
Crashed thread: Main thread

Checkpoints:
Thread: GUI thread
Thread: Main thread
        Profile.cpp:1951 Loading the node that contains song scores.
        Profile.cpp:2030 Loading the node that contains course scores.
        Profile.cpp:2136 Loading the node that contains category scores.
        Profile.cpp:2191 Loading the node containing screenshot data.
        Profile.cpp:2225 Loading the node containing calorie data.
Thread: Decode thread
Thread: Music thread
Thread: HAL I/O thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)

Thread: Main thread
9d4bbc75: CFDictionaryGetValue (CoreFoundation)
00752e47: LowLevelWindow_MacOSX::SetActualParamsFromMode(__CFDictionary const*) 
00752d41: LowLevelWindow_MacOSX::LowLevelWindow_MacOSX() 
00751d0e: LowLevelWindow::Create() 
003b489a: RageDisplay_Legacy::Init(VideoModeParams const&, bool) 
006ca1b2: sm_main 
0076958b: -[SMMain startGame:] 

Static log:
StepMania5.0.12
Compiled 20160811 @ 00:05:39 (build 45e0787)
Log starting 2017-02-18 14:05:57
Loading window: macosx
Model: MacBookPro11,1 (4/4)
Clock speed 2.40 GHz
Mac OS X 10.11.6
Memory: 8.00 GB
WARNING: Selected theme '_fallback' not found.  Trying Theme preference default value '_fallback'.
WARNING: Theme preference defaults to '_fallback', which cannot be used.  Trying DefaultTheme preference 'default'.
WARNING: ReadFile(Save/ThemePrefs.ini): No such file or directory
Sound driver: AudioUnit
Lights driver: SystemMessage
Video renderers: 'opengl'
Language: en
Current renderer: OpenGL
Theme: default

Partial log:
00:00.228: Starting thread: Worker thread (/@mc2int/)
00:00.229: Profile::LoadAllFromDir( /Save/MachineProfile/ )
00:00.229: Loading /Save/MachineProfile/Stats.xml
00:00.230: Done.
00:00.230: UnlockManager::Load()
00:00.234: Last seen video driver: 
00:00.234: Card matches 'OpenGL'.
00:00.234: Applying defaults for OpenGL.
00:00.234: Video renderers: 'opengl'
00:00.234: RageDisplay_Legacy::RageDisplay_Legacy()

-- End of report

**Comment by dguzek** [comment]
See issue #1299  and, more specifically, https://github.com/stepmania/stepmania/issues/1299#issuecomment-275114142

**Comment by psychic2ombie** [comment]
SO after some further testing, I have discovered that the game only crashes when I am connected to an external monitor. What would the reason for this?
