### ISSUE TITLE
''Assertion 'mad->length != 0' failed'' crash.

### ISSUE THREAD

**Issue by sunwinds2003** [stepmania/stepmania#1410]
I've added some custom songs to Stepmania 5 (newest version). I've made some steps for them, adjusted the BPM but when I click ''Play Current Beat'' or ''Play Selection'' or ''Play Preview Music'' the game crashes. I can give anyone the full crash log, if needed. The crash reason is: Assertion 'mad->length != 0' failed. Any help is appreciated. Thanks ^^

**Comment by shakesoda** [comment]
your song file is corrupt, verify that it works in a media player. I strongly recommend converting it to ogg, in any case. mp3's are buggy in the editor (VBR, in particular, causes seeking problems)

**Comment by sunwinds2003** [comment]
Converting to .ogg worked. Thanks so much! My sister adores this game.
