### ISSUE TITLE
Only one resolution available on Ubuntu 16.04

### ISSUE THREAD

**Issue by RhythmLunatic** [stepmania/stepmania#1413]
I compiled StepMania 5.1-new and StepMania only lists what the current resolution of the display device is as the available resolution.

Terminal log: http://pastebin.com/RLmLjA0n
The last line occurs when StepMania is closed.

**Comment by drewbarbs** [comment]
On X11, Stepmania relies on `xrandr` to tell it what resolutions the display supports; can you try running `xrandr -q` and see if the resolutions you expect are in that list? If not, you might want to check out [this wiki](https://wiki.archlinux.org/index.php/xrandr#Adding_undetected_resolutions) for adding more resolutions.

Do you have more than one monitor? If so, checkout from master and give that a shot, it supports multimonitors better on X11.

**Comment by ARCofSpada** [comment]
xrandr lists all the resolutions it should.

It seems like this fix isn't in 5.1-new? https://github.com/stepmania/stepmania/commit/f9f0adff75a5595554f1295fde459bc09d74a60d

**Comment by drewbarbs** [comment]
No, that patch isn't in 5.1-new, have you given master a try and verified that works for you?

**Comment by ARCofSpada** [comment]
This issue can be closed, I'll backport it to 5.1-new in my own build.
