### ISSUE TITLE
Shift key not working in 5.1-3 [macOS Sierra]

### ISSUE THREAD

**Issue by katawajojo** [stepmania/stepmania#1417]
When attempting to fill out things such as Profile Names or Passwords (online play), 5.1-3 doesn't see the case change. (example, STronGP455w()rD will be input as strongp455w90rd instead.)

**Comment by concubidated** [comment]
Can reproduce this as well. 5_1-new does not have this issue, but the 5.2 branch does.

**Comment by katawajojo** [comment]
the pre-built version of 5.1-3 has this issue. I haven't tested building it from source.
