### ISSUE TITLE
Any news for make it run on Rasbperry Pi Zero 1/2/3?

### ISSUE THREAD

**Issue by Grondoval** [stepmania/stepmania#1418]
Hi

Are there any news about a new stepmania version that make it run on Raspberry Pi, or a process that make it run on it?

Greetings!

**Comment by concubidated** [comment]
Check out https://www.stepmania.com/forums/stepmania-development/show/5825

**Comment by shakesoda** [comment]
you CAN get it working, but performance is awful and not about to really improve until SM6. 6 will support rpi if possible (probably at low res, the gpu is pretty weak). I might look into optimizing 5.1/5.2 a bit, but don't hold out too much hope.

the renderer basically needs a complete overhaul to be friendly with GLES devices and have any hope of holding framerate.

**Comment by njfox** [comment]
I have not tested on a Raspberry Pi (and it probably wouldn't work very well on one), but I've managed to get Stepmania `master` to run pretty much flawlessly on an Odroid XU4 using [this library](https://github.com/ptitSeb/gl4es) in case anyone wants to give it a try.
