### ISSUE TITLE
I messed up... Crash reason: Game has no Style that can be used with HowToPlay: lights

### ISSUE THREAD

**Issue by Poorlittlemissie** [stepmania/stepmania#1421]
So I installed stepmania 5.0.12 and I must have messed up somehow in game options. I think it was caused by choosing a theme/style I didn't add to the game. Now I can't even open the game. Even uninstalling and reinstalling makes the same issue occur. I really don't know what to do next. Here's the crash info if it helps anyone to understand the issue and to solve it.

StepMania5.0.12 crash report (build 45e0787, 20160811 @ 00:34:46)
--------------------------------------

Crash reason: Game has no Style that can be used with HowToPlay: lights

Thread: Main thread
        FontManager.cpp:40 FontManager::LoadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        RageTextureManager.cpp:145 RageTextureManager::LoadTexture(__blank__).
        RageTextureManager.cpp:145 RageTextureManager::LoadTexture(__blank__).
        RageTextureManager.cpp:145 RageTextureManager::LoadTexture(__blank__).
        GameManager.cpp:3337 Game has no Style that can be used with HowToPlay: lights
Thread: Decode thread
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:773 
        InputHandler_DirectInput.cpp:749 
        InputHandler_DirectInput.cpp:768 
        InputHandler_DirectInput.cpp:773 
        InputHandler_DirectInput.cpp:749 
0116e76f: StepMania!00d70000
00e05b4d: StepMania!00d70000
00e17389: StepMania!00d70000
0123fde8: StepMania!00d70000
0112aef3: StepMania!00d70000
00e6ba82: StepMania!00d70000
00e6bc4f: StepMania!00d70000
77185b32: ntdll!RtlAllocateHeap [77140000+45b00+32]
0123fe3e: StepMania!00d70000
01222ad1: StepMania!00d70000
00e055b7: StepMania!00d70000
00e19661: StepMania!00d70000
0112a59b: StepMania!00d70000
77185b32: ntdll!RtlAllocateHeap [77140000+45b00+32]
00e76f68: StepMania!00d70000
00fa1ad1: StepMania!00d70000
00e76001: StepMania!00d70000
00e7643d: StepMania!00d70000
01096eaf: StepMania!00d70000
00e788cd: StepMania!00d70000
00e2f82f: StepMania!00d70000
00e05365: StepMania!00d70000
00e0d2fc: StepMania!00d70000
01240d0f: StepMania!00d70000
0116e61a: StepMania!00d70000
0116e2d6: StepMania!00d70000
01223e09: StepMania!00d70000
771a0fa4: ntdll!RtlSubscribeWnfStateChangeNotification [77140000+60ba0+404]

Static log:
StepMania5.0.12
Compiled 20160811 @ 00:34:46 (build 45e0787)
Log starting 2017-03-18 12:03:15
Loading window: win32
Windows 6.2 (Win8) build 9200 []
Memory: 2047mb total, 4095mb swap (1514mb swap avail)
Video driver: AMD Radeon HD 7620G [Advanced Micro Devices, Inc.]
              15.200.1062.1004, 8-3-2015 [pci\ven_1002&dev_9907]
Drive: "TOSHIBA MQ01ABD075" Driver: amdsata DMA: N/A
Drive: "hp      DVD RAM UJ8C2   1.00" Driver: amdsata DMA: N/A
Sound device 0: Speaker/HP (Realtek High Defini, 10.0, MID 1, PID 100 
WARNING: ReadFile(Save/ThemePrefs.ini): No such file or directory
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'd3d,opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 1, 640, 480, 32, 0, 1 )
D3D Windowed 640x480 32 color 16 texture 60Hz Vsync SmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 2 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Mouse' axes: 3, hats: 0, buttons: 5 (buffered)
Players joined: none
Language: en
Current renderer: Direct3D
Theme: default

Partial log:
00:10.673: Loading /Themes/default/BGAnimations/_frame 3x3/default.lua, type FileType_Lua
00:10.673: Loading /Themes/_fallback/BGAnimations/_frame files 3x3/rounded black 3x3.png, type FileType_Bitmap
00:10.673: Loading /Themes/default/BGAnimations/ScreenHowToPlay overlay/_howtoplay miss.lua, type FileType_Lua
00:10.675: Loading /Themes/default/BGAnimations/_frame 3x3/default.lua, type FileType_Lua
00:10.675: Loading /Themes/_fallback/BGAnimations/_frame files 3x3/rounded black 3x3.png, type FileType_Bitmap
00:10.913: Loading /Themes/default/BGAnimations/ScreenWithMenuElements decorations/default.lua, type FileType_Lua
00:10.913: Loading /Themes/default/BGAnimations/_Arcade decorations/default.lua, type FileType_Lua
00:10.925: Loading /Themes/default/Graphics/OptionRowExit frame.png, type FileType_Bitmap
00:10.932: Loading /Themes/default/Sounds/default/_Screen cancel.ogg, type FileType_Sound
00:10.932: RageSound: Load "/Themes/default/Sounds/default/_Screen cancel.ogg" (precache: 1)

-- End of report

**Comment by dguzek** [comment]
It looks like you accidentally tried to play "lights" gamemode (which is only used for mapping light patterns on arcade cabinets and can't really be played) (but it is pretty confusing).  You'll need to manually edit your Preferences.ini file to change the `CurrentGame` setting.

It looks like you're using Windows.  If so, you'll find your Preferences.ini file at `appdata%\StepMania 5\Save\Preferences.ini`.  You can open the file with any text editor and change the line `CurrentGame=lights` to `CurrentGame=dance`

**Comment by Poorlittlemissie** [comment]
Thanks a lot! It resolved part of the issue as I can now play the game. However, I'm stucked in offline event mode and I can't get to the options (i.e. change keys). Is there a way to get to the options or to change keys?

**Comment by dguzek** [comment]
Hmm, if you're unable to get to the main Options Menu, you might be in "freeplay" mode rather than "home" mode.  You can toggle which mode you are in by holding <kbd>F3</kbd> and tapping <kbd>1</kbd>.

Alternatively, you can always shortcut yourself to the Options Menu by pressing <kbd>Scroll Lock</kbd>.

**Comment by Poorlittlemissie** [comment]
Thanks, using scroll locks, it now works perfectly fine!

**Comment by dguzek** [comment]
No problem.  I'll close this issue now.
