### ISSUE TITLE
Audio crackly after recording with OBS

### ISSUE THREAD

**Issue by lukeoftheaura** [stepmania/stepmania#1428]
Hi,
I've been playing stepmania for a while now, and I decided to try and stream some gameplay to twitch. I started recording stepmania with OBS and the audio was crackly (not only on the stream but for me as well). I then stopped the stream, rebooted my PC, and now the audio from stepmania is always crackly (even when I'm not streaming) and I don't know how to fix it.

**Comment by lukeoftheaura** [comment]
issue was actually with ALSA-JACK bridge being used. setting stepmania to use JACK directly solved the problem.

**Comment by ArcFutahito** [comment]
Hey! Remember me on IRC? I believe you wanted to do Taiko on stepmania. So here's an example of taiko https://www.youtube.com/watch?v=7g0K2AphDog

P. S. Waited for you to appear on IRC but since that's not happening at least you'll see it here xD
