### ISSUE TITLE
Crash Assertion 'AddTo.size() != NumAdd' failed

### ISSUE THREAD

**Issue by Hens94** [stepmania/stepmania#1433]
Before load the songs, the game crash

Crash reason: Assertion 'AddTo.size() != NumAdd' failed

Thread: Main thread
        RageTextureManager.cpp:123 RageTextureManager::LoadTexture(/Themes/Fiesta 2/Graphics/ScreenSelectMusic/_GoFullMode/bar_glow.png).
        RageTextureManager.cpp:123 RageTextureManager::LoadTexture(/Themes/Fiesta 2/Graphics/ScreenSelectMusic/_GoFullMode/bar_glow.png).
        RageTextureManager.cpp:123 RageTextureManager::LoadTexture(/Themes/Fiesta 2/Graphics/ScreenSelectMusic/_GoFullMode/bar_glow.png).
        RageTextureManager.cpp:123 RageTextureManager::LoadTexture(/Themes/Fiesta 2/Graphics/ScreenSelectMusic/_GoFullMode/bar_glow.png).
        SongManager.cpp:2274 Assertion 'AddTo.size() != NumAdd' failed
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
        InputHandler_DirectInput.cpp:750 
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
Thread: Streaming sound buffering

**Comment by fernandoulp** [comment]
Hi, I'm on the same spot, found a supposed solution to this but no luck, it mentions to do this:
Save cache folder and delete preferences.ini from Save folder.

**Comment by dguzek** [comment]
What version of StepMania are you using, @Hens94 ?

**Comment by Flameshadowxeroshin** [comment]
Given that a StepF2 crashlog showing a similar crash (which I can't find in our codebase) was posted earlier today, I think this is StepF2.

**Comment by dguzek** [comment]
I was thinking the same thing.  I'll close this issue for now.  If @Hens94 responds with information demonstrating otherwise, we can reopen it at that time.
