### ISSUE TITLE
Fullscreen goes black on Mac OS Mavericks

### ISSUE THREAD

**Issue by befree2209** [stepmania/stepmania#1434]
I have a problem concerning my StepMania 5.0.12 version. My game is going black when I'm in fullscreen mode, and I don't have a way to get out of it. I tried redownloading a fresh copy of the game, but it still doesn't work. I want to fix this, but I don't want to royally screw up my computer. Does anybody have any solutions?

**Comment by concubidated** [comment]
Click the green + instead on the window. This is a known issue with OSX.

**Comment by dguzek** [comment]
This issue has been resolved by pull request #1523 and can now be closed.

**Comment by amatiasq** [comment]
I'm having this issue with 5.0.12 right now, I don't know how to open Stepmania now or change the video settings since it goes directly to black.

**Comment by amatiasq** [comment]
Found it. Edit ~/Library/Preferences/StepMania 5/Preferences.ini` and set `Windowed=1`

**Comment by dguzek** [comment]
You can use <kbd>alt</kbd> + <kbd>return</kbd> to toggle fullscreen.  

This issue was fixed for the SM5.1 betas: https://github.com/stepmania/stepmania/releases/tag/v5.1.0-b2

There are instructions for installing SM5.1 on macOS here: https://github.com/stepmania/stepmania/wiki/Installing-on-macOS

**Comment by GuitarKat** [comment]
> You can use alt + return to toggle fullscreen.
> 
> This issue was fixed for the SM5.1 betas: https://github.com/stepmania/stepmania/releases/tag/v5.1.0-b2
> 
> There are instructions for installing SM5.1 on macOS here: https://github.com/stepmania/stepmania/wiki/Installing-on-macOS

Hi, I did run this with the SM5.1 betas (currently running SM 5.1.0-b2) and I got this issue to come up. I'm on MacOS High Sierra, version 10.13.6.

Thanks for those that wrote about the preferences file and the toggle. :)
