### ISSUE TITLE
Crash reason: Assertion 'AddTo.size() != NumAdd' failed

### ISSUE THREAD

**Issue by fr3e53x** [stepmania/stepmania#1438]
StepMania v5.0 beta 3 crash report (build 7, 20170407 @ 23:43:04 Hora estándar de Argentina)
--------------------------------------

Crash reason: Assertion 'AddTo.size() != NumAdd' failed

Thread: Main thread
        RageFileDriverDirectHelpers.cpp:227 C:/PIU/STEP_F2_V1_14 (Steppack 2.14)/STEP_F2_V1_14 (Steppack 2.14)/Songs/17-PRIME/*
        RageFileDriverDirectHelpers.cpp:227 C:/PIU/STEP_F2_V1_14 (Steppack 2.14)/STEP_F2_V1_14 (Steppack 2.14)/Songs/17-PRIME/1479 - Mitosudaira/*
        RageFileDriverDirectHelpers.cpp:227 C:/PIU/STEP_F2_V1_14 (Steppack 2.14)/STEP_F2_V1_14 (Steppack 2.14)/Songs/17-PRIME/*
        RageFileDriverDirectHelpers.cpp:227 C:/PIU/STEP_F2_V1_14 (Steppack 2.14)/STEP_F2_V1_14 (Steppack 2.14)/Songs/17-PRIME/1481_JE - Bad Apple/*
        SongManager.cpp:2274 Assertion 'AddTo.size() != NumAdd' failed
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
        InputHandler_DirectInput.cpp:750 
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
Thread: Streaming sound buffering

debug resource file 'C:\PIU\STEP_F2_V1_14 (Steppack 2.14)\STEP_F2_V1_14 (Steppack 2.14)\STEP_F2.vdi': CreateFile failed (El sistema no puede encontrar el archivo especificado.).

Static log:
StepMania v5.0 beta 3
Compiled 20170407 @ 23:43:04 Hora estándar de Argentina (build 7)
Log starting 2017-05-03 01:24:28
Loading window: win32
Windows 6.2 (Win8) build 9200 []
Memory: 2047mb total, 4095mb swap (1376mb swap avail)
Video driver: Mobile Intel(R) 4 Series Express Chipset Family (Microsoft Corporation - WDDM 1.1) [Intel Corporation]
              8.15.10.2702, 3-11-2013 [pci\ven_8086&dev_2a43]
Drive: "TOSHIBA MK2565GSXV" Driver: storahci DMA: N/A
Drive: "TSSTcorpCDDVDW TS-L633C TF20" Driver: storahci DMA: N/A
Sound device 0: Auriculares (Dispositivo de Hig, 0.0, MID 1, PID 65535 
Sound device 1: Altavoces (Dispositivo de High , 0.0, MID 1, PID 65535 
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'd3d,opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 1, 640, 480, 16, 0, 1 )
D3D Windowed 640x480 16 color 16 texture 60Hz Vsync NoSmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Teclado" Product Name: "Teclado"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 2 DirectInput devices:
   0: 'Teclado' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Mouse' axes: 3, hats: 0, buttons: 8 (buffered)
WARNING: RageSoundDriver::GetHardwareFrame: too many tries
Mixing underruns: 2
Players joined: P2
Lost focus to: rundll32.exe
Language: es
Current renderer: Direct3D
Theme: Fiesta 2

Partial log:
01:03.242: RageSound: Load "/Themes/Fiesta 2/Sounds/Categories/ORIGINAL.mp3" (precache: 1)
01:03.266: RageSound: Load "/Themes/Fiesta 2/Sounds/Categories/K-POP.wav" (precache: 1)
01:03.277: RageSound: Load "/Themes/Fiesta 2/Sounds/Categories/WORLD MUSIC.mp3" (precache: 1)
01:03.296: RageSound: Load "/Themes/Fiesta 2/Sounds/Categories/J-MUSIC.ogg" (precache: 1)
01:03.320: RageSound: Load "/Themes/Fiesta 2/Sounds/Sounds/TIMER_TICK.mp3" (precache: 0)
01:03.370: Song "/Songs/04-SKILLUP ZONE/Media/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
01:03.388: Song "/Songs/12-NX-NX2/D08F - [Full Song] Free/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
01:03.391: Song "/Songs/12-NX-NX2/D11F - [Full Song] For You/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
01:03.396: Song "/Songs/17-PRIME/1479 - Mitosudaira/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.
01:03.397: Song "/Songs/17-PRIME/1481_JE - Bad Apple/" has no SSC, SM, SMA, DWI, BMS, or KSF files, ignoring it.

-- End of report

**Comment by Flameshadowxeroshin** [comment]
We cannot investigate or fix bugs in StepF2.
