### ISSUE TITLE
5.1-new: latest commit causes crashes when going to select song

### ISSUE THREAD

**Issue by YungDaVinci** [stepmania/stepmania#1445]
#1361 causes my game to crash when getting to ScreenSelectMusic.
Using default.

**Comment by shakesoda** [comment]
argh

**Comment by sillybear** [comment]
I just downloaded a new 5.1_new clone. Compiled a released build via VS2013 ,using non-XP platform toolset.
No crash anywhere in default theme.

**Comment by YungDaVinci** [comment]
Running Linux Mint.
crashlog.txt: https://pastebin.com/GczeQxqc

**Comment by dguzek** [comment]
I just updated my local copy of *5_1-new*, built, and encountered no crashes on ScreenSelectMusic in default theme or Simply Love.

**Comment by sillybear** [comment]
Mine is windows 10 though.

**Comment by sillybear** [comment]
Kyzentun also confirmed this crash.  I assume his OS is Linux?

**Comment by YungDaVinci** [comment]
Yeah. Must be a linux specific thing.

**Comment by sillybear** [comment]
someone already submitted the same issue before yours. See #1442

**Comment by YungDaVinci** [comment]
That's a different issue and running on an older build. I can build 5.1-new on the commit before #1361

**Comment by sillybear** [comment]
He said "fresh build" the time it was posted, and it's past #1361, for same reason: segmentation fault.

**Comment by YungDaVinci** [comment]
#1442 was built April 18th and #1361 was committed in May. Plus I can build master, just not 5.1-new. And I could play 5.1-new without crashes before #1361. #1442 is a different issue.

**Comment by sillybear** [comment]
#1361 was merged 9 days ago while #1442 was built 6 days ago. Therefore,  #1361 was already present in his build. You have both same crash reason but he didn't blame #1361 for that. You both used Linux but different versions.

**Comment by sillybear** [comment]
#1361 was merged 9 days ago while #1442 was built 6 days ago. Therefore,  #1361 was already present in his build. You have both same crash reason but he didn't blame #1361 for that. You both used Linux but different versions.

**Comment by YungDaVinci** [comment]
Okay but he said he tried master, 5.1, and 5.0. I can build master and play it and not get a segmentation fault.

**Comment by drewbarbs** [comment]
Just got this segfault when trying to enter ScreenSelectMusic on default theme a fresh checkout/build of 5_1-new on a fresh install of Arch. Honestly not sure why some encounter it and others don't, but the crash was in a case statement that was obviously missing break statements, introduced in #1361.

**Comment by YungDaVinci** [comment]
Fixed the problem. Awesome.
