### ISSUE TITLE
[master] Leaving edit menu with an empty chart results in a crash

### ISSUE THREAD

**Issue by YungDaVinci** [stepmania/stepmania#1464]
Doesn't matter if you save it or don't save it, always crashes. No crashlog.txt or anything, just disappears. At least on Linux.

**Comment by quietly-turning** [comment]
The discussion in #1505 suggests that this was fixed in the 5.2 branch.  A quick test of 5.1-new suggests this isn't an issue there.

Closing to have one fewer open issue.
