### ISSUE TITLE
Crash when quit new chart without saving changes

### ISSUE THREAD

**Issue by aeubanks** [stepmania/stepmania#1466]
In edit mode, I started a new couples song on accident, quit out without saving changes, crash. Log:

StepMania5.0.12 crash report (build 45e0787, 20160811 @ 00:05:39)
--------------------------------------

Architecture:   Mac OS X (i386)
Crash reason:   Segmentation fault - address not mapped at 0x00000038
Crashed thread: Main thread

Checkpoints:
Thread: GUI thread
Thread: Main thread
        Screen.cpp:164 ScreenMessage(SM_UpdateTextInfo)
        FontManager.cpp:64 FontManager::UnloadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        FontManager.cpp:64 FontManager::UnloadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        FontManager.cpp:64 FontManager::UnloadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        FontManager.cpp:64 FontManager::UnloadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
Thread: Music thread
Thread: HAL I/O thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: Input thread
Thread: Streaming sound buffering

Thread: Main thread
006ffc66: TimingData::empty() const 
006d4b96: Steps::GetTimingData() const 
00047bef: ArrowEffects::GetYOffset(PlayerState const*, int, float, float&, bool&, bool) 
00262e80: NoteField::Update(float) 
0001eeb5: ActorFrame::UpdateInternal(float) 
0000e684: Actor::Update(float) 
0045b07b: Screen::Update(float) 
0049160d: ScreenEdit::Update(float) 
00571441: ScreenManager::Update(float) 
00147ca8: GameLoop::RunGameLoop() 
006caf6b: sm_main 
0076958b: -[SMMain startGame:] 

Static log:
StepMania5.0.12
Compiled 20160811 @ 00:05:39 (build 45e0787)
Log starting 2017-05-30 22:45:07
Loading window: macosx
Model: MacBookPro12,1 (4/4)
Clock speed 2.70 GHz
Mac OS X 10.12.5
Memory: 8.00 GB
Sound driver: AudioUnit
Lights driver: SystemMessage
WARNING: Main title or music file for '/Songs/Community Keyboard Megapack - Volume 3/(Cynic) #56/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Couldn't open Data/Translations.xml for reading: No such file or directory
WARNING: Couldn't open Data/Translations.xml for reading: No such file or directory
WARNING: Couldn't open Data/Translations.xml for reading: No such file or directory
Video renderers: 'opengl'
Paletted textures disabled: GL_EXT_paletted_texture missing.
WARNING: Error compiling shader Data/Shaders/GLSL/Texture matrix scaling.vert: No such file or directory
WARNING: Error compiling shader Data/Shaders/GLSL/Shell.frag: No such file or directory
WARNING: Error compiling shader Data/Shaders/GLSL/Shell.vert: No such file or directory
WARNING: Error compiling shader Data/Shaders/GLSL/Cel.frag: No such file or directory
WARNING: Error compiling shader Data/Shaders/GLSL/Cel.vert: No such file or directory
WARNING: Error compiling shader Data/Shaders/GLSL/Unpremultiply.frag: No such file or directory
WARNING: Error compiling shader Data/Shaders/GLSL/Color burn.frag: No such file or directory
WARNING: Error compiling shader Data/Shaders/GLSL/Color dodge.frag: No such file or directory
WARNING: Error compiling shader Data/Shaders/GLSL/Vivid light.frag: No such file or directory
WARNING: Error compiling shader Data/Shaders/GLSL/Hard mix.frag: No such file or directory
WARNING: Error compiling shader Data/Shaders/GLSL/Overlay.frag: No such file or directory
WARNING: Error compiling shader Data/Shaders/GLSL/Screen.frag: No such file or directory
WARNING: Error compiling shader Data/Shaders/GLSL/YUYV422.frag: No such file or directory
OGL Vendor: Intel Inc.
OGL Renderer: Intel(R) Iris(TM) Graphics 6100
OGL Version: 2.1 INTEL-10.25.13
OGL Max texture size: 16384
OGL Texture units: 8
GLU Version: 1.3 MacOSX
OGL Extensions:
  GL_APPLE: aux_depth_stencil, client_storage, element_array, fence, float_pixels, flush_buffer_range, 
    flush_render, object_purgeable, packed_pixels, pixel_buffer, rgb_422, row_bytes, specular_vector, 
    texture_range, transform_hint, vertex_array_object, vertex_array_range, vertex_point_size, 
    vertex_program_evaluators, ycbcr_422
  GL_ARB: color_buffer_float, depth_buffer_float, depth_clamp, depth_texture, draw_buffers, 
    draw_elements_base_vertex, draw_instanced, fragment_program, fragment_program_shadow, fragment_shader, 
    framebuffer_object, framebuffer_sRGB, half_float_pixel, half_float_vertex, instanced_arrays, multisample, 
    multitexture, occlusion_query, pixel_buffer_object, point_parameters, point_sprite, provoking_vertex, 
    seamless_cube_map, shader_objects, shader_texture_lod, shading_language_100, shadow, sync, 
    texture_border_clamp, texture_compression, texture_compression_rgtc, texture_cube_map, texture_env_add, 
    texture_env_combine, texture_env_crossbar, texture_env_dot3, texture_float, texture_mirrored_repeat, 
    texture_non_power_of_two, texture_rectangle, texture_rg, transpose_matrix, vertex_array_bgra, vertex_blend, 
    vertex_buffer_object, vertex_program, vertex_shader, window_pos
  GL_ATI: separate_stencil, texture_env_combine3, texture_float, texture_mirror_once
  GL_EXT: abgr, bgra, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, blend_subtract, 
    clip_volume_hint, debug_label, debug_marker, draw_buffers2, draw_range_elements, fog_coord, framebuffer_blit, 
    framebuffer_multisample, framebuffer_multisample_blit_scaled, framebuffer_object, framebuffer_sRGB, 
    geometry_shader4, gpu_program_parameters, gpu_shader4, multi_draw_arrays, packed_depth_stencil, packed_float, 
    provoking_vertex, rescale_normal, secondary_color, separate_specular_color, shadow_funcs, stencil_two_side, 
    stencil_wrap, texture_array, texture_compression_dxt1, texture_compression_s3tc, texture_env_add, 
    texture_filter_anisotropic, texture_integer, texture_lod_bias, texture_rectangle, texture_sRGB, 
    texture_sRGB_decode, texture_shared_exponent, timer_query, transform_feedback, vertex_array_bgra
  GL_IBM_rasterpos_clip
  GL_NV: blend_square, conditional_render, depth_clamp, fog_distance, light_max_exponent, texgen_reflection, 
    texture_barrier
  GL_SGIS: generate_mipmap, texture_edge_clamp, texture_lod
OpenGL Windowed 1280x774 32 color 16 texture 60Hz Vsync SmoothLines
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Unmatched 3 in "0003"
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Background missing: deltaMAX.avi
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
WARNING: Error trying to read "Data/AI.ini" to load AI player skill settings.
Mixing underruns: 1
Players joined: P1
Top Screen: ScreenEdit
Language: en
Current renderer: OpenGL
Theme: home

Partial log:
51:57.479: 61 FPS, 61 av FPS, 7920 VPF, OpenGL
51:57.496: Loading screen: "ScreenPrompt"
51:57.501: Loading /Themes/default/Sounds/default/_Screen cancel.ogg, type FileType_Sound
51:57.501: RageSound: Load "/Themes/default/Sounds/default/_Screen cancel.ogg" (precache: 1)
51:57.504: RageSound: Load "/Themes/default/Sounds/default/Common value.ogg" (precache: 1)
51:57.504: Loaded "ScreenPrompt" ("ScreenPrompt") in 0.008692
51:57.505: PushScreen: "ScreenPrompt"
51:57.505: Zeroing this update.  Was 0.016906
51:58.329: Performing texture garbage collection.
51:58.330: Zeroing this update.  Was 0.065800

-- End of report

**Comment by quietly-turning** [comment]
The discussion in #1505 suggests that this was fixed in the 5.2 branch.  A quick test of 5.1-new suggests this isn't an issue there.

Closing to have one fewer open issue.
