### ISSUE TITLE
Dependencies as of June 2017

### ISSUE THREAD

**Issue by Tatsh** [stepmania/stepmania#1469]
I would suggest the following changes for dependencies as I try to construct a decent ebuild on Gentoo without making things weird, especially having a very specific version of fmtlib (`extern/cppformat`). The idea is to only use stable releases of every library, even if you use git submodules to pull them in (especially for building on systems other than Linux).

- ffmpeg =3.3.x required if `-DWITH_SYSTEM_FFMPEG=ON`, later update this version
- upgrade to fmtlib 3.0.1? don't have your own version?
- system GLEW by default (on Gentoo we have this slotted with versions 1.6, 1.10 and 0 (which really means 1.10.0, 1.13.0 or 2.0.0; 2.0.0 is the one I have installed)
- system jsoncpp by default
- system libjpeg by default (support libjpeg-turbo as the API is supposed to be 100% the same)
- system libogg and libvorbis by default
- system libpng by default
- system libmad by default
- system libpcre by default
- system tommath by default (tomcrypt might be gone from a lot of Linux distros)
- system zlib by default

How forked is the Lua 5.1 included with the source? I have not yet done a comparison. If it is compatible with actual 5.1 (5.1.5 is the only version supported on x86-64 by Gentoo) then it would be nice to have the system version get used there too.

Many of the above libraries do not change a lot in API even across major versions, and I only suggest that major, stable releases of a certain version (like 1.0.x) be supported, not multiple major versions.

Some things can be a little less predictable in particular libav especially when distros apply their own patches. Generally I have not yet had an issue with ffmpeg 3.3 built on Gentoo.

Also FYI, in the case of the tarball source releases, GitHub unfortunately does not pull in sub-modules when it generates these. You should release a tested source tarball that has them included with the correct versions.

I can work on a patch, but I am wondering if everyone involved is open to supporting more system libs as opposed to bundling specific versions, including on a system like a Mac with MacPorts installed.

**Comment by shakesoda** [comment]
SM Lua is definitely incompatible with official Lua. Don't replace it, it'll break everything.

GLEW's going to be removed, but I'm not sure why it'd be a system library anyway.

A few of these libs I'd like to look into removing/replacing (fmt, ogg, png, jpeg, jsoncpp...) or just putting directly into src/. The system lib thing is a pure loss for most of them (causes inconsistency between systems, i.e. crashes), and the submodules have been a pain.

The goal is to distribute builds with as many deps as possible either static linked or in our own source. I know packagers really hate this, but it ensures our bins actually work in as many places as possible.

I'm not personally opposed to people using system libs themselves, but historically when people do we end up seeing all kinds of unfixable crashes caused by distro X's weird flags or ancient/bleeding edge versions, and then package maintainers go enabling all the system flags and the package sucks compared to the official releases (argh! bugs nobody here caused!)

**Comment by Tatsh** [comment]
> The goal is to distribute builds with as many deps as possible either static linked or in our own source. I know packagers really hate this, but it ensures our bins actually work in as many places as possible.

This is the Chrom(e/ium)-way to distribute and given the source size and popularity it makes sense. Chromium packages nearly everything in the source including their own copy of ffmpeg. The ebuild maintainer for Chromium has gone back and forth on using system libs vs not and has basically at this point chosen not to because of unpredictability and lack of support from upstream on this issue.

I have no issues with monolithicity, in this case because the source is complex and not small, as long as the official source distribution (i.e. not the one GitHub generates) comes with the dependencies that must be there (like SM fork of Lua, trusted version of ffmpeg) and other not so common libs not available on the OS/distro (tomcrypt is gone on Gentoo; it used to only be there because of StepMania back when there was a supported ebuild).

**Comment by shakesoda** [comment]
@SpoOkyMagician just the current libs. there are smaller libs for the job these days (stb, lodepng)

**Comment by Tatsh** [comment]
Nothing is suggested for removal. I am only suggesting more flexibility to use the pre-built dependencies that may already exist on a system (mostly a Linux use case). The current build system only allows linking with the system's ffmpeg.

**Comment by Tatsh** [comment]
I would suggest packaging libjpeg-turbo in place of libjpeg for x86-64. It is assembly optimised for new x86-64 instruction sets. Chrome has replaced libjpeg completely with it.

**Comment by Prcuvu** [comment]
You can make a diff between SM-Lua and official 5.1, then apply the diff on a newer version of Lua 5.1.x. This will be backwardly compatible.

**Comment by chrispable** [comment]
An FYI, I am working on a PR that will be using libusb-dev, pretty sure that's pretty rock solid to be used on any platform.

**Comment by ListenerJubatus** [comment]
I was able to do a build successfully with the latest stable glew (2.1.0)
