### ISSUE TITLE
FR: Cache File Type Extentions

### ISSUE THREAD

**Issue by SpoOkyMagician** [stepmania/stepmania#1476]
I discussed this on IRC and while it's only a windows things, I recommend having something as the file extension for the cache. In windows, it's just a garbled mess. (By Default, they are "file") I recommend ending it with something like...

.cache
.cach
.cah

or something along those lines. (Preferable a 3 character ending. Which is the standard for Windows.)

**Comment by Flameshadowxeroshin** [comment]
there's no reason that windows has to have 3-character extensions, you could do .sm5-cache if you wanted

**Comment by concubidated** [comment]
Should be a super simple change, but is there really any reason though? This shouldn't even be a directory users should have to go into at all.

Something like this in Song.cpp 
```c++
std::string Song::GetCacheFilePath() const
{
	return SongCacheIndex::GetCacheFilePath( "Songs", m_sSongDir+".cache" );
}
```
Didn't look if anywhere else would need it.

**Comment by concubidated** [comment]
Closing, either PR will get merged or not.
