### ISSUE TITLE
OS X Services Menu

### ISSUE THREAD

**Issue by stonedune** [stepmania/stepmania#1477]
Is there a way to compile or setup Stepmania for OS X to enable the "Services" menu? I am using it on a headless computer and want to use a service to manage open/closing of applications. I have the service setup but can not access it while Stepmania is the active application.

**Comment by shakesoda** [comment]
not that I'm aware of.

**Comment by stonedune** [comment]
Ok, I've also put up a post on the apple dev forum to see if it's a compiling issue or something else.
Thanks
