### ISSUE TITLE
[CLOSE THIS] Half transparent images not transparent

### ISSUE THREAD

**Issue by ARCofSpada** [stepmania/stepmania#1482]
If you load an image with only transparency and no fully opaque pixels, the transparent parts will be opaque.

Example image if you want to test: https://arcofswords.s-ul.eu/Y5hAjVuI.png

You'll see that it's fully opaque in StepMania.

Tested in OpenGL with both Windows and Linux. DirectX not tested.

**Comment by shakesoda** [comment]
info.txt please

**Comment by ARCofSpada** [comment]
`StepMania5.1-UNKNOWN
Compiled 20170225 @ 15:47:19 (build UNKNOWN)
Log starting 2017-06-13 21:46:14
Loading window: gtk
OS: Linux ver 040400
Crash backtrace component: x86 custom backtrace
Crash lookup component: backtrace_symbols
Runtime library: glibc 2.23
Threads library: NPTL 2.23
libavcodec: 0x372765 (3614565)
WARNING: Lua runtime error: /Themes/Konami will sue 22/Scripts/91 CustomOptions Fixed.lua:74: attempt to index global 'SCREENMAN' (a nil value)
WARNING: /Themes/Konami will sue 22/Scripts/91 CustomOptions Fixed.lua:74: main(SL_CustomPrefs = (null),file = (null),NeedsRewrite = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = 0,(*temporary) = (null),(*temporary) = attempt to index global 'SCREENMAN' (a nil value))
ALSA: Advanced Linux Sound Architecture Driver Version k4.4.0-22-generic.
ALSA Driver: 0: HDA Intel PCH [PCH], device 0: ALC3246 Analog [ALC3246 Analog], 0/1 subdevices avail
ALSA Driver: 0: HDA Intel PCH [PCH], device 3: HDMI 0 [HDMI 0], 1/1 subdevices avail
ALSA Driver: 0: HDA Intel PCH [PCH], device 7: HDMI 1 [HDMI 1], 1/1 subdevices avail
ALSA Driver: 0: HDA Intel PCH [PCH], device 8: HDMI 2 [HDMI 2], 1/1 subdevices avail
ALSA: dsnd_pcm_hw_params_set_access: Invalid argument
Couldn't load driver ALSA-sw: SetHWParams failed
Couldn't load driver OSS: RageSoundDriver_OSS: Couldn't open /dev/dsp: No such file or directory
Sound driver: Pulse
Lights driver: SystemMessage
Lights driver: Export
WARNING: Main title or music file for '/Songs/IIDX 22 Pendual/The_Relentless/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
Video renderers: 'opengl'
Display: :0 (screen 0)
X server vendor: The X.Org Foundation [1.18.4.0]
Server GLX vendor: NVIDIA Corporation [1.4]
Client GLX vendor: NVIDIA Corporation [1.4]
Paletted textures disabled: GL_EXT_paletted_texture missing.
Direct rendering: yes
OGL Vendor: NVIDIA Corporation
OGL Renderer: GeForce GTX 960M/PCIe/SSE2
OGL Version: 4.5.0 NVIDIA 375.39
OGL Max texture size: 16384
OGL Texture units: 4
GLU Version: 1.3
OGL Extensions:
  GL_AMD: multi_draw_indirect, seamless_cubemap_per_texture
  GL_ARB: ES2_compatibility, ES3_1_compatibility, ES3_2_compatibility, ES3_compatibility, arrays_of_arrays, 
    base_instance, bindless_texture, blend_func_extended, buffer_storage, clear_buffer_object, clear_texture, 
    clip_control, color_buffer_float, compatibility, compressed_texture_pixel_storage, compute_shader, 
    compute_variable_group_size, conditional_render_inverted, conservative_depth, copy_buffer, copy_image, 
    cull_distance, debug_output, depth_buffer_float, depth_clamp, depth_texture, derivative_control, 
    direct_state_access, draw_buffers, draw_buffers_blend, draw_elements_base_vertex, draw_indirect, 
    draw_instanced, enhanced_layouts, explicit_attrib_location, explicit_uniform_location, 
    fragment_coord_conventions, fragment_layer_viewport, fragment_program, fragment_program_shadow, 
    fragment_shader, framebuffer_no_attachments, framebuffer_object, framebuffer_sRGB, geometry_shader4, 
    get_program_binary, get_texture_sub_image, gl_spirv, gpu_shader5, gpu_shader_fp64, gpu_shader_int64, 
    half_float_pixel, half_float_vertex, imaging, indirect_parameters, instanced_arrays, internalformat_query, 
    internalformat_query2, invalidate_subdata, map_buffer_alignment, map_buffer_range, multi_bind, 
    multi_draw_indirect, multisample, multitexture, occlusion_query, occlusion_query2, parallel_shader_compile, 
    pipeline_statistics_query, pixel_buffer_object, point_parameters, point_sprite, program_interface_query, 
    provoking_vertex, query_buffer_object, robust_buffer_access_behavior, robustness, sample_shading, 
    sampler_objects, seamless_cube_map, seamless_cubemap_per_texture, separate_shader_objects, 
    shader_atomic_counter_ops, shader_atomic_counters, shader_ballot, shader_bit_encoding, shader_clock, 
    shader_draw_parameters, shader_group_vote, shader_image_load_store, shader_image_size, shader_objects, 
    shader_precision, shader_storage_buffer_object, shader_subroutine, shader_texture_image_samples, 
    shader_texture_lod, shading_language_100, shading_language_420pack, shading_language_include, 
    shading_language_packing, shadow, sparse_buffer, sparse_texture, stencil_texturing, sync, tessellation_shader, 
    texture_barrier, texture_border_clamp, texture_buffer_object, texture_buffer_object_rgb32, 
    texture_buffer_range, texture_compression, texture_compression_bptc, texture_compression_rgtc, 
    texture_cube_map, texture_cube_map_array, texture_env_add, texture_env_combine, texture_env_crossbar, 
    texture_env_dot3, texture_float, texture_gather, texture_mirror_clamp_to_edge, texture_mirrored_repeat, 
    texture_multisample, texture_non_power_of_two, texture_query_levels, texture_query_lod, texture_rectangle, 
    texture_rg, texture_rgb10_a2ui, texture_stencil8, texture_storage, texture_storage_multisample, 
    texture_swizzle, texture_view, timer_query, transform_feedback2, transform_feedback3, 
    transform_feedback_instanced, transform_feedback_overflow_query, transpose_matrix, uniform_buffer_object, 
    vertex_array_bgra, vertex_array_object, vertex_attrib_64bit, vertex_attrib_binding, vertex_buffer_object, 
    vertex_program, vertex_shader, vertex_type_10f_11f_11f_rev, vertex_type_2_10_10_10_rev, viewport_array, 
    window_pos
  GL_ATI: draw_buffers, texture_float, texture_mirror_once
  GL_EXTX_framebuffer_mixed_formats
  GL_EXT: Cg_shader, abgr, bgra, bindable_uniform, blend_color, blend_equation_separate, blend_func_separate, 
    blend_minmax, blend_subtract, compiled_vertex_array, depth_bounds_test, direct_state_access, draw_buffers2, 
    draw_instanced, draw_range_elements, fog_coord, framebuffer_blit, framebuffer_multisample, 
    framebuffer_multisample_blit_scaled, framebuffer_object, framebuffer_sRGB, geometry_shader4, 
    gpu_program_parameters, gpu_shader4, import_sync_object, multi_draw_arrays, packed_depth_stencil, 
    packed_float, packed_pixels, pixel_buffer_object, point_parameters, polygon_offset_clamp, provoking_vertex, 
    rescale_normal, secondary_color, separate_shader_objects, separate_specular_color, 
    shader_image_load_formatted, shader_image_load_store, shader_integer_mix, shadow_funcs, stencil_two_side, 
    stencil_wrap, texture3D, texture_array, texture_buffer_object, texture_compression_dxt1, 
    texture_compression_latc, texture_compression_rgtc, texture_compression_s3tc, texture_cube_map, 
    texture_edge_clamp, texture_env_add, texture_env_combine, texture_env_dot3, texture_filter_anisotropic, 
    texture_integer, texture_lod, texture_lod_bias, texture_mirror_clamp, texture_object, texture_sRGB, 
    texture_sRGB_decode, texture_shared_exponent, texture_storage, texture_swizzle, timer_query, 
    transform_feedback2, vertex_array, vertex_array_bgra, vertex_attrib_64bit, window_rectangles, x11_sync_object
  GL_IBM: rasterpos_clip, texture_mirrored_repeat
  GL_KHR: blend_equation_advanced, blend_equation_advanced_coherent, context_flush_control, debug, no_error, 
    robust_buffer_access_behavior, robustness
  GL_KTX_buffer_region
  GL_NVX: conditional_render, gpu_memory_info, nvenc_interop
  GL_NV: ES1_1_compatibility, ES3_1_compatibility, alpha_to_coverage_dither_control, bindless_multi_draw_indirect, 
    bindless_multi_draw_indirect_count, bindless_texture, blend_equation_advanced, 
    blend_equation_advanced_coherent, blend_square, command_list, compute_program5, conditional_render, 
    copy_depth_to_color, copy_image, depth_buffer_float, depth_clamp, draw_texture, draw_vulkan_image, 
    explicit_multisample, fence, float_buffer, fog_distance, fragment_program, fragment_program2, 
    fragment_program_option, framebuffer_multisample_coverage, geometry_shader4, gpu_program4, gpu_program4_1, 
    gpu_program5, gpu_program5_mem_extended, gpu_program_fp64, gpu_shader5, half_float, 
    internalformat_sample_query, light_max_exponent, multisample_coverage, multisample_filter_hint, 
    occlusion_query, packed_depth_stencil, parameter_buffer_object, parameter_buffer_object2, path_rendering, 
    pixel_data_range, point_sprite, primitive_restart, register_combiners, register_combiners2, 
    robustness_video_memory_purge, shader_atomic_counters, shader_atomic_float, shader_atomic_int64, 
    shader_buffer_load, shader_storage_buffer_object, shader_thread_group, shader_thread_shuffle, 
    texgen_reflection, texture_barrier, texture_compression_vtc, texture_env_combine4, texture_multisample, 
    texture_rectangle, texture_shader, texture_shader2, texture_shader3, transform_feedback, transform_feedback2, 
    uniform_buffer_unified_memory, vdpau_interop, vertex_array_range, vertex_array_range2, 
    vertex_attrib_integer_64bit, vertex_buffer_unified_memory, vertex_program, vertex_program1_1, vertex_program2, 
    vertex_program2_option, vertex_program3
  GL_S3_s3tc
  GL_SGIS: generate_mipmap, texture_lod
  GL_SGIX: depth_texture, shadow
  GL_SUN_slice_accum
OpenGL Windowed 854x480 16 color 16 texture 50Hz NoVsync SmoothLines
LinuxEvent: Couldn't open /dev/input/event0: Permission denied.
LinuxEvent: Couldn't open /dev/input/event1: Permission denied.
LinuxEvent: Couldn't open /dev/input/event2: Permission denied.
LinuxEvent: Couldn't open /dev/input/event3: Permission denied.
LinuxEvent: Couldn't open /dev/input/event4: Permission denied.
LinuxEvent: Couldn't open /dev/input/event8: Permission denied.
LinuxEvent: Couldn't open /dev/input/event5: Permission denied.
LinuxEvent: Couldn't open /dev/input/event6: Permission denied.
LinuxEvent: Couldn't open /dev/input/event7: Permission denied.
LinuxEvent: Couldn't open /dev/input/event9: Permission denied.
LinuxEvent: Couldn't open /dev/input/event10: Permission denied.
LinuxEvent: Couldn't open /dev/input/event11: Permission denied.
LinuxEvent: Couldn't open /dev/input/event12: Permission denied.
LinuxEvent: Couldn't open /dev/input/event13: Permission denied.
LinuxEvent: Couldn't open /dev/input/event14: Permission denied.
LinuxEvent: Couldn't open /dev/input/event15: Permission denied.
LinuxEvent: Couldn't open /dev/input/event16: Permission denied.
WARNING: The graphic '/Themes/Konami will sue 22/BGAnimations/_footer_header/frame_armor_grd01.png' has frame dimensions that aren't a multiple of 2.
WARNING: The entire image is 1282x279 and frame size is 1282.0x279.0.
WARNING: Image quality will be much improved if you resize the graphic to 1282x280, which is a frame size of 1282x280.
`

**Comment by shakesoda** [comment]
Does this also happen with 32-bit color and texture set in video options?

**Comment by ARCofSpada** [comment]
I was able to reproduce it inside an ActorScroller only.

Test theme download: https://arcofswords.s-ul.eu/rHlzji1l.7z

Might be an issue with the ActorScroller, but it doesn't seem like it.
image is in Graphics/ScreenSelectPlayMode scroll Choice. You can see it in ScreenSelectPlayMode.
