### ISSUE TITLE
Stepmania in buisness

### ISSUE THREAD

**Issue by Cermeke** [stepmania/stepmania#1483]
Hello, I'm writing to ask you for some information for Stepmania's game.I want too start my own buisness and i would like to know , is stepmania can be used in profit targets?I mean i want to take Dance pad and play stepmania on this for money.Is it legal?Second question is that can you tell me that your music in Stepmania, for example "La Bamba" or "Don't stop the music" are protected by copyright?

**Comment by ARCofSpada** [comment]
1. StepMania only comes with three songs, you can't use them for business. Everything else is made by other people and is not part of StepMania.
2. You are free to use StepMania for whatever you want as long as you adhere to the licencing terms, and it's your job to determine the legality of that.

**Comment by shakesoda** [comment]
stepmania can be used for commercial purposes, but you must properly license songs and the ones we include may not be used for this.

songs you download off the internet cannot be used this way either, you must ask the artist/publisher for permission.
