### ISSUE TITLE
No input in Fullscreen mode on Wayland

### ISSUE THREAD

**Issue by Ancovens** [stepmania/stepmania#1487]
I can't use my keyboard when Stepmania 5_0 branch run in full screen. I can't exit from the StepMania in the GNOME shell because when I press super it doesn't shows StepMania is running. In don't have this problem in 5.1 when I run it in exclusive mode.
I use Fedora 25 and I use my I5-6600's IGP.

**Comment by concubidated** [comment]
5_0 has been superseded by 5_1-new, can you try building and testing that branch?

(The old 5.1 is now 5.2)

**Comment by Ancovens** [comment]
Yes. I am trying it.

**Comment by Ancovens** [comment]
It has the same problem but I think it will work in exclusive mode. I try Cyberia theme with it. I hope it will work.

**Comment by Ancovens** [comment]
Thank you it works fine!

**Comment by Ancovens** [comment]
I I found a problem :(
When I exit from a song it exit from the game too :(
Is the 5.1_new fully compatible with the 5.0?

**Comment by concubidated** [comment]
@Ancovens  Sorry for the delay in getting back to you. 5.0 content is compatible with 5.1-new

**Comment by dseomn** [comment]
I'm still having this problem in the latest release on flathub, 5.1.0-b2, which seems to have come out after this bug was closed. Does 5.1.0-b2 include the changes from `5_1-new` that were supposed to fix this? Or if it's only fixed in exclusive mode, what is exclusive mode?

**Comment by dseomn** [comment]
I just found the `FullscreenIsBorderlessWindow` option in `Preferences.ini`. Setting that to 1 seems to work around this issue.
