### ISSUE TITLE
[5.0.12] Every noteskin replaced with default?

### ISSUE THREAD

**Issue by StardustAlpha** [stepmania/stepmania#1492]
No mater what noteskin I try, it just looks like the default. Like, EXACTLY the same. This happens on the Default theme and Simply Love SM5 Port, but it works fine on consensual. Also recorded me trying to use metal 3d noteskin in default and consensual.
https://youtu.be/aDSFxLRlDq4
https://youtu.be/ubn7LWSCf90

**Comment by dguzek** [comment]
What OS are you using?  Where do you have StepMania installed to?  Where do you have your NoteSkins installed to?

**Comment by kyzentun** [comment]
As a fun aside, let's trace the path through the code for setting a noteskin from an option.

First we have OptionRowHandler.cpp, OptionRowHandlerListNoteSkins.
```c++
GameCommand mc;
mc.m_sPreferredModifiers = arraySkinNames[skin];
m_aListEntries.push_back( mc );
m_Def.m_vsChoices.push_back( arraySkinNames[skin] );
```
This creates a GameCommand for each choice in the option row.  The GameCommand has the noteskin name in the PreferredModifiers variable.  That variable also stores things like Drunk, Left, Dizzy, and so on.

Next is GameCommand.cpp.  Skipping straight to the relevant part of ApplySelf:
```c++
GAMESTATE->ApplyPreferredModifiers( *pn, m_sPreferredModifiers );
```

GameState.cpp:
```c++
void GameState::ApplyPreferredModifiers( PlayerNumber pn, RString sModifiers )
{
	m_pPlayerState[pn]->m_PlayerOptions.FromString( ModsLevel_Preferred, sModifiers );
	m_SongOptions.FromString( ModsLevel_Preferred, sModifiers );
}
```

In PlayerOptions.cpp we see this in FromString:
```c++
split( sTemp, ",", vs, true );
```
Which splits the entire mod string into parts at commas.  If there is a comma in a noteskin name, or the name of anything, that name will get broken up here.  There is no escaping or quoting to allow a comma in anything that might need it.

Each part then goes to FromOneModString, which has this:
```c++
split( sBit, " ", asParts, true );
```
That split is for parsing things like "*2 200% tipsy", where the parts control how tipsy is applied.

The parts go through some parsing for that format before reaching this:
```c++
sBit = asParts.back();
```

This is what breaks noteskin names that have a space.

If the noteskin name is ```"metal 3d"```, then asParts contains ```{"metal", "3d"}```.  sBit is then set to ```"3d"```.

**Comment by StardustAlpha** [comment]
Using Mac OS X, and my stepmania folder is on my desktop [not the folder from the dmg because that one denies Stepmania's access to the Noteskin folder], My noteskins ARE in Noteskins>Dance.

**Comment by dguzek** [comment]
It seems that the fix for now is to not have spaces in your NoteSkin folder names.  Kyzentun has been kind enough to [submit a pull request](https://github.com/stepmania/stepmania/pull/1493) fixing this, so this may not be necessary in future versions of SM5.
