### ISSUE TITLE
Feature Request: "New" vs "Old" difficulty field in SM file parser

### ISSUE THREAD

**Issue by dzackgarza** [stepmania/stepmania#1494]
It looks like a number of people on various forums have been running into this problem, so I figured I would bring up a discussion of it over here and see what people working on SM think.

The switch in official mixes from the 1-10 foot scale to the new 1-19 scale has really wreaked havoc on the simfile community. In an arbitrary SM file, there's no way of telling which scale the difficulty is calibrated against, and so it's easy to end up with (for example) new-style DDR 12s, which are relatively easy, mixed in with old-style DDR/ITG 12s, which are extremely difficult. 

For a while, people were manually converting old difficulties to new ones, usually just running a script over old simfiles and multiplying the difficulties by 1.5 or something. Other people took the opposite approach, running a script over the _new_ simfiles to convert them back to the old scale.

As of now, many of the official packs have switched over to the new scale, but the vast majority of non-official simfiles out there remain on the old one. 

I'm not sure if there actually _is_ a good solution to this, but it seems like retroactively converting every simfile that's been made in the past 10+ years to the new scale is not really feasible. That being said, one idea to address this would be to introduce a new field to the .sm file format that documents which scale the file is calibrated against.

This approach has a couple of advantages:
- This would make it possible for Stepmania to _internally_ convert between old and new scales (e.g. using the same multiplicative factor that people have been using in scripts or even just a lookup table)
- Migrating old simfile packs to the new scales becomes much simpler, as it only involves adding a single field (rather than overwriting the old difficulty field and potentially losing that information forever)
- It makes the checking/conversion process easier to automate (i.e. the lack of this field makes it easy to identify files on the old scale)
- For old simfiles, this preserves the simfile author's original intended difficulty level
- For new simfiles, it forces the authors to document the _relative_ difficulty of the file

Plus, with the addition of a little internal logic, it seems like this would make it possible to introduce options for Stepmania users to display their entire collection in a particular scale, provided all of their simfiles have this field. (Much like the current option to use the "old" scoring system vs. the "new" SN2 system)

For example, if someone prefers the old 1-10 scale, everything with the field set to "old" would be displayed as-is, while any field file with the field set to "new" would trigger a function that modifies the difficulty level that is displayed on the song wheel and used for grouping.

Similar, if someone preferred the new scale, all of the files with the field set to "new" display as-is, while files set to "old" have their difficulties multiplied by 1.5 (or whatever the conversion is) when they are displayed/sorted.

Again, I don't know if this is the _right_ solution, but since so many people in the community are doing these conversions in an ad-hoc way right now, something like this seems like a good candidate to be moved into internal code in a future release.

**Comment by concubidated** [comment]
I believe SM can already predict the difficulty of a chart (old scale). The editor for example trys to guess how hard the chart is? I have seen some themes do this as well too. I think consensual did something in like this in it too?

Are they any packs other then the newer DDR packs using the Konami new scale? I believe most people prefer and use the old scale.

**Comment by dzackgarza** [comment]
Ahh so I haven't seen this functionality anywhere - is this something people are scripting into their themes somehow?

The way this issue is cropping up for me is that I've started with a base of DDR packs. Places like Zenius are retroactively converting everything to the new scale, so everything is pretty consistent if you're just using officials. (Although this isn't great since ideally you'd want to keep those original difficulties around, after all of the work went into matching those with the difficulties displayed in arcade releases)

If you start trying to add in customs or older packs, though, it can be a mixed bag - a majority are on the old scale, some have had a conversion script run on them, and there are even some that are on the old scale but still have difficulties reaching up into the 16s. So it can be tough to determine what scale a file is on until you actually play it.

I'm mainly just trying to find a way for to automatically keep a song collection consistent, whether it's on the old or the new scale. So in my case, the main roadblock is just not having a (reliable, automatable) way of determining the scale.

**Comment by dzackgarza** [comment]
Another potential use-case where this is an issue is when you want to allow people to play/import songs from USB drives or something. If your files are all on one scale and theirs are on the other, there's just not a really good solution there - you either have an extremely hard song (e.g. old 13) mixed into easy ones (new 13s), or an easy song buried amongst difficult ones.

You could feasibly run a script to try and match things up before importing their simfile, but then you have to heuristically guess which scale it's on.

**Comment by Flameshadowxeroshin** [comment]
The best we could probably do is have something like a free-text METERTYPE field, because to my knowledge there's at least six different scales some people are actively using for new .sm/.ssc files, plus plenty more only used in other formats that SM can import.

**Comment by dzackgarza** [comment]
Seems like a good option - if that were to go in, how difficult would it be to add a hook in somewhere before a chart's difficulty is accessed? My thought is that maybe it would be possible to have a function that can perform some intermediate logic any time the difficulty is accessed/calculated (e.g for the song wheel display) , which hopefully has access to the rest of the chart metadata. In this case, it'd be checking for the existence of that text field, and doing some kind of appropriate conversion before returning the difficulty rating.

(Although I guess there would also have to be a global preference for which difficulty scale everything should end up in? )

**Comment by he29-net** [comment]
This issue was marked as completed, but I do not see any linked PR that resolves the issue. Was it implemented in some other version (I lost track of all the Stepmania forks a decade ago), or was it abandoned? It seems like an easy and useful fix for a common problem.
