### ISSUE TITLE
Feature Request: Add "Jump to next note" to the editor's shortcuts list ("." and ",").

### ISSUE THREAD

**Issue by ra-om** [stepmania/stepmania#1496]
I would love a hotkey that makes the editor jump to the exact position of each note, so I can edit notes easily while preserving their timing. It'd make it possible to create new step charts much more easily than it is currently, by using the recording feature and timing the notes by ear, then changing those notes to whatever pattern one wishes.

**Comment by kyzentun** [comment]
Press comma or period.

**Comment by ra-om** [comment]
Thank you very much!. I found it very odd such a simple feature had not been implemented. I modified the title of the issue accordingly.

**Comment by concubidated** [comment]
This has been added to master branch
