### ISSUE TITLE
Getting a course entry that doesn't exist causes an access violation

### ISSUE THREAD

**Issue by RhythmLunatic** [stepmania/stepmania#1497]
This is inside ScreenSelectMusic underlay. Right when you select the next course (ScreenSelectCourse falls back on ScreenSelectMusic), it crashes.

The lua is inside a for loop. Substitute 'i' for any digit beyond the number of course entries you have.
```lua
LoadFont("TextBanner text")..{
	InitCommand=cmd(horizalign,left;settext,"test";addx,80;addy,-2;zoom,.75);
	CurrentCourseChangedMessageCommand=function(self)
		local course = GAMESTATE:GetCurrentCourse();
		if course then
			local song = course:GetCourseEntry(i):GetSong();
			if song then
				self:settext(song:GetDisplayMainTitle()); --The crash is triggered here, if you comment it out nothing happens
			end;
		end;
	end;
};
```

**Comment by kyzentun** [comment]
Additional problem: Course does not have a function for getting the number of entries.  Just GetCourseEntry for getting one entry, and GetCourseEntries for getting all of them.
