### ISSUE TITLE
Scoreboard in network play covers lane

### ISSUE THREAD

**Issue by zelbrium** [stepmania/stepmania#1500]
On a clean install of both 5.0.12 and 5.1.-3, with the only configuration change being "Center 1 Player" switched to On, the scoreboard in network play covers part of the lane. This occurs on macOS 10.11 (El Capitan), although I'm not sure about other OSes. The display resolution has no effect on the covering. ~~5.0.10 does not have this issue.~~

<img width="1440" alt="screen shot 2017-07-10 at 6 34 25 pm" src="https://user-images.githubusercontent.com/7142049/28043319-5bd4d8d6-659f-11e7-9f56-2a9c4c3cb7c4.png">

**Comment by concubidated** [comment]
Yeah, you can disable 'Center 1 Player' or edit the theme to move the score board stuff around. 

You can add these metrics from fallback to your default theme and position it where you would like.

https://github.com/stepmania/stepmania/blob/master/Themes/_fallback/metrics.ini#L3540-L3560

**Comment by zelbrium** [comment]
Never mind, I'm dumb. 5.0.10 also has this issue. I had played a version of SM that didn't have this problem, but it must have been an older version. I'm not sure which.

**Comment by zelbrium** [comment]
Uh, I wouldn't exactly call this "closed." It's still a bug.
