### ISSUE TITLE
StepMania doesn't startup

### ISSUE THREAD

**Issue by NickolasNeptune** [stepmania/stepmania#1509]
So, I just downloaded StepMania for Windows, and it won't startup. My Windows version is Windows 10.
I don't know what's wrong. Here's the Crash Info and Log. 

StepMania5.0.12 crash report (build 45e0787, 20160811 @ 00:34:46)
--------------------------------------

Crash reason: Access Violation

Thread: Main thread
        GraphicsWindow.cpp:179 000A07B4, 512, 00000000, 01280070
        GraphicsWindow.cpp:54 000A07B4, 127, 00000000, 00000060
        GraphicsWindow.cpp:179 000A07B4, 127, 00000000, 00000060
        GraphicsWindow.cpp:54 000A07B4, 15, 00000000, 00000000
        GraphicsWindow.cpp:179 000A07B4, 15, 00000000, 00000000
Thread: Decode thread
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
def00980: ???!7fff0000
0ca90bf5: atioglxx!DrvPresentBuffers [0b640000+13ad20+1315ed5]
0ca9119e: atioglxx!DrvPresentBuffers [0b640000+13ad20+131647e]
0ca87790: atioglxx!DrvPresentBuffers [0b640000+13ad20+130ca70]
0ca81f9b: atioglxx!DrvPresentBuffers [0b640000+13ad20+130727b]
0ca7373d: atioglxx!DrvPresentBuffers [0b640000+13ad20+12f8a1d]
0ca73724: atioglxx!DrvPresentBuffers [0b640000+13ad20+12f8a04]
0ca840c1: atioglxx!DrvPresentBuffers [0b640000+13ad20+13093a1]
0ca7e3f3: atioglxx!DrvPresentBuffers [0b640000+13ad20+13036d3]
0ca6dea0: atioglxx!DrvPresentBuffers [0b640000+13ad20+12f3180]
0ca6bf30: atioglxx!DrvPresentBuffers [0b640000+13ad20+12f1210]
0b75e289: atioglxx!atiPPHSN [0b640000+116a00+7889]
772996c9: ntdll!RtlUnicodeStringToAnsiString [77240000+59620+a9]
75d62ed4: KERNEL32!GetSystemWindowsDirectoryA [75d40000+22e30+a4]
0b7567a5: atioglxx!DrvSwapBuffers [0b640000+10cd10+9a95]
0b74ce43: atioglxx!DrvSwapBuffers [0b640000+10cd10+133]
0b793c51: atioglxx!DrvPresentBuffers [0b640000+13ad20+18f31]
7728766b: ntdll!RtlAllocateHeap [77240000+45b00+1b6b]
77287447: ntdll!RtlAllocateHeap [77240000+45b00+1947]
77287447: ntdll!RtlAllocateHeap [77240000+45b00+1947]
77287447: ntdll!RtlAllocateHeap [77240000+45b00+1947]
772892c9: ntdll!RtlFreeHeap [77240000+48480+e49]
7728603a: ntdll!RtlAllocateHeap [77240000+45b00+53a]
77285c95: ntdll!RtlAllocateHeap [77240000+45b00+195]
77285c0c: ntdll!RtlAllocateHeap [77240000+45b00+10c]
77285b32: ntdll!RtlAllocateHeap [77240000+45b00+32]
0104f693: StepMania!00b80000
01067b96: StepMania!00b80000
77284ec7: ntdll!RtlDosSearchPath_Ustr [77240000+44580+947]
77285c0c: ntdll!RtlAllocateHeap [77240000+45b00+10c]
77285b32: ntdll!RtlAllocateHeap [77240000+45b00+32]
772858f9: ntdll!RtlDosSearchPath_Ustr [77240000+44580+1379]
7728590c: ntdll!RtlDosSearchPath_Ustr [77240000+44580+138c]
7728766b: ntdll!RtlAllocateHeap [77240000+45b00+1b6b]
77287447: ntdll!RtlAllocateHeap [77240000+45b00+1947]
77287447: ntdll!RtlAllocateHeap [77240000+45b00+1947]
77287447: ntdll!RtlAllocateHeap [77240000+45b00+1947]
772892c9: ntdll!RtlFreeHeap [77240000+48480+e49]
01041882: StepMania!00b80000
01041790: StepMania!00b80000
0104179f: StepMania!00b80000
01040f5e: StepMania!00b80000
01040f91: StepMania!00b80000
01040112: StepMania!00b80000
0103fcb9: StepMania!00b80000
0103fcde: StepMania!00b80000
77284ec7: ntdll!RtlDosSearchPath_Ustr [77240000+44580+947]
77285c0c: ntdll!RtlAllocateHeap [77240000+45b00+10c]
77285b32: ntdll!RtlAllocateHeap [77240000+45b00+32]
772858f9: ntdll!RtlDosSearchPath_Ustr [77240000+44580+1379]
7728590c: ntdll!RtlDosSearchPath_Ustr [77240000+44580+138c]
77285c0c: ntdll!RtlAllocateHeap [77240000+45b00+10c]
77283232: ntdll!RtlAnsiStringToUnicodeString [77240000+43180+b2]
77283261: ntdll!RtlAnsiStringToUnicodeString [77240000+43180+e1]
7726e7d3: ntdll!SbSelectProcedure [77240000+2e680+153]
7726e7ef: ntdll!SbSelectProcedure [77240000+2e680+16f]
772692e9: ntdll!RtlRestoreLastWin32Error [77240000+292b0+39]
76349f23: KERNELBASE!OpenThreadToken [76280000+c9ed0+53]
7634a9b1: KERNELBASE!CreateFileW [76280000+ca5c0+3f1]
7634a9a4: KERNELBASE!CreateFileW [76280000+ca5c0+3e4]
7634a61e: KERNELBASE!CreateFileW [76280000+ca5c0+5e]
772692e9: ntdll!RtlRestoreLastWin32Error [77240000+292b0+39]
0ca8b2af: atioglxx!DrvPresentBuffers [0b640000+13ad20+131058f]
772692e9: ntdll!RtlRestoreLastWin32Error [77240000+292b0+39]
0ca8b2af: atioglxx!DrvPresentBuffers [0b640000+13ad20+131058f]
0ca88a41: atioglxx!DrvPresentBuffers [0b640000+13ad20+130dd21]
0ca840c1: atioglxx!DrvPresentBuffers [0b640000+13ad20+13093a1]
0ca91178: atioglxx!DrvPresentBuffers [0b640000+13ad20+1316458]
0ca8c671: atioglxx!DrvPresentBuffers [0b640000+13ad20+1311951]
0ca90c26: atioglxx!DrvPresentBuffers [0b640000+13ad20+1315f06]
0ca90bf5: atioglxx!DrvPresentBuffers [0b640000+13ad20+1315ed5]
0ca90bf5: atioglxx!DrvPresentBuffers [0b640000+13ad20+1315ed5]
0ca9119e: atioglxx!DrvPresentBuffers [0b640000+13ad20+131647e]
0ca87790: atioglxx!DrvPresentBuffers [0b640000+13ad20+130ca70]
0ca81f9b: atioglxx!DrvPresentBuffers [0b640000+13ad20+130727b]
0ca73724: atioglxx!DrvPresentBuffers [0b640000+13ad20+12f8a04]
0ca840c1: atioglxx!DrvPresentBuffers [0b640000+13ad20+13093a1]
0ca7e3f3: atioglxx!DrvPresentBuffers [0b640000+13ad20+13036d3]
0b6da2c5: atioglxx!getIcdInterfaceES2 [0b640000+94ad0+57f5]
77284570: ntdll!RtlFreeUnicodeString [77240000+44530+40]
0b6d9357: atioglxx!getIcdInterfaceES2 [0b640000+94ad0+4887]
0b6da430: atioglxx!getIcdInterfaceES2 [0b640000+94ad0+5960]
772657f8: ntdll!RtlDeleteBoundaryDescriptor [77240000+257e0+18]
7726fa9e: ntdll!RtlSidDominatesForTrust [77240000+2f120+97e]
77270ae5: ntdll!RtlGetActiveActivationContext [77240000+30790+355]
77270b0d: ntdll!RtlGetActiveActivationContext [77240000+30790+37d]
0f42b934: atigktxx!DisableSubmitThread [0f410000+d754+e1e0]
772ca611: ntdll!LdrSetAppCompatDllRedirectionCallback [77240000+83220+73f1]
7726f737: ntdll!RtlSidDominatesForTrust [77240000+2f120+617]
7726f746: ntdll!RtlSidDominatesForTrust [77240000+2f120+626]
7726fa0e: ntdll!RtlSidDominatesForTrust [77240000+2f120+8ee]
7726fa2b: ntdll!RtlSidDominatesForTrust [77240000+2f120+90b]
772657f8: ntdll!RtlDeleteBoundaryDescriptor [77240000+257e0+18]
7727f806: ntdll!RtlImageNtHeaderEx [77240000+3f640+1c6]
7729acb6: ntdll!RtlTimeFieldsToTime [77240000+5a9c0+2f6]
772801df: ntdll!RtlEnterCriticalSection [77240000+3ff20+2bf]
772801df: ntdll!RtlEnterCriticalSection [77240000+3ff20+2bf]
7727cd94: ntdll!RtlpCreateProcessRegistryInfo [77240000+3c9c0+3d4]
7727cdb6: ntdll!RtlpCreateProcessRegistryInfo [77240000+3c9c0+3f6]

Static log:
StepMania5.0.12
Compiled 20160811 @ 00:34:46 (build 45e0787)
Log starting 2017-07-24 21:52:07
Loading window: win32
Windows 6.2 (Win8) build 9200 []
Memory: 2047mb total, 4095mb swap (3667mb swap avail)
Video driver: AMD Radeon R7 200 Series [Advanced Micro Devices, Inc.]
              22.19.162.4, 4-24-2017 [pci\ven_1002&dev_6613]
Drive: "        ST1000DM003-1ER1CC45" Driver: amd_sata DMA: N/A
Sound device 0: Speakers (Realtek High Definiti, 10.0, MID 1, PID 100 
WARNING: Selected theme '_fallback' not found.  Trying Theme preference default value '_fallback'.
WARNING: Theme preference defaults to '_fallback', which cannot be used.  Trying DefaultTheme preference 'default'.
WARNING: ReadFile(Save/ThemePrefs.ini): No such file or directory
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'opengl,d3d'
Language: en
Current renderer: OpenGL
Theme: default

Partial log:
00:00.886: Loading /Save/MachineProfile/Stats.xml
00:00.887: Done.
00:00.889: UnlockManager::Load()
00:00.904: Last seen video driver: 
00:00.904: Card matches 'GeForce|Radeon|Wonder 9|Quadro'.
00:00.904: Applying defaults for AMD Radeon R7 200 Series.
00:00.905: Video renderers: 'opengl,d3d'
00:00.907: RageDisplay_Legacy::RageDisplay_Legacy()
00:00.919: WM_ACTIVATE (0, 0): has focus
00:00.936: SetScreenMode ...

-- End of report

00:00.086: StepMania5.0.12
00:00.086: Compiled 20160811 @ 00:34:46 (build 45e0787)
00:00.086: Log starting 2017-07-24 22:11:35
00:00.086:  
00:00.087: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.090: Reading 'Data/Static.ini' failed: No such file or directory
00:00.288: Loading window: win32
00:00.288: Windows 6.2 (Win8) build 9200 []
00:00.288: Memory: 2047mb total, 4095mb swap (3838mb swap avail)
00:00.289: Video driver: AMD Radeon R7 200 Series [Advanced Micro Devices, Inc.]
00:00.289:               22.19.162.4, 4-24-2017 [pci\ven_1002&dev_6613]
00:00.290: Drive: "        ST1000DM003-1ER1CC45" Driver: amd_sata DMA: N/A
00:00.338: Sound device 0: Speakers (Realtek High Definiti, 10.0, MID 1, PID 100 
00:00.339: Reading 'Data/Static.ini' failed: No such file or directory
/////////////////////////////////////////
00:00.339: WARNING: Selected theme '_fallback' not found.  Trying Theme preference default value '_fallback'.
/////////////////////////////////////////
/////////////////////////////////////////
00:00.339: WARNING: Theme preference defaults to '_fallback', which cannot be used.  Trying DefaultTheme preference 'default'.
/////////////////////////////////////////
00:00.339: ThemeManager::SwitchThemeAndLanguage: "default", "en"
00:00.367: Loading "/Scripts/32log.lua" ...
00:00.368: Loading "/Scripts/extend_table.lua" ...
00:00.368: Loading "/Scripts/unavailable_functions.lua" ...
00:00.369: Loading "/Scripts/32log.lua" ...
00:00.369: Loading "/Scripts/extend_table.lua" ...
00:00.369: Loading "/Scripts/unavailable_functions.lua" ...
00:00.371: Loading "/Themes/_fallback/Scripts/00 init.lua" ...
00:00.371: Loading "/Themes/_fallback/Scripts/01 alias.lua" ...
00:00.372: Loading "/Themes/_fallback/Scripts/01 base.lua" ...
00:00.373: Loading "/Themes/_fallback/Scripts/01 IniFile.lua" ...
00:00.373: Loading "/Themes/_fallback/Scripts/02 Actor.lua" ...
00:00.375: Loading "/Themes/_fallback/Scripts/02 ActorDef.lua" ...
00:00.377: Loading "/Themes/_fallback/Scripts/02 Branches.lua" ...
00:00.378: Loading "/Themes/_fallback/Scripts/02 Colors.lua" ...
00:00.379: Loading "/Themes/_fallback/Scripts/02 Debug.lua" ...
00:00.380: Loading "/Themes/_fallback/Scripts/02 Enum.lua" ...
00:00.381: Loading "/Themes/_fallback/Scripts/02 OptionsMenu.lua" ...
00:00.381: Loading "/Themes/_fallback/Scripts/02 Other.lua" ...
00:00.382: Loading "/Themes/_fallback/Scripts/02 Serialize.lua" ...
00:00.383: Loading "/Themes/_fallback/Scripts/02 Sprite.lua" ...
00:00.383: Loading "/Themes/_fallback/Scripts/02 StageMods.lua" ...
00:00.383: Loading "/Themes/_fallback/Scripts/02 ThemePrefs.lua" ...
00:00.384: Loading "/Themes/_fallback/Scripts/02 ThemePrefsRows.lua" ...
00:00.385: Loading "/Themes/_fallback/Scripts/02 Utilities.lua" ...
00:00.386: Loading "/Themes/_fallback/Scripts/03 CustomSpeedMods.lua" ...
00:00.387: Loading "/Themes/_fallback/Scripts/03 Gameplay.lua" ...
00:00.388: Loading "/Themes/_fallback/Scripts/03 GamePreferences.lua" ...
00:00.390: Loading "/Themes/_fallback/Scripts/03 ThemeAndGamePrefs.lua" ...
00:00.391: Loading "/Themes/_fallback/Scripts/03 ThemeLibrary.lua" ...
00:00.391: Loading "/Themes/_fallback/Scripts/03 UserPreferences2.lua" ...
00:00.391: Reading 'Themes/_fallback/ThemeInfo.ini' failed: No such file or directory
00:00.392: Loading "/Themes/_fallback/Scripts/04 CreditsHelpers.lua" ...
00:00.396: Loading "/Themes/_fallback/Scripts/04 LogDisplay.lua" ...
00:00.396: Loading "/Themes/_fallback/Scripts/04 NumPadEntry.lua" ...
00:00.398: Loading "/Themes/_fallback/Scripts/04 pause_menu_helper.lua" ...
00:00.398: Loading "/Themes/_fallback/Scripts/04 SetBGFitHelpers.lua" ...
00:00.399: Loading "/Themes/_fallback/Scripts/find_missing_lang_strings.lua" ...
00:00.400: Loading "/Themes/default/Scripts/00 ThemeInfo.lua" ...
00:00.400: Loading "/Themes/default/Scripts/02 Colors.lua" ...
00:00.401: Loading "/Themes/default/Scripts/02 Lyrics.lua" ...
00:00.401: Loading "/Themes/default/Scripts/02 TextBanner.lua" ...
00:00.401: Loading "/Themes/default/Scripts/02 ThemePrefs.lua" ...
00:00.402: ThemePrefs.InitAll( prefs )
00:00.402: ThemePrefs.Init: loading from disk
00:00.402: IniFile.ReadFile( Save/ThemePrefs.ini )
/////////////////////////////////////////
00:00.403: WARNING: ReadFile(Save/ThemePrefs.ini): No such file or directory
/////////////////////////////////////////
00:00.403: NotePosition doesn't exist, creating
00:00.403: GameplayFooter doesn't exist, creating
00:00.403: TimingDisplay doesn't exist, creating
00:00.403: GameplayShowScore doesn't exist, creating
00:00.403: ShowLotsaOptions doesn't exist, creating
00:00.403: FlashyCombo doesn't exist, creating
00:00.403: AutoSetStyle doesn't exist, creating
00:00.403: ComboOnRolls doesn't exist, creating
00:00.403: LongFail doesn't exist, creating
00:00.403: GameplayShowStepsDisplay doesn't exist, creating
00:00.403: FancyUIBG doesn't exist, creating
00:00.403: ComboUnderField doesn't exist, creating
00:00.403: Loading "/Themes/default/Scripts/03 Gameplay.lua" ...
00:00.403: Loading "/Themes/default/Scripts/04 Other.lua" ...
00:00.513: WaveOut software mixing at 44100 hz
00:00.513: Starting thread: Decode thread
00:00.513: Starting thread: Mixer thread
00:00.513: Sound driver: WaveOut
00:00.513: Starting thread: Music thread
00:00.516: Initializing lights drivers: SystemMessage,Export
00:00.516: Lights driver: SystemMessage
00:00.516: Lights driver: Export
00:00.516: ThemeManager::SwitchThemeAndLanguage: "default", "en"
00:00.516: Reading 'Save/Keymaps.ini' failed: No such file or directory
00:00.516: Couldn't open mapping file "Save/Keymaps.ini": No such file or directory.
00:00.516: Reading 'Save/Keymaps.ini' failed: No such file or directory
00:00.516: Couldn't open mapping file "Save/Keymaps.ini": No such file or directory.
00:00.519: Attempting to load 3 songs from "Songs/StepMania 5"
00:00.526: Loaded 3 songs from "Songs/StepMania 5"
00:00.532: Found 3 songs in 0.014000 seconds.
00:00.532: Loading courses.
00:00.534: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/ChallengingRandom5.crs") ("Cache/Courses/Courses_Default_ChallengingRandom5.crs")
00:00.538: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/Jupiter.crs") ("Cache/Courses/Courses_Default_Jupiter.crs")
00:00.540: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_01-04.crs") ("Cache/Courses/Courses_Default_MostPlayed_01-04.crs")
00:00.541: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_05-08.crs")
00:00.541: Course file "/Courses/Default/MostPlayed_05-08.crs" is trying to load BEST4 with only 3 songs installed. This entry will be ignored.
00:00.541: Course file "/Courses/Default/MostPlayed_05-08.crs" is trying to load BEST5 with only 3 songs installed. This entry will be ignored.
00:00.541: Course file "/Courses/Default/MostPlayed_05-08.crs" is trying to load BEST6 with only 3 songs installed. This entry will be ignored.
00:00.541: Course file "/Courses/Default/MostPlayed_05-08.crs" is trying to load BEST7 with only 3 songs installed. This entry will be ignored.
00:00.542: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_09-12.crs")
00:00.542: Course file "/Courses/Default/MostPlayed_09-12.crs" is trying to load BEST8 with only 3 songs installed. This entry will be ignored.
00:00.542: Course file "/Courses/Default/MostPlayed_09-12.crs" is trying to load BEST9 with only

**Comment by SpoOkyMagician** [comment]
Did you install SM in Program Files? If so, try somewhere else. Like your desktop or somewhere your local user has access too. That is my guess.

**Comment by concubidated** [comment]
@NickolasNeptune any update?

**Comment by concubidated** [comment]
Closing as no update was posted.
