### ISSUE TITLE
Win32Minimaid Bugs: Certain button lights don't function

### ISSUE THREAD

**Issue by sillybear** [stepmania/stepmania#1510]
I noticed that MenuKey Left and MenuKey Right lights aren't functioning and I realized that these buttons aren't mapped yet (see https://github.com/stepmania/stepmania/blob/master/src/arch/Lights/LightsDriver_Win32Minimaid.cpp):
GAME_BUTTON_LEFT
GAME_BUTTON_RIGHT
GAME_BUTTON_UP
GAME_BUTTON_DOWN

Also, although GAME_BUTTON_START buttons are already mapped, they neither light too, both in Title Screen and when being pressed.

**Comment by chrispable** [comment]
Ddr panels don't have separate lights for left and right on the cabinet, the whole panel lights when the start button lights. You could OR those lights in to light the panel if you want.

Those lights only illuminate when the game instructs them to light. Check the functionality in the test menu if you must test but there's no bug here.
