### ISSUE TITLE
Stepmania no longer starts

### ISSUE THREAD

**Issue by lukeoftheaura** [stepmania/stepmania#1516]
Stepmania is no longer starting on my PC. There is a paste of the crashinfo file here: http://sprunge.us/dJdD

OS: antergos (arch) linux 64-bit

**Comment by drewbarbs** [comment]
I believe I had a similar problem on my arch box last week, I believe due to an nvidia update. Can you try rebuilding SM?

**Comment by concubidated** [comment]
@lukeoftheaura any update?

**Comment by lukeoftheaura** [comment]
rebuilding fixed the issue.
