### ISSUE TITLE
Stepmania no longer starts

### ISSUE THREAD

**Issue by litangel** [stepmania/stepmania#1519]
I got a new monitor, and since then Stepmania no longer starts. this is the basic message I get - 

Video Driver: Intel(R) G33/G31 Express Chipset Family (Microsoft Corporation - WDDM 1.0)Initializing d3d...SetVideoMode failed: CreateDevice failed: 'D3DERR_INVALIDCALL';CreateDevice failed: 'D3DERR_INVALIDCALL';CreateDevice failed: 'D3DERR_INVALIDCALL';CreateDevice failed: 'D3DERR_INVALIDCALL'Initializing opengl...SetVideoMode failed: The WGL_EXT_swap_control extension is not supported on your computer.;The WGL_EXT_swap_control extension is not supported on your computer.;The WGL_EXT_swap_control extension is not supported on your computer.;The WGL_EXT_swap_control extension is not supported on your computer.

and attached is the error log

[DDR eror.txt](https://github.com/stepmania/stepmania/files/1203926/DDR.eror.txt)

**Comment by Flameshadowxeroshin** [comment]
Something appears to be wrong with your video drivers, based on what's going on here.

**Comment by shakesoda** [comment]
update your video drivers. WDDM drivers are not supported.
