### ISSUE TITLE
 Stepmania Fatal Error (Graphics Driver)

### ISSUE THREAD

**Issue by NuclearThrone** [stepmania/stepmania#1522]
No se pudo iniciar la tarjeta grÃ¡fica.

Â¡Este error no es un bug! Utiliza la siguiente direcciÃ³n para solucionar el problema.

http://old.stepmania.com/stepmaniawiki.php?title=Video_Driver_Troubleshooting

Controlador de grÃ¡ficos: Intel(R) Graphics Media Accelerator 3150 (Microsoft Corporation - WDDM 1.0)

Iniciando d3d...
SetVideoMode fallido: CreateDevice failed: 'D3DERR_INVALIDCALL';CreateDevice failed: 'D3DERR_INVALIDCALL';CreateDevice failed: 'D3DERR_INVALIDCALL';CreateDevice failed: 'D3DERR_INVALIDCALL'

Iniciando opengl...
SetVideoMode fallido: The WGL_EXT_swap_control extension is not supported on your computer.;The WGL_EXT_swap_control extension is not supported on your computer.;The WGL_EXT_swap_control extension is not supported on your computer.;The WGL_EXT_swap_control extension is not supported on your computer.

 I can't get the game to start, my graphics driver is updated to latest version and i have the latest DirectX version.

**Comment by concubidated** [comment]
Looks like you need to update your video card drivers.
