### ISSUE TITLE
StepMania - Etterna5.0-UNKNOWN crash report (build UNKNOWN, 20170127 @ 18:52:15)

### ISSUE THREAD

**Issue by CXgamer** [stepmania/stepmania#1525]
Crashing upon startup on Windows 7. This was my installation/fix procedure:

- Previously installed spawncampingwallhacks theme.
- Moved %appdata%/Stepmania 5 to a backup folder to keep my scores.
- Ran the Stepmania 5.0.12 installer, letting it uninstall the old one.
- Ran the Etterna 0.54.1 installer, installing it into a different folder than Stepmania 5.
- Moved songs from Stepmania to Etterna.
- Run the program as admin.
- About 15% into loading the songs, this crash occurs.
- Attempted fix #1104, changing preferences, but the crash report keeps saying it used WaveOut.

Information about my setup:
- Dual monitor. AMD card for main monitor and a TV which is turned off, NVIDIA card for other monitor.
- Stepmania and Etterna folders are located in D:/Games/
- Appdata still remains in its default location in C:/
- My libraries folders are located in a non-standard location in D:/Libraries/

Is maybe Etterna using a different preferences file?

Thank you in advance,

CX

---
Crash reason: Access Violation

Thread: Main thread
        SongUtil.cpp:274 MaxX Xstacy had charts sorted.
        SongUtil.cpp:271 MaxX Xstacy had duplicate steps removed.
        SongUtil.cpp:274 MaxX Xstacy had charts sorted.
        SongUtil.cpp:271 MaxX Xstacy had duplicate steps removed.
        SongUtil.cpp:274 MaxX Xstacy had charts sorted.
Thread: Decode thread
Thread: Mixer thread
Thread: Music thread
00d88c00: StepMania!008b0000
00b3606e: StepMania!008b0000
00af8d37: StepMania!008b0000
00b03817: StepMania!008b0000
00b039ba: StepMania!008b0000
00b03ecc: StepMania!008b0000
00ba46f9: StepMania!008b0000
00b05728: StepMania!008b0000
77cde0a3: ntdll!RtlFreeHeap [77cb0000+2e025+7e]
759f14ad: kernel32!HeapFree [759e0000+11499+14]
00b7b3ca: StepMania!008b0000
00b16299: StepMania!008b0000
77cde0a3: ntdll!RtlFreeHeap [77cb0000+2e025+7e]
759f14ad: kernel32!HeapFree [759e0000+11499+14]
00da4e9c: StepMania!008b0000
00b19426: StepMania!008b0000
00b19442: StepMania!008b0000
00b0f850: StepMania!008b0000
00b157ba: StepMania!008b0000
00b13e7d: StepMania!008b0000
77cde40c: ntdll!RtlInitUnicodeString [77cb0000+2e2a8+164]
77cde172: ntdll!RtlAllocateHeap [77cb0000+2e0c6+ac]
00bdfb63: StepMania!008b0000
00da4f0e: StepMania!008b0000
00d70331: StepMania!008b0000
0093d6d3: StepMania!008b0000
00a9126a: StepMania!008b0000
009be2c3: StepMania!008b0000
77cde0a3: ntdll!RtlFreeHeap [77cb0000+2e025+7e]
009bc35a: StepMania!008b0000
009bc691: StepMania!008b0000
009bae7d: StepMania!008b0000
00944901: StepMania!008b0000
00da5d7e: StepMania!008b0000
00da5d6e: StepMania!008b0000
00da5d6e: StepMania!008b0000
00cb44ca: StepMania!008b0000
00cb4176: StepMania!008b0000
00d71750: StepMania!008b0000
77ce98d5: ntdll!RtlInitializeExceptionChain [77cb0000+3989f+36]

Static log:
StepMania - Etterna5.0-UNKNOWN
Compiled 20170127 @ 18:52:15 (build UNKNOWN)
Log starting 2017-08-16 11:47:26
Loading window: win32
Windows 6.1 (Win7) build 7601 [Service Pack 1]
Memory: 4095mb total, 4095mb swap (4095mb swap avail)
Video driver: AMD Radeon R9 200 Series [Advanced Micro Devices, Inc.]
              21.19.519.2, 2-10-2017 [pci\ven_1002&dev_6810&rev_00]
WARNING: RegOpenKeyEx(80000002,HARDWARE\DEVICEMAP\Scsi) error (The system cannot find the file specified.)
Sound device 0: PC (High Definition Audio Devic, 0.0, MID 1, PID 65535 
Sound device 1: Digital Audio (S/PDIF) (High De, 0.0, MID 1, PID 65535 
Sound device 2: TV (AMD High Definition Audio D, 6.1, MID 1, PID 100 
WARNING: Selected theme '_fallback' not found.  Trying Theme preference default value '_fallback'.
WARNING: Theme preference defaults to '_fallback', which cannot be used.  Trying DefaultTheme preference 'Til Death'.
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Lights driver: SystemMessage
Lights driver: Export
WARNING: Couldn't load the Edit chart's NoteData from "/Songs/Apersons/apOMEGA/omega.dwi"
WARNING: Couldn't load the Edit chart's NoteData from "/Songs/Apersons/apOMEGA/omega.dwi"
Not caching empty difficulty in file Cache/Songs/Songs_Apersons_apOMEGA
WARNING: Couldn't load the Edit chart's NoteData from "/Songs/Arch0wl Originals/Biolab (Split Mushroom)/biolab.DWI"
WARNING: Couldn't load the Edit chart's NoteData from "/Songs/Arch0wl Originals/Biolab (Split Mushroom)/biolab.DWI"
Not caching empty difficulty in file Cache/Songs/Songs_Arch0wl Originals_Biolab (Split Mushroom)
WARNING: Unmatched 3 in "3322"
WARNING: Unmatched 3 in "2033"
WARNING: Unmatched 3 in "2033"
WARNING: Unmatched 3 in "0030"
WARNING: Unmatched 3 in "3003"
WARNING: Unmatched 3 in "0300"
WARNING: Unmatched 3 in "0003"
WARNING: Unmatched 3 in "0030"
WARNING: Unmatched 3 in "3000"
WARNING: Unmatched 3 in "0003"
Language: en
Theme: Til Death

Partial log:
00:28.313: Song::SaveToSSCFile('Cache/Songs/Songs_Beyond Legends_jack')
00:28.320: Song::LoadFromDWIFile(/Songs/Beyond Legends/Max314/max317.dwi)
00:28.322: Song '/Songs/Beyond Legends/Max314/' points to a music file that doesn't exist, found music file 'max317.mp3'
00:28.349: Song::SaveToSSCFile('Cache/Songs/Songs_Beyond Legends_Max314')
00:28.356: Song::LoadFromDWIFile(/Songs/Beyond Legends/MaxX Enigma/maxxenigma.dwi)
00:28.357: Song '/Songs/Beyond Legends/MaxX Enigma/' points to a music file that doesn't exist, found music file 'maxxenigma.mp3'
00:28.388: Song::SaveToSSCFile('Cache/Songs/Songs_Beyond Legends_MaxX Enigma')
00:28.395: Song::LoadFromDWIFile(/Songs/Beyond Legends/MaxX Extacy/MaxX Xstacy.dwi)
00:28.396: Song '/Songs/Beyond Legends/MaxX Extacy/' points to a music file that doesn't exist, found music file 'MaxX Xstacy.mp3'
00:28.430: Song::SaveToSSCFile('Cache/Songs/Songs_Beyond Legends_MaxX Extacy')

-- End of report

**Comment by shakesoda** [comment]
read the end of the crash log, you have a bad simfile. also, please don't file crash bugs from etterna here unless you can repro on a build from this repo.

**Comment by CXgamer** [comment]
Thanks and sorry man.
