### ISSUE TITLE
Crash on Startup (Fullscreen only)

### ISSUE THREAD

**Issue by maidboy** [stepmania/stepmania#1531]
Hello, I've been playing Stepmania for a couple of years now and never experienced this. I was changing some options and suddenly my Stepmania started crashing on startup.The only thing that could fix it is making it windowed by editing the Preferences file. I tried reinstalling or not using the theme and it crashes anyway. Updated all my drivers and nothing helped. Please help. Thank you.
[crashinfo.txt](https://github.com/stepmania/stepmania/files/1275117/crashinfo.txt)

**Comment by SpoOkyMagician** [comment]
Related to #1467. Have you tried running SM as admin?

**Comment by maidboy** [comment]
Just tried it. Didn't help.

**Comment by SpoOkyMagician** [comment]
What about swapping d3d/opengl in preferences.ini?

**Comment by maidboy** [comment]
How do I do that?

**Comment by maidboy** [comment]
Oh, I figured it out. I removed d3d from the preferences file and it worked. Thanks a lot!
