### ISSUE TITLE
Stepmania 5.0 beta 3 Crash

### ISSUE THREAD

**Issue by Konsento2017** [stepmania/stepmania#1545]
Not sure what to do with this, but i'll post it here :-)

StepMania v5.0 beta 3 crash report (build 11, 20140224 @ 15:37:56 Central Standard Time)
--------------------------------------

Crash reason: The music file was not found! Was it deleted or moved while the game was on?

Thread: Main thread
        MovieTexture_FFMpeg.cpp:272 
        MovieTexture_Generic.cpp:485 
        MovieTexture_Generic.cpp:492 
        MovieTexture_Generic.cpp:68 
        RageSoundReader_Extend.cpp:18 The music file was not found! Was it deleted or moved while the game was on?
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
Thread: Mixer thread
Thread: Music thread
        RageFileDriverDirectHelpers.cpp:227 D:/Games/StepMania 5/Themes/_fallback/Sounds/*
        RageFileDriverDirectHelpers.cpp:227 D:/Games/StepMania 5/Themes/_fallback/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Aaron/AppData/Roaming/StepMania 5/Themes/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Aaron/AppData/Roaming/StepMania 5/Themes/_fallback/Sounds/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Aaron/AppData/Roaming/StepMania 5/Themes/_fallback/*
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
        InputHandler_DirectInput.cpp:750 
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 

cd335e5f: ???!7fff0000

Static log:
StepMania v5.0 beta 3
Compiled 20140224 @ 15:37:56 Central Standard Time (build 11)
Log starting 2017-09-30 19:51:50
Loading window: win32
Windows 6.2 (unknown NT-based) build 9200 []
Memory: 2047mb total, 4095mb swap (4095mb swap avail)
Video driver: Intel(R) HD Graphics 530 [Intel Corporation]
              21.20.16.4542, 10-24-2016 [pci\ven_8086&dev_191b&subsys_816e103c]
Drive: "ST2000LM003             2BE1" Driver: iaStorA DMA: N/A
Drive: "hp      DVDRW  DU8A6SH  DH61" Driver: iaStorA DMA: N/A
Sound device 0: SAMSUNG (Intel(R) Display Audio, 10.0, MID 1, PID 100 
Sound device 1: Speakers (Realtek High Definiti, 10.0, MID 1, PID 100 
DirectSound Driver: Primary Sound Driver
DirectSound Driver: SAMSUNG (Intel(R) Display Audio) {0.0.0.00000000}.{1df585c8-1cdf-43a4-b9d2-c24c218c2e00}
DirectSound Driver: Speakers (Realtek High Definition Audio) {0.0.0.00000000}.{8c8e4bf0-6d10-4658-b097-9149ec1ce831}
DirectSound sample rates: 100..200000 (continuous)
Software mixing at 44100 hz
Sound driver: DirectSound-sw
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'd3d,opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 0, 1280, 720, 32, 59, 1 )
D3D Fullscreen 1280x720 32 color 16 texture 59Hz Vsync NoSmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 2 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Mouse' axes: 3, hats: 0, buttons: 8 (buffered)
WARNING: No options in row "list,Style" were selected, and no fallback row found; selected entry 0
WARNING: No options in row "list,Style" were selected, and no fallback row found; selected entry 0
WARNING: No options in row "list,Difficulty" were selected, and no fallback row found; selected entry 0
WARNING: No options in row "list,Difficulty" were selected, and no fallback row found; selected entry 0
WARNING: Background missing: Have You Never Been Mellow.avi
WARNING: Background missing: Boys.avi
WARNING: Background missing: Boys.avi
WARNING: Background missing: Little Bitch.avi
WARNING: Background missing: Boom Boom Dollar (Red Monster Mix).avi
WARNING: Background missing: MAKE IT BETTER (So-REAL Mix).avi
WARNING: Background missing: PUT YOUR FAITH IN ME (Jazzy Groove).avi
WARNING: Background missing: My Fire (UKS Remix).avi
WARNING: Background missing: LET'S GET DOWN.avi
WARNING: Background missing: MAKE IT BETTER (So-REAL Mix).avi
WARNING: Background missing: IF YOU WERE HERE.avi
WARNING: Background missing: DUB-I-DUB.avi
WARNING: Background missing: Have You Never Been Mellow.avi
WARNING: GetFileContents(/BackgroundEffects/StretchNormal.lua): Too many open files
WARNING: GetFileContents(/BackgroundEffects/StretchNormal.lua): Too many open files
WARNING: GetFileContents(/BackgroundEffects/StretchNormal.lua): Too many open files
WARNING: GetFileContents(/BackgroundEffects/StretchNormal.lua): Too many open files
WARNING: GetFileContents(/BackgroundEffects/StretchNormal.lua): Too many open files
WARNING: Couldn't load the Medium chart's NoteData from "/Songs/Dance Dance Revolution 6th Mix -DDRMAX-/Firefly/Firefly.sm"
Mixing underruns: 1
Players joined: P1
Language: en
MovieTexture_Generic::Update looping
Current renderer: Direct3D
Theme: default

Partial log:
31:12.056: Expect 0.000000, got 0.033333 -> 0.033333
31:12.056: Resolution: 304x208 (304x208, 512x256)
31:12.057: Created movie texture "/RandomMovies/blizzard3.avi" with driver "FFMpeg"
31:12.057: WARNING: GetFileContents(/BackgroundEffects/StretchNormal.lua): Too many open files
31:12.057: WARNING: GetFileContents(/BackgroundEffects/StretchNormal.lua): Too many open files
31:12.057: WARNING: GetFileContents(/BackgroundEffects/StretchNormal.lua): Too many open files
31:12.057: WARNING: GetFileContents(/BackgroundEffects/StretchNormal.lua): Too many open files
31:12.057: WARNING: GetFileContents(/BackgroundEffects/StretchNormal.lua): Too many open files
31:12.057: Song file "/Songs/Dance Dance Revolution 6th Mix -DDRMAX-/Firefly/Firefly.sm" couldn't be opened: Too many open files
31:12.057: WARNING: Couldn't load the Medium chart's NoteData from "/Songs/Dance Dance Revolution 6th Mix -DDRMAX-/Firefly/Firefly.sm"

-- End of report

**Comment by dguzek** [comment]
SM5.0 beta 3 is ancient.  Please consider upgrading to SM5.0.12: 
 https://github.com/stepmania/stepmania/releases/tag/v5.0.12.

**Comment by Konsento2017** [comment]
Omg! Really? Thank u so much for the tip!
