### ISSUE TITLE
OptionsList should have a metric for button mapping, not be hardcoded

### ISSUE THREAD

**Issue by RhythmLunatic** [stepmania/stepmania#1551]
https://github.com/stepmania/stepmania/blob/7275b70c03f28c186d18c801b52747da4d358341/src/ScreenSelectMusic.cpp#L573

Something like OptionsListButton in [ScreenSelectMusic].

**Comment by RhythmLunatic** [comment]
Actually, forget it, nobody needs this anyway

**Comment by kyzentun** [comment]
it's line 573, easter egg, gotta leave it
