### ISSUE TITLE
Stepmania Portable

### ISSUE THREAD

**Issue by maidboy** [stepmania/stepmania#1554]
Hello, I would like to run Stepmania on a USB 3.0 drive. I have already managed to run it and everything, except I can't manage to save the %appdata% directory on the drive and my settings are all messed up on every new computer. Any suggestions on how to change the save directory? Thank you.

**Comment by ChicoCybergoth** [comment]
After creating this files, in which folder it stores the config files?
After this modification I have lost my configurations.

**Comment by ChicoCybergoth** [comment]
After creating this files, in which folder it stores the config files?
After this modification I have lost my configurations (as expected).
