### ISSUE TITLE
Is it possible to have streaming video (e.g. YouTube) in the background during a Stepmania session with the current code?

### ISSUE THREAD

**Issue by shyamalschandra** [stepmania/stepmania#1558]
Instead of using a canned video, I would like to enable the song to be buffered in the background from YouTube and played in sync with the steps in the step file.  Is that easily doable considering the right location where I would like to plug in this capability?  I would like to build something similar to MusixMatch for dance steps that sync with the video in YouTube.

**Comment by shakesoda** [comment]
it's not, sorry. streaming content is not planned to be supported anytime soon. links are often not permanent and stepmania is designed such that all content works offline

**Comment by kyzentun** [comment]
Background.cpp loads the bgvideo based on data from the simfile, theme metrics, and preferences.

Videos are handled as a Sprite.  RageTexture has some stuff to point to video files.  Sprite::Update has a special case for videos, and calls RageTexture::DecodeSeconds to decode the current frame to show.

**Comment by shyamalschandra** [comment]
Are there open-source web versions of Stepmania online where I might be able to easily add this?

**Comment by fent** [comment]
Would the steps buffer along with the video too?

**Comment by shyamalschandra** [comment]
That's where you need fine-grain control of the YouTube video through its API to make it work.  Otherwise, there would be problem with sync.
