### ISSUE TITLE
No Double Performance Pump stepstype?

### ISSUE THREAD

**Issue by RhythmLunatic** [stepmania/stepmania#1559]
As far as I know, these are what the stepstypes are supposed to be...
'StepsType_Pump_Single' == Single
'StepsType_Pump_Halfdouble' == Halfdouble
'StepsType_Pump_Double' == Double
'StepsType_Pump_Couple' == Co-op
'StepsType_Pump_Routine' == Single Performance

Unless Routine is something else entirely.

**Comment by kyzentun** [comment]
What would "Double Performance" even mean?  Routine is already two players using both pads.

**Comment by RhythmLunatic** [comment]
It's just double, but easy mode

If Routine is both players then what's Couple?

**Comment by kyzentun** [comment]
If it's double but easy mode, then why would it be a different stepstype?  Just use an easier difficulty in the existing stepstype.

Couple is an abomination that is edited as one double chart, but played as two single charts.

**Comment by RhythmLunatic** [comment]
There's no need for extra stepstypes for S/D Performance because StepF2 uses the #DESCRIPTION tag and that might as well be the standard.

**Comment by shakesoda** [comment]
Routine is double performance, single performance is just easy doubles/freestyle. we don't support stuff like the 3+ player routines
