### ISSUE TITLE
OBS makes 5.2 lag when open

### ISSUE THREAD

**Issue by ListenerJubatus** [stepmania/stepmania#1579]
I got major frame rate droppage when OBS was open alongside a nightly build (particularly from smnightly.katzepower.com), even if SM was not even loaded in via a game capture yet.

5.0.12 does not exhibit this behaviour, but can it be replicated?

OS: Windows 10 (1709)
Graphics card: Nvidia GTX 1060

**Comment by shakesoda** [comment]
check 5.1, too


- Colby

**Comment by SpoOkyMagician** [comment]
Really? I recorded 5.2 in OBS with little/no issues before... Also, is this really a issue per say for SM? It is a different program all together. However, I do agree it should be looked into... Since I use it myself to record/steam sometimes... I can try it tomorrow.

**Comment by ListenerJubatus** [comment]
Just did some testing. It is doing it with every version
