### ISSUE TITLE
Remove D3D renderer

### ISSUE THREAD

**Issue by shakesoda** [stepmania/stepmania#1583]
It's unmaintained, and there are no active devs who can or will fix it when things go wrong. Further, it's one more thing tying the renderer to the way it was done well over a decade ago.

I'd like to update the GL renderer to be something more sensible on modern machines.

**Comment by sillybear** [comment]
I don't know why but, of all setup I've made until the last time I bought a new laptop and install SM in a DDR cab, I prefer to use d3d than ogl.
D3D gives me more consistent frame rate w/ vsync on than ogl (even now that i have a new gaming laptop). I have a hard time syncing global offset (using stricter judgment than default) when I tried to use ogl video renderer. Gameplay shows random stutters from time to time in ogl.

**Comment by capnkenny** [comment]
Would this be resolved with just removing the D3D renderer from RAGE for now? Or would you prefer to have an upgrade to GL packaged with the removal of D3D at the same time?

Removing D3D would be trivial, however I'm unsure of what specification you would want to bring OpenGL to (possibly OpenGL 3.2 Core?).

**Comment by shakesoda** [comment]
I wouldn't want to remove D3D without GL also being upgraded to at least remove all the ancient fixed function stuff. At minimum, that means a complete GLES2 renderer, maybe another path for actually modern hardware (i.e. compute capable) using ES3.1 or GL4.3+.

If someone (not me) *really* wants D3D then it'd be nice to have a D3D11 renderer that works on lowest [feature level](https://docs.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-devices-downlevel-intro), instead of the current D3D9 renderer.

The current status of this issue, though, is that D3D actually did get some maintenance since 2017, and while I still don't like it there's at least grounds enough to leave it around until at least 5.3, where rendering is being redesigned anyway.

**Comment by Prcuvu** [comment]
I am planning an upgrade to Direct3D 11, which also gives us a good reason to force Windows 7.
