### ISSUE TITLE
InputHandler_X11: IPAC polling rate is limited to framerate

### ISSUE THREAD

**Issue by geefr** [stepmania/stepmania#1590]
This may only happen on modern Linux distros (There was some change to evdev in recent years that broke the cobalt flux drivers, and I think it's related to this).

System setup:
- Linux Mint 18.2
- Kernel built with 1000hz tick rate, and 1000hz polling on usb devices. Polling rates have been verified as working
- Pad connected via IPAC
- Stepmania 5.1 using InputHandler_X11 for IPAC input (Default settings)

Despite usb polling rate being high polling issues are experienced in gameplay, correlating to framerate of stepmania. Running with VSync enabled makes this especially obvious as the input events are quantised to the middle of the last update (frame).

This is caused by di.ts == 0 in InputHandler::ButtonPressed, or event.xkey.time == 0 in InputHandler_X11::Update. 
Every now and then an X11 event will have a timestamp, but the vast majority don't have any timestamp available to Stepmania.  

Workaround:
- Set InputDrivers=LinuxEvent,X11 in Preferences.ini
- Modify InputHandler_Linux_Event.cpp to handle the IPAC as an input. By default the IPAC is detected as a keyboard, and ignored by the handler.

While this may be fairly specific to my setup I think this will affect a lot more. A lot of pad adapters won't register any axes, so would be ignored by LinuxEvent.
Unfortunately I don't know why the X11 events are lacking timestamps, but it seems to happen on any recent Debian-based distro. 

I'm happy to provide a fix/testing if this is accepted as a problem, for now I've only got as far as a workaround/hack for my needs.

**Comment by shakesoda** [comment]
this is the expected (if bad) behavior of the x11 driver. event should be preferred for any device possible, patch welcome

**Comment by geefr** [comment]
I'm not too surprised (Other than thinking I fixed my polling issues.), I haven't seen any other software that would care much about the actual input timestamps.

I can easily get the event driver to detect the IPAC but it seems the X11 driver is also detecting it causing all the button presses to be registered twice.
When mapping the input the X11 event is triggered first, making it very hard to bind the input using the correct driver.

Would there be an easy way to make the X11 driver ignore the IPAC? It probably doesn't help that the IPAC is detected as a keyboard to the system, so there might need to be some udev rules/something to register it as a joystick.

**Comment by geefr** [comment]
I think I've worked out an approach to solving this but it's going to take some time for a non-hacky solution

I'm planning on extending the Event driver to read keyboards fully. I can't find any way to ignore a specific device in the X11 driver, and having more accurate keyboard timing would probably be a good idea for any keyboard players (There's bound to be a few using Linux?)

* Having the X11 driver and the Event driver reading the same device doesn't work well, and is just going to be confusing. The X11 driver may need to be disabled completely for this case?
* The X11 driver could probably be updated to ignore all key events, if the Event driver can handle them without any problems.
* Either update the Event driver to detect which devices are keyboards and/or provide a config value to force specific devices to use this driver
* Update the Event driver to map key codes to a DeviceButton in a similar fashion to the X11 driver mapping
  * There is a collision between KEY_* in linux/input-event-codes.h and KEY_* in DeviceButton. Not sure how to solve this (The simple but time consuming option would be to rename the DeviceButton values)

**Comment by geefr** [comment]
So...it turns out that giant stack of X11 documentation is really useful and there's a simple solution to this, like all software problems it turns out learning more about the system before making changes actually helps ;)

The XKeyEvent structure does actually include the timestamp for the event, accurate to 1ms. It's just that the input driver was ignoring this and passing zero through to ButtonPressed.

Pull request to follow after a few cleanups and a bit more playtesting. If anyone wants to play with the changes they're in my fork under the X11-input-driver-preserve-timestamps branch

**Comment by geefr** [comment]
I'm not planning any further changes, so unless anyone finds bugs this is resolved by #1702
