### ISSUE TITLE
Can't add taps in editor

### ISSUE THREAD

**Issue by Clonewayx** [stepmania/stepmania#1593]
On linux Mint 18.2 (64) with stepmania 5.0-12 in song editor I can add only "left" ~ 4 tap other number keys seems to do nothing.

**Comment by kyzentun** [comment]
Are the other number keys the keys you use in gameplay or the menus?  That might cause your problem.

**Comment by Clonewayx** [comment]
Yes, but they are mapped as default arrows for second player so I can't change it. (And "4" key is also mapped and it works)

Numbers in top row of keyboard don't work nor can be mapped. I working with numpad...

**Comment by kyzentun** [comment]
You could try reading Docs/Mapping_keys_for_edit_mode.txt and manually creating Save/EditMode_Keymaps.ini to remap the keys edit mode uses.  Stepmania is generally bad about handling non-qwerty layouts.

**Comment by Clonewayx** [comment]
I edited it like:
```
[edit]
COLUMN_0=Key_g
COLUMN_1=Key_h
COLUMN_2=Key_j
COLUMN_3=Key_z
```
Something happens because key "4" stops to add arrows
but "GHJZ" does not work.

**Comment by kyzentun** [comment]
The section in the ini file must be named "[Edit]".  It won't work all lowercase.

**Comment by Clonewayx** [comment]
Solved, thanks.

**Comment by kyzentun** [comment]
Close the issue if you consider the problem adequately solved.  That way it doesn't clutter the list.

**Comment by Clonewayx** [comment]
I think its rather workaround than fix but for me it's enough.
