### ISSUE TITLE
crashes on start up 

### ISSUE THREAD

**Issue by xURZU7x** [stepmania/stepmania#1601]
hey guys im new to openITG and im having this problem

Video Driver: Intel(R) HD Graphics 620

Initializing Direct3D...
SetVideoMode failed: CreateDevice failed: 'D3DERR_INVALIDCALL'Initializing OpenGL...
SetVideoMode failed: Couldn't set screen mode

can you guys tell me how to fix this?

**Comment by RhythmLunatic** [comment]
This is the StepMania 5 github, not the OpenITG github.

https://github.com/openitg/openitg
