### ISSUE TITLE
Plugins?

### ISSUE THREAD

**Issue by matthewwithanm** [stepmania/stepmania#1618]
Does Stepmania have any kind of plugin system? It would be cool to integrate with Google Fit!

**Comment by shakesoda** [comment]
no, not really. you can write lua, but external file access (io library) and loading external modules (require) aren't available.

being able to load binary modules would be useful, but I won't even think about that while we also can't stop simfiles from doing anything they want.

**Comment by coderjo** [comment]
Not just simfiles, but also themes.

**Comment by shakesoda** [comment]
you can't run themes off usb drives on cabs. we can't really gimp themes if we add this, either, that's the place it'd be most useful. best we can do is require that binary modules aren't in smzips (that won't work regardless) and make sure not allow simfiles access to this stuff in any way (this includes replacing env, so leaked stuff in _G can't be abused)
