### ISSUE TITLE
Graphics render problems in KDE

### ISSUE THREAD

**Issue by ilyavenner** [stepmania/stepmania#1622]
__System info:__
1. Linux Mint `18.3`;
2. KDE `5.8.8`;
3. Stepmania `5.0.12`.

---

When OpenGL is selected as the rendering backend, black artifacts appear in the game.

_This screenshot shows the list of renders backends. Path to this menu: `System Settings -> Display and Monitor -> Compositor` (if you use KDE too)._ Also you can download this [video](https://github.com/stepmania/stepmania/files/1647861/graphics-artifacts-demonstration.zip). This is a small demonstration of the bug.

![screenshot_20180119_230528](https://user-images.githubusercontent.com/13315957/35169341-4626e41e-fd6d-11e7-934f-111eb05d8351.png)

**Comment by Flameshadowxeroshin** [comment]
Does this happen in the latest version of the 5_1-new branch as well?

**Comment by kyzentun** [comment]
This reminds me of the flicker I get when OBS is running.  I use ratpoison as my window manager, so there's normally no compositing occurring.  I don't know to solve it, just mentioning another way it manifests.

**Comment by ilyavenner** [comment]
@Flameshadowxeroshin, I will try to install latest release and give you my feedback soon.

**Comment by kyzentun** [comment]
You would need to follow the compiling instructions and build the 5_1-new branch instead of the master branch.  There's a "Compiling Stepmania" page on the stepmania github wiki that should have the instructions you need for that.

I believe it occurs in the current master and 5_1-new branches because I've seen something similar when I record a video with OBS.

**Comment by Flameshadowxeroshin** [comment]
What kind of graphics hardware do you have?

**Comment by ilyavenner** [comment]
@Flameshadowxeroshin, this issue can be closed. The problem was in the X-Server.
