### ISSUE TITLE
StepMania 5.1 Beta -> Song Modifiers Reset after 15 stages?

### ISSUE THREAD

**Issue by SpoOkyMagician** [stepmania/stepmania#1626]
I dunno if this was just some random glitch or what but, while I was playing DWI Extreme, this happened after 15 songs. I am checking the logs over now. I will let you know if I find anything. I will edit post if I find anything interesting.

Edit: Found something interesting... Although, pretty minor I think...

174:37.801: Attempted to load a non-existing mod 'no clap' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod 'no metronome' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod 'clap' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod 'no metronome' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod 'no clap' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod 'metronome' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod 'clap' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod 'metronome' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod '0.25xmusic' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod '0.50xmusic' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod '0.75xmusic' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod '0.8xmusic' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod '0.9xmusic' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod '1.0xmusic' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod 'haste' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod '1.1xmusic' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod '1.2xmusic' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod '1.25xmusic' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod '1.3xmusic' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod '1.333xmusic' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod '1.4xmusic' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod '1.5xmusic' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod '1.6xmusic' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod '1.667xmusic' for the Player. Ignoring.
174:37.802: Attempted to load a non-existing mod '1.7xmusic' for the Player. Ignoring.
174:37.803: Attempted to load a non-existing mod '1.75xmusic' for the Player. Ignoring.
174:37.803: Attempted to load a non-existing mod '1.8xmusic' for the Player. Ignoring.
174:37.803: Attempted to load a non-existing mod '1.9xmusic' for the Player. Ignoring.
174:37.803: Attempted to load a non-existing mod '2.0xmusic' for the Player. Ignoring.
174:37.803: Attempted to load a non-existing mod 'no effect' for the Player. Ignoring.
174:37.803: Attempted to load a non-existing mod 'EffectSpeed' for the Player. Ignoring.
174:37.803: Attempted to load a non-existing mod 'EffectPitch' for the Player. Ignoring.
174:37.803: Attempted to load a non-existing mod 'no autosync' for the Player. Ignoring.
174:37.803: Attempted to load a non-existing mod 'autosyncsong' for the Player. Ignoring.
174:37.803: Attempted to load a non-existing mod 'autosyncmachine' for the Player. Ignoring.
174:37.803: Attempted to load a non-existing mod 'autosynctempo' for the Player. Ignoring.
174:37.803: Attempted to load a non-existing mod 'no effect' for the Player. Ignoring.
174:37.803: Attempted to load a non-existing mod 'staticbg' for the Player. Ignoring.
174:37.803: Attempted to load a non-existing mod 'randombg' for the Player. Ignoring.
174:37.803: Attempted to load a non-existing mod 'no savescore' for the Player. Ignoring.
174:37.803: Attempted to load a non-existing mod 'savescore' for the Player. Ignoring.
174:37.806: Approximate sound time: driver frame 462036267, m_pImpl->m_Queue frame 1108576..1271808 (dist 3371), closest position is 1271808
174:37.807: Zeroing this update.  Was 0.441000
174:38.515: 43 FPS, 43 av FPS, 1575 VPF, OpenGL
174:39.515: 60 FPS, 52 av FPS, 1743 VPF, OpenGL
174:40.400: Attempted to load a non-existing mod 'no clap' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod 'no metronome' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod 'no clap' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod 'no metronome' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod 'no clap' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod 'no metronome' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod 'no clap' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod 'no metronome' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod '1.0xmusic' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod '1.0xmusic' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod '1.0xmusic' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod '1.0xmusic' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod 'no haste' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod 'no haste' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod 'no haste' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod 'no haste' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod '1.0xmusic' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod '1.0xmusic' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod '1.0xmusic' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod '1.0xmusic' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod 'no effect' for the Player. Ignoring.
174:40.400: Attempted to load a non-existing mod 'no effect' for the Player. Ignoring.
174:40.401: Attempted to load a non-existing mod 'no effect' for the Player. Ignoring.
174:40.401: Attempted to load a non-existing mod 'no effect' for the Player. Ignoring.
174:40.401: Attempted to load a non-existing mod 'no autosync' for the Player. Ignoring.
174:40.401: Attempted to load a non-existing mod 'no autosync' for the Player. Ignoring.
174:40.401: Attempted to load a non-existing mod 'no autosync' for the Player. Ignoring.
174:40.401: Attempted to load a non-existing mod 'no autosync' for the Player. Ignoring.
174:40.401: Attempted to load a non-existing mod 'no effect' for the Player. Ignoring.
174:40.401: Attempted to load a non-existing mod 'no effect' for the Player. Ignoring.
174:40.401: Attempted to load a non-existing mod 'no effect' for the Player. Ignoring.
174:40.401: Attempted to load a non-existing mod 'no effect' for the Player. Ignoring.
174:40.401: Attempted to load a non-existing mod 'savescore' for the Player. Ignoring.
174:40.401: Attempted to load a non-existing mod 'savescore' for the Player. Ignoring.
174:40.401: Attempted to load a non-existing mod 'savescore' for the Player. Ignoring.
174:40.401: Attempted to load a non-existing mod 'savescore' for the Player. Ignoring.

**Comment by kyzentun** [comment]
Those log entries are an irrelevant result of stuffing player mods and song mods into the same string.  Bad system design, but not the cause of the reset that occurred.

**Comment by SpoOkyMagician** [comment]
Ah I see... Damn code... The left/right one. I forgot about that.
