### ISSUE TITLE
[Editor] Time Signature bug

### ISSUE THREAD

**Issue by sillybear** [stepmania/stepmania#1630]
If the number of beats per measure and/or base beat is not a whole number (decimals for example) in sm/ssc files, it rounded up or truncated to a whole number.

There is a particular simfile like DDR A's Chocolate Philosophy where it uses 2.5/4 for only 2 measures while the rest is 3/4. That 2.5/4 is processed as 2/4 in the editor.

**Comment by Flameshadowxeroshin** [comment]
2.5/4 is not a time signature.

**Comment by sillybear** [comment]
Look at Chocolate Philosophy.

**Comment by Flameshadowxeroshin** [comment]
I don’t think “Konami did something ridiculous and irrational” is a reason for us to support it. Just mark that measure 5/8 or something.
