### ISSUE TITLE
Adding applicable example to theming documentation in #Sounds

### ISSUE THREAD

**Issue by JavaJeremy** [stepmania/stepmania#1638]
At [this theming doc](https://github.com/stepmania/stepmania/wiki/Theming#sounds)  it says

> (e.g. ScreenSelectDifficulty music (loop)).

But in the current version I'm using (5.1) there's no such file and after deleting every "(loop)" I could find, the songs still kept on looping their preview sample in the selection screen :(
I would like to change this to an applicable use case, like the one I described but first I would need to know how...

**Comment by JavaJeremy** [comment]
Yes!

**Comment by RhythmLunatic** [comment]
Those are metrics settings, it's unrelated to theme music playback.

Put this under [ScreenSelectMusic] in metrics.ini.
```ini
SampleMusicLoops=false
```
And some other things you can change if you want:
```ini
SampleMusicFallbackFadeInSeconds=2
SampleMusicDelay=0.5
SampleMusicDelayInit=0.2
```

**Comment by dguzek** [comment]
It looks like the specific question of *How can I prevent song previews from looping indefinitely on ScreenSelectMusic?* has been answered here.  Thanks, @RhythmLunatic!

The larger issue of documenting Metrics and SM5 theming remains nebulous and intractable.

I'm going to close this issue now in the interest of cleaning up old threads.
