### ISSUE TITLE
CHANGING FROM LAMBDA to another theme and back causes lambda to put receptors in the middle of the screen

### ISSUE THREAD

**Issue by jakeggsp5** [stepmania/stepmania#1642]
when i change from lambda to another theme, close stepmania, open stepmania then change the theme back it causes the yellow background to turn black than receptors stay at halfway or in the middle of the screen. ill put a image in when i can. i am running on macosx 10.12.6 macbook air 13 inch early 2014. stepmania 5.1.0 b1.

**Comment by ListenerJubatus** [comment]
What theme was in between?

**Comment by jakeggsp5** [comment]
It happend on all themes that i go on.including legacy. Ill put an image in when i can use my computer.

**Comment by dguzek** [comment]
> It happend on all themes that i go on.including legacy. Ill put an image in when i can use my computer.

Yes, but what was the theme you initially switched to when you first noticed that this happened?

It sounds like your `Center1Player` preferences got switched to *on* somehow; maybe the theme you switched to changed it on you.  Knowing what theme you used that particular time would help @ListenerJubatus narrow down the possibilities of what happened.

**Comment by jakeggsp5** [comment]
1st it happend from symply love. Then legacy. If this is only macosx. Than ill use a theme that im not used to like symply love

**Comment by dguzek** [comment]
If you mean [Simply Love](https://github.com/dguzek/Simply-Love-SM5), then I can confirm for @ListenerJubatus that Simply Love doesn't directly manipulate that particular preference.  

If it was some other theme called *symply love*, I have no idea.

Anyway, @jakeggsp5, you should be able to get your back to the left (or right) side of the screen by turning `Center1Player` off.  In Lambda, this is under Options -> Display Options -> UI Options.

![screen shot 2018-02-21 at 1 49 22 am](https://user-images.githubusercontent.com/1253483/36466731-8efaef82-16a9-11e8-8d46-20d8318884d0.png)

Let us know if this resolves the issue for you.

**Comment by jakeggsp5** [comment]
Ill tell you if it works. If it dosent. Then i will use othere themes cause they seem to work still. Thanks.

**Comment by Flameshadowxeroshin** [comment]
@jakeggsp5 can you put a photo up still anyway?

**Comment by jakeggsp5** [comment]
shure. ill put it up when i can.

**Comment by Flameshadowxeroshin** [comment]
@jakeggsp5 any updates?

**Comment by jakeggsp5** [comment]
@Flameshadowxeroshin i have not been able to find this glitch again. but it may have been that i have edited textures in lambda. but because i haven't done it in a while \. it hasn't been bothering anymore. also what i meant by arrows are in the middle of the screen i meant in 1 or 2 player mode both of the receptors at at the middle of the screen. but not like you would set it in p1. if i can't do it. ill make a 'simulation' of it in photoshop on what it would look like if the glitch decided to work again

**Comment by Flameshadowxeroshin** [comment]
yeah, that sounds like some theme forced Center 1 Player

**Comment by jakeggsp5** [comment]
if i cant do the glitch. ill show you an photoshopped image of what i saw. but anyway. thanks for your help

**Comment by jakeggsp5** [comment]
also. it seems that "some theme forced center player 1" is not the problem. cause p1 is always on the left still.

**Comment by dguzek** [comment]
I think issue can safely be closed.
