### ISSUE TITLE
lights driver should set brightness to 0 on exit

### ISSUE THREAD

**Issue by karai17** [stepmania/stepmania#1645]
I have an ITG2 dedicab and I am using the PIUIO driver. When I exit stepmania, beit via alt+f4 or via the exit button, any lights controlled by SM are not reset so lights will stay on indefinitely until machine is turned off (or manually adjusted brightness via evdev).

**Comment by geefr** [comment]
Seems like an easy fix (a destructor in LightsDriver.cpp should do it). 
This is a minor annoyance on my setup aswell, I'm happy to take this if no one gets there first

**Comment by Flameshadowxeroshin** [comment]
#1646 got merged, so I think this should be good?
