### ISSUE TITLE
Add "TitleImage" to .ssc format and APIs

### ISSUE THREAD

**Issue by ListenerJubatus** [stepmania/stepmania#1648]
A TitleImage is intended to be used as an alternate wordmark "logo" for a song. Although it may be visibly similar to a banner, it is intended to be a transparent image (unlike banners, which are primarily meant to be non-transparent).

Potential use cases include early DDR themes, where some of the "banners" had transparent backgrounds (but one would want to use them alongside normal banners depending on the theme).

I am also doing a theme where songs' TextBanners can be substituted with a TitleImage on the music wheel, but it is currently being done in a rather hackish way, and I would prefer a more native and official path with support for the 5.1 image cache,

**Comment by Flameshadowxeroshin** [comment]
One issue I can see is that the two uses I’ve seen, your theme and the DDR banner use you suggest, really don’t overlap that well. The dimensions would probably be different and I feel if a Dance Rush style TitleImage or an early DDR banner TitleImage were used in a place where the other was expected it would just look strange.

**Comment by shakesoda** [comment]
absolutely not, this is near totally useless to anyone not duping old DDR (this is not a use case we care about enough to add new features) is totally inflexible anyway. baking text into content is not a good thing.
