### ISSUE TITLE
[SM5.1] Crash after exiting the game (either by quit game or alt+F4)

### ISSUE THREAD

**Issue by sillybear** [stepmania/stepmania#1661]
Pulled the current update as of this writing and compiled. Here is the log: http://codepad.org/mqC0TdNd

I actually used Win10 Single Language OS, not Windows 8 as stated in the log.

**Comment by sillybear** [comment]
This commit results to a crash on program exit (Windows build). ---> https://github.com/stepmania/stepmania/pull/1646

**Comment by geefr** [comment]
That's interestin..

Unfortunately I don't have any Windows machines at home to debug on, I'll see if I can set one up but it'll take a while.

@sillybear can you remove the call to LightsDriver::reset for the listed drivers are test? I changed both of these so it could be either

- Lights driver: SystemMessage
- Lights driver: Export

**Comment by coderjo** [comment]
LIGHTSMAN is destroyed after PREFMAN and SCREENMAN, so LightsDriver_SystemMessage will crash with a null_ptr deref.

The fix is either to move LIGHTSMAN's destruction to before those two objects, or to put a check for null_ptr before trying to deref.

**Comment by coderjo** [comment]
LD_SystemMessage puts together a string showing what new light state is being set, by broadcasting a SystemMessage to anybody subscribed to it. The theme's ScreenSystemLayer overlay is subscribed and displays it in the top left corner.

**Comment by dguzek** [comment]
Was this resolved by #1663 as far as we can tell?

**Comment by sillybear** [comment]
Sorry for the delay. It's indeed fixed
