### ISSUE TITLE
[Feature Request] Allow Versus on differing difficulty levels in 'Extended' mode

### ISSUE THREAD

**Issue by thurn** [stepmania/stepmania#1665]
Currently, it is possible in 'Versus - Single Song' mode for each player to play on a different difficulty level. The same does not seem to be true of 'Extended' or 'Endless' mode, which seem to force both players to be on the same difficulty level.

I'd appreciate an option to play Extended on two different difficulty levels.

**Comment by dguzek** [comment]
This can be accomplished by setting `LockCourseDifficulties=0` in your [Preferences.ini file](https://github.com/stepmania/stepmania/wiki/Manually-Changing-Preferences).
