### ISSUE TITLE
Sorting song as level regardless of difficulty

### ISSUE THREAD

**Issue by dreiki** [stepmania/stepmania#1667]
In the recent DDR Ace release the song can be sorted and categorized by level alone without associating it with the difficulty. As far as i know in the 5.1 release this isn't possible, you need to categorize it by difficulty first and then the level can be sorted. Can this feature implemented in the next releases?

**Comment by concubidated** [comment]
#180 Issue is already open for this. I tried working on it before, but the music wheel is a nightmare... Kyz managed to get this working in his theme by rewriting the entire music wheel, this is important feature. Going to close this out though, since it is a duplicate.
