### ISSUE TITLE
What keys do?

### ISSUE THREAD

**Issue by latot** [stepmania/stepmania#1676]
Hi all, well, i think all know sm have some keys to do other things, like mistery things, like cntrl + letter, will sort the songs with it, but, how restore the order?, or what other mysteries there are?

Well, i think would be great have a screen with the keys, actually there is f3, but is only function while is hold.

(f2 will reload textures)

Thx.

**Comment by SpoOkyMagician** [comment]
read the wiki: https://github.com/stepmania/stepmania/wiki/Key-Bindings-and-combinations

**Comment by latot** [comment]
Hi, thx for that, i think would be great have that in the game, like the screens f3, maybe an f5?

Thx.

**Comment by latot** [comment]
i check the list, and there is missed combinations, like cntr+letter

**Comment by dguzek** [comment]
The [relevant wiki page](https://github.com/stepmania/stepmania/wiki/Key-Bindings-and-combinations) has been updated many more times since this issue was originally filed.  I think this can be considered resolved now.

Thanks go out all those that [contributed](https://github.com/stepmania/stepmania/wiki/Key-Bindings-and-combinations/_history) to this wiki page!

**Comment by latot** [comment]
Hi, i still think this must be opened again, is great that the wiki is updated, but the info ingame is not updated.

**Comment by dguzek** [comment]
>  but the info ingame is not updated.

Can you clarify what you mean by this?

**Comment by latot** [comment]
Hi, maybe i'm just confused, becasue when we press F3 we can access to a description of keys, but seems to be different to the game-actions.

**Comment by dguzek** [comment]
Can you provide examples of items in the F3 Menu that are confusing?  Please be as specific as possible as this will help us address the items that need better documentation.

**Comment by latot** [comment]
this is probably a mix of 2 things, first, we don't have ingame a way to know what keys do, that info is here, in the dev wiki, there is no way to a normal user can know that.
Second, we have the debug mode (F3), with the keys and a description, personally is little confusing, in my case i confuse that descriptions with the ingame bindings, in some way i would expect a menu with the actual bindings if we have F3, maybe include the ingame descriptions in F4?
