### ISSUE TITLE
zmasking on P1 breaks when P1 and P2 fields exist.

### ISSUE THREAD

**Issue by MrThatKid** [stepmania/stepmania#1678]
This happens in 5.1-new, but it has been present since 5.0.12 (It's not an issue in 5.2, due to the new notefield).
Zbuffer masking is an effect seen in several gimmick files, but it doesn't work quite properly.
The example shown was adapted from a gimmick file called "Complete Domination"
Test lua: [https://hastebin.com/ucapahenus.lua](https://hastebin.com/ucapahenus.lua)
Pictures and texture used: [https://imgur.com/a/LXv4U](https://imgur.com/a/LXv4U)
This requires a 3D noteskin, and for Fast Note Rendering to be on.

I've narrowed the issue down to commit 5fca435b43bb98ff8fbd5f522646bfacf39b70b7
Commenting out that line fixes the issue, but since it seems to have been done to fix another issue, I'm not sure how to go about fixing this.

I am aware of the intention to replace zbuffer masking with stencil-based masking, but it hasn't been implemented yet, so I consider this a vaild issue for now.

**Comment by kyzentun** [comment]
Move that clear call to ScreenGameplay::DrawPrimitives, after the notefield board is drawn for both players.

**Comment by MrThatKid** [comment]
Fix was merged.
