### ISSUE TITLE
How to move notes / add mods to song?

### ISSUE THREAD

**Issue by 9thCore** [stepmania/stepmania#1682]
I am new to this game, I wouldn't have got it if it didn't have the editor tbh. Anyway, I am working on my first song _(it's 2 hours why am I doing this and yes I know no one will play it_) and I was wondering how to add "enhancements" to gameplay (moving notes things like that). Do you need to learn .lua? Because I looked into some songs and they used .lua for modding the visual changes while I sit here not understanding anything. Any help is appreciated. Thanks! :smile: 

Side note: one also used sprites and I didn't even find the .lua file and idk if this is helpful

**Comment by ListenerJubatus** [comment]
There's two ways

1. The .SM format has an ATTACKS tag that can be used to input course scripts.

2. The more advanced method does involve Lua code and direct manipulation and tweening to the notefield actors.

**Comment by RhythmLunatic** [comment]
Along with #ATTACKS, you can download some SM5 converts from @MrThatKid that has lua for modifying the playing field and other effects.

https://www.youtube.com/user/MrThatKid4

**Comment by 9thCore** [comment]
Thanks! I'll look into it tomorrow. It's late today :|

**Comment by quietly-turning** [comment]
As @ListenerJubatus noted already, there are two ways to achieve what you're asking about.

1. the ATTACKS tag found in ssc files
2. writing your own Lua files and calling them as BGCHANGES or FGCHANGES from sm or ssc files

---

### Attacks

Most SM5 themes have a rudimentary menu for adding ATTACKS via the built-in step editor.  This is generally found in the step editor's *Alter Menu*, which can be found by pressing <kbd>A</kbd> while a segment of stepchart has been actively highlighted using <kbd>Spacebar</kbd>.  In the *Alter Menu* you will (probably) find an OptionRow titled *Convert selection to Attack*.  

From there, you may see a screen that resembles your current theme's primary modifier menu (ScreenPlayerOptions) where you can apply ATTACKS like you would select modifiers.  What modifiers are accessible here (and even the presence of this menu) is theme-dependent.  

Note that many themes may allow you to add ATTACKS that will result in SM5 crashing.  For example, turn mods (left, right, mirror, etc.) as ATTACKS causes StepMania to crash, but only in Linux.  (They are ignored in Windows and macOS.)

Generally speaking, ATTACKS are underdeveloped and not-really-supported.  I don't know of any documentation on them.

### Lua

Writing your own Lua files that utilize SM5's Lua API is generally the accepted way of scripting modifiers.  It is complicated and requires you to write your own code, but also it is also immensely flexible and far more capable than ATTACKS.

For learning resources, there is this primer on **Setting Up a "Mod" Chart**: https://quietly-turning.github.io/Lua-For-SM5/Introduction/Mod-Chart-Setup that will help you set up the absolute basics and take you no further.

TaroNuke also runs a Discord server largely dedicated to exploring stepchart modding: https://discordapp.com/invite/rGDpXWR

The people there are quite friendly and eager to explore/discuss stepchart modding.

---

For now, I'm going to close this issue in the interest of cleaning up old threads.  I believe the original question has been answered satisfactorily.
