### ISSUE TITLE
Can't Open Stepmania 5.1 beta DMG on OSX El Capitan

### ISSUE THREAD

**Issue by CybrNight** [stepmania/stepmania#1686]
So I recently have been getting back into StepMania and wanted to try out the new theme that is in the latest beta, and when I try to open the DMG I get an error saying that there are no mountable volumes. However I tried opening the same DMG on another Mac I have running macOS Sierra and it opens just fine. Is this because the DMG was created on a newer version of macOS?

**Comment by dougshell** [comment]
Yes, please see this bug report

https://github.com/stepmania/stepmania/issues/1726

Update your Mac OSX version.

**Comment by dguzek** [comment]
I'm closing this now for the same reasons I closed #1732.  See the discussion there for more information.
