### ISSUE TITLE
Win10 SM5 and 5.1 crash on startup

### ISSUE THREAD

**Issue by zabuzafreak** [stepmania/stepmania#1694]
I've tried both the official build on the website, as well as a 5.1 build and neither work. The crash log initially said it couldn't find "save/ThemePrefs.ini" so I copied the "Preferences.ini" and renamed it and that part of the log went away, however the game still immediately crashes upon loading. I've tried setting the default theme to default instead of _fallback, and I've tried forcing d3d for renderer, however neither of these are being taken into account and it still says that _fallback is the default theme, and OpenGl is the current renderer. I'm attaching both my dxdiag and crash log.
[DxDiag.txt](https://github.com/stepmania/stepmania/files/1997472/DxDiag.txt)
[crashinfo.txt](https://github.com/stepmania/stepmania/files/1997474/crashinfo.txt)

EDIT: Just thought I'd clarify, this is a fresh installation. I also have already installed the redistributables (I even redownloaded them and attempted to install them but it just says that it's already installed.)

EDIT2: Ok, so with a fresh pair of eyes, I decided to see if maybe the game didn't like that I had two graphics cards (more specifically, a ryzen apu with a gpu) and temporarily removed my 2nd (well first pcie) card. And it now works flawlessly. Any way we could get support for Hybrid Gfx in the future?

**Comment by coderjo** [comment]
Hmm. Offhand, I don't know what we can do. This crash is deep in the bowels of ATI's OpenGL drivers. Are you running the latest drivers?

When an item is not found in the current theme (which defaults to "Default", but can be changed), the game searches in the fallback. It also looks in the user profile for things that have been saved, including the preferences that have been changed. You should never point the current theme at fallback.

**Comment by zabuzafreak** [comment]
I didn't. Once I changed my graphics setup, it worked flawlessly and
properly created and found all the files on first run. Drivers are up to
date. I think the program just doesn't know what to do when there are two
different gfx cards (not two of the same, but two different cards
entirely.) But thats just my guess.
