### ISSUE TITLE
error: class ‘InputHandler_Linux_Event’ does not have any field named ‘m_bHaveKeyboard’

### ISSUE THREAD

**Issue by MrThatKid** [stepmania/stepmania#1698]
Building 5_1-new breaks with the error listed above.
Undoing the most recent commit to 5_1-new, 252e1e7b1f5df43a9c6379bf3dee8c3c1deac92f fixes the error above.

**Comment by geefr** [comment]
Oops...It really did build for me, maybe I messed up with git again..

I'll fix this tonight if no one gets there first

**Comment by geefr** [comment]
Should be resolved by #1699

**Comment by DinsFire64** [comment]
It's always when I go to update my build, new things are found.

Thanks for fixing it. Hoping for a quick merge.

**Comment by MrThatKid** [comment]
The PR was merged (with some conflict resolution), and this issue should be fixed. Closing for now.
