### ISSUE TITLE
Stepmania 5.1 level testing issues.

### ISSUE THREAD

**Issue by thereallollolman** [stepmania/stepmania#1701]
I was trying to make a level with a song which I had ported over from Stepmania 3.9 and tried to make a newer version of it and when I tried to test it only hold notes worked *the normal notes would not respond*. Please fix

**Comment by geefr** [comment]
Typically if you want something changed in software then a decent bug report is the way to do it

So you would want to clearly define:
- What you did to produce the behaviour (Along with providing any sample data/files used)
- What happened (screenshots/video even)
- What you would expect to happen
- If you know anything about the system any initial hints for people to debug

Remember project such as Stepmania are run by volunteers, who often have very limited capacity and other (paid) jobs to worry about first.

**Comment by dguzek** [comment]
I'm closing this this issue now in the interest of cleaning up stale threads.  

If you feel that this is still something that needs to be addressed, @thereallollolman, please address each of @geefr's four bullet points with as much detail as possible.
