### ISSUE TITLE
Libva.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bryanwillis7** [stepmania/stepmania#1706]
Got this after upgrading from Ubuntu 16.04 to 18.04. It previously worked. I tried resinstalling the dependencies like this:

`sudo apt-get install mesa-common-dev libglu1-mesa-dev libglew1.5-dev libxtst-dev libxrandr-dev libpng12-dev libjpeg-dev zlib1g-dev libbz2-dev libogg-dev libvorbis-dev libc6-dev yasm libasound-dev libpulse-dev libjack-dev binutils-dev libgtk2.0-dev libmad0-dev libjack0 libudev-dev libva-dev`

and the issue persist.

**Comment by concubidated** [comment]
You have the dev package, but do you have the libva1 package?

`sudo apt-get install libva1`

**Comment by bryanwillis7** [comment]
Is there any special steps I need to go through to rebuild stepmania with the correct packages? or will this suffice?:

https://github.com/stepmania/stepmania/wiki/Compiling-StepMania

**Comment by concubidated** [comment]
That should work.

**Comment by bryanwillis7** [comment]
@concubidated 

it didn't work. It got to 100% and threw this:

'[100%] Linking CXX executable ../../stepmania
/usr/bin/x86_64-linux-gnu-ld: ../../extern/libmmmagic/linux-64bit/libmmmagic.a(mmmagic.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: ../../extern/libmmmagic/linux-64bit/libmmmagic.a(minimaidhid.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: ../../extern/libmmmagic/linux-64bit/libmmmagic.a(update.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
src/CMakeFiles/StepMania.dir/build.make:10879: recipe for target '../stepmania' failed
make[2]: *** [../stepmania] Error 1
CMakeFiles/Makefile2:498: recipe for target 'src/CMakeFiles/StepMania.dir/all' failed
make[1]: *** [src/CMakeFiles/StepMania.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
'

**Comment by bryanwillis7** [comment]
@concubidated 

Thanks for that. This worked. I've built stepmania and it seems to be working now. I really appreciate the help. It's just weird. I have a laptop and a desktop both with ubuntu 18.04. One is able to still run the prebuilt stepmania that you can download from the website. the other (the laptop) wouldn't work when I upgraded ubuntu and I had to build stepmania myself. Weird.

Either way thanks.

**Comment by dkrotov** [comment]
In my system, I just found libva.so.2 in /usr/lib/x86_64-linux-gnu/ (it was a symbolic link to libva.so.2.700.0 ) and made a copy named libva.so.1 . May by it would work better (for the case of future updates) if you make a link to libva.so.2 with link name libva.so.1

**Comment by BayronVazquez** [comment]
I confirm the solution of @dkrotov in my case i havet to install stepmania in kali :smile: so i have to search where is located the library at first, execute the command `ldconfig -p | grep libva` this will promt the location of where is installed your library, and then change directory with `cd` and make copy of the symbolic link with the name of **libva.so.1** `sudo cp libva.so.2 libva.so.1` and enjoy. Thank you so much @dkrotov.

**Comment by Ghostbird** [comment]
Just a quick info for those running Debian 11. I needed a quick fix and I installed `libva1` from [Stretch](https://packages.debian.org/stretch/libva1) which worked fine on my system.
