### ISSUE TITLE
game crashes when launched

### ISSUE THREAD

**Issue by vhdrmfdl** [stepmania/stepmania#1707]
NXACLONE5.0-UNKNOWN crash report (build UNKNOWN, 20161211 @ 04:45:43)
--------------------------------------

Crash reason: Access Violation

Thread: Main thread
        MovieTexture_Generic.cpp:462 About to upload the texture.
        GameSoundManager.cpp:557 6.635152, delta 0.017000
        MovieTexture_Generic.cpp:462 About to upload the texture.
        GraphicsWindow.cpp:54 00670A2E, 256, 00000053, 001f0001
        GameSoundManager.cpp:557 6.652152, delta 0.017000
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:773 
        InputHandler_DirectInput.cpp:749 
        InputHandler_DirectInput.cpp:768 
        InputHandler_DirectInput.cpp:773 
        InputHandler_DirectInput.cpp:749 
debug resource file 'C:\Users\BASS\Downloads\NXA_CLONE_ULTIMATE\Program\NXACLONE.vdi': CreateFile failed (지정된 파일을 찾을 수 없습니다.).

Static log:
NXACLONE5.0-UNKNOWN
Compiled 20161211 @ 04:45:43 (build UNKNOWN)
Log starting 2018-06-17 10:40:26
Loading window: win32
Windows 6.2 (Win8) build 9200 []
Memory: 2047mb total, 4095mb swap (4064mb swap avail)
Video driver: Radeon(TM) RX 460 Graphics [Advanced Micro Devices, Inc.]
              23.20.15002.11, 12-6-2017 [pci\ven_1002&dev_67ef&rev_cf]
Drive: "WDC     WD20EZRX-32D8PB080.0" Driver: amd_sata DMA: N/A
Drive: "TOSHIBA DT01ACA200" Driver: amd_sata DMA: N/A
Drive: "WDC     WD80EMAZ-00WJTA083.H" Driver: amd_sata DMA: N/A
Sound device 0: 헤드셋 이어폰(Corsair VOID Wire, 0.0, MID 65535, PID 65535 
Sound device 1: Realtek Digital Output(Realtek , 10.0, MID 1, PID 100 
Sound device 2: 헤드셋 이어폰(XBOX_360_DEVICE_0, 1.20, MID 65535, PID 65535 
Sound device 3: 4 - LCDTV(AMD High Definition A, 10.0, MID 1, PID 100 
DirectSound Driver: 주 사운드 드라이버
DirectSound Driver: 헤드셋 이어폰(Corsair VOID Wireless Gaming Dongle) {0.0.0.00000000}.{4657b6b6-c211-4493-a549-4a24b47985be}
DirectSound Driver: Realtek Digital Output(Realtek High Definition Audio) {0.0.0.00000000}.{24dada4c-90ff-438c-aa38-4957fae2cb54}
DirectSound Driver: 헤드셋 이어폰(XBOX_360_DEVICE_00:01) {0.0.0.00000000}.{36bc43a4-dff1-4a80-8356-8827ffc7b80c}
DirectSound Driver: 4 - LCDTV(AMD High Definition Audio Device) {0.0.0.00000000}.{fab4f853-c288-432c-ba18-1db7aa5d5d56}
DirectSound sample rates: 100..200000 (continuous)
Software mixing at 44100 hz
Sound driver: DirectSound-sw
Lights driver: SystemMessage
Lights driver: Export
WARNING: Main title or music file for '/Songs/STATION/ARCADE/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/STATION/BRAINSHOWER/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/STATION/EASY/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/STATION/SPECIAL/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/STATION/WORLDMAX/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
WARNING: Main title or music file for '/Songs/STATION/WORLDMAXGRAY/' came up blank, forced to fall back on TidyUpData to fix title and paths.  Do not use # or ; in a song title.
Video renderers: 'opengl,d3d'
Mode: ICD 32 (888) 8 alpha 16 depth 
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: ATI Technologies Inc.
OGL Renderer: Radeon(TM) RX 460 Graphics
OGL Version: 4.5.13506 Compatibility Profile Context 23.20.15002.11
OGL Max texture size: 16384
OGL Texture units: 8
GLU Version: 1.2.2.0 Microsoft Corporation
OGL Extensions:
  GL_AMDX_debug_output
  GL_AMD: blend_minmax_factor, conservative_depth, debug_output, depth_clamp_separate, draw_buffers_blend, 
    framebuffer_sample_positions, gcn_shader, gpu_shader_half_float, gpu_shader_half_float2, gpu_shader_int64, 
    interleaved_elements, multi_draw_indirect, name_gen_delete, occlusion_query_event, performance_monitor, 
    pinned_memory, query_buffer_object, sample_positions, seamless_cubemap_per_texture, shader_atomic_counter_ops, 
    shader_stencil_export, shader_stencil_value_export, shader_trace, shader_trinary_minmax, sparse_texture, 
    sparse_texture_pool, stencil_operation_extended, texture_cube_map_array, texture_texture4, 
    transform_feedback3_lines_triangles, transform_feedback4, vertex_shader_layer, vertex_shader_viewport_index
  GL_ARB: ES2_compatibility, ES3_1_compatibility, ES3_compatibility, arrays_of_arrays, base_instance, 
    bindless_texture, blend_func_extended, buffer_storage, clear_buffer_object, clear_texture, clip_control, 
    color_buffer_float, compatibility, compressed_texture_pixel_storage, compute_shader, 
    conditional_render_inverted, conservative_depth, copy_buffer, copy_image, cull_distance, debug_output, 
    depth_buffer_float, depth_clamp, depth_texture, derivative_control, direct_state_access, draw_buffers, 
    draw_buffers_blend, draw_elements_base_vertex, draw_indirect, draw_instanced, enhanced_layouts, 
    explicit_attrib_location, explicit_uniform_location, fragment_coord_conventions, fragment_layer_viewport, 
    fragment_program, fragment_program_shadow, fragment_shader, framebuffer_no_attachments, framebuffer_object, 
    framebuffer_sRGB, geometry_shader4, get_program_binary, get_texture_sub_image, gl_spirv, gpu_shader5, 
    gpu_shader_fp64, half_float_pixel, half_float_vertex, imaging, indirect_parameters, instanced_arrays, 
    internalformat_query, internalformat_query2, invalidate_subdata, map_buffer_alignment, map_buffer_range, 
    multi_bind, multi_draw_indirect, multisample, multitexture, occlusion_query, occlusion_query2, 
    parallel_shader_compile, pipeline_statistics_query, pixel_buffer_object, point_parameters, point_sprite, 
    program_interface_query, provoking_vertex, query_buffer_object, robust_buffer_access_behavior, sample_shading, 
    sampler_objects, seamless_cube_map, seamless_cubemap_per_texture, separate_shader_objects, 
    shader_atomic_counters, shader_ballot, shader_bit_encoding, shader_draw_parameters, shader_group_vote, 
    shader_image_load_store, shader_image_size, shader_objects, shader_precision, shader_stencil_export, 
    shader_storage_buffer_object, shader_subroutine, shader_texture_image_samples, shader_texture_lod, 
    shader_viewport_layer_array, shading_language_100, shading_language_420pack, shading_language_packing, shadow, 
    shadow_ambient, sparse_buffer, sparse_texture, spirv_extensions, stencil_texturing, sync, tessellation_shader, 
    texture_barrier, texture_border_clamp, texture_buffer_object, texture_buffer_object_rgb32, 
    texture_buffer_range, texture_compression, texture_compression_bptc, texture_compression_rgtc, 
    texture_cube_map, texture_cube_map_array, texture_env_add, texture_env_combine, texture_env_crossbar, 
    texture_env_dot3, texture_float, texture_gather, texture_mirror_clamp_to_edge, texture_mirrored_repeat, 
    texture_multisample, texture_non_power_of_two, texture_query_levels, texture_query_lod, texture_rectangle, 
    texture_rg, texture_rgb10_a2ui, texture_snorm, texture_stencil8, texture_storage, texture_storage_multisample, 
    texture_swizzle, texture_view, timer_query, transform_feedback2, transform_feedback3, 
    transform_feedback_instanced, transform_feedback_overflow_query, transpose_matrix, uniform_buffer_object, 
    vertex_array_bgra, vertex_array_object, vertex_attrib_64bit, vertex_attrib_binding, vertex_buffer_object, 
    vertex_program, vertex_shader, vertex_type_10f_11f_11f_rev, vertex_type_2_10_10_10_rev, viewport_array, 
    window_pos
  GL_ATI: draw_buffers, envmap_bumpmap, fragment_shader, separate_stencil, texture_compression_3dc, 
    texture_env_combine3, texture_float, texture_mirror_once
  GL_EXT: abgr, bgra, bindable_uniform, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, 
    blend_subtract, compiled_vertex_array, copy_buffer, copy_texture, depth_bounds_test, direct_state_access, 
    draw_buffers2, draw_instanced, draw_range_elements, fog_coord, framebuffer_blit, framebuffer_multisample, 
    framebuffer_object, framebuffer_sRGB, geometry_shader4, gpu_program_parameters, gpu_shader4, histogram, 
    multi_draw_arrays, packed_depth_stencil, packed_float, packed_pixels, pixel_buffer_object, point_parameters, 
    polygon_offset_clamp, provoking_vertex, rescale_normal, secondary_color, separate_specular_color, 
    shader_image_load_store, shader_integer_mix, shadow_funcs, stencil_wrap, subtexture, texgen_reflection, 
    texture3D, texture_array, texture_buffer_object, texture_compression_bptc, texture_compression_latc, 
    texture_compression_rgtc, texture_compression_s3tc, texture_cube_map, texture_edge_clamp, texture_env_add, 
    texture_env_combine, texture_env_dot3, texture_filter_anisotropic, texture_integer, texture_lod, 
    texture_lod_bias, texture_mirror_clamp, texture_object, texture_rectangle, texture_sRGB, texture_sRGB_decode, 
    texture_shared_exponent, texture_snorm, texture_storage, texture_swizzle, timer_query, transform_feedback, 
    vertex_array, vertex_array_bgra, vertex_attrib_64bit
  GL_IBM_texture_mirrored_repeat
  GL_INTEL_fragment_shader_ordering
  GL_KHR: context_flush_control, debug, no_error, parallel_shader_compile, robust_buffer_access_behavior, 
    robustness
  GL_KTX_buffer_region
  GL_NV: alpha_to_coverage_dither_control, blend_square, conditional_render, copy_depth_to_color, copy_image, 
    depth_buffer_float, explicit_multisample, float_buffer, half_float, primitive_restart, texgen_reflection, 
    texture_barrier
  GL_OES_EGL_image
  GL_SGIS: generate_mipmap, texture_edge_clamp, texture_lod
  GL_SUN_multi_draw_arrays
  GL_WIN_swap_hint
  WGL_EXT_swap_control
OpenGL Windowed 640x480 32 color 32 texture 59Hz Vsync SmoothLines
DInput: Enumerating device - Type: 0x00000813 Instance Name: "키보드" Product Name: "키보드"
DInput: Enumerating device - Type: 0x00010215 Instance Name: "Controller (XBOX 360 For Windows)" Product Name: "Controller (XBOX 360 For Windows)"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "마우스" Product Name: "마우스"
Found 3 DirectInput devices:
   0: '?ㅻ낫?? axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Controller (XBOX 360 For Windows)' axes: 5, hats: 1, buttons: 10 (buffered)
   2: '留덉슦?? axes: 3, hats: 0, buttons: 8 (buffered)
WARNING: Compiling "return function(self)
WARNING: 	self:""()
WARNING: end
WARNING: ": [string "ScreenStationSelect::ScreenModsCommand"]:2: '<name>' expected near '""'
WARNING: Compiling "return function(self)
WARNING: 	self:""()
WARNING: end
WARNING: ": [string "ScreenSelectMusicEasy::ScreenModsCommand"]:2: '<name>' expected near '""'
WARNING: Background missing: F07.MPG
WARNING: Compiling "return function(self)
WARNING: 	self:""()
WARNING: end
WARNING: ": [string "ScreenStationSelect::ScreenModsCommand"]:2: '<name>' expected near '""'
WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:151: Profile index 0 out of range.
WARNING: [C]: GetLocalProfileFromIndex( = (null))
WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:151: unknown(self = (null))
WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:161: attempt to index upvalue 'aProfile' (a nil value)
WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:161: unknown(self = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = ,(*temporary) = _USB/ch_,(*temporary) = (null),(*temporary) = %03i,(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:209: attempt to index upvalue 'aProfile' (a nil value)
WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:209: unknown(self = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:233: attempt to index upvalue 'aProfile' (a nil value)
WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:233: unknown(self = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = %09i,(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:257: attempt to index upvalue 'aProfile' (a nil value)
WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:257: unknown(self = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = %07i,(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:281: attempt to index upvalue 'aProfile' (a nil value)
WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:281: unknown(self = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = %07i,(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:510: attempt to index upvalue 'aProfile' (a nil value)
WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:510: unknown(self = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = %09i,(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:534: attempt to index upvalue 'aProfile' (a nil value)
WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:534: unknown(self = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb out.lua:17: Profile index 0 out of range.
WARNING: [C]: GetLocalProfileFromIndex( = (null))
WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb out.lua:17: unknown(self = (null))
WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb out.lua:31: attempt to index upvalue 'profile' (a nil value)
WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb out.lua:31: unknown(self = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'profile' (a nil value))
WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:323: attempt to index upvalue 'aProfile' (a nil value)
WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:323: unknown(self = (null),params = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:354: attempt to index upvalue 'aProfile' (a nil value)
WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:354: unknown(self = (null),params = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:385: attempt to index upvalue 'aProfile' (a nil value)
WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:385: unknown(self = (null),params = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:416: attempt to index upvalue 'aProfile' (a nil value)
WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:416: unknown(self = (null),params = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:448: attempt to index upvalue 'aProfile' (a nil value)
WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:448: unknown(self = (null),params = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:479: attempt to index upvalue 'aProfile' (a nil value)
WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:479: unknown(self = (null),params = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:503: attempt to index upvalue 'aProfile' (a nil value)
WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:503: unknown(self = (null),params = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
Mixing underruns: 1
Players joined: P1
Lost focus to: NXACLONE.exe
Top Screen: ScreenLoadUsb
Language: en
Current renderer: OpenGL
Theme: NXA

Partial log:
02:48.615: WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:416: unknown(self = (null),params = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
02:48.615: WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:448: attempt to index upvalue 'aProfile' (a nil value)
02:48.615: WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:448: unknown(self = (null),params = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
02:48.616: WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:479: attempt to index upvalue 'aProfile' (a nil value)
02:48.616: WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:479: unknown(self = (null),params = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
02:48.616: WARNING: Error playing command:/Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:503: attempt to index upvalue 'aProfile' (a nil value)
02:48.616: WARNING: /Themes/NXA/BGAnimations/ScreenLoadUsb underlay/default.lua:503: unknown(self = (null),params = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index upvalue 'aProfile' (a nil value))
02:54.869: File "/Themes/NXA/BGAnimations/VIDEO/USB_BG.MPG" looping
02:54.871: Opening codec mpeg2video
02:54.875: Expect 0.000000, got 0.033367 -> 0.033367

-- End of report

**Comment by shakesoda** [comment]
this is not a build we can support, I've never even heard of it.
