### ISSUE TITLE
All Only A+ or better (except if we lose there is always F)

### ISSUE THREAD

**Issue by latot** [stepmania/stepmania#1717]
Hi, i notice now all evaluations in stepmania are A+, or AA, or AA+, or something like that, B, C, D and A are missing...

Here i miss a lot, and still i'm getting A+.

![2018-07-17_093720](https://user-images.githubusercontent.com/10523095/42821088-c31e5208-89a5-11e8-9361-b170a589a180.jpg)

Cya.

**Comment by dguzek** [comment]
The default theme for the `5_1-new` branch doesn't define its own GradeTier metrics under `[PlayerStageStats]`, so it inherits what the *_fallback* theme defines [here](https://github.com/stepmania/stepmania/blob/5_1-new/Themes/_fallback/metrics.ini#L1136-L1148). 

The *_fallback* theme defines 7 GradeTiers, and `GradeDisplay Grade Grade_Tier07.png` is, in fact, an "A" grade.  Interestingly, the default theme has graphics for 17 grades, though 8 through 17 are not currently used.

**Comment by ListenerJubatus** [comment]
This was a Lambda oversight relevant to all branches.

I put the ITG ranking tiers from SL in on both 5.2 and 5.1, so it should be correct now.

**Comment by dguzek** [comment]
Oversights happen; thanks for taking care of it, @ListenerJubatus! 🙂

**Comment by ListenerJubatus** [comment]
![stepmania_2018-07-17_14-39-31](https://user-images.githubusercontent.com/6346433/42844130-a346ccee-89d7-11e8-8ce0-7a5dbd595074.png)
and some visual proof of the fix.
