### ISSUE TITLE
Support for Raspberry Pi 3?

### ISSUE THREAD

**Issue by mtoensing** [stepmania/stepmania#1719]
Hi, do you plan to implement support for the Raspberry Pi?

**Comment by shakesoda** [comment]
it should work on x with experimental gl drivers, although it is not optimized for it and probably very slow

**Comment by mtoensing** [comment]
From what I found on the internet it seems like nobody got working sound output. The pi would be the ideal platform for this kind of thing and would open it to a whole new audience. Does anybody know if there is an already installed and bootable image for an SD card for Raspberry Pi or at least a pre-compiled version or a tutorial?

**Comment by dougshell** [comment]
A side project may fulfill this desire, but it may or may not be ported to SM5. StayTuned™

**Comment by dougshell** [comment]
Can this be closed as it is not an issue but rather a request.

**Comment by alexksso** [comment]
Just bumped on this - hope it's helpful: https://github.com/SpottyMatt/raspbian-3b-stepmania-arcade
