### ISSUE TITLE
Program Crash - Crash on Start Up

### ISSUE THREAD

**Issue by wylbor** [stepmania/stepmania#1720]
Can anyone help?

Win10 - 64x
GPU: GTX 760 Windforce
CPU: AMD FX 8300

--------------------------------------
StepMania v5.0 beta 3 crash report (build 26, 20170820 @ 12:18:59 Hora estándar de Argentina)
--------------------------------------

Crash reason: Crash!

Thread: Main thread
        RageFileManager.cpp:522 Driver %s successfully made.
        RageFileDriverDirectHelpers.cpp:227 D:/Games/EMULATOR/PIU/Backgrounds/*
        RageFileDriverDirectHelpers.cpp:227 D:/Games/EMULATOR/PIU/Backgrounds/F2/*
        RageFileDriverDirectHelpers.cpp:227 D:/Games/EMULATOR/PIU/Previews/*
        StepMania.cpp:1237 Crash!

debug resource file 'D:\Games\EMULATOR\PIU\STEP_F2.vdi': CreateFile failed (The system cannot find the file specified.).

Static log:
StepMania v5.0 beta 3
Compiled 20170820 @ 12:18:59 Hora estándar de Argentina (build 26)
Log starting 2018-07-29 17:05:32
Loading window: win32

Partial log:
00:00.037: StepMania v5.0 beta 3
00:00.037: Compiled 20170820 @ 12:18:59 Hora estándar de Argentina (build 26)
00:00.037: Log starting 2018-07-29 17:05:32
00:00.037:  
00:00.037: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.037: Reading 'Save/Preferences.ini' failed: No such file or directory
00:00.037: Reading 'Save/Preferences.ini' failed: No such file or directory
00:00.037: Reading 'Data/Static.ini' failed: No such file or directory
00:00.037: Reading 'Data/Static.ini' failed: No such file or directory
00:00.284: Loading window: win32

-- End of report

**Comment by ListenerJubatus** [comment]
This is StepF2, a fork of an older version of StepMania.

Please seek support from your vendor.
