### ISSUE TITLE
ScreenSelectProfile CardBackground (doubleres) has dimensions not a multiple of 4

### ISSUE THREAD

**Issue by Frappocalypse** [stepmania/stepmania#1729]
**Prompt Text:**
```
The graphic '/Themes/default/Graphics/ScreenSelectProfile CardBackground (doubleres).png' has frame dimensions that aren't a multiple of 4.
The entire image is 550x864 and frame size is 550.0x864.0.
Image quality will be much improved if you resize the graphic to 552x864, which is a frame size of 552x864.
```

Not sure if this is an issue or not, but doesn't seem like intended UX. This is on the latest release (5.1-Beta 2 20180723).

**Comment by dougshell** [comment]
if you open the file in question and resize it to the dimensions listen in the error it will serve as a temp solution until it is patched

**Comment by ListenerJubatus** [comment]
That has already been fixed on trunk

https://github.com/stepmania/stepmania/blob/5_1-new/Themes/default/Graphics/ScreenSelectProfile%20CardBackground%20(doubleres).png

**Comment by dougshell** [comment]
Frappocalypse

Replace the file in question with the file linked above
