### ISSUE TITLE
unable to download (macbook pro mid-2012)

### ISSUE THREAD

**Issue by neonkel** [stepmania/stepmania#1732]
Unable to open 5.1 b2 dmg. Instead I receive the following error: "No mountable file systems"

**Comment by JoseVarelaP** [comment]
What OS are you running your Macbook? It seems like a similar error like this one. (#1726)

**Comment by dguzek** [comment]
This is almost definitely the same issue reported in #1726.  

As discussed there, the issue arises from older versions of macOS (10.12 and older) not being able to natively mount APFS dmg volumes (the default from 10.13 onward).  StepMania definitely was not the only software project to bump into this issue.

As of #1775, the minimum macOS version required for SM5 is 10.9, so this dmg filesystem issue still needs to be considered for future releases of SM5.  [Blog posts like this one](https://davidnelson.net/2017/09/high-sierra-dmg/) suggest that it is possible to create HFS+ volumes from macOS 10.13.

---

I'm going to close this issue in the interest of cleaning up stale threads.
