### ISSUE TITLE
Stepmania5.0.12 crashed on Mac OS X High Sierra

### ISSUE THREAD

**Issue by dgraham573** [stepmania/stepmania#1733]
Stepmania has been crashing lately for me and a similar error message comes up:

StepMania5.0.12 crash report (build 45e0787, 20160811 @ 00:05:39)
--------------------------------------

Architecture:   Mac OS X (i386)
Crash reason:   Segmentation fault - address not mapped at 0x00000024
Crashed thread: Main thread

Checkpoints:
Thread: GUI thread
Thread: Main thread
        Screen.cpp:164 ScreenMessage(SM_UpdateTextInfo)
        Screen.cpp:164 ScreenMessage(SM_UpdateTextInfo)
        Screen.cpp:164 ScreenMessage(SM_UpdateTextInfo)
        Screen.cpp:164 ScreenMessage(SM_UpdateTextInfo)
        Screen.cpp:164 ScreenMessage(SM_UpdateTextInfo)
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
Thread: Music thread
Thread: HAL I/O thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: Input thread
Thread: Streaming sound buffering

Thread: Main thread
a3997f6f: IOAccelContextAddResource (IOAccelerator)
08811fdb: 
088e413d: 
003b8837: SetupVertices(RageSpriteVertex const*, int) 
003b8577: RageDisplay_Legacy::DrawQuadsInternal(RageSpriteVertex const*, int) 
0008eef0: BitmapText::DrawChars(bool) 
00091a27: BitmapText::DrawPrimitives() 
0000c5a9: Actor::Draw() 
0001e5b5: ActorFrame::DrawPrimitives() 
0000c5a9: Actor::Draw() 
0001e5b5: ActorFrame::DrawPrimitives() 
0000c5a9: Actor::Draw() 
0001e5b5: ActorFrame::DrawPrimitives() 
0049406b: ScreenEdit::DrawPrimitives() 
0000c5a9: Actor::Draw() 
00571e9b: ScreenManager::Draw() 
00147d9f: GameLoop::RunGameLoop() 
006caf6b: sm_main 
0076958b: -[SMMain startGame:] 

Static log:
StepMania5.0.12
Compiled 20160811 @ 00:05:39 (build 45e0787)
Log starting 2018-08-14 21:42:01
Loading window: macosx
Model: MacBookAir6,2 (4/4)
Clock speed 1.40 GHz
Mac OS X 10.13.4
Memory: 8.00 GB
WARNING: Type mismatch between default (number) and value 1 (string)
Sound driver: AudioUnit
Lights driver: SystemMessage
Video renderers: 'opengl'
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: Intel Inc.
OGL Renderer: Intel HD Graphics 5000 OpenGL Engine
OGL Version: 2.1 INTEL-10.32.48
OGL Max texture size: 16384
OGL Texture units: 8
GLU Version: 1.3 MacOSX
OGL Extensions:
  GL_APPLE: aux_depth_stencil, client_storage, element_array, fence, float_pixels, flush_buffer_range, 
    flush_render, object_purgeable, packed_pixels, pixel_buffer, rgb_422, row_bytes, specular_vector, 
    texture_range, transform_hint, vertex_array_object, vertex_array_range, vertex_point_size, 
    vertex_program_evaluators, ycbcr_422
  GL_ARB: color_buffer_float, depth_buffer_float, depth_clamp, depth_texture, draw_buffers, 
    draw_elements_base_vertex, draw_instanced, fragment_program, fragment_program_shadow, fragment_shader, 
    framebuffer_object, framebuffer_sRGB, half_float_pixel, half_float_vertex, instanced_arrays, multisample, 
    multitexture, occlusion_query, pixel_buffer_object, point_parameters, point_sprite, provoking_vertex, 
    seamless_cube_map, shader_objects, shader_texture_lod, shading_language_100, shadow, sync, 
    texture_border_clamp, texture_compression, texture_compression_rgtc, texture_cube_map, texture_env_add, 
    texture_env_combine, texture_env_crossbar, texture_env_dot3, texture_float, texture_mirrored_repeat, 
    texture_non_power_of_two, texture_rectangle, texture_rg, transpose_matrix, vertex_array_bgra, vertex_blend, 
    vertex_buffer_object, vertex_program, vertex_shader, window_pos
  GL_ATI: separate_stencil, texture_env_combine3, texture_float, texture_mirror_once
  GL_EXT: abgr, bgra, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, blend_subtract, 
    clip_volume_hint, debug_label, debug_marker, draw_buffers2, draw_range_elements, fog_coord, framebuffer_blit, 
    framebuffer_multisample, framebuffer_multisample_blit_scaled, framebuffer_object, framebuffer_sRGB, 
    geometry_shader4, gpu_program_parameters, gpu_shader4, multi_draw_arrays, packed_depth_stencil, packed_float, 
    provoking_vertex, rescale_normal, secondary_color, separate_specular_color, shadow_funcs, stencil_two_side, 
    stencil_wrap, texture_array, texture_compression_dxt1, texture_compression_s3tc, texture_env_add, 
    texture_filter_anisotropic, texture_integer, texture_lod_bias, texture_rectangle, texture_sRGB, 
    texture_sRGB_decode, texture_shared_exponent, timer_query, transform_feedback, vertex_array_bgra
  GL_IBM_rasterpos_clip
  GL_NV: blend_square, conditional_render, depth_clamp, fog_distance, light_max_exponent, texgen_reflection, 
    texture_barrier
  GL_SGIS: generate_mipmap, texture_edge_clamp, texture_lod
OpenGL Windowed 854x480 32 color 16 texture 60Hz Vsync SmoothLines
Mixing underruns: 1
Players joined: P1
Top Screen: ScreenMiniMenuMainMenu
Language: en
Current renderer: OpenGL
Theme: Simply Love

Partial log:
19:19.899: 60 FPS, 58 av FPS, 4216 VPF, OpenGL
19:25.305: 4 FPS, 11 av FPS, 4313 VPF, OpenGL
19:25.305: Approximate sound time: driver frame 4428814618, m_pImpl->m_Queue frame 244161..253204 (dist 217415), closest position is 253204
19:25.343: PushScreen: "ScreenMiniMenuMainMenu"
19:25.344: ScreenOptions::InitMenu()
19:25.352: RageSound: Load "/Themes/_fallback/Sounds/_missing.ogg" (precache: 0)
19:25.363: Sound "/Themes/_fallback/Sounds/_missing.ogg" has a start time 0.000021 seconds in the past
19:30.359: 0 FPS, 11 av FPS, 5320 VPF, OpenGL
19:30.359: Approximate sound time: driver frame 4429037515, m_pImpl->m_Queue frame 76416..85120 (dist 211274), closest position is 85120
19:31.373: 59 FPS, 56 av FPS, 5320 VPF, OpenGL

-- End of report
 
Does anyone know what may be the problem here? Thanks

**Comment by quietly-turning** [comment]
It seems like this is (likely) the same crash as in #1767, so I'll close this one now in the interest of having 1 fewer open GitHub issue.
