### ISSUE TITLE
Mac OS 10.14 will drop support for 32 bit applications

### ISSUE THREAD

**Issue by pqnet** [stepmania/stepmania#1734]
As announced by Apple, the next version of the operating system (expected to be released later this year) will not support 32 bit applications anymore. This is also the meaning of the warning "This app is not optimized, please ask the developer to update it" you get on high sierra when running stepmania. Is it currently possible to build stepmania as 64 bit application? Can we get release packages for that architecture?

**Comment by dguzek** [comment]
> Is it currently possible to build stepmania as 64 bit application?

It not currently possible.

**Comment by coderjo** [comment]
I don't know about other platforms, but on windows, the largest problem seems to be libmad. Of course, I don't even make it to linking or running, so there could be a number of other problems. (I did do a couple of commits attempting to start the process of doing a 64-bit build, cleaning up errors)

**Comment by coderjo** [comment]
(oh, and ffmpeg, but that isn't as big of a problem as libmad)

**Comment by coderjo** [comment]
Strike that. I forgot that there a so many warnings that I would not trust it even if it did link.

**Comment by geefr** [comment]
It's definitely possible to build stepmania as 64-bit on Linux

Unless there's anything weird in the build system (Fairly likely?) then 64-bit on OSX shouldn't be a problem surely?

As far as CMake/build systems go OSX is very similar to Linux, as they're both descended from the unices of old. I've also had some success building on FreeBSD, which again is quite close to OSX in this area.

(If anyone needs help on this I know a thing or 2, but don't own a mac to test this on)

**Comment by ListenerJubatus** [comment]
@geefr do you ever go on IRC?

**Comment by geefr** [comment]
@ListenerJubatus I wasn't aware there was one. If you throw me a link I can drop in when I get a free second

**Comment by dguzek** [comment]
This is probably unrelated to building 64bit on macOS, but #633 and #627 could be `cherry-pick`'d into to 5_1-new if there's going to be an effort to clean up macOS builds.  They were merged into master (what is now 5.2) in 2015 and aren't present in 5_1-new.

I'll try to make time to test them this coming weekend and will submit a pull request to 5_1-new if I'm able to build and play a few games without immediate issues.

As for building a 64bit app for macOS, I don't have enough CS knowledge to be immediately helpful beyond owning a macbook and being able+willing to test things.

**Comment by ListenerJubatus** [comment]
@geefr #stepmania-devs on freenode but right now the server and channel require nickserv registration due to spam issues

**Comment by geefr** [comment]
@ListenerJubatus Thanks managed to sort it out

My only issue is I don't have the hardware (and can't afford it). If there's no OSX devs available I can certainly answer questions/etc on cmake and general unix dev

**Comment by dguzek** [comment]
Just to check in: I upgraded to macOS 10.14 yesterday and HEAD from `5_1-new` (built prior to upgrading) still opens and runs.

...not that this isn't still an issue.

**Comment by aenrichus** [comment]
It looks like this will be an issue when macOS 10.15 arrives, but 10.14 Mojave has 32-bit support.

https://support.apple.com/en-us/HT208436

**Comment by dguzek** [comment]
Here's what I've tried so far:

1. Clear out all existing files generated by cmake.

2. Edit [line 284](https://github.com/stepmania/stepmania/blob/338becc5d7c780ac2603e6f58e3a6369789b7f9c/StepmaniaCore.cmake#L284) of ./StepmaniaCore.cmake from

```cmake
set(CMAKE_OSX_ARCHITECTURES "i386")
```

to

```cmake
set(CMAKE_OSX_ARCHITECTURES "x86_64")
```

Delete [line 315](https://github.com/stepmania/stepmania/blob/338becc5d7c780ac2603e6f58e3a6369789b7f9c/StepmaniaCore.cmake#L315) of the same file as the `QuickTime` framework is apparently [not available in Xcode 10](https://github.com/openframeworks/openFrameworks/pull/6131).


3. Delete [this block](https://github.com/stepmania/stepmania/blob/338becc5d7c780ac2603e6f58e3a6369789b7f9c/CMake/SetupFfmpeg.cmake#L29-L35) from ./Cmake/SetupFfmpeg.cmake

```cmake
if(MACOSX)
  # TODO: Remove these two items when Mac OS X StepMania builds in 64-bit.
  list(APPEND FFMPEG_CONFIGURE
    "--arch=i386"
    "--cc=clang -m32"
  )
endif()
```


4. Generate a new Xcode project within the ./Build/ directory using `cmake -G Xcode .. && cmake ..`

5. Use Xcode to attempt to build.

6. Get these warnings while linking and then many subsequent related errors:

```
ld: warning: ignoring file /Users/dan/Games/SM5/Xcode/Libraries/libogg.a, missing required architecture x86_64 in file /Users/dan/Games/SM5/Xcode/Libraries/libogg.a (2 slices)
ld: warning: ignoring file /Users/dan/Games/SM5/Xcode/Libraries/libtheora.a, missing required architecture x86_64 in file /Users/dan/Games/SM5/Xcode/Libraries/libtheora.a (2 slices)
ld: warning: ignoring file /Users/dan/Games/SM5/Xcode/Libraries/libvorbis.a, missing required architecture x86_64 in file /Users/dan/Games/SM5/Xcode/Libraries/libvorbis.a (2 slices)
```

I assume that that means those three static libraries were built for `i386` and need to be updated.

7. For lack of a better thing to try, I replaced those three static libraries with up-to-date copies obtained via [Homebrew](https://brew.sh).

8. Use Xcode to try to build again.  Get these errors while linking:

```
Undefined symbols for architecture x86_64:
  "_ov_clear", referenced from:
      RageSoundReader_Vorbisfile::~RageSoundReader_Vorbisfile() in RageSoundReader_Vorbisfile.o
  "_ov_info", referenced from:
      RageSoundReader_Vorbisfile::Open(RageFileBasic*) in RageSoundReader_Vorbisfile.o
      RageSoundReader_Vorbisfile::Read(float*, int) in RageSoundReader_Vorbisfile.o
      RageSoundReader_Vorbisfile::GetSampleRate() const in RageSoundReader_Vorbisfile.o
  "_ov_open_callbacks", referenced from:
      RageSoundReader_Vorbisfile::Open(RageFileBasic*) in RageSoundReader_Vorbisfile.o
  "_ov_pcm_seek", referenced from:
      RageSoundReader_Vorbisfile::SetPosition(int) in RageSoundReader_Vorbisfile.o
  "_ov_pcm_tell", referenced from:
      RageSoundReader_Vorbisfile::Open(RageFileBasic*) in RageSoundReader_Vorbisfile.o
      RageSoundReader_Vorbisfile::SetPosition(int) in RageSoundReader_Vorbisfile.o
      RageSoundReader_Vorbisfile::Read(float*, int) in RageSoundReader_Vorbisfile.o
      RageSoundReader_Vorbisfile::GetNextSourceFrame() const in RageSoundReader_Vorbisfile.o
  "_ov_read_float", referenced from:
      RageSoundReader_Vorbisfile::Read(float*, int) in RageSoundReader_Vorbisfile.o
  "_ov_time_total", referenced from:
      RageSoundReader_Vorbisfile::GetLength() const in RageSoundReader_Vorbisfile.o
  "_vm_region", referenced from:
      GetRegionInfo(unsigned int, void const*, unsigned long&, int&) in Backtrace.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

---

I'm pretty much willing to try whatever approaches anyone else might suggest.

**Comment by coderjo** [comment]
I think you have a mismatch between your headers and lib files. Like the API changed between the headers you already had and the new lib files. Just a guess, though.

**Comment by kategray** [comment]
@dguzek There are some static libraries in Xcode/Libraries.  They are 32 bit, so the linker ignores them.

I've updated the Xcode project to build 64 bit libraries, and have recompiled them.  There are likely to be some API changes that have to incorporated into the build itself.

If you're interested in seeing the changes I made, my updated library files are here:

https://github.com/kategray/stepmania/tree/unilights/Xcode/Libraries

I have no clue why libtheora.a isn't present.  I'll be working to upgrade to 64 bit and eliminate the QuickTime requirement in that branch (unilights).

**Comment by Tatsh** [comment]
master branch is already fixed to build 64-bit and I am almost done with making this work for the 5_1-new branch.

**Comment by rogerclark** [comment]
hey @Tatsh! any progress with making this work for 5_1-new?

**Comment by Tatsh** [comment]
@rogerclark Yes it works. It's in my [cmake-refactor](https://github.com/Tatsh/stepmania/tree/cmake-refactor) branch. This will build it statically:

```
cd Build
cmake -DWITH_OGG=TRUE -DWITH_MP3=TRUE ..
```

If you look at `CMakeLists.txt` in the root, you'll see there are now `WITH_SYSTEM_*` options, in case you don't want to build everything statically.

**Comment by Tatsh** [comment]
This is all fixed in `5_1-new` since #1790 was merged.

**Comment by dguzek** [comment]
Thanks for all your work on #1790, @Tatsh.  

I pulled the latest from `5_1-new` just now, generated a new Xcode project using `cmake -G Xcode -DCMAKE_BUILD_TYPE=Release ..`, successfully built SM5.1 for macOS, and played through a single game cycle without any issues.  I think this issue can be closed now.

Is there a particular set of cmake options you recommend using for building on macOS?  In particular, do you think the Wiki should be updated to reflect your changes? https://github.com/stepmania/stepmania/wiki/Compiling-StepMania#mac-os-x

**Comment by Tatsh** [comment]
If people don't want to use GUIs (like me), then the instructions should include those steps too. By default CMake outputs Make files, and also can generate Ninja build files. All 3 ways are now supported: `xcodebuild`/Xcode GUI, `make`, and `ninja` (except when building ffmpeg statically).

**Comment by Tatsh** [comment]
Also if you use Homebrew (I use MacPorts), you should consider making a package for it, for those who like that way of managing their installed software.

**Comment by JeffreyATW** [comment]
Just FYI, macOS 10.15 is out as a developer beta right now and indeed is unable to play the 32-bit binary that is part of the latest release. Any news on a new release with a 64-bit Mac build?

**Comment by Horsey-** [comment]
looks like Dan got it working from Tatsh's fork

https://github.com/stepmania/stepmania/issues/1734#issuecomment-464375826

**Comment by JeffreyATW** [comment]
I understand. I can also build it myself. This is more of a question about the binary available on the Releases page.

**Comment by dguzek** [comment]
Hi @JeffreyATW,

There is no news on a future release with a 64-bit Mac build right now, but this is mostly inertia and/or lack of time to dedicate to it.  I'm definitely still behind on testing a number of currently open pull requests.

Is this something you can help with?  I'll be honest and admit I'm way out of my league when it involves building binaries.

---

@Horsey-, please use my GitHub handle.

**Comment by JeffreyATW** [comment]
I also have little-to-no experience building binaries. But I would be happy to provide a new build based off of `5_1-new` assuming it works on my machine. Verdict is out on whether I could provide a Windows release because I only have access to that via a virtual machine. I'll let you know what happens.

As for drafting release notes, I have never contributed to StepMania so I wouldn't be able to say what's changed since beta 2, other than just listing out merged PRs.

**Comment by JeffreyATW** [comment]
Welp, I ran the commands to create the Xcode project and tried to build with the `ALL_BUILD` and `StepMania` schemes, but it resulted in a `StepMania-debug.app` executable that macOS says is "damaged or incomplete". So, as someone who's basically never used Xcode before, I'm stuck. Thoughts?

**Comment by Tatsh** [comment]
Don't use Xcode. Use `cmake -G Xcode ...`

**Comment by dguzek** [comment]
@Tatsh – Thanks again for your help with this.

> Don't use Xcode. Use `cmake -G Xcode ...`

I'm sorry, but I'm unfamiliar with cmake's `...` syntax.  What does that do?

> If people don't want to use GUIs (like me), then the instructions should include those steps too. By default CMake outputs Make files, and also can generate Ninja build files. All 3 ways are now supported: xcodebuild/Xcode GUI, make, and ninja (except when building ffmpeg statically).

Would you be able and willing write more clear, step-by-step instructions on how to build SM5.1 for macOS using make (or ninja)?  I tried generating a makefile back in February when you submitted #1790, but I was unable to build (I forget the details already) and resorted to generating an Xcode project and using that.  Even if you can jot down rough notes, I can try to expand them with prose from there.

It's definitely not your responsibility to do this, but as it stands, I'm not sure how many other people there are right now that understand how to build SM5 for macOS.

**Comment by Tatsh** [comment]
I will write some instructions when I get home.

For now if you want, take a look at a Gentoo ebuild and a MacPorts port.

https://github.com/Tatsh/tatsh-overlay/blob/master/games-arcade/stepmania/stepmania-5.1.0_beta2_p20190216.ebuild#L61

https://github.com/Tatsh/ports/blob/master/games/stepmania/Portfile#L32

These are the CMake arguments using regular Makefiles. So after invoking `cmake -D... ... source-directory`, just run `make`. On macOS the app bundle should be present in the build directory.

You may want to mimic the installation process in the Portfile:

https://github.com/Tatsh/ports/blob/master/games/stepmania/Portfile#L77

**Comment by JeffreyATW** [comment]
FWIW, I was following [these steps](https://github.com/stepmania/stepmania/wiki/Compiling-StepMania#mac-os-x). They follow your suggestion to run `cmake -G Xcode`, but then after that they say to open the `.xcodeproj` and build from there.

**Comment by JeffreyATW** [comment]
Release of 10.15 edges ever closer. @Tatsh, when you have the time can you take a swing at the `make` instructions for Mac? Thank you!

**Comment by dguzek** [comment]
On macOS, using the `5_1-new` branch at 38b97f4738d37d72dd2b2db53bdacc8cc0f44f1a, this is what I've found so far.  

Each of these assumes cmake has already been installed via `brew install cmake`.

## Xcode

An Xcode project can generated and then opened via:

```bash
cd ./stepmania/Build
cmake -G Xcode -DWITH_FULL_RELEASE=ON -DCMAKE_BUILD_TYPE=Release ..
xed StepMania.xcodeproj/
```

The resulting Xcode project will build a debug StepMania by default, but that can be changed to a release build within Xcode. 

I will try to followup with instructions on changing this later, but I feel like I must not be using cmake correctly if I'm having to do this.

## make

```bash
cd ./stepmania/Build
cmake -DCMAKE_BUILD_TYPE=Release -DWITH_FULL_RELEASE=yes -DWITH_FFMPEG=yes ..
make -j8
```

This will not build as-is, throwing errors on NoteData.h.  I changed [lines 383-386](https://github.com/stepmania/stepmania/blob/5_1-new/src/NoteData.h#L383-L386) to 

```C++
namespace std
{
	template<> inline void swap<NoteData>( NoteData &nd1, NoteData &nd2 )
	noexcept(is_nothrow_move_constructible<NoteData>::value && is_nothrow_move_assignable<NoteData>::value)
	{
		nd1.swap( nd2 );
	}
}
```

and that allowed clang via make to successfully finish a release build.  Xcode is still able to build with this change in place.  I haven't submitted this as a pull request yet because I don't understand the change particularly well.

## Ninja

I have no prior experience with Ninja, so take this with a grain of salt.

```bash
brew install ninja ffmpeg libtommath mad libtomcrypt
cd ./stepmania/Build
cmake -G "Ninja" \
  -DCMAKE_BUILD_TYPE=Release \
  -DWITH_LTO=ON \
  -DWITH_FFMPEG=yes \
  -DWITH_SYSTEM_FFMPEG=ON \
  -DWITH_SYSTEM_GLEW=ON \
  -DWITH_SYSTEM_JPEG=ON \
  -DWITH_SYSTEM_JSONCPP=OFF \
  -DWITH_SYSTEM_MAD=ON \
  -DWITH_SYSTEM_OGG=ON \
  -DWITH_SYSTEM_PCRE=ON \
  -DWITH_SYSTEM_PNG=OFF \
  -DWITH_SYSTEM_TOMCRYPT=ON \
  -DWITH_SYSTEM_TOMMATH=ON \
  -DWITH_SYSTEM_ZLIB=ON \
  ..
ninja
```

That generates a Ninja project and attempts to build, but I was not able to successfully build.

---

It would extremely helpful to simply have "recommended" cmake invocations for people building on macOS that aren't necessarily familiar with cmake and SM5.

It would be more time consuming and helpful (but not completely necessary) to have some kind of documentation on what flags are available when building SM5 using cmake and what they mean/what kind of impact they'll have on the resulting build.

**Comment by JeffreyATW** [comment]
Ah, I made a breakthrough. The piece I was missing was not knowing how to switch from the `Debug` to the `Release` configuration within Xcode.

I started by clicking this:
![image](https://user-images.githubusercontent.com/266170/61160630-06b3e700-a4b5-11e9-8b8d-d0a531403783.png)

and changed it to StepMania:
![image](https://user-images.githubusercontent.com/266170/61160642-103d4f00-a4b5-11e9-8fd7-58c2c5158074.png)

Then I went to Product > Scheme > Edit Scheme...
![image](https://user-images.githubusercontent.com/266170/61160672-319e3b00-a4b5-11e9-8f3c-b529f22043fc.png)

And changed the "Run" build configuration from `Debug` to `Release`, and unchecking "Debug executable":
![image](https://user-images.githubusercontent.com/266170/61160698-5397bd80-a4b5-11e9-89c9-76387369371f.png)

Then I was able to go to Product > Build For > Running
![image](https://user-images.githubusercontent.com/266170/61160725-732ee600-a4b5-11e9-8854-1378002b8f44.png)

And after all that was done, Stepmania.app appeared in the root directory of the repo. Works great.

Would be glad to contribute this somewhere if it's helpful.

**Comment by JeffreyATW** [comment]
I went and added the above steps (sans screenshots) to the [wiki article](https://github.com/stepmania/stepmania/wiki/Compiling-StepMania#mac-os-x).

**Comment by Tatsh** [comment]
>and that allowed clang via make to successfully finish a release build. Xcode is still able to build with this change in place. I haven't submitted this as a pull request yet because I don't understand the change particularly well.

MSVC does not support this `noexcept()` syntax. There needs to be an `#ifdef __clang__` or whatever here or preferably:

```c++
#if defined(__has_feature) && __has_feature(cxx_noexcept)
// the noexcept code
#else 
// the current version
#endif
```

**Comment by Horsey-** [comment]
just tried building this with the above instructions and got errors for ffmpeg, I have a feeling it's because of something I didn't install or am missing
<img width="1401" alt="Screen Shot 2019-07-26 at 9 59 48 PM" src="https://user-images.githubusercontent.com/5679966/61990219-2a1c7d00-aff1-11e9-8bfe-db7adf0fb107.png">

**Comment by JeffreyATW** [comment]
Did you follow the first step in the guide I linked that says to install yasm?

**Comment by Horsey-** [comment]
sorry about the above, I installed yasm after initializing the xcode project and found online that I can run in terminal `sudo xcode-select --reset` 

I'm new to xcode, so I didn't realize I had to clear a cache of some sort instead of just deleting the folder and starting all over again

now question: how do I choose the 5.1_new branch to build? the above built 5.2

**Comment by dguzek** [comment]
To clarify for other readers, the guide for building on macOS using Xcode is currently here: https://github.com/stepmania/stepmania/wiki/Compiling-StepMania#macos

The instructions there are not great, and they should likely be updated to reflect Tatsh's changes from February 2019, but they're all the project really has right now.
