### ISSUE TITLE
Xcode Build Fails: Can't Find pthread_setname_np

### ISSUE THREAD

**Issue by ed1d1a8d** [stepmania/stepmania#1740]
When building with Xcode 8.3.3 on macOS 10.12.6, I get the following error:
```
/Users/ed1d1a8d/dev/stepmania/src/arch/Threads/Threads_Pthreads.cpp:120:8: Use of undeclared identifier 'pthread_setname_np'; did you mean 'pthread_setugid_np'?
```

If I comment out these lines: https://github.com/stepmania/stepmania/blob/27fdfb38718474253aeb33e9f9c7fd1a91ed823a/src/arch/Threads/Threads_Pthreads.cpp#L120-L123 then the build works fine.

It seems this code if for debugging purposes only, so maybe we can just not run them for macOS builds?

**Comment by Tatsh** [comment]
This is fixed in latest master.
