### ISSUE TITLE
Announcer sounds even when turned off Linux Mint

### ISSUE THREAD

**Issue by PehrMeldert** [stepmania/stepmania#1741]
I've installed SM5 on Linux mint and when I'm playing i'm getting for example "Let's step-step" at the start of songs and "400 combos!" at combo ~85, don't know if there are any more. I have announcer set to "off" and even no announcers installed, but I still have an announcer yelling at me!

I tried to install another and choose that one instead of announcer "off", but then I get both announcers!
pls help, where is my ghost announcer coming from?

**Comment by dguzek** [comment]
Can you verify that the music files for the songs your are playing do not having the announcer embedded in them?  That is to say, were they recorded using a line out from some other arcade game?

Open them up in audacity and listen to them outside of StepMania and let us know.

**Comment by PehrMeldert** [comment]
You can close this, it was an unused theme that caused the ghosting announcer.
I deleted the theme and the announcer is gone.
