### ISSUE TITLE
Lights Problem

### ISSUE THREAD

**Issue by ABCsHub** [stepmania/stepmania#1742]
Stepmania Delvolpers...

I putted the "Light" tag and it change something about the game...

Then I don't Liked

So...Someone can fix it?

The Differences are.....

He has olny 1 mode of gamemode (Cabinet)

You Can't Play rave..

Most ALL The Songs Will be deleted.....

You Can't Import Musics to DDR

And...You CAN'T switch the tag....

So at Stepmania 6 at 2019 i think DELETE THIS TAG!

Code Error:

StepMania5.0.12 crash report (build 45e0787, 20160811 @ 00:34:46)
--------------------------------------

Crash reason: Game has no Style that can be used with HowToPlay: lights

Thread: Main thread
        RageTextureManager.cpp:145 RageTextureManager::LoadTexture(/Themes/default/Graphics/OptionsUnderlineP1 Right (doubleres).png).
        BitmapText.cpp:210 BitmapText::LoadFromFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini)
        FontManager.cpp:40 FontManager::LoadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        RageTextureManager.cpp:145 RageTextureManager::LoadTexture(/Themes/default/Graphics/OptionRowExit frame.png).
        GameManager.cpp:3337 Game has no Style that can be used with HowToPlay: lights
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
Thread: Mixer thread
Thread: Music thread

So Pleeeeeeeeease fix it ;(

>ABCsHub

**Comment by ABCsHub** [comment]
With Love ABCsHub

**Comment by coderjo** [comment]
You can open up Preferenes.ini in the Save folder, find the line that says "CurrentGame=lights" and change it to "CurrentGame=dance", then save it.

Where you find the Save folder depends on your OS and whether or not you're using portable mode. With portable mode, it is in the same folder as the Stepmania program. Otherwise:
- On Windows, look in "%AppData%\StepMania 5"
- On Linux, look in ~/.stepmania-5
- On MacOS, look in ~/Library/Preferences/Stepmania 5

**Comment by ABCsHub** [comment]
Thx 😃
