### ISSUE TITLE
Stepmania 5.0.12 sync drifts the longer the program has been open

### ISSUE THREAD

**Issue by OnceUponASmore** [stepmania/stepmania#1743]
I can play a song I know is on sync, and get 99.75%. If I leave the game open for 20 minutes and play it again, I'll get 65% because the sync has drifted so far. Restarting the program will reset/fix the problem temporarily.

Tried:
- Different themes
- Reinstalling
- Running as compatibility mode (Windows 7)
- Turning off V-sync on Stepmania and graphics card control panel
- Setting Windows priority of Stepmania to "Real time"

**Comment by shakesoda** [comment]
hmm, none of those things should affect sync (only latency/offset).

have you tried changing the audio driver? if using WaveOut, try DirectSound-sw (or the reverse). the default driver was already changed for 5.1, if this works.

if there is still a sync issue after that you may need to mess with sampling rates, but I can't honestly remember a time I've had to go that far.

**Comment by OnceUponASmore** [comment]
Thank you for your reply shakesoda.

Changing the audio driver to WaveOut resolved the issue.

For anyone else reading this, the audio driver StepMania uses can be changed in Preferences.ini.
C:\Users\<your name>\AppData\Roaming\StepMania 5\Save\Preferences.ini

Within that file, change the line for "SoundDrivers" to be:
**SoundDrivers=WaveOut**

Thank you again. This is very relieving.
