### ISSUE TITLE
How to hide the Command Prompt window with self-compiled StepMania 5.1?

### ISSUE THREAD

**Issue by OnceUponASmore** [stepmania/stepmania#1746]
I downloaded the source code and spent a few days putting in my own desired modifications.
I'm now compiling the code as "Release" via Visual Studio, which creates the .exe.

However, I notice a Command Prompt / DOS window appears whenever I run my own build of SM. This doesn't happen when I run the official released version (from installer).

**Comment by OnceUponASmore** [comment]
Perfect, thank you!

For anyone else with the same issue, the file was at C:\Users\[Your username]\AppData\Roaming\StepMania 5.1\Save\Preferences.ini.

The variable "ShowLogOutput" had to be set to 0.

Thank you, TheKamilia!

**Comment by TheKamilia** [comment]
> Perfect, thank you!
> 
> For anyone else with the same issue, the file was at C:\Users[Your username]\AppData\Roaming\StepMania 5.1\Save\Preferences.ini.
> 
> The variable "ShowLogOutput" had to be set to 0.
> 
> Thank you, TheKamilia!

np

**Comment by coderjo** [comment]
You can also find it by going to %appdata%\StepMania 5.1\Save

Of course, you would replace the "StepMania 5.1" with the correct name for your version of stepmania.

**Comment by TheKamilia** [comment]
Or just make a file called portable.ini place it in your normal sm directory

**Comment by coderjo** [comment]
Keep in mind, portable mode will not work if you installed under Program Files unless you change the permissions of the folder.
