### ISSUE TITLE
Couples mode doesn't work in Pump

### ISSUE THREAD

**Issue by RhythmLunatic** [stepmania/stepmania#1753]
I made a couples chart for Pump mode, but for some reason P1 and P2 are both using P1's notes.

Tried multiple themes, AutoSetStyle on or off. Tested on StepMania 5.0.12 and 5.1 beta 2.

It works fine in Dance mode, though.

**Comment by dguzek** [comment]
Just to clarify, did you make a couples chart or a routine chart?

I've never tried making a couples chart, but in the past I've found that routine mode has a similar issue (and a few others), leaving it not really playable.

**Comment by RhythmLunatic** [comment]
Routine works (somewhat). This is specifically a couples chart.

**Comment by dguzek** [comment]
Perhaps this discussion can be rolled into #1789?

**Comment by RhythmLunatic** [comment]
Found something.

`iOriginalTrack[]` in `NoteData::LoadTransformed()` is looping back to 0-4 instead of 0-9 like it should. Somehow this is only happening in pump.

In dance it loops from 0-7.

So what's happening?
`int iNewToOriginalTrack[]` is an array that is initialized in `Style::GetTransformedNoteDataForStyle()`:
```cpp
int iNewToOriginalTrack[MAX_COLS_PER_PLAYER]
for( int col=0; col<m_iColsPerPlayer; col++ )
{
	ColumnInfo colInfo = m_ColumnInfo[pn][col];
	iNewToOriginalTrack[col] = colInfo.track;
}
```

In both dance and pump it has a length of 16. That doesn't seem right, but it's not the issue anyway. (Also that means the unused parts of the array are left uninitialized)
`m_iColsPerPlayer` is 5 in pump, 4 in dance.

In dance, `iNewToOriginalTracks[]` is set up correctly:
for P1: `[0,1,2,3,X,X,X,X,X,X,X,X,X,X,X,X]`
for P2: `[4,5,6,7,X,X,X,X,X,X,X,X,X,X,X,X]`
X: uninitialized data.

in pump, it's initialized like this:
for P1: `[0,1,2,3,4,X,X,X,X,X,X,X,X,X,X,X]`
for P2: `[0,1,2,3,4,X,X,X,X,X,X,X,X,X,X,X]`

ColumnInfo is a struct, m_ColumnInfo is an array of it:
```cpp
/** @brief Some general column infromation */
struct ColumnInfo 
{ 
	int   track;		/**< Take note data from this track. */
	float fXOffset;		/**< This is the x position of the column relative to the player's center. */
	const char *pzName;	/**< The name of the column, or NULL to use the button name mapped to it. */
};

/** @brief Map each players' colun to a track in the NoteData. */
ColumnInfo		m_ColumnInfo[NUM_PLAYERS][MAX_COLS_PER_PLAYER];
```

So where is m_ColumnInfo coming from? Well, it's defined in GameManager.cpp, right?

So... Someone messed up and it wasn't caught until now.

```cpp
{	// PLAYER_1
    { TRACK_1,	-PUMP_COL_SPACING*2.0f, NULL },
    { TRACK_2,	-PUMP_COL_SPACING*1.0f, NULL },
    { TRACK_3,	+PUMP_COL_SPACING*0.0f, NULL },
    { TRACK_4,	+PUMP_COL_SPACING*1.0f, NULL },
    { TRACK_5,	+PUMP_COL_SPACING*2.0f, NULL },
},
{	// PLAYER_2
    { TRACK_1,	-PUMP_COL_SPACING*2.0f, NULL },
    { TRACK_2,	-PUMP_COL_SPACING*1.0f, NULL },
    { TRACK_3,	+PUMP_COL_SPACING*0.0f, NULL },
    { TRACK_4,	+PUMP_COL_SPACING*1.0f, NULL },
    { TRACK_5,	+PUMP_COL_SPACING*2.0f, NULL },
},
```

https://github.com/stepmania/stepmania/blob/5_1-new/src/GameManager.cpp#L731-L744
