### ISSUE TITLE
Add a lua binding for CloseCurrentFolder

### ISSUE THREAD

**Issue by sillybear** [stepmania/stepmania#1755]
Setting the mwheel's SetOpenSection to "" (nothing) doesn't do the AfterMusicChange so the highlighted item always points to a song instead of a folder. The title in my post is the only known solution for me.

**Comment by RhythmLunatic** [comment]
ScreenSelectMusic:CloseCurrentSection() has been in the source for about a year

**Comment by dguzek** [comment]
I haven't tested it, but this has presumably been fixed by #1555.
