### ISSUE TITLE
"No Noteskins found" on startup on MacOS Mojave 10.14.1

### ISSUE THREAD

**Issue by shyamalschandra** [stepmania/stepmania#1759]
What is going on?  I am getting the following error message.

![screen shot 2018-11-06 at 8 16 20 pm](https://user-images.githubusercontent.com/9545735/48106459-20ec4580-e201-11e8-9cbf-31b6cd8e12d3.png)

What is going on?  I cannot even build the app from source because there is no dependencies list in the GitHub README?

**Comment by coderjo** [comment]
For the error message, check #1299 and see if that helps you. Yes, we should fix it, but I am not a MacOS developer. (And I think the solution is having a developer sign releases.)

**Comment by dguzek** [comment]
See: <https://github.com/dguzek/Simply-Love-SM5/wiki/Installing-StepMania-5.1-beta-on-macOS>

**Comment by ianklatzco** [comment]
for anyone who finds this issue in the future: 
```xattr -dr com.apple.quarantine ~/your-path-to/StepMania.app/```

**Comment by quietly-turning** [comment]
Sorry, the guide I linked to above got moved to here: 
https://github.com/stepmania/stepmania/wiki/Installing-on-macOS
