### ISSUE TITLE
SM5.1-beta2 crashes on startup on macOS High Sierra

### ISSUE THREAD

**Issue by beachgirl6976** [stepmania/stepmania#1762]
I followed instructions on [GitHub](https://github.com/dguzek/Simply-Love-SM5/wiki/Installing-StepMania-5.1-beta-on-macOS ) to download and fix the no noteskins error.

SM seemed to be working fine but I changed the settings to Freeplay by accident and noticed that the menu was not loading anymore so I was unable to access any settings at all. 

This [thread](https://www.stepmania.com/forums/general-stepmania/show/2271) suggested a fix by holding the F3 key to get into the Debug Menu to change back. Since I’ve done this the game crashes on startup every time. 

I’ve uninstalled, removed all files I can find associated to the game and reinstalled again including many of the other previous versions and all of them continue to crash. Any ideas on how to get the game working again?

[crashinfo.txt](https://github.com/stepmania/stepmania/files/2586650/crashinfo.txt)
[Terminal.txt](https://github.com/stepmania/stepmania/files/2586664/Terminal.txt)

**Comment by dguzek** [comment]
It sounds like you're on macOS, so the keyboard shortcut you're looking for will be to hold <kbd>fn</kbd> then hold <kbd>F3</kbd> then tap <kbd>1</kbd> until the until you see the `CoinMode` change to `Home` in the debug overlay.

**Comment by dguzek** [comment]
I'm not sure what might be causing this, so my only suggestion is to try deleting the folder located at `~/Library/Preferences/StepMania 5.1/`.  

If you're unsure how to get there, you can bring up a *Go to folder* prompt with the <kbd>Shift</kbd> + <kbd>Command</kbd> + <kbd>G</kbd> keyboard shortcut while on your desktop (or, when Finder is the active application), copy/paste the path I provided above, and deleting all the files in there such as Preferences.ini, Coin.ini, Coins.xml, etc.

By deleting all this, it should effectively "reset" your StepMania's preferences and settings, and these files should be recreated with default values the next time you start up SM5.
