### ISSUE TITLE
Lack of modified latin characters like "š" "ā" or "ī"

### ISSUE THREAD

**Issue by xillmisa** [stepmania/stepmania#1769]
I wanted to translate stepmania to my language but after creating lv.ini in language folder(https://pastebin.com/BvB3Q6M0), and when i change language to lv.ini, lots of modified latin characters (like "ā") becomes question marks (https://i.imgur.com/VsN5MvX.png)

**Comment by Horsey-** [comment]
the problem is that the font library in the default theme do not support those characters, and just to warn you, any other themes won't either. What are all the modified Latin letters that appear in the Latvian language? They just need to be added to all the necessary font files.

**Comment by xillmisa** [comment]
@Horsey- it's "ā" "č" "ē" "ģ" "ī" "ķ" "ļ" "ņ" "š" "ū" "ž"

**Comment by Horsey-** [comment]
I'm assuming they all have majiscule (uppercase) forms as well?

**Comment by xillmisa** [comment]
yes

**Comment by xillmisa** [comment]
when i opened font files in stepmania themes, then there are modified latin characters but why stepmania dont recognise them?

**Comment by xillmisa** [comment]
i think i should create font file for transaltion

**Comment by Horsey-** [comment]
oh sorry, I forgot to mention that you had to encode the file in a certain format in notepad++, I'll be home in about 8 hours from now

**Comment by shakesoda** [comment]
> oh sorry, I forgot to mention that you had to encode the file in a certain format in notepad++, I'll be home in about 8 hours from now to check what it was (I don't remember what it is offhand)

utf-8 (without bom)
