### ISSUE TITLE
Noteskins not appearing

### ISSUE THREAD

**Issue by AURA547** [stepmania/stepmania#1780]
When I first got Stepmania I used this website ---> (http://zettbou.co.uk/#) To install some DDR noteskins and they worked fine, now I'm trying to use ITG noteskins and t=get them from the same website but now they are not appearing in-game at all. I tried uninstalling reinstalling the skins, changing themes and tried looking in the .ini files to see if I can increase the number of skins shown on screen at once, but to no avail. maybe I installed them incorrectly or something or if it's an SM5 problem or something to do with Windows10 idk, I just need a little assistance rn.

**Comment by ListenerJubatus** [comment]
Is the folder structure correct?

Has to be NoteSkins/**dance**/[noteskin name]

with [noteskin name] folder containing the ini, lua, etc

**Comment by AURA547** [comment]
It worked, man I'm dumb sometimes... Thank you so much!
