### ISSUE TITLE
The targets overlap on pump mode

### ISSUE THREAD

**Issue by s34nvideos** [stepmania/stepmania#1784]
The targets overlap on pump mode.

1. Select pump as the game
2. Pick a chart and play
3. At the top of the screen, the arrow targets overlap each other slightly. It's really strange.

No pump game I have ever played does this, so I presume this is a bug.

Example here: https://arcofswords.s-ul.eu/aKZIqvs3.png

Should look more like this: https://www.youtube.com/watch?v=73Irh648c1A

**Comment by ListenerJubatus** [comment]
I was actually looking at that. Increasing the column spacing too much actually causes the notefield to forcibly go to the center of the screen for some reason.

I noticed that the _very old_ PIU games did this, but it's been largely removed (even on Prime 2 with this noteskin)

https://www.youtube.com/watch?v=_47lZ0mlgyk

**Comment by shakesoda** [comment]
not a bug, and some overlap is still visible in prime. afaik the size of the sprites is just different.

**Comment by s34nvideos** [comment]
'some' overlap on prime, yeh maybe 1mm or so.
On SM5, the overlap is crazy huge!

Please don't close this without providing an actual solution or more supporting information for your sprite theory.

**Comment by s34nvideos** [comment]
From the comments I've had in the SL and SM repos (apart from ListenerJubatus), it doesn't make we want to contribute anything. Some weird attitude problem here. You guys need some sleep or something. Christ. I'm out

**Comment by shakesoda** [comment]
nobody here is trying to be mean about it or something, I'm just fairly certain the column spacing is what it should be. we're using a bigger sprite than pump does.
