### ISSUE TITLE
how to disable hold notes [help wanted]

### ISSUE THREAD

**Issue by helppe** [stepmania/stepmania#1787]
hello,
im a beginner at this game (downloaded it yesterday) i dont find option where i can disable the hold notes.
i have more fun with just simple notes. can you tell me how to do?

thank you

**Comment by Tatsh** [comment]
When you choose modifiers (by pressing Enter after choosing a song), there's an option called *No Holds*.

![20190210133914-screenshot](https://user-images.githubusercontent.com/724848/52537853-45dce100-2d39-11e9-9446-1fa4664a7a5f.png)

The bar underneath indicates it is on.

**Comment by helppe** [comment]
thank you

**Comment by dguzek** [comment]
I'm going to close this issue now under the assumption that it has been satisfactorily resolved.
