### ISSUE TITLE
Compiling the 5_0 Branch fails, recompile with -fPIC?

### ISSUE THREAD

**Issue by calexil** [stepmania/stepmania#1796]
**Full Output:**

[100%] Linking CXX executable ../../stepmania
/usr/bin/ld: ../../extern/libmmmagic/linux-64bit/libmmmagic.a(mmmagic.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../extern/libmmmagic/linux-64bit/libmmmagic.a(minimaidhid.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../extern/libmmmagic/linux-64bit/libmmmagic.a(update.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
src/CMakeFiles/StepMania.dir/build.make:11004: recipe for target '../stepmania' failed
make[2]: *** [../stepmania] Error 1
CMakeFiles/Makefile2:380: recipe for target 'src/CMakeFiles/StepMania.dir/all' failed
make[1]: *** [src/CMakeFiles/StepMania.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by shakesoda** [comment]
5_0 branch is dead.

this should already be fixed in the 5_1-new branch

**Comment by shakesoda** [comment]
btw you can work around by disabling minimaid driver in cmake flags

**Comment by calexil** [comment]
@calexil how would one do that?

**Comment by calexil** [comment]
Solved with: https://github.com/stepmania/stepmania/issues/1627#issuecomment-361024454
