### ISSUE TITLE
memcards mounting at wrong player for Windows

### ISSUE THREAD

**Issue by RhythmLunatic** [stepmania/stepmania#1797]
Somehow MemoryCardOsMountPointP1 is being used for Player 2.

This does not affect Linux, I tested.
OS: Windows 8.1 and Windows 10 (separate machines)

**Comment by RhythmLunatic** [comment]
the issue mysteriously disappeared.

**Comment by quietly-turning** [comment]
> the issue mysteriously disappeared.

Sounds like a good excuse to apply my favorite StepMania GitHub label.
