### ISSUE TITLE
"Anamorphic" aspect ratio not possible from 5_1-new

### ISSUE THREAD

**Issue by PehrMeldert** [stepmania/stepmania#1801]
I used to have 16:9 aspect ratio with 1024x768 resolution because I have an old SDTV, but from 5_1-new I can only choose 720x400 which is the only true 16:9 resolution my TV can handle.
Is there a workaround for this?`
I'm in Linux btw.

**Comment by dguzek** [comment]
This is a result of #1018 which fixed #139.  I encourage you to read both those to gain a better understanding of the issue.  If you still have questions afterwards, ask here, and we can try to help you further.

**Comment by sillybear** [comment]
I dunno if this work but, try manually changing the values via pref.ini instead of changing in game's main option. Just don't go to main options though after.

**Comment by dguzek** [comment]
@PehrMeldert - can you more clearly explain what you are trying to accomplish?  For example:

* what is the physical aspect ratio of your TV?
* what aspect ratio are you trying to force SM into?
* what resolution are you trying to force?

**Comment by PehrMeldert** [comment]
> @PehrMeldert - can you more clearly explain what you are trying to accomplish? For example:
> 
> * what is the physical aspect ratio of your TV?
> * what aspect ratio are you trying to force SM into?
> * what resolution are you trying to force?

* 16:9 (2004 LG Plasma 42")
* 16:9
* 1024*768 @ 60 Hz

I think I managed this by manually editing preferences.ini now...

**Comment by dguzek** [comment]
Thanks for responding.  

Have you asked anywhere else about this?  In general, GitHub is better suited to development work/talk/interactions than software support, but I understand issues like this do blur the lines.

Out of curiosity, what is you reasoning for forcing the software into a 4:3 aspect ratio when the TV  is physically 16:9?  I don't understand right now, but maybe if explain it will make more sense.

> I think I managed this by manually editing preferences.ini now...

That's good to hear.  Let us know if not.

**Comment by PehrMeldert** [comment]
I'm  sorry but I thought I could ask here since stepmania forum is closed...

The reason is that my tv does not support any true 16:9 resolution. Instead it takes the 4:3 signal and stretches it to 16:9. This is how most tv's worked in the early 00's in the transition from 4:3 to 16:9.

**Comment by dguzek** [comment]
> I'm sorry but I thought I could ask here since stepmania forum is closed...

It's fine.  I think most people have better luck asking on Facebook's DDR+ITG Players group, the stepmania subreddit, or the ZIv forums, but this works in a pinch.

> The reason is that my tv does not support any true 16:9 resolution. Instead it takes the 4:3 signal and stretches it to 16:9. This is how most tv's worked in the early 00's in the transition from 4:3 to 16:9.

I'd never heard of anything like this before, so I was confused by your request, but I understand better now.  Thank you for taking the time to explain.

Have you gotten this working satisfactorily by editing Preferences.ini?  Let us know.

**Comment by PehrMeldert** [comment]
Yes, it works like before now so I'm satisfied with the work around.

**Comment by dguzek** [comment]
Glad to hear you got it working.  I'll close this now.
