### ISSUE TITLE
cmake failed if only select pulseaudio as audio driver [all branch(?)]

### ISSUE THREAD

**Issue by sl1pkn07** [stepmania/stepmania#1803]
https://github.com/stepmania/stepmania/blob/e0b27d60b9da88bc6569b0b0b96a1b1ea7a75b4c/StepmaniaCore.cmake#L407

seems is a typo. should be `PULSEAUDIO_FOUND`

https://github.com/stepmania/stepmania/blob/e0b27d60b9da88bc6569b0b0b96a1b1ea7a75b4c/CMake/Modules/FindPulseAudio.cmake#L7

if set 

~~~
    -DWITH_JACK=OFF \
    -DWITH_ALSA=OFF \
    -DWITH_PULSEAUDIO=ON \
~~~
then
~~~
- Checking for module 'libpulse'
--   Found libpulse, version 12.2
-- Found PULSEAUDIO: /usr/include  
CMake Error at StepmaniaCore.cmake:409 (message):
  No sound libraries found (or selected).  You will require at least one.
Call Stack (most recent call first):
  CMakeLists.txt:5 (include)


-- Configuring incomplete, errors occurred!
~~~

if set `PULSEAUDIO_FOUND` start build without problem

**Comment by latot** [comment]
mmm, i test this today and in my case works correctly (Linux).

**Comment by geefr** [comment]
So it's a type on PULSEAUDIO_FOUND

Fixed by #1843

**Comment by latot** [comment]
Hi, i test today this with the 5_1-new branch and still is present.

Bye.

**Comment by latot** [comment]
my bad, is working.

**Comment by geefr** [comment]
@latot We all make mistakes, click the 'close issue' button down there vv if you're feeling helpful :)
