### ISSUE TITLE
Arrows work in menu but not in the song

### ISSUE THREAD

**Issue by yoicherrs** [stepmania/stepmania#1817]
I have a problem in MacOS Mojave with both 5.0.12 and the 5.1-beta. I have mapped the pad manually because automatic mapping didn't work. I can use arrows and select/back buttons in the menu to chose the song, level, navigate through the menu, but when the song starts no button on the pad works. Any ideas how to solve it?
I have 2 pads and cannot use either of them.

**Comment by PaddyCo** [comment]
@yoicherrs Check the **Config Key/Joy Mappings** screen again, you might've have only mapped the MenuLeft/MenuRight/MenuUp/MenuDown bindings, further down should be the actual Left/Right/Up/Down mappings that are actually used in-game

Why those bindings are at the bottom I have no clue, as I feel like they should actually be at the top

**Comment by yoicherrs** [comment]
This worked well. many years in quality assurance and this didn't cross my mind! Thank you!
