### ISSUE TITLE
Windows PacDrive missing in 5.1-new

### ISSUE THREAD

**Issue by RhythmLunatic** [stepmania/stepmania#1818]
Not sure if these files were removed on purpose or if something happened, is this intentional?

If not I will make a pull request and copy them from the master branch to 5.1-new.

**Comment by dguzek** [comment]
The PacDrive files were added to the *master* branch via pull request #1329, which was submitted 30 October 2016.  The *5_1-new* branch had already been created a few months prior (5 August 2016, to be precise), and the two branches weren't necessarily kept on par with one another.

So, it's not that the PacDrive files were removed on purpose from 5_1-new, it's that they were never added in the first place.  You can probably just `cherry-pick` 561e4349111ce5159814776b86b199b6ab7fc0c5 into 5_1-new, though I haven't tried that.

**Comment by dguzek** [comment]
Resolved by #1819.  Thanks, @RhythmLunatic!
