### ISSUE TITLE
Groove Radar doesn't work for many simfiles

### ISSUE THREAD

**Issue by RhythmLunatic** [stepmania/stepmania#1836]
Suddenly the groove radar only stays in the middle for most simfiles, but for others it generates correctly. No idea why. I see the groove radar code hasn't been touched in 4 years, so it's kind of a mystery to me.

Tested with the latest 5.1-new nightly..

Update: Aaaaaand it's only happening on Windows.

**Comment by shakesoda** [comment]
try deleting your cache

**Comment by RhythmLunatic** [comment]
It is not a cache bug, I've deleted the cache.

I think it's a compiler bug since it's only happening on Windows, so I'll try compiling again.

**Comment by RhythmLunatic** [comment]
I found the issue. https://github.com/stepmania/stepmania/blob/631985af4bbb42b7ece9561c8e7904d7c4223252/src/GrooveRadar.cpp#L110

A float is being cast to an int. My linux build was outdated because my git branches were being annoying.

**Comment by thenerdie** [comment]
Lol good spot!

**Comment by shakesoda** [comment]
oh good, i botched a warning fix. thanks for spotting.
