### ISSUE TITLE
lua.xml missing information in various places

### ISSUE THREAD

**Issue by RhythmLunatic** [stepmania/stepmania#1839]
Just making this an issue so I can remember to fix it later.

GetDisplaySubTitle() returns "" on blank, maybe other song related functions will as well.

**Comment by RhythmLunatic** [comment]
GetCourseDir() documentation is also incorrect and says it returns the directory when it returns the location of the .crs file

**Comment by RhythmLunatic** [comment]
FindSong() supports searching by group if you give it an argument like "MyGroup/MySong"

**Comment by RhythmLunatic** [comment]
SetOpenSection does not state that doing SetOpenSection("") will close the current section.
Additionally `SCREENMAN:GetTopScreen():PostScreenMessage( 'SM_SongChanged', 0.5 );` has to be executed after this to actually update the music wheel's selection.

**Comment by RhythmLunatic** [comment]
MusicWheel:GetWheelItem(index-1):GetType() is returning an int instead of a WheelItemDataType enum.

This should probably be fixed.

**Comment by RhythmLunatic** [comment]
EffectMode enum is missing from xml https://github.com/stepmania/stepmania/blob/master/src/RageTypes.h#L45-L59

(Yes, I know it doesn't work, but it should be there anyway)

**Comment by quietly-turning** [comment]
Adding to this thread with Lua.xml things I've found and have been meaning to fix...

---

`HighScore:GetHighScore()` – looks like this was accidentally duplicated from `PlayerStageStats:GetHighScore()`; HighScore.cpp does not have a `GetHighScore()` method

---

`ClearEnterMappedKeys()` is not actually a global Lua function defined in _fallback

---

`ScreenSelectProfile:SetProfileIndex(pn, iProfileIndex)` has important but currently undocumented functionality via hardcoded values that can be passed in.

Player profile index values typically (are supposed to?) start at 0.

`-1` as second argument calls JoinPlayer() on the player argument and returns `false`

`-2` as second argument Unjoins the player, unlocks their memory card, unmounts their memory card, and returns `true`

values less than `-2` will just return `false`

---

Actor classes currently not mentioned in the XML LuaDocs:

 * DeviceList
 * InputList
 * SongMeterDisplay

**Comment by RhythmLunatic** [comment]
RageTexture::GetTextureCoordRect expects `int iFrameNo` as the argument

**Comment by RhythmLunatic** [comment]
GAMESTATE:GetPreferredDifficulty() takes PlayerNumber enum as the argument

**Comment by RhythmLunatic** [comment]
I checked https://quietly-turning.github.io/Lua-For-SM5/LuaAPI and it seems like everything is there so I'm going to assume this issue is resolved. (Though I didn't check closely.)

If I missed something someone reopen it.

**Comment by quietly-turning** [comment]
I'm still working on #1997, I promise!  It was originally supposed to take a week, but I'm still working on it five weeks in... 😬

I haven't yet had time to look at WheelItemBase's `Move()` or RageTexture's `GetTextureCoordRect`, so both of those are unchanged.  

Everything else mentioned here has had documentation updated one way or another in #1997.
