### ISSUE TITLE
params.HasFocus in SetMessageCommand does not function correctly in 5.1-new

### ISSUE THREAD

**Issue by RhythmLunatic** [stepmania/stepmania#1840]
Short example for Graphics/MusicWheelItem Song NormalPart/default.lua
```lua
return Def.ActorFrame{
    LoadActor("bg")..{
        SetMessageCommand=function(self,params)        
            if params.HasFocus then
                self:visible(true);
                self:diffuseramp();
                self:effectcolor2(PlayerColor(getPlayer));
                self:effectclock('beatnooffset');
            else
                self:visible(false);
            end;
        end;
    };
};
```
In 5.0.12 this will set HasFocus to true and then it will show when the item has focus, in 5.1-new it will appear and then disappear a frame later.

Caused by https://github.com/stepmania/stepmania/commit/31e99dc457a4bd287a83773369802564b8dff241 and https://github.com/stepmania/stepmania/pull/1361

SetMessage is being called twice, once for the new WheelItem being set and again because the steps changed. In fact since it handles both P1 and P2 steps it's probably running multiple times on the same WheelItem which seems detrimental.

Personally I think SetMessage should not be used in this way because there are already MessageCommands to handle this. I'm not sure what the benefit is of adding it is.

**Comment by RhythmLunatic** [comment]
@sillybear since nobody else seems to care about this issue, what is the benefit of SetMessage being broadcast when CurrentStepsPXChanged is broadcast as opposed to listening for CurrentStepsPXChanged in a MusicWheel Item?

**Comment by sillybear** [comment]
I can't pass a song param (from MusicWheelItem's SetMessage) to CurrentStepsPXChanged.

**Comment by RhythmLunatic** [comment]
```lua
CurrentStepsPXChangedMessageCommand=function(self)
local param;
param.Song = GAMESTATE:GetCurrentSong()
playcommand("Set",param)
```

**Comment by sillybear** [comment]
That's only for the current song. You forgot the songs from the other music wheel items.

**Comment by RhythmLunatic** [comment]
Idk a real fix for this so the first SetMessage can be removed and everything should be duplicated to the second one.

It doesn't fix SetMessage being called multiple times but the "fix" is just reverting the PR

**Comment by sillybear** [comment]
I'm not sure about it but, try removing all Set params except for Song and Course in the cpp and see if there is a difference.

**Comment by RhythmLunatic** [comment]
The problem is that HasFocus is nil.
something like this might be possible if the second SetMessage is removed:
```lua
local paramCache;
Return Def.ActorFrame{
    Def.BitmapText{
        SetMessageCommand=function(self,param)
            paramCache = param;
            self:playcommand("Set2",param)
        end;
        CurrentStepsPXChangedCommand=cmd(playcommand,"Set2", paramCache);
    }
}
```
(Pseudo code, I don't know if it works for sure)

**Comment by RhythmLunatic** [comment]
Lazier fix, maybe just checking false instead of nil is fine.

**Comment by sillybear** [comment]
Doesn't work. :-(

**Comment by RhythmLunatic** [comment]
Lazy fix:
`if params.HasFocus == nil then return end;`

**Comment by RhythmLunatic** [comment]
Coming back to this a year later... The real fix is to deep copy an array, not just use equals. Since arrays are pointers. Oops, my mistake.

Either way I don't think this should have been merged without checking since it breaks older themes. But it's too late now and there are probably themes that rely on this new behavior at this point, being a three year old merge.
