### ISSUE TITLE
Building 5.1-new from source on Linux produces a soundless executable (no sound in gameplay)

### ISSUE THREAD

**Issue by Horsey-** [stepmania/stepmania#1848]
I've been trying to get the game to compile properly all week no no avail. I have tried installing 4 different linux derivatives (Mint, Lubuntu 18 and 19) to no avail. I followed the build instructions on the wiki by copy+pasting commands into the terminal. When I build the 5.1-new branch I receive an executable that produces no sound (I am able to play a youtube video just fine on my system with sound, so I know that there is no hardware issues). In order to best debug this situation, I have reinstalled Linux Lubuntu 19 from scratch on a new harddrive. The only interaction I had with the system before running the below commands was to switch the display driver from nouveau to the Nvidia proprietary display driver. 

The terminal log below is from a clean Linux installation, following the guide verbatim from installing dependencies to building the executable to running the executable (playing one song 'soundless') and exiting the game. No outside code, themes, extras: this is a clean installation from github. 

[terminal output building 5.1-new (no sound).txt](https://github.com/stepmania/stepmania/files/3465295/terminal.output.building.5.1-new.no.sound.txt)

(pastebin https://pastebin.com/uhNNAr4q)

**Comment by Horsey-** [comment]
When I build the master stepmania branch (5.2) I receive an executable that works just fine after playing one song. I am pasting my terminal log below of downloading the repo through git all the way to playing one round of the game and exiting the game after. 

[terminal output building 5.2 (works great).txt](https://github.com/stepmania/stepmania/files/3465315/terminal.output.building.5.2.works.great.txt)


--I'd like to point out that when building the master branch (5.2) terminal actually has an output when I input the `git submodule update --init` command. When I run this code while building 5.1 nothing happens in terminal.

**Comment by pmaranin** [comment]
Hi.
I had the same issue yesterday. It seems the root ause was that 5.1 is not compiled with pulseaudio for sound as default (check the system output when you start stepmania under the ALSA... lines)

I solved the issue by adding the following parameter to the cmake command : 
-DWITH_PULSEAUDIO=ON

Now when I run stemania 5.a in the sys out I get "
"Sound Driver: Pulse" below the ALSA log lines

Hope it helps

**Comment by mwkroening** [comment]
I think, this can be closed now.

**Comment by shakesoda** [comment]
enabling pulse aside - the issue here seems to be just bad audio device selection, you had to change the preference (probably to something like plughw:0,0 or "default"), or it'd fail if you don't use pasuspender.

try changing some alsa driver settings if you encounter bugs with pulse, but it should fix audio output.
