### ISSUE TITLE
Linux: Building without legacy GL library

### ISSUE THREAD

**Issue by mwkroening** [stepmania/stepmania#1859]
When setting up a build folder this warning shows up:
```bash
# [...]
CMake Warning (dev) at /usr/share/cmake-3.15/Modules/FindOpenGL.cmake:275 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  StepmaniaCore.cmake:438 (find_package)
  CMakeLists.txt:5 (include)
# [...]
```

I think it would be good to use `GLVND` if available as it's being adopted by many distributions using Mesa: [phoronix.com - Ubuntu 18.04 LTS Landing Mesa 18.0, Enabling GLVND](http://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-18.04-Getting-Mesa-18.0)

**Comment by shakesoda** [comment]
this sounds good to me, but i'm a little unsure if changing this will affect building on older cmake versions. how far back does this option go?

**Comment by mkroening** [comment]
The `FindOpenGL` module was created in 2001 in [cmake/commit/c24437](https://gitlab.kitware.com/cmake/cmake/commit/c244378a861fd5d2c923c9452c0ab44343f7aac3). So that should not be a problem. Setting the preference via a variable should be fine as well. It should just be ignored if CMake does not support it.

**Comment by geefr** [comment]
I would question the use of include(FindOpenGL) vs find_package. I might be a little behind the times on this one but always found find_package to be the best choice for dependency searching.

Moving the dependency/linking over to the new OpenGL::OpenGL name syntax would probably be a good idea, but think that prevents older versions of cmake.

Speaking of old versions it might be a sensible idea just to require 3.6+ or so.

**Comment by mkroening** [comment]
Ah, yes! Thanks for the heads up! find_package is indeed still to be preferred. Changed the PR.

I agree on the new name syntax but I think we should tackle that separately from this one.
