### ISSUE TITLE
5_1-new: Outdated .editorconfig

### ISSUE THREAD

**Issue by mwkroening** [stepmania/stepmania#1862]
The .editorconfig of branch `5_1-new` does not match the format of the existing source and CMake files.

In particular the CRLF line ending is throwing me off every time I edit something on this branch.

**Comment by shakesoda** [comment]
thanks for transplanting that.

it'll certainly mess up a lot of alignment (after indent) which assumes 8-wide tabs, but those can be replaced as needed.
