### ISSUE TITLE
Don't depend on the DirectX SDK

### ISSUE THREAD

**Issue by mkroening** [stepmania/stepmania#1874]
Since the DirectX SDK is deprecated we should use the Windows SDK instead.

See [Where is the DirectX SDK (2015 Edition)?](https://walbourn.github.io/where-is-the-directx-sdk-2015-edition/) and [The Zombie DirectX SDK](https://walbourn.github.io/the-zombie-directx-sdk/).

Since we also use XInput we must work around a version mismatch if we want to maintain Windows 7 support.

I already started working on this but still have to clean the changes up.

What do you think?

**Comment by coderjo** [comment]
I need to backport my changes for this from master to 5.1-new. (Or someone else is welcome to, if they want)

**Comment by mkroening** [comment]
I'll have a look at it.

**Comment by RodentVienna** [comment]
would winxp be affected?

**Comment by mkroening** [comment]
Indeed this would not run on Windows XP but IMHO it's time to move past XP.

@RodentVienna, are you still using XP? Is it possible for you to migrate to a more recent Windows or Linux?

**Comment by coderjo** [comment]
I think it might actually still run on XP if built with the right toolchain, like v140_xp on vs2015.

**Comment by mkroening** [comment]
In the first blog entry it says: "There are really only three scenarios where you should continue to use the old DirectX SDK: [...] 3. You are targeting Windows XP with the alternate `v1x0_xp` Platform Toolset.". I did not test that though.

**Comment by mkroening** [comment]
On second though those statements are not contradictory and it should still work if we supported the old DirectX SDK as well. Is there still a large userbase stuck on Windows XP?

**Comment by Prcuvu** [comment]
Yes, there is indeed a large player base (who do not even own a computer) playing StepMania in cheap Internet café where managers do not bother upgrading their hardware and software, thus still stuck on Windows XP.

**Comment by coderjo** [comment]
I can try a v140_xp build on an xp vm later to see if it works.

**Comment by mkroening** [comment]
Okay, having Windows XP machines connected to the internet is obviously a bad idea. I'm not sure, if we should encourage that. Also some libraries (like FFmpeg since 4.0, see [changelog](https://github.com/FFmpeg/FFmpeg/blob/master/Changelog#L121-L122)) are not supporting XP. In my opinion this project should not be held back by this legacy operating system of which extended support ended in 2014. On the other hand losing a large player base should obviously be avoided if possible. @Prcuvu, are you sure, that this information is up to date and correct? Should we do a survey or would that player base be invisible to a survey?

@coderjo, which chance set are you testing? AppVeyor builds are targeting XP.

**Comment by coderjo** [comment]
I was just going to use my most recent build, which was done off master (because I have been too lazy to backport the tomcrypt and dx fixes so far) using vs2015 and the v140_xp toolset (because last time I tried running one built with v140 on my win7 box, it didn't run. I forget why, however.) The goal just being to see if that will even run on xp.

**Comment by mkroening** [comment]
The highest usage of Windows XP I found on first glance was in Armenia with 45% of all Windows PCs according to StatCounter. The global Windows market share of Windows XP does not seem to be higher than 3% though.

Would you still insist on supporting Windows XP, @Prcuvu?

Sources:
* [StatCounter Global Stats](https://gs.statcounter.com/windows-version-market-share/desktop/worldwide)
* [NetMarketShare](https://www.netmarketshare.com/operating-system-market-share.aspx?id=platformsDesktopVersions)
* [Wikimedia Analytics](https://analytics.wikimedia.org/dashboards/browsers/#all-sites-by-os/os-family-timeseries)

**Comment by quietly-turning** [comment]
My understanding is that at one point, many players were tied to XP because they also wanted to run other games (that were made to run on XP) using a single PC.  I'm not sure if the Soft15KHz project was ever updated to run on OSes newer than XP, either.

Maybe there are other alternatives to Soft15KHz now.  Or, maybe those players are no longer tied down to XP.  I don't know because I don't keep up with the scene.  

In general, I support moving forward, which includes dropping support for older OSes and hardware.

**Comment by RodentVienna** [comment]
if i remember correctly, i was involved in a discussion on an openitg git
pr of chris pable where i was very wrong (in subject and behavior, my
apologies) about winxp. basically Operators of older ddr cabinets depend on
winxp to deploy stepmania. i will link you to that disussion when i am home
from work. thank you for the heads up.

dguzek <notifications@github.com> schrieb am Do., 29. Aug. 2019, 13:21:

**Comment by Prcuvu** [comment]
Actually there is a tide of ending support of Windows XP (and also Windows Vista) from mainstream online games, and I am sure Internet cafés will be forced to upgrade their machines in the near future.

However, I still personally do not see it necessary to drop support of Windows XP when there is no Windows Vista specific APIs being used. I am specifically referring to Direct3D 11 and WASAPI (for low-latency audio output). If we are to add Direct3D 11 (just like StepMania 5 moving from Direct3D 8 to 9) and/or WASAPI, I will be totally with dropping Windows XP support.

**Comment by mkroening** [comment]
As I said above, our dependencies tend to have dropped XP support in recent versions.

I see three possibilities:
1. Stick to old library versions
2. Update libraries and drop Windows XP support
3. Support multiple library versions

Coincidentally this also collides with my initiative of removing certain bundled dependencies (see #1869 and #1876), since my recommended CMake toolchain provider vcpkg requires at least Windows 7. So my preference would be 2, as 3 would require some custom CMake toolchains for XP support or similar, which would be a maintenance burden but be bearable. What's your stance on this?

Edit: So even though we might not use Windows 7 specific features directly, we might do so indirectly with recent libraries. Even if current libraries happened to just work on XP, we can't rely on that if the support has ended explicitly.

**Comment by geefr** [comment]
@mwkroening On the subject of package managers I've done a little playing with conan recently, its only dependency is python and there's a fetch mode that works with find_package/etc. Could be useful if keeping xp support.

If anyone wants my 2p I'd drop xp completely whenever the graphics engine is next updated, or just as a matter of fact to reduce the support load. (I'd also stop worrying about 32-bit, go purely opengl, and start thinking about vulkan but that's personal bias :P)

**Comment by mkroening** [comment]
Thanks, @geefr. I think for supporting Windows XP with FFmpeg, it would be easiest to provide a CMake toolchain file for XP which sets up an older version of FFmpeg. That is not so different from what is happening currently. If, on the other hand, you think, it would be possible/better to throw conan into the mix via a toolchain file (not sure if possible), then I'd be happy to discuss details.

But we divert from the original issue here. Before we make big efforts on supporting multiple versions, we should agree on one of the three strategies I mentioned. If it turns out, that we can't let go of XP yet, the original issue can't be resolved until then.

Personally I like your bias regarding the backend fragmentation! ;)

**Comment by Horsey-** [comment]
I personally know an arcade manager that relies on XP for soft15khz, but that same person is using oITG and not SM5. There may be a multitude of people stuck on XP, but there's no way that those same people are fervently updating and recompiling SM5 for the latest updates. I say make a point release now before removing XP support and anyone that is stuck on XP can use that binary indefinitely. The old cab hardware we're depreciating is 20+ years old now. There's no reason to hypothetically support hardware that doesn't receive updates.

**Comment by mkroening** [comment]
Regarding soft-15khz: I did not know it before, but it seems to me that there have been updates for Windows 7: [SailorSat/soft-15khz](https://github.com/SailorSat/soft-15khz)

**Comment by shakesoda** [comment]
while it still technically works, we don't officially support xp anymore and haven't for some time.

clarification edit: while it isn't supported i'm perfectly fine with not breaking it, i just don't want it to be grounds for not moving out of the (rather distant, now) past.

**Comment by coderjo** [comment]
Resolved in #1905.

Also, I just tested a build made with Visual Studio 2015 and the included Windows SDK, without the DirectX SDK (which has never been installed on my system) on Windows XP and it runs fine.

**Comment by quietly-turning** [comment]
Thank you, @coderjo!
