### ISSUE TITLE
Support Visual Studio 2017 and higher

### ISSUE THREAD

**Issue by mkroening** [stepmania/stepmania#1875]
Currently building fails with Visual Studio 2017 or higher. This is due a problem with `libtomcrypt`.  I'll fill in the exact error message later, at this moment I don't have access to a Windows machine.

We really should not require Visual Studio 2015 since that version is hard to come by nowadays.

Updating `libtomcrypt` resolves the issue. I'll follow up with a PR.

**Comment by coderjo** [comment]
I had an issue with it on 2015 as well, due to conflicts with the latest windows SDKs. I did the work in master to bring the tomcrypt submodule up to a more recent version. I had been meaning to backport that as well, but haven't found the time/motivaition yet.

**Comment by mkroening** [comment]
Thanks! I'll have a look at your commits.
