### ISSUE TITLE
PRIME theme is disabled/gone, is it because of Windows 10 1903 update?

### ISSUE THREAD

**Issue by NHLJang** [stepmania/stepmania#1877]
Hi guys, sorry if this is not the place to issue this, but my game suddenly uses the default/fallback theme only for my StepMania5 CAOS PRIME installation. Could it be something to do with recent update of Windows version 1903, since my other installation on different PC still work fine.

**Comment by ListenerJubatus** [comment]
are you sure you didn't place it too deep in the directory structure?

It has to be, say, Themes/Theme Name/BGAnimations and so on. It cannot be Themes/Theme-1.0/Theme Name/BGAnimations etc.

**Comment by RhythmLunatic** [comment]
CAOS Prime is a fork of StepMania, ask the creator.

**Comment by NHLJang** [comment]
> are you sure you didn't place it too deep in the directory structure?

I didn't change a thing. It just a install-and-play version that has been working fine for a time, until my Windows update.

**Comment by NHLJang** [comment]
> CAOS Prime is a fork of StepMania, ask the creator.

Sorry. I know I should. I spent hours try to find a solution since I prefer to stick with the simple PRIME. But I don't know anything about the author, except the "CAOS" thing. Can you give me his/their contact page?

**Comment by shakesoda** [comment]
closed since this isn't anything we have control over. as for the problem, see if themes folder looks how you expect.

i'm not aware of any windows update having any effects on stepmania. if the theme is available and set in options it should work, assuming the files are all still there.
