### ISSUE TITLE
Distorted audio seemingly at random

### ISSUE THREAD

**Issue by TheDoctor40** [stepmania/stepmania#1891]
When using nightly build 173 from smnightly.katzepower.com/, audio will get distorted during a song, seemingly at random. Only way to fix it is by restarting stepmania completely, but even then when you are playing a song it will eventually be distorted again. It never happens at the same point in a song and up untill now it has only started happening when I was actively playing a song. Menus are fine untill a song distorts.

Don't know if this matters but I'm running Windows 10 pro build 1903.

**Comment by RhythmLunatic** [comment]
Please state the actual git commit your version is running on, it is usually shown in the title screen and logs 

But it may be an an audio driver issue. Does it happen on all audio devices?

**Comment by quietly-turning** [comment]
Downloaded "Stepmania Nightly Build 173" from http://smnightly.katzepower.com/, ran it using Wine with a modified SL just to get it to SystemMessage the build info at init.

```
StepMania 5.2-git-96f9771, Built 22 November 2017
```

<img width="966" alt="Screen Shot 2019-09-12 at 5 23 22 PM" src="https://user-images.githubusercontent.com/1253483/64822151-5fb9fd00-d582-11e9-8b6b-519d239bfc8a.png">

**Comment by RhythmLunatic** [comment]
>Built 22 November 2017

I think it's safe to say this issue might not be valid, or at least needs to be tested on a nightly that was compiled recently

**Comment by TheDoctor40** [comment]
Dang that would mean the website the wiki gives with nightly builds for Windows is quite out of date. That would make the latest beta release on GitHub newer. I'll close this thread. Unfortunately I've not been able yet to compile on windows. I'm gonna look into getting Linux running on my new laptop again.

**Comment by coderjo** [comment]
You probably want to use 5.1 builds, too. 5.2 is pretty much abandoned at this point.

**Comment by TheDoctor40** [comment]
It is? I guess I have not been paying attention to the developement too well then
