### ISSUE TITLE
Quick feature: reload song option in current song menu while playing

### ISSUE THREAD

**Issue by linuxtsunami** [stepmania/stepmania#1898]
Hi, 
In the menu when double-tapping on a song, can you please make it default to "reload song" instead of "restart song" ? When editing a song from outside stepmania (.sm), it would be really nice to reload the song and update the cache from disk as well.

Curently, I have to go back to main menu, then options, then reload songs, then it lost the song I was working on, then I have to find it back in the wheel, then I can restart it. Would save a lot of pain if one could just reload song (from disk!) directly from the song menu when within the song!

Thank you

**Comment by quietly-turning** [comment]
It is possible this feature already exists, but I am not sure what you are requesting based on what you wrote above.

If possible, can you clarify what you mean by 

 * double-tapping
 * reload song
 * restart song
 * editing a song from outside stepmania (.sm)
 * Curently

It is unclear where in StepMania you'd like this reloading feature to be accessible.  Are you playing StepMania?  Are you writing stepcharts in StepMania?  Are you developing for StepMania?  More context will help.

**Comment by RhythmLunatic** [comment]
The reload song shortcut is pressing Ctrl+Shift+R when hovering the song in the song select.

**Comment by quietly-turning** [comment]
Yes, that is the keyboard shortcut in most themes to reload a song from disk, creating new cache files in the process, while on ScreenSelectMusic.

**Comment by linuxtsunami** [comment]
Thanks for the quick reply.
Double-tapping: Hitting ESC twice while a song is playing (when hitting this key once, the word "double-tap [  ] to access menu" appears. When hitting it twice,this brings a mini-menu for that song.
In it, I see at the end of the options:
- Forfeit
- Restart Song

I'm talking about the restart song option, and I was thinking, if for any reason it is needed, can you ALSO add Reload song in this mini menu? I understand there might be shortcut keys, but I'd like to know this is accessible by the UI as well.

I don't want to have to exit the song. I would like to be able to hit "Reload Song" from the menu:
- Restart Song
- Reload song (from disk)
- Forfeit

And the Reload song would effectively call a reload of the song from disk and update the cache as well.

**Comment by linuxtsunami** [comment]
Are you playing StepMania? YES
Are you writing stepcharts in StepMania?  YES
Are you developing for StepMania? NOT YET, but I think this is super interesting

**Comment by linuxtsunami** [comment]
Nevermind, seems like Restart Song actually does a reload of the song from disk. Somehow it did not work when I had tried.
