### ISSUE TITLE
cdtitles broken (Invalid? Cannot reproduce)

### ISSUE THREAD

**Issue by RhythmLunatic** [stepmania/stepmania#1901]
Some information:
- Nightly version [c7f9133134](https://github.com/stepmania/stepmania/commit/c7f913313469e46f5bb2889156e9d94d51ddd940). Will test with latest nightly soon but it's unlikely anything significant has changed...
- HasCDTitle returns false.
- Tag is `#CDTITLE:./CDTITLES/DANCE DANCE REVOLUTION 3RD MIX.PNG;`
- Was working in SM 5.0.9

**Comment by RhythmLunatic** [comment]
After some discussion it seems like ./ is depreciated, but ../ is crashing the game right now and that probably shouldn't happen.

Unfortunately people STILL use ./ even for the latest and greatest simfiles...

**Comment by coderjo** [comment]
It seems to be working for me on 7ae3cfe99.

I am really curious about that crash on ../, though...

https://imgur.com/lcic8UJ

**Comment by RhythmLunatic** [comment]
This was reported to me by someone else and I couldn't be bothered to test it until now.
I tested the latest nightly and they appear to be working, so it's either invalid or something else is wrong.
Additionally ../ is working fine.

.sm or .ssc seems to have no difference.
