### ISSUE TITLE
The AppVeyor CI status badge is dysfunctional

### ISSUE THREAD

**Issue by Prcuvu** [stepmania/stepmania#1904]
Currently the AppVeyor badge is bound to https://ci.appveyor.com/project/wolfman2000/stepmania-wm87c, but the CI worker is actually https://ci.appveyor.com/project/Nickito12/stepmania, which is owned by a user who changed his username to [nico-abram](https://github.com/nico-abram), and moved to Etterna dev group.

What can we do to fix that? Can we contact those people and change the badge URL and/or webhook?

**Comment by nico-abram** [comment]
The CI was moved to me after/while I was already part of EDG, not before :P 

If it's what you're looking for, this is the URL for the badge under my appveyor account : https://ci.appveyor.com/api/projects/status/uvoplsnyoats81r2?svg=true

**Comment by Prcuvu** [comment]
Thank you. I will make a PR for README.md update.
