### ISSUE TITLE
Where can I disable "little" [half-note] globally

### ISSUE THREAD

**Issue by linuxtsunami** [stepmania/stepmania#1910]
Hi!

When playing I would like to disable the blue half-notes arrows, or what was previously called "little" in the old UI. I can't find it anywhere anymore...

Can I add/modify a parameter in ..../Save/Preferences.ini to disable "little" globally?

**Comment by ListenerJubatus** [comment]
"New UI"?

what branch? screenshots? I think we labelled it as "4th Notes Only"

**Comment by linuxtsunami** [comment]
I think the UI is called Lambda?

And where is the option **4th notes only** (to be able to globally disable)?

**Comment by linuxtsunami** [comment]
https://www.zwodnik.com/software/windows/stepmania, first screen shot, you can see the blue arrows

**Comment by linuxtsunami** [comment]
branch I use is 5.2-git-5dad6a1

**Comment by linuxtsunami** [comment]
Hi! So in case this is still not clear, what I'd like to know is where is this *"4th notes only"* (or any option that can remove these blue arrows) in:

a) the menu for a song while the song is playing?
b) the global stepmania config (options -> and then? )
c) in the stepmania config file (~/.stepmania-5.0/Save/Preferences.ini)

d) if it's not implemented, any idea about where in the code can I look for it?

Preferred would be to be able to turn it off globally.

Thank you!

**Comment by coderjo** [comment]
In that version and theme:

a) in the song options menu, go to Chart Mods, then Insertion Chart Mods, then Little.
c) set DefaultModifiers=Little in Save/Preferences.ini. There may be multiple DefaultModifiers lines, because there is the main Options section, and a section for each game type (dance, pump, etc)

**Comment by linuxtsunami** [comment]
Perfect! Thanks a lot
