### ISSUE TITLE
The game crashes when a song with a .lrc file with an unsupported tag is played

### ISSUE THREAD

**Issue by kiiriisame** [stepmania/stepmania#1930]
The .lrc file format used to display lyrics in stepmania supports a wide range of ID tags [see https://en.wikipedia.org/wiki/LRC_(file_format)].
However, many of these will be interpreted as a timestamp by stepmania, which causes the game the crash when attempting to use 
`seg.m_fStartTime = HHMMSSToSeconds(sValueName);`,
which calls
`StringToFloat()`
which calls the standard string to float
`std::stof()`
where an "invalid argument" exception is raised, causing the game to crash. This is not only a problem because it causes stepmania to be incompatible with a standard-compliant .lrc files, but the bigger problem is that this is likely a regression, as I've downloaded older song packs that used .lrc files containing ID tags, which thus couldn't be played without modifying the source code or the offending .lrc files.

I've fixed this issue myself by simply catching the exception, by adding a try block around the offending code:
```
			/* If we've gotten this far, and no other statement caught this
			 * value before this does, assume it's a time value. */

			LyricSegment seg;
			seg.m_Color = CurrentColor;
			try {
				seg.m_fStartTime = HHMMSSToSeconds(sValueName);
				seg.m_sLyric = sValueData;

				seg.m_sLyric.Replace( "|","\n" ); // Pipe symbols denote a new line in LRC files
				out.AddLyricSegment( seg );
			}
			catch (const std::invalid_argument& e){
				// It does not matter if a lyric segment cannot be displayed, so we can ignore this exception
			}
```
but I realize that the rest of the code does not use many try blocks, and that this may be a case of using exceptions as flow control. However, I am not comfortable enough in C++ to write a better fix, hence I've posted this issue.

**Comment by RhythmLunatic** [comment]
Isn't that what this PR is for?
https://github.com/stepmania/stepmania/pull/1923

**Comment by kiiriisame** [comment]
That's definitely it, sorry for creating a duplicate issue.
