### ISSUE TITLE
AYUDA!!!!!

### ISSUE THREAD

**Issue by KIKE-BL** [stepmania/stepmania#1938]
Cuando quiero sincronizar el juego con la música, me saca del programa
¿Porqué no me deja sincronizarlo?
ayuda por favor

**Comment by ghost** [comment]
¿Qué sistema operativo estás usando? ¿Qué versión de eso está instalada? ¿Sus controladores están actualizados?

**Comment by KIKE-BL** [comment]
> ¿Qué sistema operativo estás usando? ¿Qué versión de eso está instalada? ¿Sus administradores están actualizados?

Tengo windows 10, tengo la version 1.06, ¿Cómo veo si están actualizados? , yo creo que si están actualizados
