### ISSUE TITLE
How to build/run the latest commits for/on Windows 7 (missing DLL files)?

### ISSUE THREAD

**Issue by ghost** [stepmania/stepmania#1948]
Are there any other SDKs/redistributables required for running the newest changes on Windows 7?

Stepmania Version: 5.1-latest git commit at this point in time plus a few custom patches. Runs without issues on Build Host.
Build Host: Windows 10 x64, VS 2019
Target PC: Windows 7 x86. Installed the linked redist from README, as well as 2019 and all required MSU packages.

First I get

```
---------------------------
StepMania.exe - System Error
---------------------------
The program can't start because XINPUT1_4.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------
```

which is easily solved (but still points to some sort of missing dependency), but then I get a massive list of errors like these
```
---------------------------
StepMania.exe - System Error
---------------------------
The program can't start because api-ms-win-eventing-classicprovider-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------
```
, all files starting with "api-ms-XXX.dll"

**Comment by RhythmLunatic** [comment]
You cannot compile StepMania on VS2019. 2015 only.

**Comment by RhythmLunatic** [comment]
I'm not sure how you successfully compiled it on VS2019 considering it produces compiler errors, but do you have DirectX redistributable and c++ redistributable installed?

**Comment by ghost** [comment]
Yeah, I do, and everything worked fine before I pulled the changes between today and 75d9400cb0.

Also that's ... interesting. I remember building with VS2019 without issues for a long time. Didn't do anything special.

![](https://puu.sh/ETMWn.png)

**Comment by coderjo** [comment]
Does it work if you build with platform toolset v142_xp? (is that even an option? I don't have 2019 installed currently). You'll probably need to regenerate the project files with cmake.

XINPUT should be covered by the DirectX runtime, I think. The others sound like missing bits of other runtimes. Perhaps coming from our prebuilt ffmpeg or something?

**Comment by ghost** [comment]
v142_xp was not a thing for me, but v140_xp was, and that solved the missing api-win-XXX.dll and api-ms-core-XXX.dll issues, thanks!

For anyone else running into this issue, set your cmake configuration to this:
<img width="250" alt="cmake-gui_2019-12-28_16-38-54" src="https://user-images.githubusercontent.com/1176191/71546305-d1814f80-2995-11ea-818b-b190a2f90e96.png">



XINPUT1_4 is apparently only a thing on Windows 10, the version for Windows 7 is XINPUT1_3, see: https://docs.microsoft.com/en-us/windows/win32/xinput/xinput-versions
While copying 1_4 over from my Windows 10 machine let me launch SM, I can't test if Xinput devices actually work on that machine as my pad and control buttons identify as keyboards.

**Comment by coderjo** [comment]
Does v140 alone work then? I think it should, since I think the _xp part allows build outputs to run on XP. It could be the v142 toolset dropped win7 support? (I don't have 2019 installed nor do I have win7 handy to test on)

**Comment by ghost** [comment]
No, regular v140 does not work and throws the same errors.
Here's a dependency walker side-by-side:

Left: v140, Right: v140_xp
<img width="959" alt="mstsc_2019-12-29_13-04-02" src="https://user-images.githubusercontent.com/1176191/71556697-e9131380-2a3b-11ea-98b3-b6537b686aaa.png">

**Comment by coderjo** [comment]
I wonder what specifically is pulling those in. And whether MS changed something, since v140 is SUPPOSED to be able to run on vista on up (if I remember correctly).

**Comment by Prcuvu** [comment]
@mario182 @coderjo You may want to try my fix.
I would like to see what DLL it will link to with `v140_xp`/`v141_xp` toolset.

Edit: `v141_xp` links to `XInput9_1_0.dll`.

**Comment by ghost** [comment]
Yes, fixed.
v140_xp also links to XInput9_1_0.dll.

**Comment by Prcuvu** [comment]
Seems like the Windows XP toolsets use Windows SDK 7.1A, a miniature version of Windows SDK 7.1.
