### ISSUE TITLE
Certain F-Keys Randomly Stopped Working

### ISSUE THREAD

**Issue by JoshsoJB** [stepmania/stepmania#1979]
I booted up StepMania yesterday and found that some of the F-keys weren't responding at all. It's really weird because I didn't make any changes to anything beyond deleting and moving around songs in folders like I usually do before that. It's not my keyboard because I had the same problem with another one I tried. I can't toggle back up difficulties after going down using F6 in Edit Mode, enable AutoPlay on the fly using F8, and some of the sync quick-fix keys (F9 - F12) aren't working either.

**Comment by tertu-m** [comment]
What version of StepMania are you using?

**Comment by JoshsoJB** [comment]
It was a weird momentary thing. Everything working now.
