### ISSUE TITLE
Announcer 'evaluation' sounds are incorrect for default theme in 5.1

### ISSUE THREAD

**Issue by richardloxley** [stepmania/stepmania#2005]
When using an announcer pack, the sounds that are played at the end of the song are taken from directories named 'evaluation a', 'evaluation b', etc - 8 directories for the 7 possible grades (plus fail).  These correspond to the possible grades in older versions of StepMania.

StepMania 5.1 allows up to 20 grade tiers (dependent on the theme).  The evaluation screen attempts to reconcile this by calling the function GradeToOldString() to convert a modern tier to an old-style grade, and then play the appropriate sound.

However GradeToOldString() only maps the first 7 tiers (plus fail) to the 8 announcer directories.

The default theme for StepMania 5.1 has 17 tiers (plus fail), so you only get an announcer sound if you get one of those top 7 grades (grade A and above) - and they are therefore the wrong sound, such that you get the sound for a bad grade for an A.

This will happen for any theme that doesn't have exactly 7 grades.

There is also a related issue for playing the cheer sound for the top three tiers, which should probably be expanded for themes using more than 7 tiers.

I have coded and tested a simple fix for this, which changes GradeToOldString() to evenly distribute the grades actually used by the theme across the available "old" grades for the announcer directories.

Is it worth submitting a pull-request to this 5.1 repository?  The last release was 2 years ago, and it looks like all the work is on the Project Moondance 5.3 fork.  That doesn't seem to be open source yet though.  Is this branch a dead-end?

**Comment by quietly-turning** [comment]
Thanks for asking about this.

---

> Is it worth submitting a pull-request to this 5.1 repository?

Pull requests are still being submitted StepMania's `5_1-new` branch in 2020.  A handful of remaining project maintainers are doing what we can to merge where we are able to.  

See:  https://github.com/stepmania/stepmania/pulls?q=is%3Apr+created%3A%3E2019+

If you (or, anyone else reading this) submit a pull request to `5_1-new` and you make some effort to explain:

* what problem the pull request is addressing
* how the code changes address the problem, and
* how players (or in some cases, content creators like themers) can expect to interact with it

then, generally, someone here will work with you to merge it, or at least discuss it.

---

> The last release was 2 years ago [...]  Is this branch a dead-end?

I wrote some of my thoughts regarding a formal 5.1 release here: https://github.com/stepmania/stepmania/issues/1914#issuecomment-629930711

I'd personally like there to be a formal SM5.1 release, but there are currently showstoppers with macOS, and the overall planning needed for a formal release is more than I can commit to, alone.
