### ISSUE TITLE
Unlock System Not Working On 5.0.12

### ISSUE THREAD

**Issue by PichuBoy000** [stepmania/stepmania#2010]
I have tried to get the unlock system to work, but I have been unable to get it to work.

I have done several different things and read the Stepmania Wiki's article on the Unlock System on GitHub, but no matter what I did, the unlock system would never be available.

If there is any way to fix this, that would be great.

Here is the code just incase if it is needed.

metrics.ini
--------------------------------------------------------------------------------------------
`[UnlockManager]
AutoLockChallengeSteps=false
UnlockNames="1,2"
Unlock1Command=song,"Danger! High Voltage";require,"UnlockRequirement_StagesCleared",2
Unlock2Command=song,"Tough Enough";require,"UnlockRequirement_ArcadePoints",8000`

Folder: ScreenSelectMusic in
default.lua
--------------------------------------------------------------------------------------------
`if (PROFILEMAN:GetProfile(PLAYER_1):GetNumTotalSongsPlayed() >= 2)
or (PROFILEMAN:GetProfile(PLAYER_2):GetNumTotalSongsPlayed() >= 2) 
then
	UNLOCKMAN:UnlockEntryID('1')
else
	UNLOCKMAN:LockEntryID('1')
end`

**Comment by concubidated** [comment]
First issue I see is, I am pretty certain you need to include the group of your song. For example

`Unlock2Command=song,"In The Groove/Tough Enough";require,"UnlockRequirement_ArcadePoints",8000`

**Comment by PichuBoy000** [comment]
I have fixed the folder issue, but I still cannot use the unlock system and the songs still show up.
It might be because of an error on default.lua.

**Comment by quietly-turning** [comment]
I tested this on a current build of SM5.1 in the default theme's metrics.ini:

```ini
[UnlockManager]
UnlockNames="1"
Unlock1Command=song,"StepMania 5/Goin' Under"
```

*Goin' Under* was locked correctly.

Check to make sure you have the Unlock System enabled.  You can set `UseUnlockSystem=1` in your [Preferences.ini file](https://github.com/stepmania/stepmania/wiki/Manually-Changing-Preferences) or use the UI in your theme – it's usually found under *Advanced Options* in most themes.

![Screen Shot 2020-06-10 at 3 24 41 AM](https://user-images.githubusercontent.com/1253483/84239617-c563f700-aaca-11ea-8e82-2f398afa37bb.png)

**Comment by PichuBoy000** [comment]
I have turned on the unlock system, It did not work.
I have looked into the Preferences.ini file and set `UseUnlockSystem=` to 1 or true, and it worked.

I have also used the longer code documented in the Unlock System page on the wiki to have multiple unlocks, It actually worked.

Thank you for your help guys. :)

**Comment by quietly-turning** [comment]
Glad to hear you were able to work it out! 🙂
