### ISSUE TITLE
Need to configure stepmania as "show all songs" without grouping

### ISSUE THREAD

**Issue by g3nsvrv** [stepmania/stepmania#2022]
I don't want to put every song in one folder, I rater prefer to show them all in stepmania by default.

**Comment by RhythmLunatic** [comment]
It should be in settings, the value is called MusicWheelUsesSections

**Comment by g3nsvrv** [comment]
I saw three values for this but none of them permit to show all the songs, and actually the only thing that I saw is that option made stepmania to not showing the groups but is still sorted in groups, and the only way to change groups again is using the left and right together: e.g.

MusicWheelUsesSections=Always
group1: songs
group2: songs
etc

MusicWheelUsesSections=Never
group1 (hidden): songs
group2 (hidden): songs
etc

```
MusicWheelUsesSections
ALWAYS means sections in group + ABC
NEVER means no sections;
ABC ONLY shows sections in just ABC sort.
```

**Comment by g3nsvrv** [comment]
BTw, stepmania has a default group that is called "preferred" where it shows all the songs but I havent figured out yer how to select by default

**Comment by g3nsvrv** [comment]
## MusicWheelUsesSections=Always
![ALWAYS](https://user-images.githubusercontent.com/11720535/85213350-3e651900-b32b-11ea-9730-5a81b202e374.png)


## MusicWheelUsesSections=TitleMusic (ABC ONLY)
![TITLEMUSIC](https://user-images.githubusercontent.com/11720535/85213355-491fae00-b32b-11ea-991a-e05141e4d2d3.png)


## MusicWheelUsesSections=Never
![NEVER](https://user-images.githubusercontent.com/11720535/85213359-4c1a9e80-b32b-11ea-8461-3387094d8250.png)

**Comment by g3nsvrv** [comment]
## Using group=preferred it show all the songs
![image](https://user-images.githubusercontent.com/11720535/85213370-6fdde480-b32b-11ea-9d98-aae1f866aa19.png)

**Comment by RhythmLunatic** [comment]
In metrics.ini
Under [ScreenSelectMusic]
DefaultSort="Preferred"

**Comment by g3nsvrv** [comment]
yeah, I was looking at that, I tried to use the same setting but it didn't work :c, but I think could be just that... a theming thing...

https://github.com/stepmania/stepmania/wiki/Preferred-Sort#metrics-way

### Previously:
DefaultSort=GAMESTATE:IsCourseMode() and "Group" or "AllCourses"

### Now
DefaultSort="Preferred"

**Comment by RhythmLunatic** [comment]
Make sure you reload metrics after setting (Shift+F2 or restart game)
Also I have no idea why but there is also DefaultSort under [GameState], try setting that too

**Comment by g3nsvrv** [comment]
Is empty... I gonna try to configure there instead

**Comment by g3nsvrv** [comment]
That made the trick!!!!! Thanks @RhythmLunatic <3 much appreciated.

I kept the same:

```
[ScreenSelectMusic]
DefaultSort=GAMESTATE:IsCourseMode() and "Group" or "AllCourses"
```

But I configured the GameState instead:

```
[GameState]
DefaultSort="Preferred"
```

**Comment by quietly-turning** [comment]
Thanks for your help here, @RhythmLunatic!
