### ISSUE TITLE
StepMania crashing 

### ISSUE THREAD

**Issue by Akio91** [stepmania/stepmania#2024]
I'm using WIndows 10 and it was working fine last week.  I think it might have something to do with themes, but not sure.  Posting error log below.  Crashinfo is below that.  Any assistance would be appreciated.  

00:00.027: StepMania5.0.12
00:00.027: Compiled 20160811 @ 00:34:46 (build 45e0787)
00:00.027: Log starting 2020-06-24 09:43:09
00:00.027:  
00:00.027: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.028: Reading 'Save/Preferences.ini' failed: No such file or directory
00:00.028: Reading 'Save/Preferences.ini' failed: No such file or directory
00:00.028: Reading 'Data/Static.ini' failed: No such file or directory
00:00.295: Loading window: win32
00:00.295: Windows 6.2 (Win8) build 9200 []
00:00.295: Memory: 2047mb total, 4095mb swap (3704mb swap avail)
00:00.296: Video driver: Radeon(TM) RX 550 [Advanced Micro Devices, Inc.]
00:00.296:               26.20.14038.2009, 4-2-2020 [pci\ven_1002&dev_699f&subsys_8424103c&rev_c7]
00:00.317: Drive: "        ST1000DM003-1SB1HPH4" Driver: storahci DMA: N/A
00:00.318: Drive: "hp PLDS DVDRW  DU8AESH  6HSM" Driver: storahci DMA: N/A
00:00.354: Sound device 0: 4 - LG TV (2- AMD High Definiti, 10.0, MID 1, PID 100 
00:00.354: Memory changed from 0 to 2047; settings changed
00:00.385: Reading 'Data/Static.ini' failed: No such file or directory
/////////////////////////////////////////
00:00.386: WARNING: Selected theme '_fallback' not found.  Trying Theme preference default value '_fallback'.
/////////////////////////////////////////
/////////////////////////////////////////
00:00.386: WARNING: Theme preference defaults to '_fallback', which cannot be used.  Trying DefaultTheme preference 'default'.
/////////////////////////////////////////
00:00.386: ThemeManager::SwitchThemeAndLanguage: "default", "en"
00:00.408: Loading "/Scripts/32log.lua" ...
00:00.409: Loading "/Scripts/extend_table.lua" ...
00:00.409: Loading "/Scripts/unavailable_functions.lua" ...
00:00.409: Loading "/Scripts/32log.lua" ...
00:00.409: Loading "/Scripts/extend_table.lua" ...
00:00.409: Loading "/Scripts/unavailable_functions.lua" ...
00:00.410: Loading "/Themes/_fallback/Scripts/00 init.lua" ...
00:00.410: Loading "/Themes/_fallback/Scripts/01 alias.lua" ...
00:00.411: Loading "/Themes/_fallback/Scripts/01 base.lua" ...
00:00.411: Loading "/Themes/_fallback/Scripts/01 IniFile.lua" ...
00:00.412: Loading "/Themes/_fallback/Scripts/02 Actor.lua" ...
00:00.413: Loading "/Themes/_fallback/Scripts/02 ActorDef.lua" ...
00:00.413: Loading "/Themes/_fallback/Scripts/02 Branches.lua" ...
00:00.414: Loading "/Themes/_fallback/Scripts/02 Colors.lua" ...
00:00.414: Loading "/Themes/_fallback/Scripts/02 Debug.lua" ...
00:00.415: Loading "/Themes/_fallback/Scripts/02 Enum.lua" ...
00:00.415: Loading "/Themes/_fallback/Scripts/02 OptionsMenu.lua" ...
00:00.415: Loading "/Themes/_fallback/Scripts/02 Other.lua" ...
00:00.415: Loading "/Themes/_fallback/Scripts/02 Serialize.lua" ...
00:00.416: Loading "/Themes/_fallback/Scripts/02 Sprite.lua" ...
00:00.416: Loading "/Themes/_fallback/Scripts/02 StageMods.lua" ...
00:00.416: Loading "/Themes/_fallback/Scripts/02 ThemePrefs.lua" ...
00:00.416: Loading "/Themes/_fallback/Scripts/02 ThemePrefsRows.lua" ...
00:00.417: Loading "/Themes/_fallback/Scripts/02 Utilities.lua" ...
00:00.418: Loading "/Themes/_fallback/Scripts/03 CustomSpeedMods.lua" ...
00:00.419: Loading "/Themes/_fallback/Scripts/03 Gameplay.lua" ...
00:00.419: Loading "/Themes/_fallback/Scripts/03 GamePreferences.lua" ...
00:00.420: Loading "/Themes/_fallback/Scripts/03 ThemeAndGamePrefs.lua" ...
00:00.420: Loading "/Themes/_fallback/Scripts/03 ThemeLibrary.lua" ...
00:00.420: Loading "/Themes/_fallback/Scripts/03 UserPreferences2.lua" ...
00:00.421: Reading 'Themes/_fallback/ThemeInfo.ini' failed: No such file or directory
00:00.421: Loading "/Themes/_fallback/Scripts/04 CreditsHelpers.lua" ...
00:00.423: Loading "/Themes/_fallback/Scripts/04 LogDisplay.lua" ...
00:00.424: Loading "/Themes/_fallback/Scripts/04 NumPadEntry.lua" ...
00:00.425: Loading "/Themes/_fallback/Scripts/04 pause_menu_helper.lua" ...
00:00.425: Loading "/Themes/_fallback/Scripts/04 SetBGFitHelpers.lua" ...
00:00.425: Loading "/Themes/_fallback/Scripts/find_missing_lang_strings.lua" ...
00:00.426: Loading "/Themes/default/Scripts/00 ThemeInfo.lua" ...
00:00.426: Loading "/Themes/default/Scripts/02 Colors.lua" ...
00:00.426: Loading "/Themes/default/Scripts/02 Lyrics.lua" ...
00:00.426: Loading "/Themes/default/Scripts/02 TextBanner.lua" ...
00:00.426: Loading "/Themes/default/Scripts/02 ThemePrefs.lua" ...
00:00.427: ThemePrefs.InitAll( prefs )
00:00.427: ThemePrefs.Init: loading from disk
00:00.427: IniFile.ReadFile( Save/ThemePrefs.ini )
/////////////////////////////////////////
00:00.427: WARNING: ReadFile(Save/ThemePrefs.ini): No such file or directory
/////////////////////////////////////////
00:00.427: NotePosition doesn't exist, creating
00:00.427: GameplayFooter doesn't exist, creating
00:00.427: TimingDisplay doesn't exist, creating
00:00.427: GameplayShowScore doesn't exist, creating
00:00.427: ShowLotsaOptions doesn't exist, creating
00:00.427: FlashyCombo doesn't exist, creating
00:00.427: AutoSetStyle doesn't exist, creating
00:00.427: ComboOnRolls doesn't exist, creating
00:00.427: LongFail doesn't exist, creating
00:00.427: GameplayShowStepsDisplay doesn't exist, creating
00:00.427: FancyUIBG doesn't exist, creating
00:00.427: ComboUnderField doesn't exist, creating
00:00.427: Loading "/Themes/default/Scripts/03 Gameplay.lua" ...
00:00.427: Loading "/Themes/default/Scripts/04 Other.lua" ...
00:00.730: WaveOut software mixing at 44100 hz
00:00.730: Starting thread: Decode thread
00:00.730: Starting thread: Mixer thread
00:00.730: Sound driver: WaveOut
00:00.730: Starting thread: Music thread
00:00.731: Initializing lights drivers: SystemMessage,Export
00:00.731: Lights driver: SystemMessage
00:00.731: Lights driver: Export
00:00.731: ThemeManager::SwitchThemeAndLanguage: "default", "en"
00:00.731: Reading 'Save/Keymaps.ini' failed: No such file or directory
00:00.731: Couldn't open mapping file "Save/Keymaps.ini": No such file or directory.
00:00.731: Reading 'Save/Keymaps.ini' failed: No such file or directory
00:00.731: Couldn't open mapping file "Save/Keymaps.ini": No such file or directory.
00:00.731: Reading 'Cache/index.cache' failed: No such file or directory
00:00.731: Cache format is out of date.  Deleting all cache files.
00:00.732: Reading 'Cache/banners.cache' failed: No such file or directory
00:00.733: Attempting to load 3 songs from "Songs/StepMania 5"
00:01.166: Song::SaveToSSCFile('Cache/Songs/Songs_StepMania 5_Goin' Under')
00:01.208: Song::SaveToSSCFile('Cache/Songs/Songs_StepMania 5_MechaTribe Assault')
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "0003"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "0300"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "0300"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "3000"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "3000"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "0300"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "3000"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "0300"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "0003"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "0030"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "0003"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "0030"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "1003"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "0031"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "0310"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "0003"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "0030"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "0003"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "0030"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "0300"
/////////////////////////////////////////
/////////////////////////////////////////
00:01.251: WARNING: Unmatched 3 in "0003"
/////////////////////////////////////////
00:01.260: Song::SaveToSSCFile('Cache/Songs/Songs_StepMania 5_Springtime')
00:01.320: Loaded 3 songs from "Songs/StepMania 5"
00:01.329: Found 3 songs in 0.597000 seconds.
00:01.329: Loading courses.
00:01.330: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/ChallengingRandom5.crs")
00:01.411: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/Jupiter.crs")
00:01.413: Course file "/Courses/Default/Jupiter.crs" contains an invalid #METER string: "Medium"
00:01.449: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_01-04.crs")
00:01.487: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_05-08.crs")
00:01.487: Course file "/Courses/Default/MostPlayed_05-08.crs" is trying to load BEST4 with only 3 songs installed. This entry will be ignored.
00:01.487: Course file "/Courses/Default/MostPlayed_05-08.crs" is trying to load BEST5 with only 3 songs installed. This entry will be ignored.
00:01.487: Course file "/Courses/Default/MostPlayed_05-08.crs" is trying to load BEST6 with only 3 songs installed. This entry will be ignored.
00:01.487: Course file "/Courses/Default/MostPlayed_05-08.crs" is trying to load BEST7 with only 3 songs installed. This entry will be ignored.
00:01.487: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_09-12.crs")
00:01.487: Course file "/Courses/Default/MostPlayed_09-12.crs" is trying to load BEST8 with only 3 songs installed. This entry will be ignored.
00:01.487: Course file "/Courses/Default/MostPlayed_09-12.crs" is trying to load BEST9 with only 3 songs installed. This entry will be ignored.
00:01.487: Course file "/Courses/Default/MostPlayed_09-12.crs" is trying to load BEST10 with only 3 songs installed. This entry will be ignored.
00:01.487: Course file "/Courses/Default/MostPlayed_09-12.crs" is trying to load BEST11 with only 3 songs installed. This entry will be ignored.
00:01.487: CourseLoaderCRS::LoadFromCRSFile("/Courses/Default/MostPlayed_13-16.crs")
00:01.488: Course file "/Courses/Default/MostPlayed_13-16.crs" is trying to load BEST12 with only 3 songs installed. This entry will be ignored.
00:01.488: Course file "/Courses/Default/MostPlayed_13-16.crs" is trying to load BEST13 with only 3 songs installed. This entry will be ignored.
00:01.488: Course file "/Courses/Default/MostPlayed_13-16.crs" is trying to load BEST14 with only 3 songs installed. This entry will be ignored.
00:01.488: Course file "/Courses/Default/MostPlayed_13-16.crs" is trying to load BEST15 with only 3 songs installed. This entry will be ignored.
00:01.491: Starting thread: Worker thread (MemoryCardWorker)
00:01.493: RageSound: Load "/Themes/_fallback/Sounds/MemoryCardManager ready.ogg" (precache: 1)
00:01.498: RageSound: Load "/Themes/_fallback/Sounds/_missing.ogg" (precache: 1)
00:01.510: RageSound: Load "/Themes/_fallback/Sounds/_missing.ogg" (precache: 1)
00:01.510: RageSound: Load "/Themes/_fallback/Sounds/MemoryCardManager disconnect.ogg" (precache: 1)
00:01.516: Starting thread: Worker thread (/@mc1int/)
00:01.516: Starting thread: Worker thread (/@mc2int/)
00:01.516: Profile::LoadAllFromDir( /Save/MachineProfile/ )
00:01.909: SaveStatsXmlToDir: /Save/MachineProfile/
00:01.967: C:\Repos\wolfmania\src\RageFileDriverDirect.cpp:156: remove 'C:/Users/Harvey/AppData/Roaming/StepMania 5/Save/MachineProfile/Edits/newdir.temp.newdir'
00:02.029: C:\Repos\wolfmania\src\RageFileDriverDirect.cpp:156: remove 'C:/Users/Harvey/AppData/Roaming/StepMania 5/Save/MachineProfile/EditCourses/newdir.temp.newdir'
00:02.059: C:\Repos\wolfmania\src\RageFileDriverDirect.cpp:156: remove 'C:/Users/Harvey/AppData/Roaming/StepMania 5/Save/MachineProfile/Screenshots/newdir.temp.newdir'
00:02.098: C:\Repos\wolfmania\src\RageFileDriverDirect.cpp:156: remove 'C:/Users/Harvey/AppData/Roaming/StepMania 5/Save/MachineProfile/Rivals/newdir.temp.newdir'
00:02.099: UnlockManager::Load()
00:02.111: Last seen video driver: 
00:02.111: Card matches 'GeForce|Radeon|Wonder 9|Quadro'.
00:02.111: Applying defaults for Radeon(TM) RX 550.
00:02.111: Video renderers: 'opengl,d3d'

[crashinfo.txt](https://github.com/stepmania/stepmania/files/4826153/crashinfo.txt)

**Comment by geefr** [comment]
I'm not expert on the windows side of things but looks like a resource/memory issue in the renderer/window management stuff, wouldn't be surprised if it's graphics driver-specific, so couple easy things to try:
1: Try stepmania 5.1, that's what folks are putting fixes into
2: Check for updated graphics drivers - straight from the manufacturer's site as the bundled ones provided by windows can be a bit naff

**Comment by Akio91** [comment]
I greatly appreciate the timely reply.  I've tried 5.1 and Outfox and they both crash on startup.  I'm going to look into the drivers now.

**Comment by Akio91** [comment]
OH MY GOD YOU'RE A GENIUS!!!!  My AMD Radeon RX Vega 8 etc etc  was malfunctioning in device manager so I grabbed an update like you said and I'm good to go.  Thank you so much, I greatly appreciate it!!
