### ISSUE TITLE
The courses that come with StepMania have a typo

### ISSUE THREAD

**Issue by RhythmLunatic** [stepmania/stepmania#2032]
I was looking into forced noteskins for courses since the code is still in the game but it's not functioning and I noticed that the courses that come with the game aren't writing their modifiers to cache.
` #SONG:StepMania 5\Springtime:Medium;nodifficult;` is supposed to be ` #SONG:StepMania 5\Springtime:Medium:nodifficult;`, you'll notice after changing `;` to `:` the modifiers will get written to cache and it will generate easier trails.
https://github.com/stepmania/stepmania/blob/5_1-new/Courses/Default/Jupiter.crs

I'm not sure if it really matters, but it is interesting that nobody noticed it until now.
Side note: Maybe there should be a PR that adds more example courses to better demonstrate the course generation system such as picking by level, modifiers, and anything else the course system supports.

**Comment by RhythmLunatic** [comment]
You know what, I'll do the PR myself.
I'm guessing people don't want a bunch of example courses clogging up the Course folder so I'll put them in Docs or something.

**Comment by quietly-turning** [comment]
Thanks for spotting this and offering to improve the existing documentation.  🙂  Feel free to copy/paste any of the prose from https://github.com/stepmania/stepmania/pull/1738#issuecomment-641626611 if it helps.

**Comment by quietly-turning** [comment]
Resolved by #2033.
