### ISSUE TITLE
Forced noteskin not functioning in courses

### ISSUE THREAD

**Issue by RhythmLunatic** [stepmania/stepmania#2034]
Forced noteskins does not work for some reason in courses despite all the code supporting it.
It seems like there's some kind of misbehaving code because I'm running it through the debugger and it's still assigning the notefield correctly. So:
- CacheAllUsedNoteSkins() still functions correctly and correctly caches the forced noteskin.
- [ensure_note_displays_have_skin()](https://github.com/stepmania/stepmania/blob/5_1-new/src/NoteField.cpp#L259-L278) is working as intended, it's assigning the forced noteskin to the player as it should. I added `LOG->Trace("Assigned NoteSkin %s to %s",it->first.c_str(),PlayerNumberToString(m_pPlayerState->m_PlayerNumber).c_str());` to make sure.

My guess is that it's reading from `m_pCurDisplay` when it should be reading from `m_pDisplays[pn]`. I can't even tell which one is supposed to be used and which isn't or why there's two of them. `m_pCurDisplay` does not have the forced noteskin though.

Also it's assigning it twice per song. It's not ordered either, sometimes the forced noteskin is assigned before the player's noteskin which would break it anyways even if it did work. It's extremely bizzare behavior.

From my logs... delta is supposed to be forced:
```
Assigned NoteSkin delta to P1
Assigned NoteSkin default to P1
Assigned NoteSkin cmd to P2
Assigned NoteSkin delta to P2
```

**Comment by RhythmLunatic** [comment]
Since this feature was supposed to be removed a long time ago, here's the hackjob fix to get it working again in your fork if you really really care.

Paste under [Line 278](https://github.com/stepmania/stepmania/blob/5_1-new/src/NoteField.cpp#L278). Good luck finding the real fix.
```cpp
//Hack to fix forced noteskins in courses
//This wastes CPU so don't try it -RL
if (GAMESTATE->IsCourseMode())
{
	FOREACH_CONST( TrailEntry, GAMESTATE->m_pCurTrail[pn]->m_vEntries, e )
	{
		PlayerOptions po;
		po.FromString( e->Modifiers );
		if( !po.m_sNoteSkin.empty() )
		{
			sNoteSkinLower = po.m_sNoteSkin;
			sNoteSkinLower.MakeLower();
			it = m_NoteDisplays.find( sNoteSkinLower );
			m_pCurDisplay = it->second; //Assign the forced noteskin
			break;
		}
	}
}
```

**Comment by quietly-turning** [comment]
Thanks for looking into this and documenting some of the process and work here.  It is appreciated. 👍 

It's helpful to have issue threads like this to link to in the future if anyone else wants to work on it.
