### ISSUE TITLE
Stepmania crashes upon launch

### ISSUE THREAD

**Issue by galatixa** [stepmania/stepmania#2038]
I recently had problems with step mania and crashes upon launch and get this error code. 
for some reason even etterna is experiencing the same problem 

StepMania5.0.12 crash report (build 45e0787, 20160811 @ 00:34:46)
--------------------------------------

Crash reason: DeviceIoControl (The device is not connected.)

Thread: Main thread
        RageFileDriverDirectHelpers.cpp:230 C:/Games/StepMania 5/Save/*
        IniFile.cpp:21 Reading 'Save/Keymaps.ini'
        IniFile.cpp:21 Reading 'Save/Keymaps.ini'
        IniFile.cpp:21 Reading 'Cache/index.cache'
        RageFileDriverDirectHelpers.cpp:230 C:/Users/carlo/AppData/Roaming/StepMania 5/Cache/*
Thread: Decode thread
Thread: Mixer thread
        RageSoundDriver_WDMKS.cpp:1188 DeviceIoControl (The device is not connected.)
Thread: Music thread
0103e76f: StepMania!00c40000
00cd5b4d: StepMania!00c40000
00e41e40: StepMania!00c40000
00e43c67: StepMania!00c40000
00e41e5b: StepMania!00c40000
773a7bf4: ntdll!RtlGetAppContainerNamedObjectPath [77340000+67b40+b4]

Static log:
StepMania5.0.12
Compiled 20160811 @ 00:34:46 (build 45e0787)
Log starting 2020-07-14 22:26:38
Loading window: win32
Windows 6.2 (Win8) build 9200 []
Memory: 2047mb total, 4095mb swap (4095mb swap avail)
Video driver: Radeon(TM) RX 580 [Advanced Micro Devices, Inc.]
              26.20.14038.2009, 4-2-2020 [pci\ven_1002&dev_67df&subsys_83c2103c&rev_c3]
Drive: "        ST1000DM003-1SB1HPH4" Driver: storahci DMA: N/A
Drive: "hp PLDS DVDRW  DU8AESH  6HSM" Driver: storahci DMA: N/A
Couldn't load driver WaveOut: waveOutOpen failed(A device ID has been used that is out of range for your system.)
Couldn't load driver DirectSound-sw: DirectSoundCreate (DSERR_NODRIVER)
KS: chunk size: 256; allocator framing: 0 (0ms)
KS: 8000 hz
Sound driver: WDMKS
Lights driver: SystemMessage
Lights driver: Export
Language: en
Theme: default

Partial log:
00:02.098: KS: chunk size: 256; allocator framing: 0 (0ms)
00:02.098: KS: 8000 hz
00:02.098: Starting thread: Decode thread
00:02.098: Starting thread: Mixer thread
00:02.098: Sound driver: WDMKS
00:02.098: Starting thread: Music thread
00:02.098: Initializing lights drivers: SystemMessage,Export
00:02.098: Lights driver: SystemMessage
00:02.098: Lights driver: Export
00:02.099: ThemeManager::SwitchThemeAndLanguage: "default", "en"

-- End of report

**Comment by geefr** [comment]
'RageSoundDriver_WDMKS.cpp:1188 DeviceIoControl (The device is not connected.)'

Looks like the crashing thread was doing something with sound devices, so is there something weird in your setup?
Assuming windows from the filepaths but what's the system specs?

Do you have some uncommon sound device, do you have up to date drivers for the sound card? have you tried say using audio over hdmi instead of line out? Things like that.

If the bug happens with sm and etterna probably just means it's a rare/old bug that was there before the fork.

**Comment by coderjo** [comment]
> Assuming windows from the filepaths but what's the system specs?

Looks like Windows 8. 

The errors on multiple sound APIs (waveOut, DSound, WDMKS) make it seem like there are no usable sound devices on the system.

**Comment by galatixa** [comment]
Im using windows 10
 How can i access my specs?

**Comment by geefr** [comment]
@galatixa  This looks pretty good if you're not familiar with things: https://www.ccleaner.com/speccy

Main thing is probably to open device manager (start, type 'device manager') and see what sound devices you've got, usually there would be some on board sound card, and if things are setup right the graphics card should provide one for HDMI audio.

Does sound work in general? I take it you can you listen to music on the system? Seems like a silly question but you'll need to help us work this out, seems like it's specific to your system and we've got no idea what that is ;)

**Comment by galatixa** [comment]
Yes, sounds does work. Its weird but after i updated windows it seemed to work. o.o 
I appreciate the help.
