### ISSUE TITLE
Severed display corruption on Intel 620

### ISSUE THREAD

**Issue by Chaz6** [stepmania/stepmania#2039]
I installed Stepmania 5.3 Alpha 4.6 RC3 and this is the result when it runs:-

![image](https://user-images.githubusercontent.com/12680/87857201-c7687380-c91c-11ea-8da1-e6251a596540.png)

Please let me know if there is any more information I can provide that would be helpful.

**Comment by Scraticus** [comment]
This repo is for 5.0 and 5.1, you didn't read about not using this repo to report OutFox bugs. 

Please repost it [here,](https://github.com/TeamRizu/OutFox) and post your logs with the bug report.

Many thanks

**Comment by Chaz6** [comment]
I am sorry, I did my best to find the place to report a bug. I did not read anywhere that I should note use this for Outfox. I will close this bug and open a new one in the right repository.
