### ISSUE TITLE
Command /usr/bin/codesign failed with exit code 1

### ISSUE THREAD

**Issue by omgitsraven** [stepmania/stepmania#2049]
I'm trying to build Stepmania on macOS (in hopes of running it on Catalina), but compiling gives one error:

```
CodeSign StepMania-debug.app
    cd /Users/andrew/Documents/GitHub/stepmania
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --entitlements /Users/andrew/Documents/GitHub/stepmania/build/src/StepMania.build/Debug/StepMania.build/StepMania-debug.app.xcent --timestamp=none /Users/andrew/Documents/GitHub/stepmania/StepMania-debug.app

/Users/andrew/Documents/GitHub/stepmania/StepMania-debug.app: code object is not signed at all
In subcomponent: /Users/andrew/Documents/GitHub/stepmania/StepMania-debug.app/Contents/MacOS/StepMania-debug
Command /usr/bin/codesign failed with exit code 1
```

I went to "code signing identity" in the build settings, and set it to 'mac developer', but the error is exactly the same as before.

**Comment by quietly-turning** [comment]
Have you tried building using make?  That's what I've been using recently.
```bash
# use homebrew to install dependencies
brew install cmake yasm

# clone stepmania from github
git clone --depth=1 https://github.com/stepmania/stepmania.git

# init local submodules
cd stepmania
git submodule update --init

# use cmake to generate a makefile
cd Build
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release .. && cmake  ..

# build using make
# the number of build jobs should not exceed 2x your CPU cores
# I have 4 cores, so -j8
make -j8
```

As is noted all throughout #1933, you'll need to explicitly grant StepMania input monitoring permissions in System Preferences for input to be recognized, currently.  You'll need to (re)do this every time you (re)build from source.

**Comment by quietly-turning** [comment]
For now, I've updated the Wiki's instructions for building on macOS to describe make instead of Xcode.  It's what I've been using on macOS 10.15/Catalina.

https://github.com/stepmania/stepmania/wiki/Compiling-StepMania#macos

Let us know if you find otherwise. 🙂

**Comment by omgitsraven** [comment]
Success, thanks!

The one thing that I'd recommend: following the instructions as printed wound up building the game into the same folder that the git was checked out into, rather than into a subfolder of 'Build', so now the sources and the app files are all mixed together. (The result still runs, but I'm not sure which files need to stay there now...)

**Comment by quietly-turning** [comment]
> Success, thanks!

Good to hear.

> The one thing that I'd recommend: following the instructions as printed wound up building the game into the same folder that the git was checked out into, rather than into a subfolder of 'Build', so now the sources and the app files are all mixed together.

I suppose I'm unfamiliar with other projects do.  Can you link to examples of other, similarly structured projects that handle build directories differently as examples?

**Comment by omgitsraven** [comment]
The only other project that I have some experience building is https://github.com/libfive/libfive

**Comment by quietly-turning** [comment]
Thanks!  How is it different, and why do you prefer that?

**Comment by omgitsraven** [comment]
If I'm understanding right, it looks like the root of the github repository contains a lot of files that the resulting app requires in order to run -- and the app actually uses those exact files _in that exact location_ when it runs. But the files that are only necessary in order __to__ build are _also_ mixed into the same directory, and there's no real way to tell them apart without knowing the project -- so if you want to move the result into your Applications folder for example, you'd be bringing all the sources with it.

I'm not an expert, but the process that I'm used to from other projects is that after running the build process, somewhere inside the Build folder will be a folder containing the executable and _all_ the files that it requires to run (and nothing else). That folder is self-contained, and you can zip it up, send it to someone, or move it to your Applications folder, or whatever. (It also doesn't run the risk of accidentally overwriting source files during the build process -- the build process only writes into its own directory that doesn't have anything else in it.) Also, it means that you only need to add that one Build subfolder to your .gitignore in order to not have Git point out all the newly built files as changes to push to the repository on your next commit...

Ultimately, it's not the end of the world to have some source files lying around, and I guess copying all those files into the Build folder on every build is a minor waste of disk space if you're planning to keep the source around? But when I first saw that the game was building into the same directory that its source files were in, I thought it was a bug -- I thought I'd missed a `cd` somewhere, and that I might have accidentally clobbered source files that would prevent me from building a second time, or that it wouldn't be able to find some associated files that it needs to run (it was only in writing this reply that I realised that those files were already placed in the root of the project too...)

**Comment by geefr** [comment]
So in a cmake project it's usually strongly encouraged to do an out-of-source build i.e the directory you build in could be anywhere.
On top of that there's then 'make install' or 'make release' targets, which package things up for you (via CPack).
Personally I use this
- /home/source/project - The git repo, containing all sources
- /home/build/projects - Temporary build dir, anything can happen here, it's intentionally a mess
- /home/install/project - Where things get installed to (Or to the system)

And to build you'd run cmake in your build directory (cmake -DCMAKE_INSTALL_PREFIX=/home/install/project /home/source/project) then run the install target (make install, or the 'install' project within generated VS solution/similar).

If the cmake project isn't structured properly there can be some quirks, but stepmania's works fine like this. It's up to the user where build/install files go, no restrictions (but also no helpful defaults as the build system is so flexible)

**Comment by omgitsraven** [comment]
ahh, okay :) Don't mind me then! I honestly just thought that I'd missed a `cd` somewhere in the instructions, is the only reason I brought it up. Thanks again!

**Comment by quietly-turning** [comment]
> ahh, okay :) Don't mind me then! I honestly just thought that I'd missed a cd somewhere in the instructions, is the only reason I brought it up. Thanks again!

Oh, no problem at all.  It was helpful for me to discuss this stuff, too, since I don't have much experience outside of StepMania.  I wasn't sure what other projects normally do.

**Comment by shakesoda** [comment]
should i or anyone else encounter this issue: build settings -> product name needs to match the executable name (StepMania) for the configuration you are building.
