### ISSUE TITLE
lua link errors in MSVC

### ISSUE THREAD

**Issue by coderjo** [stepmania/stepmania#2054]
After #1947, MSVC builds are failing to link. It seems that, despite the cmake file specifying the /TP flag to build lua as c++ code, the vcxproj file does not have that set. As a result, symbol names do not match when it gets around to linking SM. Manually setting the "Build As" setting in the VS GUI to "C++" allows the build.

I'm documenting this so someone else can potentially fix it before I get more time to dig into cmake.

**Comment by geefr** [comment]
CMake bits look fine to me other than some older syntax, so yeah that's a bit odd. If you can't sort it before the weekend feel free to throw it my way.
