### ISSUE TITLE
Raspberry Pi4 - Arrow Jitter

### ISSUE THREAD

**Issue by JA64Flyers** [stepmania/stepmania#2077]
Hello all! After following SpottyMatt's guide, i have SM running successfully on an RPi4. My issue is the arrows slightly jitter upwards, like they're skipping pixels along the way, even though my FPS is 60 pretty much all the time. The only deviation i have from his guide is not using a USB sound card, tho i have tried one with no change in my results.

Here's comparison videos to show you what i mean - 
Win10 - https://youtu.be/iW9K3mJ4U2Q
RPi4 - https://youtu.be/MyFh3OSBkHE
(Ignore the fact that there's no audio on the RPi4 version, another experiment i tried)

The issue is slight, but drives me crazy. Since my knowledge of how this and other linux installs work is very limited, i had a nerd friend of mine run me through trying some settings changes and audio server changes. Nothing made a difference, and i ended up wiping it and starting over.

Is this just how it runs on this platform? Or could i have something not configured properly to produce these results? Thanks for your time!

**Comment by shakesoda** [comment]
I don't know anything about that guide, but that looks about as expected. Not very much work has gone into the RPi port other than my branch with some small changes for it. If your framerate is good that's usually a sound position related problem, or a timing problem with the frame presentation.

Try your luck with one of the pi builds for 5.3 over here https://projectmoon.dance/downloads, they've done a lot more work on ARM support and it should be smoother (it'll be merged back here in the future)

**Comment by JA64Flyers** [comment]
Thanks for the direction, i had no idea that project existed. I'll give it a shot!

**Comment by JA64Flyers** [comment]
That worked! With fast note enabled l, this version has buttery smooth arrows. Thanks for the help!
