### ISSUE TITLE
StepMania ARM: Is decent performance possible on a Raspbery Pi 4? 

### ISSUE THREAD

**Issue by mtoensing** [stepmania/stepmania#2079]
Thank you for StepMania! It sparked joy to my life since many years on the original XBOX 1. I read many tutorials and ended up compiling StepMania from source for the most recent 32-bit version of Raspberry OS. Well, it works but performance worse than my PS1 and Dreamcast emulator with Dance Dance Revolution on the same hardware. Even OpenArena (Quake 3) runs okay on a Pi. And even my Original XBOX (yes, the very first one) runs Stepmania 4 in 720p with 60fps.

So, here is what I did: 

- Installed most recent 32-bit Raspberry OS
- I compiled StepMania from source for my Pi
- Reduced resolution to 720p or even lower
- Compared exclusive fullcreen mode and borderless window and every other setting.
- Reduced texture resolution to 1024 and lower
- Fast Note Rendering enabled (huge gain!) 
- Overclocked my gpu and cpu of my Pi4

Still  I am unable to reach a stable 60 fps. If many notes/arrows appear it drops significantly. 

So my questions are:

- Why is the performance of this game so bad on a pi if the hardware should and can do better. Even emulating the original games is faster.
- Why do we have to compile our own version or rely on ppl who build it? Can you just provide an ARM release for everyone? Or an Image for the Pi like RetroPi?

Isn't this time during the pandemic the best chance to get the whole world dancing with Stepmania? If the performance and ease of use on a pi would be improved many more ppl would be able to use StepMania. Think of Retropi and all other emulation distributions how they gain popularity during the pandemic. So:

What can be done to improve the situation? Or is the topic not relevant according to the community?

**Comment by shakesoda** [comment]
yes, it's entirely possible - the work just mostly hasn't been upstreamed yet. there's a lot of problems that have been resolved that just haven't made their way here yet. see this issue https://github.com/stepmania/stepmania/issues/2077#issuecomment-751564037

as for builds, we just haven't made any for a very long time, and shipping for arm64 wasn't on the radar yet. there's no reason they can't be done in the future.

edit: to be very, very clear, the fact that it runs so bad on pi is a bug, it can and should run significantly better, as you expect.

**Comment by mtoensing** [comment]
Ok, this works and is really fast (60 fps on most songs) 

https://github.com/mtoensing/Moondance-StepMania64-pi4
