### ISSUE TITLE
Stepmania doesn't pick pulse over ALSA

### ISSUE THREAD

**Issue by weedleeedle** [stepmania/stepmania#2082]
Using Arch Linux and compiling stepmania from source, the compiled executable kept choosing ALSA instead of Pulse, which resulted in no sound and being unable to play through any songs. In addition, flags like -DWITH_PULSEAUDIO=ON seemed to be doing nothing. CMake was telling me that these variables weren't being used. I was able to get it to work by changing the each of the audio systems in StepmaniaCore.cmake as follows:

`IF (PULSEAUDIO_FOUND)`

to 

`IF (PULSEAUDIO_FOUND AND WITH_PULSEAUDIO)`.

**Comment by geefr** [comment]
I thought there was some recent change here that improved that somewhat..

The cmake setting you probably want in that case is then WITH_ALSA=OFF, which should tell the project to ignore alsa even if it's found on the system. best way to edit is to use cmake-gui or ccmake (in the director you ran cmake run 'cmake .' change options, then c, g, to configure/regenerate the makefiles).

CMake ignoring flags should only happen if you passed them incorrectly, but the project might have them configured as 'CACHE FORCE' which I think can ignore any user-provided values before cmake runs.

Are you planning to make a pull request with the change?

**Comment by weedleeedle** [comment]
What I was finding is that any of the WITH_X options was not being used by CMake at all. I get the following message with StepmaniaCore.cmake left as is:

`CMake Warning:
  Manually-specified variables were not used by the project:

    WITH_ALSA
`
I felt like what I was doing was little more than a hack that happened to fix the problem that I was facing, but if that's actually what needs to change in order for Stepmania to properly use Pulse instead of ALSA then I can certainly do that!

**Comment by geefr** [comment]
Update on this one - I took a look and the 5_1-new branch is fine.

(The 5_0 branch on the other hand is a little janky, but no one should be building that ;))

**Comment by shakesoda** [comment]
@geefr thanks for investigating, closing.
