### ISSUE TITLE
can someone give me a default theme so it works

### ISSUE THREAD

**Issue by dsfdsdsgfdgfd** [stepmania/stepmania#2108]
The default glyph is missing from the font "/Themes/default/Fonts/_r bold 30px (2).ini".

**Comment by arceuss** [comment]
what

**Comment by dsfdsdsgfdgfd** [comment]
it is where you see themes if you see default copy it to a website to where I can download it

**Comment by dsfdsdsgfdgfd** [comment]
because i tryed to put a theme that did not work

**Comment by concubidated** [comment]
The default theme is in the github repo themes folder.
