### ISSUE TITLE
Background scaling with lua in #bgchanges is now very weird

### ISSUE THREAD

**Issue by TaroNuke** [stepmania/stepmania#2130]
code: `OnCommand= cmd(x,0;y,0;diffuse,.5,.5,.5,1;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT;),`

desired result:
![image](https://user-images.githubusercontent.com/633391/124177110-b5d59880-daa7-11eb-967e-987904cad95c.png)

actual result:
![image](https://user-images.githubusercontent.com/633391/124176835-5aa3a600-daa7-11eb-85ae-45da47bd4b79.png)

code: `OnCommand= cmd(x,0;y,0;diffuse,.5,.5,.5,1;zoom,0.001;),`

![image](https://user-images.githubusercontent.com/633391/124177184-c8e86880-daa7-11eb-811c-d191d88c14bf.png)

For some reason it looks like 0,0 is the center of the screen, and it's scaled about 10,000 times

**Comment by CrashCringle12** [comment]
Hiya,

I noticed this as well and embarked on a bit of journey to figure out where it started. After some tedious searching through commits, I found reverting this commit fixes the issue
56caf6da4b8ea7a122d845c39adda2b81524a9e8 https://github.com/stepmania/stepmania/pull/1888

**Comment by TaroNuke** [comment]
Ah this is definitely the fault of whatever changes were made to NotesLoaderSM's #BGCHANGES tag parsing.
The ability to load non numbers is causing some empty string to be parsed as "stretch this BG" maybe?

**Comment by Scraticus** [comment]
I've applied the same code we have in outfox to resolve this for you. I didn't expect to have permissions but it's done.
