### ISSUE TITLE
Compilation problem in Raspberry pi 3b +

### ISSUE THREAD

**Issue by PTALTS-LK** [stepmania/stepmania#2137]
When I tried to compile, it started very good, but this error appeared

/home/pi/stepmania/src/archutils/Common/PthreadHelpers.cpp:251:2: error: #error GetThreadBacktraceContext: which arch?
 #error GetThreadBacktraceContext: which arch?
  ^~~~~

use Raspberry pi os(armhf)

**Comment by concubidated** [comment]
For building on RasPi you should checkout https://github.com/SpottyMatt/raspbian-stepmania-build

Project Outfox performs much much better on a Raspi then 5.1 will though. I would personally recommend to check that out.
