### ISSUE TITLE
X11 Protocol error BadValue on Fedora

### ISSUE THREAD

**Issue by audreyazura** [stepmania/stepmania#2145]
The game still worked recently, but when I tried to play today, it crashed repeatedly on launch. I recompiled it from source, but the error is consistently the same.

OS: Linux
Distribution: Fedora 33
CPU: AMD Ryzen 5 2600
GPU: GeForce GTX 1060clear

Partial log:
```
00:00.681: Video renderers: 'opengl'
00:00.681: RageDisplay_Legacy::RageDisplay_Legacy()
00:00.682: DPMSQueryExtension returned true.  Stepmania will disable power management, and restore the original state on exit.
00:00.682: Display: :1 (screen 0)
00:00.682: X server vendor: Fedora Project [1.20.11.0]
00:00.749: Server GLX vendor: NVIDIA Corporation [1.4]
00:00.749: Client GLX vendor: NVIDIA Corporation [1.4]
00:01.007: WARNING: X11 Protocol error BadValue (integer parameter out of range for operation) (2) has occurred, caused by request 151,3, resource ID 0
00:01.012: WARNING: X11 Protocol error BadValue (integer parameter out of range for operation) (2) has occurred, caused by request 151,3, resource ID 0
00:01.012: WARNING: X11 Protocol error BadMatch (invalid parameter attributes) (8) has occurred, caused by request 151,5, resource ID 0
```

**Comment by geefr** [comment]
X11 errors are notoriously difficult to debug, even if they're reproducible.
If you know which line of code in stepmania caused it (and have the X11 manuals on your shelf) you're golden, but it's an async protocol and generally awkward.

So, the question would be what changed today? Did you install system updates, a new graphics driver, etc?
It's possible that it's a logic error in stepmania, but that code has probably been happy for a decade or so, and the X11 side of that interface basically doesn't change, that's been stable forever basically.

**Comment by audreyazura** [comment]
Sadly, I don't think I have enough knowledge to find the line of code that caused this.

Regarding the thing that changed between last time I launched the game and today, probably quite a few things. I usually run dnf update at least once a day, and I think there was a kernel update recently. I remember seeing an nvidia update recently too, but I am not sure if it was before or after last time I launched the game, sorry.

But I realize I didn't do an update since I had the problem, so I tried to do so and there was a new kernel update available. After restarting my computer, the game is launching correctly.

Sorry to have been a bit quick to do a bug report, it looks like it was probably an update done by Fedora that was slightly broken. Thank you for your help! =)

**Comment by geefr** [comment]
Very few have the knowledge and desire to debug that one properly ;)

Likely - The kernel update and nvidia drivers were mismatched somehow, then a call to X11 (glx) to start opengl failed.
Most likely no other opengl games/programs would've worked properly either.
