### ISSUE TITLE
Unauthenticated git protocol no longer supported with extern/ffmpeg-linux-2.1.3

### ISSUE THREAD

**Issue by Espionage724** [stepmania/stepmania#2197]
Ran into that error on Fedora 35 today when trying to compile from 5.1-new. According to a quick search, it seems easily fixable by using **http://** instead of **git://**

I haven't tried that yet and went ahead with trying my system's FFMPEG package.

**Comment by Scraticus** [comment]
Fixed, thanks for reporting
