### ISSUE TITLE
Trying to compile on Linux, but seeing "Unable to locate package libglew1.5-dev"

### ISSUE THREAD

**Issue by mulliganaceous** [stepmania/stepmania#2204]
As a Linux user and a longtime casual Stepmania player, I am planning to reinstall Stepmania 5.1 (beta for so long!) to replay my old songs. I am currently using **Jammy Jellyfish** as my Linux distro.

I have noticed that the first step, which is to build dependencies, is always failiing noting that `libglew1.5-dev` is unable to be locaetd. I tried using `sudo apt-get install -y libglew1.5-dev` with no effect.

Maybe the dependencies should be updated?

[https://imgur.com/a/qpdfcqr](url)

**Comment by mulliganaceous** [comment]
I tried installing `libglew-dev` rather than `libglew1.5-dev`. Hope that will fix. Can you please verify and update this on the wiki?

**Comment by concubidated** [comment]
This has been updated already
