### ISSUE TITLE
This should not be happening

### ISSUE THREAD

**Issue by ScienceNerd2240** [stepmania/stepmania#2234]
Stepmania 5.1 b2, getting an 'Out of memory' crash and I have 32GB RAM installed on my PC. Can anyone tell me how to allocate more to the game or something? I've tried everything I can think of
[crashinfo.txt](https://github.com/stepmania/stepmania/files/10045838/crashinfo.txt)

**Comment by tertu-m** [comment]
StepMania 5.1 b2 is a 32 bit application on Windows and can't use more than 3GB of RAM.

**Comment by ScienceNerd2240** [comment]
Good to know, thank you!

**Comment by ScienceNerd2240** [comment]
Good to know, thank you!
