### ISSUE TITLE
Broken Fullscreen under OS X

### ISSUE THREAD

**Issue by Wowfunhappy** [stepmania/stepmania#224]
When opening the current latest version in OS X (commit 6104c3f) and entering full screen, no picture is displayed. The game continues to run and accept input, with fully working sound, but the screen is black.

Returning to windowed mode fixes the issue.

Tested under OS X Mountain Lion 10.8.5 on a 2012 Macbook Air with Intel HD Graphics 4000.

**Comment by Noyabronok** [comment]
Are there any plans to fix this?

**Comment by dguzek** [comment]
Having spent (many) hours tinkering with *LowLevelWindow_MacOSX.mm* I can only assert that this issue is beyond my capacity to fix.

For StepMania 5.0.10, you can still achieve fullscreen by clicking the green "traffic light" to fullscreen the window using OS X native code.  It is only StepMania's custom fullscreen handling code that is broken.

**Comment by cgoudie** [comment]
I can confirm it's not working on El Capitan with the default mac build (dmg install)

Could full screen mode on the mac simply cause the application to launch "full screen" such as with the green "traffic light"?

**Comment by dguzek** [comment]
I'll just copy/paste what I wrote above:

> Having spent (many) nights tinkering with LowLevelWindow_MacOSX.mm I can only assert that this issue is beyond my capacity to fix.

> For StepMania 5.0.10, you can still achieve fullscreen by clicking the green "traffic light" to fullscreen the window using OS X native code. It is only StepMania's custom fullscreen handling code that is broken.

It is feasible that fullscreen on OS X will become a non-issue with the eventual transition to SDL2, but there is no timeframe for that that I know of.

**Comment by nilbus** [comment]
I confirm that clicking the green button correctly puts the app
full-screen, and that Ctrl+Enter fails. This would be an excellent fix.
>
>

**Comment by dguzek** [comment]
This has been resolved by pull request #1523 and can now be closed.
