### ISSUE TITLE
DNS for www.stepmania.com is not resolving

### ISSUE THREAD

**Issue by helloimalemur** [stepmania/stepmania#2267]
DNS for www.stepmania.com is not resolving
![Screenshot_20240515_150612](https://github.com/stepmania/stepmania/assets/37273704/221897b4-4bdf-456b-9af5-3f008c53cf74)

**Comment by bonimy** [comment]
RIP stepmania.com

**Comment by PkGamTV** [comment]
Oh! It's back up.
