### ISSUE TITLE
Polishing the Default Theme

### ISSUE THREAD

**Issue by freem** [stepmania/stepmania#242]
There's a number of things in the default theme that need fixing up; please reply with anything missing from this list and I'll add it.
- Stage numbers aren't correct.
  - ~~ScreenEvaluationNormal, Event Mode off~~ (fixed in 527e93c)
  - ~~ScreenGameplay in course mode (constantly shows 1)~~ (fixed in ???)
- ~~Rave's evaluation screen needs to be customized.~~ (fixed in ???)
- ScreenNetRoom has odd screen elements on it.
- ~~Banners on ScreenEvaluationSummary seem to be in reverse order.~~
  - ~~First stage played is shown in front, last stage at back.~~
- ~~Banners on ScreenEvaluationSummary need positioning magic to not look weird in certain situations. (e.g. anything less than 3 stages)~~
  - No longer an issue due to a change in how the banners are displayed.
- ~~Font used on the service options screen has garbage above the space and comma glyphs. [(screenshot)](http://i.imgur.com/dO3XnR1.jpg)~~
- ~~Game Over screen needs to be more than just some microscopic text.~~ (fixed in 3239e46)
- ~~Summary shouldn't be shown after course play~~
-  "Show Score" and "Show Steps" under "Theme Options" reset to "on" whenever the program is started. (see #158 )

**Related to codebase**
- Life and Combo graph on ScreenEvaluationSummary has stages in reverse order.
- Network/Online screens are heavily based on legacy code.

**fallback Theme**
- ~~"ScreenHighScores has no metrics in _fallback"~~ (#217; fixed recently)

**Comment by ListenerJubatus** [comment]
Some of these are no longer relevant due to the new 5.1 default theme (Lambda), but the point about online play needing less legacy code is still relevant (it needs a new way to show other players' results because the new way it renders the evaluation screen doesn't support it).

However, that can be treated as its own bug.
