### ISSUE TITLE
EditorNoteSkins should be game-specific

### ISSUE THREAD

**Issue by dguzek** [stepmania/stepmania#247]
EditorNoteSkinP1 and EditorNoteSkinP2 are current global preferences, defaulting to:
```
[Options]
EditorNoteSkinP1=default
EditorNoteSkinP2=default
```
It may be desirable to set a default editor noteskin on a per-game basis.

**Comment by kyzentun** [comment]
Resolved in 5.1 by allowing the user to pick the noteskin in a menu.  Saved per-stepstype.
