### ISSUE TITLE
SoundDriver setting is ignored

### ISSUE THREAD

**Issue by xwidghet** [stepmania/stepmania#248]
When I set the sound driver in Preferences.ini, located at appdata/roaming/StepMania 5/Save, to WaveOut or WDKMS they are ignored. This is shown by "Sound driver: directsound-sw" being written in the logs. This is a problem because on every sound device I've used with W7, W8 and W8.1 they give bad sound timing while using DirectSound. That is every couple frames at 120fps the arrows are only scrolled up a couple pixels. When I compiled it myself with the sound device order switched so that WaveOut is first this problem completely goes away. I have recorded some before and after footage at 120fps of this.

Before
https://mega.co.nz/#!1QxUCDCb!MIPBFnPl4fbrPKid1J6BQcq7w7PULWbFFvqlNgEq7gM

After
https://mega.co.nz/#!YU5ACBpS!_fVAcRkMp1xAY-axRx_mbjfOptfjI7HTCANEBQR6j9U

**Comment by shakesoda** [comment]
long forgotten, but 1) dsound driver has been fixed, 2) AFAICT, these settings work now.
