### ISSUE TITLE
VC2010 build (probably OSX too) needs to be updated to ffmpeg 2.1

### ISSUE THREAD

**Issue by roothorick** [stepmania/stepmania#27]
Two things I know about that are end-user affecting and 100% the result of using old ffmpeg:
- MPEG4 video is 200ms off
- Loading too many videos in one #BGCHANGES causes a crash in av_freep

So we need to version bump.

**Comment by dguzek** [comment]
Is this still an issue on Windows?  On the OS X side of things, this has been resolved since #827 was merged in October 2015.
