### ISSUE TITLE
Player choice re: routine sanity checks

### ISSUE THREAD

**Issue by roothorick** [stepmania/stepmania#30]
If we're doing routine, both players need to agree on the same routine chart.

How I think it's best to enforce this:

At the end of ScreenSelectMusic, if either player (or both) has selected a routine chart, but BOTH players aren't on THE SAME routine chart:
* If it's ending by player choice (i.e. hitting Start), then SSM should refuse to end, with a visual cue somehow hinting that the players need to agree on the chart to start routine.
* If it's ending by time running out, and the song has one or more single charts, any player on a routine chart is booted to the first chart we find on the easiest difficulty. If there are no single charts, we'll just go with the master player's routine chart.

**Comment by kyzentun** [comment]
This has been fixed since #489 was merged.  When steps for one player are changed, the other player is checked for compatibility.  If the steps are incompatible (one is routine, or different per-chart music), then the other player is forced to change to the same steps as the player that changed.
