### ISSUE TITLE
bundled ffmpeg is not properly linked

### ISSUE THREAD

**Issue by foresto** [stepmania/stepmania#307]
The ffmpeg libraries are currently bundled and linked dynamically to the stepmania executable, but not installed with it. This leads to a broken executable.

```
$ ldd stepmania |grep libav
	libavutil.so.52 => /usr/lib/x86_64-linux-gnu/libavutil.so.52 (0x00007f321f1ec000)
	libavformat.so.55 => not found
	libavcodec.so.55 => not found

$ ./stepmania 
./stepmania: error while loading shared libraries: libavformat.so.55: cannot open shared object file: No such file or directory
```

These libraries probably ought to be linked statically until the system libraries (libav on most distributions) become good enough to use instead.

**Comment by roothorick** [comment]
2aed24ce4666bbe5c04ca412ac40d4fe1c39b437
