### ISSUE TITLE
E_OUTOFMEMORY

### ISSUE THREAD

**Issue by unnAMD** [stepmania/stepmania#315]
So i was playing a couple of minutes ago.. and all of the sudden this error appears...

![fatal error](https://cloud.githubusercontent.com/assets/8765197/4263047/bc9af8e0-3bc6-11e4-9427-69c76669b24b.png)

(i've _never_ seen this error before)

Here's part of what the Log file recorded

76:04.911: Mixing underruns: 1
76:05.313: RageTextureManager: deleting 'Cache/Banners/Songs_KBO Solo Files Part VII_Ankoku Psychadelic_ankoku.png'.
76:05.373: 99 FPS, 164 av FPS, 5230 VPF, D3D
76:05.520: RageTextureManager: deleting '/Songs/KBO Solo Files Part VII/Ankoku Psychadelic/ankoku.png'.
76:06.379: 94 FPS, 163 av FPS, 5542 VPF, D3D
76:07.379: 96 FPS, 164 av FPS, 5729 VPF, D3D
76:07.481: MusicWheel::Select()
76:07.481: WheelBase::Select()
76:07.525: RageBitmapTexture: Loaded '/Songs/Frandre's ZUN BGM Collection Mega Pack - The Last Touhou Mix -/Bad Apple!!/bg.jpg' (1024x512); RGBA8 opaque, source 640,480;  image 640,480.
76:07.559: RageBitmapTexture: Loaded '/Songs/Frandre's ZUN BGM Collection Mega Pack - The Last Touhou Mix -/Be of good cheer/bg.jpg' (1024x512); RGBA8 opaque, source 640,480;  image 640,480.
76:07.599: RageBitmapTexture: Loaded '/Songs/Frandre's ZUN BGM Collection Mega Pack - The Last Touhou Mix -/Cosmic Mind/cosmic-bg.jpg' (1024x512); RGBA8 opaque, source 640,480;  image 640,480.
76:07.645: RageBitmapTexture: Loaded '/Songs/Frandre's ZUN BGM Collection Mega Pack - The Last Touhou Mix -/Darkness of Windholl/bg.jpg' (1024x512); RGBA8 opaque, source 640,480;  image 640,480.
76:07.672: RageBitmapTexture: Loaded '/Songs/Frandre's ZUN BGM Collection Mega Pack - The Last Touhou Mix -/Demystify Feast/demystifyfeast-bg.jpg' (1024x512); RGBA8 opaque, source 640,480;  image 640,480.
76:07.701:
76:07.701: //////////////////////////////////////////////////////
76:07.701: Exception: CreateTexture(1024,1024,RGBA8) failed: E_OUTOFMEMORY
76:07.701: //////////////////////////////////////////////////////
76:07.701: 
76:07.701: Shutting down mixer thread ...
76:07.710: Mixer thread shut down.
76:07.714: Shutting down decode thread ...
76:07.723: Decode thread shut down.
76:07.723: Mixing 4382.810684 ahead in 363826 Mix() calls
76:07.723: ScreenManager::~ScreenManager()
76:07.723: ScreenSelectMusic::~ScreenSelectMusic()
76:07.783: Performing texture garbage collection.
76:07.795: Shutting down DirectInput thread ...
76:07.796: DirectInput thread shut down.
76:08.203: Shutting down music start thread ...
76:08.203: Music start thread shut down.
(From here on it's just "TEXTUREMAN LEAK" thing.. and then)
76:08.479: RageDisplay_D3D::~RageDisplay()
76:08.481: WM_ACTIVATE (1, 0): doesn't have focus
76:08.673: Mixing underruns: 1
76:08.673: Players joined: P1
76:08.673: Lost focus to: (NULL), StepMania-SSE2.exe, explorer.exe
76:08.673: Language: en
76:08.673: Current renderer: Direct3D
76:08.673: Theme: CyberiaStyle8

probably it's just a minor error, but.. ever since SM has a "report" button.. i jus thought what the hey.. ha,.

i've posted this because as i said before.. i've never seen this error

"RIG"
8gb of ram (available in the system according to windows task manager = around 6gb)
HD7870 2Gb of VRam
fx4100 @4.0GHz.

**Comment by concubidated** [comment]
unable to allocate memory, prob not a sm issue, and he never came back with it occurring again.

**Comment by sabrina-440** [comment]
@unnAMD did you ever figure this out? I'm running 16GB of ram and a GTX 980TI so it seems unlikely im out of memory but this started as of recent epically with stamina songs. I always do windows updates on this machine, going to attempt NVidia driver update check and see...

**Comment by sabrina-440** [comment]
I'm really hoping I don't need to replace my RAM or smtn, other things seem to run fine although I mostly just run SM, DDR GP and Data here...going to switch to ITGmania but I doubt that will fix this

**Comment by Horsey-** [comment]
Could this be because you’re hitting the 32bit application memory limit? Stepmania runs as a 32bit application on windows (which is limited to 2 or 4gb of RAM, I don’t remember which) so that could be your problem. [OutFox](https://projectoutfox.com/releases/0.4.19)  runs as a native 64bit application everywhere so I recommend you switch to that. Outfox is being actively maintained and has a bunch of development going on in their discord (link is on that website). I recommend you stick to the LTS build for now and try the alpha builds later.

**Comment by sabrina-440** [comment]
I switched to ITGmania and stopped having this issue, might've done a few other things when I was trying to get things to work so that might not have been it but glad it worked now regardless

**Comment by coderjo** [comment]
There was a memory leak in the PNG loading code starting in 2016, which was fixed in 2020 (in PR #1998), but a new release of 5.1 hasn't been made since 2018. Forks like ITGmania have pulled the fix and made releases since.
