### ISSUE TITLE
LoadLibrary with error 8

### ISSUE THREAD

**Issue by jojomexi** [stepmania/stepmania#338]
I believe this only happens when the program sucks up too much ram. The first time I loaded SM5 with Simply Love theme (the compatible port) on beta 4,I was loading a LOT of songs (987 packs). It failed to load and displayed this error. I noticed in task manager it was utilizing ~1.8GB ram at that point. I went to reload again, and given all the songs were pre-cached, it successfully loaded with ~1.3GB ram utilization. I did not play an extended amount of time, so I'm not for sure if it would crash if continuing to play (since I've noticed ram usage goes up slowly while playing long periods of time).

**Comment by concubidated** [comment]
beta4 is old now, I have not seen any noticeable memory leaks in later versions.
