### ISSUE TITLE
Foregrounds / Gimmicky files

### ISSUE THREAD

**Issue by jojomexi** [stepmania/stepmania#339]
This is the main, and possibly only reason I don't consistently use SM5 more often. Gimmicky files just seem to not work that well with it. I only tested Gay4Gimmix in the Gay4Gimmix 3 pack, and both the mods and foreground effects just werent working. I'm not for sure if this can be fixed with coding, or if the stepcharts just must be simply re-written to use different code, but thought i'd throw it out there!

**Comment by kyzentun** [comment]
If someone had the skills to do so, they could convert most of the Gay4Gimmix simfiles to work in SM5 and SM5.1.  They will not be loaded natively in SM5 because perfect automated conversion just isn't possible.
