### ISSUE TITLE
patch for DESTDIR=

### ISSUE THREAD

**Issue by sl1pkn07** [stepmania/stepmania#34]
this is a patch for add DESTDIR variable in makefile.am file

https://dl.dropboxusercontent.com/u/6596386/destdir.patch

to use with "make install": make DESTDIR=>path< install

valid for distro package maintainers

see: http://www.gnu.org/prep/standards/html_node/DESTDIR.html

edit: patch update

greetings

**Comment by shakesoda** [comment]
Closing now that cmake support (#518) is in.
