### ISSUE TITLE
Send Music Rate modifiers to stepmania server

### ISSUE THREAD

**Issue by Leo137** [stepmania/stepmania#346]
I frequently play with rates at the online server using stepmania 5b4, does anyone knows if its possible to send music rate modifiers to the server so they could display at this page? since the new cmod-adjust to the rate thingy i can't tell the difference browsing my scores on the page and it gets anyoing.

**Comment by zardoru** [comment]
https://github.com/stepmania/stepmania/blob/a41d9c046753f3b35e56a6c2b475d6cfc44881ed/src/SongOptions.cpp#L73
This string is sent to the server.

https://github.com/stepmania/stepmania/blob/bd3671ed2e3bb85d693cacd864294130e7adf6cf/src/NetworkSyncManager.cpp#L323
This method is called when ScreenGameplay begins.

Here.
https://github.com/stepmania/stepmania/blob/7687d5c8a167b74e56dabd0f6b3094fefe20ee7e/src/ScreenGameplay.cpp#L1588

It seems to me like the string is being sent.

**Comment by concubidated** [comment]
https://github.com/stepmania/stepmania/pull/1393
Resolved by this PR
