### ISSUE TITLE
Stepmania 5.0 beta 4a crashing after builing from source.

### ISSUE THREAD

**Issue by GregPK** [stepmania/stepmania#357]
Build by running the below on Linux Mint

``
cat /proc/version
Linux version 3.5.0-17-generic (buildd@allspice) (gcc version 4.7.2 (Ubuntu/Linaro 4.7.2-2ubuntu1) ) #28-Ubuntu SMP Tue Oct 9 19:31:23 UTC 2012
``

Built by invoking:

```
sudo apt-get install autoconf automake mesa-common-dev libglu1-mesa-dev libxtst-dev libxrandr-dev libpng12-dev libjpeg8-dev zlib1g-dev libbz2-dev libogg-dev libvorbis-dev libc6-dev yasm binutils-dev libgtk2.0-dev libmad0-dev
git clone https://github.com/stepmania/stepmania.git && \
cd stepmania && \
./autogen.sh && \
./configure && \
make && \
cp src/GtkModule.so ./ && \
cp src/stepmania ./
./stepmania
```

Crashlog:
https://gist.github.com/GregPK/5eadbae83bca4f24add6

Any ideas?

**Comment by GregPK** [comment]
When Xinerama has been disabled, works fine. I believe this bug can be closed.

**Comment by roothorick** [comment]
I wonder... Check out the x11_fullscreen branch and see if it works with
xinerama enabled.
