### ISSUE TITLE
Copy steps between different game types

### ISSUE THREAD

**Issue by freem** [stepmania/stepmania#364]
from IRC:

&lt;Dragonaire&gt; how do you copy solo steps over to kb7?
&lt;@freem&gt; good question; there really should be way to copy steps between [different game] types

the current solution is to do it manually in a text editor, which can be tedious, especially if you want to copy multiple charts.

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/commit/4559fc9b4ac0a857c0af15e2b28d61e6009974ba
http://i.imgur.com/tTL1RnG.jpg
Charts can still only be made for the current game type, but at least now you can copy from a different game type.
