### ISSUE TITLE
Multiple Joysticks Hide Keyboard on Key Config

### ISSUE THREAD

**Issue by wolfman2000** [stepmania/stepmania#371]
See attached screenshot. I have three items plugged in: Keyboard, Precision Dance Pad (Joy1), and Wired XBox 360 Controller (Joy2). Keyboard is hiding.

![screen shot 2014-11-17 at 22 38 32](https://cloud.githubusercontent.com/assets/148345/5082228/a345e654-6eaa-11e4-9700-3103bdf0f7fd.png)

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/commit/d28c8a8ab125f01669196ad6c0fa4e67d3e303ae
