### ISSUE TITLE
Few Themes Overlap Selection Area

### ISSUE THREAD

**Issue by wolfman2000** [stepmania/stepmania#374]
In the options screen: two custom themes set up.
![screen shot 2014-11-18 at 22 47 02](https://cloud.githubusercontent.com/assets/148345/5100474/0eb8efba-6f75-11e4-859c-a24cd1c9f969.png)

**Comment by shakesoda** [comment]
Is this still valid?

**Comment by kyzentun** [comment]
I believe it is.  You have to have just the right number of themes, enough to extend out of the frame, but not enough to make condense to a single item.

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/commit/d28c8a8ab125f01669196ad6c0fa4e67d3e303ae
