### ISSUE TITLE
Appearence Options -> Theme -> Fallback Theme

### ISSUE THREAD

**Issue by SpoOkyMagician** [stepmania/stepmania#390]
(Question/Feature Request)

Not really sure how you all feel about this but, I was wondering, why isn't there a selectable theme of fallback in SM5? It's extremely simple to include. It will help show what is available by default to themers visually. All, you need is this:

[Global]
FallbackTheme=_fallback

I would like to see it usable in SM5. (This is IMO but, it's up to you all to add it/include it or not.)

**Comment by concubidated** [comment]
Questioned answered. Closing
