### ISSUE TITLE
SM5 doesn't like huge tap count simfiles it seems.

### ISSUE THREAD

**Issue by SpoOkyMagician** [stepmania/stepmania#408]
This file I created has 192000 taps and it crashes after the first few taps. Seems it can't calculate numbers this high safely?

Edit: https://dl.dropboxusercontent.com/u/105712481/step.sm

StepMania v5.0 beta 4a crash report (build 4, 20141205 @ 11:22:21 Eastern Standard Time)
--------------------------------------

Crash reason: iScore < 0 before re-rounding

Thread: Main thread
        GraphicsWindow.cpp:54 001404AA, 257, 00000041, c01e0001
        GraphicsWindow.cpp:54 001404AA, 256, 00000041, 001e0001
        GraphicsWindow.cpp:54 001404AA, 257, 00000041, c01e0001
        GraphicsWindow.cpp:54 001404AA, 256, 00000041, 001e0001
        ScoreKeeperNormal.cpp:323 iScore < 0 before re-rounding
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
        InputHandler_DirectInput.cpp:750 
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
Thread: Streaming sound buffering

005c2cff: void CrashHandler::ForceCrash(char const *) [00400000+1c2ce0+1f]
005a24dc: void sm_crash(char const *) [00400000+1a24c0+1c]
00597fa9: void ScoreKeeperNormal::AddScoreInternal(enum TapNoteScore) [00400000+197de0+1c9]
00598bca: void ScoreKeeperNormal::AddTapRowScore(enum TapNoteScore,class NoteData const &,int) [00400000+198bc0+a]
7740e023: ntdll!RtlFreeHeap [773e0000+2dfa5+7e]
754514ad: kernel32!HeapFree [75440000+11499+14]
74c23c1b: MSVCR90!free [74bc0000+63b4e+cd]
74c23c3a: MSVCR90!free [74bc0000+63b4e+ec]
00413289: struct TapNote const & NoteData::GetTapNote(unsigned int,int)const  [00400000+13250+39]
00413289: struct TapNote const & NoteData::GetTapNote(unsigned int,int)const  [00400000+13250+39]
006364af: void Player::UpdateJudgedRows(void) [00400000+236260+24f]
006364b7: void Player::UpdateJudgedRows(void) [00400000+236260+257]
7740e023: ntdll!RtlFreeHeap [773e0000+2dfa5+7e]
754514ad: kernel32!HeapFree [75440000+11499+14]
74c23c1b: MSVCR90!free [74bc0000+63b4e+cd]
7740e023: ntdll!RtlFreeHeap [773e0000+2dfa5+7e]
74c23c1b: MSVCR90!free [74bc0000+63b4e+cd]
00637fae: void Player::Update(float) [00400000+2372f0+cbe]
00637fb5: void Player::Update(float) [00400000+2372f0+cc5]
0069d369: void Actor::UpdateInternal(float) [00400000+29ceb0+4b9]
006a702c: void ActorFrame::UpdateInternal(float) [00400000+2a6f70+bc]
006128df: void BackgroundImpl::Update(float) [00400000+212820+bf]
0053bd96: struct TimingSegment const * TimingData::GetSegmentAtRow(int,enum TimingSegmentType)const  [00400000+13bd60+36]
006a702c: void ActorFrame::UpdateInternal(float) [00400000+2a6f70+bc]
0069d369: void Actor::UpdateInternal(float) [00400000+29ceb0+4b9]
0052c2fe: void SongPosition::UpdateSongPosition(float,class TimingData const &,class RageTimer const &) [00400000+12c130+1ce]
00402eba: void Screen::Update(float) [00400000+2ea0+1a]
0068cdff: void RageTimer::Touch(void) [00400000+28cde0+1f]
006d9d8a: enum PlayerNumber GetNextEnabledPlayer(enum PlayerNumber) [00400000+2d9d60+2a]
006d9f33: void GameState::UpdateSongPosition(float,class TimingData const &,class RageTimer const &) [00400000+2d9df0+143]
004519e8: void ScreenGameplay::UpdateSongPosition(float) [00400000+51940+a8]
00454c9f: void ScreenGameplay::Update(float) [00400000+54c30+6f]
7740e023: ntdll!RtlFreeHeap [773e0000+2dfa5+7e]
74c23c3a: MSVCR90!free [74bc0000+63b4e+ec]
7740e023: ntdll!RtlFreeHeap [773e0000+2dfa5+7e]
754514ad: kernel32!HeapFree [75440000+11499+14]
74c23c1b: MSVCR90!free [74bc0000+63b4e+cd]
74c23c3a: MSVCR90!free [74bc0000+63b4e+ec]
7367582d: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::compare [73670000+57e5+48]
74bf69ed: MSVCR90!memcpy_s [74bc0000+369a3+4a]
73674f2a: MSVCP90!std::char_traits<char>::_Copy_s [73670000+4f13+17]
73675242: MSVCP90!std::allocator<wchar_t>::deallocate [73670000+5081+1c1]
736759d5: MSVCP90!std::allocator<char>::allocate [73670000+5929+ac]
7367582d: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::compare [73670000+57e5+48]
73675d47: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::compare [73670000+5d22+25]
736858ca: MSVCP90!std::operator==<char,std::char_traits<char>,std::allocator<char> > [73670000+158ba+10]
7368591e: MSVCP90!std::operator!=<char,std::char_traits<char>,std::allocator<char> > [73670000+1590e+10]
00714348: void ScreenManager::Update(float) [00400000+314330+18]
006d76d0: void GameState::Update(float) [00400000+2d7660+70]
00689a22: void RageTextureManager::Update(float) [00400000+2899c0+62]
005a2310: void GameLoop::RunGameLoop(void) [00400000+1a21f0+120]
73675e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [73670000+5dfb+48]
73675ec4: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > [73670000+5ebb+9]
005a69d6: main() [00400000+1a5b10+ec6]
74be36c5: MSVCR90!_set_flsgetvalue [74bc0000+236b6+f]
74be38b3: MSVCR90!initptd [74bc0000+23753+160]
005c22b4: int GetWin32CmdLine(char * * &) [00400000+1c2200+b4]
005c2035: WinMain@16() [00400000+1c2020+15]
007ad23f: __tmainCRTStartup() [00400000+3ad0ff+140]
77419f45: ntdll!RtlInitializeExceptionChain [773e0000+39f0f+36]

Static log:
StepMania v5.0 beta 4a
Compiled 20141205 @ 11:22:21 Eastern Standard Time (build 4)
Log starting 2014-12-13 19:03:13
Loading window: win32
Windows 6.1 (Win7) build 7601 [Service Pack 1]
Memory: 3966mb total, 4095mb swap (4095mb swap avail)
Video driver: NVIDIA GeForce 6150SE nForce 430 [NVIDIA]
              9.18.13.783, 1-31-2013 [pci\ven_10de&dev_03d0]
Drive: "Hitachi HDP725050GLA    GM4O" Driver: nvstor64 DMA: N/A
Drive: "ATAPI   DVD A  DH16AAL  LHD3" Driver: nvstor64 DMA: N/A
Sound device 0: Speakers (Logitech USB Headset , 1.22, MID 65535, PID 65535 
Sound device 1: Speakers (Realtek High Definiti, 6.1, MID 1, PID 100 
DirectSound Driver: Primary Sound Driver
DirectSound Driver: Speakers (Logitech USB Headset H540) {0.0.0.00000000}.{110272c3-4e9e-47ba-b3b1-f6ae09c2ef75}
DirectSound Driver: Speakers (Realtek High Definition Audio) {0.0.0.00000000}.{e695f95b-9a83-4802-b6b3-6096df3386fe}
DirectSound sample rates: 100..200000 (continuous)
Software mixing at 44100 hz
Sound driver: DirectSound-sw
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'opengl,d3d'
Mode: ICD 32 (888) 24 depth 64 accum 
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: NVIDIA Corporation
OGL Renderer: GeForce 6150SE nForce 430/integrated/SSE2
OGL Version: 2.1.2
OGL Max texture size: 4096
OGL Texture units: 4
GLU Version: 1.2.2.0 Microsoft Corporation
OGL Extensions:
  GL_ARB: ES2_compatibility, color_buffer_float, compressed_texture_pixel_storage, conservative_depth, 
    copy_buffer, depth_clamp, depth_texture, draw_buffers, explicit_attrib_location, fragment_program, 
    fragment_program_shadow, fragment_shader, framebuffer_object, get_program_binary, half_float_pixel, 
    half_float_vertex, imaging, internalformat_query, map_buffer_alignment, map_buffer_range, multisample, 
    multitexture, occlusion_query, occlusion_query2, pixel_buffer_object, point_parameters, point_sprite, 
    provoking_vertex, robustness, sampler_objects, separate_shader_objects, shader_objects, shading_language_100, 
    shading_language_420pack, shading_language_include, shadow, sync, texture_border_clamp, texture_compression, 
    texture_cube_map, texture_env_add, texture_env_combine, texture_env_crossbar, texture_env_dot3, texture_float, 
    texture_mirrored_repeat, texture_non_power_of_two, texture_rectangle, texture_rg, texture_storage, 
    texture_swizzle, timer_query, transpose_matrix, vertex_array_bgra, vertex_array_object, vertex_buffer_object, 
    vertex_program, vertex_shader, window_pos
  GL_ATI: draw_buffers, texture_float, texture_mirror_once
  GL_EXT: Cg_shader, abgr, bgra, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, 
    blend_subtract, compiled_vertex_array, depth_bounds_test, direct_state_access, draw_range_elements, fog_coord, 
    framebuffer_blit, framebuffer_multisample, framebuffer_object, gpu_program_parameters, import_sync_object, 
    multi_draw_arrays, packed_depth_stencil, packed_pixels, pixel_buffer_object, point_parameters, 
    provoking_vertex, rescale_normal, secondary_color, separate_shader_objects, separate_specular_color, 
    shadow_funcs, stencil_two_side, stencil_wrap, texture3D, texture_compression_dxt1, texture_compression_s3tc, 
    texture_cube_map, texture_edge_clamp, texture_env_add, texture_env_combine, texture_env_dot3, 
    texture_filter_anisotropic, texture_format_BGRA8888, texture_lod, texture_lod_bias, texture_mirror_clamp, 
    texture_object, texture_sRGB, texture_sRGB_decode, texture_storage, texture_swizzle, timer_query, 
    vertex_array, vertex_array_bgra
  GL_IBM: rasterpos_clip, texture_mirrored_repeat
  GL_KTX_buffer_region
  GL_NVX_conditional_render
  GL_NV: ES1_1_compatibility, alpha_test, blend_minmax, blend_square, complex_primitives, copy_depth_to_color, 
    depth_clamp, fbo_color_attachments, fence, float_buffer, fog_distance, fragdepth, fragment_program, 
    fragment_program2, fragment_program_option, framebuffer_multisample_coverage, half_float, light_max_exponent, 
    multisample_filter_hint, occlusion_query, packed_depth_stencil, pixel_data_range, point_sprite, 
    primitive_restart, register_combiners, register_combiners2, texgen_reflection, texture_barrier, 
    texture_compression_vtc, texture_env_combine4, texture_expand_normal, texture_lod_clamp, texture_rectangle, 
    texture_shader, texture_shader2, texture_shader3, vertex_array_range, vertex_array_range2, vertex_program, 
    vertex_program1_1, vertex_program2, vertex_program2_option, vertex_program3
  GL_OES: compressed_paletted_texture, depth24, depth32, depth_texture, element_index_uint, fbo_render_mipmap, 
    get_program_binary, mapbuffer, packed_depth_stencil, point_size_array, point_sprite, read_format, rgb8_rgba8, 
    standard_derivatives, texture_3D, texture_float, texture_float_linear, texture_half_float, 
    texture_half_float_linear, texture_npot, vertex_array_object, vertex_half_float
  GL_S3_s3tc
  GL_SGIS: generate_mipmap, texture_lod
  GL_SGIX: depth_texture, shadow
  GL_SUN_slice_accum
  GL_WIN_swap_hint
  WGL_EXT_swap_control
OpenGL Windowed 1601x885 32 color 32 texture 60Hz NoVsync SmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00010214 Instance Name: "USB Joystick          " Product Name: "USB Joystick          "
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 3 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'USB Joystick          ' axes: 4, hats: 1, buttons: 12 (buffered)
   2: 'Mouse' axes: 3, hats: 0, buttons: 3 (buffered)
WARNING: Lua runtime error: /Themes/default/BGAnimations/ScreenGameplay decorations/default.lua:48: calling 'GetElapsedTimeFromBeat' on bad self (number expected, got nil)
WARNING: [C]: GetElapsedTimeFromBeat( = (null))
WARNING: /Themes/default/BGAnimations/ScreenGameplay decorations/default.lua:48: CreateLine(beat = (null),secs = 0,firstShadow = #4169E177,firstDiffuse = #4169E177,secondShadow = #4169E177,firstEffect = #0000FF77,secondEffect = #FF000077)
WARNING: /Themes/default/BGAnimations/ScreenGameplay decorations/default.lua:109: CreateSegments(Player = PlayerNumber_P1,t = (null),bars = (null),bpmFrame = (null),stopFrame = (null),delayFrame = (null),warpFrame = (null),fakeFrame = (null),scrollFrame = (null),speedFrame = (null),fFrameWidth = 380,fFrameHeight = 8,song = (null),steps = (null),timingData = (null),songLen = 0.078000001609325,firstBeatSecs = 0,lastBeatSecs = 24000,bpms = (null),stops = (null),delays = (null),warps = (null),fakes = (null),scrolls = (null),speeds = (null),sumSegments = 3,CreateLine = (null),(for index) = 1,(for limit) = 1,(for step) = 1,i = 1,(*temporary) = 1)
WARNING: /Themes/default/BGAnimations/ScreenGameplay decorations/default.lua:210: main(maxSegments = 150,CreateSegments = (null),t = (null),songMeterScale = (null),(for generator) = (null),(for state) = (null),(for control) = PlayerNumber_P1,pn = PlayerNumber_P1,MetricsName = SongMeterDisplayP1,songMeterDisplay = (null),(*temporary) = 7)
Mixing underruns: 1
Players joined: P1
Lost focus to: StepMania-SSE2.exe
Top Screen: ScreenGameplay
Language: en
Current renderer: OpenGL
Theme: default

Partial log:
00:44.926: Performing texture garbage collection.
00:44.929: Zeroing this update.  Was 0.138000
00:44.937: Approximate sound time: driver frame 1964655, m_pImpl->m_Queue frame 0..1024 (dist 3473), closest position is 0
00:45.929: 65 FPS, 65 av FPS, 3109 VPF, OpenGL
00:46.930: 82 FPS, 73 av FPS, 906 VPF, OpenGL
00:47.938: 82 FPS, 75 av FPS, 926 VPF, OpenGL
00:48.939: 83 FPS, 78 av FPS, 832 VPF, OpenGL
00:49.950: 86 FPS, 79 av FPS, 455 VPF, OpenGL
00:50.958: 85 FPS, 80 av FPS, 460 VPF, OpenGL
00:51.958: 82 FPS, 81 av FPS, 512 VPF, OpenGL

-- End of report

**Comment by Flameshadowxeroshin** [comment]
192000*192001=0x89546EE00, which is too big to fit in an int

**Comment by SpoOkyMagician** [comment]
I am no expert with SM source but from the above post... If your using Int (32)...

square root(2,147,483,648) = 46340.950011841578559133736114903 (I would round this down for safety... 46340... I've heard of files being larger than this...)

46340*46341 = 2147441940

The maximum arrows (from my understanding) should be 46340.

**Comment by shakesoda** [comment]
@Flameshadowxeroshin I forget, what's the status of your patch for this?

**Comment by kyzentun** [comment]
Fixed by #440.
