### ISSUE TITLE
Unhandled Microsoft C++ Exception / GL_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by SpoOkyMagician** [stepmania/stepmania#413]
I know we are not meant to report non default/fallback theme bugs but, I am just wondering if this could/may be a possible windows issue that _might_ come up. This related to the GL ran out of memory issue I had in my theme a while back. However, this error came up instead... If anyone is willing to look into this, please do. Otherwise, just close.
## StepMania v5.0 beta 4a crash report (build 4, 20141205 @ 11:22:21 Eastern Standard Time)

Crash reason: Unhandled Microsoft C++ Exception

Thread: Main thread
        RageSurface_Load_PNG.cpp:20 
        RageSurface_Load_PNG.cpp:20 
        RageSurface_Load_PNG.cpp:20 
        RageSurface_Load_PNG.cpp:20 
        RageSurface_Load_PNG.cpp:20 
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
Thread: Mixer thread
Thread: Music thread
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Jeremy/Desktop/StepMania_Nightly/Themes/_fallback/Sounds/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Jeremy/Desktop/StepMania_Nightly/Themes/_fallback/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Jeremy/AppData/Roaming/StepMania 5/Themes/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Jeremy/AppData/Roaming/StepMania 5/Themes/_fallback/Sounds/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Jeremy/AppData/Roaming/StepMania 5/Themes/_fallback/*
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
        InputHandler_DirectInput.cpp:750 
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
Thread: Streaming sound buffering

7577c42d: KERNELBASE!RaiseException [75770000+c3d5+58]
7577c42d: KERNELBASE!RaiseException [75770000+c3d5+58]
74be2e2b: MSVCR90!unlock [74bc0000+22e16+15]
74be21e7: MSVCR90!amsg_exit [74bc0000+22157+90]
74c2ce95: MSVCR90!onexit [74bc0000+6ce5a+3b]
74c1df60: MSVCR90!CxxThrowException [74bc0000+5df18+48]
74c23efd: MSVCR90!operator new [74bc0000+63e99+64]
0067f7e8: struct RageSurface \* CreateSurface(int,int,int,unsigned int,unsigned int,unsigned int,unsigned int) [00400000+27f740+a8]
0064c97e: enum RagePixelFormat RageDisplay_Legacy::GetImgPixelFormat(struct RageSurface \* &,bool &,int,int,bool) [00400000+24c8a0+de]
0064cc04: unsigned int RageDisplay_Legacy::CreateTexture(enum RagePixelFormat,struct RageSurface *,bool) [00400000+24cba0+64]
7740e38c: ntdll!RtlInitUnicodeString [773e0000+2e228+164]
7578c6ed: KERNELBASE!CreateFileW [75770000+1c299+454]
7740e38c: ntdll!RtlInitUnicodeString [773e0000+2e228+164]
7740e0f2: ntdll!RtlAllocateHeap [773e0000+2e046+ac]
7740e38c: ntdll!RtlInitUnicodeString [773e0000+2e228+164]
74c23eb8: MSVCR90!operator new [74bc0000+63e99+1f]
773ff8d1: ntdll!ZwWaitForSingleObject [773e0000+1f8bc+15]
757814ab: KERNELBASE!WaitForSingleObjectEx [75770000+11413+98]
757814de: KERNELBASE!WaitForSingleObjectEx [75770000+11413+cb]
7740e38c: ntdll!RtlInitUnicodeString [773e0000+2e228+164]
757814de: KERNELBASE!WaitForSingleObjectEx [75770000+11413+cb]
7740e023: ntdll!RtlFreeHeap [773e0000+2dfa5+7e]
773ffad2: ntdll!ZwAllocateVirtualMemory [773e0000+1fac0+12]
77422af6: ntdll!NtdllDefWindowProc_A [773e0000+42ad3+23]
77413cd3: ntdll!RtlImageNtHeader [773e0000+33194+b3f]
74bf69ed: MSVCR90!memcpy_s [74bc0000+369a3+4a]
7740e38c: ntdll!RtlInitUnicodeString [773e0000+2e228+164]
773ffb6a: ntdll!NtFreeVirtualMemory [773e0000+1fb58+12]
77412b4c: ntdll!RtlGetCurrentProcessorNumberEx [773e0000+32a79+d3]
774457e9: ntdll!RtlDeleteAtomFromAtomTable [773e0000+6557d+26c]
774138aa: ntdll!RtlImageNtHeader [773e0000+33194+716]
77413cd3: ntdll!RtlImageNtHeader [773e0000+33194+b3f]
77413cfe: ntdll!RtlImageNtHeader [773e0000+33194+b6a]
7740e38c: ntdll!RtlInitUnicodeString [773e0000+2e228+164]
7740e0f2: ntdll!RtlAllocateHeap [773e0000+2e046+ac]
754514ad: kernel32!HeapFree [75440000+11499+14]
74c23c1b: MSVCR90!free [74bc0000+63b4e+cd]
74c23c3a: MSVCR90!free [74bc0000+63b4e+ec]
74be46fc: MSVCR90!_threadhandle [74bc0000+23a8e+c6e]
774138aa: ntdll!RtlImageNtHeader [773e0000+33194+716]
7740e023: ntdll!RtlFreeHeap [773e0000+2dfa5+7e]
754514ad: kernel32!HeapFree [75440000+11499+14]
74c23c1b: MSVCR90!free [74bc0000+63b4e+cd]
74c23c3a: MSVCR90!free [74bc0000+63b4e+ec]
74c23c3a: MSVCR90!free [74bc0000+63b4e+ec]
00685531: void RageSurfaceUtils::ConvertSurface(struct RageSurface \* &,int,int,int,unsigned int,unsigned int,unsigned int,unsigned int) [00400000+2854e0+51]
0064095b: void RageBitmapTexture::Create(void) [00400000+2401e0+77b]
7740e38c: ntdll!RtlInitUnicodeString [773e0000+2e228+164]
7740e0f2: ntdll!RtlAllocateHeap [773e0000+2e046+ac]
7740e0f2: ntdll!RtlAllocateHeap [773e0000+2e046+ac]
7740e0f2: ntdll!RtlAllocateHeap [773e0000+2e046+ac]
7740e38c: ntdll!RtlInitUnicodeString [773e0000+2e228+164]
7740e0f2: ntdll!RtlAllocateHeap [773e0000+2e046+ac]
754514ad: kernel32!HeapFree [75440000+11499+14]
74c23c1b: MSVCR90!free [74bc0000+63b4e+cd]
74c23c3a: MSVCR90!free [74bc0000+63b4e+ec]
73675ec4: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > [73670000+5ebb+9]
00688e56: RageTexture::RageTexture(struct RageTextureID) [00400000+288de0+76]
7367637a: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [73670000+632a+50]
0040fe5e: RageTextureID::RageTextureID(struct RageTextureID const &) [00400000+fe10+4e]
00640e30: RageBitmapTexture::RageBitmapTexture(struct RageTextureID) [00400000+240e00+30]
0068a31e: class RageTexture \* RageTextureManager::LoadTextureInternal(struct RageTextureID) [00400000+28a1c0+15e]
74c23eb8: MSVCR90!operator new [74bc0000+63e99+1f]
736858ca: MSVCP90!std::operator==<char,std::char_traits<char>,std::allocator<char> > [73670000+158ba+10]
0040fe5e: RageTextureID::RageTextureID(struct RageTextureID const &) [00400000+fe10+4e]
0068a379: class RageTexture \* RageTextureManager::LoadTexture(struct RageTextureID) [00400000+28a360+19]
7367637a: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [73670000+632a+50]
0040fe5e: RageTextureID::RageTextureID(struct RageTextureID const &) [00400000+fe10+4e]
006c7ee4: void Sprite::LoadFromTexture(struct RageTextureID) [00400000+2c7ea0+44]
73675d47: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::compare [73670000+5d22+25]
006c7f30: void Sprite::Load(struct RageTextureID) [00400000+2c7f10+20]
7367637a: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [73670000+632a+50]
0040fe5e: RageTextureID::RageTextureID(struct RageTextureID const &) [00400000+fe10+4e]
73675e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [73670000+5dfb+48]
73675ec4: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > [73670000+5ebb+9]
00766997: luaS_newlstr() [00400000+3668e0+b7]
0076ad98: luaV_gettable() [00400000+36ad70+28]
736773c3: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [73670000+73b2+11]
00754d2f: lua_rawget() [00400000+354d10+1f]
0075458d: lua_type() [00400000+354580+d]
0076c36d: luaV_execute() [00400000+36b800+b6d]
7740e0f2: ntdll!RtlAllocateHeap [773e0000+2e046+ac]
7740e38c: ntdll!RtlInitUnicodeString [773e0000+2e228+164]
7740e0f2: ntdll!RtlAllocateHeap [773e0000+2e046+ac]
0075bfab: luaD_call() [00400000+35bf60+4b]
00755195: f_call() [00400000+355180+15]
0075b53a: luaD_rawrunprotected() [00400000+35b500+3a]
0075b528: luaD_rawrunprotected() [00400000+35b500+28]
0075c11e: luaD_pcall() [00400000+35c0e0+3e]
007551f1: lua_pcall() [00400000+3551a0+51]
006f21fb: bool LuaHelpers::RunScriptOnStack(struct lua_State *,class StdString::CStdStr<char> &,int,int,bool) [00400000+2f21c0+3b]
7367642f: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [73670000+63c3+6c]
73676458: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [73670000+643c+1c]
0069c0b4: void Actor::RunCommands(class LuaReference const &,class LuaReference const *) [00400000+29bfc0+f4]
73675e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [73670000+5dfb+48]
73675ec4: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > [73670000+5ebb+9]
00754cfd: lua_getfield() [00400000+354cb0+4d]
0076c36d: luaV_execute() [00400000+36b800+b6d]
7740e38c: ntdll!RtlInitUnicodeString [773e0000+2e228+164]

Static log:
StepMania v5.0 beta 4a
Compiled 20141205 @ 11:22:21 Eastern Standard Time (build 4)
Log starting 2014-12-15 20:49:15
Loading window: win32
Windows 6.1 (Win7) build 7601 [Service Pack 1]
Memory: 3966mb total, 4095mb swap (4095mb swap avail)
Video driver: NVIDIA GeForce 6150SE nForce 430 [NVIDIA]
              9.18.13.783, 1-31-2013 [pci\ven_10de&dev_03d0]
Drive: "Hitachi HDP725050GLA    GM4O" Driver: nvstor64 DMA: N/A
Drive: "ATAPI   DVD A  DH16AAL  LHD3" Driver: nvstor64 DMA: N/A
Sound device 0: Speakers (Logitech USB Headset , 1.22, MID 65535, PID 65535 
Sound device 1: Speakers (Realtek High Definiti, 6.1, MID 1, PID 100 
DirectSound Driver: Primary Sound Driver
DirectSound Driver: Speakers (Logitech USB Headset H540) {0.0.0.00000000}.{110272c3-4e9e-47ba-b3b1-f6ae09c2ef75}
DirectSound Driver: Speakers (Realtek High Definition Audio) {0.0.0.00000000}.{e695f95b-9a83-4802-b6b3-6096df3386fe}
DirectSound sample rates: 100..200000 (continuous)
Software mixing at 44100 hz
Sound driver: DirectSound-sw
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'opengl,d3d'
Mode: ICD 32 (888) 24 depth 64 accum 
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: NVIDIA Corporation
OGL Renderer: GeForce 6150SE nForce 430/integrated/SSE2
OGL Version: 2.1.2
OGL Max texture size: 4096
OGL Texture units: 4
GLU Version: 1.2.2.0 Microsoft Corporation
OGL Extensions:
  GL_ARB: ES2_compatibility, color_buffer_float, compressed_texture_pixel_storage, conservative_depth, 
    copy_buffer, depth_clamp, depth_texture, draw_buffers, explicit_attrib_location, fragment_program, 
    fragment_program_shadow, fragment_shader, framebuffer_object, get_program_binary, half_float_pixel, 
    half_float_vertex, imaging, internalformat_query, map_buffer_alignment, map_buffer_range, multisample, 
    multitexture, occlusion_query, occlusion_query2, pixel_buffer_object, point_parameters, point_sprite, 
    provoking_vertex, robustness, sampler_objects, separate_shader_objects, shader_objects, shading_language_100, 
    shading_language_420pack, shading_language_include, shadow, sync, texture_border_clamp, texture_compression, 
    texture_cube_map, texture_env_add, texture_env_combine, texture_env_crossbar, texture_env_dot3, texture_float, 
    texture_mirrored_repeat, texture_non_power_of_two, texture_rectangle, texture_rg, texture_storage, 
    texture_swizzle, timer_query, transpose_matrix, vertex_array_bgra, vertex_array_object, vertex_buffer_object, 
    vertex_program, vertex_shader, window_pos
  GL_ATI: draw_buffers, texture_float, texture_mirror_once
  GL_EXT: Cg_shader, abgr, bgra, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, 
    blend_subtract, compiled_vertex_array, depth_bounds_test, direct_state_access, draw_range_elements, fog_coord, 
    framebuffer_blit, framebuffer_multisample, framebuffer_object, gpu_program_parameters, import_sync_object, 
    multi_draw_arrays, packed_depth_stencil, packed_pixels, pixel_buffer_object, point_parameters, 
    provoking_vertex, rescale_normal, secondary_color, separate_shader_objects, separate_specular_color, 
    shadow_funcs, stencil_two_side, stencil_wrap, texture3D, texture_compression_dxt1, texture_compression_s3tc, 
    texture_cube_map, texture_edge_clamp, texture_env_add, texture_env_combine, texture_env_dot3, 
    texture_filter_anisotropic, texture_format_BGRA8888, texture_lod, texture_lod_bias, texture_mirror_clamp, 
    texture_object, texture_sRGB, texture_sRGB_decode, texture_storage, texture_swizzle, timer_query, 
    vertex_array, vertex_array_bgra
  GL_IBM: rasterpos_clip, texture_mirrored_repeat
  GL_KTX_buffer_region
  GL_NVX_conditional_render
  GL_NV: ES1_1_compatibility, alpha_test, blend_minmax, blend_square, complex_primitives, copy_depth_to_color, 
    depth_clamp, fbo_color_attachments, fence, float_buffer, fog_distance, fragdepth, fragment_program, 
    fragment_program2, fragment_program_option, framebuffer_multisample_coverage, half_float, light_max_exponent, 
    multisample_filter_hint, occlusion_query, packed_depth_stencil, pixel_data_range, point_sprite, 
    primitive_restart, register_combiners, register_combiners2, texgen_reflection, texture_barrier, 
    texture_compression_vtc, texture_env_combine4, texture_expand_normal, texture_lod_clamp, texture_rectangle, 
    texture_shader, texture_shader2, texture_shader3, vertex_array_range, vertex_array_range2, vertex_program, 
    vertex_program1_1, vertex_program2, vertex_program2_option, vertex_program3
  GL_OES: compressed_paletted_texture, depth24, depth32, depth_texture, element_index_uint, fbo_render_mipmap, 
    get_program_binary, mapbuffer, packed_depth_stencil, point_size_array, point_sprite, read_format, rgb8_rgba8, 
    standard_derivatives, texture_3D, texture_float, texture_float_linear, texture_half_float, 
    texture_half_float_linear, texture_npot, vertex_array_object, vertex_half_float
  GL_S3_s3tc
  GL_SGIS: generate_mipmap, texture_lod
  GL_SGIX: depth_texture, shadow
  GL_SUN_slice_accum
  GL_WIN_swap_hint
  WGL_EXT_swap_control
OpenGL Windowed 1601x885 32 color 32 texture 60Hz NoVsync SmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00010214 Instance Name: "USB Joystick          " Product Name: "USB Joystick          "
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 3 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'USB Joystick          ' axes: 4, hats: 1, buttons: 12 (buffered)
   2: 'Mouse' axes: 3, hats: 0, buttons: 3 (buffered)
WARNING: The graphic '/Themes/simplicity_theme/Graphics/Judgment Normal 1x6.png' has frame dimensions that aren't a multiple of 2.
WARNING: The entire image is 256x55 and frame size is 256.0x9.2.
WARNING: Image quality will be much improved if you resize the graphic to 256x60, which is a frame size of 256x10.
WARNING: The graphic '/Songs/DDR PS2 FESTIVAL Japan/SANA MOLLETE NE ENTE (B.L.T.STYLE)/SANA MOLLETE NE ENTE (B.L.T.STYLE)-bg.png' has frame dimensions that aren't a multiple of 2.
WARNING: The entire image is 311x240 and frame size is 311.0x240.0.
WARNING: Image quality will be much improved if you resize the graphic to 312x240, which is a frame size of 312x240.
Mixing underruns: 1
Players joined: P1
Lost focus to: (NULL), SmartMenu.exe, StepMania-SSE2.exe, explorer.exe, firefox.exe
Top Screen: ScreenSelectMusic
Language: en
Current renderer: OpenGL
Theme: simplicity_theme

Partial log:
62:47.435: Starting thread: Streaming sound buffering
62:47.445: Sound "/Songs/DDR Wii Disney Grooves North America/M.C. Mickey/M.C. Mickey.mp3" has a start time 0.009000 seconds in the past
62:47.450: Mixing underruns: 1
62:48.309: P1 Taps: 164, P1 Jumps: 8, P1 Holds: 10, P1 Mines: 0, P1 Hands: 0, P1 Rolls: 0, P1 Lifts: 0, P1 Fakes: 0, P1 Total: 182
62:48.309: P2 Taps: 0, P2 Jumps: 0, P2 Holds: 0, P2 Mines: 0, P2 Hands: 0, P2 Rolls: 0, P2 Lifts: 0, P2 Fakes: 0, P2 Total: 1
62:48.309: P1 Last Known Difficulty: Difficulty_Hard
62:48.309: P2 Last Known Difficulty: Difficulty_Edit
62:48.309: Last known Stage: Stage_1st
62:48.351: glTexImage2D (format GL_RGBA8, 256x128, format GL_RGBA, type GL_UNSIGNED_BYTE, pixfmt 0, imgpixfmt 0)
62:48.352: RageBitmapTexture: Loaded '/Songs/DDR Wii Disney Grooves North America/Magical House Cleaning Blue or Pink/Magical House Cleaning Blue or Pink.png' (256x128); RGBA8 opaque, source 256,80;  image 256,80.

-- End of report

**Comment by SpoOkyMagician** [comment]
I recently upgraded my graphic card/power supply. I am kind of curious if it was RAM or my GPU... Gonna turn it back on and see if it still crashes...

**Comment by wolfman2000** [comment]
So...is this issue resolved?

**Comment by SpoOkyMagician** [comment]
I suppose it can be closed. I don't really encounter this much anymore. If ever. I am building the source code now so, I could test it one more time. Although, I doubt I will reproduce the crash again.
