### ISSUE TITLE
ScreenMiniMenuContext/ScreenOptionsManageProfiles is a bit broken. (Nightly 867)

### ISSUE THREAD

**Issue by SpoOkyMagician** [stepmania/stepmania#420]
https://dl.dropboxusercontent.com/u/105712481/manage_profile_issue.png

Positioning may need to be adjusted here and there.

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/commit/d28c8a8ab125f01669196ad6c0fa4e67d3e303ae
