### ISSUE TITLE
ScoreDisplay update request

### ISSUE THREAD

**Issue by sillybear** [stepmania/stepmania#421]
Requesting to update ScoreDisplay in Course mode so that it won't return a survived time(?) instead of actual score. Or maybe a UI option setting for this in to choose between time, score or percent.

**Comment by kyzentun** [comment]
Hide the ScoreDisplay and make an actor that displays the "actual score" you want, whether that's dance points, percentage, the score returned by PlayerStageStats:GetScore, or the phase of the moon.
Def.BitmapText{ Font= "Common Normal", Text= "0", JudgmentMessageCommand= function(self) self:settext(STATSMAN:GetCurStageStats():GetPlayerStageStats(pn):GetScore()) end }

**Comment by sillybear** [comment]
Sorry to misinterpret you. I just updated my previous comment. It's particularly for Oni ScoreDisplay. It says in this source and you'll notice that Oni ScoreDisplay returns a time:
http://codepad.org/i20BVCQx
