### ISSUE TITLE
Program sometimes locks up when taking screenshots

### ISSUE THREAD

**Issue by YourDesiredUsername** [stepmania/stepmania#423]
On my system (Windows 7) the program sometimes locks up after after taking a screenshot.  Sometimes it becomes responsive again after a period of time, sometimes it never recovers and has to be terminated.  The worst thing about it is that if it locks up when taking a screenshot of a result  screen an I have to terminate the process, the results are not saved.  

Here's a log excerpt of an incident today where the program did recover after about 10 seconds:

27:15.954: PushScreen: "ScreenEvaluationNormal"
27:15.961: RageBitmapTexture: Loaded '/AdditionalSongs/Dance Dance Revolution 4th Mix/Holic/Holic-bg.png' (512x256); RGBA8 opaque dither, source 320,240;  image 320,240.
27:15.961: Performing texture garbage collection.
27:15.978: Deleted old sound "/themes/_fallback/sounds/gameplayassist clap.ogg"
27:15.978: Deleted old sound "/themes/_fallback/sounds/player course attack ending.ogg"
27:15.978: Deleted old sound "/themes/_fallback/sounds/player course attack launch.ogg"
27:15.978: Deleted old sound "/themes/_fallback/sounds/player mine.ogg"
27:15.978: Deleted old sound "/themes/default-toasty/sounds/_toasty charmy.ogg"
27:15.979: Zeroing this update.  Was 4.640000
27:16.965: 122 FPS, 122 av FPS, 3094 VPF, D3D
27:18.067: Screenshot took 0.893000 seconds.
27:28.015: 2 FPS, 7 av FPS, 3096 VPF, D3D
27:28.015: Approximate sound time: driver frame 72240684, m_pImpl->m_Queue frame 0..8192 (dist 426540), closest position is 8192
27:28.211: RageTextureManager: deleting '/AdditionalSongs/Dance Dance Revolution 4th Mix/Holic/Holic.png'.
27:28.212: Performing texture garbage collection.
27:28.229: PushScreen: "ScreenProfileSave"

I believe the period from 27:18.067 to 27:28.015 is when it was locked up, and notice the extremely low framerate reported in the 27:28.015 timestamp.

This seems to mostly (or maybe only) happen when I've suspended my web browser using Resource Monitor.  I usually close my web browser completely before playing Stepmania, but sometimes I'm in a situation where I can't close it in which case I suspend it in order to free up the CPU for Stepmania (if I don't close or suspend it, I sometimes have framerate drops in Stepmania).  It's still sporadic though and not easy to replicate.  I'm currently using Waterfox for my web browser but I'm pretty sure this happened back when I was still using vanilla Firefox.  This may or may not have happened in scenarios where I didn't have my web browser suspended, but if it did, it's very rare.

One suggestion might be to save results before displaying the results screen, so that if the game locks up or crashes on the results screen, the score will still be saved.

Please let me know if I can provide any further information.

**Comment by kyzentun** [comment]
See if your browser has any graphics acceleration options that can be disabled.  It might be a case of contention over the graphics device if it really only happens when the browser is suspended in the background.

**Comment by kyzentun** [comment]
This is probably related to #668 because the log reports that it is using the D3D renderer.

**Comment by kyzentun** [comment]
Closing because this is probably a repeat of #668 and we probably won't get any followup at this point.
