### ISSUE TITLE
Modifier speed applied incorrectly via GAMESTATE

### ISSUE THREAD

**Issue by thepaparazzi** [stepmania/stepmania#424]
In StepMania 3.95 the following foreground change produces a slow transition into Reverse:
```xml
<!-- default.xml -->
<Quad
    OnCommand="%function(self)
        self:sleep(6)
        GAMESTATE:ApplyGameCommand('mod,*0.1 Reverse')
    end"
/>
```
The equivalent Lua code for beta 4a either ignores or sets speed to a arbitrarily high value, producing no transition:
```lua
-- default.lua
return Def.Quad {
    OnCommand = function(self)
        self:sleep(6)
        GAMESTATE:ApplyGameCommand('stagemod,*0.1 Reverse')
    end;
}
```
This behavior is present using the `mod` command as well.

Environment: StepMania 5.0 beta 4a Oct 19 20:50:22 2014; Mac OS X 10.9.5

**Comment by kyzentun** [comment]
The PlayerOptions API exists as an alternative to using ApplyGameCommand function because using strings for modifiers really bugged me.  See the PlayerOptions section of Docs/Luadoc/Lua.xml for a list of functions and explanation.
GAMESTATE:GetPlayerState(pn):GetPlayerOptions("ModsLevel_Song"):Reverse(1, .1)

(store the object returned by GetPlayerOptions and reuses it for convenience)

**Comment by kyzentun** [comment]
Or you could adapt this solution that I wrote when converting Iris last year.

local function iris_mod_internal(str, pn)
	local ps= GAMESTATE:GetPlayerState(pn)
	local pmods= ps:GetPlayerOptionsString('ModsLevel_Song')
	ps:SetPlayerOptions('ModsLevel_Song', pmods .. ', ' .. str)
	--GAMESTATE:ApplyGameCommand('mod,'..str, pn)
end

local function iris_mod(str)
	for i=1,2 do
		if _G['iris_diffP'..i] == 4 then
			iris_mod_internal(str, 'PlayerNumber_P' .. i)
		end
	end
end

-- This chunk is from inside the function that walks a list of mod strings, picking which one should be applied at a given time.
-- Collect all the mods that will be applied in this frame into one string.
-- Mod tweening doesn't work correctly if the mods are in seperate commands.
local mods_this_frame= {}
local function add_mod(mod_str)
	mods_this_frame[#mods_this_frame+1]= mod_str
end
local function execute_mods()
	if #mods_this_frame <= 0 then return end
	local total_mod_str= ""
	for i, ms in ipairs(mods_this_frame) do
		if #total_mod_str > 0 then
			total_mod_str= total_mod_str .. ", "
		end
		total_mod_str= total_mod_str .. ms
	end
	iris_mod(total_mod_str)
end
