### ISSUE TITLE
Dialog: "BackgroundEffect '1^0^0^1' is missing." [LUA_ERROR]

### ISSUE THREAD

**Issue by YourDesiredUsername** [stepmania/stepmania#425]
I've only seen this with one simfile so far, which is an ITG Rebirth file:  http://pastebin.com/tRW9AK37

I don't know if this is an error with the simfile or an error with the default theme?

**Comment by kyzentun** [comment]
That looks like the simfile has the wrong number of "=" in its lines for setting the parameters of a bgchange.  This post has a list of what each field means:  http://www.stepmania.com/forums/general-stepmania/show/1393#post3757

(PS:  I dislike having stuff separated by '=' like that, such an error-prone pain to edit)

**Comment by YourDesiredUsername** [comment]
I've started seeing other similar messages with other ITG Rebirth simfiles, for example "BackgroundEffect '0^0^1^1' is missing" with this file:  http://pastebin.com/wwSFqidt

It could just be one guy messing up multiple files the same way, but I wonder if this worked in some other version back when ITG Rebirth was being tested (around 2008).

**Comment by kyzentun** [comment]
Whatever the reason for the bgchange args being wrong in those simfiles, their order is not going to be changed now.  The only way to fix it is to edit those simfiles to put the args in the correct order.  The args are explained in the post I linked before.

**Comment by concubidated** [comment]
Don't think this needs to stay open. Syntax error in file caused this.
