### ISSUE TITLE
Stepmania 5 will crash if there are no songs to play in the attract screen

### ISSUE THREAD

**Issue by ZeroTheSavior** [stepmania/stepmania#426]
I'm not sure kb7 even works, but here's the link to the crash log.

http://pastebin.com/XEGdhGQy

Instead of crashing, it should probably check if there's any kb7 songs and not go to the attract screen when there aren't any.

**Comment by kyzentun** [comment]
Duplicate:  https://github.com/stepmania/stepmania/issues/415
