### ISSUE TITLE
The sound keys are not working in Linux

### ISSUE THREAD

**Issue by jmgomezpoveda** [stepmania/stepmania#427]
My laptop (Dell XPS 15) changes the volume with the keys Fn+F1, Fn+F2 and Fn+F3. However, these keys don't do anything from within StepMania 5 beta 4a while in full screen. In windowed mode there is no issue.

**Comment by jmgomezpoveda** [comment]
This issue is worse given that it is not possible to momentarily go to the desktop, as per https://github.com/stepmania/stepmania/issues/428.

**Comment by shakesoda** [comment]
yeah, don't use fullscreen. fullscreen is awful. closing this and changing the other one to a feature request for fullscreen desktop support.
