### ISSUE TITLE
Add fullscreen windowed support

### ISSUE THREAD

**Issue by jmgomezpoveda** [stepmania/stepmania#428]
In full screen mode, it is not possible to press ALT+TAB, the Windows key, or Windows key + D, to leave momentarily the game. The only option is to exit the game. Tested in StepMania 5 beta 4a.

**Comment by shakesoda** [comment]
this is just how fullscreen works in Linux, because we're not using fullscreen windowed (yet)

**Comment by shakesoda** [comment]
as said on #427, the issue is that we need fullscreen desktop support for normal interactions like volume keys and alt+tab to actually do anything. changing the title.

**Comment by roothorick** [comment]
It's a tricky topic. IIRC there's four or five ways to do it but none of them are even remotely ideal. Some fullscreen methods use ancient deprecated APIs, some have undesirable effects on the desktop; some prevent the WM/DE from trapping keystrokes that should be environment-wide; some will disable certain graphics card/driver features (GeForce V-sync is particularly picky) or severely impact performance.

What does SDL2 do? (I'm gonna make that a thing: WDSD?)

**Comment by shakesoda** [comment]
fullscreen windowed is standardized these days, I'll just see what GLFW is doing later.

**Comment by kyzentun** [comment]
As a workaround, I've been setting Stepmania's window to the full resolution I'm running at, then positioning it by hand.  Performance is good that way.

**Comment by roothorick** [comment]
...severely impact performance ON SOME CARDS. How did I flub that.

**Comment by jmgomezpoveda** [comment]
Running SM in windowed mode is a fair workaround, but just note that it has a couple of disadvantages:
- To avoid running the game in a small window in the middle of the screen, you have to run SM at the same resolution as your desktop (my system can't reach 60fps at 3200x1800, so I have to lower my desktop resolution before running SM)
- The window bar (at the top) and the task bar (at the bottom) are visible during the game.

**Comment by shakesoda** [comment]
For FS windowed we could decouple the game resolution from the window
resolution using an FBO without too much complication.


- Colby

**Comment by milistisia2** [comment]
full screen windowed? just making sure you do in fact mean that, or do you mean borderless?

**Comment by roothorick** [comment]
Just a thought: there is no distinction between fullscreen and borderless
window on Linux, other than maybe override redirect and WM hints. So the
setting would be meaningless on at least one platform.

**Comment by karai17** [comment]
+1, SM could really do with borderless window mode. One of my biggest pet peeves over the years has been the messy alt+tab to and from SM.

**Comment by Aryetis** [comment]
Could the fact that I can't use hotkeys ( volumeUp, volumeDown, contrastUp, etc) be related to this issue? Also, any news on this topic ?

**Comment by shakesoda** [comment]
Yeah, exclusive fullscreen can break stuff like that. This will either happen for 5.1 (slight chance) or 6.0 (100%), depending on if someone wants to actually dig into the fullscreen code on every platform for it...
