### ISSUE TITLE
Crash on Song Select when Using USB Joystick

### ISSUE THREAD

**Issue by pdeperio** [stepmania/stepmania#429]
Program crashes when I push a joystick button on the song select screen. Crash report below:

StepMania v5.0 beta 4a crash report (build 12, Sun Oct 19 20:50:22 EDT 2014 @ )
--------------------------------------

Architecture:   Mac OS X (i386)
Crash reason:   Bus error - nonexistent physical address at 0x00000000
Crashed thread: Main thread

Checkpoints:
Thread: GUI thread
Thread: Main thread
        RageTextureManager.cpp:134 RageTextureManager::LoadTexture(/Songs/Community Keyboard Megapack - Volume 2/(aperson) 1stSamurai/!aptitle.png).
        ScrollBar.cpp:67 
        ScrollBar.cpp:85 
        ScrollBar.cpp:97 
        RageTextureManager.cpp:134 RageTextureManager::LoadTexture(/Songs/Community Keyboard Megapack - Volume 2/(aperson) 1stSamurai/!aptitle.png).
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
Thread: Music thread
Thread: HAL I/O thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: Input thread
Thread: Streaming sound buffering

Thread: Main thread
948180c1: CFDataGetBytePtr (CoreFoundation)
004ebeda: KeyCodeToChar(unsigned short, unsigned int) 
004ebe66: InputHandler_MacOSX_HID::DeviceButtonToChar(DeviceButton, bool) 
0000c1d8: RageInput::DeviceInputToChar(DeviceInput, bool) 
00205c0e: ScreenSelectMusic::Input(InputEventPlus const&) 
000e11f7: HandleInputEvents(float) 
0046ad18: GameLoop::RunGameLoop() 
000deee2: SM_main 
004a270b: -[SMMain startGame:] 

Static log:
StepMania v5.0 beta 4a
Compiled Sun Oct 19 20:50:22 EDT 2014 @  (build 12)
Log starting 2015-01-12 20:34:05
Loading window: macosx
Model: MacBookPro10,1 (8/8)
Clock speed 2.70 GHz
Mac OS X Unknown
Memory: 16.00 GB
Sound driver: AudioUnit
Lights driver: SystemMessage
Video renderers: 'opengl'
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: NVIDIA Corporation
OGL Renderer: NVIDIA GeForce GT 650M OpenGL Engine
OGL Version: 2.1 NVIDIA-8.16.74 310.40.00.10f02
OGL Max texture size: 16384
OGL Texture units: 8
GLU Version: 1.3 MacOSX
OGL Extensions:
  GL_APPLE: aux_depth_stencil, client_storage, element_array, fence, float_pixels, flush_buffer_range, 
    flush_render, object_purgeable, packed_pixels, pixel_buffer, rgb_422, row_bytes, specular_vector, 
    texture_range, transform_hint, vertex_array_object, vertex_array_range, vertex_point_size, 
    vertex_program_evaluators, ycbcr_422
  GL_ARB: color_buffer_float, depth_buffer_float, depth_clamp, depth_texture, draw_buffers, 
    draw_elements_base_vertex, draw_instanced, fragment_program, fragment_program_shadow, fragment_shader, 
    framebuffer_object, framebuffer_sRGB, half_float_pixel, half_float_vertex, imaging, instanced_arrays, 
    multisample, multitexture, occlusion_query, pixel_buffer_object, point_parameters, point_sprite, 
    provoking_vertex, seamless_cube_map, shader_objects, shader_texture_lod, shading_language_100, shadow, sync, 
    texture_border_clamp, texture_compression, texture_compression_rgtc, texture_cube_map, texture_env_add, 
    texture_env_combine, texture_env_crossbar, texture_env_dot3, texture_float, texture_mirrored_repeat, 
    texture_non_power_of_two, texture_rectangle, texture_rg, transpose_matrix, vertex_array_bgra, vertex_blend, 
    vertex_buffer_object, vertex_program, vertex_shader, window_pos
  GL_ATI: separate_stencil, texture_env_combine3, texture_float, texture_mirror_once
  GL_EXT: abgr, bgra, bindable_uniform, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, 
    blend_subtract, clip_volume_hint, depth_bounds_test, draw_buffers2, draw_range_elements, fog_coord, 
    framebuffer_blit, framebuffer_multisample, framebuffer_multisample_blit_scaled, framebuffer_object, 
    framebuffer_sRGB, geometry_shader4, gpu_program_parameters, gpu_shader4, multi_draw_arrays, 
    packed_depth_stencil, packed_float, provoking_vertex, rescale_normal, secondary_color, 
    separate_specular_color, shadow_funcs, stencil_two_side, stencil_wrap, texture_array, 
    texture_compression_dxt1, texture_compression_s3tc, texture_env_add, texture_filter_anisotropic, 
    texture_integer, texture_lod_bias, texture_mirror_clamp, texture_rectangle, texture_sRGB, texture_sRGB_decode, 
    texture_shared_exponent, timer_query, transform_feedback, vertex_array_bgra
  GL_IBM_rasterpos_clip
  GL_NV: blend_square, conditional_render, depth_clamp, fog_distance, fragment_program2, fragment_program_option, 
    light_max_exponent, multisample_filter_hint, point_sprite, texgen_reflection, vertex_program2_option, 
    vertex_program3
  GL_SGIS: generate_mipmap, texture_edge_clamp, texture_lod
OpenGL Windowed 1138x640 32 color 16 texture 60Hz Vsync SmoothLines
WARNING: Failed to add HID element with cookie 0x2 to queue: 3758097090
WARNING: Failed to add HID element with cookie 0x2 to queue: 3758097090
WARNING: Couldn't initialize device.
Mixing underruns: 1
Players joined: P1
Top Screen: ScreenSelectMusic
Language: en
Current renderer: OpenGL
Theme: default

Partial log:
00:15.742: Performing texture garbage collection.
00:15.742: Zeroing this update.  Was 0.242425
00:15.744: glTexImage2D (format GL_RGBA4, 64x64, format GL_RGBA, type GL_UNSIGNED_BYTE, pixfmt 2, imgpixfmt 0)
00:15.744: RageBitmapTexture: Loaded '/Songs/Community Keyboard Megapack - Volume 2/(aperson) 1stSamurai/!aptitle.png' (64x64); RGBA4, source 40,44;  image 40,44.
00:15.849: glTexImage2D (format GL_RGBA8, 256x128, format GL_RGBA, type GL_UNSIGNED_BYTE, pixfmt 0, imgpixfmt 0)
00:15.849: RageBitmapTexture: Loaded '/Songs/Community Keyboard Megapack - Volume 2/(aperson) 1stSamurai/1stSamurai.png' (256x128); RGBA8 opaque, source 256,80;  image 256,80.
00:15.996: RageSound: Load "/Songs/Community Keyboard Megapack - Volume 2/(aperson) 1stSamurai/1stSamurai.mp3" (precache: 0)
00:15.996: Starting thread: Streaming sound buffering
00:15.998: Sound "/Songs/Community Keyboard Megapack - Volume 2/(aperson) 1stSamurai/1stSamurai.mp3" has a start time 0.001825 seconds in the past
00:16.745: 62 FPS, 62 av FPS, 4224 VPF, OpenGL

-- End of report

**Comment by dguzek** [comment]
It looks like this has been resolved via https://github.com/stepmania/stepmania/pull/545
Since issue#504 was closed, I think it is safe to close this issue for now, too.
