### ISSUE TITLE
StepMania v5.0 beta 4a crash - ptrace failed: Operation not permitted

### ISSUE THREAD

**Issue by latot** [stepmania/stepmania#430]
Hi, basically the game crash when i start it, this the output:

StepMania v5.0 beta 4a
Compiled 20150113 @ 21:41:12 CLST (UTC-03:00) (build 0)
Log starting 2015-01-13 21:51:48
Loading window: gtk
OS: Linux ver 031707
Crash backtrace component: x86 custom backtrace
Crash lookup component: dladdr
Crash demangle component: cxa_demangle
Runtime library: glibc 2.19
Threads library: NPTL 2.19
libavcodec: 0x373466 (3617894)
TLS is available
ALSA: Advanced Linux Sound Architecture Driver Version k3.17.7-gentoo.
ALSA Driver: 0: HDA Intel PCH [PCH], device 0: ALC663 Analog [ALC663 Analog], 1/1 subdevices avail
ALSA Driver: 0: HDA Intel PCH [PCH], device 1: ALC663 Digital [ALC663 Digital], 1/1 subdevices avail
ALSA Driver: 0: HDA Intel PCH [PCH], device 3: HDMI 0 [HDMI 0], 1/1 subdevices avail
ALSA: dsnd_pcm_hw_params_set_access: Invalid argument
Couldn't load driver ALSA-sw: SetHWParams failed
Couldn't load driver OSS: RageSoundDriver_OSS: Couldn't open /dev/dsp: No such file or directory
Couldn't load driver JACK: Couldn't connect to JACK server
Sound driver: Pulse
Lights driver: SystemMessage
Lights driver: Export

(stepmania:6483): Gtk-CRITICAL **: IA__gtk_style_detach: assertion 'style->attach_count > 0' failed
Video renderers: 'opengl'
Display: :0 (screen 0)
X server vendor: The X.Org Foundation [1.15.2.0]
Server GLX vendor: SGI [1.4]
Client GLX vendor: Mesa Project and SGI [1.4]
Paletted textures disabled: GL_EXT_paletted_texture missing.
ptrace failed: Operation not permitted
ptrace failed: Operation not permitted
ptrace failed: Operation not permitted
ptrace failed: Operation not permitted
ptrace failed: Operation not permitted

StepMania 5 has crashed.  Debug information has been output to

    /tmp/crashinfo.txt

Please report a bug at:

    https://github.com/stepmania/stepmania/issues

And this is the crashinfo.txt

StepMania v5.0 beta 4a crash report (build 0, 20150113 @ 21:41:12 CLST (UTC-03:00))
--------------------------------------

Architecture:   Unix
Crash reason:   Assertion 'iFPS != 0' failed
Crashed thread: Main thread

Checkpoints:
Thread: Main thread
        Profile.cpp:1955 
        Profile.cpp:2061 
        Profile.cpp:2116 
        Profile.cpp:2150 
        RageDisplay.cpp:908 Assertion 'iFPS != 0' failed
Thread: Decode thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)

Thread: 
0000000000891282: CrashHandler::ForceCrash(char const*) 
000000000088e41a: LowLevelWindow_X11::LowLevelWindow_X11() 
00000000009bd74f: RageDisplay_Legacy::Init(VideoModeParams const&, bool) 
00007f35df0fa60b: 
00000000009c148e: RageDisplay_Legacy_Helpers::Init() 
0000000000587b3f: main 
0000000000af5306: std::vector<Luna<UnlockManager>::RegType, std::allocator<Luna<UnlockManager>::RegType> >::_M_insert_aux(__gnu_cxx::__normal_iterator<Luna<UnlockManager>::RegType*, std::vector<Luna<UnlockManager>::RegType, std::allocator<Luna<UnlockManager>::RegType> > >, Luna<UnlockManager>::RegType const&) 
0000000000af593b: LunaUnlockManager::LunaUnlockManager() 
00007f35de7bb5b4: 
00000000005aedf4: (exe)
0000000000b0cddd: __libc_csu_init 
00007f35de7a4dd5: 
00000000005af049: (exe)

Static log:
StepMania v5.0 beta 4a
Compiled 20150113 @ 21:41:12 CLST (UTC-03:00) (build 0)
Log starting 2015-01-13 21:43:52
Loading window: gtk
OS: Linux ver 031707
Crash backtrace component: x86 custom backtrace
Crash lookup component: dladdr
Crash demangle component: cxa_demangle
Runtime library: glibc 2.19
Threads library: NPTL 2.19
libavcodec: 0x373466 (3617894)
TLS is available
ALSA: Advanced Linux Sound Architecture Driver Version k3.17.7-gentoo.
ALSA Driver: 0: HDA Intel PCH [PCH], device 0: ALC663 Analog [ALC663 Analog], 1/1 subdevices avail
ALSA Driver: 0: HDA Intel PCH [PCH], device 1: ALC663 Digital [ALC663 Digital], 1/1 subdevices avail
ALSA Driver: 0: HDA Intel PCH [PCH], device 3: HDMI 0 [HDMI 0], 1/1 subdevices avail
ALSA: dsnd_pcm_hw_params_set_access: Invalid argument
Couldn't load driver ALSA-sw: SetHWParams failed
Couldn't load driver OSS: RageSoundDriver_OSS: Couldn't open /dev/dsp: No such file or directory
Couldn't load driver JACK: Couldn't connect to JACK server
Sound driver: Pulse
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'opengl'
Display: :0 (screen 0)
X server vendor: The X.Org Foundation [1.15.2.0]
Server GLX vendor: SGI [1.4]
Client GLX vendor: Mesa Project and SGI [1.4]
Paletted textures disabled: GL_EXT_paletted_texture missing.
Language: es
Current renderer: OpenGL
Theme: default2

Partial log:
00:00.953: Compiling shader Data/Shaders/GLSL/Cel.frag
00:00.956: Compiling shader Data/Shaders/GLSL/Cel.vert
00:00.958: Compiling shader Data/Shaders/GLSL/Unpremultiply.frag
00:00.959: Compiling shader Data/Shaders/GLSL/Color burn.frag
00:00.961: Compiling shader Data/Shaders/GLSL/Color dodge.frag
00:00.962: Compiling shader Data/Shaders/GLSL/Vivid light.frag
00:00.964: Compiling shader Data/Shaders/GLSL/Hard mix.frag
00:00.968: Compiling shader Data/Shaders/GLSL/Overlay.frag
00:00.970: Compiling shader Data/Shaders/GLSL/Screen.frag
00:00.973: Compiling shader Data/Shaders/GLSL/YUYV422.frag

Obvs i try start it with the default theme, i have other (the deafult2) but i can't start it u.u

i'm using gentoo with ffmpeg 2.2.11

i try disabling the yama protection but don't works.

Thx (Sorry my poor english)

**Comment by YungDaVinci** [comment]
Does it work with the original default?
Try passing `./stepmania --theme:default` from the command line.

**Comment by latot** [comment]
Don't Works u.u the same crash info...

**Comment by shakesoda** [comment]
Looks like an OpenGL problem on your system. What does glxinfo | grep
OpenGL say?


- Colby

**Comment by latot** [comment]
glxinfo | grep -i opengl

OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.4, 256 bits)
OpenGL version string: 3.0 Mesa 10.2.8
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:

**Comment by shakesoda** [comment]
Yeah, I've never had any luck running SM on llvmpipe. You need something HW
accelerated.


- Colby

**Comment by latot** [comment]
Well, i tested changing llvmpipe to softpipe, and changing gallium to software rasterizer, and i test run SM with optirun with nvidia drivers but in all of these cases i received the same error u.u
i checked my packages of intel drivers and the hw accelerated is enabled and working.

**Comment by kyzentun** [comment]
Side note:  If you're not using the bundled ffmpeg, you will crash on videos.

**Comment by latot** [comment]
Yep, well i try with the option enable and disable, and i got the same error u.u

**Comment by latot** [comment]
Well, I restarted the computer and recompiled the SM and it works again :D but i don't know the solution to this problem in specific u.u but now the problem appears in other place for other reason i think, i'll make a new issue for that with the info, thx for all.
