### ISSUE TITLE
when closing Fraps, SM crashes

### ISSUE THREAD

**Issue by chewiiii** [stepmania/stepmania#434]
StepMania v5.0 beta 4a crash report (build 1, 20141019 @ 19:58:47 Central Daylight Time)
--------------------------------------

Crash reason: Access Violation

Thread: Main thread
        GraphicsWindow.cpp:179 00340442, 642, 00000002, 00000000
        GraphicsWindow.cpp:54 00340442, 7, 00000000, 00000000
        GraphicsWindow.cpp:179 00340442, 7, 00000000, 00000000
        Screen.cpp:164 ScreenMessage(SM_UpdateTextInfo)
        Screen.cpp:164 ScreenMessage(SM_UpdateTextInfo)
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
Thread: Mixer thread
Thread: Music thread
        RageFileDriverDirectHelpers.cpp:227 C:/Games/StepMania 5/Themes/_fallback/Sounds/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Kyle/AppData/Roaming/StepMania 5/Themes/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Kyle/AppData/Roaming/StepMania 5/Themes/_fallback/Sounds/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Kyle/AppData/Roaming/StepMania 5/Themes/_fallback/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Kyle/AppData/Roaming/StepMania 5/Themes/Obelisk/Sounds/*
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
        InputHandler_DirectInput.cpp:750 
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
Thread: Streaming sound buffering

67521ea0: StepMania-SSE2!00000000
005bbaec: void LowLevelWindow_Win32::SwapBuffers(void) [00400000+1bbae0+c]
005a1a46: void GameLoop::RunGameLoop(void) [00400000+1a1880+1c6]
00245e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [00240000+5dfb+48]
00245ec4: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > [00240000+5ebb+9]
005a5fd9: main() [00400000+1a5120+eb9]
00352e2b: MSVCR90!unlock [00330000+22e16+15]
003536c5: MSVCR90!_set_flsgetvalue [00330000+236b6+f]
003538b3: MSVCR90!initptd [00330000+23753+160]
005c1964: int GetWin32CmdLine(char * * &) [00400000+1c18b0+b4]
005c16e5: WinMain@16() [00400000+1c16d0+15]
007b2b9f: __tmainCRTStartup() [00400000+3b2a5f+140]
77710b91: ntdll!RtlInitializeExceptionChain [776c0000+50b37+5a]

Static log:
StepMania v5.0 beta 4a
Compiled 20141019 @ 19:58:47 Central Daylight Time (build 1)
Log starting 2015-01-16 18:36:13
Loading window: win32
Windows 6.2 (Win8) build 9200 []
Memory: 3528mb total, 4095mb swap (1776mb swap avail)
Video driver: AMD Radeon(TM) R2 Graphics [Advanced Micro Devices, Inc.]
              13.351.1105.1005, 6-16-2014 [pci\ven_1002&dev_9853&subsys_22cd103c]
Drive: "HGST    HTS545050A7E680" Driver: amdsata DMA: N/A
Drive: "hp      DVDRW  GUB0N    UB00" Driver: amdsata DMA: N/A
Sound device 0: Speaker/HP (Realtek High Defini, 6.3, MID 1, PID 100 
DirectSound Driver: Primary Sound Driver
DirectSound Driver: Speaker/HP (Realtek High Definition Audio) {0.0.0.00000000}.{36097cfb-e19f-42a7-a22e-a54fc5ded009}
DirectSound sample rates: 100..200000 (continuous)
Software mixing at 44100 hz
Sound driver: DirectSound-sw
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'opengl,d3d'
Mode: ICD 32 (888) 8 alpha 24 depth 8 stencil 
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: ATI Technologies Inc.
OGL Renderer: AMD Radeon(TM) R2 Graphics
OGL Version: 4.3.12798 Compatibility Profile Context 13.351.1105.1005
OGL Max texture size: 16384
OGL Texture units: 8
GLU Version: 1.2.2.0 Microsoft Corporation
OGL Extensions:
  GL_AMDX_debug_output
  GL_AMD: blend_minmax_factor, conservative_depth, debug_output, depth_clamp_separate, draw_buffers_blend, 
    framebuffer_sample_positions, gcn_shader, gpu_shader_int64, interleaved_elements, multi_draw_indirect, 
    name_gen_delete, occlusion_query_event, performance_monitor, pinned_memory, query_buffer_object, 
    sample_positions, seamless_cubemap_per_texture, shader_atomic_counter_ops, shader_stencil_export, 
    shader_stencil_value_export, shader_trace, shader_trinary_minmax, sparse_texture, stencil_operation_extended, 
    texture_cube_map_array, texture_texture4, transform_feedback3_lines_triangles, transform_feedback4, 
    vertex_shader_layer, vertex_shader_viewport_index
  GL_ARB: ES2_compatibility, ES3_compatibility, arrays_of_arrays, base_instance, blend_func_extended, 
    clear_buffer_object, clear_texture, color_buffer_float, compatibility, compressed_texture_pixel_storage, 
    compute_shader, conservative_depth, copy_buffer, copy_image, debug_output, depth_buffer_float, depth_clamp, 
    depth_texture, draw_buffers, draw_buffers_blend, draw_elements_base_vertex, draw_indirect, draw_instanced, 
    explicit_attrib_location, explicit_uniform_location, fragment_coord_conventions, fragment_layer_viewport, 
    fragment_program, fragment_program_shadow, fragment_shader, framebuffer_no_attachments, framebuffer_object, 
    framebuffer_sRGB, geometry_shader4, get_program_binary, gpu_shader5, gpu_shader_fp64, half_float_pixel, 
    half_float_vertex, imaging, instanced_arrays, internalformat_query, internalformat_query2, invalidate_subdata, 
    map_buffer_alignment, map_buffer_range, multi_bind, multi_draw_indirect, multisample, multitexture, 
    occlusion_query, occlusion_query2, pixel_buffer_object, point_parameters, point_sprite, 
    program_interface_query, provoking_vertex, query_buffer_object, sample_shading, sampler_objects, 
    seamless_cube_map, seamless_cubemap_per_texture, separate_shader_objects, shader_atomic_counters, 
    shader_bit_encoding, shader_group_vote, shader_image_load_store, shader_image_size, shader_objects, 
    shader_precision, shader_stencil_export, shader_storage_buffer_object, shader_subroutine, shader_texture_lod, 
    shading_language_100, shading_language_420pack, shading_language_packing, shadow, shadow_ambient, 
    stencil_texturing, sync, tessellation_shader, texture_border_clamp, texture_buffer_object, 
    texture_buffer_object_rgb32, texture_buffer_range, texture_compression, texture_compression_bptc, 
    texture_compression_rgtc, texture_cube_map, texture_cube_map_array, texture_env_add, texture_env_combine, 
    texture_env_crossbar, texture_env_dot3, texture_float, texture_gather, texture_mirror_clamp_to_edge, 
    texture_mirrored_repeat, texture_multisample, texture_non_power_of_two, texture_query_levels, 
    texture_query_lod, texture_rectangle, texture_rg, texture_rgb10_a2ui, texture_snorm, texture_storage, 
    texture_storage_multisample, texture_view, timer_query, transform_feedback2, transform_feedback3, 
    transform_feedback_instanced, transpose_matrix, uniform_buffer_object, vertex_array_bgra, vertex_array_object, 
    vertex_attrib_64bit, vertex_attrib_binding, vertex_buffer_object, vertex_program, vertex_shader, 
    vertex_type_10f_11f_11f_rev, vertex_type_2_10_10_10_rev, viewport_array, window_pos
  GL_ATI: draw_buffers, envmap_bumpmap, fragment_shader, separate_stencil, texture_compression_3dc, 
    texture_env_combine3, texture_float, texture_mirror_once
  GL_EXT: abgr, bgra, bindable_uniform, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, 
    blend_subtract, compiled_vertex_array, copy_buffer, copy_texture, depth_bounds_test, direct_state_access, 
    draw_buffers2, draw_instanced, draw_range_elements, fog_coord, framebuffer_blit, framebuffer_multisample, 
    framebuffer_object, framebuffer_sRGB, geometry_shader4, gpu_program_parameters, gpu_shader4, histogram, 
    multi_draw_arrays, packed_depth_stencil, packed_float, packed_pixels, pixel_buffer_object, point_parameters, 
    provoking_vertex, rescale_normal, secondary_color, separate_specular_color, shader_image_load_store, 
    shader_integer_mix, shadow_funcs, stencil_wrap, subtexture, texgen_reflection, texture3D, texture_array, 
    texture_buffer_object, texture_compression_bptc, texture_compression_latc, texture_compression_rgtc, 
    texture_compression_s3tc, texture_cube_map, texture_edge_clamp, texture_env_add, texture_env_combine, 
    texture_env_dot3, texture_filter_anisotropic, texture_integer, texture_lod, texture_lod_bias, 
    texture_mirror_clamp, texture_object, texture_rectangle, texture_sRGB, texture_sRGB_decode, 
    texture_shared_exponent, texture_snorm, texture_storage, texture_swizzle, timer_query, transform_feedback, 
    vertex_array, vertex_array_bgra, vertex_attrib_64bit
  GL_IBM_texture_mirrored_repeat
  GL_KHR_debug
  GL_KTX_buffer_region
  GL_NV: blend_square, conditional_render, copy_depth_to_color, copy_image, depth_buffer_float, 
    explicit_multisample, float_buffer, half_float, primitive_restart, texgen_reflection, texture_barrier
  GL_SGIS: generate_mipmap, texture_edge_clamp, texture_lod
  GL_SUN_multi_draw_arrays
  GL_WIN_swap_hint
  WGL_EXT_swap_control
OpenGL Windowed 854x480 32 color 32 texture 60Hz Vsync SmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 2 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Mouse' axes: 3, hats: 0, buttons: 5 (buffered)
Paletted textures disabled: GL_EXT_paletted_texture missing.
WARNING: Banner cache for '/Songs/chewi pack 02/Hello Kitty/Hello Kitty.png' wasn't loaded
WARNING: Banner cache for '/Songs/chewi pack 02/Hello Kitty/Hello Kitty.png' wasn't loaded
WARNING: Banner cache for '/Songs/chewi pack 02/Hello Kitty/Hello Kitty.png' wasn't loaded
WARNING: No options in row "list,BatLives" were selected, and no fallback row found; selected entry 0
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: RunCommands: command is unset or nil
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: RunCommands: command is unset or nil
WARNING: Banner cache for '/Songs/chewi pack 02/Hello Kitty/Hello Kitty.png' wasn't loaded
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: RunCommands: command is unset or nil
WARNING: Banner cache for '/Songs/chewi pack 02/Hello Kitty/Hello Kitty.png' wasn't loaded
WARNING: Banner cache for '/Songs/chewi pack 02/Hello Kitty/Hello Kitty.png' wasn't loaded
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: Background missing: Jai Ho (You Are My Destiny).avi
WARNING: RunCommands: command is unset or nil
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: RunCommands: command is unset or nil
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: RunCommands: command is unset or nil
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: RunCommands: command is unset or nil
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: RunCommands: command is unset or nil
WARNING: Banner cache for '/Songs/DanceDanceRevolution (2014)/HeartLatte/HeartLatte.png' wasn't loaded
WARNING: Banner cache for '/Songs/DanceDanceRevolution (2014)/HeartLatte/HeartLatte.png' wasn't loaded
WARNING: Banner cache for '/Songs/chewi pack 02/Hello Kitty/Hello Kitty.png' wasn't loaded
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: RunCommands: command is unset or nil
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: RunCommands: command is unset or nil
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: Compiling "return function(self, param) 	if PREFSMAN:GetPreference("PercentageScoring") then 		self:visible(false) 	else 		if self:GetParent():GetName() == "ScoreP1" then 			self:diffuse(PlayerColor(PLAYER_1); \	": [string "ScoreDisplayNormal::TextOnCommand"]:1: ')' expected near ';'
WARNING: RunCommands: command is unset or nil
WARNING: HID devices changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: polling for joystick changes
WARNING: Banner cache for '/Songs/chewi pack 02/Hello Kitty/Hello Kitty.png' wasn't loaded
WARNING: Banner cache for '/Songs/chewi pack 02/Hello Kitty/Hello Kitty.png' wasn't loaded
Mixing underruns: 1
Players joined: P1
Lost focus to: (NULL), HelpPane.exe, OpenProcess (Access is denied.), StepMania-SSE2.exe, chrome.exe, explorer.exe
Top Screen: ScreenEdit
Language: en
Current renderer: OpenGL
Theme: Obelisk

Partial log:
53:09.239: 18 FPS, 16 av FPS, 6884 VPF, OpenGL
53:10.278: 17 FPS, 16 av FPS, 6884 VPF, OpenGL
53:11.320: 16 FPS, 16 av FPS, 6878 VPF, OpenGL
53:12.354: 14 FPS, 16 av FPS, 6884 VPF, OpenGL
53:13.370: 15 FPS, 17 av FPS, 6884 VPF, OpenGL
53:14.385: 15 FPS, 17 av FPS, 6884 VPF, OpenGL
53:15.395: 15 FPS, 17 av FPS, 6884 VPF, OpenGL
53:16.145: WM_ACTIVATE (0, 0): has focus
53:16.185: App has focus
53:16.530: 16 FPS, 15 av FPS, 6884 VPF, OpenGL

-- End of report

**Comment by shakesoda** [comment]
sorry, we've got pretty much no way of knowing what FRAPS might be doing to SM. try OBS or bandicam. OBS works well for me, personally.

**Comment by shakesoda** [comment]
Oh, you also might want to try running SM in D3D mode (in preferences.ini, set VideoRenderers=d3d). FRAPS sucks with OpenGL.

**Comment by lomdr** [comment]
Probably my only complaint since 3.9, but maybe have it as a setable option in the graphics option in game or if  that's not possible have either 2 different executables for each mode or have an external app set it between the 2 modes.
