### ISSUE TITLE
D-Force dance pad automappings

### ISSUE THREAD

**Issue by shakesoda** [stepmania/stepmania#435]
We should get these in before 5.0.5. Straight from their email to me:

```
Back=Joy1_B7:Joy1_B9 (B7 is for the X key and B9 is for the BACK button on top. B7 can also funtion as upleft in solo mode)
Down=Joy1_B2
Left=Joy1_B3
Right=Joy1_B4
Start=Joy1_B8:Joy1_B10 (B8 is for the O key and B10 is for the START button on top. B8 can also funtion as upright in solo mode)
Up=Joy1_B1
```

I've got some of the older model to test, hopefully they report the same.

**Comment by kyzentun** [comment]
Stick this code in at this line and fix the regex to match what the pad reports and it should work.
https://github.com/stepmania/stepmania/blob/master/src/InputMapper.cpp#L429

	   AutoMappings(
		"dance",
		"D-Force-Shakesoda-to-change-this",
		"D-Force",
		AutoMappingEntry(0, JOY_BUTTON_1, DANCE_BUTTON_UP, false),
		AutoMappingEntry(0, JOY_BUTTON_2, DANCE_BUTTON_DOWN, false),
		AutoMappingEntry(0, JOY_BUTTON_3, DANCE_BUTTON_LEFT, false),
		AutoMappingEntry(0, JOY_BUTTON_4, DANCE_BUTTON_RIGHT, false),
		AutoMappingEntry(0, JOY_BUTTON_7, DANCE_BUTTON_UPLEFT, false),
		AutoMappingEntry(0, JOY_BUTTON_8, DANCE_BUTTON_UPRIGHT, false),
		AutoMappingEntry(0, JOY_BUTTON_9, GAME_BUTTON_BACK, false),
		AutoMappingEntry(0, JOY_BUTTON_10, GAME_BUTTON_START, false)
	   ),

**Comment by shakesoda** [comment]
Added in b07dc24
