### ISSUE TITLE
Weird Fatal Error

### ISSUE THREAD

**Issue by Musicisgood** [stepmania/stepmania#438]
Hi, 

I was curious if anyone knew how to fix this weird error I keep getting. I tried uninstalling/reinstalling the program, and I still get the fatal error even though the file is gone... 

The folder "Songs/yuugaa" appears to be a song folder. All song folders must reside in a group folder. For example, "Songs/Originals/My Song" will contain the music file (MP3, OGG...), the steps file (.sm, .dwi, .ksf...) and other related files.

**Comment by kyzentun** [comment]
The error is telling you that there is a folder named "yuugaa" inside your Songs folder that has music files in it.  Stepmania is very strict about the layout of the Songs folder, and requires songs to be inside of groups.

**Comment by Musicisgood** [comment]
That's what I figured at first, but whenever I click on the Song folder the "yuugaa" folder isn't visible.

**Comment by kyzentun** [comment]
That's weird, I don't use Windows, so I don't know how to reveal hidden folders, but try looking for a way to reveal hidden folders or use the Find Files or Folders thing to search for a folder with that name.

**Comment by Musicisgood** [comment]
Oh nevermind, I found the solution to the problem. For some reason there were two separate folders for Stepmania itself =\ Thanks for your help though!

**Comment by kyzentun** [comment]
All is well that ends well.  As a side note, you can put songs and stuff in %APPDATA/StepMania 5.0/Songs/ if you prefer that over putting them in the Stepmania main folder.  (makes updating easier)
