### ISSUE TITLE
32 bit Linux Build Issue

### ISSUE THREAD

**Issue by rjfoertsch** [stepmania/stepmania#441]
I built stepmania from the master on a new 32 bit Debian 7 system (Linux debian 3.2.0-4-686-pae #1 SMP Debian 3.2.65-1 i686 GNU/Linux, Debian 7.8) and ran into a build issue.  The solution was to add CPPFLAGS="-lrt" and CXXFLAGS="-lrt" or you would end up with the following errors on build. 

ArchHooks_Unix.cpp:(.text+0x95e): undefined reference to `clock_gettime'
ArchHooks_Unix.cpp:(.text+0x9e3): undefined reference to `clock_getres'

I assume these might be useful to add to the default configuration?

Let me know if you have any questions.

Robert.

**Comment by kyzentun** [comment]
If you add "-lrt" to AM_CXXFLAGS in src/Makefile.am and rebuild (make distclean, autogen, configure, make), does it build successfully for you?
I don't have a 32 bit debian system to test on, my system is 64 bit (possibly unrelated?) and doesn't need -lrt in the flags.

**Comment by rjfoertsch** [comment]
Yep, after adding -lrt as you described, the build completed successfully for me, no problems whatsoever.

**Comment by kyzentun** [comment]
Apparently adding -lrt like that breaks building on some 64bit linux systems.  (Travis.ci's build system hits an error, but my 64bit debian jessie system does not)
So this needs a real solution, which I don't know how to implement.
If you can, join the IRC dev channel #stepmania-devs on irc.freenode.net to discuss it with roothorick and figure out a fix.

**Comment by roothorick** [comment]
Checked in a proper fix, does this work for you @rjfoertsch ?

**Comment by rjfoertsch** [comment]
I tried master, and yes, it did work on my system.  Thanks!
