### ISSUE TITLE
user data locations on OS X

### ISSUE THREAD

**Issue by dguzek** [stepmania/stepmania#448]
The recent commits to how _version_ is handled internally have caused duplicate user data directories to exist on OS X.  The old are ignored in favor of the new, which is expected, but it leaves unexpecting users in a lurch since nothing carries over, and I think it needs to be addressed in some way before the next release.

**old locations:**
    ~/Library/Application Support/StepMania 5/
    ~/Library/Caches/StepMania 5/
    ~/Library/Logs/StepMania 5/
    ~/Library/Preferences/StepMania 5/

**new locations:**
    ~/Library/Application Support/StepMania 5.0/
    ~/Library/Caches/StepMania 5.0/
    ~/Library/Logs/StepMania 5.0/
    ~/Library/Preferences/StepMania 5.0/

As a secondary issue, the new Kepmaps.ini file that was generated in _/Preferences/StepMania 5.0/_ had no keys mapped.

**Comment by kyzentun** [comment]
I knew it!  I wrote a thread that listed data directories, and I realized this was going to come up.  This definitely needs to be addressed, preferably by having Stepmania quietly copy stuff over on install or something.

**Comment by roothorick** [comment]
Where does this chain reaction end?

In the short term let's just hardcode user data paths back to where they were.

Long term... what should 5.1's user data folder be? 5.2? 6.0? If the same, how do we address the issue of theme breakage from 5.0 to 5.1 but they're all sitting in the same folder? If different, what will the user be expecting? What do we copy and when?

**Comment by kyzentun** [comment]
We could check for an APIVersion metric in the theme and use that.  If it's not there, treat it as 5.0.

**Comment by roothorick** [comment]
The short term situation has been addressed.

**Comment by kyzentun** [comment]
I'm dumb and should read the status before changing the milestone.  I only saw that it was still open.

For what it's worth, Wesnoth has different folders for 1.8 and 1.10, so they apparently decided to change folders with their minor version numbers.

We could load themes from all 5.x folders, and somehow tag them with the folder they were loaded from and show that tag in selection or something.  That sounds kind of cumbersome though.
6.0 will definitely need its own folder, everything will break.

**Comment by dguzek** [comment]
Can this issue be considered resolved as of now?  If there's some aspect of it I'm missing, and it is still an issue, then keep it it open.  Otherwise, I'm all for cleaning house and closing dead issues.

**Comment by concubidated** [comment]
Looks like this can be considered closed. Feel free to reopen if there any objections.
