### ISSUE TITLE
Spanish translation is incomplete

### ISSUE THREAD

**Issue by Flameshadowxeroshin** [stepmania/stepmania#451]
I tried to do a bit of it myself, but it's incredibly incomplete and my Spanish isn't good enough to fix it.

**Comment by wolfman2000** [comment]
#457 addresses some of this.

**Comment by TheFireRed** [comment]
I think I will work on this. I provided with a basic translation to a SM5 theme some days ago.

**Comment by kyzentun** [comment]
If you read the forums,  Jose_Varela is already working on the Spanish translation.
http://www.stepmania.com/forums/news/show/1776#post4596

**Comment by TheFireRed** [comment]
Um... I'm not really comfortable with his translation. There are a lot of spelling mistakes and doesn't look professional at all.

**Comment by kyzentun** [comment]
Okay, then I'll use what you make.

**Comment by kyzentun** [comment]
Post on the forum, argue it out with him.  I can't spell check spanish and I don't know who to go with.

**Comment by TheFireRed** [comment]
Done. I have also posted some WIP screenshots. If you need the translation before the 12th, I'll continue with the process right away.

**Comment by TheFireRed** [comment]
I finished translating all strings. I'm currently editing the lines for screen fitting and the like.
