### ISSUE TITLE
[Edit Mode] Change Step Recording start behavior

### ISSUE THREAD

**Issue by sillybear** [stepmania/stepmania#454]
I'm requesting to change it so that recording start at exactly 1 measure before the current beat or selected measures. It's difficult to catch up the first few notes while transcribing stepcharts from external sources (youtube, nico or its exported videos in any video editing programs), especially in doubles. Currently it starts at 2-3 beats(?) before the current beat or selected measures so it's very short and confusing because my hands need to prepare and get to my key inputs immediately. In SM3.9, recording starts at exactly 1 measure before the current beat or selected measures.

**Comment by kyzentun** [comment]
I spent more time waiting for stepmania to compile than I did writing the code.
https://github.com/stepmania/stepmania/commit/c7ffbb34532c141720e131ffc606287985171cd3

**Comment by sillybear** [comment]
I was expecting that those options are times in beats, not times in seconds. It's easier to transcribe steps from imported videos in like Sony Vegas if the lead-in time is in beats. I have no idea on how to catch-up first few notes during recording when the lead-in time is in seconds, especially if songs have different starting bpms.
