### ISSUE TITLE
[Edit mode] Option/possibility to not hold notes during record mode (CTRL+R)

### ISSUE THREAD

**Issue by silverkorn** [stepmania/stepmania#460]
Feature request:
I know we can clean it up once done but it's irritating to do each time during a "choreography" development, including the holds visual pollution. :rage1: 

Thanks! :smile:

**Comment by kyzentun** [comment]
The current behavior is to place a hold if a panel is held for more than 0.3 seconds.
Do you want an on/off switch, or do you want to be able to change that 0.3 seconds value to any value you want?

**Comment by silverkorn** [comment]
It was more to turn it on/off, but I guess giving a specific threshold could be more desirable for flexibility.

Where would you judge this option useful, edit mode only or "game wide"?

As said, I personally would love this for the edit mode but, again, for flexibility, it could be good as a "game wide" option (Input options?).

BTW, Thanks for your quick interaction!

**Comment by kyzentun** [comment]
It only make sense in edit mode, since we're talking about the record mode part of edit mode.
The timing window for gameplay to decide that you've dropped a hold is something completely different and controlled by the TimingWindowSecondsHold preference.

**Comment by silverkorn** [comment]
Yeah, I've seen there a ton scriptable things for the gameplay/themes! :smiley:
I'll wait and test once ready (if you accept to work on it).
Thanks again!

**Comment by kyzentun** [comment]
Edit mode isn't scriptable by themes, everything in it is hardcoded and changing it requires rebuilding,  and I don't have a way to make Windows builds, so having you test it isn't an option.  I'll just have to make sure it works right, and it'll be in the next release.
The hard part is finding a place to put the number on the screen so you know what it is when you're changing it.  The screen is already packed pretty full of status stuff.

**Comment by kyzentun** [comment]
And done.  https://github.com/stepmania/stepmania/commit/cb379505d504bdf2daf0df5db662b5ed266937d2
Simple requests make me happy.  Look for it in Saturday's release, or pull new source from github if you build from source.
(you can still comment more, I just typically close resolved issues)

**Comment by silverkorn** [comment]
Wow, thanks!
The worst is that it's been more than a year that I was irritated about this!
Shame on me not for not asking earlier.
