### ISSUE TITLE
Backslash in keymap is saved literally.

### ISSUE THREAD

**Issue by kyzentun** [stepmania/stepmania#469]
If the backslash key is mapped, it is written to Keymaps.ini as a literal backslash, which causes the lines to be joined together when the ini file is loaded, which makes that key and the one after it get mapped wrong.

**Comment by shakesoda** [comment]
Easiest solution would be to write it into the file as \\

**Comment by kyzentun** [comment]
No, that's the problem.  It is written to the file as a literal backslash, and then the ini reader interprets the backslash to mean that the two lines are joined.  It needs to be written to the file as a string that is correctly mapped, the same way space is handled.

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/commit/f1229d29cb647b26150bc3926d0cff2ef14c29bd
