### ISSUE TITLE
Sync overlay's bpm segment list different from song's

### ISSUE THREAD

**Issue by YungDaVinci** [stepmania/stepmania#471]
Steps:
1. Change the bpm (with F7 and F8) on the current beat so that it's different from the song's bpm.
2. Go down a beat, and do the same thing.
3. Go back up a beat, and change the bpm to the song bpm.
4. Go down, and change the bpm to the song bpm.

**Comment by kyzentun** [comment]
This mistake of mine is why we are releasing 5.0.6 right on the tail of 5.0.5.
Fixed in this commit:  https://github.com/stepmania/stepmania/commit/f1229d29cb647b26150bc3926d0cff2ef14c29bd

**Comment by roothorick** [comment]
I thought we were still doing the little-letter notation for hotfix releases...?

**Comment by kyzentun** [comment]
@roothorick: @freem and @shakesoda said that calling it 5.0.6 would be best for getting everyone to replace their 5.0.5 with it.  Since this is a bug that will affect everyone editing bpms (or other timing segments, bpm changes are the most common), making sure people get the fix is important.
