### ISSUE TITLE
Game Crashes on 

### ISSUE THREAD

**Issue by zencornhopper** [stepmania/stepmania#472]

**Comment by zencornhopper** [comment]
I recently downloaded StepMania and upon starting it up the first time, all I get is a white screen and then a crash. I can't figure out what is the cause, so I thought I would turn here.

I'll put the crash report down here since I don't know where else to

-------------------------------------------------------------------------------------------------------------------------------


StepMania v5.0 beta 4a crash report (build 1, 20141019 @ 19:58:47 Central Daylight Time)
--------------------------------------

Crash reason: Access Violation

Thread: Main thread
        GraphicsWindow.cpp:179 000D09F0, 512, 00000000, 01ae011c
        GraphicsWindow.cpp:54 000D09F0, 49341, 00000000, 00000000
        GraphicsWindow.cpp:179 000D09F0, 49341, 00000000, 00000000
        GraphicsWindow.cpp:54 000D09F0, 15, 00000000, 00000000
        GraphicsWindow.cpp:179 000D09F0, 15, 00000000, 00000000
Thread: Decode thread
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)

04f5a645: atioglxx!04f10000
76f44a0b: ntdll!LdrGetDllHandleByName [76ef0000+549a0+6b]
76f44a0b: ntdll!LdrGetDllHandleByName [76ef0000+549a0+6b]
74e27cc2: KERNELBASE!GetModuleHandleExA [74e10000+17999+329]
74e60e24: KERNELBASE!InterlockedExchangeAdd [74e10000+4f808+161c]
74e60e24: KERNELBASE!InterlockedExchangeAdd [74e10000+4f808+161c]
05b14233: atioglxx!04f10000
05b14b96: atioglxx!04f10000
05adecb9: atioglxx!04f10000
04f14ade: atioglxx!eglCopyBuffers [04f10000+4a60+7e]
05010e47: atioglxx!04f10000
7510e969: USER32!GetClassNameA [750f0000+1e902+67]
7510e97e: USER32!GetClassNameA [750f0000+1e902+7c]
059baa81: atioglxx!04f10000
059ba568: atioglxx!04f10000
04f2b497: atioglxx!DrvSwapBuffers [04f10000+1b200+297]
76f317d1: ntdll!RtlAllocateHeap [76ef0000+41240+591]
76f31354: ntdll!RtlAllocateHeap [76ef0000+41240+114]
76f4443b: ntdll!RtlAppendUnicodeToString [76ef0000+541a0+29b]
76f444ba: ntdll!RtlAppendUnicodeToString [76ef0000+541a0+31a]
0066006f: void RageFileDriverMountpoints::LoadFromDrivers(class std::vector<struct LoadedDriver *,class std::allocator<struct LoadedDriver *> > const &) [00400000+25fff0+7f]
00620062: void LifeMeterTime::Load(class PlayerState const *,class PlayerStageStats *) [00400000+21ffa0+c2]
76f32796: ntdll!RtlFreeHeap [76ef0000+41f10+886]
76f31309: ntdll!RtlAllocateHeap [76ef0000+41240+c9]
76f39980: ntdll!RtlInitializeCriticalSectionEx [76ef0000+498b0+d0]
76f320ca: ntdll!RtlFreeHeap [76ef0000+41f10+1ba]
76f39ae2: ntdll!RtlInitializeCriticalSection [76ef0000+49ad0+12]
74e31568: KERNELBASE!FindFirstFileW [74e10000+214f8+70]
74e314d4: KERNELBASE!FindFirstFileExW [74e10000+21191+343]
74e314ed: KERNELBASE!FindFirstFileExW [74e10000+21191+35c]
00620062: void LifeMeterTime::Load(class PlayerState const *,class PlayerStageStats *) [00400000+21ffa0+c2]
76f317d1: ntdll!RtlAllocateHeap [76ef0000+41240+591]
76f32796: ntdll!RtlFreeHeap [76ef0000+41f10+886]
76f320ca: ntdll!RtlFreeHeap [76ef0000+41f10+1ba]
74e315f2: KERNELBASE!FindClose [74e10000+2157e+74]
76f2c80c: ntdll!ZwQueryInformationProcess [76ef0000+3c800+c]
74e73ca5: KERNELBASE!GetErrorMode [74e10000+63c8d+18]
76f2c83c: ntdll!NtSetInformationProcess [76ef0000+3c830+c]
74e24615: KERNELBASE!SetErrorMode [74e10000+145e0+35]
74fc7a92: KERNEL32!WriteConsoleOutputW [74fa0000+279d4+be]
74fb3ebe: KERNEL32!GetLongPathNameW [74fa0000+13baa+314]
76f39897: ntdll!RtlFindCharInUnicodeString [76ef0000+491f0+6a7]
76f39828: ntdll!RtlFindCharInUnicodeString [76ef0000+491f0+638]
76f507e4: ntdll!LdrGetDllHandleEx [76ef0000+60710+d4]
76f508e8: ntdll!LdrGetDllHandleEx [76ef0000+60710+1d8]
76f382d2: ntdll!RtlNtStatusToDosError [76ef0000+45f90+2342]
76f50983: ntdll!LdrGetDllHandleEx [76ef0000+60710+273]
76f4b025: ntdll!RtlCompareUnicodeString [76ef0000+5b000+25]
76f13ffb: ntdll!TpReleaseWork [76ef0000+23e10+1eb]
76f13885: ntdll!RtlDestroyHeap [76ef0000+23260+625]
76f13fbd: ntdll!TpReleaseWork [76ef0000+23e10+1ad]
76f3892f: ntdll!RtlFindActivationContextSectionString [76ef0000+48740+1ef]
74fb1deb: KERNEL32!FindActCtxSectionStringWWorker [74fa0000+11d4c+9f]
74fb1dfe: KERNEL32!FindActCtxSectionStringWWorker [74fa0000+11d4c+b2]
74fb4caa: KERNEL32!GetSystemWindowsDirectoryW [74fa0000+14c4f+5b]
73f129eb: MSVCR90!_getmainargs [73ef0000+22793+258]
73f129c2: MSVCR90!_getmainargs [73ef0000+22793+22f]
0066006f: void RageFileDriverMountpoints::LoadFromDrivers(class std::vector<struct LoadedDriver *,class std::allocator<struct LoadedDriver *> > const &) [00400000+25fff0+7f]
00620062: void LifeMeterTime::Load(class PlayerState const *,class PlayerStageStats *) [00400000+21ffa0+c2]
0066006f: void RageFileDriverMountpoints::LoadFromDrivers(class std::vector<struct LoadedDriver *,class std::allocator<struct LoadedDriver *> > const &) [00400000+25fff0+7f]
00620062: void LifeMeterTime::Load(class PlayerState const *,class PlayerStageStats *) [00400000+21ffa0+c2]
76f3a24c: ntdll!RtlImageNtHeaderEx [76ef0000+49fe0+26c]
76f317d1: ntdll!RtlAllocateHeap [76ef0000+41240+591]
76f3a57e: ntdll!RtlImageNtHeaderEx [76ef0000+49fe0+59e]
76f31309: ntdll!RtlAllocateHeap [76ef0000+41240+c9]
76f31354: ntdll!RtlAllocateHeap [76ef0000+41240+114]
76f341a2: ntdll!RtlFreeHeap [76ef0000+41f10+2292]
76f33e03: ntdll!RtlFreeHeap [76ef0000+41f10+1ef3]
76f31309: ntdll!RtlAllocateHeap [76ef0000+41240+c9]
76f31309: ntdll!RtlAllocateHeap [76ef0000+41240+c9]
06046159: atioglxx!04f10000
060462e0: atioglxx!04f10000
05c0246a: atioglxx!04f10000
05c023ae: atioglxx!04f10000
05c022ba: atioglxx!04f10000
05bfb09a: atioglxx!04f10000
76f3a57e: ntdll!RtlImageNtHeaderEx [76ef0000+49fe0+59e]
76f31309: ntdll!RtlAllocateHeap [76ef0000+41240+c9]
76f317d1: ntdll!RtlAllocateHeap [76ef0000+41240+591]
76f4443b: ntdll!RtlAppendUnicodeToString [76ef0000+541a0+29b]
76f444ba: ntdll!RtlAppendUnicodeToString [76ef0000+541a0+31a]
006f005c: class XNode * LuaHelpers::GetLuaInformation(void) [00400000+2ef640+a1c]
76f3a57e: ntdll!RtlImageNtHeaderEx [76ef0000+49fe0+59e]
76f31309: ntdll!RtlAllocateHeap [76ef0000+41240+c9]
76f4443b: ntdll!RtlAppendUnicodeToString [76ef0000+541a0+29b]
76f444ba: ntdll!RtlAppendUnicodeToString [76ef0000+541a0+31a]
006f005c: class XNode * LuaHelpers::GetLuaInformation(void) [00400000+2ef640+a1c]
76f44619: ntdll!SbSelectProcedure [76ef0000+544e0+139]
76f44673: ntdll!SbSelectProcedure [76ef0000+544e0+193]
76f317d1: ntdll!RtlAllocateHeap [76ef0000+41240+591]
76f31309: ntdll!RtlAllocateHeap [76ef0000+41240+c9]
76f31354: ntdll!RtlAllocateHeap [76ef0000+41240+114]
76de86ec: CFGMGR32!CM_Get_Device_ID_ExA [76de0000+6c01+1aeb]
76de8748: CFGMGR32!CM_Get_Device_ID_ExA [76de0000+6c01+1b47]
76f2d0dc: ntdll!ZwCreateMutant [76ef0000+3d0d0+c]
74e23492: KERNELBASE!CreateMutexExW [74e10000+13428+6a]
74e234b0: KERNELBASE!CreateMutexExW [74e10000+13428+88]
76f383f5: ntdll!bsearch [76ef0000+48390+65]
76f383f5: ntdll!bsearch [76ef0000+48390+65]

Static log:
StepMania v5.0 beta 4a
Compiled 20141019 @ 19:58:47 Central Daylight Time (build 1)
Log starting 2015-02-15 23:01:32
Loading window: win32
Windows 6.2 (Win8) build 9200 []
Memory: 4095mb total, 4095mb swap (4095mb swap avail)
Video driver: ATI Radeon HD 4600 Series (Microsoft Corporation - WDDM v1.1) [Advanced Micro Devices, Inc.]
              8.97.10.6, 6-20-2012 [pci\ven_1002&dev_9490]
Drive: "TOSHIBA DT01ACA100      MS2O" Driver: amd_sata DMA: N/A
Drive: "WDC WD1001FALS-00J7B0   05.0" Driver: amd_sata DMA: N/A
Drive: "ASUS    SH-224DB        1.00" Driver: amd_sata DMA: N/A
Sound device 0: Speakers (2- USB Sound Device  , 0.16, MID 65535, PID 65535 
Sound device 1: AMD HDMI Output (2- AMD High De, 6.3, MID 1, PID 100 
WARNING: ReadFile(Save/ThemePrefs.ini): No such file or directory
DirectSound Driver: Primary Sound Driver
DirectSound Driver: Speakers (2- USB Sound Device        ) {0.0.0.00000000}.{cda2d430-12e1-4545-8848-790c40e15495}
DirectSound Driver: AMD HDMI Output (2- AMD High Definition Audio Device) {0.0.0.00000000}.{67e26c26-b76c-4b66-ad4a-9df3622246b9}
DirectSound sample rates: 100..200000 (continuous)
Software mixing at 44100 hz
Sound driver: DirectSound-sw
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'opengl,d3d'
Language: en
Current renderer: OpenGL
Theme: default

Partial log:
00:00.463: Loading /Save/MachineProfile/Stats.xml
00:00.463: Done.
00:00.465: UnlockManager::Load()
00:00.483: Last seen video driver: 
00:00.483: Card matches 'GeForce|Radeon|Wonder 9|Quadro'.
00:00.483: Applying defaults for ATI Radeon HD 4600 Series (Microsoft Corporation - WDDM v1.1).
00:00.483: Video renderers: 'opengl,d3d'
00:00.483: RageDisplay_Legacy::RageDisplay_Legacy()
00:00.515: WM_ACTIVATE (0, 0): has focus
00:00.537: SetScreenMode ...

-- End of report

**Comment by kyzentun** [comment]
Try 5.0.5, which was released yesterday.

**Comment by kyzentun** [comment]
Closing because user never responded to whether 5.0.6 works or not.
