### ISSUE TITLE
Crash on attempting to delete newly created steps from copy

### ISSUE THREAD

**Issue by freem** [stepmania/stepmania#475]
1) create a new chart from a copy of an existing chart
2) go into editor
3) press F7 and F8 a few times (may or may not be dependent)
4) exit editor without saving
5) attempt to delete copied steps
then a crash happens.

crashinfo (I wish github would let us upload text files when creating new issues)

StepMania5.0-UNKNOWN crash report (build 6, 20150216 @ 18:37:59 Central Standard Time)
--------------------------------------

Crash reason: Access Violation

Thread: Main thread
        RageTextureManager.cpp:135 RageTextureManager::LoadTexture(/Themes/default/Graphics/Common fallback banner.png).
        RageTextureManager.cpp:135 RageTextureManager::LoadTexture(Cache/Banners/Songs_bad_bganim_Sandstorm_Sandstorm.png).
        RageTextureManager.cpp:135 RageTextureManager::LoadTexture(Cache/Banners/Songs_bad_bganim_Sandstorm_Sandstorm.png).
        RageTextureManager.cpp:135 RageTextureManager::LoadTexture(Cache/Banners/Songs_bad_bganim_Sandstorm_Sandstorm.png).
        GameSoundManager.cpp:557 1.063472, delta 0.183000
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
Thread: Mixer thread
Thread: Music thread
        RageFileDriverDirectHelpers.cpp:227 E:/StepMania 5/Themes/*
        RageFileDriverDirectHelpers.cpp:227 E:/StepMania 5/Themes/_fallback/*
        RageFileDriverDirectHelpers.cpp:227 E:/StepMania 5/Themes/*
        RageFileDriverDirectHelpers.cpp:227 E:/StepMania 5/Themes/_fallback/Sounds/*
        RageFileDriverDirectHelpers.cpp:227 E:/StepMania 5/Themes/_fallback/*
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
        InputHandler_DirectInput.cpp:750 
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 

0048676a: struct BPMSegment * ToBPM(struct TimingSegment *) [00400000+86765+5]
0047458c: struct BPMSegment const * TimingData::GetBPMSegmentAtRow(int)const  [00400000+7457b+11]
004746f5: float TimingData::GetBPMAtRow(int)const  [00400000+746ea+b]
004db38f: void TimingData::GetBeatAndBPSFromElapsedTimeNoOffset(float,float &,float &,bool &,bool &,int &,float &)const  [00400000+db321+6e]
004dba15: void TimingData::GetBeatAndBPSFromElapsedTime(float,float &,float &,bool &,bool &,int &,float &)const  [00400000+db9e3+32]
004cfd18: void SongPosition::UpdateSongPosition(float,class TimingData const &,class RageTimer const &) [00400000+cfcc1+57]
0052bc33: _int64 ArchHooks::GetMicrosecondsSinceStart(bool)() [00400000+12bc03+30]
005c2dd5: void RageTimer::Touch(void) [00400000+1c2db6+1f]
005f89e6: void GameState::UpdateSongPosition(float,class TimingData const &,class RageTimer const &) [00400000+1f8944+a2]
005f5609: void GameSoundManager::Update(float) [00400000+1f5324+2e5]
005adc10: void RageSoundManager::Update(void) [00400000+1adb35+db]
0052051d: void GameLoop::RunGameLoop(void) [00400000+12047c+a1]
71365e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [71360000+5dfb+48]
71365ec4: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > [71360000+5ebb+9]
005239b9: main() [00400000+122ea9+b10]
6f592e2b: MSVCR90!unlock [6f570000+22e16+15]
6f5d67ab: MSVCR90!realloc [6f570000+66415+396]
6f5938b3: MSVCR90!initptd [6f570000+23753+160]
005378d9: WinMain@16() [00400000+1378c3+16]
006a545e: __tmainCRTStartup() [00400000+2a531e+140]
771c9f45: ntdll!RtlInitializeExceptionChain [77190000+39f0f+36]

Static log:
StepMania5.0-UNKNOWN
Compiled 20150216 @ 18:37:59 Central Standard Time (build 6)
Log starting 2015-02-16 19:00:39
Command line args (count=1): [[--theme=default]]
Loading window: win32
Windows 6.1 (Win7) build 7601 [Service Pack 1]
Memory: 2046mb total, 4095mb swap (2021mb swap avail)
Video driver: NVIDIA GeForce GTX 550 Ti [NVIDIA]
              9.18.13.3193, 11-23-2013 [pci\ven_10de&dev_1244]
WARNING: RegOpenKeyEx(80000002,HARDWARE\DEVICEMAP\Scsi) error (The system cannot find the file specified.)
Sound device 0: Speakers (Realtek AC'97 Audio f, 6.1, MID 1, PID 100 
Sound device 1: Speakers (2- Logitech USB Heads, 16.19, MID 65535, PID 65535 
DirectSound Driver: Primary Sound Driver
DirectSound Driver: Speakers (Realtek AC'97 Audio for VIA (R) Audio Controller) {0.0.0.00000000}.{ad5dbfbf-6ed7-4631-9a99-218ccbec27b7}
DirectSound Driver: Speakers (2- Logitech USB Headset) {0.0.0.00000000}.{a9d93f66-d937-4389-b760-5e1ee02cb74f}
DirectSound sample rates: 100..200000 (continuous)
Software mixing at 44100 hz
Sound driver: DirectSound-sw
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'opengl,d3d'
Mode: ICD 32 (888) 24 depth 64 accum 
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: NVIDIA Corporation
OGL Renderer: GeForce GTX 550 Ti/PCIe/SSE2
OGL Version: 4.4.0
OGL Max texture size: 16384
OGL Texture units: 4
GLU Version: 1.2.2.0 Microsoft Corporation
OGL Extensions:
  GL_AMD_multi_draw_indirect
  GL_ARB: ES2_compatibility, ES3_compatibility, arrays_of_arrays, base_instance, blend_func_extended, 
    buffer_storage, clear_buffer_object, clear_texture, color_buffer_float, compatibility, 
    compressed_texture_pixel_storage, compute_shader, compute_variable_group_size, conservative_depth, 
    copy_buffer, copy_image, debug_output, depth_buffer_float, depth_clamp, depth_texture, draw_buffers, 
    draw_buffers_blend, draw_elements_base_vertex, draw_indirect, draw_instanced, enhanced_layouts, 
    explicit_attrib_location, explicit_uniform_location, fragment_coord_conventions, fragment_layer_viewport, 
    fragment_program, fragment_program_shadow, fragment_shader, framebuffer_no_attachments, framebuffer_object, 
    framebuffer_sRGB, geometry_shader4, get_program_binary, gpu_shader5, gpu_shader_fp64, half_float_pixel, 
    half_float_vertex, imaging, indirect_parameters, instanced_arrays, internalformat_query, 
    internalformat_query2, invalidate_subdata, map_buffer_alignment, map_buffer_range, multi_bind, 
    multi_draw_indirect, multisample, multitexture, occlusion_query, occlusion_query2, pixel_buffer_object, 
    point_parameters, point_sprite, program_interface_query, provoking_vertex, query_buffer_object, 
    robust_buffer_access_behavior, robustness, sample_shading, sampler_objects, seamless_cube_map, 
    separate_shader_objects, shader_atomic_counters, shader_bit_encoding, shader_draw_parameters, 
    shader_group_vote, shader_image_load_store, shader_image_size, shader_objects, shader_precision, 
    shader_storage_buffer_object, shader_subroutine, shader_texture_lod, shading_language_100, 
    shading_language_420pack, shading_language_include, shading_language_packing, shadow, sparse_texture, 
    stencil_texturing, sync, tessellation_shader, texture_border_clamp, texture_buffer_object, 
    texture_buffer_object_rgb32, texture_buffer_range, texture_compression, texture_compression_bptc, 
    texture_compression_rgtc, texture_cube_map, texture_cube_map_array, texture_env_add, texture_env_combine, 
    texture_env_crossbar, texture_env_dot3, texture_float, texture_gather, texture_mirror_clamp_to_edge, 
    texture_mirrored_repeat, texture_multisample, texture_non_power_of_two, texture_query_levels, 
    texture_query_lod, texture_rectangle, texture_rg, texture_rgb10_a2ui, texture_stencil8, texture_storage, 
    texture_storage_multisample, texture_swizzle, texture_view, timer_query, transform_feedback2, 
    transform_feedback3, transform_feedback_instanced, transpose_matrix, uniform_buffer_object, vertex_array_bgra, 
    vertex_array_object, vertex_attrib_64bit, vertex_attrib_binding, vertex_buffer_object, vertex_program, 
    vertex_shader, vertex_type_10f_11f_11f_rev, vertex_type_2_10_10_10_rev, viewport_array, window_pos
  GL_ATI: draw_buffers, texture_float, texture_mirror_once
  GL_EXTX_framebuffer_mixed_formats
  GL_EXT: Cg_shader, abgr, bgra, bindable_uniform, blend_color, blend_equation_separate, blend_func_separate, 
    blend_minmax, blend_subtract, compiled_vertex_array, depth_bounds_test, direct_state_access, draw_buffers2, 
    draw_instanced, draw_range_elements, fog_coord, framebuffer_blit, framebuffer_multisample, 
    framebuffer_multisample_blit_scaled, framebuffer_object, framebuffer_sRGB, geometry_shader4, 
    gpu_program_parameters, gpu_shader4, import_sync_object, multi_draw_arrays, packed_depth_stencil, 
    packed_float, packed_pixels, pixel_buffer_object, point_parameters, provoking_vertex, rescale_normal, 
    secondary_color, separate_shader_objects, separate_specular_color, shader_image_load_store, shadow_funcs, 
    stencil_two_side, stencil_wrap, texture3D, texture_array, texture_buffer_object, texture_compression_dxt1, 
    texture_compression_latc, texture_compression_rgtc, texture_compression_s3tc, texture_cube_map, 
    texture_edge_clamp, texture_env_add, texture_env_combine, texture_env_dot3, texture_filter_anisotropic, 
    texture_integer, texture_lod, texture_lod_bias, texture_mirror_clamp, texture_object, texture_sRGB, 
    texture_sRGB_decode, texture_shared_exponent, texture_storage, texture_swizzle, timer_query, 
    transform_feedback2, vertex_array, vertex_array_bgra, vertex_attrib_64bit
  GL_IBM: rasterpos_clip, texture_mirrored_repeat
  GL_KHR_debug
  GL_KTX_buffer_region
  GL_NVX: conditional_render, gpu_memory_info
  GL_NV: ES1_1_compatibility, bindless_multi_draw_indirect, blend_equation_advanced, blend_square, 
    compute_program5, conditional_render, copy_depth_to_color, copy_image, depth_buffer_float, depth_clamp, 
    draw_texture, explicit_multisample, fence, float_buffer, fog_distance, fragment_program, fragment_program2, 
    fragment_program_option, framebuffer_multisample_coverage, geometry_shader4, gpu_program4, gpu_program4_1, 
    gpu_program5, gpu_program5_mem_extended, gpu_program_fp64, gpu_shader5, half_float, light_max_exponent, 
    multisample_coverage, multisample_filter_hint, occlusion_query, packed_depth_stencil, parameter_buffer_object, 
    parameter_buffer_object2, path_rendering, pixel_data_range, point_sprite, primitive_restart, 
    register_combiners, register_combiners2, shader_atomic_counters, shader_atomic_float, shader_buffer_load, 
    shader_storage_buffer_object, texgen_reflection, texture_barrier, texture_compression_vtc, 
    texture_env_combine4, texture_expand_normal, texture_multisample, texture_rectangle, texture_shader, 
    texture_shader2, texture_shader3, transform_feedback, transform_feedback2, vertex_array_range, 
    vertex_array_range2, vertex_attrib_integer_64bit, vertex_buffer_unified_memory, vertex_program, 
    vertex_program1_1, vertex_program2, vertex_program2_option, vertex_program3
  GL_S3_s3tc
  GL_SGIS: generate_mipmap, texture_lod
  GL_SGIX: depth_texture, shadow
  GL_SUN_slice_accum
  GL_WIN_swap_hint
  WGL_EXT_swap_control
OpenGL Windowed 854x480 32 color 32 texture 60Hz Vsync SmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00010214 Instance Name: "?" Product Name: "?"
DInput: Enumerating device - Type: 0x00010214 Instance Name: "?" Product Name: "?"
DInput: Enumerating device - Type: 0x00010214 Instance Name: "?" Product Name: "?"
DInput: Enumerating device - Type: 0x00010214 Instance Name: "?" Product Name: "?"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 6 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: '?' axes: 4, hats: 1, buttons: 12 (buffered)
   2: '?' axes: 4, hats: 1, buttons: 12 (buffered)
   3: '?' axes: 4, hats: 1, buttons: 8 (buffered)
   4: '?' axes: 4, hats: 1, buttons: 8 (buffered)
   5: 'Mouse' axes: 3, hats: 0, buttons: 8 (buffered)
Players joined: P1
Lost focus to: StepMania.exe
Top Screen: ScreenEditMenu
Language: en
Current renderer: OpenGL
Theme: default

Partial log:
00:55.464: Performing texture garbage collection.
00:55.465: Delete successful; deleting steps from memory
00:55.483: Song::SaveToSongFile()
00:55.506: Song::SaveToSSCFile('/Songs/bad_bganim/Sandstorm/Sandstorm.ssc')
00:55.539: Song::SaveToSMFile(/Songs/bad_bganim/Sandstorm/Sandstorm.sm)
00:55.618: Song::SaveToSSCFile('Cache/Songs/Songs_bad_bganim_Sandstorm')
00:55.632: BannerCache::LoadCachedBanner(/Songs/bad_bganim/Sandstorm/Sandstorm.png): Cache/Banners/Songs_bad_bganim_Sandstorm_Sandstorm.png
00:55.633: BannerCache::LoadCachedBanner(/Songs/bad_bganim/Sandstorm/Sandstorm.png): Cache/Banners/Songs_bad_bganim_Sandstorm_Sandstorm.png
00:55.634: BannerCache::LoadCachedBanner(/Songs/bad_bganim/Sandstorm/Sandstorm.png): Cache/Banners/Songs_bad_bganim_Sandstorm_Sandstorm.png
00:55.636: Zeroing this update.  Was 0.018000

-- End of report

**Comment by kyzentun** [comment]
It's simpler than your steps.
Create or find an existing chart.
Delete that chart.

Fixed:  https://github.com/stepmania/stepmania/commit/955c807dd5bcbc77ee1d87d0590c2842016d1ebd
