### ISSUE TITLE
No Main Menu On Startup

### ISSUE THREAD

**Issue by spitsalot** [stepmania/stepmania#479]
I have downloaded the most recent version of stepmania (5.0.6) and on startup, I can only hit enter to continue straight into song type/selection/etc. There is no longer a main menu so I cannot change the game type, map keys of any sort, change themes/skins, etc. Is there any known fix to this issue?

**Comment by kyzentun** [comment]
You're probably in arcade mode instead of home mode.  Hit Scroll Lock to enter the service menu, then go to Arcade Options and change the coin mode to Home.

**Comment by spitsalot** [comment]
Thank you so much! That was exactly my issue.

**Comment by dguzek** [comment]
Most macOS keyboards don't have a ScrollLock key, but you can manually change the current CoinMode by holding <kbd>fn</kbd> then holding <kbd>F3</kbd> and then tapping <kbd>1</kbd> until you are in "home" mode

**Comment by Vitalurg** [comment]
It works!!!
THANK YOU VERY MUCH!!!!
