### ISSUE TITLE
Random mid-song crash

### ISSUE THREAD

**Issue by User15937** [stepmania/stepmania#509]
So this has only happened once in 100+ song plays, but I haven't found anyone else post this so I thought I probably should.

While playing a song, the game suddenly froze, the music became a very loud buzzing, and, in fact, the entire computer froze (mouse and keyboard didn't work), and I had to shut it off with the power button.

I had played through that same song before and it didn't cause a problem, so I don't think the song was the issue.

(also, this should be bug/crash label? not sure how to do that though)

**Comment by Missingmew** [comment]
If this happens to you again, try using CTRL-ALT-DEL to bring up the corresponding menu to run taskmanager from it. If nothing happens, it was probably an error that was bluescreen-worthy but was bad enough not to bluescreen. It shouldnt have anything to do with stepmania.

**Comment by User15937** [comment]
Yeah I tried to open task manager and it didn't work because the computer was frozen.

**Comment by shakesoda** [comment]
There's not enough info to possibly fix this issue, it could be anything.

Your computer could have overheated for all we know - without a crash log, file or sequence of events that reliably crashes the game, it's unfixable.
