### ISSUE TITLE
no input

### ISSUE THREAD

**Issue by schmurfy** [stepmania/stepmania#517]
Hi,
I am trying to run stepmania 5.0.6 on linux, I am running it using the stepmania.desktop session file provided with lightdm:

```bash
$ cat lightdm.stepmania.conf
[LightDM]
minimum-vt=1
run-directory=/run/lightdm

[SeatDefaults]
session-wrapper=/etc/lightdm/Xsession
pam-service=lightdm-autologin
autologin-user=kodi
autologin-user-timeout=0
user-session=stepmania

$ lightdm -d -c lightdm.stepmania.conf
```

It starts the game but does not take any input even from keyboard, it is working as far as I can tell since the background is moving and it is logging things but I can't figure what is wrong :(

Here is some (I think) revelant lines from the Log.txt file of an attempt to plug a PS3 controller which did not change a thing sadly:

```
00:00.983: RageInput::RageInput()
00:00.984: LinuxEvent: Couldn't open /dev/input/event0: Permission denied.
00:00.984: LinuxEvent: Couldn't open /dev/input/event1: Permission denied.
00:00.984: LinuxEvent: Couldn't open /dev/input/event2: Permission denied.
00:00.984: LinuxEvent: Couldn't open /dev/input/event3: Permission denied.
00:00.985: LinuxEvent: Couldn't open /dev/input/event4: Permission denied.
00:00.985: LinuxEvent: Couldn't open /dev/input/event5: Permission denied.
00:00.985: LinuxEvent: Couldn't open /dev/input/event6: Permission denied.
00:00.985: LinuxEvent: Couldn't open /dev/input/event7: Permission denied.
00:00.985: LinuxEvent: Couldn't open /dev/input/event8: Permission denied.
00:00.985: LinuxEvent: Couldn't open /dev/input/event9: Permission denied.
00:00.985: LinuxEvent: Couldn't open /dev/input/event10: Permission denied.
00:00.985: LinuxEvent: Couldn't open /dev/input/event11: Permission denied.
00:00.985: LinuxEvent: Couldn't open /dev/input/event12: Permission denied.
00:00.985: LinuxEvent: Couldn't open /dev/input/event13: Permission denied.
00:00.985: InputHandler_Linux_Joystick::InputHandler_Linux_Joystick
00:00.985: LinuxJoystick: Opened /dev/input/js0
00:00.985: Starting thread: Joystick thread
```

This full log is here: https://gist.github.com/schmurfy/e3e3a9e314ae30718736

it may just be me missing something but I have no clue what this could be, any help/pointer would be greatly appreciated :)

**Comment by roothorick** [comment]
Start it from inside a normal WM/DE. If you have input now, change settings
to full screen, then try starting it in its own X session. X is weird about
focus without a WM.

As for the controller, PS3 controllers aren't automapped; very little is.
Once you have keyboard input, manually map it in settings.

**Comment by schmurfy** [comment]
thanks, I will give it a try.

**Comment by schmurfy** [comment]
you were right it was a focus issue, running inside a wm fixed this and I now have the keyboard at least ^^
the PS3 pad was just a test, I have a dance pad and now I can try to have stepmania use it.
