### ISSUE TITLE
Future FR: Song/Simfile tag ID

### ISSUE THREAD

**Issue by SpoOkyMagician** [stepmania/stepmania#530]
I highly doubt this is something SM5 should have (for now anyway.) but, SM6 should include it. (Much later.) I discussed the idea before on irc but, let me try to explain it a bit further. The idea was 'borrowed' from wesnoth. For custom content, they use an id system. The id is basically a string that contains letters, numbers, underscores, etc. (to my understanding.) If a id matches another one, causes and error, etc; an error is output and the file(s) is/are NOT loaded.

My reasoning behind feature requesting this? Look at it this way. Instead of having to create a separate folder/song directory to make a new chart, you could literally define/create a new chart with a new id. (Will have to add some sort of id input when creating a chart in StepMania/autogenerating one temporarily.) This way, the game can load multiple charts in a single file directory. For example...

stepfile_1.sm (chart one)
stepfile_2.sm (chart two)
Etc...

If you were to take it a step further, you could even apply this to noteskins, announcers, random BGA's, etc. However, this may break stuff but, it would really be useful IMO. It would take a lot of work sadly but, if anyone is willing to try, please consider it.

**Comment by kyzentun** [comment]
I'm not sure I understand the point of this, but it sounds like the only benefit is that you can make a second simfile for a particular song/cut without copying the audio to another directory.  Hardly seems worth the effort.

**Comment by roothorick** [comment]
I think he wants an inheritance system, kind of like themes, but for songs. It'd certainly be a cleaner way to implement edits...

**Comment by SpoOkyMagician** [comment]
Well for one it would save file space. (music, videos, etc.) Second, this could/may fix the online issue picking the wrong song due to being a different version of the song. Finally, you could literally have limitless charts in a single song. (If you wanted to anyway.)

After thinking about the others it may not exactly be useful but... What if you were to have... content type ID's as well? You could literally have just one directory for all custom content. (You would define it in some file. Again, like wesnoth does.) I am just thinking/discussing at this point but, surely some idea could be useful.

**Comment by SpoOkyMagician** [comment]
probably not even worth the effort.
