### ISSUE TITLE
Spreading Meaure bars when selecting speed mods.

### ISSUE THREAD

**Issue by DXUltimate** [stepmania/stepmania#533]
This is more of a feature request I would like to see added back into StepMania as it was in StepMania 3.9. I would like to see when modifying speed mods in Edit Mode, that it would spread out the measures as well, for easier editing of simfiles and their BPMs. The red BPM text when squished together when creating gimmicky simfiles is very hard to read using the default speed of "1x". I will provide a further explaination in necessary.

If this was already added back into the game, please provide me the steps on how to get those measure bars to spread out when editing the steps (not previewing/playing them, but editing them), as this would save a lot of time when editing/creating simfiles. Thanks. =)

**Comment by dguzek** [comment]
You can use **Control** + **Up** to spread the notes further apart and **Control** + **Down** to collapse them back.  You can access a full list of keyboard commands for StepMania's editor by pressing **F1** while editing steps.
