### ISSUE TITLE
Should radar values be uncapped?

### ISSUE THREAD

**Issue by kyzentun** [stepmania/stepmania#539]
Two things:  Capping, and inaccuracy of Stream and Voltage
1.  Currently, Stream, Voltage, Air, Freeze, and Chaos radar values are capped at 1 by this line of code:
https://github.com/stepmania/stepmania/blob/master/src/NoteDataUtil.cpp#L1120

If they were uncapped, they could be relevant at higher difficulties, instead of being discarded by practically all skilled players.

2.  As mentioned in a comment, Stream and Voltage calculations count hold heads twice, and roll heads once.  This is because the old (slow) methods did it by accident, and rather than deal with any possible backlash, I duplicated that behavior in the new calculation method.

I believe this should be fixed so that hold heads are only counted once, because counting something that only requires a single step twice is silly.

**Comment by kyzentun** [comment]
If nobody presents a reason against it in a week, I'm going to go ahead and do both.

**Comment by SpoOkyMagician** [comment]
+1 to fix.

**Comment by dguzek** [comment]
I am in favor counting hold heads once.

I cannot offer any useful feedback on capping/not-capping RadarValues.  I don't actually understand what RadarValues are, how they're used currently, or how they might benefit from the first proposed change.

**Comment by kyzentun** [comment]
You might recognize the RadarValues better if I say that Stream, Voltage, Air, Freeze, and Chaos what's used by the Groove Radar.  Uncapping them means that "We Eat At Five Five Five" comes up with a voltage of 1.97 and stream of 1.59, instead of coming up at 1.0 for both.
I haven't checked it on a theme that displays the groove radar yet, and I'm planning to just make the built in groove radar actor cap it at that end.  Themes that display radar values in some custom way will suffer a bit if they are using a quad sized by the value.

**Comment by kyzentun** [comment]
Done in #552
