### ISSUE TITLE
Max DancePoints is over 100%. (from SM5.0.7)

### ISSUE THREAD

**Issue by waiei** [stepmania/stepmania#542]
If STEPS has LIFTS, max DancePoints is over 100%.
Only SM5.0.7. SM5.0.7rc is no problem.

https://youtu.be/ADmYqTSRqzM
2P has lifts. Result dancepoints is 200%.

5.0.7
![2015-04-04_164535](https://cloud.githubusercontent.com/assets/8708955/6991983/802cbdb8-daee-11e4-9930-f44f1f0a5f5c.jpg)

5.0.7rc (No problem)
![2015-04-04_170957](https://cloud.githubusercontent.com/assets/8708955/6991988/97c0c014-daee-11e4-9a5e-0ce4987123bf.jpg)

**Comment by kyzentun** [comment]
Fixed in #552
