### ISSUE TITLE
Severe judgments (SM5.0.7)

### ISSUE THREAD

**Issue by waiei** [stepmania/stepmania#546]
Please look this movie.
https://www.youtube.com/watch?v=KwGqWFxs6J0
I have to play in the same way. (Timing difficulty : 4)
But 5.0.7 is very wrong judgements.

This song has many stops.
At StepMania5.0.7, judgments is very severe in STOPS+NOTES area. (WARPS is not much relationship)
5.0.7rc is no problem.

simfile is here
http://waiei.net/_tmp/h000.zip

**Comment by wolfman2000** [comment]
The way the timing data is read in is different from 5.0.6 and 5.0.7. Sounds like a corner case was missed.

**Comment by kyzentun** [comment]
I believe this bug occurs specifically when there's a stop and a warp on the same row *and* that spot is one of the entries in the lookup table.
It gives you a miss for that one note.
If I'm right about that, it might not be hard to fix.

**Comment by kyzentun** [comment]
Figured out that it was an odd case in the precedence between warps, stops, and the marker for the current step.  I put in a kluge to change the way stops are put in the lookup table and managed to get this score with a cmod:
http://i.imgur.com/V1gAx1L.jpg
Fixed in #552
