### ISSUE TITLE
SM data of edit modes. Bug

### ISSUE THREAD

**Issue by latot** [stepmania/stepmania#550]
Hi, its a littple problem of sm in linux, it doesn't load the data of edit modes, example, y play songs a i get an B, and when i back to menu i can see that, but when i close the game and i saw the songs don't say anything u.u, i check the Stat.xml and the data is saved, this only happend on linux version, in windows no problem.

Well the images are a graph expl.
![2015-04-06_050220](https://cloud.githubusercontent.com/assets/10523095/7002046/808ae320-dc1a-11e4-9ada-9a4197c7835a.jpg)
![2015-04-06_050413](https://cloud.githubusercontent.com/assets/10523095/7002047/80d8a24a-dc1a-11e4-839e-9b468e2b586d.jpg)

Thx

**Comment by Wallacoloo** [comment]
This could be a permissions issue if you have stepmania installed to
/usr/... If that's the case, you may want to try installing it to your home
directory and see if the problem persists.

**Comment by kyzentun** [comment]
He's talking about it not loading the scores for edit charts until you play them.  Nothing to do with permissions, just some weird quirk of score loading.

**Comment by kyzentun** [comment]
@latot Can you send me your Stats.xml from your machine profile and your local profile?
~/.stepmania-5.0/Save/MachineProfile/Stats.xml
~/.stepmania-5.0/Save/LocalProfile/00000000/Stats.xml
Don't paste their contents here.  Upload them on some sharing site and post links or email them to me. (my address is visible in my github profile)

**Comment by latot** [comment]
Hi, here is my Stat.xml

https://mega.co.nz/#!EVt0FQyD!ujRiJ11vxz6-IhiNHjXOUiIM5XyAoo3GYEwEZQNwzOg

and i only have the machineprofile, the folder localprofile don't exist.
With the last update when start the sm, this don't show the score, but if i play it and when i back to the songs list it appears.

**Comment by kyzentun** [comment]
Fixed: https://github.com/stepmania/stepmania/commit/1c3db825374e4bdb5ede8b398584d2b11939f0b2
