### ISSUE TITLE
Crash: Edit Mode after using "Revert from Disk"

### ISSUE THREAD

**Issue by DXUltimate** [stepmania/stepmania#556]
While I was attempting on how to figure out to copy and paste timing segments, I came across this crash after I tried to reload from disk. Not sure if this is a major problem or not.

http://pastebin.com/QHAaCPMK

The full log can be found here;

https://www.dropbox.com/s/uqojlhkxsjp70n8/log.txt?dl=0

**Comment by kyzentun** [comment]
Edit mode in 5.0.7 lacks proper ways to copy and paste timing segments, they will be in the next release.  See #543 for a short explanation, or try them out in the latest nightly.

Revert from Disk still has some problems that need to be fixed.

**Comment by kyzentun** [comment]
Revert From Disk fixed.  https://github.com/stepmania/stepmania/commit/b04e7faec6fe79ce87f0055521f826f728cd40bd
