### ISSUE TITLE
Maybe a audio bug?

### ISSUE THREAD

**Issue by latot** [stepmania/stepmania#559]
Hi, i'm posting this but i really don't know if is a bug of my system or the sm, but as i can't found a fail in my system i'm here, well i'll explain all with details because i don't know what info is important.

problem, sm sounds only one side, the left, well i was playing and i use a second display to play it, then i in the sound conf of gnome i inadvertently change the auricular conf to listen by one side, then i was thinking are was a auricular problem or something i restart the pc, then trying again son't result and i found that change.., but when i restore the conf in pulseaudio sm continuing sound on one side, the others apps works fine, y test with auticular and without them but was the same. i try restarting and resinstalling but i really don't know what happend, i check the individual confs by app and are nothing weird. in any case i try in the main display too and don't works, it looks as if it had locked in that audio conf.

my log: https://gist.github.com/latot/f67ae82811de6b4772cd
the ptrace problem don't is relevant, it happend when i use alt+enter in a video or when i close the app, comparing the log with the previus i can't see anything anormal.

Thx. (sorry my bad english)

**Comment by latot** [comment]
well, that was a system fail in pulseaudio, for some reason pulseaudio lock that conf in stepmania for a werid reazon.

for fix it 
pulseaudio -k
rm -r .~/config/pulse/
rm ~/.pulse-cookie
pulseaudio --start

with i can fix it for now but i can't say sm don't influenced on this, i'll wait if some devep can help with this.

**Comment by Wallacoloo** [comment]
I don't think there's enough info here for any developers to figure this
out, if it even is a problem in Stepmania. If you can find a way to
reliably reproduce it though, that would make things far easier.

**Comment by latot** [comment]
mm, well i'll close this for now, if i found a way to reproduce it i'll repost this, if not, most be my system problem, thx anyway cya.
