### ISSUE TITLE
Errors in popup windows

### ISSUE THREAD

**Issue by SoonDead** [stepmania/stepmania#560]
On some songs when an error occures (like unable to load x.png) a notification pops up over the game. It's intrusive as it captures the focus and hard to press ok on it if you are on a pad.
This is new to me. I have only seen errors written to the ingame background, which was non intrusive.

Is this an intended feature?

If not, I'll try to provide more information on it when I get home.

**Comment by kyzentun** [comment]
Probably an error in the song, especially if it has scripted background or foreground stuff, send a link to the song and I can probably figure out what the author did wrong.

**Comment by SoonDead** [comment]
To clarify:

 * My problem is not that a song has a broken scripted background.
 * My problem is that the error is shown in a popup window.

The error should either be:
1. Silently ignored.
2. Or shown in a discrete manner which does not break the game flow.

**Comment by kyzentun** [comment]
Click the "Do not show again" button and you'll never see errors reported again at all.
If you're a content author and need them for debugging, there are at least three threads on the forum explaining how to get only the on-screen display and not the popup.

**Comment by Wallacoloo** [comment]
Try to capture a screenshot of it if it's not too much trouble. And I
assume you're using the default theme?

**Comment by Wallacoloo** [comment]
Scratch that - I started my reply before this was closed.

**Comment by shakesoda** [comment]
further, those windows do not come up in fullscreen.

**Comment by SoonDead** [comment]
Thank you guys!

**Comment by kyzentun** [comment]
I wonder if your problem was with a background that was never loaded, as discussed in this thread.
http://www.stepmania.com/forums/general-questions/show/1535
