### ISSUE TITLE
RageBitmapTexture: Couldn't load ... popup keeps showing

### ISSUE THREAD

**Issue by tristanbes** [stepmania/stepmania#577]
Hi,

On a lot of songs I have those kinds of errors:
```
RageBitmapTexture: Couldn't load /Songs/Best of 2015/Habits (Stay High)/Habits (Stay High).png: No such file or directory
```

The problem is that when I click on **"Never show this again", it has no effect**. It forces me between each song to go to my computer, get off my pad, and click on the popup.

I'm on OSX 10.10.3 and i'm using the latest version of stepmania I just downloaded it today on the Github repo using the release.

**Comment by kyzentun** [comment]
Does that file actually exist?  Normally Stepmania checks to make sure the banner images and stuff actually exist when caching a song so this shouldn't happen.  Can you post a link to an example simfile and the theme you're using so we can figure out why it's trying to load an image that doesn't exist?

The "never show this again" button should work in the next release.

**Comment by tristanbes** [comment]
It was on this pack: http://zenius-i-vanisher.com/v5.2/viewsimfilecategory.php?categoryid=861
and on some other songs too But i can't remember which pack it was.

Until the next release, can I patch manually some file to stop displaying this popup ?

**Comment by kyzentun** [comment]
You could edit the simfiles to not point to images that don't exist.  Open the .ssc or .sm file in a text editor and clear the fields that point to files that don't exist (usually the banner or background fields).  Then hit Ctrl+Shift+R on Select Music on the songs you edited to make Stepmania regenerate the cache files.

**Comment by kyzentun** [comment]
Forgot to close this after fixing it.  https://github.com/stepmania/stepmania/commit/9758932be06e5c3a56d14bd585c833d2d0f939dd
(2 fold fixed:  If an image doesn't exist when a song is cached, a blank filename is saved in the cache.  And RageBitmapTexture now allows the dialog to be ignored)
