### ISSUE TITLE
Insta-fail if battery lifebar with one life is used.

### ISSUE THREAD

**Issue by ListenerJubatus** [stepmania/stepmania#584]
Steps to reproduce:

1. Select a song in standard mode.
2. Set the lifebar mode to Battery, give yourself one life.
3. Watch as you magically fail instantly at the start of the song.

Notice the "0 lives" modifier in the options.
![2015-05-03_194612](https://cloud.githubusercontent.com/assets/6346433/7448069/19cf90ae-f1cd-11e4-88e9-9fd0379b7242.jpg)

**Comment by dguzek** [comment]
I'm unable to reproduce this using an up-to-date build.

**Comment by kyzentun** [comment]
Also cannot reproduce on a recent build.  Probably a sign that you have mismatched default theme and SM version or something.

**Comment by dguzek** [comment]
Any update on this @ListenerJubatus?

**Comment by ZeroTheSavior** [comment]
I've experienced this using the DDR2013 theme from Zenius I Vanisher, but
I'm not sure if that's a theme problem or not.

**Comment by kyzentun** [comment]
No update, almost certainly a case of using an outdated release, and people known to use an updated release cannot reproduce it.
