### ISSUE TITLE
2D Noteskins don't play animations

### ISSUE THREAD

**Issue by hookyboysb** [stepmania/stepmania#601]
After I upgraded to 5.0.8 from 5.0.7, I noticed that my DDR noteskins were broken. The receptors weren't flashing and the arrows were static Thought it was something I did and I ignored it. Today, I realized that it could be an SM problem, so I tested out default (which seemed normal), retrobar (also normal), and midi-note (which comes with SM, the receptors work [likely because they're from the 3D version] and the arrows were blank inside). All of these appear to be 2D noteskins.

It seems like there was a change made to noteskins that broke 2D ones, and default was fixed. I'm not saying to revert the change, but I'd like to know what exactly changed here. Maybe it is a regression and should be reverted; I don't know.

**Comment by hookyboysb** [comment]
I believe the issue is this commit: https://github.com/stepmania/stepmania/commit/2656123464656510681d5081d53e62f3227de5ad

**Comment by shakesoda** [comment]
Can you post a link to a broken noteskin?

**Comment by kyzentun** [comment]
midi-note shows the problem, but you have to look closely to see it.  It is indeed something in that commit that did it.  I haven't narrowed it down yet.

**Comment by kyzentun** [comment]
http://git.io/vUFOy
