### ISSUE TITLE
[GameState] AllowLateJoin isn't working correctly.

### ISSUE THREAD

**Issue by kr4kp0t** [stepmania/stepmania#604]
From StepMania 5.0.8, metrics.ini at [GameState] section, even though changed AllowLateJoin to false, it seems not working correctly.
5.0.7 or older is working correctly.

Totally aside from this, Is Texture Font Generator excluded from 5.0.8?
It's very handy for making font bitmap...

**Comment by SpoOkyMagician** [comment]
Really? Lemme see...

Yep... It is broken...

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/commit/e6e0dcff443d5cff425f7d022066f4ee4475bce3
