### ISSUE TITLE
Virus scanner warning

### ISSUE THREAD

**Issue by NemoPersona** [stepmania/stepmania#608]
On windows both Avast and Norton block the file listed below. This happens when downloading source from github and the source tar ball on your website. It could be a false positive ether way you might want to resolve it and/or update the file so it no longer has the signature triggering the scanners.

File: https://github.com/stepmania/stepmania/tree/master/Utils/handle.exe

**Comment by freem** [comment]
This file was added way back in 200x and doesn't appear to be used by anything in the repo:
http://sourceforge.net/p/stepmania/mailman/message/12627727/

There was a note about using this tool to see threads:
http://sourceforge.net/p/stepmania/mailman/message/15508513/

If anyone needs it, the latest version can be found here:
https://technet.microsoft.com/en-us/sysinternals/bb896655.aspx
