### ISSUE TITLE
Legal conundrum: APIs

### ISSUE THREAD

**Issue by cybik** [stepmania/stepmania#660]
http://fortune.com/2015/05/26/google-oracle-api-supremecourt-obama-appeal/

Seeing that, what can we do to guarantee that Stepmania is going to stay open and not sue anyone who uses our code/hooks/APIs for Lua theming? I feel this could influence future development just a bit.

**Comment by Wallacoloo** [comment]
Isn't all the stepmania code licensed permissively (MIT, if I recall
correctly)? Does that not extend to the APIs? If so, then I'm pretty sure
this is already taken care of.

**Comment by shakesoda** [comment]
Lua still isn't an acronym.

I don't see this being a problem - who would sue? Further, we don't do copyright assignment.
