### ISSUE TITLE
Compiler failure on latest git

### ISSUE THREAD

**Issue by ZeroTheSavior** [stepmania/stepmania#662]
When attempting to compile from the latest git clone, it will fail due to verstub.cpp.

```
[ 48%] Built target GtkModule
[ 48%] Generating /home/obsidian/Documents/stepmania/src/generated/delete
[ 48%] Generating /home/obsidian/Documents/stepmania/src/generated/verstub.cpp
Scanning dependencies of target stepmania
[ 48%] Generating /home/obsidian/Documents/stepmania/src/generated/delete
[ 48%] Generating /home/obsidian/Documents/stepmania/src/generated/verstub.cpp
[ 48%] Building CXX object src/CMakeFiles/stepmania.dir/generated/verstub.cpp.o
/home/obsidian/Documents/stepmania/src/generated/verstub.cpp:8:58: warning: missing terminating " character [enabled by default]
 extern char const * const version_time = ""16:44:01 -0500";
                                                          ^
/home/obsidian/Documents/stepmania/src/generated/verstub.cpp:8:1: error: missing terminating " character
 extern char const * const version_time = ""16:44:01 -0500";
 ^
/home/obsidian/Documents/stepmania/src/generated/verstub.cpp:7:44: error: expected ‘,’ or ‘;’ before numeric constant
 extern char const * const version_date = ""20150531"";
                                            ^
/home/obsidian/Documents/stepmania/src/generated/verstub.cpp:8:44: error: expected ‘,’ or ‘;’ before numeric constant
 extern char const * const version_time = ""16:44:01 -0500";
                                            ^
make[2]: *** [src/CMakeFiles/stepmania.dir/generated/verstub.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/stepmania.dir/all] Error 2
make: *** [all] Error 2
```

Contents of verstub.cpp:
```C++
extern int const sm_version_major = 5;
extern int const sm_version_minor = 0;
extern int const sm_version_patch = 8;
extern char const * const sm_version_git_hash = "93da38d";
extern char const * const smVersionTraditional = "5.0.8";
extern char const * const smVersionFull = "5.0-git-93da38d";
extern char const * const version_date = ""20150531"";
extern char const * const version_time = ""16:56:02 -0500";
#if defined(IS_FULL_RELEASE)
extern char const * const product_version = smVersionFull;
#else
extern char const * const product_version = smVersionTraditional;
#endif

extern int const version_num = 0; // will change
```

**Comment by wolfman2000** [comment]
There were recent changes made involving compilation due to Android setup stuff. Did you clean your cmake cache first?

**Comment by wolfman2000** [comment]
Also, now that I notice, why are version_date and version_time double double quoted?

**Comment by cybik** [comment]
@wolfman2000 your macros implementing CMake3's TIMESTAMP might be doing that.

**Comment by wolfman2000** [comment]
@cybik I thought I put in the Cmake 3 if buffer appropriately. That may have to be re-looked at.

**Comment by mumeino2** [comment]
im facing a similar issue. this is what im getting. im sorry, i dont know what version of cmake im using.

diogenesofindy@r ~/stepmania/Build $ make -j3
[  0%] Built target glew
[  1%] [  7%] Built target ffmpeg
Built target jpeg
[  8%] Built target jsoncpp
[ 10%] Built target png
[ 14%] Built target lua-5.1
[ 32%] Built target tomcrypt
[ 46%] [ 48%] Built target GtkModule
Built target tommath
[ 48%] Generating ../../src/generated/delete
[ 48%] Generating ../../src/generated/verstub.cpp
Scanning dependencies of target stepmania
[ 48%] Generating ../../src/generated/delete
[ 48%] Generating ../../src/generated/verstub.cpp
[ 48%] Building CXX object src/CMakeFiles/stepmania.dir/generated/verstub.cpp.o
/home/diogenesofindy/stepmania/src/generated/verstub.cpp:8:44: error: invalid digit "8" in octal constant
 extern char const * const version_time = ""08:15:10 -0400";
                                            ^
/home/diogenesofindy/stepmania/src/generated/verstub.cpp:8:58: warning: missing terminating " character [enabled by default]
 extern char const * const version_time = ""08:15:10 -0400";
                                                          ^
/home/diogenesofindy/stepmania/src/generated/verstub.cpp:8:1: error: missing terminating " character
 extern char const * const version_time = ""08:15:10 -0400";
 ^
/home/diogenesofindy/stepmania/src/generated/verstub.cpp:7:44: error: expected ‘,’ or ‘;’ before numeric constant
 extern char const * const version_date = ""20150603"";
                                            ^
/home/diogenesofindy/stepmania/src/generated/verstub.cpp:8:44: error: expected ‘,’ or ‘;’ before numeric constant
 extern char const * const version_time = ""08:15:10 -0400";
                                            ^
make[2]: *** [src/CMakeFiles/stepmania.dir/generated/verstub.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/stepmania.dir/all] Error 2
make: *** [all] Error 2

**Comment by kyzentun** [comment]
This commit should fix this problem.  The commands that generated the timestamp strings had quotes in them, and there were quotes in the code that generated the file.  Thus, double quotes.
https://github.com/stepmania/stepmania/commit/963a204fb02753c07102d473acbe4a5cff6b8020
