### ISSUE TITLE
Should Consensual be bundled with 5.0.9?

### ISSUE THREAD

**Issue by kyzentun** [stepmania/stepmania#666]
Some know this already:  I'm working on a reskin of Consensual with the intent to bundle it with 5.0.9.
This issue is for people to discuss whether they're in favor or opposed, and why.

Reasons to do this:
1. (in my view) Consensual is the future of Stepmania's capabilities.
2. Default does not provide many advanced features, and even has some "simple" ones missing.  Currently, people have to go to custom themes that are either not maintained, or poorly maintained to get features outside of default's range.
3. No active theme dev uses default?  (not sure, midiman might be using default).  Whenever someone asks devs what themes they use, each one is using their own custom theme.  I believe that having no theme dev using default as their primary theme results in a lower quality theme.

Reasons not to do this:
Consensual does not support online mode, and I do not plan to implement that before the next release.
Izzy has expressed that he wants to make new compatibility breaking changes to online mode anyway, so that might not be a serious problem.

**Comment by Wallacoloo** [comment]
Whether or not it is set as the default active theme, I think it's
definitely worth shipping it with stepmania.

**Comment by SpoOkyMagician** [comment]
I think it should be included. However, until online mode is added/worked on, it should remain as a extra theme to use in SM5.

**Comment by shakesoda** [comment]
I use default, for what it's worth.

**Comment by kyzentun** [comment]
I don't want it to replace default entirely.  Default is the theme people go to for examples and to copy paste when starting their own themes, and Consensual is really not suited to that.

**Comment by dguzek** [comment]
I am definitely in favor of packaging Consensual's reskin with a future release of SM5, but I sense 5.0.9 should come out sooner than the reskin will be completed.

**Comment by kyzentun** [comment]
Update:  Not packaging Consensual reskin with 5.0.9 because I spent the last 10 days working on engine stuff instead of the reskin, and the reskin isn't going to be finished in time.
Plus, shakeshoda said on IRC that he doesn't want to bundle it in.

**Comment by wolfman2000** [comment]
Then the case is closed.
