### ISSUE TITLE
1px "gap" separating Hold Body and Hold BottomCap

### ISSUE THREAD

**Issue by dguzek** [stepmania/stepmania#667]
I've determined via git bisect that commit [2656123464656510681d5081d53e62f3227de5ad](https://github.com/stepmania/stepmania/commit/2656123464656510681d5081d53e62f3227de5ad) introduced the known issue of the 1px gap in hold notes.  Unfortunately, the commit made too many changes for me to narrow it down further than that.

**Comment by kyzentun** [comment]
I've been ignoring this bug because I'm hoping to rewrite the noteskin system, NoteField, and ArrowEffects entirely for 5.1.

**Comment by shakesoda** [comment]
It really should be dealt with for 5.0.9. It's an obvious and distracting visual problem...

**Comment by KcHecKa** [comment]
The notefield only works in reverse.

**Comment by kyzentun** [comment]
I don't like this fix, but it gets rid of the seam.
https://github.com/stepmania/stepmania/commit/771e24d1ca50c1c78d46cfa1a08cf95e54e04797
