### ISSUE TITLE
Screenshot PNG not working, using Direct3D renderer

### ISSUE THREAD

**Issue by Prcuvu** [stepmania/stepmania#668]
Version: commit 87349e6723f41506157226c00dc5f48320f21fb8
Built on Windows with Visual Studio 2013

When I pressed PrintScreen, the program always successfully generated a screenshot in JPG format. But when I pressed Shift + PrintScreen, I heard the "invalid sound" and found a 33 KB PNG file, which was surely corrupted. 
There were such lines in `log.txt`:
```
00:23.224: 29 FPS, 32 av FPS, 122357 VPF, D3D
00:24.118: Couldn't write Screenshots/2015-06-05_025757.png: 
00:24.120: Screenshot took 0.125000 seconds.
```
Such problem occurs since 5.0 beta 3 builds. The last working version for me is 5.0 beta 2a.

**Comment by tuxdude143** [comment]
Just tested on stepmania build 5.0.8 and stepmania just straight up crashed. I'll work on looking into this

**Comment by wolfman2000** [comment]
@Prcuvu @tuxdude143  I just ran the latest from master (commit 3bd182b). For both Debug and Release builds, StepMania did not crash upon hitting Shift + Print Screen.

Pictures as proof attached.
![2015-06-10_195340](https://cloud.githubusercontent.com/assets/148345/8097090/8f7979a8-0fac-11e5-9e04-0b12cbe25af6.png)
![2015-06-10_200748](https://cloud.githubusercontent.com/assets/148345/8097089/8f762244-0fac-11e5-816c-0e97fd14afb3.png)

**Comment by Prcuvu** [comment]
@wolfman2000 Curiously, I tried switching renderer to OpenGL just now (on the same build), and the problem disappeared, the PNG screenshot was generated successfully.
In my opinion there might be something wrong with Direct3D renderer. I'm trying to recompile StepMania with a different version of DXSDK to confirm whether the problem is on a specific update.

**Comment by kyzentun** [comment]
The D3D render seems neglected and broken in half a dozen different ways.  I think it should not be the default on Windows.

**Comment by wolfman2000** [comment]
...you are right. My default renderer was OpenGL.

@Prcuvu Feel free to scout: I think the 2009 DirectX package can be used to compile StepMania still (you may have to either modify cmake or the generated project itself though).

I would not object to changing the renderer for Windows.

**Comment by Prcuvu** [comment]
I've tried a great variety of DirectX SDKs, from Summer 2004 to June 2010.
None of them works. Maybe there have been changes in DirectX runtime that
affected how Direct3D renderer works, however, that seems not what is
possible to know.
Having tested both renderers, I've noticed that Direct3D may cause a lot
more rendering problems than only PNG screenshot. For example, in @Kyzentun
's Consensual theme, there are obscure curves in main menu, a strange white
rectangle bar under the NoteField, and more lags (none occurs in OpenGL). I
would suggest disabling Direct3D renderer until it's fixed.

**Comment by kyzentun** [comment]
It looks like this section is what controls the default renderer.
https://github.com/stepmania/stepmania/blob/master/src/StepMania.cpp#L471
It looks like the default is different depending on the video card, and there are several video cards where opengl is disabled, with comments about it crashing.

However, all that info is years out of date.  I used diff to compare it with the same section from the 3.95 source, and it's identical except for the GeForce group now including Quadro, one card went from 1024 texture size to 2048, and one card went from 16bit color to 32bit.

So either the info should be properly updated, and someone found to work on the d3d driver, or it should be disabled entirely.

**Comment by kyzentun** [comment]
Maybe @xwidghet can step up to take over the d3d driver, since he made some improvements to it a few months ago?

**Comment by tuxdude143** [comment]
I personally would like to see someone continue maintaining the Direct 3D support because OpenGL in general really chugs on my computer (and on a lot of computers). I have no idea why but it's not ideal. Direct 3D support should, ideally still be maintained

**Comment by shakesoda** [comment]
@tuxdude143 personally, I'd rather make the main GL renderer use GLES2/GL2 and get d3d support via https://chromium.googlesource.com/angle/angle. We'd have a lot fewer headaches.

This kind of issue should still be fixed, though.

**Comment by kyzentun** [comment]
Yaniel did the work and came up with this fix:
https://github.com/stepmania/stepmania/commit/eb87ca453054f1d03ae8250dc4bac7fd84f1ccd0

**Comment by Prcuvu** [comment]
Many thanks, it is working. By the way, bAlpha is thus unused and should be removed.
