### ISSUE TITLE
stepmania keeps crashing

### ISSUE THREAD

**Issue by deekzavis** [stepmania/stepmania#684]
what do I do?

StepMania5.0-git-b3addbe crash report (build 7, 20150331 @ 23:48:24 EDT)
--------------------------------------

Architecture:   Mac OS X (i386)
Crash reason:   Assertion 'sScreenName != ""' failed
Crashed thread: Main thread

Checkpoints:
Thread: GUI thread
Thread: Main thread
        BitmapText.cpp:208 BitmapText::LoadFromFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini)
        FontManager.cpp:40 FontManager::LoadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        BitmapText.cpp:208 BitmapText::LoadFromFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini)
        FontManager.cpp:40 FontManager::LoadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        ScreenManager.cpp:638 Assertion 'sScreenName != ""' failed
Thread: Decode thread
Thread: Music thread
Thread: HAL I/O thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: Input thread

Thread: 
006240ac: CrashHandler::ForceCrash(char const*) 
00629fcd: sm_crash(char const*) 
004913ee: ScreenManager::SetNewScreen(StdString::CStdStr<char> const&) 
005a9148: sm_main 
00621c7b: -[SMMain startGame:] 

Static log:
StepMania5.0-git-b3addbe
Compiled 20150331 @ 23:48:24 EDT (build 7)
Log starting 2015-06-12 17:37:05
Loading window: macosx
Model: MacBookPro9,2 (4/4)
Clock speed 2.50 GHz
Mac OS X 10.10.2
Memory: 4.00 GB
WARNING: DifficultiesToShow must have at least one entry.
WARNING: CourseDifficultiesToShow must have at least one entry.
Sound driver: AudioUnit
Lights driver: SystemMessage
WARNING: Lua runtime error parsing "ScreenRanking::CoursesToShow": [string "ScreenRanking::CoursesToShow"]:1: malformed number near '4.crs'
Video renderers: 'opengl'
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: Intel Inc.
OGL Renderer: Intel HD Graphics 4000 OpenGL Engine
OGL Version: 2.1 INTEL-10.2.46
OGL Max texture size: 16384
OGL Texture units: 8
GLU Version: 1.3 MacOSX
OGL Extensions:
  GL_APPLE: aux_depth_stencil, client_storage, element_array, fence, float_pixels, flush_buffer_range, 
    flush_render, object_purgeable, packed_pixels, pixel_buffer, rgb_422, row_bytes, specular_vector, 
    texture_range, transform_hint, vertex_array_object, vertex_array_range, vertex_point_size, 
    vertex_program_evaluators, ycbcr_422
  GL_ARB: color_buffer_float, depth_buffer_float, depth_clamp, depth_texture, draw_buffers, 
    draw_elements_base_vertex, draw_instanced, fragment_program, fragment_program_shadow, fragment_shader, 
    framebuffer_object, framebuffer_sRGB, half_float_pixel, half_float_vertex, instanced_arrays, multisample, 
    multitexture, occlusion_query, pixel_buffer_object, point_parameters, point_sprite, provoking_vertex, 
    seamless_cube_map, shader_objects, shader_texture_lod, shading_language_100, shadow, sync, 
    texture_border_clamp, texture_compression, texture_compression_rgtc, texture_cube_map, texture_env_add, 
    texture_env_combine, texture_env_crossbar, texture_env_dot3, texture_float, texture_mirrored_repeat, 
    texture_non_power_of_two, texture_rectangle, texture_rg, transpose_matrix, vertex_array_bgra, vertex_blend, 
    vertex_buffer_object, vertex_program, vertex_shader, window_pos
  GL_ATI: separate_stencil, texture_env_combine3, texture_float, texture_mirror_once
  GL_EXT: abgr, bgra, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, blend_subtract, 
    clip_volume_hint, debug_label, debug_marker, draw_buffers2, draw_range_elements, fog_coord, framebuffer_blit, 
    framebuffer_multisample, framebuffer_multisample_blit_scaled, framebuffer_object, framebuffer_sRGB, 
    geometry_shader4, gpu_program_parameters, gpu_shader4, multi_draw_arrays, packed_depth_stencil, packed_float, 
    provoking_vertex, rescale_normal, secondary_color, separate_specular_color, shadow_funcs, stencil_two_side, 
    stencil_wrap, texture_array, texture_compression_dxt1, texture_compression_s3tc, texture_env_add, 
    texture_filter_anisotropic, texture_integer, texture_lod_bias, texture_rectangle, texture_sRGB, 
    texture_sRGB_decode, texture_shared_exponent, timer_query, transform_feedback, vertex_array_bgra
  GL_IBM_rasterpos_clip
  GL_NV: blend_square, conditional_render, depth_clamp, fog_distance, light_max_exponent, texgen_reflection, 
    texture_barrier
  GL_SGIS: generate_mipmap, texture_edge_clamp, texture_lod
OpenGL Windowed 854x480 32 color 16 texture 60Hz Vsync SmoothLines
WARNING: Couldn't initialize device.
Players joined: none
Language: en
Current renderer: OpenGL
Theme: DDRextreme_beware

Partial log:
00:08.239: RageBitmapTexture: Loaded '/Themes/_fallback/Fonts/_open sans semibold 24px [main-stroke] 15x15.png' (1024x1024); RGBA4, source 540,540;  image 540,540.
00:08.243: Loaded "ScreenSystemLayer" ("ScreenSystemLayer") in 2.300565
00:08.243: Loading screen: "ScreenSyncOverlay"
00:08.245: Loaded "ScreenSyncOverlay" ("ScreenSyncOverlay") in 0.002014
00:08.245: Loading screen: "ScreenStatsOverlay"
00:08.246: Loaded "ScreenStatsOverlay" ("ScreenStatsOverlay") in 0.001013
00:08.246: Loading screen: "ScreenDebugOverlay"
00:08.255: Loaded "ScreenDebugOverlay" ("ScreenDebugOverlay") in 0.008408
00:08.255: Loading screen: "ScreenInstallOverlay"
00:08.255: Loaded "ScreenInstallOverlay" ("ScreenInstallOverlay") in 0.000744

-- End of report

**Comment by wolfman2000** [comment]
That commit matches version 5.0.7. Did you get the binary? Did you compile it? What are you doing to cause the crash?

**Comment by kyzentun** [comment]
"Theme: DDRextreme_beware"

Themes made for StepMania 3.9 or 3.95 or Stepmania 4 or any version older than SM5 beta 3 will not work at all.  Remove them from the theme folder and it should revert to loading the default theme.
