### ISSUE TITLE
Feature Request: Encore Extra Stages that needs a PFC,

### ISSUE THREAD

**Issue by ElementTimes682** [stepmania/stepmania#686]
Yeah, Basically, They should make a mode to clear with a PFC or higher or like a MFC 
(or FFC for Flawless Attack Combo if you like it to call it that)

Like they need a MA (Marvelous/Flawless Attack). By that, They have to get all marvelous (Flawless)

I got this idea originated from DDR X3 and DDR 2014's Phase 2 Encore Extra Stage of Over The Period.

**Comment by wolfman2000** [comment]
Technically, this premiered with Love is the Power.

Still, couldn't this be done with lua at this point? Watch the judgments, and if it's anything less than W2, fail the player?

**Comment by kyzentun** [comment]
Something like this would probably work as an actor on gameplay that fails the player if they don't do well enough on Stage_Extra2:

```
if not GAMESTATE:IsExtraStage2() then return Def.Actor{} end

local function do_fail(pn)
  STATSMAN:GetCurStageStats():GetPlayerStageStats(pn):FailPlayer()
end

local fail_tns= {
  TapNoteScore_Miss= true, TapNoteScore_W5= true, TapNoteScore_W4= true,
  TapNoteScore_W3= true, TapNoteScore_HitMine= true,
  HoldNoteScore_LetGo= true, HoldNoteScore_Missed= true, 
}

return Def.Actor{
  JudgmentMessageCommand= function(self, param)
    if fail_tns[param.TapNoteScore] or fail_tns[param.HoldNoteScore] then
      do_fail(param.Player)
    end
  end
}
```

**Comment by kyzentun** [comment]
I don't think it's appropriate as part of the default Stepmania theme, it's more suited to the various DDR themes that try to emulate DDR.  So send one of them that example code and maybe they'll put it in their theme.

**Comment by ElementTimes682** [comment]
Uh, How are we gonna do this with a specific stage?

**Comment by dguzek** [comment]
The feature request explicitly mentioned *Encore Extra Stage* so kyzentun wrote the code snippet above to check for ExtraStage2. 

```lua
if not GAMESTATE:IsExtraStage2() then return Def.Actor{} end
```

If the StepMania engine doesn't consider the current stage to be "ExtraStage2" then it returns early and doesn't execute the rest of that code.  So, if that was your question, it's already handled.

---

If you are asking how to use the above code, you can do so copy/pasting it into a .lua file and calling that file from *./BGAnimations/ScreenGameplay underlay/default.lua*

If you named the file something like **EncoreExtraStage.lua** then you would place it in *./BGAnimations/Screen Gameplay underlay/* and call it from the default.lua that also resided there like:

```lua
LoadActor("./EncoreExtraStage.lua");
```

---

Generally speaking, theming questions are better left for the [StepMania forums](http://www.stepmania.com/forums/) than GitHub.
