### ISSUE TITLE
Stepmania.exe is not a valid Win32 application

### ISSUE THREAD

**Issue by Leo137** [stepmania/stepmania#688]
Running Stepmania 5.0.8b on my Windows XP machine, i encountered that issue at the moment of launching the game, 5.0.7 doesn't seems to give any troubles

**Comment by dguzek** [comment]
I can reproduce this on my Windows XP VM using the 5.0.8b download from GitHub.

This issue is not present in the May 8, 2015 nightly build found on the nightly server.

**Comment by kyzentun** [comment]
Hm, May 8th was right before the release, maybe it's an issue with the SDK version that was used to make the release.

**Comment by dguzek** [comment]
If anyone can get me an early copy of a 5.0.9 installer, I'd be happy to test it as soon as I get it.

**Comment by kyzentun** [comment]
I'll pass the word on to @wolfman2000 and @tuxdude143 to have them make a build as soon as they can.  I don't think there are going to be anymore changes before release.

**Comment by kyzentun** [comment]
From Yaniel:  http://filebin.net/lp311mypo3
(also confirm whether it truly fixes #668)

**Comment by dguzek** [comment]
The build provided by Yaniel does not open on my Windows XP VM, producing the same error:

![screen shot 2015-06-19 at 5 15 52 pm](https://cloud.githubusercontent.com/assets/1253483/8263254/de6116ec-16a6-11e5-952a-506193afd8d5.png)

No crash log or logs of any kind are produced.

**Comment by Leo137** [comment]
Same result to me.

**Comment by jansol** [comment]
updated linked file

**Comment by Leo137** [comment]
Now i got this

![error](http://puu.sh/ivjwI.png)

Seems i need to grab this: http://www.microsoft.com/en-us/download/details.aspx?id=40784

let me check

**Comment by Leo137** [comment]
Gotcha ;)

![asd](http://puu.sh/ivjTQ.jpg)
![asd2](http://puu.sh/ivk4Y.png)
