### ISSUE TITLE
Video not found?? (BMS)

### ISSUE THREAD

**Issue by farsdewibs0n** [stepmania/stepmania#698]
do you know how to play bms files wihout video??
error code:
StepMania v5.0 beta 3 crash report (build 11, 20140224 @ 15:37:56 Central Standard Time)
--------------------------------------

Crash reason: Invalid parameter

Thread: Main thread
        RageFileDriverDirectHelpers.cpp:158 C:/Users/A/AppData/Roaming/StepMania 5/Cache/Songs/Songs_COMPLETE MIX_Kagen no tsuki
        RageFileDriverDirectHelpers.cpp:227 D:/game/StepMania 5/Songs/COMPLETE MIX/KAMAITACHI/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/A/AppData/Roaming/StepMania 5/Songs/COMPLETE MIX/KAMAITACHI/*
        RageFileDriverDirectHelpers.cpp:227 D:/game/StepMania 5/Songs/COMPLETE MIX/KAMAITACHI/*
        ArchHooks_Win32.cpp:22 Invalid parameter
Thread: Decode thread
Thread: Mixer thread
Thread: Music thread

00520e2d: long MainExceptionHandler(struct _EXCEPTION_POINTERS *) [00400000+120e28+5]
00509aa6: void sm_crash(char const *) [00400000+109a8b+1b]
00514abb: void InvalidParameterHandler(wchar_t const *,wchar_t const *,wchar_t const *,unsigned int,unsigned int) [00400000+114a9f+1c]
6fd6ccd5: MSVCR90!invalid_parameter_noinfo [6fd00000+6ccc9+c]
004cecd7: bool BMSChartReader::ReadNoteData(void) [00400000+ce59f+738]
56295e94: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::basic_string<char,std::char_traits<char>,std::allocator<char> > [56290000+5e81+13]
56296403: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [56290000+63c3+40]
56296458: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [56290000+643c+1c]
562a2115: MSVCP90!std::collate<unsigned short>::do_compare [56290000+11fab+16a]
56295e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [56290000+5dfb+48]
770b2ce8: ntdll!RtlFreeHeap [77060000+52c6a+7e]
6fd63eb8: MSVCR90!operator new [6fd00000+63e99+1f]
005fe51c: struct std::_Tree_nod<class std::_Tmap_traits<class Steps *,class Song *,struct std::less<class Steps *>,class std::allocator<struct std::pair<class Steps * const,class Song *> >,0> >::_Node * std::_Allocate<struct std::_Tree_nod<class std::_Tmap_traits<class Steps *,class Song *,struct std::less<class Steps *>,class std::allocator<struct std::pair<class Steps * const,class Song *> >,0> >::_Node>(unsigned int,struct std::_Tree_nod<class std::_Tmap_traits<class Steps *,class Song *,struct std::less<class Steps *>,class std::allocator<struct std::pair<class Steps * const,class Song *> >,0> >::_Node *) [00400000+1fe4e3+39]
005e39a8: struct std::_Tree_nod<class std::_Tmap_traits<class Steps *,class Song *,struct std::less<class Steps *>,class std::allocator<struct std::pair<class Steps * const,class Song *> >,0> >::_Node * std::_Tree<class std::_Tmap_traits<class Steps *,class Song *,struct std::less<class Steps *>,class std::allocator<struct std::pair<class Steps * const,class Song *> >,0> >::_Buynode(struct std::_Tree_nod<class std::_Tmap_traits<class Steps *,class Song *,struct std::less<class Steps *>,class std::allocator<struct std::pair<class Steps * const,class Song *> >,0> >::_Node *,struct std::_Tree_nod<class std::_Tmap_traits<class Steps *,class Song *,struct std::less<class Steps *>,class std::allocator<struct std::pair<class Steps * const,class Song *> >,0> >::_Node *,struct std::_Tree_nod<class std::_Tmap_traits<class Steps *,class Song *,struct std::less<class Steps *>,class std::allocator<struct std::pair<class Steps * const,class Song *> >,0> >::_Node *,struct std::pair<class Steps * const,class Song *> const &,
004a6f81: class std::_Tree<class std::_Tmap_traits<enum InputDevice,class InputHandler *,struct std::less<enum InputDevice>,class std::allocator<struct std::pair<enum InputDevice const ,class InputHandler *> >,0> >::iterator std::_Tree<class std::_Tmap_traits<enum InputDevice,class InputHandler *,struct std::less<enum InputDevice>,class std::allocator<struct std::pair<enum InputDevice const ,class InputHandler *> >,0> >::_Insert(bool,struct std::_Tree_nod<class std::_Tmap_traits<enum InputDevice,class InputHandler *,struct std::less<enum InputDevice>,class std::allocator<struct std::pair<enum InputDevice const ,class InputHandler *> >,0> >::_Node *,struct std::pair<enum InputDevice const ,class InputHandler *> const &) [00400000+a6e26+15b]
0041fdd4: class std::_Tree<class std::_Tmap_traits<int,bool,struct std::less<int>,class std::allocator<struct std::pair<int const ,bool> >,0> >::iterator std::_Tree<class std::_Tmap_traits<int,bool,struct std::less<int>,class std::allocator<struct std::pair<int const ,bool> >,0> >::insert(class std::_Tree<class std::_Tmap_traits<int,bool,struct std::less<int>,class std::allocator<struct std::pair<int const ,bool> >,0> >::const_iterator,struct std::pair<int const ,bool> const &) [00400000+1fcac+128]
004d01cd: class std::_Tree<class std::_Tmap_traits<int,int,struct std::less<int>,class std::allocator<struct std::pair<int const ,int> >,0> >::iterator std::_Tree<class std::_Tmap_traits<int,int,struct std::less<int>,class std::allocator<struct std::pair<int const ,int> >,0> >::lower_bound(int const &) [00400000+d01b9+14]
004cf271: bool BMSChartReader::Read(void) [00400000+cf25b+16]
004cf3b7: bool BMSSongLoader::Load(class StdString::CStdStr<char>) [00400000+cf309+ae]
770b2fe7: ntdll!RtlAllocateHeap [77060000+52dd6+211]
56296149: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Grow [56290000+60f5+54]
7517179c: KERNELBASE!WaitForSingleObjectEx [75170000+1730+6c]
770b2fe7: ntdll!RtlAllocateHeap [77060000+52dd6+211]
770b2fe7: ntdll!RtlAllocateHeap [77060000+52dd6+211]
770b2e82: ntdll!RtlAllocateHeap [77060000+52dd6+ac]
770b2e82: ntdll!RtlAllocateHeap [77060000+52dd6+ac]
6fd63eb8: MSVCR90!operator new [6fd00000+63e99+1f]
6fd369ed: MSVCR90!memcpy_s [6fd00000+369a3+4a]
562963b5: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [56290000+632a+8b]
004cf511: bool BMSLoader::LoadFromDir(class StdString::CStdStr<char> const &,class Song &) [00400000+cf434+dd]
6fd63c3a: MSVCR90!free [6fd00000+63b4e+ec]
56295e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [56290000+5dfb+48]
004ccc4a: void BMSLoader::GetApplicableFiles(class StdString::CStdStr<char> const &,class std::vector<class StdString::CStdStr<char>,class std::allocator<class StdString::CStdStr<char> > > &) [00400000+ccb55+f5]
004cc95b: bool NotesLoader::LoadFromDir(class StdString::CStdStr<char> const &,class Song &,class std::set<class StdString::CStdStr<char>,struct std::less<class StdString::CStdStr<char> >,class std::allocator<class StdString::CStdStr<char> > > &) [00400000+cc805+156]
56295e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [56290000+5dfb+48]
56295ec4: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > [56290000+5ebb+9]
00585a80: enum RageFileManager::FileType RageFileManager::GetFileType(class StdString::CStdStr<char> const &) [00400000+1859bd+c3]
562963aa: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [56290000+632a+80]
004b7e1c: bool Song::LoadFromSongDir(class StdString::CStdStr<char>) [00400000+b7c47+1d5]
770b2fe7: ntdll!RtlAllocateHeap [77060000+52dd6+211]
6fd63eb8: MSVCR90!operator new [6fd00000+63e99+1f]
6fd369ed: MSVCR90!memcpy_s [6fd00000+369a3+4a]
56294f2a: MSVCP90!std::char_traits<char>::_Copy_s [56290000+4f13+17]
56295242: MSVCP90!std::allocator<wchar_t>::deallocate [56290000+5081+1c1]
562959d5: MSVCP90!std::allocator<char>::allocate [56290000+5929+ac]
562963aa: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [56290000+632a+80]
562963b5: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [56290000+632a+8b]
562972aa: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::basic_string<char,std::char_traits<char>,std::allocator<char> > [56290000+7286+24]
005fd10c: void SongManager::LoadStepManiaSongDir(class StdString::CStdStr<char>,class LoadingWindow *) [00400000+1fcd52+3ba]
768ac484: kernel32!HeapFree [76860000+4c470+14]
005fd2cb: void SongManager::InitSongsFromDisk(class LoadingWindow *) [00400000+1fd297+34]
005fe198: void SongManager::InitAll(class LoadingWindow *) [00400000+1fe18c+c]
0050c7ac: main() [00400000+10bf67+845]
6fd22e2b: MSVCR90!unlock [6fd00000+22e16+15]
6fd667ab: MSVCR90!realloc [6fd00000+66415+396]
6fd238b3: MSVCR90!initptd [6fd00000+23753+160]
005204cf: WinMain@16() [00400000+1204b9+16]
0067b05e: __tmainCRTStartup() [00400000+27af1e+140]
770c37be: ntdll!RtlInitializeExceptionChain [77060000+636fc+c2]

Static log:
StepMania v5.0 beta 3
Compiled 20140224 @ 15:37:56 Central Standard Time (build 11)
Log starting 2015-06-25 20:47:18
Loading window: win32
Windows 6.1 (Win7) build 7601 [Service Pack 1]
Memory: 2008mb total, 4095mb swap (3814mb swap avail)
Video driver: Intel(R) Graphics Media Accelerator 3600 Series [Intel Corporation]
              8.14.8.1096, 10-23-2013 [pci\ven_8086&dev_0be1]
Drive: "HGST HTS545050A7E38" Driver: iaSto DMA: yes
Sound device 0: Speakers (High Definition Audio, 0.0, MID 1, PID 65535 
WARNING: Invalid StepsType value 'pump-solo' in 'dance-couple,dance-solo,dance-threepanel,dance-routine,pump-couple,pump-halfdouble,pump-solo,lights-cabinet'
DirectSound Driver: Primary Sound Driver
DirectSound Driver: Speakers (High Definition Audio Device) {0.0.0.00000000}.{51609736-b722-4c80-9557-161b0a1c3f98}
DirectSound sample rates: 100..200000 (continuous)
Software mixing at 44100 hz
Sound driver: DirectSound-sw
Lights driver: SystemMessage
Lights driver: Export
Language: en
Theme: PIU Delta NEX 2.5.1

Partial log:
02:03.929: Song::SaveToSSCFile('Cache/Songs/Songs_COMPLETE MIX_IXION')
02:04.429: Song::LoadFromBMSDir(/Songs/COMPLETE MIX/Kagachi/)
02:04.777: Song file "/Songs/COMPLETE MIX/Kagachi/" references bmp "../../bga/COMPLETE MIX/Kagachi.avi" that can't be found
02:07.686: Song::SaveToSSCFile('Cache/Songs/Songs_COMPLETE MIX_Kagachi')
02:08.167: Song::LoadFromBMSDir(/Songs/COMPLETE MIX/Kagen no tsuki/)
02:08.397: Song file "/Songs/COMPLETE MIX/Kagen no tsuki/" references bmp "../../bga/COMPLETE MIX/kagen no tsuki.avi" that can't be found
02:10.151: Song::SaveToSSCFile('Cache/Songs/Songs_COMPLETE MIX_Kagen no tsuki')
02:10.638: Song::LoadFromBMSDir(/Songs/COMPLETE MIX/KAMAITACHI/)
02:10.867: Song file "/Songs/COMPLETE MIX/KAMAITACHI/" references bmp "..\!\image\BLACK.png" that can't be found
02:10.869: Song file "/Songs/COMPLETE MIX/KAMAITACHI/" references bmp "../../bga/COMPLETE MIX/KAMAITACHI.avi" that can't be found

-- End of report

**Comment by kyzentun** [comment]
Several crashes in the BMS loader were fixed after beta 3.  Try again with SM 5.0.9.
