### ISSUE TITLE
MEMCARDMAN bug

### ISSUE THREAD

**Issue by sillybear** [stepmania/stepmania#714]
When MemoryCards=1 and MemoryCardProfiles=0 in Preference.ini and I inserted a USB memory card in P1 or P2 slot, MEMCARDMAN:GetCardState(PLAYER_1) or MEMCARDMAN:GetCardState(PLAYER_2) always returns 'MemoryCardState_none'.

They only return 'MemoryCardState_ready' if both are set to 1.

**Comment by kyzentun** [comment]
Looking at the source in MemoryCardManager.cpp, this looks intentional.

**Comment by sillybear** [comment]
My purpose for this is I want to load songs from the memory card without loading the player profile. If at least one memory card is available, after title screen, it will direct to a custom ScreenReloadSongs screen, otherwise it will direct to ScreenCaution. I don't want to use LoadProfile screen.
