### ISSUE TITLE
AllowLateJoin suggestion

### ISSUE THREAD

**Issue by sillybear** [stepmania/stepmania#715]
Make AllowLateJoin be part of ScreenWithMenuElements instead of GameState theme metric. There are some screens (other than ScreenAttract, ScreenTitleJoin and ScreenSelectStyle) in some custom themes that need to set AllowLateJoin to false, assuming that the default fallback value is true.

**Comment by kyzentun** [comment]
Read the fucking Lua.xml.  ScreenWithMenuElements has had a lua function for toggling whether late joinining is allowed on the screen for over a year.  https://github.com/stepmania/stepmania/commit/779e3da2866917f87e3b84074e50f5755fd3a6ec

**Comment by sillybear** [comment]
ScreenWithMenuElements' SetAllowLateJoin is broken anyway.
