### ISSUE TITLE
All 4 arrows simultaneous on OSX

### ISSUE THREAD

**Issue by jwoertink** [stepmania/stepmania#723]
Pressing 3 of the arrows at the same time seem to work fine, but pressing all 4 at the same nothing happens. I know this worked way back in version 3. Is this a bug, or just something removed?

Running v 5.0.9 on OSX 10.9.5

**Comment by kyzentun** [comment]
This is a result of how keyboards are made.  Most keyboards aren't designed to register all four arrow keys at once.  Experiment on the test input screen to find four keys that don't conflict with each other.

If you're using a dance pad, then it's a different problem.

**Comment by shakesoda** [comment]
Hardware problem. It's your keyboard, change your key mappings or it won't work.
