### ISSUE TITLE
[proposal] Change display of difficulty

### ISSUE THREAD

**Issue by HirotakaTakayama** [stepmania/stepmania#724]
I'm terribly sorry If this topic was raised in the past.
StepMania's difficulty is NOVICE, EASY, MEDIUM, HARD and EXPERT. 
But, DDR's difficulty is Beginner, Basic, Difficult, Expert and Challenge ( I saw https://en.wikipedia.org/wiki/Dance_Dance_Revolution ).

Both games have EXPERT. But, it's different mean. I was confused at the first time.
Is it possible to consider to change the difficulty style from StepMania to DDR?

**Comment by Flameshadowxeroshin** [comment]
If that was done, some ITG player would probably complain that Expert now meant Difficulty_Hard instead of Difficulty_Challenge.

**Comment by ZeroTheSavior** [comment]
Why don't we just come to a compromise and add an option to change the display names?

**Comment by Flameshadowxeroshin** [comment]
that adds a bit of Lua, another ThemePref, and at least one custom options row for something that isn't even that important and wouldn't even work right without some tricks

**Comment by kyzentun** [comment]
We're not using DDR's difficulty names.  If you want DDR difficulty names, go find some crap DDR theme.

**Comment by HirotakaTakayama** [comment]
Thank you for answering my proposal and question!
