### ISSUE TITLE
Error Direct 3D

### ISSUE THREAD

**Issue by tio119** [stepmania/stepmania#727]
I got an error. I can't solve it.
Please help me.
Initializing opengl...
SetVideoMode failed: The WGL_EXT_swap_control extension is not supported on your computer.;The WGL_EXT_swap_control extension is not supported on your computer.;The WGL_EXT_swap_control extension is not supported on your computer.;The WGL_EXT_swap_control extension is not supported on your computer.
[Initializing d3d...]
[Your system is reporting that Direct3D hardware acceleration is not available.  Please obtain ]
[updated driver from your video card manufacturer.]

**Comment by shakesoda** [comment]
Update your video card drivers.
