### ISSUE TITLE
In editor, offset changes in playback depending on where I start playing

### ISSUE THREAD

**Issue by darknotezero** [stepmania/stepmania#731]
Video makes this clearer than trying to explain in words.  I believe the offset is consistent based on location of when i hit play (as in, if i start in m. 7, offset will always be the same, but measure to measure it changes).

Video: https://youtu.be/xjkWCc4U9TE

Version of Stepmania is 5.0.7.  Didn't see mention of this on release notes for newest build.
OS is Mac OS X 10.10.4

**Comment by shakesoda** [comment]
Don't use VBR MP3's.

**Comment by darknotezero** [comment]
aaaah.  cool.

**Comment by Prcuvu** [comment]
Is this issue based on resample libraries? StepMania 3.9 used libresample and didn't have such problem.
