### ISSUE TITLE
RollingNumbers new theme metric: "LeadingTextCharacter"

### ISSUE THREAD

**Issue by sillybear** [stepmania/stepmania#732]
Some rolling numbers require to use a real texture (other than plain white bitmap text) for leading zeroes so that it will display its original color when LeadingZeroMultiplyColor="#ffffff" . LeadingTextCharacter can be set to "0" (default) or "?" (for leading zero character from real texture).

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/pull/733
