### ISSUE TITLE
[Noteskin] Hold Body Inactive image bug during hold miss

### ISSUE THREAD

**Issue by sillybear** [stepmania/stepmania#738]
See this video (Note: I'm using custom theme)

https://goo.gl/pfE2Gp

As you can see, the hold body inactive doesn't move when it reaches the top edge of the screen, making it weird alongside the hold bottom cap image.

**Comment by kyzentun** [comment]
I'm currently working on a complete rewrite of the notefield and noteskin system, to deal with issues like this and other problems, which will go into the 5.1.x line.  So this bug is not going to be fixed in the 5.0.x line, and will not occur in 5.1 onwards.

**Comment by sillybear** [comment]
Paging @waiei , you are my last hope before they finally release SM 5.1. Please help me fix this hold body bug during reverse.
