### ISSUE TITLE
Different transformation for each MusicWheel item?

### ISSUE THREAD

**Issue by wasingtjme** [stepmania/stepmania#739]
**Hello everyone. I'm making a new SM5 theme. What I need now is to make each MusicWheel item transform in different way. And I found out this in {metrics.ini}:**

[ScreenSelectMusic]
.....................
CDTitleOnCommand=draworder,10;scaletoclipped,247,190;diffusealpha,0;finishtweening;sleep,0.3;linear,1;diffusealpha,1
CDTitleOffCommand=sleep,0.2;linear,0.5;zoom,0.5;decelerate,0.9;zoom,3
CDTitleFrontCommand=
CDTitleBackCommand=
.....................
***---[[this is the transformation command part]]---***
CDTitleOnCommand=draworder,10;scaletoclipped,247,190;diffusealpha,0;finishtweening;sleep,0.3;linear,1;diffusealpha,1
CDTitleOffCommand=sleep,0.2;linear,0.5;zoom,0.5;decelerate,0.9;zoom,3
CDTitleFrontCommand=
CDTitleBackCommand=
CDTitleX=SCREEN_CENTER_X
CDTitleY=SCREEN_CENTER_Y-7
................
MusicWheelX=-SCREEN_CENTER_X*3
MusicWheelY=SCREEN_CENTER_Y-7
MusicWheelOnCommand=zoom,2;diffusealpha,0;addx,SCREEN_CENTER_X*4;fov,72;linear,.5;zoom,1;diffusealpha,1
MusicWheelOffCommand=Hidden,1
......................
[MusicWheel]
.....................
ItemTransformFunction=function(self,offsetFromCenter,itemIndex,numItems) HandleWheel(self,offsetFromCenter,itemIndex,numItems) end;
.....................
**Yeah. Some kind of link to HandleWheel function in {utils.lua}:**

function HandleWheel( self,offsetFromCenter,itemIndex,numItems )
	local x = offsetFromCenter * 180
		if offsetFromCenter >= 1 then
			x = scale(offsetFromCenter+1,-1,1,-.5,.5) * 180
		elseif offsetFromCenter <= -1 then
			x = scale(offsetFromCenter-1,-1,1,-.5,.5) * 180
	end
	self:zoom(math.cos(offsetFromCenter/math.pi))
	self:x( x )
	self:z((-clamp(math.abs(offsetFromCenter),0,1)*170)-math.abs(offsetFromCenter))
	self:rotationy( clamp( offsetFromCenter, -1, 1) * 75)
end

**But the only thing is, the transformation is applied to *the whole MusicWheel.* How can I get it to work with each MusicWheel item instead? I really need help. Thanks so much!**

**Comment by dguzek** [comment]
Generally, we try to reserve GitHub's issue tracker for things like bug reports and pull requests. 

Scripting questions like this are better suited for the [stepmania.com forums](http://www.stepmania.com/forums/).  You may want to try asking your question there.
