### ISSUE TITLE
Link to DirectX and VS runtimes on download page

### ISSUE THREAD

**Issue by whatsthepoint** [stepmania/stepmania#741]
Instead of having it be in an FAQ page a couple links deep and always having to answer it on forums/IRC, it would be nice to have BIG WARNING LETTERS (well, not that big) stating that you also need to install the DX9/VS runtimes and then linking them right on the download page at http://www.stepmania.com/download/.

This is especially the case for the VS runtime, since lots of people will have old games still using (and installing) DX9, but VS2013 is still relatively new and it's not uncommon to not have programs using it.

DirectX runtime: https://www.microsoft.com/en-ca/download/details.aspx?id=35 
VS2013 runtime: https://www.microsoft.com/en-ca/download/details.aspx?id=40784

(And if/when VS2015 gets used to build SM, then links need to get updated.)

**Comment by shakesoda** [comment]
file website things [here](/stepmania/stepmania-site) instead.
