### ISSUE TITLE
Missing .ini's

### ISSUE THREAD

**Issue by smokofrodo71** [stepmania/stepmania#746]
00:00.033: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.034: Reading 'Data/Static.ini' failed: No such file or directory
00:00.034: Reading 'Data/Static.ini' failed: No such file or directory

**Comment by smokofrodo71** [comment]
00:00.033: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.034: Reading 'Data/Static.ini' failed: No such file or directory
00:00.034: Reading 'Data/Static.ini' failed: No such file or directory

**Comment by dguzek** [comment]
>Static.ini? That's a name I haven't heard in a long time.

StepMania 3.9 and OpenITG use *Static.ini* files but StepMania 5 does not and hasn't ever that I know of.

If you're using SM3.9, that version is no longer supported.
If you're using OpenITG, you can try filing an issue on [that project's tracker](https://github.com/openitg/openitg/issues).

If you're using a theme or noteskin designed for one of those with StepMania 5, that is not supported, either.

**Comment by kyzentun** [comment]
The same lines show up in my log file, so this isn't a case of someone using the wrong version.
SM5 is looking for those files, but it doesn't matter if they're missing.  Someone should hunt down the code that tries to load the files and decide whether they should be used.

**Comment by freem** [comment]
From what I remember, [they're still supported](https://github.com/stepmania/stepmania/search?utf8=%E2%9C%93&q=%22static.ini%22&type=Code)...

**Comment by smokofrodo71** [comment]
not sure if this is going to help but for every theme i have except DDR 2014 every time i try to play a song it crashes and always gives me the missing Data/Data.ini error

**Comment by shakesoda** [comment]
Static.ini files totally work fine. I use them regularly.

Those files are missing because they aren't needed, it just happens to be logged. There's no bug here.

**Comment by dguzek** [comment]
That's really interesting; I had no idea.  Thanks for clarifying, @shakesoda.

**Comment by smokofrodo71** [comment]
so then how come none of my themes want to work

**Comment by dguzek** [comment]
Can you provide a list of what themes present this issue?

**Comment by smokofrodo71** [comment]
DDR Max 2 HD
DDRNG
DDR 5TH MIX

**Comment by dguzek** [comment]
Fresh downloads of themes work without issue for me.

What happens when you use the default theme that comes with SM5?
It it also crashes, then whatever problem you're encountering will be most easily resolved by uninstalled StepMania 5, then deleting any remaining application files, then doing a completely fresh install.

**Comment by smokofrodo71** [comment]
default theme works perfectly fine.

**Comment by shakesoda** [comment]
The ini warnings aren't crash errors. It's not the crash reason.

**Comment by smokofrodo71** [comment]
have i been looking in the wrong text document?

**Comment by smokofrodo71** [comment]
alright. so i think i HAVE been looking at the wrong text doc http://prntscr.com/869vqj
anyone wanna help?

**Comment by kyzentun** [comment]
It looks like you have the theme in two place, both in the desktop folder, and in the appdata folder.  Remove it from the desktop folder and only have it in the appdata folder, and try again.

**Comment by smokofrodo71** [comment]
i deleted the one from the desktop folder and and the theme still doesnt work.

**Comment by kyzentun** [comment]
Outdated.
