### ISSUE TITLE
Stepmnaia weird crash; won't open

### ISSUE THREAD

**Issue by SuillaIsAwesome** [stepmania/stepmania#752]
I Tried to open stepmanis, I had just downloaded the ddr 2014 theme, and it crashed with this window saying 'No NoteSkins'. So i went into my application support, stepmania 5.0.9 and put some noteskins in THERE instead of the game file (The noteskins file was empty). and then it came up with something else. heres the screenshots.
![screen shot 2015-08-23 at 13 20 29](https://cloud.githubusercontent.com/assets/13925044/9426802/31662c58-499a-11e5-9fe7-1ec2426919fd.png)
![screen shot 2015-08-23 at 13 24 01](https://cloud.githubusercontent.com/assets/13925044/9426806/43271966-499a-11e5-941c-8bb553bf4c4b.png)
I would really appriceate it if you could help me with this, P.S, im on a mac

**Comment by kyzentun** [comment]
The forum or IRC channel is a better place for tech support issues like this.
Stepmania should have come with noteskins, so if you didn't get stepmania from the release page on github or the download page on stepmania.com, that is probably the source of the problem.

**Comment by SuillaIsAwesome** [comment]
I did indeed download it from the stepmania website, but what happened was i had only just placed stepmania in the application folder. so when i went to the application support folder, and then stepmania, the notskins folder had nothing in it. so i placed all of the same folders from the game folder to that folder in the application support.

**Comment by dguzek** [comment]
On OS X, the StepMania application folder should (probably) not be installed to the root-level `/Applications/` directory; I have seen it cause permissions problems.  It is better have it reside somewhere in your user directory.

So, for example, if your OS X username is SuillaIsAwesome, then an appropriate place to install StepMania would be `/Users/SuillaIsAwesome/StepMania 5` or `/Users/SuillaIsAwesome/Games/StepMania 5/`
