### ISSUE TITLE
Editor Issue - Pump

### ISSUE THREAD

**Issue by DXUltimate** [stepmania/stepmania#753]
I have found another problem, however, it is with the Pump style when opening the editor for the song "Coming Out" in Pump it up Pro. This file was downloaded from pumpproplus.com if this means anything, which it probably won't. If it has something to do with the formatting of the old .sm's, how would I be able to rewrite a new .sm file for it? The initial reason for this discovery is because I recently found out that my Infinity Pump location has edits, and I really REALLY want to make edit charts for songs on the machine.

Pastebin: http://pastebin.com/Y2ZdfyPX
This will expire in 30 days time.

Steps to reproduce;
Step 1: Download file from PPP
Step 2: Load StepMania 5.0.x (originally I was using an outdated version of StepMania 5, version 5.0.7 to be exact, so I thought that was the main issue, I updated to 5.0.9 and it is still producing the crash)
Step 3: Proceed into options and change gamemode to "Pump".
Step 4: Open up editor menus, and select Coming Out, highlight the "EXPERT" blank difficulty to create the initial steps for it.
Step 5: Crash

Thank you for reviewing this as a potential cilentside issue. As always, keep up the hard work you all do for us.

**Comment by dguzek** [comment]
I downloaded the file you specified, Coming Out, from pumpproplus.com, and created a new challenge difficulty, wrote some steps, saved it, modified, saved, quit, restarted, loaded, etc. -- all without issue.

**Comment by wolfman2000** [comment]
@dguzek I need to clarify. Did you do that test on 5.0.9 directly, or the latest source?

**Comment by kyzentun** [comment]
There's the possibility that the crash only occurs if the game starts up in non-pump game mode, then changes to pump after startup (so you start it up in dance mode, then use the menu to switch to pump mode, then go into edit mode to make a chart).  That needs to be investigated to avoid thinking the bug is unreproducible.

**Comment by dguzek** [comment]
@wolfman2000 -- That's a good point.  I tested using the latest code from the master branch.

**Comment by DXUltimate** [comment]
I actually tried it again, and it reproduced the exact same crash message. New pastebin here, expires in a week, looks similar, almost like a carbon copy. This time, it booted in pump mode, went straight to the editor, with the same song, and it caused it again, just as it did in the original message.

http://pastebin.com/1H2NABeu

**Comment by dguzek** [comment]
@kyzentun – I tried various combinations like:
+ starting in dance and loading/writing steps, switching to pump and loading/writing steps
+ starting in pump  and loading writing steps, switching to dance and loading/writing steps
+ starting in pump and loading writing steps, quitting, restarting, and loading/writing more steps
+ starting in dance and loading writing steps, quitting, restarting, and loading/writing more steps

I was unable to reproduce this crash using the latest build from master branch.

**Comment by dguzek** [comment]
I'm also unable to reproduce this bug using the release version of SM5.0.9

**Comment by DXUltimate** [comment]
I really don't know what to do then. =(

I actually went out of my way and did a complete reinstall of 5.0.9 and the same issue is still coming up. I tried a complete recache of all 17,000+ songs I have, and nothing. What are all the possibilities that could be causing this? It must be on my end if no one else can reproduce the issue.

I am currently using Windows 7 Home (as stated in the log) and UAC is off. I'm at a standstill right now. =(

**Comment by kyzentun** [comment]
When you upgraded from 5.0.7 to 5.0.9, did you accidentally copy the default theme from the game folder to a user data folder like %APPDATA%/StepMania 5/Themes?
Your log has this line at the end:
WARNING: ThemeManager:  There is more than one theme element that matches 'default/Graphics/NoteField board'.  Please remove all but one of these matches: /Themes/default/Graphics/NoteField board.png, /Themes/default/Graphics/NoteField board.png

That makes it look like the default theme version you have is outdated, and somehow has a duplicated file.  If %APPDATA%/StepMania 5/Themes has a copy of the default theme in it, that copy needs to be removed.  If the file named in the message exists in the default theme folder in the normal game folder, then the reinstall must not have been clean.

If that duplicate file is the problem, then editing anything should crash, since it's unrelated to pump mode.

**Comment by DXUltimate** [comment]
I do see the error you're talking about. Although, I am sure that it is not causing the crash.

http://puu.sh/jOI1X/6d3c0b73ed.jpg - Simply Love theme
http://puu.sh/jOI82/49c3aa37af.jpg - Default theme

Both themes were able to open up the editor in 4 panel Dance mode, but not 5 panel pump mode for some reason. It is able to boot "dance" simfiles in the editor without an issue. I even resorted to changing the noteskin for pump to see if that was actually the issue, turns out it wasn't and it crashed with every other noteskin that I have for it, which is all of the noteskins that come with the game. My theme folder;

http://puu.sh/jOIfU/358cdec9f0.jpg - in C:\StepMania 5\Themes
http://puu.sh/jOIon/6ad7a08052.jpg - in %appdata%\StepMania 5\Themes

"Folder" is where my old Simply Love theme was before I updated it, just in case it wasn't working on the newer versions of stepmania.

Thank you all for taking the time on reviewing my issue. =)

**Comment by kyzentun** [comment]
I tried copying the 5.0.7 default, then putting 5.0.9 on top of it, then running that in 5.0.9, and I got the message saying that there is more than one Notefield board file.  So I think that's your problem.
You could download the source code zip of the 5.0.9 release (https://github.com/stepmania/stepmania/archive/v5.0.9.zip), delete the default and _fallback folders from your stepmania Themes folder, then put in the ones from the source code zip.

**Comment by DXUltimate** [comment]
I have removed the _fallback and the Default folders as instructed, and replaced then in the zip that you have provided. I am still getting this crash. Another Access Violation crash.

http://pastebin.com/ZXC2U8z4

**Comment by kyzentun** [comment]
Well, I'm baffled and out of ideas.  If you were on Linux, I'd tell you to rebuild with debugging symbols and run it in a debugger to get an actual backtrace, since the backtrace that's supposed to be in the log is broken.
Maybe it's running out of memory or something, since you have so many songs and the Windows version is still 32 bit.

**Comment by SpoOkyMagician** [comment]
I just wanted to point something out. I know we had this conversation before on the IRC at one point. (or at least I did with some of the others.) I am unsure if it was ever fixed/looked into but, there used to be a bug creating a pump file on challenge/expert. (Had something to do with this difficulty.) It would crash the game. Step 4 is the idea I am getting at. I just trying it in in a different file in the editor and it works fine for me now. (The file was created)

**Comment by DXUltimate** [comment]
If that's the case, I am immediately moving to whichever nightly build you are using. Simfile creation on the pump gamemode is an absolute must especially since we have a new Infinity machine that supports edits. =3

Thank you all for looking into this.

Which nightly build did you use to test the simfiles?

**Comment by SpoOkyMagician** [comment]
I am using Stepmania 5 908 2015-05-08_11-18-13 on here: http://smnightly.katzepower.com/

**Comment by DXUltimate** [comment]
This is from the nightly build. Still not working.

http://pastebin.com/ZXuGKyhZ

This is starting to agitate me a little more than anticipated. I will figure out why it's doing this. The .sm that comes with this file strangely displayed this "security" problem with the file. Even after recaching and "unblocking" the sm file, it's still causing this.

"Security problem"
http://puu.sh/jR2Pt/894310c51c.png

Next crash
http://pastebin.com/LbBdXaZp

I really need to stop reloading the 17k song SM when testing this, lol.

**Comment by kyzentun** [comment]
Check how much memory stepmania is using when you run it.  Then try starting up with fewer songs and see if it still crashes.  There's a pretty fair chance you're hitting the memory limit for 32-bit programs.

**Comment by freem** [comment]
oddly enough, each crash log has Steps::GetMusicPath as the last function called. Not fully sure if this is the cause of the issue, but maybe see if the simfile is pointing to an invalid music file?

**Comment by kyzentun** [comment]
In the copy I got from ppp, all the fields point to the right files.  So I don't think that's the problem.

**Comment by kyzentun** [comment]
Run this build, get the crash, upload Logs/log.txt for us to look at.
https://mega.nz/#!4B80gIJI!b-8QlKAjsuhBCB5wgdsOUjcOkNI4ImQnASNkMBNlKVU

**Comment by wolfman2000** [comment]
If @kyzentun's link does not work, I have a backup.
https://mega.nz/#!8Y0h0SLb!FV8aEueZy4fVSoner7DnDwSuhiXOKVYm087cJQwJj6g

**Comment by kyzentun** [comment]
This version does not crash for the other person that had a similar problem.
https://mega.nz/#!8NdEhRoZ!ruMzzjcT8-2dEw0uWzh8DSX-7WgYHKU8ouQ3UT_fbOs

So I think this commit fixes it: https://github.com/stepmania/stepmania/commit/06c63364b1de1086e629ed1f9be5ba8a8a61e8e2

**Comment by DXUltimate** [comment]
Sorry that I have been away the last few days.

After extraction of the files from the first build that kyzentun provided, it says it was missing msvcp120d.dll.

wolfman2000's build he provided. I did install to a completely separate directory as well and ensured that only the pump pro 1, and 2 songs were loading off of this; 
http://pastebin.com/JsmN5CqY

Completely reinstalled with kyzentun's version he also provided, and it worked!
http://puu.sh/jVsNY/5ddcb7915f.jpg
