### ISSUE TITLE
Autogen ./Configure vs Cmake

### ISSUE THREAD

**Issue by latot** [stepmania/stepmania#756]
Hi ppl, whell this issue es because actually SM have 2 ways to be compiled, via ./configure and cmake basically, teorically they don't most have differences in the compilation (a working compilation) but here are difference, actually compile via ./configure is causing errors,bugs and compatibilities problems, example, only can be compiled with ffmpeg 55 (you can compile but sm don't run)

And this doesn't happend with cmake, i know its posible fix it but i think It is an unnecessary effort, so if its posible disable the compilation via ./configure and autogen. what do you think?

Thx.

**Comment by wolfman2000** [comment]
When cmake starts working on MinGW, then we can formally remove autogen.

**Comment by latot** [comment]
okis Thx :D

**Comment by latot** [comment]
A little thing, can be good idea retest the actually bugs compiling with cmake...

**Comment by latot** [comment]
well, i prefer close the issue, anyway this will be done with this pull request

https://github.com/stepmania/stepmania/pull/758

**Comment by latot** [comment]
well, i prefer
