### ISSUE TITLE
Cmake missed option extdatadir

### ISSUE THREAD

**Issue by latot** [stepmania/stepmania#757]
Hi, first may be this is because i don't find the option but anyway, i can't found the equivalent of --with-extdatadir in the cmake options.

Thx.

**Comment by wolfman2000** [comment]
...and this is partly why I haven't flat out removed the autogen stuff yet. Figures that I missed something.

What did --with-extdatadir do previously?

**Comment by latot** [comment]
enable the files in the ~/.stepmania-5.0 when we install the SM

**Comment by kyzentun** [comment]
The files in ~/.stepmania-5.0 work just fine when building with cmake already.  They always have.

**Comment by wolfman2000** [comment]
...okay, that answer seems off. May be my lack of translating. I'll take a guess.

By default: the data files are placed in `~/.stepmania-5.0`. When passing in `--with-extdatadir`, you can change it to, say, `~/latotmania`.

How close am I?

**Comment by latot** [comment]
sorry my ugly english, be default sm use the executable dir for search the files, for use the ~/.stepmania-5.0 we pass the --with-extdatadir.

**Comment by latot** [comment]
mm, this is weird, when i run sm from the working directory works the user folder (~/.stepmania) but when i install it don't works ...

**Comment by kyzentun** [comment]
Update and try again.  Wallacoloo fixed a problem that occured when running SM from the install folder.  The fix was committed yesterday.

**Comment by latot** [comment]
Okis, well, are a little deference between the extdatadir in autogen and cmake, in cmake only recognize the user dir but dont the systems dir, for example, i'm using this config:

user data: ~/.stepmania-5.0
binary: /usr/games/bin/stepmania
data game: /usr/share/games/stepmania

for some reason dont recognize this dirs, it works with autogen.

Thx.

**Comment by kyzentun** [comment]
Is the binary that is in /usr/games/bin/stepmania a symlink?  If it's a symlink to the real binary in /usr/share/games/stepmania/stepmania, then Wallacoloo's fix should solve your problem.

**Comment by latot** [comment]
its the original binary, not a symlink

**Comment by latot** [comment]
sadly the pull request don't fix this issue D:

**Comment by latot** [comment]
Hi, well i was looking the info of extdatadir but it was weird because i can't found any data of the option,  and checking the version of stepmania, the overlay in gentoo have a patch for enable the option:

https://github.com/Gentoo-zh/gentoo-zh/blob/master/games-arcade/stepmania/files/01_all_extdatadir.patch

Sorry for the inconveniences. D:
