### ISSUE TITLE
Allow pausing in the default theme

### ISSUE THREAD

**Issue by shakesoda** [stepmania/stepmania#764]
The engine supports it, we should use it (for home mode).

I may have broken the gameplay timer when paused a couple years ago, so if trouble arises my crimes can be found [here](https://github.com/stepmania/stepmania/blob/master/src/GameState.cpp#L1250-L1256)

**Comment by kyzentun** [comment]
The mechanism is fixed as of now.  https://github.com/stepmania/stepmania/commit/f182a04780647a89b7ef7d29c31ec6706d76063e
But, Start, Select, and Back are all used for different forms of giving up, so there's nothing to map it to without breaking one or more of the related metrics or making a better system.

**Comment by monokles** [comment]
The [spawncamping-wallhack](https://github.com/ca25nada/spawncamping-wallhack) theme allows pausing by quickly tapping select twice. IMHO that's a very acceptable solution as introducing new buttons is not very convenient for people with home built arcade cabs etc. Might be an idea for the default theme too.

**Comment by kyzentun** [comment]
#980 will provide pausing.
