### ISSUE TITLE
Game crashes when advanced input options selected

### ISSUE THREAD

**Issue by moosecalibur** [stepmania/stepmania#767]
StepMania5.0.9 crash report (build 0, 20150620 @ 17:37:55)
--------------------------------------

Architecture:   Mac OS X (i386)
Crash reason:   AxisFix
Crashed thread: Main thread

Checkpoints:
Thread: GUI thread
Thread: Main thread
        FontManager.cpp:64 FontManager::UnloadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        FontManager.cpp:64 FontManager::UnloadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        FontManager.cpp:64 FontManager::UnloadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        FontManager.cpp:64 FontManager::UnloadFont(/Themes/_fallback/Fonts/_open sans semibold 24px.ini).
        ScreenOptionsMasterPrefs.cpp:137 AxisFix
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
        RageSoundDriver_Generic_Software.cpp:204 Processing the sound while buffers are available.
Thread: Music thread
Thread: HAL I/O thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: Input thread

Thread: 
0067919c: CrashHandler::ForceCrash(char const*) 
0067f05d: sm_crash(char const*) 
0052a134: void MovePref<bool>(int&, bool, ConfOption const*) 
002b6943: OptionRowHandlerConfig::ImportOption(OptionRow*, std::vector<PlayerNumber, std::allocator<PlayerNumber> > const&, std::vector<bool, std::allocator<bool> >*) const 
002aaa10: OptionRow::ImportOptions(std::vector<PlayerNumber, std::allocator<PlayerNumber> > const&) 
0051c677: ScreenOptionsMaster::ImportOptions(int, std::vector<PlayerNumber, std::allocator<PlayerNumber> > const&) 
004fc7c2: ScreenOptions::BeginScreen() 
004cc2d2: ScreenManagerUtil::GetPreppedScreen(StdString::CStdStr<char> const&, ScreenManagerUtil::LoadedScreen&) 
004cf70e: ScreenManager::ActivatePreparedScreenAndBackground(StdString::CStdStr<char> const&) 
004cf7d2: ScreenManager::ActivatePreparedScreenAndBackground(StdString::CStdStr<char> const&) 
004ced68: ScreenManager::LoadDelayedScreen() 
004ce897: ScreenManager::Update(float) 
00127598: GameLoop::RunGameLoop() 
005eb9d6: sm_main 
00676afb: -[SMMain startGame:] 

Static log:
StepMania5.0.9
Compiled 20150620 @ 17:37:55 (build 0)
Log starting 2015-09-06 15:22:53
Loading window: macosx
Model: MacBookPro6,2 (4/4)
Clock speed 2.66 GHz
Mac OS X 10.10.5
Memory: 4.00 GB
WARNING: ReadFile(Save/ThemePrefs.ini): No such file or directory
Sound driver: AudioUnit
Lights driver: SystemMessage
Video renderers: 'opengl'
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: NVIDIA Corporation
OGL Renderer: NVIDIA GeForce GT 330M OpenGL Engine
OGL Version: 2.1 NVIDIA-10.0.35 310.90.10.05b12
OGL Max texture size: 8192
OGL Texture units: 8
GLU Version: 1.3 MacOSX
OGL Extensions:
  GL_APPLE: aux_depth_stencil, client_storage, element_array, fence, float_pixels, flush_buffer_range, 
    flush_render, object_purgeable, packed_pixels, pixel_buffer, rgb_422, row_bytes, specular_vector, 
    texture_range, transform_hint, vertex_array_object, vertex_array_range, vertex_point_size, 
    vertex_program_evaluators, ycbcr_422
  GL_ARB: color_buffer_float, depth_buffer_float, depth_clamp, depth_texture, draw_buffers, 
    draw_elements_base_vertex, draw_instanced, fragment_program, fragment_program_shadow, fragment_shader, 
    framebuffer_object, framebuffer_sRGB, half_float_pixel, half_float_vertex, imaging, instanced_arrays, 
    multisample, multitexture, occlusion_query, pixel_buffer_object, point_parameters, point_sprite, 
    provoking_vertex, seamless_cube_map, shader_objects, shader_texture_lod, shading_language_100, shadow, sync, 
    texture_border_clamp, texture_compression, texture_compression_rgtc, texture_cube_map, texture_env_add, 
    texture_env_combine, texture_env_crossbar, texture_env_dot3, texture_float, texture_mirrored_repeat, 
    texture_non_power_of_two, texture_rectangle, texture_rg, transpose_matrix, vertex_array_bgra, vertex_blend, 
    vertex_buffer_object, vertex_program, vertex_shader, window_pos
  GL_ATI: separate_stencil, texture_env_combine3, texture_float, texture_mirror_once
  GL_EXT: abgr, bgra, bindable_uniform, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, 
    blend_subtract, clip_volume_hint, compiled_vertex_array, debug_label, debug_marker, depth_bounds_test, 
    draw_buffers2, draw_range_elements, fog_coord, framebuffer_blit, framebuffer_multisample, 
    framebuffer_multisample_blit_scaled, framebuffer_object, framebuffer_sRGB, geometry_shader4, 
    gpu_program_parameters, gpu_shader4, multi_draw_arrays, packed_depth_stencil, packed_float, provoking_vertex, 
    rescale_normal, secondary_color, separate_specular_color, shadow_funcs, stencil_two_side, stencil_wrap, 
    texture_array, texture_compression_dxt1, texture_compression_s3tc, texture_env_add, 
    texture_filter_anisotropic, texture_integer, texture_lod_bias, texture_mirror_clamp, texture_rectangle, 
    texture_sRGB, texture_sRGB_decode, texture_shared_exponent, timer_query, transform_feedback, 
    vertex_array_bgra
  GL_IBM_rasterpos_clip
  GL_NV: blend_square, conditional_render, depth_clamp, fog_distance, fragment_program2, fragment_program_option, 
    light_max_exponent, multisample_filter_hint, point_sprite, texgen_reflection, texture_barrier, 
    vertex_program2_option, vertex_program3
  GL_SGIS: generate_mipmap, texture_edge_clamp, texture_lod
OpenGL Windowed 854x480 32 color 16 texture 60Hz Vsync SmoothLines
WARNING: Failed to add HID element with cookie 0x2 to queue: 3758097090
WARNING: Failed to add HID element with cookie 0x5 to queue: 3758097090
WARNING: Couldn't initialize device.
WARNING: Couldn't initialize device.
Disconnected: Twin USB Joystick
Twin USB Joystick
Auto-mapping all joysticks.
Players joined: P1, P2
Top Screen: ScreenOptionsInput
Language: en
Current renderer: OpenGL
Theme: default

Partial log:
01:16.509:    8x  8 (36)                             OptionsUnderlineP1 Middle (doubleres).png
01:16.509:    8x  8 (36)                             OptionsUnderlineP1 Right (doubleres).png
01:16.509:  512x1024 ( 1)                            ScreenOptions page.png
01:16.509:   64x1024 ( 2)                            Header.png
01:16.509:    8x  8 ( 1)                             _texture stripe (stretch).png
01:16.509:    1x  1 (12)                             __blank__
01:16.509: total 18712385 texels
01:16.509: PushScreen: "ScreenOptionsInput"
01:16.510: RageSound: Load "/Themes/_fallback/Sounds/_missing.ogg" (precache: 0)
01:16.510: Sound "/Themes/_fallback/Sounds/_missing.ogg" has a start time 0.000008 seconds in the past

-- End of report

**Comment by kyzentun** [comment]
AxisFix preference didn't exist on OS X, which caused the crash.  The crash is fixed as of https://github.com/stepmania/stepmania/commit/e1eceda03152777252561551454853e1c7e03cfe but the AxisFix preference does nothing on OS X.
