### ISSUE TITLE
Def.ActorSound

### ISSUE THREAD

**Issue by Jousway** [stepmania/stepmania#781]
"Oddly, you can’t currently use ActorSounds via Def.ActorSound{} like every other actor (ActorSound isn’t a registered Actor class). This is likely a bug that will be fixed in the future."

http://dguzek.github.io/Lua-For-SM5/Actors/ActorSound.html

**Comment by sigatrev** [comment]
The syntax is "Def.Sound{}", not "Def.ActorSound{}". Perhaps someone could add an alias "function Def.ActorSound(t) return Def.Sound(t) end"

**Comment by Jousway** [comment]
then why is it documented as actorsound?

https://github.com/stepmania/stepmania/blob/master/Docs/Themerdocs/actordef.txt

**Comment by sigatrev** [comment]
Because of Kyzentun: https://github.com/stepmania/stepmania/commit/9244b0f1d8287967c6a4620f6e044d7aab372c2f

"Sound" is and has been on that list from the beginning. Also this: https://github.com/stepmania/stepmania/blob/master/src/ActorSound.cpp#L8

**Comment by kyzentun** [comment]
I was young and foolish, editing the file by hand instead of writing some code to generate it.

**Comment by Jousway** [comment]
it has been for years in the lua.xml as actorsound tough https://github.com/stepmania/stepmania/blob/master/Docs/Luadoc/Lua.xml#L579 thats the main reason why I tought it was actorsound

**Comment by sigatrev** [comment]
That is because the Lua class is named "ActorSound". https://github.com/stepmania/stepmania/blob/master/src/ActorSound.cpp#L77

**Comment by Jousway** [comment]
why is it so confusing hurrrr

**Comment by dguzek** [comment]
StepMania is confusing and messy?  Woah.

Anyway, thanks for the clarification, @sigatrev.  I'll update my Lua guide later (or, when this conversation finds some resolution).
