### ISSUE TITLE
Rolls not breaking the combo

### ISSUE THREAD

**Issue by Arvaneth** [stepmania/stepmania#793]
Rolls not breaking the combo when failing to keep rolling.

![rollissue](https://cloud.githubusercontent.com/assets/9543478/9999858/ad563bc2-6066-11e5-8f0c-db8517f9b09f.jpg)

**Comment by kyzentun** [comment]
This is controlled by a metric in the theme.
If the ComboBreakOnImmediateHoldLetGo metric in the Player section of metrics.ini is set to false, then dropping holds and rolls does not break combo.  If that metric is set to true, then dropping a hold or roll breaks the combo.

As a side note, the RollBodyIncrementsCombo metric controls whether keeping a roll alive increases the combo.

**Comment by shakesoda** [comment]
Working as intended.
