### ISSUE TITLE
Possibly unfixable - pad which isn't Red Octane registers as Red Octane

### ISSUE THREAD

**Issue by AngledLuffa** [stepmania/stepmania#811]
This pad

http://www.ddrgame.com/dance-dance-revolution-energy-premium-deluxe.html

This occurs on Windows.  I don't know anything about how StepMania recognizes the devices, so it could be that Windows reports it as a Red Octane pad and the problem is completely unfixable.  If there's some way to distinguish them, though, that would be great.  The DDRGame pad doesn't use the same inputs as the Red Octane, so the buttons need to be remapped each time.

I have both a Red Octane and a DDRGame pad, so I can possibly help debug this issue if someone gives me pointers to the appropriate code path.

**Comment by kyzentun** [comment]
Turn off the Automap Joysticks option so you don't have to remap every time.  I'm pretty sure it's a case of DDR Game using Red Octane as their control box supplier.  Cobalt Flux also used Red Octane control boxes for a while too.

**Comment by shakesoda** [comment]
Almost everyone uses the same control box, there's no way to identify the pad beyond that.

The hardware itself is flawed in this way, so the only thing you can do is turn off auto mapping.

**Comment by AngledLuffa** [comment]
Got it, not a software bug.  A hardware issue where there's no way to identify the actual pad aside from the control box.

Thanks anyway!
