### ISSUE TITLE
[Network Options] "Always Online" demanded.

### ISSUE THREAD

**Issue by Prcuvu** [stepmania/stepmania#871]
Feedback from my local community.

Some players always play online, and it is annoying always having to connect to server in Network Options before starting a game. Since the server name is stored, they demand an "Always Online" switch (in Network Options) that enables an online mode, in which the game connects to the current server and prompts username and password on program startup, thus saving their time and efforts. When the switch is turned off, the game is changed back to offline mode.

I hope that this can be implemented in 5.1.0.

**Comment by shakesoda** [comment]
We should probably just bring back a "Play Online" option in the menu (4 CVS had it there back in the day). Worth mentioning that this can be done by absolutely any theme very easily or you can set the initial screen to ScreenNetworkOptions

**Comment by concubidated** [comment]
As Shakesoda mentioned this can already be done. Here is a guide to set it up on every OS.

http://stepmaniaonline.net/forum/viewtopic.php?f=8&t=2472
