### ISSUE TITLE
[Linux] Related CMake flags problems

### ISSUE THREAD

**Issue by latot** [stepmania/stepmania#890]
Hi i take a little time listing and searching problems with combinations of cmake flags, here:

WITH_TTY=ON
issue: https://github.com/stepmania/stepmania/issues/689
can't compile, i try search the package sdl_utils but i can't found any official with that name, and neither packets containing the file snd_utils.h

WITH_VERSION_INFO=OFF
can't compile

Log:

/home/pipe/Documentos/git/stepmania/src/NetworkSyncManager.cpp: In member function ‘void NetworkSyncManager::PostStartUp(const RString&)’:
/home/pipe/Documentos/git/stepmania/src/NetworkSyncManager.cpp:165:54: error: ‘product_version’ was not declared in this scope
  m_packet.WriteNT( RString( string(PRODUCT_FAMILY) + product_version ) );

/home/pipe/Documentos/git/stepmania/src/StepMania.cpp: In function ‘void WriteLogHeader()’:
/home/pipe/Documentos/git/stepmania/src/StepMania.cpp:924:36: error: ‘product_version’ was not declared in this scope
  LOG->Info("%s%s", PRODUCT_FAMILY, product_version);

WITH_MP3=OFF && WITH_WAV=OFF
can't compile

Log:

/home/pipe/Documentos/git/stepmania/src/RageSoundReader_FileReader.cpp: In static member function ‘static RageSoundReader_FileReader* RageSoundReader_FileReader::OpenFile(RString, RString&, bool*)’:
/home/pipe/Documentos/git/stepmania/src/RageSoundReader_FileReader.cpp:95:3: error: ‘RageFile’ was not declared in this scope
   RageFile *pFileOpen = new RageFile;
   ^
/home/pipe/Documentos/git/stepmania/src/RageSoundReader_FileReader.cpp:95:13: error: ‘pFileOpen’ was not declared in this scope
   RageFile *pFileOpen = new RageFile;
             ^
/home/pipe/Documentos/git/stepmania/src/RageSoundReader_FileReader.cpp:95:29: error: ‘RageFile’ does not name a type
   RageFile *pFileOpen = new RageFile;
                             ^
/home/pipe/Documentos/git/stepmania/src/RageSoundReader_FileReader.cpp:99:11: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
    delete pFileOpen;

Thx.

**Comment by wolfman2000** [comment]
Let's go through one at a time.

`WITH_TTY`: I don't remember the last time we ever used SDL. We have discussed bringing back SDL for future major revisions, however. I may have to disable that one.

`WITH_FFMPEG` and `WITH_SYSTEM_FFMPEG`: As intended. If `WITH_FFMPEG` is off, that overrules `WITH_SYSTEM_FFMPEG`.

`WITH_VERSION_INFO`: to be removed. Version Info should always be included.

`WITH_MP3` and `WITH_WAV`: that sounds like a genuine bug. I will investigate.

**Comment by latot** [comment]
O_o are you right, i don't see it, wel its a little confusing this, because we don't have to know how sm choose the ffmpeg (bundled system) at least we start checking the code, its posible edit the description of the WITH_SYSTEM_FFMPEG, actually say this:

Build with the system's FFMPEG.
to
Build with the system's FFMPEG, disabled build with bundled's FFMPEG 

i'll remove the ffmpeg part of the issua because don't have any sense now.

**Comment by latot** [comment]
well, all the parts are solved, closing. thx all
