### ISSUE TITLE
How SM 5.1 set ffmpeg version?

### ISSUE THREAD

**Issue by latot** [stepmania/stepmania#892]
Hi, this is a little question, i can't find how sm 5.1 set ffmpeg to 2.1.3, in the .gitmodules say this:

[submodule "extern/ffmpeg-git"]
path = extern/ffmpeg-git
url = git://source.ffmpeg.org/ffmpeg.git

don't specify any tag or branch, but when we update the submodules say this:

Submodule path 'extern/ffmpeg-git': checked out 'eda6effcabcf9c238e4635eb058d72371336e09b'

basically the 2.1.3 tag, i try changing the ffmpeg version in setupffmpeg but no luky the extern/ffmpeg-git continues with 2.1.3.

**Comment by wolfman2000** [comment]
To change the version in 5.1, go into the ffmpeg repository and check out a branch or commit.

The change can then be committed for others to update on their end.

As a basic example, ffmpeg 2.8 can be used by going into `extern/ffmpeg` and going `git checkout n2.8` if I remember right.

Does that help?

**Comment by latot** [comment]
mm, with that we can change the version.. i'm still confusing, because if we change it, and then we push the changes, when we run 'git submodule update' it back to n2.1.3.

or in other way, if we remove extern/ffmpeg-git, when we run 'git submodule update --init' where git get the info to checkout to the n2.1.3??

**Comment by latot** [comment]
closing, to much time.
