### ISSUE TITLE
Crash when opening Advanced Input Options menu

### ISSUE THREAD

**Issue by jboning** [stepmania/stepmania#904]
5.0.9, StepMania 5.0.9. I seem to be able to reproduce consistently.

crashinfo.txt: https://gist.github.com/jboning/4db8b8aaf62131b4c0a6

**Comment by jboning** [comment]
Looks like a dupe of #767. I only searched for open issues, oops.

**Comment by kyzentun** [comment]
lol, I had just barely copied the link to the commit that fixed it, and was about to post.

**Comment by jboning** [comment]
Sorry for the noise.

Though I guess now's a good time to ask when you'll push a release with the fix ;-)

**Comment by kyzentun** [comment]
Halloween, so this weekend.  Until then, you could edit your metrics to remove the conf line for the AxisFix preference from that screen.

**Comment by Prcuvu** [comment]
@kyzentun Hopefully the new Windows release is built with /MT flag.

**Comment by wolfman2000** [comment]
@Prcuvu I'm not seeing the relation to `/MT` and this issue.

**Comment by jboning** [comment]
Workaround worked like a charm, thanks!
