### ISSUE TITLE
What is going to be done with smpackage?

### ISSUE THREAD

**Issue by Prcuvu** [stepmania/stepmania#925]
`smpackage` is the only part that is left out since 5.0 release. Is it going to be reutilized (cross-platform, for instance) or removed from the codebase?

**Comment by wolfman2000** [comment]
Fair question. I want it to be a cross platform application, but MFC does not exactly cater well for it. I'd have to look into something like [wxWidgets](https://www.wxwidgets.org/) most likely (I already checked the licensing terms: they will work for us to my knowledge). The tricky part...is that I'd want to use submodules no matter which GUI library is used.

The smpackage tool may have to just be redone in the `5_1_0` branch for the time being.

**Comment by shakesoda** [comment]
it's going to be rewritten or something.

@wolfman2000 submodules only go so far, and having heavy dependence on external servers is extremely bad (they are liable to go away, and repos like this are around for numerous years)
