### ISSUE TITLE
Just to let y'all know

### ISSUE THREAD

**Issue by electromuis** [stepmania/stepmania#927]
When i exited from edit mode (after playing with some attacks)

StepMania5.0.6 crash report (build 9, 20150217 @ 11:50:31 Central Standard Time)
--------------------------------------

Crash reason: Access Violation

Thread: Main thread
        RageFileDriverDirectHelpers.cpp:227 C:/Games/StepMania 5.0/Songs/*
        RageFileDriverDirectHelpers.cpp:227 C:/Games/StepMania 5.0/Songs/Fietsemaker Dump 1/*
        RageFileDriverDirectHelpers.cpp:227 C:/Games/StepMania 5.0/Songs/*
        RageFileDriverDirectHelpers.cpp:227 C:/Games/StepMania 5.0/Songs/Fietsemaker Dump 1/Love is War/*
        RageFileDriverDirectHelpers.cpp:227 C:/Games/StepMania 5.0/Songs/Fietsemaker Dump 1/*
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
Thread: Mixer thread
Thread: Music thread
        RageFileDriverDirectHelpers.cpp:227 C:/Games/StepMania 5.0/Themes/_fallback/Sounds/*
        RageFileDriverDirectHelpers.cpp:227 C:/Games/StepMania 5.0/Themes/_fallback/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Electromuis/AppData/Roaming/StepMania 5/Themes/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Electromuis/AppData/Roaming/StepMania 5/Themes/_fallback/Sounds/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Electromuis/AppData/Roaming/StepMania 5/Themes/_fallback/*
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
        InputHandler_DirectInput.cpp:750 
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
Thread: Streaming sound buffering

0054c96a: void TimingData::GetBeatAndBPSFromElapsedTimeNoOffset(float,float &,float &,bool &,bool &,int &,float &)const  [00400000+14c8c0+aa]
0054d97a: void TimingData::GetBeatAndBPSFromElapsedTime(float,float &,float &,bool &,bool &,int &,float &)const  [00400000+14d930+4a]
006502df: void Player::UpdateJudgedRows(void) [00400000+250290+4f]
778fe013: ntdll!RtlFreeHeap [778d0000+2df95+7e]
76d514bd: kernel32!HeapFree [76d40000+114a9+14]
71513c1b: MSVCR90!free [714b0000+63b4e+cd]
71513c3a: MSVCR90!free [714b0000+63b4e+ec]
778fe013: ntdll!RtlFreeHeap [778d0000+2df95+7e]
76d514bd: kernel32!HeapFree [76d40000+114a9+14]
006f723e: bool GameState::IsHumanPlayer(enum PlayerNumber)const  [00400000+2f7150+ee]
0065203f: void Player::Update(float) [00400000+251340+cff]
00652046: void Player::Update(float) [00400000+251340+d06]
006b7299: void Actor::UpdateInternal(float) [00400000+2b6de0+4b9]
006c1f5c: void ActorFrame::UpdateInternal(float) [00400000+2c1ea0+bc]
00636c37: void NoteDisplay::Update(float) [00400000+236bd0+67]
004205b9: void std::vector<class StdString::CStdStr<char>,class std::allocator<class StdString::CStdStr<char> > >::_Insert_n(class std::_Vector_const_iterator<class StdString::CStdStr<char>,class std::allocator<class StdString::CStdStr<char> > >,unsigned int,class StdString::CStdStr<char> const &) [00400000+20480+139]
006b7299: void Actor::UpdateInternal(float) [00400000+2b6de0+4b9]
6e4e4f2a: MSVCP90!std::char_traits<char>::_Copy_s [6e4e0000+4f13+17]
6e4e59d5: MSVCP90!std::allocator<char>::allocate [6e4e0000+5929+ac]
00402daa: void Screen::Update(float) [00400000+2d90+1a]
6e4e73c3: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign [6e4e0000+73b2+11]
00507eed: void PlayerOptions::Approach(class PlayerOptions const &,float) [00400000+1079c0+52d]
0051710b: void PlayerState::Update(float) [00400000+116f00+20b]
0044fb9d: void ScreenWithMenuElements::Update(float) [00400000+4fb90+d]
004a6d0f: void ScreenEdit::Update(float) [00400000+a6610+6ff]
778fe013: ntdll!RtlFreeHeap [778d0000+2df95+7e]
76d514bd: kernel32!HeapFree [76d40000+114a9+14]
71513c1b: MSVCR90!free [714b0000+63b4e+cd]
71513c3a: MSVCR90!free [714b0000+63b4e+ec]
71513c3a: MSVCR90!free [714b0000+63b4e+ec]
6e4e5e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [6e4e0000+5dfb+48]
6e4e5ec4: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > [6e4e0000+5ebb+9]
006802b2: void RageLog::Trace(char const *,...) [00400000+280280+32]
71513c3a: MSVCR90!free [714b0000+63b4e+ec]
6e4e5e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [6e4e0000+5dfb+48]
00736b44: void ScreenManager::Update(float) [00400000+3369b0+194]
006f6110: void GameState::Update(float) [00400000+2f60a0+70]
006a2da2: void RageTextureManager::Update(float) [00400000+2a2d40+62]
005b51b0: void GameLoop::RunGameLoop(void) [00400000+1b5090+120]
6e4e5e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [6e4e0000+5dfb+48]
6e4e5ec4: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > [6e4e0000+5ebb+9]
005b9966: main() [00400000+1b8aa0+ec6]
714d36c5: MSVCR90!_set_flsgetvalue [714b0000+236b6+f]
714d38b3: MSVCR90!initptd [714b0000+23753+160]
005d4df4: int GetWin32CmdLine(char * * &) [00400000+1d4d40+b4]
005d4b75: WinMain@16() [00400000+1d4b60+15]
007d822f: __tmainCRTStartup() [00400000+3d80ef+140]
77909855: ntdll!RtlInitializeExceptionChain [778d0000+3981f+36]

Static log:
StepMania5.0.6
Compiled 20150217 @ 11:50:31 Central Standard Time (build 9)
Log starting 2015-11-02 16:28:32
Loading window: win32
Windows 6.1 (Win7) build 7601 [Service Pack 1]
Memory: 4095mb total, 4095mb swap (4095mb swap avail)
Video driver: NVIDIA GeForce GTX 660 [NVIDIA]
              9.18.13.4465, 11-3-2014 [pci\ven_10de&dev_11c0]
WARNING: RegOpenKeyEx(80000002,HARDWARE\DEVICEMAP\Scsi) error (The system cannot find the file specified.)
Sound device 0: Speakers (7- USB Audio Device), 0.1, MID 65535, PID 65535 
Sound device 1: Line 2 (Virtual Audio Cable), 6.1, MID 1, PID 100 
Sound device 2: Line 1 (Virtual Audio Cable), 6.1, MID 1, PID 100 
Sound device 3: Line 3 (Virtual Audio Cable), 6.1, MID 1, PID 100 
DirectSound Driver: Primary Sound Driver
DirectSound Driver: Speakers (7- USB Audio Device) {0.0.0.00000000}.{2ef37c8e-7c44-44ad-9856-7c8b8fc73198}
DirectSound Driver: Line 2 (Virtual Audio Cable) {0.0.0.00000000}.{54951d34-7a94-40dc-a762-09a83f0bcc7a}
DirectSound Driver: Line 1 (Virtual Audio Cable) {0.0.0.00000000}.{5f488dd2-17ea-4cda-a922-d5eed6ed2743}
DirectSound Driver: Line 3 (Virtual Audio Cable) {0.0.0.00000000}.{c0b7379f-baed-46f7-9092-480babd7f1d9}
DirectSound sample rates: 100..200000 (continuous)
Software mixing at 44100 hz
Sound driver: DirectSound-sw
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'opengl,d3d'
Mode: ICD 32 (888) 24 depth 64 accum 
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: NVIDIA Corporation
OGL Renderer: GeForce GTX 660/PCIe/SSE2
OGL Version: 4.4.0 NVIDIA 344.65
OGL Max texture size: 16384
OGL Texture units: 4
GLU Version: 1.2.2.0 Microsoft Corporation
OGL Extensions:
  GL_AMD: multi_draw_indirect, seamless_cubemap_per_texture
  GL_ARB: ES2_compatibility, ES3_1_compatibility, ES3_compatibility, arrays_of_arrays, base_instance, 
    bindless_texture, blend_func_extended, buffer_storage, clear_buffer_object, clear_texture, color_buffer_float, 
    compatibility, compressed_texture_pixel_storage, compute_shader, compute_variable_group_size, 
    conservative_depth, copy_buffer, copy_image, debug_output, depth_buffer_float, depth_clamp, depth_texture, 
    draw_buffers, draw_buffers_blend, draw_elements_base_vertex, draw_indirect, draw_instanced, enhanced_layouts, 
    explicit_attrib_location, explicit_uniform_location, fragment_coord_conventions, fragment_layer_viewport, 
    fragment_program, fragment_program_shadow, fragment_shader, framebuffer_no_attachments, framebuffer_object, 
    framebuffer_sRGB, geometry_shader4, get_program_binary, gpu_shader5, gpu_shader_fp64, half_float_pixel, 
    half_float_vertex, imaging, indirect_parameters, instanced_arrays, internalformat_query, 
    internalformat_query2, invalidate_subdata, map_buffer_alignment, map_buffer_range, multi_bind, 
    multi_draw_indirect, multisample, multitexture, occlusion_query, occlusion_query2, pixel_buffer_object, 
    point_parameters, point_sprite, program_interface_query, provoking_vertex, query_buffer_object, 
    robust_buffer_access_behavior, robustness, sample_shading, sampler_objects, seamless_cube_map, 
    seamless_cubemap_per_texture, separate_shader_objects, shader_atomic_counters, shader_bit_encoding, 
    shader_draw_parameters, shader_group_vote, shader_image_load_store, shader_image_size, shader_objects, 
    shader_precision, shader_storage_buffer_object, shader_subroutine, shader_texture_lod, shading_language_100, 
    shading_language_420pack, shading_language_include, shading_language_packing, shadow, sparse_texture, 
    stencil_texturing, sync, tessellation_shader, texture_border_clamp, texture_buffer_object, 
    texture_buffer_object_rgb32, texture_buffer_range, texture_compression, texture_compression_bptc, 
    texture_compression_rgtc, texture_cube_map, texture_cube_map_array, texture_env_add, texture_env_combine, 
    texture_env_crossbar, texture_env_dot3, texture_float, texture_gather, texture_mirror_clamp_to_edge, 
    texture_mirrored_repeat, texture_multisample, texture_non_power_of_two, texture_query_levels, 
    texture_query_lod, texture_rectangle, texture_rg, texture_rgb10_a2ui, texture_stencil8, texture_storage, 
    texture_storage_multisample, texture_swizzle, texture_view, timer_query, transform_feedback2, 
    transform_feedback3, transform_feedback_instanced, transpose_matrix, uniform_buffer_object, vertex_array_bgra, 
    vertex_array_object, vertex_attrib_64bit, vertex_attrib_binding, vertex_buffer_object, vertex_program, 
    vertex_shader, vertex_type_10f_11f_11f_rev, vertex_type_2_10_10_10_rev, viewport_array, window_pos
  GL_ATI: draw_buffers, texture_float, texture_mirror_once
  GL_EXTX_framebuffer_mixed_formats
  GL_EXT: Cg_shader, abgr, bgra, bindable_uniform, blend_color, blend_equation_separate, blend_func_separate, 
    blend_minmax, blend_subtract, compiled_vertex_array, depth_bounds_test, direct_state_access, draw_buffers2, 
    draw_instanced, draw_range_elements, fog_coord, framebuffer_blit, framebuffer_multisample, 
    framebuffer_multisample_blit_scaled, framebuffer_object, framebuffer_sRGB, geometry_shader4, 
    gpu_program_parameters, gpu_shader4, import_sync_object, multi_draw_arrays, packed_depth_stencil, 
    packed_float, packed_pixels, pixel_buffer_object, point_parameters, provoking_vertex, rescale_normal, 
    secondary_color, separate_shader_objects, separate_specular_color, shader_image_load_store, 
    shader_integer_mix, shadow_funcs, stencil_two_side, stencil_wrap, texture3D, texture_array, 
    texture_buffer_object, texture_compression_dxt1, texture_compression_latc, texture_compression_rgtc, 
    texture_compression_s3tc, texture_cube_map, texture_edge_clamp, texture_env_add, texture_env_combine, 
    texture_env_dot3, texture_filter_anisotropic, texture_integer, texture_lod, texture_lod_bias, 
    texture_mirror_clamp, texture_object, texture_sRGB, texture_sRGB_decode, texture_shared_exponent, 
    texture_storage, texture_swizzle, timer_query, transform_feedback2, vertex_array, vertex_array_bgra, 
    vertex_attrib_64bit
  GL_IBM: rasterpos_clip, texture_mirrored_repeat
  GL_KHR: blend_equation_advanced, debug
  GL_KTX_buffer_region
  GL_NVX: conditional_render, gpu_memory_info, nvenc_interop
  GL_NV: ES1_1_compatibility, ES3_1_compatibility, bindless_multi_draw_indirect, 
    bindless_multi_draw_indirect_count, bindless_texture, blend_equation_advanced, blend_square, compute_program5, 
    conditional_render, copy_depth_to_color, copy_image, depth_buffer_float, depth_clamp, draw_texture, 
    explicit_multisample, fence, float_buffer, fog_distance, fragment_program, fragment_program2, 
    fragment_program_option, framebuffer_multisample_coverage, geometry_shader4, gpu_program4, gpu_program4_1, 
    gpu_program5, gpu_program5_mem_extended, gpu_program_fp64, gpu_shader5, half_float, light_max_exponent, 
    multisample_coverage, multisample_filter_hint, occlusion_query, packed_depth_stencil, parameter_buffer_object, 
    parameter_buffer_object2, path_rendering, pixel_data_range, point_sprite, primitive_restart, 
    register_combiners, register_combiners2, shader_atomic_counters, shader_atomic_float, shader_buffer_load, 
    shader_storage_buffer_object, shader_thread_group, shader_thread_shuffle, texgen_reflection, texture_barrier, 
    texture_compression_vtc, texture_env_combine4, texture_multisample, texture_rectangle, texture_shader, 
    texture_shader2, texture_shader3, transform_feedback, transform_feedback2, vertex_array_range, 
    vertex_array_range2, vertex_attrib_integer_64bit, vertex_buffer_unified_memory, vertex_program, 
    vertex_program1_1, vertex_program2, vertex_program2_option, vertex_program3
  GL_S3_s3tc
  GL_SGIS: generate_mipmap, texture_lod
  GL_SGIX: depth_texture, shadow
  GL_SUN_slice_accum
  GL_WIN_swap_hint
  WGL_EXT_swap_control
OpenGL Fullscreen 1920x1200 32 color 32 texture 59Hz NoVsync SmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 2 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Mouse' axes: 3, hats: 0, buttons: 5 (buffered)
WARNING: Banner cache for '/Songs/Ace's Picks 1 - Fun Stuff/EasyAsPie2-bn.png' wasn't loaded
WARNING: No options in row "list,Steps" were selected, and no fallback row found; selected entry 0
WARNING: No options in row "list,Steps" were selected, and no fallback row found; selected entry 0
WARNING: No options in row "list,Steps" were selected, and no fallback row found; selected entry 0
WARNING: No options in row "list,Steps" were selected, and no fallback row found; selected entry 0
Mixing underruns: 1
Players joined: P1
Lost focus to: StepMania-SSE2.exe, chrome.exe, dwm.exe
Top Screen: ScreenEdit
Language: en
Current renderer: OpenGL
Theme: default

Partial log:
11:41.085:  128x512 ( 0)                             _rave result P2.png
11:41.085:  128x512 ( 0)                             _rave result draw.png
11:41.085:    1x  1 (77)                             __blank__
11:41.085: total 53906177 texels
11:41.085: PushScreen: "ScreenPrompt"
11:41.086: RageSound: Load "/Themes/_fallback/Sounds/_missing.ogg" (precache: 0)
11:41.086: Zeroing this update.  Was 0.009000
11:42.073: 123 FPS, 123 av FPS, 8856 VPF, OpenGL
11:42.226: Performing texture garbage collection.
11:42.231: Zeroing this update.  Was 0.008000

-- End of report

**Comment by shakesoda** [comment]
5.0.6 is old, upgrade to 5.0.10
