### ISSUE TITLE
SetLife() function

### ISSUE THREAD

**Issue by Puur0** [stepmania/stepmania#962]
This particular function could be used in gimmick simfiles with minigames in them. For example, it could be used in a minigame where the player controls a character and is required to dodge and/or collect objects that fall down from the top edge of the screen. The person who would program such a minigame could use this function in order to punish or reward the players for their actions by manipulating the amount of life they have left.

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/commit/4e0fa012c11ec05d31b886716a0533c0b9f5f7ab
