### ISSUE TITLE
Texture Font Generator crashes on save

### ISSUE THREAD

**Issue by parashep** [stepmania/stepmania#964]
Steps to reproduce:
1. Open Texture Font Generator.exe
2. Change font settings like normal or leave as default, it makes no difference with what I've tried
3. Go to File > Save and choose a name for your texture font in the file saver dialog
4. Crash on save, resulting texture font is broken

This is using the build included in StepMania 5.0.10 on Windows 8.1.

**Comment by wolfman2000** [comment]
Debugging this is strange, and thus I'll need assistance.

The call to Save attempts to write out the first PNG. It passes a setjmp call on the way, and fails on the first attempt to write a row within the for loop. At that point, it somehow jumps _back_ to said setjmp call, where it returns `false` and contains a png PNG error: `internal write transform logic error`. During the attempt to destroy the PNG object, the program has a read access violation.

The PNG version used should not have any effect. Unfortunately, I'm short on time for now and hope that someone else can continue where I left off.

**Comment by wolfman2000** [comment]
Closed by 92724cd.
