### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by GingerAle27** [stepmania/stepmania#968]
The folder "Songs/Ouran High School Host Club OP" appears to be a song folder. All song folders must reside in a group folder. For example, "Songs/Originals/My Song" will contain the music file (MP3, OGG...), the steps file (.sm, .dwi, .ksf...) and other related files.
Everytime I start stepmania I get this error. How do I fix it?

**Comment by kyzentun** [comment]
Make a group folder to put the song folder in.  The error message is trying to give you an example of how song folders need to be organized.

**Comment by GingerAle27** [comment]
I still don't know what i'm doing wrong. https://gyazo.com/2123ef3ece78a4cca9cc4f760299fd6f

**Comment by GingerAle27** [comment]
I created a "group folder" to put the song folder in. When I restarted it, it created another song folder and gave me the same error. https://gyazo.com/0bd4351a55c776ee12bef50ee293f592

**Comment by SpoOkyMagician** [comment]
Lemme give you an example...

Songs/Pack_Name/Song_1/<Files>
Songs/Pack_Name/Song_2/<Files>
Songs/Pack_Name/Song_3/<Files>

**Comment by dguzek** [comment]
Here's a more visual example of how it should be nested:
http://www.personal.psu.edu/djg270/sites/sm5/?open=0-10-1-0

**Comment by GingerAle27** [comment]
I have no idea what or where Songs/Ouran High School Host Club Op is located at.

**Comment by GingerAle27** [comment]
I finally fixed the problem, I found the song file and put it in the right place.

**Comment by GingerAle27** [comment]
Thank all of you for the help
and Merry Christmas.
