### ISSUE TITLE
Erorr cuando inicia el programa

### ISSUE THREAD

**Issue by Joseph92** [stepmania/stepmania#970]
StepMania v5.0 beta 3 crash report (build 7, 20151224 @ 08:41:45 Hora estándar de Argentina)
--------------------------------------

Crash reason: Crash!

Thread: Main thread
        RageFileDriverDirectHelpers.cpp:227 C:/Pump it up/STEP_F2_V1_04 (Steppack 1.50)/Themes/Fiesta 2/BGAnimations/ScreenSelectMusic decorations/_stages/*
        RageFileDriverDirectHelpers.cpp:227 C:/Pump it up/STEP_F2_V1_04 (Steppack 1.50)/Themes/Fiesta 2/BGAnimations/ScreenSelectMusic decorations/_preview/*
        RageFileDriverDirectHelpers.cpp:227 C:/Pump it up/STEP_F2_V1_04 (Steppack 1.50)/Themes/Fiesta 2/BGAnimations/ScreenSelectMusic decorations/_groupwheel/*
        RageFileDriverDirectHelpers.cpp:227 C:/Pump it up/STEP_F2_V1_04 (Steppack 1.50)/Themes/Fiesta 2/Graphics/OptionList/*
        StepMania.cpp:1278 Crash!
Thread: Decode thread
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
        InputHandler_DirectInput.cpp:750 
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 

00525af2: long MainExceptionHandler(struct _EXCEPTION_POINTERS *) [00400000+125aed+5]
0050e076: void sm_crash(char const *) [00400000+10e05b+1b]
005113cc: main() [00400000+110a9a+932]
77412c0e: ntdll!RtlAllocateHeap [773e0000+32be0+2e]
5e092e2b: MSVCR90!unlock [5e070000+22e16+15]
5e0d67ab: MSVCR90!realloc [5e070000+66415+396]
00525194: WinMain@16() [00400000+12517e+16]
006836ee: __tmainCRTStartup() [00400000+2835ae+140]
7744568e: ntdll!RtlUnicodeStringToInteger [773e0000+65470+21e]

Static log:
StepMania v5.0 beta 3
Compiled 20151224 @ 08:41:45 Hora estándar de Argentina (build 7)
Log starting 2015-12-24 16:17:52
Loading window: win32
Windows 6.2 (Win8) build 9200 []
Memory: 2047mb total, 4095mb swap (4095mb swap avail)
Video driver: Intel(R) HD Graphics 4600 [Intel Corporation]
              10.18.15.4256, 7-17-2015 [pci\ven_8086&dev_0416&subsys_14ad1043]
Drive: "TSSTcorpDVDWBD SN-406AB AS02" Driver: iaStorA DMA: N/A
Drive: "ST1000LMST1000LM024 HN-M2BA3" Driver: iaStorA DMA: N/A
Sound device 0: Altavoces (Realtek High Definit, 10.0, MID 1, PID 100 
Sound device 1: Realtek Digital Output (Realtek, 10.0, MID 1, PID 100 
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'd3d,opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 1, 640, 480, 16, 0, 1 )
D3D Windowed 640x480 16 color 16 texture 60Hz Vsync NoSmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Teclado" Product Name: "Teclado"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 2 DirectInput devices:
   0: 'Teclado' axes: 0, hats: 0, buttons: 256 (buffered)
   1: 'Mouse' axes: 3, hats: 0, buttons: 8 (buffered)
Players joined: none
Language: es
Current renderer: Direct3D
Theme: Fiesta 2

Partial log:
00:04.223: RageBitmapTexture: Loaded '/Themes/Fiesta 2/Fonts/USB 12x3.png' (128x64); RGBA4, source 120,36;  image 120,36.
00:04.227: RageBitmapTexture: Loaded '/Themes/Fiesta 2/Graphics/Levels/Levels 10x10.png' (256x256); RGBA4, source 140,160;  image 140,160.
00:04.248: RageBitmapTexture: Loaded '/Themes/_fallback/Fonts/_open sans book 24px [main] 15x15.png' (512x1024); RGBA4, source 480,540;  image 480,540.
00:04.248: Loaded "ScreenSystemLayer" ("ScreenSystemLayer") in 0.070000
00:04.248: Loading screen: "ScreenSyncOverlay"
00:04.249: Loaded "ScreenSyncOverlay" ("ScreenSyncOverlay") in 0.001000
00:04.249: Loading screen: "ScreenStatsOverlay"
00:04.250: Loaded "ScreenStatsOverlay" ("ScreenStatsOverlay") in 0.001000
00:04.250: Loading screen: "ScreenDebugOverlay"
00:04.254: Loaded "ScreenDebugOverlay" ("ScreenDebugOverlay") in 0.004000

-- End of report

**Comment by wolfman2000** [comment]
This is for StepMania, not Step F2. Furthermore, we don't support older versions.

Come back when you have an issue with a recent version of StepMania.
