### ISSUE TITLE
How can I use my usb adapted wii dance pad for stepmania

### ISSUE THREAD

**Issue by GingerAle27** [stepmania/stepmania#972]
I connected the adapter and the wii dance pad. All the drivers were installed automatically and then when I tried setting the keys for each button in the options, it wouldn't do anything. Its like it didn't recognize the dance pad.

**Comment by SoonDead** [comment]
I would go to options -> test input to see if anything shows up while pressing buttons on the pad.

If nothing shows up then I would fiddle around with drivers and software like joytokey to map the inputs to something that windows recognises.

**Comment by concubidated** [comment]
@SoonDead provided an excellent answer. Gunna close out, @GingerAle27 if still having issues with key2joy please reopen.
