### ISSUE TITLE
Some scores aren't saved

### ISSUE THREAD

**Issue by burnmyshadow** [stepmania/stepmania#993]
Installed fresh 5.1.0 version, put modded ultralight theme, put my old profile, played game as normal. After passing some songs have this:

![2016-01-18_221439](https://cloud.githubusercontent.com/assets/16764894/12400544/c70d331c-be31-11e5-9b53-527183f6f244.jpg)

This happens in any theme. Tried turning Save Scores ON and OFF, reloaded songs, restared stepmania a couple of times, changed to my old profile, same thing. Most song scores are saving but sometimes I have this problem and it is irritating. Profiles are from older version of stepmania, like 5.0.4 or so. The song is from Yolomania vol.4 pack. Any help how to fix this?

**Comment by kyzentun** [comment]
Does that song have stops or BPM changes in it?  Do you have the Disqualification preference turned on?  If Disqualification is turned on and you use a Cmod on a song that has stops or BPM changes, your score is disqualified because the Cmod makes it easier to score high.

**Comment by burnmyshadow** [comment]
Turned Disqualification OFF, it helped thanks. Though, I don't really know if there really were stops:
![screenshot_1](https://cloud.githubusercontent.com/assets/16764894/12401566/56959d48-be38-11e5-8e2b-6ead600d9e32.png)
Anyway thanks for the help!

**Comment by kyzentun** [comment]
That screenshot shows several bpm changes, so that's the reason you were being disqualified.  Going to close this issue since it's not really a bug, just a misunderstanding.

**Comment by SpoOkyMagician** [comment]
Ah, so that's why I could never get some scores...
